local stations = {
    {name = "Abradio Chillout", url = "http://mp3stream4.abradio.cz/chillout128.mp3"},
    {name = "Český Impuls", url = "http://icecast6.play.cz/cesky-impuls.mp3"},
    {name = "Český Rozhlas BRNO", url = "https://rozhlas.stream/brno_mp3_128.mp3"},
    {name = "Český Rozhlas České Budějovice", url = "https://rozhlas.stream/ceske_budejovice_high.aac"},
    {name = "Cesky Rozhlas Classical Lossless FLAC Stream", url = "http://amp.cesnet.cz:8000/cro-d-dur.flac"},
    {name = "Cesky Rozhlas D-Dur", url = "http://amp.cesnet.cz:8000/cro-d-dur-256.ogg"},
    {name = "Cesky Rozhlas Jazz", url = "https://rozhlas.stream/jazz_high.aac"},
    {name = "Cesky Rozhlas Jazz Lossless FLAC Stream", url = "http://amp.cesnet.cz:8000/cro-jazz.flac"},
    {name = "Český Rozhlas Rádio Junior", url = "http://icecast1.play.cz/xnostream.mp3"},
    {name = "Český Rozhlas ZLÍN", url = "https://rozhlas.stream/zlin_mp3_128.mp3"},
    {name = "City FM", url = "http://ice.abradio.cz/cityfm128.mp3"},
    {name = "City Milenium", url = "http://ice.abradio.cz:8000/citymi128.mp3"},
    {name = "Classic Praha", url = "http://icecast8.play.cz/classic128.mp3"},
    {name = "COLOR Music Radio", url = "https://icecast8.play.cz/color128.mp3"},
    {name = "COOP TIP Radio", url = "http://mp3stream4.abradio.cz:8000/coop128.mp3"},
    {name = "Country Radio", url = "http://icecast4.play.cz/country128.mp3"},
    {name = "County", url = "http://icecast4.play.cz/country128.mp3"},
    {name = "Čro D-Dur", url = "http://amp.cesnet.cz:8000/cro-d-dur.flac"},
    {name = "Čro D-Dur FLAC", url = "http://amp.cesnet.cz:8000/cro-d-dur.flac"},
    {name = "Čro D-Dur HD", url = "http://amp.cesnet.cz:8000/cro-d-dur-256.ogg"},
    {name = "Čro Dvojka", url = "http://icecast1.play.cz:8000/cro2-32aac"},
    {name = "Čro Jazz", url = "http://amp.cesnet.cz:8000/cro-jazz.flac"},
    {name = "ČRO Jazz 256", url = "https://rozhlas.stream/jazz_mp3_256.mp3"},
    {name = "Čro Olomouc", url = "https://rozhlas.stream/olomouc_low.aac"},
    {name = "Čro Ostrava", url = "https://rozhlas.stream/ostrava_high.aac"},
    {name = "Čro Plus", url = "http://amp.cesnet.cz:8000/cro-plus-256.ogg"},
    {name = "Čro Pohoda", url = "https://rozhlas.stream/pohoda_mp3_128.mp3"},
    {name = "Čro Rádio Junior", url = "http://icecast3.play.cz:8000/crojuniormaxi32aac"},
    {name = "Čro Radio Wave", url = "http://amp.cesnet.cz:8000/cro-radio-wave-256.ogg"},
    {name = "Čro Radiožurnál", url = "http://icecast1.play.cz:8000/cro132aac"},
    {name = "Cro Radiozurnal", url = "https://rozhlas.stream/radiozurnal_aac_128.aac"},
    {name = "ČRO Radiožurnál Sport", url = "https://rozhlas.stream/radiozurnal_sport_high.aac"},
    {name = "Čro Radiožurnál Sport Adhoc Stream 1", url = "https://rozhlas.stream/radiozurnal_sport_adhoc_1_high.mp3"},
    {name = "ČRO Radiožurnál Sport Adhoc Stream 2", url = "https://rozhlas.stream/radiozurnal_sport_adhoc_2_high.mp3"},
    {name = "Čro Radiožurnál Sport Stream Adhoc 2", url = "https://rozhlas.stream/radiozurnal_sport_adhoc_2_high.mp3"},
    {name = "Čro Sever", url = "https://rozhlas.stream/sever_mp3_128.mp3"},
    {name = "Čro Vltava", url = "http://icecast2.play.cz:8000/cro3-32aac"},
    {name = "Cro Vysocina", url = "https://rozhlas.stream/vysocina_high.aac"},
    {name = "Čro Wave", url = "https://rozhlas.stream/wave_mp3_128.mp3"},
    {name = "Czech Radio Classical", url = "http://amp.cesnet.cz:8000/cro-d-dur.flac"},
    {name = "Czech Radio Čro D-Dur", url = "http://amp.cesnet.cz:8000/cro-d-dur.flac"},
    {name = "Dance Club FM", url = "http://mp3stream4.abradio.cz/dance128.mp3"},
    {name = "Dance Club Radio", url = "https://ice4.abradio.cz/dance128.mp3"},
    {name = "Dance Radio", url = "http://ice.actve.net/dance-radio320.mp3"},
    {name = "Dance Rádio Cz", url = "https://ice.actve.net/dance-radio128.mp3"},
    {name = "Dandy Radio", url = "http://88.99.25.114:8022/stream"},
    {name = "ELLIS", url = "http://ellis.stream.laut.fm/ellis?t302=2024-08-26_17-34-41&uuid=19c7d309-b2ad-4451-bf77-f08e8e4e2b9c"},
    {name = "Evropa 2 - Aac", url = "https://23613.live.streamtheworld.com:443/EVROPA2AAC.aac"},
    {name = "Evropa 2 - Actve", url = "https://ice.actve.net/fm-evropa2-128"},
    {name = "Evropa 2 - Mp3", url = "https://23543.live.streamtheworld.com:443/EVROPA2.mp3"},
    {name = "Evropa 2 - Radio", url = "https://ice.actve.net/fm-evropa2-128"},
    {name = "Evropa2 Youradio Flashbacky", url = "https://ice.actve.net/web-e2-flashback"},
    {name = "Expres FM", url = "http://icecast8.play.cz/expres128mp3"},
    {name = "Expresradio", url = "http://icecast5.play.cz:8000/expres128mp3"},
    {name = "Express FM", url = "http://icecast8.play.cz/expres128mp3"},
    {name = "Fajn Fresh", url = "http://ice.abradio.cz/fajnfresh128.mp3"},
    {name = "Fajn Fresh Radio", url = "http://mp3stream4.abradio.cz/fajnfresh64.mp3"},
    {name = "Fajn Rádio", url = "http://ice.abradio.cz/fajn128.mp3"},
    {name = "Flash Radio", url = "http://185.47.222.75:8750/"},
    {name = "Free Rave CZ", url = "http://164.68.122.137:8061/"},
    {name = "Frekvence 1", url = "http://ice.actve.net/fm-frekvence1-aac"},
    {name = "Frekvence 1 - Youradio Československé Hity", url = "http://ice.actve.net/web-e2-csweb"},
    {name = "Frekvence 1 - Youradio Legendy", url = "http://ice.actve.net/web-f1-legendy"},
    {name = "Frekvence 1 - Youradio Osmdesátky", url = "http://ice.actve.net/web-80"},
    {name = "Funkstar Radio", url = "https://funkstar.radioca.st/stream"},
    {name = "Haná", url = "http://icecast8.play.cz/hana128.mp3"},
    {name = "HEY Rádio", url = "http://icecast3.play.cz/hey-radio128.mp3"},
    {name = "Hit FM Plus", url = "http://ice.abradio.cz:8000/fmplus64.aac"},
    {name = "Hit Poprock", url = "http://ice.abradio.cz/hitpoprock128.mp3"},
    {name = "HIT Rádio Orion", url = "http://ice.abradio.cz/orion128.mp3"},
    {name = "Hitrádio Černá Hora", url = "http://ice.abradio.cz/cernahora64.mp3"},
    {name = "Hitrádio Černá Hora 128", url = "http://ice.abradio.cz/cernahora128.mp3"},
    {name = "Hitrádio City Brno", url = "http://ice.abradio.cz/magicbrno128.mp3"},
    {name = "Hitradio City Zona Lasky", url = "http://ice.abradio.cz/cityzl128.mp3"},
    {name = "Hitrádio Contact", url = "https://ice3.abradio.cz/hitradiocontact128.mp3"},
    {name = "Hitrádio Devadesátka", url = "http://ice.abradio.cz/hit90128.mp3"},
    {name = "Hitrádio Faktor", url = "https://ice.abradio.cz/faktor128.mp3"},
    {name = "Hitrádio FM", url = "http://ice.abradio.cz/hitradiofm128.mp3"},
    {name = "Hitrádio FM Crystal", url = "http://ice.abradio.cz/crystal128.mp3"},
    {name = "Hitrádio Osmdesátka", url = "http://ice.abradio.cz/hit80128.mp3"},
    {name = "Hitrádio Poprock", url = "http://ice.abradio.cz/hitpoprock128.mp3"},
    {name = "Hitrádio Vysočina", url = "http://ice5.abradio.cz/hitvysocina128.mp3"},
    {name = "Impuls", url = "http://icecast1.play.cz/impuls128.mp3"},
    {name = "Impuls Ráááádio", url = "http://icecast5.play.cz/impuls128.mp3"},
    {name = "Jasrádio News Service", url = "https://radio.plainrock127.xyz/listen/jasns/radio.mp3"},
    {name = "JČ1 - Televize Jižní Čechy", url = "https://stream.jc1.cz/hls/jc1.m3u8"},
    {name = "Kiss 98 FM", url = "http://icecast2.play.cz:8000/kiss128aac"},
    {name = "Kiss Delta", url = "http://icecast1.play.cz:8000/kissdelta192.mp3"},
    {name = "Kiss Hady", url = "http://icecast8.play.cz/kisshady128.mp3"},
    {name = "Kiss Publikum", url = "http://icecast1.play.cz:8000/kisspublikum128aac"},
    {name = "Kiss Radio", url = "http://icecast4.play.cz/kiss128.mp3"},
    {name = "LA RADIO PLUS ANNECY", url = "https://laradioplus.ice.infomaniak.ch/laradioplus-high.aac?i=96970"},
    {name = "Metal Heart", url = "http://fr.radio-streamhosting.com:8000/metalheartradio64aac"},
    {name = "Metal Heart Radio", url = "https://cz.radio-streamhosting.com:8443/metalheartradio128mp3"},
    {name = "Metalománie", url = "http://ice.abradio.cz/metalomanie128.mp3"},
    {name = "Mňau TV", url = "https://5ca49f2417d90.streamlock.net/mnau/livestream/playlist.m3u8"},
    {name = "Óčko", url = "http://ocko-live.ssl.cdn.cra.cz/channels/ocko/playlist/cze/live_lq.m3u8"},
    {name = "Óčko Expres", url = "http://ocko-live.ssl.cdn.cra.cz/channels/ocko_expres/playlist/cze/live_lq.m3u8"},
    {name = "Óčko Star", url = "https://ocko-live-dash.ssl.cdn.cra.cz/cra_live2/ocko_gold.stream.1.smil/playlist.m3u8"},
    {name = "OIK TV", url = "https://streamer05.low-latency.cz/oiktv/index.m3u8"},
    {name = "Oldies Rádio", url = "http://ice.abradio.cz/oldiesradio128.mp3"},
    {name = "Phonk Nation Radio", url = "https://radio.plainrock127.xyz/phonk/stream"},
    {name = "PHONK RADIO", url = "https://stream-156.zeno.fm/90fvpb27u18uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5MGZ2cGIyN3UxOHV2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlV3NlgybGZKUlFPTDA1b0p0Z0dzeUEiLCJpYXQiOjE3MjQ2NjAxNDYsImV4cCI6MTcyNDY2MDIwNn0.4kLiQV-m35W39DvF0ezCTSiO65gQdr7YVV1ejVwm8XY"},
    {name = "Plzeň TV", url = "https://vysilani.zaktv.cz/broadcast/hls/ptv/index.m3u8"},
    {name = "Povídka", url = "https://ice3.abradio.cz/povidka128.mp3"},
    {name = "Radia CZ - Depeche Mode", url = "http://mp3stream4.abradio.cz/depeche128.mp3"},
    {name = "Rádio 1", url = "http://icecast6.play.cz/radio1-128.mp3"},
    {name = "RADIO 1", url = "http://icecast2.play.cz/radio1.mp3"},
    {name = "Radio 4U", url = "http://mpc1.mediacp.eu:8342/stream"},
    {name = "Rádio 7", url = "http://icecast8.play.cz/radio7-128.mp3"},
    {name = "Rádio 7 32Kb", url = "http://icecast1.play.cz:8000/radio7cz32.mp3"},
    {name = "Rádio Applaus", url = "http://mp3stream3.abradio.cz/applaus128.mp3"},
    {name = "Radio B", url = "http://n01.radiojar.com/9nayamd31tzuv?1660328034=&rj-tok=AAABkY97GyEAfby4xVyNIfyCMw&rj-ttl=5"},
    {name = "Rádio Beat", url = "http://icecast2.play.cz/radiobeat128.mp3"},
    {name = "Radio Beat", url = "http://icecast2.play.cz/radiobeat128.mp3"},
    {name = "Radio Beat 128 MP3", url = "http://icecast2.play.cz/radiobeat128.mp3"},
    {name = "Rádio Blaník", url = "https://20133.live.streamtheworld.com:443/RADIO_BLANIK_128.mp3"},
    {name = "Rádio Blaník CZ Webové Rádio", url = "http://ice.abradio.cz/blanikcz128.mp3"},
    {name = "Radio Blaník Morava A Slezsko", url = "https://ice.abradio.cz/blanikmorava128.mp3?gdpr=1&gdpr_consent=Q084aEUyaE84aEUyaEFjQUJCRU5BX0NnQVBfQUFIX0FBQVlnRjVvQmhEeEVCU0ZDQUdKb1lOa2dBQUFXeHdBQUFDQUNBQUFBb0FBQUFCb0FBQVFBQUFBQUFBQWdCQUFBQUJJQUlBSUFBQUJBR0VBQUFBQUFBQUFBQUFBQUFFQUFBQUFBSVFBQUFBQUFBQ0JBQUFBQUFBQUFBQUFBQUFBQVFBQUFnWG5BZUFBV0FCVUFDNEFIQUFRQUFxQUJvQURrQUlnQVRBQW5nQlZBQzRBRjhBTVFBaElCRUFFVUFLVUFXSUF5d0Jtd0R1QU84QWhBQkZnQzBnRjFBTUNBYXdCTm9DOHdBQUFBLllBQUFBQUFBQUFBQQ=="},
    {name = "Rádio Blaník Oldies", url = "https://ice.radia.cz/oldiesradio128.mp3"},
    {name = "Rádio Blaník Živé", url = "http://ice.abradio.cz/blanikfm128.mp3"},
    {name = "Rádio Bonton", url = "http://ice.actve.net/fm-bonton-128"},
    {name = "Radio Budweis", url = "https://rozhlas.stream/ceske_budejovice_high.aac"},
    {name = "Radio Cas", url = "http://icecast6.play.cz/casradio128.mp3"},
    {name = "Radio Čas", url = "http://icecast6.play.cz/casradio128.mp3"},
    {name = "Radio Cas Rock", url = "http://icecast6.play.cz/casrock128.mp3"},
    {name = "Radio Čas Rock", url = "http://icecast6.play.cz/casrock128.mp3"},
    {name = "Radio City FM", url = "http://ice.abradio.cz/cityfm128.mp3"},
    {name = "Rádio Dálnice", url = "http://icecast8.play.cz/radiodalnice.mp3"},
    {name = "Radio Dechovka", url = "http://icecast5.play.cz/dechovka128.mp3"},
    {name = "Radio Dechovka 1233 Stredni Vlny", url = "http://icecast5.play.cz/dechovka128.mp3"},
    {name = "Radio Depeche Mode", url = "http://mp3stream4.abradio.cz/depeche128.mp3"},
    {name = "Radio Dixie", url = "http://icecast8.play.cz/radiodixie192.mp3"},
    {name = "Rádio Dráťák", url = "http://dratak.cz:8000/dratak"},
    {name = "Rádio Energic", url = "https://icecast9.play.cz/energic.mp3"},
    {name = "Rádio Folk Czech", url = "http://mp3stream2.abradio.cz:8000/folk320.mp3"},
    {name = "Rádio Hády", url = "http://46.36.36.149:8000/live"},
    {name = "Radio Helax", url = "http://ice.abradio.cz:8000/helax128.mp3?type=.mp3/;stream.mp3"},
    {name = "Radio Humor", url = "http://mp3stream4.abradio.cz:8000/humor128.mp3"},
    {name = "Rádio Humor 2", url = "https://25653.live.streamtheworld.com:443/RADIO_HUMOR.aac"},
    {name = "Rádio Jih", url = "https://icecast6.play.cz/jih32.mp3"},
    {name = "Radio JIH Cimbalka", url = "http://icecast6.play.cz/jihcimbalka128.mp3"},
    {name = "Rádio Junior", url = "http://amp.cesnet.cz:8000/cro-radio-junior-256.ogg"},
    {name = "Radio Kiss", url = "http://icecast4.play.cz/kiss128.mp3"},
    {name = "Radio Krokodyl", url = "http://icecast-u2.play.cz:8000/krokodyl128.mp3"},
    {name = "Rádio MB", url = "http://icecast3.play.cz/radiomb.mp3"},
    {name = "Rádio Music CZ", url = "https://mpc1.mediacp.eu/stream/radiomusiccz"},
    {name = "Radio Orlicko", url = "http://46.28.111.246/stream192.mp3"},
    {name = "Radio Ostravan", url = "http://icecast9.play.cz/radio-ostravan-256.mp3"},
    {name = "Radio Otava", url = "https://radiootava.trefcon.cz:8889/radio.mp3"},
    {name = "Rádio Pohádka", url = "http://ice3.abradio.cz/pohadka128.mp3"},
    {name = "Radio Ponte Records", url = "http://ice3.abradio.cz/ponterec128.mp3"},
    {name = "Radio Prague International", url = "https://rozhlas.stream/radio_prague_int_high.aac"},
    {name = "Radio Praha", url = "http://icecast2.play.cz/cro7-128.mp3"},
    {name = "Radio Proglas", url = "http://icecast2.play.cz/proglas128"},
    {name = "Radio Prostor", url = "https://bcast.spmmedia.cz/prostor-mp3"},
    {name = "Radio Punctum", url = "https://radiopunctum.cz:8001/radio"},
    {name = "Radio R", url = "https://radior.video.muni.cz:8000/FSS_mp3-128.mp3"},
    {name = "Rádio Relax", url = "http://icecast7.play.cz/relax128.mp3"},
    {name = "Radio ROCK", url = "http://ice.abradio.cz/rockradio128.mp3"},
    {name = "Rádio Samson", url = "http://icecast8.play.cz/samsonfm128.mp3"},
    {name = "Radio Sázava", url = "http://sc.ipip.cz:8224/;stream"},
    {name = "Radio Slobodna Evropa", url = "https://n02.radiojar.com/bugesa4nn3quv?rj-ttl=5&rj-tok=AAABkY_uQN4ArEO-NRkcy5uwtQ"},
    {name = "Radio Svoboda", url = "https://rfe-ingest.akamaized.net/hls/live/2035254/axia04/playlist.m3u8"},
    {name = "Radio Svoboda Rus", url = "http://n0d.radiojar.com/hcrb063nn3quv?rj-ttl=5&rj-tok=AAABkY80zCkAwWYeUTSq4Pfo8Q"},
    {name = "Rádio Trojka", url = "http://12901.cloudrad.io:9306/live"},
    {name = "Radio Wave", url = "https://rozhlas.stream/wave_aac_32.aac"},
    {name = "Rádio Xaver", url = "https://icecast6.play.cz/radio-xaver.aac"},
    {name = "RADIO1", url = "http://icecast2.play.cz/radio1-64.mp3"},
    {name = "RETRO DJ RADIO - 128", url = "https://free.rcast.net/70814"},
    {name = "RETRO DJ Radio - HQ", url = "http://icecast1.play.cz/retrodjradio.mp3"},
    {name = "RETRO DJ RADIO CZ", url = "https://free.rcast.net/70814.mp3"},
    {name = "Retro Music Television", url = "http://stream.mediawork.cz/retrotv/retrotvHQ1/playlist.m3u8"},
    {name = "Retro Music TV", url = "http://stream.mediawork.cz/retrotv/retrotvHQ1/chunklist_w627639048.m3u8"},
    {name = "ROCK MAX", url = "http://ice.abradio.cz/rockmax256.mp3"},
    {name = "Rock Radio", url = "https://25593.live.streamtheworld.com:443/ROCK_RADIO_128.mp3"},
    {name = "Rock Rádio Šumava", url = "http://ice.abradio.cz/sumava128.mp3"},
    {name = "Rocková Zábava", url = "http://ice.abradio.cz/rockzabava128.mp3"},
    {name = "Rockzone", url = "http://icecast5.play.cz/rockzone128.mp3"},
    {name = "Samson", url = "http://icecast2.play.cz:8000/samsonfm128aac"},
    {name = "Seejay Radio", url = "http://icecast6.play.cz/seejay128.mp3"},
    {name = "Signál Rádio", url = "http://icecast1.play.cz/signal128.mp3"},
    {name = "Signál Rádio Brno", url = "http://icecast6.play.cz/signal-brno128.mp3"},
    {name = "SKYROCK", url = "http://icecast8.play.cz/skyrock128.mp3"},
    {name = "Svobodne-Radio", url = "http://svobodneradio.radioca.st:8859/stream"},
    {name = "Svobodný Vysílač", url = "http://stream.svobodny-vysilac.cz:8000/live.ogg"},
    {name = "United Czech Chillers", url = "https://chill.mfnet.cz/radio/8000/radio192.mp3"},
    {name = "Webradio Epigon", url = "http://ice3.abradio.cz/epigon128.mp3"},
    {name = "Wehouseradio", url = "https://icecast9.play.cz/zun192.mp3"},
    {name = "Známka Punku", url = "https://ice.abradio.cz/znamkapunku128.mp3"},
    {name = "Zoner Underground Network", url = "https://stream.zunradio.cz/zun3.mp3"},
    {name = "ZX Music Radio", url = "http://zxm.cz:8000/zx"},
    {name = "Радио Свобода", url = "https://rfe-ingest.akamaized.net/hls/live/2035254/axia04/playlist.m3u8"},
    {name = "Свобода", url = "https://rfe-ingest.akamaized.net/hls/live/2035254/axia04/playlist.m3u8"},
}

return stations
