local stations = {
    {name = "Aktív Rádió", url = "http://aktivradio.hu:8000/aktiv.mp3"},
    {name = "Argentine Tango Radio", url = "https://ais-edge94-nyc04.cdnstream.com/2202_128.mp3"},
    {name = "Balaton Rádió", url = "http://91.82.85.41:8200/;"},
    {name = "Balatonica", url = "http://balatonica.hu:8000/stream_low"},
    {name = "BALATONICA RADIO", url = "http://balatonica.hu:8000/stream_high"},
    {name = "Bartók Rádió", url = "http://mr-stream.mediaconnect.hu/4742/mr3hq.mp3"},
    {name = "Base FM", url = "https://icast.connectmedia.hu/5401/live.mp3"},
    {name = "BDPST ROCK", url = "http://s2.audiostream.hu/bdpstrock_FLAC"},
    {name = "Best FM", url = "http://stream.webthings.hu:8000/fm95-x-128.mp3"},
    {name = "Best FM - Budapest", url = "https://icast.connectmedia.hu/5101/live.mp3/;"},
    {name = "Best FM - Debrecen", url = "http://stream.webthings.hu:8000/fm95-x-128.mp3"},
    {name = "Best FM - Eger", url = "https://icast.connectmedia.hu/5116/live.mp3"},
    {name = "Best FM - Nyíregyháza", url = "https://icast.connectmedia.hu/5115/live.mp3"},
    {name = "Best FM - Pécs", url = "https://icast.connectmedia.hu/5128/live.mp3"},
    {name = "Best FM - Székesfehérvár", url = "http://icast.connectmedia.hu/5113/live.mp3"},
    {name = "Best FM - Szolnok", url = "http://icast.connectmedia.hu/5112/live.mp3/;"},
    {name = "Best FM - Zalaegerszeg", url = "http://icast.connectmedia.hu/5111/live.mp3/;"},
    {name = "Best Of Rádió", url = "http://45.67.156.157:18000/bestofradio_hq"},
    {name = "Bias Radio", url = "https://admin.biasradio.com/listen/bias_radio/live"},
    {name = "Bithang Yoo Rádió", url = "http://stream.diazol.hu:35160/live.mp3"},
    {name = "Buddha FM", url = "http://libretime.buddhafm.hu:4000/buddhafm"},
    {name = "Callisto", url = "http://188.165.11.30:4500/live.mp3"},
    {name = "Callisto Radio", url = "http://adas.poptarisznya.hu:4500/live.mp3"},
    {name = "Campus Rádió FM90", url = "https://stream.fm90.hu:8000/;"},
    {name = "Cegléd Rádió", url = "http://stream.cegledradio.hu:4387/mp3"},
    {name = "CEU Medieval Radio", url = "http://137.74.85.85:7020/;stream"},
    {name = "Chiqui", url = "http://ia800307.us.archive.org/28/items/my-produced-tracks/Francis%20Viner%20Feat%20Chiqui%20-%20When%20Nature%20Calls.mp3"},
    {name = "Civil Radio", url = "http://civilradio.hu:8000/listen.mp3"},
    {name = "Civil Rádió", url = "http://civilradio.hu:8000/;stream"},
    {name = "Club Dance Online", url = "http://stream.clubdance.online:8000/live.mp3"},
    {name = "Club Dance Online - Retro", url = "http://stream.clubdance.online:8000/retro"},
    {name = "Cool FM", url = "http://mediagw.e-tiger.net/stream/cfmhq"},
    {name = "Cool FM - Kultx", url = "http://mediagw.e-tiger.net/stream/krehq"},
    {name = "Cool FM - Xbeat", url = "http://mediagw.e-tiger.net/stream/xbeathq"},
    {name = "COOLFM 2000-Es Évek", url = "https://mediagw.e-tiger.net/stream/zc03"},
    {name = "COOLFM 2010-Es Évek", url = "https://mediagw.e-tiger.net/stream/zc02"},
    {name = "COOLFM 90-Es Évek", url = "https://mediagw.e-tiger.net/stream/zc05"},
    {name = "COOLFM Acoustic", url = "https://mediagw.e-tiger.net/stream/zc12"},
    {name = "COOLFM Best Hits EVER", url = "https://mediagw.e-tiger.net/stream/zc11"},
    {name = "COOLFM Chill", url = "https://mediagw.e-tiger.net/stream/zc24"},
    {name = "COOLFM Country", url = "http://mediagw.viacomkft.hu:8000/stream/zc17"},
    {name = "COOLFM Filmzenék", url = "https://mediagw.e-tiger.net/stream/zc01?ver=753658"},
    {name = "COOLFM Hazai Kedvencek", url = "https://mediagw.e-tiger.net/stream/zc19"},
    {name = "COOLFM Jazz", url = "https://mediagw.e-tiger.net/stream/zc13"},
    {name = "COOLFM Karácsonyi Dalok", url = "https://mediagw.e-tiger.net/stream/zc27"},
    {name = "COOLFM Love Songs", url = "https://mediagw.e-tiger.net/stream/zc28"},
    {name = "COOLFM Nyári Slágerek", url = "https://mediagw.e-tiger.net/stream/zc09"},
    {name = "COOLFM Party", url = "https://mediagw.e-tiger.net/stream/zc18"},
    {name = "COOLFM Sportoláshoz", url = "https://mediagw.e-tiger.net/stream/zc20"},
    {name = "COOLFM World Music", url = "https://mediagw.e-tiger.net/stream/zc26"},
    {name = "Coronita Fm", url = "http://stream-176.zeno.fm/ktzdc7rf7f0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJrdHpkYzdyZjdmMHV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ijd4S2laWkxqUVNLUHJZS292SWNwLXciLCJpYXQiOjE3MjQ2ODgwNzQsImV4cCI6MTcyNDY4ODEzNH0.fxjqvHjDE8HpChQXZU9TmzdzOtJg_UyiJFEANATQXMM"},
    {name = "Csillagpont Rádió", url = "http://streamer1.borsodweb.hu:48000/csillagpont"},
    {name = "Danceable Radio", url = "http://176.31.244.83:35944/;"},
    {name = "Dankó Rádió", url = "http://mr-stream.mediaconnect.hu/4747/mr7.aac"},
    {name = "Danubius", url = "https://stream.danubiusradio.hu/danubius_320k"},
    {name = "Danubius Rádió", url = "https://stream.danubiusradio.hu/danubius_192k"},
    {name = "Danubius Radio", url = "http://stream.danubiusradio.hu:8091/danubius_HiFi"},
    {name = "Disco Diamond 2", url = "http://discodiamond.radioca.st/stream"},
    {name = "Disco Diamond Radio", url = "https://ddr2020.radioca.st/stream"},
    {name = "Diveky-Radio-Gramofon", url = "http://178.238.223.39:8000/gramofon"},
    {name = "Diveky-Radio-Klasszikusok", url = "http://178.238.223.39:8000/klasszikusok"},
    {name = "Diveky-Radio-Könnyűzene", url = "http://178.238.223.39:8000/konnyuzene"},
    {name = "Diveky-Radio-Madeinhungary", url = "http://178.238.223.39:8000/madeinhungary"},
    {name = "Diveky-Radio-Swing", url = "http://178.238.223.39:8000/swing"},
    {name = "Diveky-Radio-Táncdalok", url = "http://178.238.223.39:8000/tancdalok"},
    {name = "Dombrádió-Online-Dombrád", url = "http://dombradio.dyndns.tv:8000/live.mp3"},
    {name = "Duna World Rádió", url = "http://mr-stream.mediaconnect.hu/4760/dwr.aac"},
    {name = "Első Pesti Egyetemi Rádió", url = "http://radio.elte.hu:8000/eper97"},
    {name = "Enying FM Hungary", url = "http://radioe.net:8080/efm_hd"},
    {name = "Euro Music Radio", url = "https://a1.asurahosting.com:9480/radio.mp3"},
    {name = "FM90 Campus Rádió", url = "http://stream.fm90.hu:8000/;"},
    {name = "Folkrádio", url = "https://stream.folkradio.hu/folkradio.mp3"},
    {name = "Folkrádió", url = "https://stream.folkradio.hu/folkradio.mp3"},
    {name = "Forrás Rádió", url = "http://91.82.85.44:9000/;stream"},
    {name = "Forrás Radio", url = "http://91.82.85.44:1630/forrasradio.mp3"},
    {name = "Gong Rádió", url = "http://stream.gongradio.hu:8000/gong-fm.mp3"},
    {name = "Hobby Rádió", url = "http://www.hobbyradio.hu:8000/hobbyradio.mp3"},
    {name = "Hujujuj", url = "http://radionova.hujujuj.com:8000/main"},
    {name = "Hungarian Dance", url = "http://gamershouse.hu:8000/livemega.mp3"},
    {name = "I Love Pécs Rádió", url = "http://radio.ilovepecs.hu:8200/ilp.mp3"},
    {name = "Inforádió", url = "http://stream.infostart.hu/lejatszo/index.html?sid=1"},
    {name = "Insane", url = "https://newinsane.info/broadcast/;stream/1"},
    {name = "Jazzy", url = "https://radio.musorok.org/listen/jazzy/jazzy.mp3"},
    {name = "Jazzy Cool", url = "https://radio.musorok.org/listen/jazzycool/jazzycool.mp3"},
    {name = "Jazzy Groove", url = "https://radio.musorok.org/listen/jazzygroove/jazzygroove.mp3"},
    {name = "Jazzy Soul", url = "https://radio.musorok.org/listen/jazzysoul/jazzysoul.mp3"},
    {name = "Klubrádió - Zebrádió", url = "https://stream.zebradio.hu:8443/zebradio"},
    {name = "Koronafm100", url = "http://82.141.165.6:8000/;stream"},
    {name = "Kossuth", url = "https://icast.connectmedia.hu/4736/mr1.mp3"},
    {name = "Kossuth Radio", url = "http://stream002.radio.hu/mr1.mp3"},
    {name = "Kossuth Rádió", url = "http://mr-stream.mediaconnect.hu/4734/mr1.aac"},
    {name = "Lahmacun Radio", url = "https://streaming.lahmacun.hu/radio/8000/radio.mp3"},
    {name = "Lakihegy Rádió", url = "http://lakihegyradio.hu/player/stream.php"},
    {name = "Lépés Rádió", url = "http://stream.lepesradio.hu:4000/live.mp3"},
    {name = "Live Radio", url = "http://radio.nnkcrazyclub.hu:7163/crazyklub"},
    {name = "Luxfunk Blackmix", url = "http://188.165.11.30:5000/luxfunkblackmix.mp3"},
    {name = "Luxfunk Dance", url = "http://188.165.11.30:5000/luxfunkdance.mp3"},
    {name = "Luxfunk Radio", url = "http://188.165.11.30:5000/luxfunkradio.mp3"},
    {name = "Magic Disco", url = "http://stream1.virtualisan.net:4420/live.mp3"},
    {name = "Magic Disco Radio", url = "https://free.rcast.net/66407"},
    {name = "Magic Disco Rádió", url = "http://live2.magicdiscoradio.com:4420/live.mp3"},
    {name = "Magyar Katolikus Rádió", url = "http://katolikusradio.hu:9000/live_hi.mp3"},
    {name = "Mária Rádió", url = "http://honlap.mariaradio.hu:8000/mr"},
    {name = "Maxi Rádió", url = "http://46.107.212.101:9240/live"},
    {name = "Megadance Rádió", url = "http://megadanceradio.hopto.org:8000/livemega.mp3"},
    {name = "Megalive", url = "https://mega-live.net:2053/live.mp3"},
    {name = "Mera", url = "https://stream.radio.co/s3fd8d173f/listen"},
    {name = "Mercy Rádió", url = "http://stream.mercyradio.eu/mercyradio.mp3"},
    {name = "Mercy Rádió - Kabaré", url = "http://stream.mercyradio.eu/kabare.mp3"},
    {name = "Mercy Rádió - Mulatós", url = "http://stream.mercyradio.eu/mulatos.mp3"},
    {name = "Mixradio Fresh", url = "https://stream.phost.hu:8006/live"},
    {name = "Mixradioretro", url = "https://stream.phost.hu:8004/retro"},
    {name = "Momo Rádió", url = "https://s03.diazol.hu:7092/zene.mp3"},
    {name = "Momó Rádió", url = "https://stream.diazol.hu:7092/zene.mp3"},
    {name = "Momó Rádió Mese", url = "https://stream.diazol.hu:7092/mese.mp3"},
    {name = "MR1 - Kossuth Rádió", url = "https://mr-stream.connectmedia.hu/4736/mr1.mp3"},
    {name = "MR2 - Petőfi Rádió", url = "https://mr-stream.connectmedia.hu/4738/mr2.mp3"},
    {name = "MR3 - Bartók Rádió", url = "https://mr-stream.connectmedia.hu/4741/mr3.mp3"},
    {name = "MR4 - Nemzetiségi Adások", url = "https://mr-stream.connectmedia.hu/4744/mr4.mp3"},
    {name = "MR5 - Parlamenti Adások", url = "https://mr-stream.connectmedia.hu/4746/mr5.mp3"},
    {name = "MR7 - Dankó Rádió", url = "https://mr-stream.connectmedia.hu/4748/mr7.mp3"},
    {name = "MR8 - Duna World Rádió", url = "https://mr-stream.connectmedia.hu/4761/dwr.mp3"},
    {name = "Mustár Rádió", url = "http://193.138.125.14:8500/;"},
    {name = "Nemzeti Sportrádió", url = "https://icast.connectmedia.hu/4657/mr11.mp3"},
    {name = "Nemzetiségi Adások", url = "http://mr-stream.mediaconnect.hu/4743/mr4.aac"},
    {name = "Next FM", url = "https://stream.nextfm.hu/radio/8000/nextfmhu.mp3?1590416039"},
    {name = "Nóta FM - 128K MP3", url = "http://live.notafm.hu:8000/notafm.mp3"},
    {name = "NST Music FM", url = "http://212.84.160.3:9819/nstmusicfm"},
    {name = "Open Air Radio", url = "http://79.172.209.223:9200/stream;"},
    {name = "Oxigen", url = "https://oxygenmusic.hu:8443/oxygenmusic"},
    {name = "Oxygen Black Music", url = "https://oxygenmusic.hu:8443/blackmusic_128"},
    {name = "Oxygen Classic Rock", url = "https://oxygenmusic.hu:8443/oxygenclassicrock"},
    {name = "Oxygen Classics", url = "https://oxygenmusic.hu:8443/Classic_128"},
    {name = "Oxygen Fitness", url = "https://oxygenmusic.hu:8443/oxygenfitness"},
    {name = "Oxygen Happy", url = "https://oxygenmusic.hu:8443/oxygenhappy_128"},
    {name = "Oxygen Indie", url = "https://oxygenmusic.hu:8443/oxygenindie"},
    {name = "Oxygen Italo Hits", url = "https://oxygenmusic.hu:8443/oxygenitalohits"},
    {name = "Oxygen Kids", url = "https://oxygenmusic.hu:8443/oxygenkids"},
    {name = "Oxygen Lounge", url = "https://oxygenmusic.hu:8443/oxygenlounge"},
    {name = "OXYGEN LOVE SONGS", url = "https://oxygenmusic.hu:8443/oxygenlovesongs"},
    {name = "Oxygen Magyar Zene", url = "https://oxygenmusic.hu:8443/oxygenmagyarzene"},
    {name = "Oxygen Music", url = "https://oxygenmusic.hu:8443/oxygenmusic_192"},
    {name = "Oxygen Oldies", url = "https://oxygenmusic.hu:8443/oxygenoldies"},
    {name = "Oxygen Spencer-Hill", url = "https://oxygenmusic.hu:8443/oxygenspencerhillzenek"},
    {name = "Oxygen The 00S Hits", url = "https://oxygenmusic.hu:8443/oxygenthe00shits"},
    {name = "Oxygen The 80S Hits", url = "https://oxygenmusic.hu:8443/oxygenthe80shits"},
    {name = "Oxygen The 90S Hits", url = "https://oxygenmusic.hu:8443/oxygenthe90shits"},
    {name = "Ozone FM", url = "https://oxygenmusic.hu:8443/ozonefm_128.mp3"},
    {name = "Ozonefm", url = "https://oxygenmusic.hu:8443/ozonefm_320"},
    {name = "Pannónia Rádió", url = "http://kft.kesintisizyayin.com:8130/stream"},
    {name = "Park FM", url = "http://radioszero.hu:2000/stream.mp3"},
    {name = "Parkfm", url = "http://radioszero.hu:2000/stream.mp3"},
    {name = "Parlamenti Adások", url = "http://mr-stream.mediaconnect.hu/4745/mr5.aac"},
    {name = "Pécs Aktuál Rádió", url = "https://stream.pecsaktual.hu/paradio.mp3"},
    {name = "Periszkop Radio", url = "https://mumia.periszkopradio.hu:8443/;stream.mp3"},
    {name = "Petőfi", url = "https://icast.connectmedia.hu/4738/mr2.mp3"},
    {name = "Petőfi Rádió", url = "http://mr-stream.mediaconnect.hu/4737/mr2.aac"},
    {name = "Poptarisznya", url = "http://adas.poptarisznya.hu:8200/live.mp3"},
    {name = "Poptarisznya Blues24", url = "http://adas.poptarisznya.hu:8200/blues.mp3"},
    {name = "Poptarisznya Oldies", url = "http://adas.poptarisznya.hu:8200/oldies.mp3"},
    {name = "Power FM - Rock FM", url = "http://s39.myradiostream.com:11590/listen/;.mp3"},
    {name = "Rádió 1", url = "https://icast.connectmedia.hu/5201/live.mp3"},
    {name = "Radio 1", url = "https://icast.connectmedia.hu/5201/live.mp3"},
    {name = "Rádió 1 - Békéscsaba", url = "https://icast.connectmedia.hu/5233/live.mp3"},
    {name = "Rádió 1 - Budapest", url = "http://icast.connectmedia.hu/5201/live.mp3"},
    {name = "Rádió 1 - Gyöngyös", url = "https://icast.connectmedia.hu/5039/live.mp3"},
    {name = "Rádió 1 Debrecen", url = "http://91.82.85.44:8080/debrecenradiofm95"},
    {name = "Rádió 1 Miskolc", url = "https://icast.connectmedia.hu/5211/live.mp3"},
    {name = "Rádió 1 Szeged", url = "http://icast.connectmedia.hu/5232/live.mp3"},
    {name = "Rádió 7", url = "http://netradio.radio7.hu:8300/stream.mp3"},
    {name = "Rádió 88", url = "http://stream.radio88.hu:8000/;"},
    {name = "Rádió 88 Club", url = "http://stream2.radio88.hu:8400/;stream"},
    {name = "Rádió 88 Retro", url = "http://stream1.radio88.hu:8300/;stream"},
    {name = "Rádió 88 Top", url = "http://stream3.radio88.hu:8500/;stream"},
    {name = "Rádió Antritt", url = "http://stream.radioantritt.hu:8000/Antritt"},
    {name = "Rádió Bézs", url = "http://195.210.29.82:8001/bezs"},
    {name = "Rádió Bézs 2", url = "http://195.210.29.82:8002/bezs2"},
    {name = "Rádió Dabas", url = "http://stream3.virtualisan.net:7040/;"},
    {name = "Rádió Dikh", url = "http://icast.connectmedia.hu/6121/live.mp3"},
    {name = "Radio E", url = "http://radioe.net:8080/efm_high"},
    {name = "RADIO INSIDE", url = "http://s03.diazol.hu:7230/192"},
    {name = "Radio Kaleid", url = "https://cast4.my-control-panel.com/proxy/misli/stream"},
    {name = "Rádió Like", url = "https://cdn-node-44.hififm.hu:8080/stream001.mp3"},
    {name = "Rádió M", url = "http://hosting2.42netmedia.com:10060/;stream.mp3"},
    {name = "RADIO MARIA HUNGARY", url = "http://dreamsiteradiocp.com:8032/stream"},
    {name = "Rádió Most", url = "http://stream.radiomost.hu:8200/live.mp3"},
    {name = "Radio Ozora", url = "https://trance.out.airtime.pro/trance_a"},
    {name = "Rádió Pápa", url = "https://oxygenmusic.hu:8443/radiopapa.mp3"},
    {name = "Radio Pirata", url = "http://s24.myradiostream.com:12420/;"},
    {name = "Radio Sense", url = "http://s03.diazol.hu:7010/stream.mp3"},
    {name = "RADIO SMILE", url = "https://smile.str.42net.hu/stream/;"},
    {name = "Radio1", url = "https://icast.connectmedia.hu/5202/live.mp3"},
    {name = "Radio1 - Paks", url = "http://icast.connectmedia.hu/5222/live.mp3"},
    {name = "Radiobrand", url = "http://radiobrand.es:8084/"},
    {name = "Radiocafé 98", url = "https://radio.radiocafe98.hu/radiocafe98_192k"},
    {name = "Radiozora", url = "http://trance.out.airtime.pro:8000/trance_a"},
    {name = "Radiozora Chill", url = "http://chill.out.airtime.pro:8000/chill_a"},
    {name = "Radiozora Trance", url = "https://trance.out.airtime.pro/trance_a"},
    {name = "Retro Rádió", url = "https://icast.connectmedia.hu/5001/live.mp3"},
    {name = "Retro Radio", url = "https://icast.connectmedia.hu/5002/live.mp3"},
    {name = "Retro Rádió", url = "https://icast.connectmedia.hu/5001/live.mp3"},
    {name = "River", url = "https://webradio.ev2.hu:10010/river.mp3"},
    {name = "Rock Paradicsom", url = "http://stream1.virtualisan.net:6590/live.mp3"},
    {name = "Rocker Rádió", url = "http://radio.ch3.hu:8200/rocker.mp3"},
    {name = "Roxy Rádió", url = "https://s2.audiostream.hu/roxy_192k"},
    {name = "Sárvár Rádió", url = "https://stream.42netmedia.com:8443/sarvar"},
    {name = "Shine FM Radio", url = "http://s01.diazol.hu:10040/stream/;"},
    {name = "Sláger FM", url = "http://92.61.114.159:7812/slagerfm256.mp3"},
    {name = "Sola Rádió", url = "http://188.165.11.30:7000/live.mp3"},
    {name = "Spirit FM", url = "http://s01.diazol.hu:10050/spweb1.mp3"},
    {name = "Sunshine Dance", url = "http://195.56.193.129:8120/;stream/1?icy=http"},
    {name = "Sunshine FM", url = "http://195.56.193.129:8100/;stream/1"},
    {name = "Sunshine Pop", url = "http://195.56.193.129:8110/;stream/1?icy=http"},
    {name = "Super DJ Radio", url = "http://s03.diazol.hu:35150/live"},
    {name = "Superdj Radio", url = "http://stream.diazol.hu:35150/stream"},
    {name = "Szakcsi Rádió", url = "https://mr-stream.connectmedia.hu/4691/mr9.mp3"},
    {name = "Szent István Rádió", url = "http://online.szentistvanradio.hu:7000/adas"},
    {name = "Szent Korona Rádió", url = "http://radio.szentkoronaradio.com:8048/"},
    {name = "Szünet Rádió", url = "http://92.61.114.191:1101/listen.mp3"},
    {name = "Táska Rádió", url = "http://live.taskaradio.com:7070/;stream.nsv#.mp3"},
    {name = "Tempomax Rádió", url = "http://94.23.169.250:2060/live.mp3"},
    {name = "Test Radio Station", url = "https://videos.prd.dlivecdn.com/dlive/live.m3u8"},
    {name = "Tilos Rádió", url = "http://stream.tilos.hu/tilos"},
    {name = "TOP FM Max", url = "http://live.topfm.hu:8000/max.mp3"},
    {name = "Translation Of The Quran In Hungarian", url = "https://server3.quraan.us:8016/"},
    {name = "Trend FM", url = "https://radio.trendfm.hu/trendfm_192k"},
    {name = "Trió FM", url = "http://92.119.123.141:9090/stream"},
    {name = "Vörösmarty Rádió", url = "https://cloudfront41.lexanetwork.com:7604/livestream.mp3"},
    {name = "Xtradio", url = "https://xtrad.io/high.mp3"},
    {name = "Youventus Rádió", url = "http://s2.audiostream.hu/juventus_192k"},
    {name = "Zugrádió", url = "http://zuglofm.netregator.hu:7812/zuglofm128.mp3"},
}

return stations
