local stations = {
    {name = ". Al quran radio ", url = "http://n12.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABkYyBr18ALi5eU4gg_fwRSA"},
    {name = ". القارئ محمد أيوب ", url = "https://qurango.net/radio/mohammed_ayyub"},
    {name = ".. مختصر التفسير ", url = "https://qurango.net/radio/mukhtasartafsir"},
    {name = "Al rasheed fm", url = "https://streaming.shoutcast.com/alrasheed-fm?1719771692024"},
    {name = "Al-bilad Radio/Yaqoubi", url = "https://streamer.radio.co/sb38bf6e66/listen"},
    {name = "Alkafeel", url = "https://stream.alkafeel.net/live/radio/playlist.m3u8"},
    {name = "Alseraj Radio Islam", url = "https://eu4.fastcast4u.com/proxy/aabdul00?mp=/1"},
    {name = "Alseraj Radio Quran", url = "http://192.99.170.8:5550/stream"},
    {name = "Ankawa", url = "http://178.32.146.187/proxy/radioankawa?mp=/1/"},
    {name = "Babylon FM", url = "https://eu7.fastcast4u.com/proxy/babylonfm"},
    {name = "Baghdad Radio", url = "http://68.230.4.240:8000/;?icy=https"},
    {name = "Darusalam Radio", url = "https://streams.radio.co/s0975ec186/listen"},
    {name = "Hawa Dijlah FM  راديو هوا دجلة", url = "https://listen.radioking.com/radio/96766/stream/136030"},
    {name = "Kurdistan 24", url = "https://audio-edge-3mayu.fra.h.radiomast.io/04b1ce4c-24f2-4172-b756-065832ef78bf"},
    {name = "Qaladshlama", url = "https://s7.voscast.com/cdn/?k=641c8eaef4209&m=;stream1679593139317/1"},
    {name = "Radio Duhok FM", url = "https://stream-159.zeno.fm/unwq3jdyhmbuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ1bndxM2pkeWhtYnV2IiwiaG9zdCI6InN0cmVhbS0xNTkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImlCaGlSR2tiUlR1U0JrYTFQeVQxNUEiLCJpYXQiOjE3MjQ2OTAxMjUsImV4cCI6MTcyNDY5MDE4NX0.6ZsavG5UXVGdM_iBSFjDP07hXQKnhRwRquGblkcik4U"},
    {name = "radio maria iraq", url = "http://dreamsiteradiocp4.com:8046/stream"},
    {name = "radio maria iraq", url = "http://dreamsiteradiocp4.com:8046/stream"},
    {name = "Radio Shanasheel ", url = "https://stream-174.zeno.fm/a33ka0d94p8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhMzNrYTBkOTRwOHV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImdIalpGLUlGUkg2dG1rS1NTSHNYSWciLCJpYXQiOjE3MjQ2ODE5MDQsImV4cCI6MTcyNDY4MTk2NH0.LiCMStGN48wXWT5KwgbVf5utfIQc0hFaQa3-w4QclW4"},
    {name = "Radio Shanasheel ", url = "https://stream-174.zeno.fm/a33ka0d94p8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhMzNrYTBkOTRwOHV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ikt1R2xja1lQUXUtdmt3UXBZdDhRNGciLCJpYXQiOjE3MjQ2OTYwNzAsImV4cCI6MTcyNDY5NjEzMH0.xHRsW_ICxtyo0z-p0q8BMb87iIXP7LPMyS6hyWciNC4"},
    {name = "Radyo  Şirvan Perwer", url = "https://stream-156.zeno.fm/x0xhw6c6g2zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4MHhodzZjNmcyenV2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImN0X1YxaHllVFBLSkdrUEg0dkZDX1EiLCJpYXQiOjE3MjQ2ODI3MjAsImV4cCI6MTcyNDY4Mjc4MH0.jpMRl8vhwRB-R9k7kFmaV6uZx-WMakO3RqHWSdsSSjo"},
    {name = "Rudaw News Radio", url = "https://l3.itworkscdn.net/itwaudio/9006/stream"},
    {name = "Shafaq radio", url = "https://radio.shafaq.com/radio"},
    {name = "SumerFm Iraq", url = "https://l3.itworkscdn.net/itwaudio/9012/stream"},
    {name = "Turkmen FM  تركمان إف إم", url = "https://radyo1.radyo-dinle.tc/8284/stream;"},
    {name = "VOA Kurdish", url = "https://n02.radiojar.com/gt792vas92quv?rj-ttl=5&rj-tok=AAABkY9r66wACCaW22mVkl67dQ"},
    {name = "Waar Radio", url = "https://streaming.brol.tech/jamendolounge"},
    {name = "Waar Radio Official Stream", url = "https://c2.radioboss.fm:18564/stream"},
    {name = "راديو الغد، alghad FM", url = "http://s10.voscast.com:9410/"},
}

return stations
