local stations = {
    {name = " صوت كل لبنان", url = "https://audio.osina.cloud:9323/stream"},
    {name = ".. مختصر التفسير ", url = "https://qurango.net/radio/mukhtasartafsir"},
    {name = ".إذاعة القرآن الكريم ", url = "http://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABkY4l3okAtX0gBJgOnJoRHA"},
    {name = "91.7FM Al Nour Radio - 91.9 / 92.2    إذاعة النور :: رائدة الصوت والكلمة :: بيروت - لبنان", url = "http://audiostreaming.itworkscdn.com:9066/"},
    {name = "Adeem", url = "https://usa19.fastcast4u.com/adeem"},
    {name = "Aghani Aghani", url = "http://185.52.127.132/lb/1/mp3_128.mp3?access_token=b413c87b8da44dda9afe8370e3f37f77"},
    {name = "Al Bal Radio", url = "https://albal-lbnet2.radioca.st/stream"},
    {name = "Anghamy", url = "https://radio.avazfarsi.com:8010/radio.mp3"},
    {name = "Arabica TV", url = "http://istream.binarywaves.com:8081/hls/arabica/playlist.m3u8"},
    {name = "Beirut Nights", url = "http://byblosnights.com:443/"},
    {name = "Beirut Nights Radio (AAC)", url = "http://byblosnights.com:6190/"},
    {name = "BeirutNights.com", url = "http://byblosnights.com:6190/;"},
    {name = "Byblos Radio", url = "http://byblosnights.com:8000/byblosaac"},
    {name = "Byblos Radio (AAC)", url = "http://byblosnights.com:8360/"},
    {name = "Delta 101.7", url = "https://cast3.my-control-panel.com/proxy/radiodel/stream"},
    {name = "Fame FM Lebanon", url = "https://l3.itworkscdn.net/itwaudio/9044/stream"},
    {name = "Hit 90", url = "https://edge62.streamonkey.net/energy-90erhits/stream/mp3?aggregator=shorty"},
    {name = "Ibi Radio", url = "http://andromeda.shoutca.st:8192/;"},
    {name = "Jabal Lebnan", url = "http://185.52.127.168/lb/2/aac_64.mp3"},
    {name = "lbi Radio", url = "http://andromeda.shoutca.st:8192/;stream.mp3"},
    {name = "Light FM 90.5 & 90.7 Beirut", url = "http://25653.live.streamtheworld.com:3690/LIGHTFMAAC_SC"},
    {name = "M Radio Lebanon", url = "https://stream-157.zeno.fm/nuf630msh98uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJudWY2MzBtc2g5OHV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjUzSlkyQ2RSU2R5aEdWeHJfYVZfRnciLCJpYXQiOjE3MjQ2NjQ3MDgsImV4cCI6MTcyNDY2NDc2OH0.krZSWAD-RJ_03NzI-QjmEhxu7iG3PgoNNmpp9Nw_UN8"},
    {name = "montcarlo", url = "https://montecarlodoualiya128k.ice.infomaniak.ch/mc-doualiya.mp3"},
    {name = "Naim Halawe", url = "https://streamer.radio.co/sf2fa6ce9d/listen"},
    {name = "Nidaa FM", url = "http://nidaa.fm:8811/stream.mp3"},
    {name = "Nostalgie Liban", url = "http://185.52.127.170/lb/55157/aac_64.mp3?adws_out_3&access_token=0878f7e470d345de91ec881e2419a5ca"},
    {name = "Nostalgie Musique", url = "http://185.52.127.162/lb/55157/aac_64.mp3?adws_out_3&access_token=8304f41af50e43b6abcc945b649c44c3"},
    {name = "Nour Mariam TV", url = "http://svs.itworkscdn.net/nour9satlive/livestream/playlist.m3u8"},
    {name = "Radio Delta Lebanon", url = "http://cast3.my-control-panel.com:8501/"},
    {name = "Radio Liban", url = "https://media2.streambrothers.com:2020/stream/8194"},
    {name = "Radio Liban Libre", url = "https://edge.mixlr.com/channel/qtqeb"},
    {name = "Radio M", url = "https://stream-155.zeno.fm/p6r19mphm98uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwNnIxOW1waG05OHV2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IllTb3FobFhlVEFtdTRaalV2b3g0OWciLCJpYXQiOjE3MjQ2NjIyOTAsImV4cCI6MTcyNDY2MjM1MH0.r-E2Z6B_v4cxqe-4uLR9pWfiwfiMka5yscpFCi6g6zM"},
    {name = "radio maria arabic", url = "http://dreamsiteradiocp4.com:8014/stream"},
    {name = "radio maria arabic", url = "http://dreamsiteradiocp4.com:8014/stream"},
    {name = "radio maria arabic", url = "http://dreamsiteradiocp4.com:8014/stream"},
    {name = "radio maria arabic", url = "http://dreamsiteradiocp4.com:8014/stream"},
    {name = "radio maria arbic", url = "http://dreamsiteradiocp4.com:8014/stream"},
    {name = "Radio Rama", url = "https://radiorama-lbnet2.radioca.st/rama"},
    {name = "Sawt El Ghad - FM 96.7", url = "https://l3.itworkscdn.net/itwaudio/9030/stream/"},
    {name = "Sawt El Mada", url = "http://audiostreaming.itworkscdn.com:9018/stream"},
    {name = "SBI Lebanon", url = "http://s4.voscast.com:7648/;stream.mp3"},
    {name = "Virgin Radio Lebanon", url = "https://stream-140.zeno.fm/dwxw3p9vea0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJkd3h3M3A5dmVhMHV2IiwiaG9zdCI6InN0cmVhbS0xNDAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik92MWxBVGxJU0JHQTBfczJ4VlZrTFEiLCJpYXQiOjE3MjQ2ODQ4NzEsImV4cCI6MTcyNDY4NDkzMX0.8dl-Dysn0QEqzJjryGHcLR7nuui202I-G5e1LtGdk-A"},
    {name = "Virgin Radio Lebanon Stars", url = "https://stream-146.zeno.fm/h66yxnapga0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJoNjZ5eG5hcGdhMHV2IiwiaG9zdCI6InN0cmVhbS0xNDYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InpQZXBpZHRfUUpLTzdhRUxBYjlPdEEiLCJpYXQiOjE3MjQ2OTEzNTAsImV4cCI6MTcyNDY5MTQxMH0.efTdXrHYUk9R_UfzH5Fcyazj1LtNSx8Ssaa57Pr7QVk"},
    {name = "voice of Grace", url = "https://securestreams5.reliastream.com:1820/;l"},
    {name = "voice of Grace", url = "https://securestreams5.reliastream.com:1820/;l"},
    {name = "Voice of Lebanon (Sawtlebnan) Radio", url = "https://l3.itworkscdn.net/itwaudio/9054/stream"},
    {name = "ذكريات", url = "https://stream-173.zeno.fm/ctmapun6ot5vv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJjdG1hcHVuNm90NXZ2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlNkNjBvR3V2UlZhb3lDZXNWM2wxa2ciLCJpYXQiOjE3MjQ2NzY3MDEsImV4cCI6MTcyNDY3Njc2MX0.bNuoKwdjUK2F5gDnpvEpRm0AfqM0aNGs4tzBe9CuHDA"},
    {name = "رحبانيات", url = "https://stream-161.zeno.fm/4g8xck48kfhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI0Zzh4Y2s0OGtmaHZ2IiwiaG9zdCI6InN0cmVhbS0xNjEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkZ2ek9rN2N5U2VDZXZzb29XOEgwc2ciLCJpYXQiOjE3MjQ2NzYyMzUsImV4cCI6MTcyNDY3NjI5NX0.ad80X7X5KLBduO1r8_1xUbCMwre46s-ZFwwg_5NhycM"},
    {name = "صوت الغد استراليا", url = "http://s4.voscast.com:7648/;stream.mp3"},
    {name = "فيروز", url = "https://stream-157.zeno.fm/9vrahqqfuuhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5dnJhaHFxZnV1aHZ2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Imd1eWt0YTVHUlNtS1cyZUwyeFNTWnciLCJpYXQiOjE3MjQ2ODA3NTEsImV4cCI6MTcyNDY4MDgxMX0.QZr5AyasU-YhRNNhpW42M-1GRjfVj1C1K3d09LykMSA"},
}

return stations
