local stations = {
    {name = "Adwaafm", url = "http://stream-156.zeno.fm/5bxh2nh0x1zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI1YnhoMm5oMHgxenV2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik5RSWZZbGlRU0hxaTd4LTRLbGh0alEiLCJpYXQiOjE3MjQ2OTM2MTUsImV4cCI6MTcyNDY5MzY3NX0.iEThWmSi9acW9OxmWJH6cO-rDqi5Hyv-0mFyj0vZJPg&1681882617017"},
    {name = "Al Quran Radio", url = "http://n09.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABkY9PN_YAFeQNnx2woH8PiQ"},
    {name = "Aswat FM", url = "http://aswat.ice.infomaniak.ch/aswat-high.mp3"},
    {name = "Atlantic Radio", url = "https://atlantic-sonic.nindohost.net:9300/stream"},
    {name = "Aziz Mustaphi", url = "https://d3ctxlq1ktw2nl.cloudfront.net/production/2022-0-3/240607172-44100-2-afb2485b0c30e.mp3"},
    {name = "Aziz Mustaphi", url = "https://d3ctxlq1ktw2nl.cloudfront.net/production/2022-0-3/240607172-44100-2-afb2485b0c30e.mp3"},
    {name = "Bldi", url = "http://beldifm.hf.ma/radio/8000/radio.mp3"},
    {name = "Cap Radio", url = "https://listen.radioking.com/radio/635263/stream/698005"},
    {name = "CAP RADIO MAROC", url = "https://listen.radioking.com/radio/635263/stream/698011"},
    {name = "Fayroz", url = "https://stream-158.zeno.fm/zv3e5wykprhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ6djNlNXd5a3ByaHZ2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkVNaXV0TWNvUTh5OWRMY0tabTR2TkEiLCJpYXQiOjE3MjQ2Njc3MzgsImV4cCI6MTcyNDY2Nzc5OH0.vmMpCNaRI8CBzrLM26okioRKa3cp9dhSS-fG8TDdvKk"},
    {name = "HIT RADIO", url = "https://hitradio-maroc.ice.infomaniak.ch/hitradio-maroc-128.mp3"},
    {name = "Hit Radio Buzz", url = "http://buzz.ice.infomaniak.ch/buzz-128.mp3"},
    {name = "Hit Radio Mgharba", url = "http://mgharba.ice.infomaniak.ch/mgharba-128.mp3"},
    {name = "Hit Radio Rnb", url = "http://rnb.ice.infomaniak.ch/rnb-128.mp3"},
    {name = "Hitradio", url = "http://hitradio-maroc.ice.infomaniak.ch/hitradio-maroc-128.mp3"},
    {name = "Hits 1 Maroc", url = "https://ecmanager3.pro-fhi.net:2680/hits1studio"},
    {name = "Hits1 Maroc", url = "https://ecmanager3.pro-fhi.net:2680/hits1studio"},
    {name = "Islam Sobhi", url = "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem/026.mp3"},
    {name = "Izlan Atlas", url = "https://izlan.fr/radios/atlas/stream?.mp3"},
    {name = "Med Radio", url = "https://stream.bodkas.com/playlist?id=medradio"},
    {name = "Medi 1", url = "http://live.medi1.com/medi1?.mp3"},
    {name = "Medi 1 Acoustic", url = "http://live.medi1.com/Acoustic"},
    {name = "Medi 1 Classique", url = "http://live.medi1.com/Classique"},
    {name = "Medi 1 Jazz", url = "http://live.medi1.com/Jazz"},
    {name = "Medi 1 Nayda", url = "http://live.medi1.com/Nayda"},
    {name = "Medi 1 Radio Andalouse", url = "http://live.medi1.com/Andalouse"},
    {name = "Medi 1 Soufi", url = "http://live.medi1.com/Soufi"},
    {name = "Medi1 Afrique", url = "http://live.medi1.com/medi3?s=1410541768"},
    {name = "Medi1 Dj", url = "http://live.medi1.com/Dj"},
    {name = "Medi1 Latino", url = "http://live.medi1.com/Latino"},
    {name = "Media 1 Radio - Lounge", url = "http://live.medi1.com/Lounge"},
    {name = "Medina FM", url = "http://medinafm.ice.infomaniak.ch/medinafm-64.mp3?.mp3"},
    {name = "Mefi1 Tarab", url = "http://live.medi1.com/Tarab"},
    {name = "MFM Radio", url = "https://stream.bodkas.com/playlist?id=mfmradio"},
    {name = "Only Rai", url = "http://onlyrai.ice.infomaniak.ch/onlyrai-high.mp3"},
    {name = "Radio 2M", url = "https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/radio_2m/radio_hls_ts_hy217612tge1f21j83/radio_2m.m3u8"},
    {name = "Radio Aswat", url = "http://aswat.ice.infomaniak.ch/aswat-high.mp3"},
    {name = "Radio Atbir", url = "https://stream-155.zeno.fm/bqdbb6hd0neuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJicWRiYjZoZDBuZXV2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InQ3SnFUSVZ1U2hXbXJRMWhTeFYzVUEiLCJpYXQiOjE3MjQ2OTkwMDgsImV4cCI6MTcyNDY5OTA2OH0.2jdR0Fgs9jUnPLRto42aE4PkiAnpKKl-5x0CO3aRhK4"},
    {name = "Radio Azawan", url = "https://az-maroc.ice.infomaniak.ch/az-maroc-128.mp3"},
    {name = "Radio Enas", url = "https://www.lflouss.com/www.BookOfHonesty.com.mp3"},
    {name = "Radio Manarat", url = "https://listen.radioking.com/radio/252934/stream/297385"},
    {name = "Radio Mars", url = "http://radiomars.ice.infomaniak.ch/radiomars-128.mp3"},
    {name = "Radio Tanger Med", url = "http://radiotangermed-22.ice.infomaniak.ch/radiotangermed-22-128.mp3"},
    {name = "Radio Yan Plus", url = "https://stream-158.zeno.fm/7nqu31p6xg0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI3bnF1MzFwNnhnMHV2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im5SeWdfY2tvVHlTSEhZaHh3OHNIV0EiLCJpYXQiOjE3MjQ2Njg3NzcsImV4cCI6MTcyNDY2ODgzN30.j9r-9fPsD8KroMPxxYVjljZKbr-AD7vrIpPfdDcL15Y"},
    {name = "RIM Radio", url = "https://streaming.rimradio.ma/live"},
    {name = "Skyrock Casablanca", url = "https://icecast.skyrock.net/s/casa_aac_64k"},
    {name = "U Radio", url = "http://uradio-aac.ice.infomaniak.ch/uradio.aac"},
    {name = "إذاعة طريق السلف", url = "https://airtime.salafwayfm.ly/"},
    {name = "اذاعة القرآن الكريم", url = "http://n0c.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABkYz7QiMAmWj2404ihj00ig"},
    {name = "العيون الكوشي رواية ورش عن نافع", url = "https://qurango.net/radio/aloyoon_alkoshi"},
    {name = "تفسير بن عثيمين", url = "https://qurango.net/radio/tafseer"},
    {name = "صدقة جارية", url = "https://stream-152.zeno.fm/xzxaqh2w5rhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4enhhcWgydzVyaHZ2IiwiaG9zdCI6InN0cmVhbS0xNTIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkdBa1N1Wm1VVEpPaFpJZGc4ZndwRGciLCJpYXQiOjE3MjQ3MDU1NTksImV4cCI6MTcyNDcwNTYxOX0.22D_kKJxf5vjvTdTJyk7KG4jyUQYXmXD-ujHNM-NGc8"},
    {name = "ضرب الراديو", url = "http://hitradio-maroc.ice.infomaniak.ch/hitradio-maroc-128.mp3"},
    {name = "قرآن كريم للمقرئ المغربي عبد الرحمن بنموسى", url = "http://ia904708.us.archive.org/32/items/A_B_M_SO_2/009.mp3"},
    {name = "نهج واضح للمسلمين", url = "http://alnahj.net:8000/stream"},
}

return stations
