local stations = {
    {name = "BBC Nepali", url = "https://stream.live.vc.bbcmedia.co.uk/bbc_nepali_radio"},
    {name = "BBC Nepali 103 MHz", url = "https://stream.live.vc.bbcmedia.co.uk/bbc_nepali_radio"},
    {name = "BFBS Gurkha Radio", url = "https://listen-ssvcbfbs.sharp-stream.com/ssvcbfbs3.aac"},
    {name = "Butwal FM 94.4", url = "http://streaming.softnep.net:8003/stream"},
    {name = "Capital FM 92.4", url = "http://streaming.softnep.net:8037/;"},
    {name = "Chitwan Online FM", url = "https://15113.live.streamtheworld.com:443/SAM04AAC227_SC"},
    {name = "CIN Khabar", url = "https://streaming.softnep.net:10996/;stream.nsv&type=mp3&volume=60"},
    {name = "Hits FM 91.2", url = "https://usa15.fastcast4u.com/proxy/hitsfm912?mp=/1"},
    {name = "Kalika FM", url = "http://kalika-stream.softnep.com:7740/;"},
    {name = "Kalika FM 95.2 FM", url = "http://kalika-stream.softnep.com:7740/stream"},
    {name = "Kantipur FM", url = "https://radio-broadcast.ekantipur.com/stream"},
    {name = "Khozee Radio", url = "http://216.55.141.189:8060/stream/1/"},
    {name = "Naya Radio", url = "http://live.itech.host:1110/;"},
    {name = "Radio Adhyatma Jyoti", url = "https://stream.hamropatro.com/8074"},
    {name = "Radio Audio", url = "https://stream-159.zeno.fm/fvrx47wpg0quv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJmdnJ4NDd3cGcwcXV2IiwiaG9zdCI6InN0cmVhbS0xNTkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlJXaFZsLUhlUzVlY05nNjhkQ0NOS2ciLCJpYXQiOjE3MjQ2NzY1MDksImV4cCI6MTcyNDY3NjU2OX0.Jcdg7EmWJVLhQjLrjY1aXEJ8oSO3lbUxN2vYsybTvtw"},
    {name = "Radio Himalaya", url = "https://live.itech.host/himalayaradio?1588276425741"},
    {name = "Radio Kantipur", url = "https://radio-broadcast.ekantipur.com/stream"},
    {name = "Radio Kantipur", url = "https://radio-broadcast.ekantipur.com/stream"},
    {name = "Radio Kantipur FM 96.1 MHz", url = "https://radio-broadcast.ekantipur.com/stream"},
    {name = "Radio Kantipur FM 96.1 MHz", url = "https://radio-broadcast.ekantipur.com/stream"},
    {name = "Radio Nepal", url = "https://stream1.radionepal.gov.np/live/"},
    {name = "Radio Sahino", url = "http://live.itech.host:7093/live"},
    {name = "Radio Sathi", url = "http://live.itech.host:7115/live"},
    {name = "RadioSagar", url = "https://eu1.fastcast4u.com/proxy/radiosag?mp=/stream/1/"},
    {name = "Swadesh 93.2 FM", url = "http://216.55.141.189:8653/stream?type=http&nocache=66846"},
    {name = "Swadesh FM", url = "https://stream-156.zeno.fm/xm2babvnephvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4bTJiYWJ2bmVwaHZ2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkdfZTlqaEpnVGF1TVlRZW5zM2p4bnciLCJpYXQiOjE3MjQ2OTMxMTIsImV4cCI6MTcyNDY5MzE3Mn0.qd3DySQzVzaGeWUdOnh9P_2uhwmYmrF51WgdCzAyZfk"},
    {name = "Ujyaalo 90 Network", url = "http://stream-150.zeno.fm/wtuvp08xq1duv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ3dHV2cDA4eHExZHV2IiwiaG9zdCI6InN0cmVhbS0xNTAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlVUYTlSbkV1UmNxemkzTnVqRFdIUnciLCJpYXQiOjE3MjQ2OTA4MjAsImV4cCI6MTcyNDY5MDg4MH0.5ascNQ4b1WY3GAHawODGfQCY1CNdWXndKYDZXdbh7XA"},
    {name = "Ultimaě radio", url = "https://ultimae-bofaradio.radioca.st/"},
    {name = "Vijaya FM 101.6", url = "https://live.itech.host:3320/stream"},
    {name = "रेडियो हिमालय", url = "https://live.itech.host/himalayaradio"},
}

return stations
