local stations = {
    {name = "A Fine Jazz Gumbo Radio", url = "https://streaming.smartradio.ch:9502/stream"},
    {name = "80Ies Dot Radio", url = "https://n06.radiojar.com/6cbvkaa1mrruv?1643199882=&rj-tok=AAABkY9ZSlwAaq8lK9Txb3xHSw&rj-ttl=5"},
    {name = "80S Forever - We Keep The 80S Alive", url = "http://azuracast.ssl-stream.com/radio/8050/256.mp3"},
    {name = "Abc", url = "https://nl1.streamhosting.ch/lounge64.aac"},
    {name = "Adonia-Kidsradio", url = "http://puma.streemlion.com:1930/stream"},
    {name = "Aebisland", url = "https://aebisland.ice.infomaniak.ch/aebisland-128.mp3"},
    {name = "Ambi Nature Radio", url = "https://nature-rex.radioca.st/stream"},
    {name = "Arc Musique", url = "https://arcmusique.ice.infomaniak.ch/arcmusique-128.mp3"},
    {name = "Audioasyl", url = "http://stream.audioasyl.net:8000/audioasyl"},
    {name = "Barix Radio", url = "http://barix-ice.streamguys1.com/barix_hi"},
    {name = "Basspistol Radio", url = "https://radio.basspistol.com/listen/basspistol/radio.mp3"},
    {name = "Break Radio", url = "https://breakradio.ice.infomaniak.ch/breakradio-192.mp3"},
    {name = "Canal3 Deutsch", url = "https://radio.upstream-cloud.ch/canal3allemand-192.aac"},
    {name = "Christmas Radio", url = "http://xmasfm1.dmd2streaming.com/christmasradiofm-128.mp3"},
    {name = "Classic Rock", url = "https://chmedia.streamabc.net/79-classicrock-mp3-192-6577748?sABC=655o94o7%230%239906209q5qoq5po487r1668p80q43331%23qverp&aw_0_1st.playerid=direc&amsparams=playerid:direc;skey:1700500663"},
    {name = "Couleur3", url = "http://stream.srg-ssr.ch/m/couleur3/aacp_96"},
    {name = "DIKS ДИКС", url = "https://icecast.correctiv.net/sacharow"},
    {name = "Dream Sequence", url = "https://listen.radioking.com/radio/453296/stream/508976"},
    {name = "Driftfm", url = "https://s4.radio.co/s5729f2e59/listen"},
    {name = "Electro Radio", url = "http://n13.radiojar.com/fkyxx4q35k0uv?rj-ttl=5&rj-tok=AAABkY48TocA5E1AT-B3LEauKQ"},
    {name = "Electrons Libres", url = "https://listen.radioking.com/radio/427889/stream/481502"},
    {name = "Energy Bern", url = "https://energybern.ice.infomaniak.ch/energybern-high.mp3"},
    {name = "Energy Blick Trendz", url = "http://energyzuerich.ice.infomaniak.ch/energyzuerich-high.mp3"},
    {name = "Energy Luzern", url = "https://energyluzern.ice.infomaniak.ch/energyluzern-high.mp3"},
    {name = "FLASHBACK FM", url = "https://chmedia.streamabc.net/79-ffm-mp3-192-2470075"},
    {name = "Framboase", url = "http://framboase.ice.infomaniak.ch/framboase-128.mp3"},
    {name = "Glaubenskampf Bibel Radio", url = "https://streams.radio.co/s06c02a443/listen"},
    {name = "Global FM", url = "http://globalfm.ice.infomaniak.ch/globalfm-high.mp3"},
    {name = "Global Sport - Vaud", url = "http://live9.avf.ch:8000/globalfmdabvd"},
    {name = "Global Sport - Genève", url = "http://live9.avf.ch:8000/globalfmdabge"},
    {name = "Global Sport - Suisse", url = "http://live9.avf.ch:8000/globalfm160"},
    {name = "Global Sport NFBJ", url = "http://live9.avf.ch:8000/globalfmdabne"},
    {name = "Global Sport SUISSE", url = "http://live7.avf.ch:8000/globalfm"},
    {name = "Gnu Radio - Metal FM", url = "https://fluxfm.streamabc.net/flx-metalfm-mp3-320-9154971?sABC=61s83r32%230%2389nqs1p1q8rrq2q126260sp7877or6oo%23fgernzf.syhksz.qr&amsparams=playerid:streams.fluxfm.de;skey:1643658802"},
    {name = "GOAT Radio", url = "https://20min.dmd2streaming.com/20minuten_radio_64.aac"},
    {name = "Gottes Radio", url = "http://gottesradio.stream.laut.fm/gottesradio?pl=m3u&t302=2024-08-26_17-14-38&uuid=1fe140ec-19f1-4fdc-b125-1e722734952c"},
    {name = "GRRIF", url = "https://rjb.ice.infomaniak.ch/rjb-high.mp3"},
    {name = "Happy Radio", url = "https://uksoutha.streaming.broadcast.radio/stream/11340/gtradio?1672903939995"},
    {name = "IP Music", url = "http://live9.avf.ch:8000/ipmusicaacplus96"},
    {name = "Ip Music 320", url = "http://live7.avf.ch:8000/ipmusic320"},
    {name = "IP Music Slow", url = "http://live7.avf.ch:8000/ipmusicslow256"},
    {name = "JAMES FM", url = "https://jamesfm.ice.infomaniak.ch/jamesfm.mp3"},
    {name = "Jazz Black Music", url = "http://jazzblackmusic.ice.infomaniak.ch/jazzblackmusic-high.aac"},
    {name = "Jazz Radio", url = "http://jazzlounge.ice.infomaniak.ch/jazzlounge-high.mp3"},
    {name = "Jazz Radio Lounge", url = "http://jazzlounge.ice.infomaniak.ch/jazzlounge-high.aac"},
    {name = "Jazzology Radio", url = "https://c2.radioboss.fm:18094/stream"},
    {name = "Kanal Bethesda", url = "http://n11.radiojar.com/a2dd2q0kb?rj-ttl=5&rj-tok=AAABkY77zy0ADWQNGGwRbX-rBA"},
    {name = "Kanal K", url = "https://kanalk.streamabc.net/91-kanalk-mp3-192-5146873?sABC=66ppn2sn%230%232qqpnss01895rqr0s8oq129o03s183o0%23jrofrvgr&aw_0_1st.playerid=webseite&amsparams=playerid:webseite;skey:1724687098"},
    {name = "Kanalk", url = "https://kanalk.streamabc.net/91-kanalk-mp3-192-5146873?sABC=66ppqq65%230%236080533n48sp2nrq0o4389q6o67o3qps%23&aw_0_1st.playerid=&amsparams=playerid:;skey:1724702053"},
    {name = "Kiss Collector Radio", url = "https://dr2101.ice.infomaniak.ch/dr2101.mp3"},
    {name = "Kontrafunk", url = "https://s5.radio.co/sca4082ebb/listen"},
    {name = "Kontrafunk News", url = "https://stream.kontrafunk.radio/listen/kontrafunk/radio.mp3"},
    {name = "LFM", url = "http://lausannefm.ice.infomaniak.ch/lausannefm-high.mp3"},
    {name = "Lounge Radio", url = "http://de1.streamhosting.ch/"},
    {name = "Loungemain Radio Jazz-Chill-Funk", url = "http://185.238.128.191:8002/live"},
    {name = "LUX RADIO", url = "https://fluxradio.ice.infomaniak.ch/fluxradio-32.aac"},
    {name = "M La Radio", url = "https://mlaradio.ice.infomaniak.ch/mlaradio.mp3"},
    {name = "Musikwälle", url = "http://stream.srg-ssr.ch/m/drsmw/mp3_128"},
    {name = "My105 - All The Hits", url = "http://my105-stream17.radiohost.de/my105-allthehits_mp3-192?_art=dD0xNzI0NjkyMjkxJmQ9MmY0Zjg1YzEwOTFhYjY2OTBmOGM"},
    {name = "My105 - Charts", url = "http://my105-stream16.radiohost.de/my105-charts_mp3-192?_art=dD0xNzI0NjUxMTY2JmQ9OTQ5MzM1ZmFmZmRhZDRkMmI3ZGU"},
    {name = "My105 - Chill", url = "http://my105-stream16.radiohost.de/my105-chill_mp3-192?_art=dD0xNzI0NjgzMTU3JmQ9MDRjNjcxMDM2YjIwZTQ0MTZkNGI"},
    {name = "My105 - Dance", url = "http://my105-stream16.radiohost.de/my105-dance_mp3-192?_art=dD0xNzI0NzAxNDUxJmQ9YjZiNzNlNGZiMzYxMmU5MzQxMGQ"},
    {name = "My105 - Deep", url = "http://my105-stream14.radiohost.de/my105-deep_mp3-192?_art=dD0xNzI0Njk3MDE4JmQ9MTFhMWQ5ZDg1ZDNiNjNlNjU2NjU"},
    {name = "My105 - Deluxe", url = "http://my105-stream17.radiohost.de/my105-nightbeatsdeluxe_mp3-192?_art=dD0xNzI0Njk0NDU1JmQ9MTk1ZWUxNDhkZGY4Y2NlYWVhYTU"},
    {name = "My105 - DJ Mixes", url = "http://my105-stream14.radiohost.de/my105-dance_mp3-192?_art=dD0xNzI0NjkzOTg2JmQ9ZWJjZTRjMjJkZjBiNzI2MzBmYTk"},
    {name = "My105 - Dreist", url = "http://my105-stream14.radiohost.de/my105-thebattle_mp3-192?_art=dD0xNzI0Njk0NDQ5JmQ9M2ZhM2RiMmI4ZGU3MjFlMTc1MTc"},
    {name = "My105 - Fresh", url = "http://my105-stream14.radiohost.de/my105-fresh_mp3-192?_art=dD0xNzI0Njg5OTI0JmQ9NDczZGVjMjljMWQyNGZlMTA2Nzk"},
    {name = "My105 - Love", url = "http://my105-stream16.radiohost.de/my105-chill_mp3-192?_art=dD0xNzI0NjQ0MzkxJmQ9NWMwZDdlNGFjZDk4OTY0YWNhN2Q"},
    {name = "My105 - Mashup", url = "http://my105-stream16.radiohost.de/my105-mashup_mp3-192?_art=dD0xNzI0NjU4MjU5JmQ9NWFiZmNiYzg0NDgwYTEyZWQyY2Q"},
    {name = "My105 - Original", url = "http://my105-stream14.radiohost.de/my105-todaysbestmusic_mp3-192?_art=dD0xNzI0Njc3MDM1JmQ9YmIxNWYwMTI0NTMzNTU1YzBjYWM"},
    {name = "My105 - Party", url = "http://my105-stream17.radiohost.de/my105-party_mp3-192?_art=dD0xNzI0Njg5NDExJmQ9NGRiN2MxZjk0YzRmZWZiYjg2YWQ"},
    {name = "My105 - Ritmo Latino", url = "http://my105-stream16.radiohost.de/my105-ritmolatino_mp3-192?_art=dD0xNzI0Njg3MTE1JmQ9MGViODhjZDczYWQ5NmU3MTM4OGI"},
    {name = "My105 - Rock", url = "http://my105-stream16.radiohost.de/my105-todaysbestmusic_mp3-192?_art=dD0xNzI0Njg2OTA1JmQ9MTg0ODczMDc5NWEwODhlNDBhNmQ"},
    {name = "My105 - The Battle", url = "http://my105-stream14.radiohost.de/my105-thebattle_mp3-192?_art=dD0xNzI0NjUxODQ1JmQ9MzUyYWE3Mjg3MDExNTEwNmFmNmQ"},
    {name = "My105 X-MAS", url = "https://my105-stream14.radiohost.de/my105-xmas_mp3-192?_art=dD0xNzI0Njg3Mjc1JmQ9OWE3MTE4YzhiNzI2MzBkNTU0NTE"},
    {name = "Neo1", url = "https://neo1.ice.infomaniak.ch/neo1.mp3"},
    {name = "New Clear Radio", url = "https://live.ncradio.fm/320"},
    {name = "One Dance Ticino", url = "https://ice04.fluidstream.net/rn1_2.aac"},
    {name = "One FM", url = "http://onefm.ice.infomaniak.ch/onefm-high.mp3"},
    {name = "One FM 2000S", url = "https://webradio0009.ice.infomaniak.ch/webradio0009-128.mp3"},
    {name = "One FM 90S", url = "https://webradio0006.ice.infomaniak.ch/webradio0006-128.mp3"},
    {name = "One FM New-Hits", url = "https://webradio0001.ice.infomaniak.ch/webradio0001-128.mp3"},
    {name = "Open Broadcast", url = "https://www.digris.ch/stream/092210ed-4eb4-483b-814f-21df6ecb1352"},
    {name = "Open Broadcast Radio", url = "http://stream.openbroadcast.ch/320.mp3"},
    {name = "Option Musique", url = "http://stream.srg-ssr.ch/m/option-musique/mp3_128"},
    {name = "Pineapple Juice", url = "http://pineapplejuice.stream.laut.fm/pineapplejuice?t302=2024-08-26_01-03-59&uuid=1bcb25c4-f4fa-40f9-8458-fa2ba2f54480"},
    {name = "Pineapplejuice", url = "http://pineapplejuice.stream.laut.fm/pineapplejuice?t302=2024-08-26_00-04-48&uuid=2a9411eb-8bfd-4815-8a0b-29c1f23ee9a5"},
    {name = "Piratenradio", url = "http://piratenradioch.ice.infomaniak.ch/piratenradioch-128.mp3"},
    {name = "Planet Ambi HD", url = "http://philae.shoutca.st:9019/stream"},
    {name = "Powerup Radio", url = "http://stream.powerup.ch/powerupradio-192.mp3"},
    {name = "Public Domain Classical", url = "http://relay.publicdomainradio.org/classical.mp3"},
    {name = "Public Domain Jazz And Swing", url = "http://relay.publicdomainproject.org/jazz_swing.mp3"},
    {name = "Public Domain Swiss Schlager", url = "http://relay.publicdomainradio.org/swiss_schlager.mp3"},
    {name = "R102", url = "http://94.23.66.155:9334/stream"},
    {name = "Rabe Radio Bern Switzerland", url = "http://stream.rabe.ch:8000/livestream/rabe-mid.mp3"},
    {name = "Radio 1", url = "http://stream.radio1.ch/128k.m3u"},
    {name = "Radio 24", url = "https://chmedia.streamabc.net/79-r24-mp3-192-6659699?sABC=66ppq789%230%236080533n48sp2nrq0o4389q6o67o3qps%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724700553"},
    {name = "Radio 32", url = "https://chmedia.streamabc.net/79-r32-mp3-192-5284783?sABC=66pp83p7%230%232qqpnss01895rqr0s8oq129o03s183o0%23puzrqvn-gbqnl-jro&aw_0_1st.playerid=chmedia-today-web&amsparams=playerid:chmedia-today-web;skey:1724679111"},
    {name = "Radio 32 Goldies", url = "https://chmedia.streamabc.net/79-goldies-mp3-192-3811722?sABC=66pp9os4%230%232qqpnss01895rqr0s8oq129o03s183o0%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724685300"},
    {name = "Radio 3FACH", url = "http://stream01.3fach.ch:8001/live"},
    {name = "Radio Argovia", url = "https://chmedia.streamabc.net/79-argovia-mp3-192-3024993?sABC=66pp5288%230%232qqpnss01895rqr0s8oq129o03s183o0%23enqvboebjfre&aw_0_1st.playerid=radiobrowser&amsparams=playerid:radiobrowser;skey:1724666504"},
    {name = "Radio Argovia Classic Rock", url = "https://chmedia.streamabc.net/79-classicrock-mp3-192-6577748?sABC=66ppoqp5%230%236080533n48sp2nrq0o4389q6o67o3qps%23enqvboebjfre&aw_0_1st.playerid=radiobrowser&amsparams=playerid:radiobrowser;skey:1724693957"},
    {name = "Radio Barix AAC", url = "http://barix.streamguys.net/barix_aacp"},
    {name = "Radio Basilisk", url = "http://radiobasilisk-64.ice.infomaniak.ch/radiobasilisk-64-128-2.mp3"},
    {name = "Radio Beo", url = "http://stream11.radiobeo.ch:8000/radiobeo.mp3"},
    {name = "RADIO BERN1", url = "https://chmedia.streamabc.net/79-rbern1-mp3-192-7860422?sABC=66popq00%230%232qqpnss01895rqr0s8oq129o03s183o0%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724632320"},
    {name = "Radio Bollwerk", url = "https://radiobollwerk.out.airtime.pro/radiobollwerk_a"},
    {name = "Radio Central", url = "https://chmedia.streamabc.net/79-rcentral-mp3-192-1355604?sABC=66pp2548%231%231723615196409_33800762%23puzrqvn-enqvb-jro&aw_0_1st.playerid=chmedia-radio-web&amsparams=playerid:chmedia-radio-web;skey:1724654920"},
    {name = "Radio Chablais", url = "http://radiochablais.ice.infomaniak.ch/radiochablais-high.mp3"},
    {name = "Radio Drachenblut", url = "http://radio-drachenblut.ch:8000/stream/3/"},
    {name = "Radio Electrons Libres", url = "https://listen.radioking.com/radio/427889/stream/481502"},
    {name = "Radio Eviva", url = "https://chmedia.streamabc.net/79-reviva-mp3-192-6592795?sABC=66pp6180%230%236080533n48sp2nrq0o4389q6o67o3qps%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724670336"},
    {name = "Radio FM1", url = "https://chmedia.streamabc.net/79-fm1-mp3-192-7523806?sABC=6499o8o6%230%230016or1p1r381r4485n244q3016qs660%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1687795894"},
    {name = "Radio Freundesdienst Deutsch", url = "http://radiofd.ice.infomaniak.ch/radiofd.mp3"},
    {name = "Radio Freundesdienst Schweiz", url = "http://radiofdch.ice.infomaniak.ch/radiofdch.mp3"},
    {name = "Radio Fribourg", url = "https://radiofribourg.ice.infomaniak.ch/radiofribourg-high.mp3"},
    {name = "Radio Gaba Switzerland", url = "http://radio-gaba.ddns.net:8000/play.ogg"},
    {name = "Radio Gloria", url = "https://ch-be06-ice.dmd2streaming.com/radiogloria_lo"},
    {name = "Radio Grischa", url = "https://somedia-1.streaming.deliver.media/radiogrischa_mp3_128?suffix0=RSO"},
    {name = "Radio Gugelhopf", url = "http://uk3.internet-radio.com:8113/stream"},
    {name = "Radio Kaiseregg", url = "http://kaiseregg.ice.infomaniak.ch/stream128k.mp3"},
    {name = "Radio Lac", url = "https://radiolac.ice.infomaniak.ch/radiolac-high.mp3"},
    {name = "Radio Lora", url = "https://livestream.lora.ch/lora.mp3"},
    {name = "Radio Maria Schweiz", url = "http://streaming2.elitecomunicacion.es:9000/radiomaria_lo"},
    {name = "RADIO MARIA SWITZERLAND", url = "http://dreamsiteradiocp2.com:8106/stream"},
    {name = "Radio Maxxima", url = "https://maxxima.mine.nu/maxxima.mp3"},
    {name = "Radio Melody", url = "https://chmedia.streamabc.net/79-rm-mp3-192-7754268?sABC=64726ssr%230%23565o8622n9638n515p1pqq82pnq6q099%23zlghare&aw_0_1st.playerid=mytuner&amsparams=playerid:mytuner;skey:1685221374"},
    {name = "Radio Melody Schweiz", url = "https://chmedia.streamabc.net/79-rm-mp3-192-7754268?sABC=66ppp070%230%236080533n48sp2nrq0o4389q6o67o3qps%23zlghare&aw_0_1st.playerid=mytuner&amsparams=playerid:mytuner;skey:1724694640"},
    {name = "Radio Merak", url = "http://79.143.187.96:8092/"},
    {name = "Radio Morcote International", url = "http://streaming.radiomorcoteinternational.com:8000/;"},
    {name = "Radio Neue Hoffnung", url = "https://stream.mnr.ch/rnh-mp3"},
    {name = "Radio Niesen", url = "https://server31677.streamplus.de/stream.mp3"},
    {name = "Radio Onyx", url = "http://nr4.newradio.it:9432/stream"},
    {name = "Radio Ouistiti", url = "http://radioouistiti2.ice.infomaniak.ch/radioouistiti-high.mp3"},
    {name = "Radio Pilatus", url = "https://chmedia.streamabc.net/79-pilatus-mp3-192-4664468?sABC=66ppqp07%230%236080533n48sp2nrq0o4389q6o67o3qps%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724701703"},
    {name = "Radio R", url = "http://radior.ice.infomaniak.ch/radior-128.mp3"},
    {name = "Radio R Louange", url = "https://radiorlouange.ice.infomaniak.ch/radiorlouange-96.aac?ver=666978"},
    {name = "Radio Rasa Schaffhausen", url = "https://radio.upstream-cloud.ch/radiorasa-128.mp3"},
    {name = "Radio Rocket", url = "https://i9.streams.ovh/sc/radioroc/stream"},
    {name = "RADIO ROTATION", url = "http://radio-rotation.stream.laut.fm/radio-rotation?t302=2024-08-26_18-26-18&uuid=1041358b-08c5-4c52-9714-1a900548c0d0"},
    {name = "Radio Rotblau", url = "https://rotblaustream.ch:8443/live"},
    {name = "Radio RTR", url = "http://stream.srg-ssr.ch/m/rr/aacp_96"},
    {name = "Radio Rumantsch", url = "http://stream.srg-ssr.ch/m/rr/mp3_128"},
    {name = "Radio S", url = "https://stream.radio-s.ch:8443/pssend"},
    {name = "Radio Sans Chaine", url = "http://radio-sans-chaine.ice.infomaniak.ch/radiosanschaine.aac"},
    {name = "Radio SRF 1", url = "http://stream.srg-ssr.ch/m/drs1/aacp_32"},
    {name = "Radio SRF 1 Aargau Solothurn", url = "http://stream.srg-ssr.ch/m/regi_ag_so/aacp_32"},
    {name = "Radio SRF 1 Basel Baselland", url = "http://stream.srg-ssr.ch/m/regi_bs_bl/aacp_32"},
    {name = "Radio SRF 1 Bern Freibourg Wallis", url = "http://stream.srg-ssr.ch/m/regi_be_fr_vs/aacp_32"},
    {name = "Radio SRF 1 HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs1_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio SRF 1 Ostschweiz", url = "http://stream.srg-ssr.ch/m/regi_ost/aacp_32"},
    {name = "Radio SRF 1 Regionaljournal Graubünden", url = "http://stream.srg-ssr.ch/m/regi_gr/mp3_128"},
    {name = "Radio SRF 1 Regionaljournal Ostschweiz", url = "http://stream.srg-ssr.ch/m/regi_ost/mp3_128"},
    {name = "Radio SRF 1 Zentralschweiz", url = "http://stream.srg-ssr.ch/m/regi_zentr/mp3_128"},
    {name = "Radio SRF 1 Zürich Schaffhausen", url = "http://stream.srg-ssr.ch/m/regi_zh_sh/aacp_32"},
    {name = "Radio SRF 2 Kultur", url = "http://stream.srg-ssr.ch/m/drs2/aacp_32"},
    {name = "Radio SRF 2 Kultur HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs2_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio SRF 3", url = "http://stream.srg-ssr.ch/m/drs3/aacp_32"},
    {name = "Radio SRF 3 HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs3_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio SRF 4 News", url = "https://stream.srg-ssr.ch/m/drs4news/aacp_32"},
    {name = "Radio SRF 4 News HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs4news_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio SRF Musikwelle", url = "http://stream.srg-ssr.ch/m/drsmw/mp3_128"},
    {name = "Radio SRF Musikwelle HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drsmw_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio SRF Virus", url = "http://stream.srg-ssr.ch/m/drsvirus/aacp_32"},
    {name = "Radio SRF Virus - Indie Rock", url = "http://streaming.swisstxt.ch/m/drsvirus/mp3_128"},
    {name = "Radio Stadtfilter Winterthur", url = "http://stream.stadtfilter.net:8406/stadtfilter.mp3"},
    {name = "Radio Südostschweiz", url = "https://somedia-1.streaming.deliver.media/rso_mp3_128?suffix0=RSO"},
    {name = "Radio Suisse Classique", url = "https://stream.srg-ssr.ch/m/rsc_fr/mp3_128"},
    {name = "Radio Summernight", url = "https://radiosummernight.stream.laut.fm/radiosummernight?t302=2024-08-26_08-13-27&uuid=9cbeba4d-3fe0-4fe8-a71f-90c118b24344"},
    {name = "Radio Svizzera Classica", url = "http://stream.srg-ssr.ch/m/rsc_it/aacp_96"},
    {name = "Radio Swiss Classic", url = "http://stream.srg-ssr.ch/m/rsc_de/aacp_96"},
    {name = "Radio Swiss Classic DE HLS 96", url = "http://lsaplus.swisstxt.ch/audio/rsc_de_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Swiss Classic French", url = "http://stream.srg-ssr.ch/m/rsc_fr/aacp_96"},
    {name = "Radio Swiss Classic German", url = "http://stream.srg-ssr.ch/m/rsc_de/mp3_128"},
    {name = "Radio Swiss Classic Italian", url = "http://stream.srg-ssr.ch/m/rsc_it/aacp_32"},
    {name = "RADIO SWISS CLASSICA ITALIA", url = "http://stream.srg-ssr.ch/m/rsc_it/aacp_96"},
    {name = "Radio Swiss Jazz", url = "http://stream.srg-ssr.ch/m/rsj/aacp_96"},
    {name = "Radio Swiss Jazz HLS 96", url = "http://lsaplus.swisstxt.ch/audio/rsj_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Swiss Pop", url = "http://stream.srg-ssr.ch/m/rsp/aacp_96"},
    {name = "Radio Swiss Pop HLS 96", url = "http://lsaplus.swisstxt.ch/audio/rsp_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Tell", url = "http://stream.radiotell.ch/radiotell.mp3"},
    {name = "Radio Top Two", url = "http://77.109.144.109:8000/twosrp128"},
    {name = "Radio Vihor", url = "https://r.name.ba:7500/"},
    {name = "Radio Vostok", url = "http://radiovostok.ice.infomaniak.ch/radiovostok.aac"},
    {name = "Radio Zuerisee", url = "http://mp3.radio.ch/radiozuerisee128k"},
    {name = "Radio Zürisee", url = "https://mp3.radio.ch/radiozuerisee256k"},
    {name = "Radio-Drachenblut", url = "https://radio-drachenblut.ch:8443/listen.mp3"},
    {name = "Radio1", url = "http://stream.radio1.ch/128k.m3u"},
    {name = "Radio24", url = "https://chmedia.streamabc.net/79-r24-mp3-192-6659699?sABC=66ppq82s%230%232qqpnss01895rqr0s8oq129o03s183o0%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724700719"},
    {name = "Radio3I", url = "https://vstream-cdn.ch/hls/radio3i.m3u8"},
    {name = "Radio4Tng", url = "http://radio4tng.ice.infomaniak.ch/radio4tng-live-web.mp3"},
    {name = "Radiopolis", url = "http://rs01.swissnwx.ch:20080/stream"},
    {name = "Radioswiss", url = "http://radioswiss.stream.laut.fm/radioswiss?t302=2024-08-26_10-33-30&uuid=22940710-d8ba-4157-a074-5993009b608f"},
    {name = "RFJ", url = "https://rfj.ice.infomaniak.ch/rfj-high.mp3"},
    {name = "Rhône FM", url = "http://rhonefm.ice.infomaniak.ch/rhonefm-high.aac"},
    {name = "RJB", url = "https://rjb.ice.infomaniak.ch/rjb-high.mp3"},
    {name = "Rock The Blues", url = "http://rock-the-blues.stream.laut.fm/rock-the-blues?t302=2024-08-26_19-28-02&uuid=7a847f08-edaf-49a5-8aaa-4215a82e9333"},
    {name = "ROCKSTATION", url = "https://radio2.stream24.net:8130/live.mp3"},
    {name = "Rouge", url = "http://rougefm.ice.infomaniak.ch/rougefm-high.aac"},
    {name = "Rouge FM 90S", url = "http://rouge-90.ice.infomaniak.ch/rouge-90-128.mp3"},
    {name = "Rouge FM Latino", url = "http://rouge-latino.ice.infomaniak.ch/rouge-latino-128.mp3"},
    {name = "Rouge FM Lounge", url = "http://rougefm.ice.infomaniak.ch/rougefm-high.mp3"},
    {name = "Rouge FM Suisse", url = "http://rouge-suisse.ice.infomaniak.ch/rouge-suisse-128.mp3"},
    {name = "Rouge Reggae", url = "http://rouge-reggae.ice.infomaniak.ch/rouge-reggae-128.mp3"},
    {name = "RSI Rete Due", url = "http://stream.srg-ssr.ch/m/retedue/aacp_32"},
    {name = "RSI Rete Tre", url = "http://stream.srg-ssr.ch/m/retetre/aacp_32"},
    {name = "RSI Rete Uno", url = "http://stream.srg-ssr.ch/m/reteuno/aacp_32"},
    {name = "RSR Couleur 3", url = "http://stream.srg-ssr.ch/m/couleur3/aacp_32"},
    {name = "RSR Espace 2", url = "http://stream.srg-ssr.ch/m/espace-2/aacp_32"},
    {name = "RSR La Premiere", url = "http://stream.srg-ssr.ch/m/la-1ere/aacp_32"},
    {name = "RSR Option Musique", url = "http://stream.srg-ssr.ch/m/option-musique/aacp_32"},
    {name = "RTN", url = "https://rtn.ice.infomaniak.ch/rtn-high.mp3"},
    {name = "RTS Couleur 3", url = "http://stream.srg-ssr.ch/m/couleur3/mp3_128"},
    {name = "RTS Espace 2", url = "http://stream.srg-ssr.ch/m/espace-2/aacp_96"},
    {name = "RTS La Première", url = "http://stream.srg-ssr.ch/m/la-1ere/mp3_128"},
    {name = "RTS Option Musique", url = "http://stream.srg-ssr.ch/m/option-musique/mp3_128"},
    {name = "Rundfunk FM", url = "http://rundfunk.ice.infomaniak.ch/rundfunk-192.mp3"},
    {name = "Skuizz Hits 90S-00S", url = "https://traxx024.ice.infomaniak.ch/traxx024-1.mp3"},
    {name = "Soul Club Radio", url = "https://a1.asurahosting.com:8430/radio.mp3"},
    {name = "Spoon Radio", url = "http://spoonradio.ice.infomaniak.ch/spoonradio-hd"},
    {name = "Spoon Radio - Acoustic Rock", url = "https://spoonradioacousticrock.ice.infomaniak.ch/spoon-acousticrock-hd.aac"},
    {name = "Spoon Radio - Alternative Rock", url = "https://spoonradioalternativerock.ice.infomaniak.ch/spoon-alternativerock-hd.aac"},
    {name = "Spoon Radio - Classic Rock", url = "https://spoonradioclassicrock.ice.infomaniak.ch/spoon-classicrock-hd.aac"},
    {name = "Spoon Radio - Hard Rock", url = "https://spoonradiohardrock.ice.infomaniak.ch/spoon-hardrock-hd.aac"},
    {name = "Spoon Radio - Modern Rock", url = "https://spoonradiomodernrock.ice.infomaniak.ch/spoon-modernrock-hd.aac"},
    {name = "Spoon Radio - Rock Ballads", url = "https://spoonradiorockballads.ice.infomaniak.ch/spoon-rockballads-hd.aac"},
    {name = "Spoon Radio Modern Rock", url = "https://spoonradiomodernrock.ice.infomaniak.ch/spoon-modernrock-hd.aac"},
    {name = "SRF 1", url = "http://stream.srg-ssr.ch/m/drs1/mp3_128"},
    {name = "SRF 2", url = "http://stream.srg-ssr.ch/m/drs2/mp3_128"},
    {name = "SRF 3", url = "http://stream.srg-ssr.ch/m/drs3/mp3_128"},
    {name = "SRF 4 News", url = "http://stream.srg-ssr.ch/m/drs4news/mp3_128"},
    {name = "SRF Musikwelle", url = "http://stream.srg-ssr.ch/m/drsmw/mp3_128"},
    {name = "SRF Virus", url = "http://stream.srg-ssr.ch/m/drsvirus/mp3_128"},
    {name = "SRF1 Radio", url = "http://stream.srg-ssr.ch/m/drs1/aacp_96"},
    {name = "SRF1 Regionaljournal Aargau Solothurn", url = "http://stream.srg-ssr.ch/m/regi_ag_so/aacp_96"},
    {name = "SWISS GROOVE", url = "https://relay2.swissgroove.ch/;"},
    {name = "Swiss Jazz Room", url = "https://stream.srg-ssr.ch/m/rsj/mp3_128"},
    {name = "Swiss Pop", url = "http://stream.srg-ssr.ch/m/rsp/aacp_96"},
    {name = "SWISSCLASSICA ITALIA", url = "http://stream.srg-ssr.ch/m/rsc_it/mp3_128"},
    {name = "Swissgroove", url = "http://158.69.74.203/"},
    {name = "Swissradio Classical", url = "http://relay.publicdomainproject.org/classical.mp3"},
    {name = "Ta Radio", url = "https://stream.taradio.ch/dab"},
    {name = "Traxx FM - Ambient", url = "http://traxx011.ice.infomaniak.ch/traxx011-low.mp3"},
    {name = "Traxx FM - Classic", url = "http://traxx012.ice.infomaniak.ch/traxx012-low.mp3"},
    {name = "Traxx FM - Cool Jam", url = "http://traxx005.ice.infomaniak.ch/traxx005-low.mp3"},
    {name = "Traxx FM - Deep", url = "http://traxx013.ice.infomaniak.ch/traxx013-low.mp3"},
    {name = "Traxx FM - Deluxe", url = "http://traxx001.ice.infomaniak.ch/traxx001-low.mp3"},
    {name = "Traxx FM - France", url = "http://traxx025.ice.infomaniak.ch/traxx025-1.mp3"},
    {name = "Traxx FM - Funk", url = "http://traxx016.ice.infomaniak.ch/traxx016-low.mp3"},
    {name = "Traxx FM - Golden Oldies", url = "http://traxx023.ice.infomaniak.ch/traxx023-1.mp3"},
    {name = "Traxx FM - House", url = "http://traxx002.ice.infomaniak.ch/traxx002-low.mp3"},
    {name = "Traxx FM - Italia", url = "http://traxx021.ice.infomaniak.ch/traxx021-1.mp3"},
    {name = "Traxx FM - Jazz", url = "http://traxx014.ice.infomaniak.ch/traxx014-low.mp3"},
    {name = "Traxx FM - Latino", url = "http://traxx008.ice.infomaniak.ch/traxx008-low.mp3"},
    {name = "Traxx FM - Latino Pop", url = "http://traxx022.ice.infomaniak.ch/traxx022-1.mp3"},
    {name = "Traxx FM - Lounge", url = "http://traxx004.ice.infomaniak.ch/traxx004-low.mp3"},
    {name = "Traxx FM - Pop", url = "http://traxx009.ice.infomaniak.ch/traxx009-low.mp3"},
    {name = "Traxx FM - Rap", url = "http://traxx015.ice.infomaniak.ch/traxx015-low.mp3"},
    {name = "Traxx FM - Rnb", url = "http://traxx007.ice.infomaniak.ch/traxx007-low.mp3"},
    {name = "Traxx FM - Rock", url = "http://traxx019.ice.infomaniak.ch/traxx019-low.mp3"},
    {name = "Traxx FM - Soul", url = "http://traxx006.ice.infomaniak.ch/traxx006-low.mp3"},
    {name = "Traxx FM - Tech Minimal", url = "http://traxx020.ice.infomaniak.ch/traxx020-low.mp3"},
    {name = "True House Chill", url = "http://stream.truehouse.net:8000/chill"},
    {name = "True House Radio", url = "http://stream.truehouse.net:8000/house"},
    {name = "Truehouse Chill", url = "http://stream.truehouse.net:8000/chill"},
    {name = "TVM 3 TV", url = "http://edge17.vedge.infomaniak.com/livecast/tvm3/playlist.m3u8"},
    {name = "URBN Radio", url = "https://dr2101.ice.infomaniak.ch/dr2103.mp3"},
    {name = "Vertical Radio", url = "http://verticalradio.ice.infomaniak.ch/verticalradio-128.mp3"},
    {name = "Vibración Latina", url = "http://vibration.stream2net.eu:8410/;stream/1"},
    {name = "Vibration 108", url = "http://vibration108-high.ice.infomaniak.ch/vibration108-high.mp3"},
    {name = "Vibration Chanson Française", url = "http://vibration.stream2net.eu:8510/;stream/1"},
    {name = "Vibration FM", url = "http://vibration-aac.stream2net.eu:8040/vibra108-64k.mp3"},
    {name = "Vibration Gayradio", url = "http://vibration.stream2net.eu:8480/;stream/1"},
    {name = "Vibration Poprock", url = "http://vibrationpoprock.ice.infomaniak.ch/vibrationpoprock-high.mp3"},
    {name = "Vibration Soft Hits", url = "http://vibration.stream2net.eu:8350/;stream/1"},
    {name = "Vibration Vintage", url = "http://vibrationvintage-high.ice.infomaniak.ch/vibration-vintage.mp3"},
    {name = "Vibration Zen Relax", url = "http://vibration.stream2net.eu:8220/;stream/1"},
    {name = "Vintage Radio", url = "https://vintageradio.ice.infomaniak.ch/vintageradio-high.mp3"},
    {name = "Virgin Radio Switzerland", url = "https://chmedia.streamabc.net/79-virginrockch-mp3-192-2872456?sABC=66pp62r5%230%232qqpnss01895rqr0s8oq129o03s183o0%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724670693"},
    {name = "Virginradio", url = "https://chmedia.streamabc.net/79-virginrockch-mp3-192-2872456?sABC=66pp926p%230%236080533n48sp2nrq0o4389q6o67o3qps%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1724682860"},
    {name = "VOXINOX", url = "http://voxinox.ice.infomaniak.ch/voxinox-128"},
    {name = "WALTS WELT", url = "https://waltswelt.out.airtime.pro/waltswelt_a?_ga=2.33964516.474222732.1669644968-446937151.1669306237"},
    {name = "World Radio Switzerland", url = "https://uksouth.streaming.broadcast.radio:10290/wrs"},
}

return stations
