local stations = {
    {name = "102.3 FM CORONILLA", url = "https://streaming01.shockmedia.com.ar/9184/stream"},
    {name = "24 de Agosto", url = "https://24deagosto-zikoxweb.radioca.st/stream"},
    {name = "89.3 Del Molino FM", url = "http://stream-176.zeno.fm/8s61u5bvlvytv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI4czYxdTVidmx2eXR2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkhXQ2xuSXJ1U0tDSGVzc3RZRUZ5bVEiLCJpYXQiOjE3MjQ2OTQxMzAsImV4cCI6MTcyNDY5NDE5MH0.Fh1vX-EAsYqGiVk5Ur71V44-00LTUR0A-KsDL25-gKI"},
    {name = "970 Universal", url = "https://970universal-3.nty.uy/"},
    {name = "Aire FM 100.3 FM", url = "https://airefm-1.nty.uy/:8030/;"},
    {name = "Alfa FM", url = "https://rfm.radio.netgate.com.uy:8443/alfafm"},
    {name = "Alfa FM 96.3", url = "http://radioonline.netgate.com.uy:8000/alfafm"},
    {name = "Amatista FM 90.7", url = "http://usa15.ciudaddigital.com.uy:8044/AmatistaFM"},
    {name = "America FM", url = "http://emisiones.com.uy:8118/america"},
    {name = "América FM 103.3", url = "http://emisiones.com.uy:8118/america"},
    {name = "ARAPEY (AM 1450)", url = "http://emisiones.com.uy:8085/arapey"},
    {name = "Armonía FM 92.5", url = "http://usa15.ciudaddigital.com.uy:8132/ArmoniaFM"},
    {name = "Aspen Punta", url = "https://streaming2.hostingmontevideo.com:7010/;"},
    {name = "Aspen Punta 103.5 FM", url = "https://streaming2.hostingmontevideo.com:7010/;"},
    {name = "Atlantida FM 89.9", url = "http://server-uk1.radioseninternet.net:8034/;"},
    {name = "Azul FM 101.9", url = "https://azul-2.nty.uy/"},
    {name = "Azul Punta del Este 93.5", url = "https://icecasthd.net/proxy/azulp/live"},
    {name = "Azul Punta del Este 93.5", url = "https://icecasthd.net/proxy/azulp/live"},
    {name = "Babel", url = "https://radios.iwstreaming.uy/8030/stream"},
    {name = "Bohemia FM", url = "https://radiopro.com.uy/radio/8000/bohemia"},
    {name = "Bohemia FM 98.9", url = "https://radiopro.com.uy/radio/8000/bohemia"},
    {name = "Boliche Radio", url = "https://streaming1.locucionar.com/proxy/bolicheradio?mp=/stream"},
    {name = "Cadena del Mar 106.5 FM", url = "http://streamingraddios.online:9455/;"},
    {name = "Casino FM (Paysandú) 96.3", url = "https://audio-edge-w4d68.yul.o.radiomast.io/dc38795c-3ef6-44b1-b861-97821b234e1d"},
    {name = "Casupá FM 94.1", url = "https://stm1.ifantasy.com.br:7256/;"},
    {name = "Causes FM 89.1", url = "https://streaming.radiosenlinea.com.ar/8870/stream"},
    {name = "Cien Punto Cinco", url = "http://emisiones.com.uy:8143/cien"},
    {name = "Clásica 650 AM", url = "https://radios.iwstreaming.uy/8032/stream"},
    {name = "colonia am 550", url = "https://27273.live.streamtheworld.com:443/COLONIA_ADP.aac"},
    {name = "Color FM 90.3", url = "http://server-uk1.radioseninternet.net:8018/;"},
    {name = "Columbia FM 88.5", url = "https://stm.gmpro.top:7008/;"},
    {name = "Conaicop", url = "http://stream-171.zeno.fm/w5k0y0qbft5tv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ3NWsweTBxYmZ0NXR2IiwiaG9zdCI6InN0cmVhbS0xNzEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjJYSTV0ZHhOVGdTMy1nVUNDMXY1M2ciLCJpYXQiOjE3MjQ2NTg2ODAsImV4cCI6MTcyNDY1ODc0MH0.-LBg2xya-82_yvU-Joose_rstRBzaqFXH8mycySNdyc"},
    {name = "Concierto FM 95.1", url = "https://conectperu.com/8012/stream"},
    {name = "CX 10 Continente", url = "http://cx10continente.com:8152/"},
    {name = "CX 10 Continente", url = "https://cast.tunzilla.com/http://cx10continente.com:8152/;"},
    {name = "CX 30 Radio Nacional", url = "https://a1.asurahosting.com:8650/radio.mp3"},
    {name = "CX 40 Radio Fenix", url = "https://sp3.servidorrprivado.com/8070/;"},
    {name = "CX 46 Radio America ", url = "https://america-2.nty.uy/stream"},
    {name = "CX 580 Radio Rural", url = "https://radiolatina.live/9206/stream"},
    {name = "CX12 Radio Oriental 770 AM", url = "http://radiolatina.live:7906/1"},
    {name = "CXC - 253A ADEOM FM 98.5", url = "http://158.106.131.228:9080/;"},
    {name = "Del Plata FM 95.5", url = "https://alba-uy-delplata-delplata.stream.mediatiquestream.com/index.m3u8"},
    {name = "Del Plata FM 95.5", url = "https://alba-uy-delplata-delplata.stream.mediatiquestream.com/index.m3u8"},
    {name = "Del Sol FM", url = "https://delsol-1.nty.uy/?type=http&nocache=2780&dbl=0"},
    {name = "Del Sol FM", url = "http://radio.dl.uy:9950/radio"},
    {name = "Delta FM 88.3", url = "http://server-uk1.radioseninternet.net:8104/;"},
    {name = "Diamante FM 98.7", url = "https://radiolatina.live/8058/stream"},
    {name = "Diamante FM 98.7", url = "https://radiolatina.live/8058/stream"},
    {name = "Difusora Treinta y Tres 1390 AM", url = "https://server-usa2.radioseninternet.net/8132/stream"},
    {name = "DifusoraSoriano 1210 AM", url = "http://usa15.ciudaddigital.com.uy:8094/DifusoraSoriano"},
    {name = "El Aguantadero", url = "https://vps-6de10815.vps.ovh.ca:10943/"},
    {name = "El bloque radio", url = "https://vivo.solumedia.com:19360/elbloque/elbloque.m3u8"},
    {name = "El Espectador 810", url = "https://espectador-1.nty.uy/"},
    {name = "El Libertador", url = "https://streamingraddios.online/proxy/llamadad?mp=/stream"},
    {name = "El Libertador 1210 AM", url = "https://streamingraddios.online/proxy/llamadad?mp=/stream"},
    {name = "El Puente FM 103.3", url = "https://as100.globalhost1.com/8082/stream"},
    {name = "Emisora del Sur", url = "https://radios.iwstreaming.uy/8034/stream"},
    {name = "Emisora Galaxia FM 105.9", url = "https://stream-153.zeno.fm/7pgbbcnpvgkuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI3cGdiYmNucHZna3V2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InAwOE9oTlNlU0xTa2NfbDBZLVVqOVEiLCJpYXQiOjE3MjQ2ODYxMzksImV4cCI6MTcyNDY4NjE5OX0.8PGyvS0GOKqRn5GrPc-OSdQ6bP4qCkG38q96ljybdSY"},
    {name = "Emisora Principal", url = "https://s7.myradiostream.com/:10764/listen.mp3?ver=755704?nocache=1724693683"},
    {name = "ESPACIO SPORT 91.5 FM", url = "https://medios.ciudaddigital.com.uy:18098/EspacioFM"},
    {name = "Espika FM 90.7", url = "https://stream.radios.red/espikafm.mp3"},
    {name = "Esteña FM 103.1", url = "https://radiopro.com.uy/radio/8060/estena"},
    {name = "Exa FM", url = "https://14553.live.streamtheworld.com:443/XHPSFMAAC.aac"},
    {name = "Exito - FM 99.7", url = "http://salida.stream.com.uy:8506/stream"},
    {name = "Exito FM 99.7", url = "https://salida.stream.com.uy:8506/stream"},
    {name = "Felicidad - AM 1240", url = "http://medios.ciudaddigital.com.uy:8042/Felicidad"},
    {name = "FM Azul", url = "https://azul-1.nty.uy/"},
    {name = "FM Ciudadela 88.7", url = "https://streaming1.locucionar.com/proxy/fmciudadela887?mp=/stream"},
    {name = "FM Claridad 88.7", url = "https://streaming2.hostingmontevideo.com:7009/;"},
    {name = "FM cordialidad 94.9", url = "https://cordialidad-zikoxweb2.radioca.st/stream"},
    {name = "FM Digital 100.1", url = "https://sh1.radioonlinehd.com:8001/stream"},
    {name = "Fm Gente", url = "https://cast1.asurahosting.com/proxy/luis1/stream"},
    {name = "FM HIT 90.3 Uruguay", url = "https://hit-1.nty.uy/stream"},
    {name = "Fm Inolvidable 93.1", url = "https://inolvidable-2.nty.uy/"},
    {name = "Fm Inolvidable 93.1", url = "https://inolvidable-2.nty.uy/"},
    {name = "FM La Ley", url = "https://streaming2.locucionar.com/proxy/laleyfm?mp=/stream"},
    {name = "Fm Like Uruguay", url = "https://alba-uy-fmlike-likefm.stream.mediatiquestream.com/index.m3u8"},
    {name = "FM Naturaleza 88.1", url = "http://stm.gmpro.top:7006/"},
    {name = "Horizonte - FM 106.3", url = "http://1063fm.ddns.net:8025/online"},
    {name = "INOLVIDABLE FM", url = "https://inolvidable-1.nty.uy/"},
    {name = "La Clave Uruguay 92.9 FM", url = "https://stream-153.zeno.fm/ndwvn44vebruv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJuZHd2bjQ0dmVicnV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImFZc1RaX2ZvVEV1QzgxSVdRWUF3bEEiLCJpYXQiOjE3MjQ2Njg2NDgsImV4cCI6MTcyNDY2ODcwOH0.RQPrH8LAalOduvmBvgYkmnzDuYv-9DL4LNXXvBMsw6Q"},
    {name = "La Costa Fm 88.3", url = "https://lacostafm-2.nty.uy/"},
    {name = "La Costa Fm 88.3", url = "https://lacostafm-2.nty.uy/"},
    {name = "La Elegida FM", url = "https://stm1.srvif.com:7042/"},
    {name = "La Elegida FM", url = "https://stm1.srvif.com:7042/;"},
    {name = "La Galena", url = "https://stream-151.zeno.fm/5w05yazgyy8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI1dzA1eWF6Z3l5OHV2IiwiaG9zdCI6InN0cmVhbS0xNTEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IllaMDdWODRTUnpXdElTbkdwUUlEbUEiLCJpYXQiOjE3MjQ2NDU2MjAsImV4cCI6MTcyNDY0NTY4MH0.qfU2bayWcTYoRcDEPnln_B2hYyQ_MpfBEUQv_5GPrb4"},
    {name = "La Isla Radio Online Del Uruguay", url = "http://lirodu.zapto.org:8000/laislaradio"},
    {name = "La Nueva del Sur", url = "http://stream-176.zeno.fm/s6hdmgb9na0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJzNmhkbWdiOW5hMHV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImNzX0FfMzd6UXBHY3d3NWw1eTQ1ZXciLCJpYXQiOjE3MjQ2ODY5MDYsImV4cCI6MTcyNDY4Njk2Nn0.DRWJIHtfZGFwaXTGZ9gsCKdj1cgCXPZi0Ga7lHFNVco"},
    {name = "La Otra - FM 104.5", url = "https://cento02.mipanelradio.com/proxy/fmlaotra?mp=/stream"},
    {name = "La R - 1410 AM", url = "https://la1410-2.nty.uy/"},
    {name = "LA VEREDA WEB RADIO", url = "https://srv2.radiostreamuy.com/8012/stream"},
    {name = "La Voz De Melo", url = "https://stream-157.zeno.fm/fzc86k96yy8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJmemM4Nms5Nnl5OHV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlpTLV9LVnNGU0lTTThLLW1UYzZUZXciLCJpYXQiOjE3MjQ2ODg3OTksImV4cCI6MTcyNDY4ODg1OX0.ttQ8KiscaYyhrtIDL-j6sYOKBFte8zQHx-UDf7r2Jb8"},
    {name = "La voz de Paysandú - AM 1320", url = "http://salida.stream.com.uy:8508/stream"},
    {name = "Laser FM", url = "https://server.laradio.online/proxy/eduardo_correa?mp=/stream"},
    {name = "Latina - FM 95.3", url = "http://medios.ciudaddigital.com.uy:8168/LatinaFM"},
    {name = "Libertador 92.3 FM", url = "https://fmlibertador-zikoxweb2.radioca.st/stream"},
    {name = "M24 · La radio que nos mueve (97.9  / 102.5 )", url = "https://streaming1.hostingmontevideo.com/8034/stream"},
    {name = "Mega FM", url = "https://radio.cimaspeed.com/8070/stream"},
    {name = "Metropolis 104.9", url = "https://metropolis-web-1.nty.uy/"},
    {name = "Metropolis 104.9", url = "https://metropolis-web-1.nty.uy/"},
    {name = "Metropolis Punta 95.9", url = "https://metropolis-web-1.nty.uy/"},
    {name = "Metropolis Punta 95.9", url = "https://metropolis-web-1.nty.uy/"},
    {name = "Montevideo Jazz Radio", url = "http://stream-172.zeno.fm/2ykx0xbm6gruv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIyeWt4MHhibTZncnV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjE0c0dTemNaUTNpQ08xTXFwdU9ZcWciLCJpYXQiOjE3MjQ2OTgwMTIsImV4cCI6MTcyNDY5ODA3Mn0.HWyNUt6VxdmU-AkwP35Lm-n2RMuRyG_6Cu8ZbgZHoSk&rj-ttl=5&amp=&rj-tok=AAABgdsb5DoAz8MV8KJpNVyteA"},
    {name = "Mundo fm", url = "http://emisiones.com.uy:8088/mundo"},
    {name = "Mundo FM 107.9", url = "https://emisiones.com.uy:8154/mundo"},
    {name = "mundo fm uruguay", url = "http://emisiones.com.uy:8088/mundo"},
    {name = "Oceano FM", url = "https://oceano-2.nty.uy/"},
    {name = "Oldies FM", url = "https://hit-1.nty.uy/stream"},
    {name = "Perfil FM", url = "https://radiosar.com:8086/stream"},
    {name = "Power Hits Uruguay", url = "https://stream-176.zeno.fm/9dwe227jejgtv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5ZHdlMjI3amVqZ3R2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlVJYTFTTDNMVENldUZYWmNoUmJPT1EiLCJpYXQiOjE3MjQ2ODI5ODksImV4cCI6MTcyNDY4MzA0OX0.X9Q3RbKYIRwLi_Oqre6u7o9UtCuSjwKtV5IHSmuVfIw"},
    {name = "Power Hits Uruguay", url = "https://stream-176.zeno.fm/9dwe227jejgtv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5ZHdlMjI3amVqZ3R2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImtYU0tuU3lrUnBDQXZKZXh4TmlDRkEiLCJpYXQiOjE3MjQ2NzQ2NjksImV4cCI6MTcyNDY3NDcyOX0.OIxBAfO2lrR0rCFhqJsf-znA8U7I2acQ2Fio7FqQ1dU"},
    {name = "Radio 41", url = "https://stream20.usastreams.com:7008/;"},
    {name = "Radio Acuarela", url = "http://204.197.245.100:8280/;"},
    {name = "Radio Carmelo", url = "https://server.laradio.online/proxy/martin_barragan05?mp=/stream"},
    {name = "Radio Centenario CX36 1250 AM", url = "http://rfm.radio.netgate.com.uy:8000/centenario"},
    {name = "Radio Chiveo", url = "https://comodin.uy/listen/chiveo/128.mp3"},
    {name = "Radio Chiveo", url = "https://comodin.uy/listen/chiveo/128.mp3"},
    {name = "Radio Chiveo", url = "https://comodin.uy/listen/chiveo/320.mp3"},
    {name = "Radio Clarin", url = "https://radioclarin-zikoxweb.radioca.st/stream"},
    {name = "Radio Continental 1600 AM Pando", url = "https://server-usa2.radioseninternet.net/9316/stream"},
    {name = "Radio Cristal AM 1470 - Las Piedras ", url = "https://medios.ciudaddigital.com.uy:18126/CristalAM"},
    {name = "Radio Cultura 1290 AM", url = "https://radios.iwstreaming.uy/8034/stream"},
    {name = "Radio Cultura AM 1280", url = "https://radios.iwstreaming.uy/8034/stream"},
    {name = "Radio Difusora 33", url = "https://server-usa2.radioseninternet.net/8132/stream"},
    {name = "Radio Disney Uruguay ", url = "https://21933.live.streamtheworld.com/DISNEY_URY_MVAAC/HLS/playlist.m3u8"},
    {name = "Radio Disney Uruguay ", url = "https://21933.live.streamtheworld.com/DISNEY_URY_MVAAC/HLS/playlist.m3u8"},
    {name = "Radio El Espectador", url = "https://espectador-1.nty.uy/"},
    {name = "Radio Extremo FM 100.9", url = "http://emisiones.com.uy:8111/bour"},
    {name = "Radio Fm 99.1", url = "https://rr5100.globalhost1.com/8454/stream"},
    {name = "Radio Futura - 91.1 FM", url = "https://alba-uy-radiofutura-futura.stream.mediatiquestream.com/index.m3u8"},
    {name = "Radio La Zurda", url = "https://radios.solumedia.com:6270/stream"},
    {name = "RADIO MARIA URUGUAY", url = "http://dreamsiteradiocp.com:8088/stream"},
    {name = "Radio Nuevo Tiempo Uruguay", url = "https://stream.live.novotempo.com/radio/smil:rntMontevideoUY.smil/playlist.m3u8"},
    {name = "Radio Paris100.7", url = "https://stream-174.zeno.fm/a708v4pexf9uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhNzA4djRwZXhmOXV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik00OEJXMVljUXUydHpNUS1XY2VKX3ciLCJpYXQiOjE3MjQ2Nzc4NDYsImV4cCI6MTcyNDY3NzkwNn0.CUEXKG3X5ya3hzXbStR6UJyaqOBT_3mS6OgYPwHBp3s"},
    {name = "Radio Patria", url = "https://medios.ciudaddigital.com.uy:18052/PatriaAM"},
    {name = "Radio Pedal", url = "https://streaming1.hostingmontevideo.com:7003/stream.mp3"},
    {name = "Radio Pipí Cucú", url = "https://comodin.uy/radio/8000/320.mp3"},
    {name = "Radio Pipí Cucú", url = "https://comodin.uy/hls/pipi_cucu/live.m3u8"},
    {name = "Radio Pipí Cucú (128 kbps)", url = "https://comodin.uy/radio/8000/128.mp3"},
    {name = "Radio Positiva", url = "https://stream-174.zeno.fm/6g9bu044cxhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI2ZzlidTA0NGN4aHZ2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImROVGdyNU5hUnFLYW5TR0M3ejkya3ciLCJpYXQiOjE3MjQ2NDQ5NDIsImV4cCI6MTcyNDY0NTAwMn0.G_thWtQxgUTtgBm6RkFZiHleTJyscHLy__C32kLatG4"},
    {name = "Radio Prado Sur", url = "https://usa2.fastcast4u.com/proxy/wqzjjais?mp=/;"},
    {name = "Radio Río Branco", url = "https://medios.ciudaddigital.com.uy:18164/RioBranco"},
    {name = "Radio Rivera CX144 AM 1440", url = "http://usa15.ciudaddigital.com.uy:8060/RiveraAM"},
    {name = "Radio San Carlos", url = "http://198.49.65.43:10396/;"},
    {name = "Radio Uno FM", url = "http://radio.hostlagarto.com:9822/"},
    {name = "Radio Uruguay 1050", url = "https://radios.iwstreaming.uy/8036/stream"},
    {name = "RadioBunker", url = "https://radio.buzon.uy/bunker"},
    {name = "Radiomundo 1170 AM - En Perspectiva", url = "https://edge.mixlr.com/channel/nuuij"},
    {name = "Reggaeton UY", url = "https://stream-154.zeno.fm/g5imua2agz9uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJnNWltdWEyYWd6OXV2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImR4UUJmUnROVDNHTzQ2elBrRXV3UXciLCJpYXQiOjE3MjQ2OTA5NzQsImV4cCI6MTcyNDY5MTAzNH0.31r_BxW0Vf9D6XIPbkYM6-KaqOjPuU1yYADFx9SqmCw"},
    {name = "Ruta FM", url = "http://204.197.245.100:8260/;"},
    {name = "Santa Isabel FM 100.1", url = "http://emisiones.com.uy:8101/san"},
    {name = "Sarandí 690", url = "https://alba-uy-sarandi-sarandi.stream.mediatiquestream.com/index.m3u8"},
    {name = "siglo 21 fm", url = "https://emisiones.com.uy:5120/siglo"},
    {name = "Sport 890", url = "https://alba-uy-sport890-sport890.stream.mediatiquestream.com/index.m3u8"},
    {name = "Sport 890", url = "https://alba-uy-sport890-sport890.stream.mediatiquestream.com/index.m3u8"},
    {name = "Stereo Tropical Radio", url = "http://144.91.98.151:8023/live"},
    {name = "ZOE FM 91.5", url = "https://sp.unoredcdn.net/8012/stream"},
    {name = "Zorrilla de San Martin", url = "https://server-usa2.radioseninternet.net/9312/stream"},
}

return stations
