return {
    ['bolivarian_republic_of_venezuela'] = {
        { n = '1027 DIGITAL FM', u = 'https://cp4.lorini.net:36187/stream' },
        { n = '935 La Gran FM', u = 'https://stream-55.zeno.fm/hcddm386za0uv? zs=_PyMMSYIRRmVntwZ85BL8g' },
        { n = '973 FM Maracay', u = 'http://station.asawstreaming.com:8010/;' },
        { n = 'Acción 1045 FM La Diferencia En El Dial', u = 'https://stream.intervalohost.com/accionfm/stream' },
        { n = 'Activa 889FM', u = 'https://stream.zeno.fm/w3gzdxagmh0tv' },
        { n = 'Activa FM 1049', u = 'https://stream.zeno.fm/t31pbasum7zuv' },
        { n = 'Adulto Joven 881', u = 'https://server6.globalhostla.com:9168/stream' },
        { n = 'Alba Ciudad 963 FM', u = 'https://envivo.albaciudad.org/albaciudad.mp3' },
        { n = 'Alba Ciudad Radio 936 Fm16K', u = 'https://envivo.albaciudad.org/alba16.mp3' },
        { n = 'Amiga FM 939', u = 'https://stream.zeno.fm/dr612ew61rhvv' },
        { n = 'Andes 893 FM', u = 'http://streamingned.com:7098/;' },
        { n = 'Aragueña FM 995', u = 'https://stream.zeno.fm/1crdje0gynatv' },
        { n = 'Audaz FM 945', u = 'https://servers58.com/proxy/audaz?mp=/stream' },
        { n = 'Autentica 1075 FM', u = 'https://stream.zeno.fm/8v5et2n6bzzuv' },
        { n = 'AUTENTIK 1007 FM', u = 'https://server6.globalhostla.com:9228/stream' },
        { n = 'Autopista Estereo 1047 Fm', u = 'https://server6.globalhostla.com:9486/stream' },
        { n = 'Bahiafmnet', u = 'https://laradiossl.online:10379/live' },
        { n = 'Baladas Y Algo Mas', u = 'http://streamingned.com:7286/;' },
        { n = 'BANDERA 1057 FM', u = 'http://streamingned.com:7148/;' },
        { n = 'Bella FM 969', u = 'https://server6.globalhostla.com:9380/stream' },
        { n = 'Betel 1021 FM', u = 'https://stream.zeno.fm/npnxhehm64zuv' },
        { n = 'C-Oye 891 FM', u = 'http://streamingned.com:7146/;' },
        { n = 'CADENA DIGITAL FM 995', u = 'https://server6.globalhostla.com:9288/stream' },
        { n = 'Calle FM', u = 'https://cloudstream2030.conectarhosting.com/8076/;' },
        { n = 'CANAIMA STEREO', u = 'https://stream.zeno.fm/cd7isb0ojlruv' },
        { n = 'Candela Pura 919 FM', u = 'https://server6.globalhostla.com:9020/stream' },
        { n = 'Capital 999 FM', u = 'http://live2.rcast.net:8520/;stream.mp3' },
        { n = 'Cardenales 921 FM', u = 'https://sp4.colombiatelecom.com.co/8082/stream' },
        { n = 'CDR 987 FM', u = 'https://laradiossl.online:8347/;' },
        { n = 'Cima 951 FM', u = 'https://stream.zeno.fm/naa84dtd6f8uv' },
        { n = 'Circuito Comunión Nueva Bolivia 931 FN', u = 'https://stream.zeno.fm/abkmpazmyk8uv' },
        { n = 'Circuito Comunión Santa Elena De Arenales 1011 FM', u = 'https://stream.zeno.fm/ksh16ht4na0uv' },
        { n = 'CIRCUITO DINAMICA 939 FM', u = 'https://acp2.lorini.net:30090/stream' },
        { n = 'CIRCUITO DINAMICA 955 FM', u = 'https://acp2.lorini.net:41066/stream' },
        { n = 'Circuito X', u = 'http://cp2.lorini.net:39500/stream' },
        { n = 'Circuito X 897 FM', u = 'http://cp2.lorini.net:39500/;mp312844|mp312844' },
        { n = 'Clasicos 909 FM El Tigre', u = 'http://acp2.lorini.net:2030/clasicoseltigre' },
        { n = 'Comunion 975 Fm', u = 'https://stream.zeno.fm/cy3ef0frwmzuv' },
        { n = 'Contacto FM 937', u = 'https://laradiossl.online:10058/;' },
        { n = 'Cool Radio Web', u = 'https://stream.zeno.fm/omuwlrerlxhvv' },
        { n = 'Costa 1055 FM', u = 'https://stream.zeno.fm/ixlhtprdocktv' },
        { n = 'Costa Del Sol 931 FM', u = 'https://cast4.asurahosting.com/tunein/sol.pls' },
        { n = 'COSTERA 1027 FM', u = 'https://streamingned.com:7112/stream' },
        { n = 'DECIBEL 887 FM', u = 'https://stream.zeno.fm/b8xv6835gd0uv' },
        { n = 'Diamante FM 919', u = 'https://stream.zeno.fm/n4tcsndvtxhvv' },
        { n = 'Digital FM 969', u = 'https://server6.globalhostla.com:9240/stream' },
        { n = 'Dinamik 899 FM', u = 'https://stream.zeno.fm/wmnqq0m2uk8uv' },
        { n = 'Dj Shaggy Venezuela', u = 'http://51.255.123.116:9226/' },
        { n = 'DJ Shaggy Venezuela Radio', u = 'https://laradiossl.online:9226/;' },
        { n = 'Electrik 977 FM', u = 'https://streamingned.com:7044/stream' },
        { n = 'Elite 1037 FM', u = 'https://stream.zeno.fm/awromk7ut4svv' },
        { n = 'Esencia 887 FM', u = 'https://stream.zeno.fm/lozraai0qlgvv' },
        { n = 'Espacio 961 FM', u = 'https://radiointernet.co/8004/stream' },
        { n = 'Espacio Network', u = 'https://acp2.lorini.net:28050/stream' },
        { n = 'Espectaculo 1007 FM', u = 'https://laradiossl.online:10583/?_=2#.mp3' },
        { n = 'Exa FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac' },
        { n = 'EXITOS 1009 FM', u = 'https://radio.webtuya.com/8076/stream' },
        { n = 'EXITOS 953 FM', u = 'https://acp4-cdn.lorini.net/proxy/10004?mp=/stream' },
        { n = 'Extremo 895 FM', u = 'https://c2.radioshdstreaming.com:8190/extremo.aac' },
        { n = 'Fama 981 FM', u = 'https://server6.globalhostla.com:9356/stream' },
        { n = 'Favorita 1061 FM', u = 'https://sp.wnetserver.com/8046/stream' },
        { n = 'Felina Estéreo', u = 'https://servers58.com/proxy/felinaestereo?mp=//;type=mp3' },
        { n = 'Fiesta 1059 FM', u = 'https://stream.zeno.fm/et7xq0a4p48uv' },
        { n = 'Fiesta 1065 FM – CARACAS', u = 'https://server6.globalhostla.com:9012/stream' },
        { n = 'Fiesta 891 FM', u = 'https://acp2.lorini.net:36050/stream' },
        { n = 'Fiesta Latina 1061 FM', u = 'https://stream.zeno.fm/e2kzfpr34d0uv' },
        { n = 'FM Mundial 1041', u = 'https://onlineradiobox.com/json/ve/lafmmundial/play?platform=web' },
        { n = 'Guanareña 983 FM', u = 'https://laradiossl.online:10175/?_=1#.mp3' },
        { n = 'Hot 941', u = 'https://server6.globalhostla.com:9016/stream' },
        { n = 'IMPACTO RADIO 973 FM', u = 'https://server6.globalhostla.com:9414/stream' },
        { n = 'La Cumanesa 1053', u = 'https://laradiossl.online:10774/live' },
        { n = 'La Mega 1073', u = 'https://acp4.lorini.net/proxy/ur2050?mp=/stream' },
        { n = 'La Mega 965 Maracay', u = 'https://acp4-cdn.lorini.net/proxy/15010?mp=/stream' },
        { n = 'La Romantica 889', u = 'https://server6.globalhostla.com:8068/stream' },
        { n = 'Lasser 977 FM', u = 'https://server6.globalhostla.com:8010/stream' },
        { n = 'Magic Radio 925 Maracay', u = 'https://cloudstream2030.conectarhosting.com/8324/;' },
        { n = 'Maxi Radio Digital', u = 'https://guri.tepuyserver.net/8010/stream' },
        { n = 'Onda 1079 La Superestación', u = 'https://acp4.lorini.net/proxy/ur2060?mp=/stream' },
        { n = 'Orbita 1075 FM Puerto La Cruz', u = 'https://cast20.plugstreaming.com:2000/stream/orbitaplc/;' },
        { n = 'Orbita 901 FM El Tigre', u = 'https://cast20.plugstreaming.com:2020/stream/orbitaeltigre/;' },
        { n = 'Orbita FM 963 Anaco', u = 'https://cast10.plugstreaming.com:2000/stream/orbitaanaco/;' },
        { n = 'Planeta 1053 Caracas FM', u = 'https://cast10.plugstreaming.com:2020/stream/planetafm/;' },
        { n = 'PLENITUD 909', u = 'https://sp.wnetserver.com/8060/stream' },
        { n = 'Radio 2000', u = 'https://streaming.adclichosting.com:8030/radio2000.mp3' },
        { n = 'RADIO ACTIVA 1035 MERIDA', u = 'https://stream.zeno.fm/3gch5vc20a0uv' },
        { n = 'Radio Dinámica 1490AM', u = 'https://guri.tepuyserver.net/8040/stream' },
        { n = 'Radio Dinámica 929', u = 'https://guri.tepuyserver.net/8012/stream' },
        { n = 'RADIO EDUCATIVA DE VENEZUELA', u = 'https://stream.zeno.fm/8vd9wvkvv8jvv' },
        { n = 'Radio Nacional De Venezuela', u = 'http://rnv.lorini.net:29100/RNVINFORMATIVO' },
        { n = 'Radio Okey 1049 Tucupita', u = 'https://stream-150.zeno.fm/9v1hr7ekzk8uv?zs=OUXqin1ySEe0qxB9jq6byQ' },
        { n = 'Radio Rio 1069 FM', u = 'https://live.ajfnetwork.com.ve/8010/stream' },
        { n = 'RADIO RUMBOS 670 AM', u = 'https://stream.zeno.fm/c3q3w8zfe18uv?triton-uid-cookie:0fae79a4-e789-4b9b-9ca7-d30ae705f0a6' },
        { n = 'Radio Sol 891', u = 'https://stream-67.zeno.fm/r2errtf2uk8uv' },
        { n = 'Radio Sol 891 Maturin', u = 'https://stream-67.zeno.fm/r2errtf2uk8uv? zs=7GPKP3MTQtWE9TZYVk5Khg' },
        { n = 'Radio Sonora 995 FM', u = 'http://stream.zeno.fm/n8zghua6u68uv' },
        { n = 'Radioalterna', u = 'https://server01.heplayer.com:7027/' },
        { n = 'Redpres Radio', u = 'https://stream.zeno.fm/qjgbevaswlfuv/' },
        { n = 'RNV Activa', u = 'http://rnv.lorini.net:29010/RNVACTIVA' },
        { n = 'Rocafm Clasicos Caracas', u = 'http://protostar.shoutca.st:8370/' },
        { n = 'RQ 910 AM', u = 'http://streaming3.globalhost.net.ve:9014/stream' },
        { n = 'Rumba 1001 Barquisimeto FM', u = 'https://cast10.plugstreaming.com:2020/stream/r1001/;' },
        { n = 'Rumba 1049 Anzoategui FM', u = 'https://cast10.plugstreaming.com:2020/stream/r1049/;' },
        { n = 'Rumba 981 FM', u = 'https://cast20.plugstreaming.com:2020/stream/r981/;' },
        { n = 'Tecnologica 931 FM', u = 'https://streamingned.com:7118/;' },
        { n = 'Tu Amiga Radio', u = 'https://audio0stream.com:8010/turadioamiga' },
        { n = 'VTV Venezuela', u = 'https://radio.gmsiptv.com/vtvve' },
        { n = 'Zona Musical Fm', u = 'https://stream-149.zeno.fm/t9fhqcsiao2uv?zs=gyKTx5SuR4SIvrC0xE8KfQ' },
        { n = 'Éxitos 1031 FM', u = 'http://ur58.lorini.net:50004/EXITOS1031FM.aac' },
        { n = 'Éxitos 897 FM', u = 'https://acp4-cdn.lorini.net/proxy/30000?mp=/stream' },
        { n = 'Éxitos 905 FM', u = 'https://acp4-cdn.lorini.net/proxy/10109?mp=/stream' },
        { n = 'Éxitos 931 Maracay', u = 'https://acp4-cdn.lorini.net/proxy/15012?mp=/stream' },
        { n = 'Éxitos 997 FM', u = 'https://acp4-cdn.lorini.net/proxy/25006?mp=/stream' },
        { n = 'Éxitos 999', u = 'https://acp4.lorini.net/proxy/ur2070?mp=/stream' },
    }
}
