return {
    ['chile'] = {
        { n = '1009 Play FM', u = 'https://mdstrm.com/audio/5c8d6406f98fbf269f57c82c/icecast.audio' },
        { n = 'Activa', u = 'http://provisioning.streamtheworld.com/pls/ACTIVA.pls' },
        { n = 'Actual Fm', u = 'http://archi-us.digitalproserver.com/actual.aac' },
        { n = 'ADN', u = 'https://27413.live.streamtheworld.com/ADNAAC.aac' },
        { n = 'ADN Radio', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/ADNAAC.aac' },
        { n = 'Almeyda', u = 'https://sonic.streamingchilenos.com/9974/stream.aac' },
        { n = 'Alta Fidelidad Radio', u = 'https://s21.myradiostream.com/14464/?type=http&nocache=1724080980?0.022147003328686576' },
        { n = 'Alternativa FM', u = 'https://radio.tvstream.cl/8056/stream' },
        { n = 'BEAT FM - La Radio Que Te Mueve - Valle Aconcagua 987', u = 'https://audio.streaminghd.cl:2000/stream/beatfm-sanfelipe' },
        { n = 'Beethoven - Santiago FM', u = 'https://unlimited4-us.dps.live/beethovenfm/aac/icecast.audio' },
        { n = 'Bio Bio Valparaíso', u = 'http://unlimited11-cl.dps.live/biobiovalparaiso/aac/icecast.audio' },
        { n = 'Biobio Chile', u = 'https://unlimited3-cl.dps.live/biobiosantiago/aac/icecast.audio' },
        { n = 'BLUFM', u = 'https://sonic.nnw.cl:7009/;' },
        { n = 'Bonita', u = 'https://sonicpanel.chileservidores.cl/8032/stream' },
        { n = 'Boogaclub', u = 'http://stream.zeno.fm/777prr0xfm8uv' },
        { n = 'Bío-Bío Concepción 981', u = 'https://unlimited3-cl.dps.live/biobioconcepcion/aac/icecast.audio' },
        { n = 'Bío-Bío Los Ángeles 967', u = 'https://unlimited11-cl.dps.live/biobiolosangeles/aac/icecast.audio' },
        { n = 'C Y S Dalcahue', u = 'http://streaming.chiloestreaming.com:9542/' },
        { n = 'Carnaval Aconcagua', u = 'http://sonando.us.digitalproserver.com/carnaval_aconcagua.aac' },
        { n = 'Carnaval Punta Arenas', u = 'http://sonando.us.digitalproserver.com/carnaval_puntaarenas.aac' },
        { n = 'Carnaval Quillota', u = 'http://sonando.us.digitalproserver.com/carnaval_quillota.aac' },
        { n = 'Carnaval San Antonio', u = 'http://sonando.us.digitalproserver.com/carnaval_sanantonio.aac' },
        { n = 'Carnaval Viña Del Mar', u = 'http://sonando.us.digitalproserver.com/carnaval_vinadelmar.aac' },
        { n = 'Chercan Radio', u = 'https://stream.zeno.fm/es9h0crh74zuv' },
        { n = 'City Radio POP', u = 'http://cityradio.ddns.net:8000/citypop' },
        { n = 'CITYRADIO - CHILE', u = 'http://cityradio.ddns.net:8000/cityradio48flac' },
        { n = 'CLG Radio 935 FM', u = 'https://sonic.portalfoxmix.club/8012/streamstream' },
        { n = 'CLUB DANCE CHILE', u = 'https://stream.clubdance.cl/' },
        { n = 'Concierto', u = 'http://provisioning.streamtheworld.com/pls/CONCIERTO.pls' },
        { n = 'Conexion Radio', u = 'https://tunein.radiomaniacos.cl/conexionradio' },
        { n = 'Contemporánea', u = 'http://sonando.us.digitalproserver.com/contemporanea_aconcagua.aac' },
        { n = 'Corazon', u = 'http://provisioning.streamtheworld.com/pls/CORAZON.pls' },
        { n = 'CQX PMONTT', u = 'http://5.9.65.9:8083/stream' },
        { n = 'CQX-OSORNO', u = 'http://5.9.65.9:8065/stream' },
        { n = 'Cys Radio 963 FM Dalcahue', u = 'http://streaming.chiloestreaming.com:9542/;' },
        { n = 'Código Metal Radio', u = 'https://streaming.viphosting.cl/8012/stream' },
        { n = 'De Los Recuerdos', u = 'http://sonando.us.digitalproserver.com/fmdelosrecuerdos.aac' },
        { n = 'Desierto FM', u = 'https://broadcast.radio247.net/radio/8100/stream' },
        { n = 'Diferencia FM 893', u = 'https://sonic-cl.streaming-chile.com/8092/stream' },
        { n = 'Digital 1041 FM - ARICA', u = 'https://radio.digitalfm.cl:8000/arica' },
        { n = 'Digital 1055 FM - CONCEPCIÓN', u = 'https://radio.digitalfm.cl:8000/concepcion1' },
        { n = 'Digital 1055 FM - TALCA', u = 'https://radio.digitalfm.cl:8000/talca' },
        { n = 'Digital 895 FM - CALAMA', u = 'https://radio.digitalfm.cl:8000/calama1' },
        { n = 'Digital 949 FM - VALPARAISO', u = 'https://radio.digitalfm.cl:8000/valparaiso1' },
        { n = 'Digital 971 FM - ANTOFAGASTA', u = 'https://radio.digitalfm.cl:8000/antofagasta1' },
        { n = 'Digital 977 FM - LA SERENA', u = 'https://radio.digitalfm.cl:8000/laserena1' },
        { n = 'Digital 991 FM - IQUIQUE', u = 'https://radio.digitalfm.cl:8000/iquique1' },
        { n = 'Digital 991 FM - PUNTA ARENAS', u = 'https://radio.digitalfm.cl:8000/ptaarenas' },
        { n = 'Digital FM', u = 'https://unlimited11-cl.dps.live/digitalfm/aac/icecast.audio' },
        { n = 'Distorsión FM', u = 'https://tunein.radiomaniacos.cl/distorsion.mp3' },
        { n = 'Ecos Del Litoral', u = 'https://studio19.radiolize.com/radio/8030/radio.mp3' },
        { n = 'En La Noticia Radio 1011 FM', u = 'http://streaming.chiloestreaming.com:9920/;' },
        { n = 'ESTRELLA DEL MAR', u = 'https://streaming.chiloestreaming.com/9626/;' },
        { n = 'Europa Beat', u = 'https://s4.radio.co/s13e4f2090/listen' },
        { n = 'Exitos La Popular', u = 'https://servers58.com/proxy/sc_relpcl?mp=/;&1578827059272' },
        { n = 'Exitosa', u = 'https://stream-024.zeno.fm/dg69bex4gxquv?zs=XUpp6K5zR3aUWceZbwXJcQ' },
        { n = 'Femenina FM', u = 'http://archi-us.digitalproserver.com/femenina.aac' },
        { n = 'Festival', u = 'https://stream.festival.cl/1' },
        { n = 'FM Okey', u = 'https://streaming.fmokey.cl/moviles.mp3' },
        { n = 'FM Okey Valparaiso', u = 'http://streaming.fmokey.cl/FmOkValpo.mp3' },
        { n = 'FM Oyeme', u = 'https://sonic.portalfoxmix.club/8128/stream' },
        { n = 'FM Siete Rock', u = 'https://sp1.streamingssl.com/8036/stream' },
        { n = 'Frecuencia Rock 953', u = 'http://audio.streaminghd.cl:9206/stream' },
        { n = 'Futuro', u = 'http://provisioning.streamtheworld.com/pls/FUTUROAAC.pls' },
        { n = 'FUTURO Chile', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/FUTUROAAC.aac' },
        { n = 'Imagina', u = 'http://provisioning.streamtheworld.com/pls/imagina.pls' },
        { n = 'Isadora', u = 'https://streaming.comunicacioneschile.net/9326/stream.aac' },
        { n = 'Isla Negra', u = 'https://radioislanegra.org/radio/8000/basic.aac' },
        { n = 'Isla Negra Upbeat', u = 'https://radioislanegra.org/radio/8030/basic.aac' },
        { n = 'La Discusión', u = 'http://archi-us.digitalproserver.com/la-discusion-fm.aac' },
        { n = 'La Jaula Del Mono Radioactiva 19032023 - Tramo De 02:00 A 03:00', u = 'https://sdmedia.radioactiva.cl/radioactiva/2023/3/19/activa_lajauladelmonoradioactiva_20230319_020000_030000.mp3?dist=radioactiva_cl-web-aod_play' },
        { n = 'La Karibeña Chile', u = 'http://5.9.65.9:8028/sanvicente' },
        { n = 'La Mega Fm', u = 'https://sonic.portalfoxmix.club/8478/stream' },
        { n = 'La Melinkana FM', u = 'https://audio3.tustreaming.cl/7050/stream' },
        { n = 'La Mexicana 953 San Vicente', u = 'http://audio0.tustreaming.cl:7160/aire' },
        { n = 'La Mexicana Chile', u = 'https://audio0.tustreaming.cl/7170/casablanca' },
        { n = 'La Más Kaliente', u = 'https://audio1stream.com/8002/stream' },
        { n = 'La Retro 80S Chile', u = 'https://s2.radio.co:80/s9ecef4f68/listen' },
        { n = 'Libelulachilecl', u = 'https://streaming.viphosting.cl/8278/;' },
        { n = 'Libelulachilecom Señal 1', u = 'https://streaming.viphosting.cl:7138/;' },
        { n = 'Llacolén', u = 'http://sonando.us.digitalproserver.com/radiollacolen.aac' },
        { n = 'Los 40 Principales Chile', u = 'http://provisioning.streamtheworld.com/pls/LOS40_CHILE.pls' },
        { n = 'LOS40 Chile', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CHILEAAC.aac' },
        { n = 'Macarena', u = 'https://sonic01.zglobalhost.com:7013/stream' },
        { n = 'María', u = 'http://dreamsiteradiocp4.com:8024/' },
        { n = 'Mi Radio', u = 'https://audio1.tustreaming.cl/9020/stream' },
        { n = 'Musicoop', u = 'https://sonic.portalfoxmix.club/8486/stream' },
        { n = 'Nostalgica', u = 'https://unlimited5-us.dps.live/nostalgica/aac/icecast.audio' },
        { n = 'Oceano FM La Serena Y Coquimbo', u = 'https://audio2.tustreaming.cl/9025/stream' },
        { n = 'Pampa Y Mar FM 1023 – Región De Tarapacá', u = 'https://sp1.streamingssl.com/8052/stream' },
        { n = 'Pirinola', u = 'http://curiosity.shoutca.st:6451/autodj' },
        { n = 'Positiva', u = 'https://unlimited4-us.dps.live/positiva/aac/icecast.audio' },
        { n = 'Positiva FM', u = 'http://unlimited4-us.dps.live/positiva/aac/icecast.audio' },
        { n = 'Principios Radio', u = 'https://stream.zeno.fm/i5darmt2oi7tv' },
        { n = 'Pudahuel', u = 'http://provisioning.streamtheworld.com/pls/PUDAHUEL.pls' },
        { n = 'RADIO 24-7 CHILE', u = 'https://broadcast.radio247.net/radio/8000/;' },
        { n = 'RADIO ACTIVA 925', u = 'http://stream.zeno.fm/pvs6hqz3crtvv' },
        { n = 'Radio Agricultura', u = 'http://unlimited4-us.dps.live/agricultura/mp3/icecast.audio?' },
        { n = 'Radio Agricultura Santiago', u = 'http://unlimited4-us.dps.live/agricultura/mp3/icecast.audio' },
        { n = 'Radio Alegría Del Transporte 907 FM', u = 'http://streaming01.xhost.cl/8048/;' },
        { n = 'Radio Amiga De Talca', u = 'http://archi-us.digitalproserver.com/amiga.aac' },
        { n = 'Radio Amiga Fm 1007', u = 'https://streams.radiomast.io/aff8c0f0-5d0c-41d6-83b2-71daff574701' },
        { n = 'Radio Arcoiris FM 993', u = 'https://audio2.tustreaming.cl/7210/stream' },
        { n = 'Radio Armonía Oficina', u = 'http://encoder.armoniaoficina.cl:3032/1.mp3' },
        { n = 'Radio Austral CD97', u = 'http://archi-us.digitalproserver.com/austral.aac' },
        { n = 'Radio Barquito FM', u = 'https://centova.streaming-chile.com/proxy/radiobarquito?mp=/radiobarquito_live' },
        { n = 'Radio BBN', u = 'https://audio-edge-es6pf.mia.g.radiomast.io/475ebed1-595e-4717-b888-64fe8fc6b09f' },
        { n = 'Radio Beethoven FM', u = 'http://unlimited4-us.dps.live/beethovenfm/aac/icecast.audio' },
        { n = 'Radio Bio Bio Temuco', u = 'https://unlimited3-cl.dps.live/biobiotemuco/aac/icecast.audio' },
        { n = 'Radio Bio-Bio Puerto Montt', u = 'https://unlimited3-cl.dps.live/biobiopuertomontt/mp3/icecast.audio' },
        { n = 'Radio Biobio Valparaiso', u = 'http://unlimited3-cl.dps.live/biobiovalparaiso/mp3/icecast.audio' },
        { n = 'Radio Caribe FM 955', u = 'http://149.56.241.149:8118/stream' },
        { n = 'RADIO CARICIA FM', u = 'https://sonic.portalfoxmix.club/8244/stream/' },
        { n = 'RADIO CAROLINA Cl', u = 'http://stream.zeno.fm/sri2de2qdlivv' },
        { n = 'Radio Central Clasista De Trabajadores', u = 'http://stream.zeno.fm/m5fw6rwx2tzuv' },
        { n = 'Radio Centro Cristiano', u = 'https://vivo.miradio.in:7008/' },
        { n = 'Radio Club 80', u = 'https://stream.radioclub80.cl:8002/clasicos80.mp3' },
        { n = 'Radio Cobremar - Chañaral FM 899', u = 'https://audio.bitsur.cl/8066/stream' },
        { n = 'Radio Colocolo', u = 'https://audio2.tustreaming.cl:10997/stream' },
        { n = 'Radio Concierto Chile', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CONCIERTOAAC.aac' },
        { n = 'Radio Contexto Ñuble', u = 'https://streaming.viphosting.cl/8028/stream' },
        { n = 'Radio Contigo', u = 'http://streaming.comunicacioneschile.net:9318/stream' },
        { n = 'RADIO COOPERATIVA', u = 'https://unlimited3-cl.dps.live/cooperativafm/mp3/icecast.audio' },
        { n = 'Radio Crystal Cabildo 1019', u = 'https://radiolatina.live/9980/;' },
        { n = 'Radio Crystal San Felipe 1065 FM', u = 'https://radiolatina.live/9982/;' },
        { n = 'Radio Cómplices', u = 'https://streaming.comunicacioneschile.net:7007/;' },
        { n = 'Radio Definitiva', u = 'http://192.198.83.230:8772/;' },
        { n = 'Radio Destino', u = 'http://radio.streemlion.com:3780/stream' },
        { n = 'Radio Dinámica 1007 FM', u = 'https://streaming.comunicacioneschile.net/8030/stream' },
        { n = 'Radio Disney - Santiago FM 953', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_CHI_SA_ADP.aac' },
        { n = 'Radio Dulce CALERA - QUILLOTA 957 FM', u = 'https://stream.zeno.fm/bx6zuwssrnjvv' },
        { n = 'Radio Dulce CASABLANCA 979 FM', u = 'https://stream.zeno.fm/yo6udiulqhbvv' },
        { n = 'Radio Dulce ILLAPEL 983 FM', u = 'https://stream.zeno.fm/kc5hofr05tavv' },
        { n = 'Radio Dulce LA LIGUA - PAPUDO ZAPALLAR 953 FM', u = 'https://stream.zeno.fm/3yv0enxnp7zuv' },
        { n = 'Radio Dulce PETORCA- -CABILDO 1047 FM', u = 'https://stream.zeno.fm/uftblekcpxguv' },
        { n = 'Radio Dulce SAN FELIPE Y LOS ANDES 1003 FM', u = 'https://stream.zeno.fm/dzvavezs85ouv' },
        { n = 'Radio El Carbón', u = 'https://unlimited11-cl.dps.live/elcarbon/aac/icecast.audio' },
        { n = 'Radio El Conquistador', u = 'https://stream10.usastreams.com/9314/stream' },
        { n = 'Radio El Conquistador FM Santiago', u = 'https://stream10.usastreams.com/9314/stream/' },
        { n = 'RADIO EL LOA 1011 FM', u = 'http://us9.maindigitalstream.com:7258/stream' },
        { n = 'Radio Emilia 1075', u = 'https://sp001.servidoresph.com:8040/index.htmlCHUMILLASsid=1' },
        { n = 'Radio Encanto 885 FM', u = 'https://archi-us.digitalproserver.com/encanto_ovalle.aac' },
        { n = 'RADIO ENTRE OLAS 931 FM', u = 'https://archi-us.digitalproserver.com/entreolas.aac' },
        { n = 'Radio Estallido Tuitero', u = 'https://stream.zeno.fm/ws9z11fhrd0uv' },
        { n = 'Radio Estrella Del Norte', u = 'http://sonic.portalfoxmix.cl:8424/;' },
        { n = 'Radio FM Centro 917', u = 'https://s02.azuracast.cl/radio/8210/fmcentro' },
        { n = 'Radio Futuro', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/FUTURO_SC.mp3' },
        { n = 'Radio Guayacán', u = 'https://sonic.mallocohosting.cl/8038/stream' },
        { n = 'Radio Iglesia Cristiana La Serena', u = 'https://servidor32.brlogic.com:7050/live' },
        { n = 'Radio Ignacio Serrano', u = 'https://sonic.portalfoxmix.club/8242/stream/' },
        { n = 'Radio Interamericana', u = 'https://sonando-us.digitalproserver.com/radiointeramericana.aac' },
        { n = 'Radio Isla Negra - Slowbeat', u = 'https://radioislanegra.org/radio/8010/basic.aac' },
        { n = 'RADIO ISLA ONLINE', u = 'https://sp.totalstreaming.net:8018/stream' },
        { n = 'Radio Kurruf', u = 'https://radio.latina.red/radiokurruf.mp3' },
        { n = 'Radio Las Nieves', u = 'https://audio2.tustreaming.cl:10987/stream' },
        { n = 'Radio Lautaro Talca', u = 'https://audio2.tustreaming.cl/7320/stream' },
        { n = 'Radio Libra', u = 'http://sonando.us.digitalproserver.com/libra.aac' },
        { n = 'RADIO MANANTIAL DE VIDA', u = 'https://audio3.tustreaming.cl/7080/stream' },
        { n = 'RADIO MARAY', u = 'https://video.mediawebchile.com:2000/stream/8212/stream' },
        { n = 'Radio Marcela', u = 'http://archi-us.digitalproserver.com/marcelafm.aac' },
        { n = 'RADIO MARIA CHILE', u = 'http://dreamsiteradiocp.com:8066/stream' },
        { n = 'Radio Millenium Network', u = 'http://5.9.65.9:8030/stream.aac' },
        { n = 'Radio Nuble 897 Fm', u = 'http://streaming.comunicacioneschile.net:9358/;' },
        { n = 'Radio Paula FM - 1037 Mhz - Laja HD', u = 'http://escucha.radiopaulafm.com/' },
        { n = 'RADIO PAULINA', u = 'https://sp1.streamingssl.com/8058/stream' },
        { n = 'Radio Picarona', u = 'https://sonic.portalfoxmix.cl:7045/;' },
        { n = 'Radio Placeres', u = 'https://sonic.streamingchilenos.com/9856/;' },
        { n = 'Radio Principios', u = 'http://stream.zeno.fm/i5darmt2oi7tv' },
        { n = 'Radio Refugio Limache', u = 'http://procyon.shoutca.st:8114/stream' },
        { n = 'Radio Retro Online', u = 'https://sonic.streamingchilenos.com/8138/stream' },
        { n = 'Radio RTL', u = 'http://radio.mediadev.cl:8090/rtl_curico' },
        { n = 'Radio San Joaquin', u = 'http://espora.org:8000/radiosanjoaquin.mp3' },
        { n = 'Radio Sol 977', u = 'https://us9.maindigitalstream.com/ssl/7389' },
        { n = 'Radio Sol Classic', u = 'https://us9.maindigitalstream.com/ssl/radiosol' },
        { n = 'Radio Udec - Universidad De Concepción', u = 'https://audio.divalstream.com:7019/stream' },
        { n = 'Radio Universidad Del Bío-Bío', u = 'http://146.83.195.22:8000/stream.ogg' },
        { n = 'Radio Vale FM CHILE', u = 'https://sp1.streamingssl.com/8056/stream' },
        { n = 'Radio XQA5', u = 'https://archi-us.digitalproserver.com/xqa-5.aac' },
        { n = 'Radio Éxitos La Popular 1061 FM', u = 'http://livehd.cdn.felpysolutions.us/proxy/sc_relpcl' },
        { n = 'Radiofavoritaranchera', u = 'https://stream.zeno.fm/pdlp0sxtdjkvv' },
        { n = 'Radiomenap Chile', u = 'https://sonicpanel.streaming10.net/8008/stream' },
        { n = 'Radiomix', u = 'https://video.mediawebchile.com:2000/stream/radiomixsc/stream' },
        { n = 'Raxies FM', u = 'https://stream.zeno.fm/annpmyskb4jtv' },
        { n = 'Ritmo FM', u = 'https://sonic.portalfoxmix.cl/9976/stream' },
        { n = 'Ritoque', u = 'http://sonando.us.digitalproserver.com/ritoquefm_aac' },
        { n = 'Ritoque FM', u = 'https://archi-us.digitalproserver.com/ritoquefm_aac' },
        { n = 'Rock Pop M', u = 'http://provisioning.streamtheworld.com/pls/ROCK_AND_POP.pls' },
        { n = 'Rockpop Chile', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/ROCK_AND_POPAAC_SC' },
        { n = 'RT Noticias', u = 'https://audio1.tustreaming.cl/9850/stream' },
        { n = 'Silens Clamor', u = 'https://www.silensclamor.com/live' },
        { n = 'Sintonizados Con Cristo Radio - IMPCH San Miguel', u = 'https://audio.streaminghd.cl:9130/live' },
        { n = 'Sonar 1053 FM', u = 'https://mdstrm.com/audio/5c915724519bce27671c4d15/icecast.audio?property=radiobox' },
        { n = 'Sunrise', u = 'https://sonic-cl.streaming-chile.com/8044/stream' },
        { n = 'Sunrise Dance Mix', u = 'https://sonic-cl.streaming-chile.com/8054/stream' },
        { n = 'Sunrise Lounge', u = 'https://sonic-cl.streaming-chile.com/8098/stream' },
        { n = 'Super45Fm', u = 'https://s4.radio.co/s421105570/listen' },
        { n = 'Tornagaleones', u = 'http://tornagaleones.ddns.net:9000/stream' },
        { n = 'UCV Radio', u = 'https://sonando-us.digitalproserver.com/ucvradio' },
        { n = 'UCV Radio Vivan Los Lentos', u = 'https://sonando-us.digitalproserver.com/ucvradio2' },
        { n = 'Universidad Católica De Valparaíso', u = 'http://sonando.us.digitalproserver.com/ucvradio' },
        { n = 'Unlimited80S', u = 'https://rsas.streamthe.world/unlimited80s' },
        { n = 'Vilas Radio 1001', u = 'https://sonic.streamingchilenos.com/8072/stream' },
        { n = 'Vilas Radio 981', u = 'https://sonic.portalfoxmix.club/8042/stream' },
        { n = 'VLN Radio', u = 'https://sonando-us.digitalproserver.com/vln_lo' },
        { n = 'World Hits Radio', u = 'https://stream.zeno.fm/6vytsnbkb8zuv' },
    }
}
