return {
    ['costa_rica'] = {
        { n = '103 FM 1031', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRC_103_1AAC.aac' },
        { n = '1047Hit', u = 'https://live.turadio.stream:7004/stream;' },
        { n = '955 Jazz', u = 'https://streaming.radio.co/s36bd2a451/listen' },
        { n = 'Amor FM 939', u = 'https://player.hostingtico.com/proxy/8094' },
        { n = 'Azul 999 FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRC_999AAC.aac' },
        { n = 'Classics Pop Rock', u = 'http://c9.radioboss.fm:8035/stream' },
        { n = 'CLUB DANCE MUSIC', u = 'https://stream.zeno.fm/5x4sda9kxtzuv' },
        { n = 'Columbia Estéreo 927 FM', u = 'https://s5.radio.co/sca838cc60/listen' },
        { n = 'CRC 891 RADIO', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRC_89_1AAC.aac' },
        { n = 'Dabar', u = 'https://a1.asurahosting.com:8720/radio.mp3' },
        { n = 'Dabar Radio', u = 'https://a1.asurahosting.com:8720/radio.mp3/;' },
        { n = 'Faro Del Caribe 971 FM Y 1080 AM', u = 'https://sp.unoredcdn.net/8032/stream' },
        { n = 'IQ Radio', u = 'http://rtvhd.net:9942/;stream/1' },
        { n = 'IQ Radio 1055 FM', u = 'http://rtvhd.net:9942/;' },
        { n = 'LOS40 Principales Radio', u = 'https://25503.live.streamtheworld.com/LOS40AAC_SC' },
        { n = 'Mundo Rock Radio', u = 'https://as100.globalhost1.com/8046/stream' },
        { n = 'Nueve Cuatro Siete - 947 FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRC_947AAC.aac?_=819140' },
        { n = 'Planet 1075', u = 'https://stream20.usastreams.com/8094/stream' },
        { n = 'Puerto Limón Radio', u = 'https://puertolimonradio-rowrigos.radioca.st/listen.pls?sid=1' },
        { n = 'RADIO 1075', u = 'http://65.60.45.74:8400/;stream/1;' },
        { n = 'Radio Casino 983FM', u = 'https://host.rowrigo.com/listen/radiocasino/radiocasino' },
        { n = 'Radio Costa', u = 'https://sonicpanel.globalstream.pro:10979/;' },
        { n = 'Radio Frecuencia Tierra', u = 'http://68.235.35.243:9008/stream' },
        { n = 'Radio Hit 1047', u = 'https://live.turadio.stream:7004/stream?type=http&nocache=596' },
        { n = 'Radio María Costa Rica - 1007 FM', u = 'http://dreamsiteradiocp2.com:8044/stream' },
        { n = 'Radio Mil Recuerdos Stereo', u = 'https://sechin.grupocentroserver.com/radio/8060/radio.mp3' },
        { n = 'Radio Musical 975', u = 'https://live.turadio.stream:7005/stream?type=http&nocache=596' },
        { n = 'Radio Omega 1051 FM', u = 'http://rtvhd.net:9932/listen.pls' },
        { n = 'Radio Revolución', u = 'https://stream.zeno.fm/ftcx2988uwzuv' },
        { n = 'Radio Spectro', u = 'https://stream20.usastreams.com/8090/stream' },
        { n = 'Tamarindo Radio', u = 'http://s1.voscast.com:11392/stream' },
        { n = 'Tiquicia Rock', u = 'https://usa19.fastcast4u.com:5860/?type=http&nocache=1690470873' },
        { n = 'Urbano 106 - 1059 FM - San José, Costa Rica', u = 'https://usa18.fastcast4u.com/proxy/rmoohhrw?mp=/1' },
    }
}
