return {
    ['denmark'] = {
        { n = '100% Kim Larsen', u = 'http://stream2.wlmm.dk/kimlarsenmp3' },
        { n = '2Town Radio', u = 'https://streaming.radio.co/sd9d980ff0/listen' },
        { n = '902 FM', u = 'http://s38.myradiostream.com:8598/.mp3' },
        { n = 'Alfa Gold', u = 'https://radioserver.dk/alfaevent' },
        { n = 'Always Elvis Radio', u = 'http://radioserver.dk/alwayselvisradio' },
        { n = 'ANR', u = 'http://stream.anr.dk/anr' },
        { n = 'Classic Dance [DK]', u = 'https://stream.classicpop.dk/dance' },
        { n = 'Classic FM', u = 'http://webradio.classicfm.dk/classichorsens' },
        { n = 'Classic FM Fyn', u = 'https://netradio.classicfm.dk/cla12a' },
        { n = 'Classic POP [DK]', u = 'https://stream.classicpop.dk/stream' },
        { n = 'Classic Rock Danmark', u = 'https://netradio.classicfm.dk/classicrock' },
        { n = 'Classicfm', u = 'http://netradio.classicfm.dk/cla8d' },
        { n = 'Danmarks Radio P2', u = 'https://live-icy.dr.dk/A/A27L.mp3' },
        { n = 'Danmarks Radio P4; Trekanten', u = 'http://live-icy.gss.dr.dk/A/A13H.mp3.m3u' },
        { n = 'Danmarks Radio P6', u = 'https://live-icy.dr.dk/A/A29H.mp3' },
        { n = 'Dansktop Kanalen', u = 'https://netradio.classicfm.dk/dansktop' },
        { n = 'Det Rigtige Faaborg', u = 'http://stream2.wlmm.dk/detrigtigefaaborg' },
        { n = 'DFM Radio Television International', u = 'http://stereo.dfm.nu:8205/dfm_1' },
        { n = 'Din Radio', u = 'http://stream.wlmm.dk/DinRadiomp3' },
        { n = 'DR 6 Beat', u = 'http://live-icy.gss.dr.dk:8000/A/A29H.mp3' },
        { n = 'DR Nyheder', u = 'http://live-icy.gss.dr.dk/A/A02L.mp3.m3u' },
        { n = 'DR P1', u = 'http://live-icy.dr.dk/A/A03H.mp3.m3u' },
        { n = 'DR P2', u = 'http://live-icy.gss.dr.dk/A/A04H.mp3.m3u' },
        { n = 'DR P4 Bornholm', u = 'http://live-icy.gss.dr.dk/A/A06H.mp3' },
        { n = 'DR P4 Esbjerg', u = 'http://live-icy.gss.dr.dk/A/A15H.mp3' },
        { n = 'DR P4 Fyn', u = 'http://live-icy.gss.dr.dk:8000/A/A07H.mp3' },
        { n = 'DR P4 København', u = 'http://live-icy.gss.dr.dk/A/A08H.mp3' },
        { n = 'DR P4 København MP3', u = 'http://live-icy.dr.dk/A/A08H.mp3' },
        { n = 'DR P4 Midt Vest', u = 'http://live-icy.gss.dr.dk/A/A09H.mp3.m3u' },
        { n = 'DR P4 Midtvest', u = 'http://live-icy.gss.dr.dk/A/A09H.mp3' },
        { n = 'DR P4 Nordjylland', u = 'http://live-icy.gss.dr.dk:8000/A/A10H.mp3' },
        { n = 'DR P4 Sjælland', u = 'http://live-icy.gss.dr.dk/A/A11H.mp3.m3u' },
        { n = 'DR P4 Syd', u = 'http://live-icy.gss.dr.dk/A/A12H.mp3' },
        { n = 'DR P4 Trekanten', u = 'http://live-icy.gss.dr.dk:8000/A/A13H.mp3' },
        { n = 'DR P4 Østjylland', u = 'http://live-icy.gss.dr.dk:8000/A/A14H.mp3' },
        { n = 'DR P4 Østjyllands Radio', u = 'http://live-icy.gss.dr.dk/A/A14H.mp3.m3u' },
        { n = 'DR P5', u = 'http://live-icy.gss.dr.dk/A/A25H.mp3.m3u' },
        { n = 'DR P5 Bornholm', u = 'https://live-icy.dr.dk/A/A30H.mp3' },
        { n = 'DR P5 Esbjerg', u = 'https://live-icy.dr.dk/A/A26H.mp3' },
        { n = 'DR P5 Fyn', u = 'https://live-icy.dr.dk/A/A02H.mp3' },
        { n = 'DR P5 Midtvest', u = 'https://live-icy.dr.dk/A/A17H.mp3' },
        { n = 'DR P5 Trekanten', u = 'http://live-icy.gss.dr.dk/A/A23H.mp3.m3u' },
        { n = 'DR P5 Østjylland', u = 'https://live-icy.dr.dk/A/A24H.mp3' },
        { n = 'DR P6 Beat', u = 'http://live-icy.gss.dr.dk/A/A29H.mp3' },
        { n = 'DR P8 JAZZ', u = 'http://live-icy.gss.dr.dk/A/A22H.mp3.m3u' },
        { n = 'DR Ramasjangultra Radio', u = 'http://live-icy.gss.dr.dk/A/A24H.mp3' },
        { n = 'DRR', u = 'http://radioserver.dk/abc' },
        { n = 'Esbjerg Classic FM', u = 'https://webradio.classicfm.dk/classicvejle' },
        { n = 'Femernfm', u = 'https://cast1.asurahosting.com/proxy/femernfm/stream' },
        { n = 'Globus Guld', u = 'http://stream.wlmm.dk/listen.pls?sid=1' },
        { n = 'Globus Guld Jul', u = 'https://stream.probroadcast.dk/guldjul' },
        { n = 'Globus Guld Kolding', u = 'http://media.wlmm.dk:8000/guldkolding' },
        { n = 'Globus Guld Tonder', u = 'http://media.wlmm.dk:8000/guldtoender' },
        { n = 'Gofm', u = 'https://radioserver.dk/gofm' },
        { n = 'Jazzkanalen', u = 'http://ca6.rcast.net:4058/;stream' },
        { n = 'København Jazz Radio', u = 'https://asima.out.airtime.pro:8000/radiojazzcopenhagen_a' },
        { n = 'Limfjord Plus', u = 'http://media.limfjordnetradio.dk/plus128' },
        { n = 'Limfjord Plus Slager', u = 'http://media.limfjordnetradio.dk/plusslager128' },
        { n = 'Lumi Radio', u = 'http://stream2.wlmm.dk/syddanmark.m3u' },
        { n = 'Midtfjord Radio Radio Nibenitten', u = 'http://stream.midtfjordradio.dk/netradio' },
        { n = 'Muzaiko', u = 'http://fluo.muzaiko.saluton.dk:8000/radio.mp3' },
        { n = 'Myrock', u = 'https://live-bauerdk.sharp-stream.com/myrock_dk_mp3' },
        { n = 'Nordic Lodge Copenhagen', u = 'http://radio.streemlion.com:1160/stream' },
        { n = 'Nordsjællands Kristne Radio', u = 'http://studie.hkr.dk:8000/stream.mp3' },
        { n = 'Norea Radio', u = 'http://radio.norea.dk:8080/;' },
        { n = 'Nova', u = 'http://live-bauerdk.sharp-stream.com/nova128.mp3' },
        { n = 'NOVA - Horsens 1036 FM', u = 'https://live-bauerdk.sharp-stream.com/nova_dk_mp3' },
        { n = 'Nova 100% Dansk', u = 'https://live-bauerdk.sharp-stream.com/DK_HQ_RP11.aac' },
        { n = 'Party Fm', u = 'http://stream1.partyfm.dk/Party320' },
        { n = 'Partyfm', u = 'http://stream.partyfm.dk/Party320/' },
        { n = 'POP FM DK', u = 'http://live-bauerdk.sharp-stream.com/popfm128.mp3' },
        { n = 'Psyradio - Chillout', u = 'http://komplex2.psyradio.org:8020/chillout/;' },
        { n = 'Radio 100', u = 'https://live-bauerdk.sharp-stream.com/radio100_dk_mp3' },
        { n = 'Radio 208', u = 'http://stream.wlmm.dk:8010/radio208' },
        { n = 'Radio 40Plus', u = 'http://stream.radiosolutions.dk/radio40plus' },
        { n = 'Radio ABC', u = 'https://radioserver.dk/abc' },
        { n = 'Radio Alfa', u = 'https://radioserver.dk/alfa' },
        { n = 'Radio Alfa Aarhus', u = 'https://radioserver.dk/alfaaarhus' },
        { n = 'Radio Alfa Midtjylland', u = 'https://radioserver.dk/alfamidt' },
        { n = 'Radio Alfa Silkeborg', u = 'https://radioserver.dk/alfasilk' },
        { n = 'Radio Alfa Skive', u = 'https://radioserver.dk/alfaskive' },
        { n = 'Radio Alfa Viborg', u = 'https://radioserver.dk/alfaviborg' },
        { n = 'Radio ALR', u = 'http://streamer.radio.co/s6a9beb92e/listen' },
        { n = 'Radio Boost', u = 'http://6434.cloudrad.io:8066/;' },
        { n = 'Radio Diablo', u = 'https://icecast1.radiostuff.dk/Diablo128' },
        { n = 'Radio Fasanen Frederiksberg', u = 'https://c14.radioboss.fm:18228/stream' },
        { n = 'Radio Folk', u = 'http://stream.radiojar.com/fqt2y0ds97zuv' },
        { n = 'Radio Freja', u = 'http://solid67.streamupsolutions.com:15507/stream' },
        { n = 'Radio Globus', u = 'https://stream.probroadcast.dk/radioglobus' },
        { n = 'Radio Haderslev', u = 'http://media.wlmm.dk/radiohaderslevmp3' },
        { n = 'Radio Helsingør FM', u = 'https://stream.radiohelsingor.dk/rh' },
        { n = 'Radio Humleborg', u = 'https://stream2.rcast.net/64145' },
        { n = 'Radio Klitholm', u = 'http://stream.radioklitholm.dk:8000/stream' },
        { n = 'Radio Koge', u = 'http://stream.wlmm.dk/stream/53/;' },
        { n = 'Radio Limfjord', u = 'http://media.limfjordnetradio.dk/limfjordaac' },
        { n = 'Radio M', u = 'https://radioserver.dk/radiom' },
        { n = 'Radio Midtsjælland', u = 'http://player.radiomidt.dk/broadwave.mp3' },
        { n = 'Radio Mælkebøtten', u = 'http://live2.rcast.net:8722/;stream' },
        { n = 'Radio Nord', u = 'http://netradio.radionord.dk:8000/RadioNord' },
        { n = 'Radio Nordjyske', u = 'http://stream.anr.dk/nordjyske' },
        { n = 'Radio Odsherred', u = 'http://87.104.40.139:88/broadwave.mp3' },
        { n = 'Radio Ost FM', u = 'http://stream.wlmm.dk/oestfmmp3' },
        { n = 'Radio Playback', u = 'http://stream02.radioplayback.dk/stream' },
        { n = 'Radio Ringkøbing', u = 'http://netradio.radioringkobing.dk:8000/;' },
        { n = 'Radio SLR', u = 'http://stream.wlmm.dk/stream/54/' },
        { n = 'Radio Soft', u = 'http://tx-bauerdk.sharp-stream.com/http_live.php?i=radiosoft_dk_mp3' },
        { n = 'Radio Soft - Københavns NR - Bispebjerg LR - Bella Chr', u = 'https://live-bauerdk.sharp-stream.com/radiosoft_dk_tunein_mp3' },
        { n = 'Radio Solo', u = 'https://radioserver.dk/solo' },
        { n = 'Radio Stinesen', u = 'https://st1.stinesen.dk/StineM320' },
        { n = 'Radio Sydhavs Øerne', u = 'https://stream.probroadcast.dk/sydhavsradiomp3' },
        { n = 'Radio Varde', u = 'http://stream.wlmm.dk/radiovardemp3' },
        { n = 'Radio Viborg', u = 'https://webradio.radioviborg.dk/viborg' },
        { n = 'Radio Victoria', u = 'http://stream.wlmm.dk/NyRadiomp3' },
        { n = 'Radio Viva', u = 'https://stream.probroadcast.dk/radioviva' },
        { n = 'Radio VLR', u = 'https://netradio.vlr.dk/vlr8d' },
        { n = 'Radio VLR - Classic Christmas', u = 'https://netradio.vlr.dk/popup2' },
        { n = 'Radio Østsjælland Rollo', u = 'http://stream.radiosolutions.dk/rollo' },
        { n = 'Radio4', u = 'http://netradio.radio4.dk/radio4' },
        { n = 'Rar', u = 'http://techno-low.rautemusik.fm/' },
        { n = 'Retro Millennium', u = 'https://tx-2.retro-radio.dk/TX-2' },
        { n = 'Retro Radio', u = 'http://stream128.retro-radio.dk/retro' },
        { n = 'Retro-Radio Jul', u = 'http://isstream.kanalplus.fm/TX-1' },
        { n = 'Retro-Radio Millennium', u = 'http://tx-2.retro-radio.dk/TX-2' },
        { n = 'Retro1', u = 'http://streammp3.retro-radio.dk/retro-mp3' },
        { n = 'Roskilde Dampradio', u = 'https://stream.rcast.net/60962' },
        { n = 'Skaga FM', u = 'http://stream.wlmm.dk/skagafm.m3u' },
        { n = 'Skala FM', u = 'http://webradio.skala.fm/kolding' },
        { n = 'Tango Copenhagen Radio', u = 'https://tangocopenhagen.stream.laut.fm/tangocopenhagen?t302=2021-01-15_18-47-40&uuid=64db9a91-4a6e-4bc8-ba24-26a2fa7f24d0' },
        { n = 'Technobasefm - Aacplus 96K', u = 'http://listen.technobase.fm/tunein-aacplus-pls' },
        { n = 'Technobasefm - MP3 192K', u = 'http://listen.technobase.fm/tunein-mp3-pls' },
        { n = 'The Lake Radio', u = 'http://hyades.shoutca.st:8627/' },
        { n = 'The Voice', u = 'http://live-bauerdk.sharp-stream.com/voice128.mp3' },
        { n = 'The Voice - Danmarks Hitstation', u = 'https://live-bauerdk.sharp-stream.com/thevoice_dk_mp3' },
        { n = 'UMLANDO Radio', u = 'https://a2.asurahosting.com:6520/radio.mp3' },
        { n = 'Vinyl Hits', u = 'http://stream.vinylhits.dk/vinylaac' },
        { n = 'Vinylhitsdk', u = 'http://stream.vinylhits.dk/vinylmp3' },
        { n = 'Vox Pop', u = 'http://stream.midlar.fo/voxpop-128' },
        { n = 'WMR - World Music Radio', u = 'https://stream.probroadcast.dk/wmr' },
        { n = 'World Music Radio', u = 'http://stream.wlmm.dk:8010/wmr' },
        { n = 'X FM K', u = 'https://uniradio.out.airtime.pro/uniradio_a' },
        { n = 'Ymse Radio', u = 'https://radio.ymseimpro.org/' },
    }
}
