return {
    ['india'] = {
        { n = '2B Radio Sangam Devi Maa', u = 'http://ibadat.out.airtime.pro:8000/ibadat_a' },
        { n = '2B Radio Sangam Ganesha', u = 'http://radio2bindia.out.airtime.pro:8000/radio2bindia_a' },
        { n = '2B Radio Sangam Guruvar', u = 'http://iskon2b.out.airtime.pro:8000/iskon2b_a' },
        { n = '2B Radio Sangam Krishna', u = 'http://millenniumhits.out.airtime.pro:8000/millenniumhits_a' },
        { n = '2B Radio Sangam Meditation', u = 'http://djbeat.out.airtime.pro:8000/djbeat_a' },
        { n = '2B Radio Sangam Shiva', u = 'http://hot.out.airtime.pro:8000/hot_a' },
        { n = '2B Radio Sangam Shri Ram', u = 'http://dard.out.airtime.pro:8000/dard_a' },
        { n = '60Sforever', u = 'https://stream.zeno.fm/btrks671ynhvv' },
        { n = '80’S Tamil Hits', u = 'https://stream.zeno.fm/48w230kx8vzuv.aac' },
        { n = '894 Tamil FM', u = 'https://centova.aarenworld.com/proxy/894tamilfm/stream' },
        { n = '90Sonceagainradio', u = 'https://stream.zeno.fm/rm4i9pdex3cuv' },
        { n = '90’S Tamil Melodies', u = 'https://stream.zeno.fm/tqnws2eafwzuv.aac' },
        { n = 'A1Tamilradio', u = 'https://ec3.yesstreaming.net:1190/stream' },
        { n = 'A9RADIO', u = 'https://a9radio1-a9media.radioca.st/stream' },
        { n = 'A9Radionewhits', u = 'https://a9newhits-a9media.radioca.st/stream' },
        { n = 'Aaha Radio 919 FM', u = 'https://raw.githubusercontent.com/himalayasingh/music-player-1/master/music/2.mp3' },
        { n = 'Aaha-Radio', u = 'https://s2.radio.co/s3801784f1/listen' },
        { n = 'Aahafmradio', u = 'http://s2.radio.co/s3801784f1/listen' },
        { n = 'Aakashvani', u = 'https://audio-edge-fvq45.ams.d.radiomast.io/3ccc1156-fcf8-4ba7-9a0c-28e3a465e1ae?listening-from-radio-garden=1607152226837' },
        { n = 'Aap Ki Awaz Up', u = 'http://stream.zeno.fm/spm0t8gq45quv' },
        { n = 'Aavai-Fm', u = 'https://stream-160.zeno.fm/kzd2e3tx24zuv?zs=oZi21YHhSm-4B0Ud_PN53w' },
        { n = 'AB DIGITAL', u = 'http://stream.zeno.fm/as9h7v04kuhvv' },
        { n = 'Abctamil', u = 'https://eu8.fastcast4u.com/proxy/ailevdcu?mp=/;' },
        { n = 'Abee Radio', u = 'https://abee.radioca.st/stream' },
        { n = 'Ada-Ceylon-Fm', u = 'https://stream.zeno.fm/c32gn1eas2zuv' },
        { n = 'Adiraifm', u = 'https://listen.radioking.com/radio/188161/stream/230320' },
        { n = 'Agaramuthalaa FM', u = 'https://stream.zenolive.com/rc739wuvra0uv.aac' },
        { n = 'Agra Radio', u = 'https://stream.zeno.fm/m1krtxpk11zuv' },
        { n = 'AIR RAINBOW FM KOCHI 1075', u = 'http://stream.zeno.fm/zcxh6wkva18uv' },
        { n = 'Ajith-Fm', u = 'https://stream.zeno.fm/ntkhu40k17zuv' },
        { n = 'Ajmer Radio', u = 'https://stream.zeno.fm/yftb93nbay8uv' },
        { n = 'Akaramradio', u = 'https://globalwebmusic.com/akaram.mp3' },
        { n = 'Akash Radio Leeds', u = 'https://c2.radioboss.fm:8276/stream' },
        { n = 'Al Mallu FM', u = 'https://stream.zeno.fm/nwmetttbqs8uv' },
        { n = 'Amenradio', u = 'https://ice7.securenetsystems.net/AMENFM' },
        { n = 'American-Tamil-Radio', u = 'https://cp11.serverse.com/proxy/hgsmgluv?mp=/stream' },
        { n = 'Amrradiokannada', u = 'https://stream.zeno.fm/7g8axtgtsg0uv' },
        { n = 'Ananda Marga FM', u = 'https://stream-151.zeno.fm/r5dxv34smm0uv?zs=-uOwHmM8Tt-OWY6boDO8kA' },
        { n = 'Ananda Marga Pracharaka Samgha', u = 'https://stream-152.zeno.fm/216zaqk88a0uv?zs=-fqdY-MsRiGgFdlBNEsYvA' },
        { n = 'Anantradio', u = 'https://node-27.zeno.fm/rzuke118e3quv?rj-ttl=5&rj-tok=AAABcTlCgAwAy6eEPdjo1Hgv7g' },
        { n = 'Anbu FM Hindi', u = 'https://stream.zeno.fm/u7yaqq493v8uv' },
        { n = 'Anbu FM Kannada', u = 'http://stream.zeno.fm/45f9c2byfy8uv' },
        { n = 'Anbu FM Malayalam', u = 'https://stream.zeno.fm/8ca40byv4x8uv' },
        { n = 'Annai FM', u = 'http://stream.zeno.fm/ewuo8mhb9zyvv' },
        { n = 'Anuradha Paudwal Radio', u = 'http://stream.zeno.fm/4dy8k3zqu98uv' },
        { n = 'Ap 9 FM', u = 'https://stream.ap9fm.in/radio/8000/radio.mp3' },
        { n = 'Apna 990 AM', u = 'https://ais-nzme.streamguys1.com/nz_145_aac' },
        { n = 'AR Rahman Radio', u = 'https://ec5.yesstreaming.net:2320/stream' },
        { n = 'Arijitsingh', u = 'https://drive.uber.radio/uber/bollywoodaruitsingh/icecast.audio' },
        { n = 'Arni City FM', u = 'https://usa9.fastcast4u.com:2199/tunein/arnifm-stream.pls' },
        { n = 'Arni-City-Fm', u = 'https://www.liveradio.es/http://192.95.39.65:5018/;' },
        { n = 'Arnicityfm', u = 'https://usa9.fastcast4u.com/proxy/arnifm?mp=/1' },
        { n = 'Arradio', u = 'https://stream.zeno.fm/heq754gwxwzuv' },
        { n = 'Arrahmanradio', u = 'http://stream.zeno.fm/0cys2h41w0hvv' },
        { n = 'Arul Vakku FM', u = 'https://stream.arulvakku.com/radio/8000/radio.mp3' },
        { n = 'Arumbu-Fm', u = 'https://stream.zeno.fm/22db1xmde2zuv' },
        { n = 'Asha Malayalam Radio', u = 'https://radio.asharadio.net:8000/asharadio' },
        { n = 'Asian Star Radio', u = 'https://radio.canstream.co.uk:9067/live.mp3' },
        { n = 'Asr-Digital-Radio', u = 'https://stream-153.zeno.fm/aqf1rvdnc18uv?zs=4S2ro1YeRSSZVUZKPe8VQQ' },
        { n = 'AURAL MELODICS', u = 'http://stream.zeno.fm/a3250rmrga0uv' },
        { n = 'AURAL OLDIES', u = 'http://stream.zeno.fm/anrf216cu68uv' },
        { n = 'AURAL WEST', u = 'http://stream.zeno.fm/xd6trx3e84zuv' },
        { n = 'Aural-Oldies', u = 'https://stream-158.zeno.fm/tksfwb1mgzzuv' },
        { n = 'Auralmelodics', u = 'https://stream-159.zeno.fm/7fmywrmrga0uv' },
        { n = 'Auralmelodies', u = 'https://stream.zeno.fm/7fmywrmrga0uv' },
        { n = 'Auralradio', u = 'http://stream.zeno.fm/8ux50camqwzuv' },
        { n = 'Awaz FM', u = 'https://uksoutha.streaming.broadcast.radio/awazfm' },
        { n = 'Bakthi-Fm', u = 'https://stream.zeno.fm/0p1p4t7043duv' },
        { n = 'Bakthi-Malai-Radio', u = 'https://bakthiisai-unicast2u.radioca.st/stream' },
        { n = 'Balurghat FM', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/SP_R3563475_SC' },
        { n = 'Beats-Radio', u = 'https://n08.radiojar.com/8yx6spzrv4zuv?rj-ttl=5&rj-tok=AAABeQK013YA0ljcGmQY_tANGw' },
        { n = 'BEST OF AR RAHMAN TAMIL SONGS', u = 'https://stream-176.zeno.fm/p7b0e3ms97zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwN2IwZTNtczk3enV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IklNa3dEVmF0VEYtVVo5ekQxUURkRVEiLCJpYXQiOjE3MjM3MjM0NTMsImV4cCI6MTcyMzcyMzUxM30.5coumX6SC7zgvRPEriGg9pnWNV6801uGjs4phyhSy6Q' },
        { n = 'Bethel-Fm-Radio', u = 'https://www.liveradio.es/http://e12392.cloudrad.io:8992/stream' },
        { n = 'Bhajans Radio Guyana', u = 'https://s5.citrus3.com:8148/stream' },
        { n = 'Bhakti Sagar FM', u = 'https://stream.zeno.fm/lcida9v81nmvv.m3u' },
        { n = 'Bhakti World - Hanuman', u = 'http://2bhanuman.out.airtime.pro:8000/2bhanuman_a' },
        { n = 'Bhakti World Media Shri Ram', u = 'https://dard.out.airtime.pro/dard_a' },
        { n = 'Bhaktisudha', u = 'https://n0a.radiojar.com/cfqyfcspcv8uv' },
        { n = 'Bhaktiworld Media Bhagavad Gita', u = 'https://stream.zeno.fm/ijklcild1wrtv' },
        { n = 'Bhaktiworld Media Devi Maa', u = 'http://ibadat.out.airtime.pro:8000/ibadat_a?_ga=2.112683904.548091236.15820292 13-1175002648.1580299245' },
        { n = 'Bhaktiworld Media Ganesha', u = 'https://radio2bindia.out.airtime.pro/radio2bindia_a?_ga=2.203455766.763289185.16 62805693-499518273.1568730566' },
        { n = 'Bhaktiworld Media Gayatri Mantra', u = 'https://stream-172.zeno.fm/503oro4ujkuuv?zs=_lsGSw9DRKSHJPEa0D8zKQ' },
        { n = 'Bhaktiworld Media Gurbani', u = 'http://gurbani.out.airtime.pro:8000/gurbani_b?_ga=2.77423505.548091236.1582029 213-1175002648.1580299245' },
        { n = 'Bhaktiworld Media Hanuman Ji', u = 'https://2bhanuman.out.airtime.pro:8000/2bhanuman_a' },
        { n = 'Bhaktiworld Media Kashta Nivaran Mantra', u = 'https://stream-176.zeno.fm/4bwupenfuedvv?zs=1Mn8umtOQgqCchvse7HGvw' },
        { n = 'Bhaktiworld Media Mahamrityunjay Mantra', u = 'https://stream-172.zeno.fm/9zrvfxrimqytv?zs=3cYTVpXZSTSLGr2KvM_q9Q' },
        { n = 'Bhaktiworld Media Meditation', u = 'http://stream.zeno.fm/mahank02nrvvv' },
        { n = 'Bhaktiworld Media Mritsanjivani Mantra', u = 'https://stream.zeno.fm/ystze8ylk8fvv' },
        { n = 'Bhaktiworld Media Navaran Mantra', u = 'https://stream-172.zeno.fm/kutyooocsdqtv?zs=ZIfiXki4Ssuh6DAv2X2uuw' },
        { n = 'Bhaktiworld Media Podcasts', u = 'http://stream.zeno.fm/nqvcaqevkx5vv' },
        { n = 'Bhaktiworld Media Sai Baba', u = 'https://iskon2b.out.airtime.pro:8000/iskon2b_a' },
        { n = 'Bhaktiworld Media Shani Mantra', u = 'https://stream-176.zeno.fm/ehmzrkjw9xtuv?zs=BlRrYHeGTmeyv1iFhWAr_g' },
        { n = 'Bhaktiworld Media Shiva', u = 'http://hot.out.airtime.pro:8000/hot_a?_ga=2.158331450.1016847427.1656651399- 396439986.1656651399' },
        { n = 'Bhaktiworld Media Shri Ram', u = 'https://dard.out.airtime.pro/dard_a?_ga=2.178816160.548091236.1582029213- 1175002648.1580299245' },
        { n = 'Bharat FM', u = 'https://s2.radio.co/s44bb88930/listen#.mp3?ver=997168' },
        { n = 'Bhojpuri Songs', u = 'https://stream.zeno.fm/yz0ncx9gha0uv' },
        { n = 'Big-Fm-Tamil', u = 'https://stream.zeno.fm/r2gn1pgm4qruv' },
        { n = 'BMZ RADIO', u = 'https://stream-59.zeno.fm/uy91e749fv8uv?zs=iP XEX-WRummaOh91E3yrw' },
        { n = 'Bol Punjabi Radio', u = 'https://bolpunjabi-ekamsoftware.radioca.st/stream' },
        { n = 'Bolly 1029 FM', u = 'https://ice6.securenetsystems.net/INTRADIO?type=.mp3' },
        { n = 'Bolly923Fm', u = 'https://stream.zeno.fm/k4hwu4qa4qzuv' },
        { n = 'Bollyhitsradio', u = 'http://hoth.alonhosting.com:1100/;' },
        { n = 'Bollyvibesradio', u = 'http://bollyvibes.radioca.st/stream' },
        { n = 'Bollywood 90S Radio', u = 'https://stream-159.zeno.fm/rm4i9pdex3cuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJybTRpOXBkZXgzY3V2IiwiaG9zdCI6InN0cmVhbS0xNTkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlMzMHdNYU40UUZtNml2WnR3UFRhSmciLCJpYXQiOjE' },
        { n = 'Bollywood Gaane Purane', u = 'https://stream.zeno.fm/6n6ewddtad0uv' },
        { n = 'Bollywood Punjabi Radio', u = 'http://stream.zeno.fm/1k0y9f0cm0quv' },
        { n = 'Bollywood Workout', u = 'https://drive.uber.radio/uber/bollywoodworkout/icecast.audio' },
        { n = 'Bollywoodandbeyond', u = 'https://s6.yesstreaming.net/proxy/john1237?mp=/live' },
        { n = 'Bollywooddance', u = 'http://drive.uber.radio/uber/bollywooddance/icecast.audio' },
        { n = 'Bollywoodmix', u = 'https://drive.uber.radio/uber/bollywoodmix/icecast.audio' },
        { n = 'Bollywoodmuziq', u = 'https://stream.zeno.fm/uy91e749fv8uv' },
        { n = 'Bollywoodpunjabiradio', u = 'https://stream.zeno.fm/1k0y9f0cm0quv' },
        { n = 'Bombay Beats Radio', u = 'https://strmreg.1.fm/bombaybeats_mobile_mp3' },
        { n = 'Bombaybeats', u = 'http://strm112.1.fm/bombaybeats_mobile_mp3' },
        { n = 'Brisvaani', u = 'http://centova71.instainternet.com/proxy/brisvaaniradio?mp=/stream' },
        { n = 'Brisvaani Radio', u = 'https://centova71.instainternet.com/proxy/brisvaaniradio?mp=/stream' },
        { n = 'Britasia Radio Punjabi', u = 'https://s4.radio.co/sfefce156f/listen' },
        { n = 'Britishindiantamilradio', u = 'https://hello.citrus3.com:2020/stream/britishindiantamilradio' },
        { n = 'Canadian-Tamil-Radio-Ctr', u = 'https://www.liveradio.es/http://198.27.66.225:8498/stream' },
        { n = 'CARMEL FM', u = 'https://stream.zeno.fm/wcqgmtcfmy8uv' },
        { n = 'Cetalks', u = 'https://stream.zeno.fm/fzcvyyer01zuv' },
        { n = 'Cetalksradio', u = 'https://node-25.zeno.fm/nvh52yer01zuv?rj-ttl=5&rj-tok=AAABdW3i3noAlZtv4wxVBjY6iw' },
        { n = 'Chann Pardesi Radio', u = 'http://mehramedia.com:8021/' },
        { n = 'Channpardesi', u = 'https://mehramedia.in:3021/;' },
        { n = 'Chellam-Fm', u = 'https://sugu.radioca.st/stream/;stream/1' },
        { n = 'Chennai Live', u = 'http://c2.radioboss.fm:8332/stream' },
        { n = 'Chillax FM', u = 'http://stream.zeno.fm/ohhsihm2byluv' },
        { n = 'Chitrahitsmalayalam', u = 'http://stream.zeno.fm/dubvcz3rkrhvv' },
        { n = 'Chmala', u = 'https://stream-159.zeno.fm/dubvcz3rkrhvv?zs=aVDxKzveQw22WcHIuNRafQ' },
        { n = 'Cinaradio', u = 'https://ice8.securenetsystems.net/CINA' },
        { n = 'CIRF-AM 1350 Radio Humsafar Brampton, ON', u = 'https://ice66.securenetsystems.net/CIRF' },
        { n = 'City 92 FM', u = 'https://stream-41.zeno.fm/bauwkrnqhxhvv?zs=6ofxJ98qR9urEIW_oItpBg' },
        { n = 'City92Fm', u = 'https://stream.zeno.fm/bauwkrnqhxhvv' },
        { n = 'CJRK-FM 1027 East FM Toronto, ON', u = 'https://centova.radioservers.biz/proxy/eastfmc1/stream' },
        { n = 'CKYE-FM 931 Red FM Vancouver, BC', u = 'https://ice24.securenetsystems.net/CKYE' },
        { n = 'CKYR-FM 1067 Red FM Calgary, AB', u = 'https://ice10.securenetsystems.net/CKYR' },
        { n = 'Classic Old Time Radio', u = 'http://stream.zeno.fm/b6v6nu8uhnruv' },
        { n = 'Classic Radio Bhakti Sangeet', u = 'https://stream.zeno.fm/epylmeu4zf7vv' },
        { n = 'Club Asia Radio', u = 'https://s3.citrus3.com:8320/stream' },
        { n = 'Club FM 943', u = 'https://eu10.fastcast4u.com/clubfmuae' },
        { n = 'CMR Hindi FM Radio', u = 'https://live.cmr24.net/CMR/Desi_Music-MQ/icecast.audio' },
        { n = 'Cmr-Tamil-Hd-Radio', u = 'https://live.cmr24.net/CMR/TamilHD-HQ/icecast.audio' },
        { n = 'Cmrthamilfm', u = 'https://live.cmr24.net/CMR/CMR-MQ/icecast.audio' },
        { n = 'Covai FM', u = 'https://stream.zeno.fm/kzd2e3tx24zuv' },
        { n = 'Cricket Commentary Hindi', u = 'https://a1.asurahosting.com:9210/radio.mp3' },
        { n = 'Ctbc-Radio', u = 'https://www.liveradio.es/http://ctbcfmradio.primcast.com:4086/;' },
        { n = 'Desi World Radio', u = 'https://stream.zenolive.com/4mbfcn4mf24tv' },
        { n = 'Desibollywood', u = 'https://www.desizoneradio.com/relay2' },
        { n = 'Desiworld', u = 'https://stream.zeno.fm/4mbfcn4mf24tv' },
        { n = 'Devaprasannam-Radio', u = 'https://devaprasannam-a9media.radioca.st/stream' },
        { n = 'Dheepam-Fm', u = 'https://stream.zeno.fm/hszf3agf0k8uv' },
        { n = 'Dil FM UK', u = 'https://my4.radiolize.com/radio/8110/radio.mp3' },
        { n = 'Dindigul-Radio', u = 'https://spserver.sscast2u.in/dindigulcityfm/stream' },
        { n = 'Diverse FM', u = 'https://carol.epichosts.co.uk:8570/;' },
        { n = 'Divyavani', u = 'http://epsilon.shoutca.st:8070/autodj' },
        { n = 'Dr Kaajal Rohira Mindfulness', u = 'http://stream.zeno.fm/29agn2cdnm5uv' },
        { n = 'Dreamzzpunjabiradio', u = 'https://c7.radioboss.fm/stream/52' },
        { n = 'Dvnradio', u = 'https://ice31.securenetsystems.net/DVN' },
        { n = 'Eaglefm', u = 'https://streaming.radio.co/sf833cd785/listen' },
        { n = 'Easy 96 Radio', u = 'https://ice8.securenetsystems.net/EASY96' },
        { n = 'Easy96Fm', u = 'https://ice8.securenetsystems.net/EASY96?type=.mp3' },
        { n = 'Ebcradio', u = 'https://ice7.securenetsystems.net/WWTR?' },
        { n = 'Enteradio', u = 'https://cast1.my-control-panel.com/proxy/enteradio/stream' },
        { n = 'Ephphatha Radio', u = 'https://ephphatha.radioca.st/stream' },
        { n = 'Erode-City-Fm', u = 'https://stream.zeno.fm/9fp1383f0d0uv' },
        { n = 'Etrradio', u = 'https://bud.streampanel.net:6257/stream' },
        { n = 'Evergreen-Tamil-Radio', u = 'https://stream.zeno.fm/2fhh49f3zf8uv' },
        { n = 'Eye-Tamil-Radio', u = 'https://streams.radio.co/s937ac5492/listen' },
        { n = 'Fever 104 FM', u = 'https://radio.canstream.co.uk:8115/live.mp3' },
        { n = 'Filmy Mirchi', u = 'https://stream-142.zeno.fm/6n6ewddtad0uv?zs=cKmM_ShzRUaR2AGnxhugOg' },
        { n = 'FM 24 Bhiwadi 908', u = 'https://streamasiacdn.atc-labs.com/24network.aac' },
        { n = 'FM City 1001', u = 'https://stream-151.zeno.fm/4yfsm0d8n98uv?zs=vPZ4f9KeRxm234lLg5HvXw' },
        { n = 'Fm Kottarakkara', u = 'https://stream.zeno.fm/gqdb1rev5s8uv' },
        { n = 'FM Mizhivathil', u = 'https://stream.zeno.fm/w9xq9dyh1v8uv' },
        { n = 'Fm-City-100-1', u = 'https://stream-158.zeno.fm/4yfsm0d8n98uv?zs=gkh46OMDR-6sribg1nE_Ow' },
        { n = 'Fnffm Hindi', u = 'http://192.99.8.192:5032/;stream' },
        { n = 'Free FM 80S San Francisco', u = 'https://freefm80.radioca.st/' },
        { n = 'Free FM New York', u = 'https://rocafmadrid.radioca.st/' },
        { n = 'Free FM Rock Bombay', u = 'http://tachyon.shoutca.st:8298/' },
        { n = 'Free FM Top100 Paris', u = 'https://cosmo.streamerr.co/proxy/freefmtop/stream' },
        { n = 'Friendstamilchatfm', u = 'https://usa3.fastcast4u.com/proxy/dhayanib?mp=/;' },
        { n = 'Friendstamilfm', u = 'https://usa15.fastcast4u.com/proxy/tammus00?mp=/;' },
        { n = 'Funasia', u = 'https://funasia.streamguys1.com/live-1?_=1596332823914' },
        { n = 'Fusion Life Radio', u = 'https://c28.radioboss.fm:18046/stream' },
        { n = 'G-Tamil-Fm', u = 'https://gtr-unicast2u.radioca.st/stream' },
        { n = 'Gazal', u = 'https://prclive4.listenon.in/Ghazal' },
        { n = 'Gazal Radio London', u = 'https://streaming.webhostnepal.com/8018/stream' },
        { n = 'Goldenvoiceradio', u = 'https://stream.zeno.fm/s3sqemewrg0uv' },
        { n = 'Goldy Blast', u = 'https://stream.zeno.fm/d0rwvvwa6p8uv' },
        { n = 'Goldy Cool', u = 'https://stream.zeno.fm/3k1fb86tfm8uv' },
        { n = 'Goldy Evergreen', u = 'https://stream.zeno.fm/n2fd0edh9k8uv' },
        { n = 'Goldy Garba', u = 'https://stream.zeno.fm/n0zkr7wa6p8uv' },
        { n = 'Goldy Mukesh', u = 'https://stream.zeno.fm/t39watus1p8uv' },
        { n = 'Goldy Sarvaani', u = 'https://stream.zeno.fm/c5bt9h37bm8uv' },
        { n = 'GUP SHUP', u = 'https://internetradio.gupshupradio.com:8080/?type=mp3' },
        { n = 'Gurbani Kirtan', u = 'https://gurbanikirtan.radioca.st/start.mp3' },
        { n = 'Gurgaon Ki Awaaz FM', u = 'https://gurgaonradio.out.airtime.pro/gurgaonradio_a' },
        { n = 'Guru Geetham FM', u = 'https://stream.zeno.fm/9sfugwc9wg0uv' },
        { n = 'Gurubox Satsang', u = 'https://azura.shoutca.st/radio/8200/radio.mp3' },
        { n = 'Gvprakashradio', u = 'https://stream.zeno.fm/d5skwct7hqzuv' },
        { n = 'Hallos Radio', u = 'https://usa8.fastcast4u.com/proxy/auralradio?mp=/1' },
        { n = 'Hand Of Jesus - AFRICAN', u = 'https://dc1.serverse.com/proxy/hojafrican/stream' },
        { n = 'Hand Of Jesus - BANGLA', u = 'https://dc1.serverse.com/proxy/hojbengali/stream' },
        { n = 'Hand Of Jesus - BIBLE INFORMATION', u = 'https://dc1.serverse.com/proxy/hoj5/stream' },
        { n = 'Hand Of Jesus - CHINESE', u = 'https://dc1.serverse.com/proxy/hojchinese/stream' },
        { n = 'Hand Of Jesus - DANIEL', u = 'https://dc1.serverse.com/proxy/hoj2/stream' },
        { n = 'Hand Of Jesus - END TIME - TAMIL', u = 'https://dc1.serverse.com/proxy/hojendtime/stream' },
        { n = 'Hand Of Jesus - ENGLISH', u = 'https://dc1.serverse.com/proxy/hojenglish/stream' },
        { n = 'Hand Of Jesus - ESTHER RANI', u = 'https://dc1.serverse.com/proxy/hoj1/stream' },
        { n = 'Hand Of Jesus - FRENCH', u = 'https://dc1.serverse.com/proxy/hojfrenc/stream' },
        { n = 'Hand Of Jesus - GUJARATI', u = 'https://dc1.serverse.com/proxy/hojgujarati/stream' },
        { n = 'Hand Of Jesus - HEBREW', u = 'https://dc1.serverse.com/proxy/hojhebrew/stream' },
        { n = 'Hand Of Jesus - HINDI', u = 'https://dc1.serverse.com/proxy/hojhindi/stream' },
        { n = 'Hand Of Jesus - KANNADA', u = 'https://dc1.serverse.com/proxy/hojkannada/stream' },
        { n = 'Hand Of Jesus - KONKANI', u = 'https://dc1.serverse.com/proxy/hojkonkani/stream' },
        { n = 'Hand Of Jesus - MALAYALAM', u = 'https://dc1.serverse.com/proxy/hojmalayalam/stream' },
        { n = 'Hand Of Jesus - MANIPURI', u = 'https://dc1.serverse.com/proxy/hojmanipuri/stream' },
        { n = 'Hand Of Jesus - MARATHI', u = 'https://dc1.serverse.com/proxy/hojmarathi/stream' },
        { n = 'Hand Of Jesus - MIZO', u = 'https://dc1.serverse.com/proxy/hojmizo/stream' },
        { n = 'Hand Of Jesus - NEPALI', u = 'https://dc1.serverse.com/proxy/hojnepali/stream' },
        { n = 'Hand Of Jesus - ODIA', u = 'https://dc1.serverse.com/proxy/hojoriya/stream' },
        { n = 'Hand Of Jesus - PAUL', u = 'https://dc1.serverse.com/proxy/hoj4/stream' },
        { n = 'Hand Of Jesus - PETER', u = 'https://dc1.serverse.com/proxy/hoj3/stream' },
        { n = 'Hand Of Jesus - PUNJABI', u = 'https://dc1.serverse.com/proxy/hojpunjabi/stream' },
        { n = 'Hand Of Jesus - TAMIL', u = 'https://dc1.serverse.com/proxy/hojtamil/stream' },
        { n = 'Hand Of Jesus - TAMIL BIBLE', u = 'https://dc1.serverse.com/proxy/hojbible/stream' },
        { n = 'Hand Of Jesus - TAMIL KIDS', u = 'https://dc1.serverse.com/proxy/hojkids/stream' },
        { n = 'Hand Of Jesus - TELUGU', u = 'https://dc1.serverse.com/proxy/hojtelugu/stream' },
        { n = 'Hand Of Jesus - URDU', u = 'https://dc1.serverse.com/proxy/hojurdu/stream' },
        { n = 'Hari-Tamil-Fm', u = 'https://haritamilfm-prabak78.radioca.st/stream' },
        { n = 'Harris Jayaraj FM', u = 'http://stream.zeno.fm/ob6tjg8gulptv' },
        { n = 'Harrisjayarajradio', u = 'https://stream.zeno.fm/0bhsthssutzuv' },
        { n = 'Hasya Katta Official', u = 'https://stream.zeno.fm/grpa985az98uv.m3u' },
        { n = 'Hawamahal Radio', u = 'https://stream-154.zeno.fm/csw7fv7sz1zuv?zs=ABfIaXh5T-65UHo9uTNoAQ' },
        { n = 'Healer-Radio', u = 'https://c13.radioboss.fm:8552/healerradio' },
        { n = 'Hello FM 1064', u = 'https://stream.zenolive.com/4g65yz9gg0quv.aac' },
        { n = 'Himal Hindi Classic Radio', u = 'https://streaming.webhostnepal.com/8012/stream' },
        { n = 'Himal Radio', u = 'https://streaming.webhostnepal.com/8020/stream' },
        { n = 'Hindi - Hits', u = 'http://stream.zeno.fm/m38h4nmgxs8uv' },
        { n = 'Hindi Gold Radio', u = 'https://azuracast.vibesounds.in:8010/radio.mp3' },
        { n = 'Hindi Retro', u = 'https://stream.zeno.fm/v2zfmxef798uv' },
        { n = 'Hindvani FM', u = 'https://edge.iono.fm/xice/129_medium.aac' },
        { n = 'Hit Of Lata', u = 'http://stream.zeno.fm/g95zm67prfhvv' },
        { n = 'Hits Of Bollywood', u = 'http://stream.zeno.fm/8ty8szwpwfeuv.m3u' },
        { n = 'Hits Of Kishor Kumar', u = 'http://stream.zeno.fm/pg6rqp8ztm0uv.m3u' },
        { n = 'Hits Of Lata Mangeshkar', u = 'http://stream.zeno.fm/g95zm67prfhvv.m3u' },
        { n = 'Hits Of Mohammed Rafi', u = 'http://stream.zeno.fm/0zkr7x8ztm0uv.m3u' },
        { n = 'Hitsbollywood', u = 'https://node-14.zeno.fm/rqqps6cbe3quv?rj-ttl=5&rj-tok=AAABccQyYG8AGJ3KW_903AafBw' },
        { n = 'Hitsofbollywood', u = 'https://node-08.zeno.fm/a2gyqzwpwfeuv.aac?rj-ttl=5&rj-tok=AAABc6yhYroA-BQkZAca7Yj0jA' },
        { n = 'Hot Now Bangla', u = 'https://stream.radiotreetal.com/listen' },
        { n = 'Humsafar', u = 'https://ice2.securenetsystems.net/HUMSAFAR' },
        { n = 'Ibc-Tamil-Radio', u = 'https://rbx2.hnux.com/http://10454.cloudrad.io:6176/;stream.mp3' },
        { n = 'Idiotic Radio', u = 'https://stream.zeno.fm/1c4vtuzvveruv' },
        { n = 'Ilctamil', u = 'https://stream.zeno.fm/vewxk5336qzuv' },
        { n = 'Imaifm', u = 'https://centova71.instainternet.com/proxy/imaifmradio?mp=/stream' },
        { n = 'Inbam Fm', u = 'https://stream.radio.co/sf55ced545/listen' },
        { n = 'Inbathamiloli', u = 'https://usa7.fastcast4u.com/proxy/ozmediae?mp=/1' },
        { n = 'Indianlinkradio', u = 'https://indianlink1.radioca.st/;' },
        { n = 'Indifun', u = 'http://indifun.net:7000/;' },
        { n = 'Indifun Radio', u = 'http://162.241.114.203:7000/listen.pls?sid=1' },
        { n = 'Instrumental-Music-Radio', u = 'https://azuracast.vibesounds.in:8030/radio.mp3' },
        { n = 'Isai-Fm', u = 'https://stream.zeno.fm/7b78sdv2x1zuv' },
        { n = 'Isai-Tamil-Radio', u = 'https://radioplayer.putulhost.com/public/radiostreamfiles/radio4.php' },
        { n = 'Isaitamilfm', u = 'https://spserver.sscast2u.in/isaitamilfm/stream' },
        { n = 'Isaiyaruvi-Fm', u = 'https://cp1.hostcrate.com/8910/stream' },
        { n = 'Itr', u = 'https://radio5.pro-fhi.net/flux-hgtidrcv/stream' },
        { n = 'Iyalisai-Bhakti-Radio', u = 'https://mhariraa.radioca.st/stream' },
        { n = 'J U RADIO', u = 'http://stream.zeno.fm/60ef4p33vxquv' },
        { n = 'Jagat Radio Punjabi', u = 'https://node-32.zeno.fm/b7afzr3cmzzuv' },
        { n = 'Janvanifm', u = 'https://centova87.instainternet.com/proxy/janvanif?mp=/stream' },
        { n = 'Jap Radio', u = 'http://stream.zeno.fm/r3m0whh0kxquv' },
        { n = 'Jayam Fm 71', u = 'https://jayamfm-prabak78.radioca.st/stream' },
        { n = 'Jcbroadcast', u = 'https://eu9.fastcast4u.com/proxy/simon?mp=/1' },
        { n = 'Jehovahrapha-Fm', u = 'https://c22.radioboss.fm:8532/jehovahrapha' },
        { n = 'Jesus Alive Radio', u = 'http://stream.zenolive.com/qyb8s75nsceuv' },
        { n = 'Jesus Coming FM – German', u = 'http://live.jesuscomingfm.com:8282/stream/' },
        { n = 'Jesus Radio Malayalam', u = 'https://gains.reviveradio.net/proxy/jesusreigns?mp=/stream' },
        { n = 'Jhanjar Radio', u = 'http://stream.radiojar.com/vy37pdm40uquv' },
        { n = 'JN FM TAMIL', u = 'http://stream.zeno.fm/0wck59rarchvv' },
        { n = 'JN FM TAMIL CLASSIC', u = 'http://stream.zeno.fm/qkdmq6d7kfhvv' },
        { n = 'Just Odisha Radio', u = 'https://cast3.my-control-panel.com/proxy/justodis/stream' },
        { n = 'K-J-Yesudas-Radio', u = 'https://stream.zeno.fm/uvdbygm6a48uv' },
        { n = 'Kalabhavan Mani Radio', u = 'https://stream.zeno.fm/s6hhy943w0hvv' },
        { n = 'Kalai Fm-Tamil', u = 'https://stream.zenolive.com/2vghnwshsqzuv.aac' },
        { n = 'Kalaignar-Fm', u = 'https://node-10.zeno.fm/x3rmesp5g18uv?rj-ttl=5&rj-tok=AAABfvIYmnMAEwu_kdBD9SXO4A' },
        { n = 'Kalvi-Radio', u = 'https://stream.zeno.fm/xezgztet6whvv' },
        { n = 'Kannadahits', u = 'https://stream.zeno.fm/68snnbug8rhvv' },
        { n = 'Kathiravan Fm', u = 'https://kathiravanfm-prabak78.radioca.st/stream' },
        { n = 'Kathirfm', u = 'https://stream.zeno.fm/ce1nxbxxnrquv' },
        { n = 'Kishore Kumar Hits', u = 'https://stream-148.zeno.fm/0ghtfp8ztm0uv?zs=fcfkH5A1Ssi4PNvrmTgXmg' },
        { n = 'Kishore Kumar Radio', u = 'https://stream-48.zeno.fm/0ghtfp8ztm0uv?zs=Kr_rJK1kSsKPKeUo9zgTxw&rj-ttl=5&rj-tok=AAABefQSIpIAGxcgV3Wv5gK8Kg' },
        { n = 'Kishorekumarradio', u = 'https://stream.zeno.fm/0ghtfp8ztm0uv' },
        { n = 'KJ Yesudas', u = 'https://stream-21.zeno.fm/uvdbygm6a48uv?zs=leR0dq-7RuWI-AdM0jItaA' },
        { n = 'KJ Yesudas Malayalam Radio', u = 'https://stream.zeno.fm/9x1sw687nf9uv' },
        { n = 'Kodai-Ragam-Fm', u = 'https://sp.radiotamilonline.com/8006/stream' },
        { n = 'Kodaiaruvifm', u = 'https://spserver.sscast2u.in/kodaiaruvifm/stream' },
        { n = 'KODAIRAGAM FM', u = 'https://centova57.instainternet.com/proxy/kodairagamradio?mp=/stream' },
        { n = 'Kohinoor Radio 973 FM', u = 'https://stream-060.zeno.fm/2gc5f5ggup8uv?zs=4wRjfZcPRFqFovuYy-9fgQ' },
        { n = 'Kripalu Bhakti Dhara Radio', u = 'https://kbd.out.airtime.pro/kbd_b' },
        { n = 'KRPI Ferndale 1550 AM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/KRPIAM_SC' },
        { n = 'KS CHITRA', u = 'https://stream-46.zeno.fm/aad4e51qz7zuv?zs=KFvl1-YuQkuqY2m7VeO4hQ' },
        { n = 'Ks-Chitra-Radio', u = 'https://stream.zeno.fm/aad4e51qz7zuv' },
        { n = 'Kumar Sanu Radio', u = 'https://stream-26.zeno.fm/70nen96vgs8uv' },
        { n = 'Kuzhippalathil', u = 'http://stream.zeno.fm/qr8ppfs22rhvv' },
        { n = 'Lakshaypar', u = 'https://lakshyapar.getstreamhosting.com:8100/stream' },
        { n = 'Lankasri-Fm', u = 'https://rbx2.hnux.com/http://5984.cloudrad.io:8032/;stream.mp3' },
        { n = 'Latamangeshkarradio', u = 'https://stream.zeno.fm/87xam8pf7tzuv' },
        { n = 'Lekhakan Radio', u = 'https://stream.radio.co/s1383afdc9/listen' },
        { n = 'Life-Fm', u = 'https://stream.zeno.fm/37tsftts91zuv' },
        { n = 'Live Kirtan Sri Harmander Sahib', u = 'https://live.sgpc.net:8442/' },
        { n = 'Live Kirtan Sri Harmandir Sahib', u = 'https://live.sgpc.net:8443/;nocache=889869' },
        { n = 'Lmrradio', u = 'https://ais-edge51-live365-dal02.cdnstream.com/a50671' },
        { n = 'London Malayalam Radio', u = 'https://ais-edge105-live365-dal02.cdnstream.com/a50671' },
        { n = 'London Telugu Radio', u = 'https://c8.radioboss.fm/stream/33' },
        { n = 'Love Station Odisha', u = 'https://stream-156.zeno.fm/dkpdmc8e0chvv?zs=uhX7-GwNR1-D5EAX_NJ1lQ' },
        { n = 'Luminous Radio', u = 'http://192.111.140.6:8546/stream' },
        { n = 'Luminous-Radio', u = 'https://patmos.cdnstream.com/proxy/luminous/?mp=/stream' },
        { n = 'Luminousradiomalayalam', u = 'https://node-01.zeno.fm/1a8r3ugrn7zuv?rj-ttl=5&rj-tok=AAABc60Whb8A20ig1x3DtwIVoA' },
        { n = 'Lyca Gold', u = 'https://listen-lycaradio.sharp-stream.com/1035.mp3' },
        { n = 'Lyca Radio 1458 AM', u = 'https://ads-direct.sharp-stream.com/1458.mp3' },
        { n = 'Lycaradio', u = 'https://tx.sharp-stream.com/http_live.php?i=1458.mp3' },
        { n = 'M S Viswanathan FM', u = 'http://stream.zeno.fm/x7wc1xgllvsvv' },
        { n = 'Maayboli Marathi', u = 'http://stream.zeno.fm/48kybvzrwfeuv.m3u' },
        { n = 'Madhur Sangeet Radio', u = 'https://stream.zeno.fm/yv2k0dp18vzuv' },
        { n = 'Madhur Tarang Kannada', u = 'https://stream.zenolive.com/v0gde6udfg8uv' },
        { n = 'Magesh Online Radio 247', u = 'http://stream.zeno.fm/8pm38q5dr7zuv' },
        { n = 'Magesh Tamil Radio', u = 'http://stream.zeno.fm/ezmck9cz5bhvv' },
        { n = 'Magizh-Asia-Hd', u = 'https://stream.zeno.fm/vqq7av4d8yzuv' },
        { n = 'Magizhchifm', u = 'https://usa15.fastcast4u.com/proxy/magizhchifm?mp=/1' },
        { n = 'Mala90', u = 'https://stream.zeno.fm/gm3g9amzm0hvv' },
        { n = 'Malayagam-Fm', u = 'https://malayagamfm.radioca.st/stream' },
        { n = 'Malayalam-Remix', u = 'https://stream-150.zeno.fm/pdgarvnt6k8uv' },
        { n = 'Malayalambhakthiradio', u = 'https://stream.zeno.fm/08e1vkshcc9uv' },
        { n = 'Malayalammusic', u = 'https://stream.zeno.fm/g8cx7tggb3quv.aac' },
        { n = 'Malayam Islam Ilmussalaf', u = 'https://equinox.shoutca.st/tunein/darhdth.pls' },
        { n = 'Malever', u = 'https://stream-158.zeno.fm/5u6gkp9sp0hvv' },
        { n = 'Mallappally-Live', u = 'https://stream.zeno.fm/s3ndrooucoyvv' },
        { n = 'Mallu Radio', u = 'https://stream.zeno.fm/mqyb58u61eruv' },
        { n = 'Malysadan', u = 'https://stream-153.zeno.fm/8g9nvr1rkrhvv?zs=96ocfKngQau54X0QIaJgkA' },
        { n = 'Marina Mango', u = 'https://stream.marinafm.com/proxy/marinamango/marinamango' },
        { n = 'Marymatharadio', u = 'https://stream.zeno.fm/g5ay9q4dgrruv' },
        { n = 'Maveli Radio', u = 'https://stream.zeno.fm/77fs4kfuhnruv' },
        { n = 'Mazhai-Fm', u = 'https://stream.zeno.fm/yu4c9ms3h2zuv' },
        { n = 'Mazhalaitamilradio', u = 'https://mazhalaitamilradio-prabak78.radioca.st/stream' },
        { n = 'Mazhavil Malayalam', u = 'https://stream.zeno.fm/wq64yce0ra0uv' },
        { n = 'Mega-Zone-South', u = 'https://vm65162.streamerr.co/listen/megazone_south/radio.mp3' },
        { n = 'Mehefilradio', u = 'http://stream.zeno.fm/yqa1zkhrn7zuv' },
        { n = 'Menorahradio', u = 'https://gains.reviveradio.net/proxy/menorah?mp=/stream' },
        { n = 'Minnal FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/MINNAL_FMAAC.aac' },
        { n = 'Mirchi Love', u = 'https://drive.uber.radio/uber/bollywoodlove/icecast.audio' },
        { n = 'Mirchi Love Hindi', u = 'https://drive.uber.radio/uber/lrbollywood/icecast.audio' },
        { n = 'Mirchi Top 20', u = 'https://drive.uber.radio/uber/bollywoodnow/icecast.audio' },
        { n = 'Mixify', u = 'https://server.mixify.in/listen/evergreen/radio.mp3' },
        { n = 'Mixify Bollywood', u = 'https://server.mixify.in/listen/listen/radio.mp3' },
        { n = 'Mixify Evergreen Hits', u = 'https://server.mixify.in:8010/' },
        { n = 'Mixify Hindi Hits', u = 'https://server.mixify.in/listen/new_hits/radio.mp3' },
        { n = 'Mohabbat Radio', u = 'https://stream.zeno.fm/t2ekq8zsgtzuv' },
        { n = 'Mohabbat Radio Punjabi', u = 'http://stream.zeno.fm/t2ekq8zsgtzuv' },
        { n = 'Mohammed Rafi', u = 'https://stream.zeno.fm/6yqvumgfxtzuv' },
        { n = 'Mohammed Rafi Radio', u = 'http://stream.zeno.fm/cgh735squ98uv' },
        { n = 'Mohanhits', u = 'https://stream.zeno.fm/wkqvzsg1238uv' },
        { n = 'Mohanlal Hits', u = 'https://stream.zeno.fm/5vva7u4ts0quv' },
        { n = 'Mohanlalhits', u = 'http://stream.zeno.fm/5vva7u4ts0quv' },
        { n = 'Mozhi FM', u = 'https://stream.zeno.fm/vgd466bfffhvv' },
        { n = 'Mozhi-Fm', u = 'https://stream-152.zeno.fm/vgd466bfffhvv?zs=gofu6e0lQSK9SCa77t60-w' },
        { n = 'Mukesh Radio', u = 'https://stream-014.zeno.fm/mrcz5sus1p8uv' },
        { n = 'Mukil-Fm', u = 'https://stream.zeno.fm/9s8119m1rzzuv' },
        { n = 'Mukil-Fm-Radio', u = 'https://stream.zeno.fm/phv06yfkwzzuv' },
        { n = 'Muthamilradio', u = 'https://ec2.yesstreaming.net:2540/stream' },
        { n = 'My 90S Bengali', u = 'http://stream.zeno.fm/2k6xfu1pvs8uv' },
        { n = 'MY CLUB REMIX', u = 'http://stream.zeno.fm/u7eee0hyzp8uv' },
        { n = 'MY RADIO DJ', u = 'http://stream.zeno.fm/84h97t3ewg0uv' },
        { n = 'N Radio Live', u = 'https://stream.zeno.fm/4yfsm0d8n98uv' },
        { n = 'Naan FM', u = 'http://stream.zeno.fm/swgzh04zbg0uv' },
        { n = 'Naan-Radio', u = 'https://stream.zeno.fm/swgzh04zbg0uv' },
        { n = 'Namaste Bollywood', u = 'https://stream.zeno.fm/cqak4ap7by8uv' },
        { n = 'Namm Radio Kannada', u = 'https://stream.zenolive.com/bbs8prb015quv' },
        { n = 'Nammradio', u = 'http://stream.zeno.fm/6quh1pfnt1duv' },
        { n = 'Nammradiogulf', u = 'http://stream.zeno.fm/kgw2tp5p1y5tv' },
        { n = 'Nammradious', u = 'http://stream.zeno.fm/kc4wg3ent1duv' },
        { n = 'Nammura Baanuli', u = 'http://198.245.61.103:8029/stream' },
        { n = 'Natrinaifm', u = 'https://centova32.instainternet.com/proxy/sasi?mp=/1' },
        { n = 'Nellai FM', u = 'https://stream.zenolive.com/5nu139840tzuv.aac' },
        { n = 'Nellai-Tamil-Fm', u = 'https://stream.zeno.fm/5nu139840tzuv' },
        { n = 'New Hits Of Bollywood', u = 'https://stream-146.zeno.fm/rqqps6cbe3quv?zs=loHp_DNyRPiAxC52AL95hg' },
        { n = 'Njanmalayalibhakthi', u = 'https://stream.zeno.fm/w9kku8utuy8uv' },
        { n = 'Njsunriseradio', u = 'https://njsunrise.out.airtime.pro/njsunrise_a' },
        { n = 'Nonstophindi', u = 'https://www.liveradio.es/http://s5.voscast.com:8216/stream' },
        { n = 'Nostalgic Bollywood 90S Radio', u = 'https://www.desizoneradio.com/relay3' },
        { n = 'NP 24 Radio', u = 'https://stream.zeno.fm/8wk1s0pt008uv' },
        { n = 'Numtamilradio', u = 'http://usa15.fastcast4u.com/proxy/tammus00?mp=/;' },
        { n = 'Oakylp', u = 'http://stream.oak935.org/oak935-128.aac' },
        { n = 'Odisha Radio', u = 'https://stream.zeno.fm/x23ttc8e0chvv' },
        { n = 'Old Monk Radio', u = 'https://stream.zeno.fm/pr0zc64zdy8uv' },
        { n = 'Om Radio Singapore', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/OMRADIO_S01AAC_SC' },
        { n = 'OMR Radio Malaylam', u = 'http://stream.zeno.fm/x2baeup395quv' },
        { n = 'Osho Radio', u = 'http://radioe.dns.osho.com:8348/live' },
        { n = 'Paasamfm', u = 'http://stream.zeno.fm/wx8ue96nc18uv' },
        { n = 'Panjab Radio UK', u = 'http://s1.voscast.com:7918/;' },
        { n = 'Parwaz Radio', u = 'http://mehramedia.com:8081/' },
        { n = 'Parwaz Radio Punjabi', u = 'http://mehramedia.com:8081/;' },
        { n = 'Pasanga-Fm', u = 'https://www.liveradio.es/http://s7.voscast.com:10864;' },
        { n = 'Peace Radio', u = 'https://peaceradio.out.airtime.pro/peaceradio_a' },
        { n = 'Peaceradio', u = 'http://stream.peaceradio.com:8000/high' },
        { n = 'Peaceradio Quran', u = 'http://stream.peaceradio.com:8000/quran/high' },
        { n = 'Planet Radio City Telugu Bhakti', u = 'https://prclive4.listenon.in/Bhakti' },
        { n = 'Pollachi Fm', u = 'http://104.200.16.182:8000/stream/1/' },
        { n = 'Pollachifm', u = 'https://stream.zeno.fm/f29eh57d3qzuv' },
        { n = 'Pozhil-Fm', u = 'https://stream.zeno.fm/ssnf4ya44d0uv' },
        { n = 'Prabhakar Radio', u = 'https://stream.zeno.fm/2uh6hkmzdzzuv' },
        { n = 'Pranayamradio', u = 'https://stream.zeno.fm/g2zves9gdwzuv' },
        { n = 'Psalmsradio', u = 'https://s2.citrus3.com:8046/stream' },
        { n = 'Pudugai-Isai-Fm', u = 'https://pudhugaisaifm-prabak78.radioca.st/stream' },
        { n = 'Punjab Rocks Radio', u = 'http://radio.punjabrocks.com:9988/;' },
        { n = 'R', u = 'https://stream.zeno.fm/2zzz7qre56duv' },
        { n = 'Radio 4 Public Health', u = 'https://cast4.my-control-panel.com/proxy/demo4usv/live' },
        { n = 'Radio 905 FM', u = 'https://ice42.securenetsystems.net/CR90' },
        { n = 'Radio Aashiqanaa', u = 'https://sonic.onlineaudience.co.uk/8114/stream?listening-from-radio-garden=1657427657' },
        { n = 'Radio Active 904 FM', u = 'https://stream.zeno.fm/xwhhyc5nyk8uv' },
        { n = 'Radio Afsana', u = 'http://us9.streamingpulse.com:7058/stream' },
        { n = 'Radio Amchikonkani', u = 'http://178.32.107.151:3711/stream' },
        { n = 'Radio AMR Kannada', u = 'https://stream.zenolive.com/7g8axtgtsg0uv' },
        { n = 'Radio Asha Bhosle', u = 'http://stream.zeno.fm/s8e3x4yqu98uv' },
        { n = 'Radio Azad', u = 'https://usa2.fastcast4u.com/proxy/jgivvimk?mp=/1' },
        { n = 'Radio Badal', u = 'https://stream.zeno.fm/nhrtcxg09u8uv' },
        { n = 'Radio Bangla Net', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SP_R3563475_SC' },
        { n = 'Radio Bhojpuriya', u = 'http://streaming.softnep.net:8143/;stream.nsv&type=mp3&volume=60' },
        { n = 'Radio Bhubaneswar', u = 'https://cast3.my-control-panel.com/proxy/radiobbsr/stream' },
        { n = 'Radio Bhumi', u = 'https://stream.zeno.fm/ybf1umk1k18uv' },
        { n = 'Radio Bollyfm', u = 'http://stream.radiobollyfm.in:8201/hd?t=1526570335' },
        { n = 'Radio Bollywood Gaane Purane', u = 'https://stream-145.zeno.fm/6n6ewddtad0uv?zs=Hc47dloSRx-vBgJnNOT8DA' },
        { n = 'Radio Bula Masti', u = 'https://c7.radioboss.fm:18052/stream' },
        { n = 'Radio Cafe', u = 'https://stream.zeno.fm/gqmh0caknchvv' },
        { n = 'Radio Caravan', u = 'https://stream.voxx.pro/radio/8260/radio.mp3' },
        { n = 'Radio Central 24', u = 'https://casper.radioca.st/stream' },
        { n = 'Radio Chahat', u = 'https://streamer.radio.co/sdb05c0648/listen' },
        { n = 'Radio Chardi Kala Punjabi', u = 'http://stream.zenolive.com/65b1awrgnv5tv' },
        { n = 'Radio Choklate', u = 'https://stream.zeno.fm/1t5ceyhcxbruv' },
        { n = 'Radio City 911 FM', u = 'https://prclive1.listenon.in/' },
        { n = 'Radio City Dance', u = 'https://prclive1.listenon.in/Dance' },
        { n = 'Radio City Freedom', u = 'https://prclive4.listenon.in/Freedom' },
        { n = 'Radio City Hindi', u = 'http://radio.garden/api/ara/content/listen/to5IKEqr/channel.mp3?1626611643750' },
        { n = 'Radio City Hip-Hop', u = 'https://stream-62.zeno.fm/gut7ff5uyc9uv?zs=SJN4wL6OR8GqeQ3G2gSILA' },
        { n = 'Radio City Kannada', u = 'https://stream-18.zeno.fm/m3q5v4dvyc9uv' },
        { n = 'Radio City Love Guru', u = 'https://prclive4.listenon.in/Ishq' },
        { n = 'Radio City Malayalam', u = 'https://prclive4.listenon.in/Malayalam' },
        { n = 'Radio City Punjabi', u = 'https://prclive1.listenon.in/Punjabi' },
        { n = 'Radio City Telugu', u = 'https://stream.zeno.fm/2532fy6zrf9uv' },
        { n = 'Radio Deewana', u = 'https://stream.zeno.fm/x1q3r3qdxy8uv' },
        { n = 'Radio Dehotties', u = 'https://s6.myradiostream.com/:15054/;' },
        { n = 'Radio Dhaakad', u = 'http://radiodhaakad.com:8000/live?type=.mp3' },
        { n = 'Radio Dhoom', u = 'https://servidor37.brlogic.com:7502/live' },
        { n = 'Radio Dhwani', u = 'https://static.s123-cdn-static-c.com/uploads/2568273/normal_5d8ba39d1261c.mp3' },
        { n = 'Radio Digital Malayali', u = 'https://radio.digitalmalayali.in/listen/stream/radio.mp3' },
        { n = 'Radio Dil', u = 'https://us3.streamingpulse.com/ssl/radiodil2' },
        { n = 'Radio Dunia Odia', u = 'https://stream.justneed.in:2087/listen/radio_dunia/radio.mp3' },
        { n = 'Radio Fiji Two', u = 'https://peridot.streamguys1.com:7150/RFTwo' },
        { n = 'RADIO FUERZA 3', u = 'https://vivo.miradio.in:7039/live' },
        { n = 'Radio Gyansthali 896 FM', u = 'https://streamasiacdn.atc-labs.com/gyansthali.aac' },
        { n = 'Radio Haanji Punjabi', u = 'http://stream.zenolive.com/unkxya7qf1duv.mp3' },
        { n = 'Radio Hind', u = 'https://azct1.cheapazuracast.xyz/radio/8020/128kbps.mp3' },
        { n = 'Radio Hungama Bollywood Dil Se', u = 'https://stream.zeno.fm/143d7gty24zuv' },
        { n = 'Radio Indradhanush', u = 'https://stream.zeno.fm/d7txbwyxfxhvv' },
        { n = 'Radio Jagriti 904 FM', u = 'https://stream.zeno.fm/kgdue4hmffhvv' },
        { n = 'Radio JSR', u = 'http://198.7.59.28:8078/stream/1/' },
        { n = 'Radio Kavalam', u = 'http://stream.zeno.fm/qiqbsyc9zqrvv' },
        { n = 'Radio Kavalam Bhajana', u = 'https://stream.zeno.fm/1lzyttobkcsuv' },
        { n = 'Radio Kavalam Carnatic', u = 'https://stream.zeno.fm/ij0xwxrfxa2vv' },
        { n = 'Radio Kesari 900 FM', u = 'https://stream.zeno.fm/7yhq985hnxhvv' },
        { n = 'Radio Khushkhabri', u = 'http://edge-audio-03-gos2.sharp-stream.com/khushkhabri.mp3' },
        { n = 'Radio Krishna', u = 'https://millenniumhits.out.airtime.pro:8000/millenniumhits_a?fbclid=IwAR0qP_F8RgDCq3gX8g7U8Dmm_uZedtPrqxCf8iIDAW5Jcd5ktA0XMs6BJu4' },
        { n = 'Radio Lata Mangeshkar', u = 'https://stream-161.zeno.fm/87xam8pf7tzuv?zs=fvTPIM3xTWi1Ik-Z9095aA' },
        { n = 'Radio Lemon', u = 'https://stream.zeno.fm/2qnbwwr7508uv' },
        { n = 'Radio Madhur Tarang', u = 'https://stream.zeno.fm/v0gde6udfg8uv' },
        { n = 'Radio Maharani', u = 'https://streamasiacdn.atc-labs.com/radiomaharani.aac' },
        { n = 'Radio Malayalam 986 FM', u = 'https://stream.zeno.fm/512rbf1e3qzuv' },
        { n = 'Radio Malayalam Canada', u = 'https://stream.zeno.fm/u3vr9bezvk8uv' },
        { n = 'Radio Malda', u = 'http://stream.zeno.fm/10rt7tpf6ehvv' },
        { n = 'Radio Manpasand', u = 'https://c5.radioboss.fm:18125/stream' },
        { n = 'RADIO MARIA INDIA', u = 'http://dreamsiteradiocp.com:8002/stream' },
        { n = 'Radio Mata Ji Durga Laxmi', u = 'https://ibadat.out.airtime.pro/ibadat_a?fbclid=IwAR2lnBbSVZVTRowXxo0eAfNP98LktcxgsqUaxNrCBmqjgmkGYWoDj11Zy7o' },
        { n = 'RADIO MATTOLI', u = 'http://cast1.my-control-panel.com/proxy/radiomattoli/stream' },
        { n = 'Radio Mirchi Hindi', u = 'https://eu8.fastcast4u.com/proxy/clyedupq/stream' },
        { n = 'Radio Mirchi USA', u = 'https://streams.radio.co/s8d06d0298/listen' },
        { n = 'Radio Namkin', u = 'https://stream.zeno.fm/yg1qhsbaqv5tv' },
        { n = 'Radio Navtarang', u = 'https://stream.fijivillage.com/navtarang' },
        { n = 'Radio Naya Andaz', u = 'https://radionayaandaz.out.airtime.pro/radionayaandaz_a' },
        { n = 'Radio Olive Kids', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_OLIVE_CLUB_S04AAC.aac' },
        { n = 'Radio Olive Retro', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_OLIVE_RETRO_S03_SC' },
        { n = 'Radio Onattukara', u = 'http://stream.zeno.fm/fu94u25kqd0uv/;stream.mp3' },
        { n = 'Radio Panchajanya', u = 'https://d3ctxlq1ktw2nl.cloudfront.net/staging/2023-8-27/24e94d7f-07dc-9d45-95d0-ddfbbda2b7ae.mp3' },
        { n = 'Radio Paramankurichi Tamil', u = 'https://vpmurugun.radioca.st/stream' },
        { n = 'Radio Parbhani 908 Fm', u = 'http://85.25.185.202:8074/stream' },
        { n = 'Radio Pragya 904 MHZ', u = 'https://stream.zeno.fm/g42tzhe29f8uv' },
        { n = 'Radio Preet', u = 'https://stream.zeno.fm/w515pk5zc48uv' },
        { n = 'Radio Punjab Canada', u = 'https://stream-076.zeno.fm/67v0d997bzzuv?zs=u6lalcGUQpyrPhSNDI54LQ' },
        { n = 'Radio Punjab Today', u = 'http://stream.zenolive.com/019324w4ez4tv' },
        { n = 'Radio Punjabi Mehak', u = 'http://stream.zenolive.com/0xsvm1nr7a5tv' },
        { n = 'Radio Punjabi Virsa', u = 'https://node-15.zeno.fm/vpak30btzwzuv' },
        { n = 'Radio Raibar Live', u = 'https://cdn1.mediaisyou.com/radioraibar.mp3' },
        { n = 'Radio Rang', u = 'http://stream.zeno.fm/44r9x09cqchvv' },
        { n = 'Radio Ranjeet', u = 'https://stream.zeno.fm/cfb2xtykhaptv' },
        { n = 'Radio Retro Bollywood 90S', u = 'https://stream-143.zeno.fm/fdgs82xkzhhvv' },
        { n = 'Radio Risham Punjabi', u = 'https://stream.zeno.fm/4pd041xv1a0uv' },
        { n = 'Radio Sagun', u = 'https://stream.zenolive.com/s2sbba66bzzuv.aac' },
        { n = 'Radio Sai Discourse Stream', u = 'http://stream.radiosai.net:8008/' },
        { n = 'Radio Sai Global Harmony Bhajan', u = 'http://stream.radiosai.net:8000/' },
        { n = 'Radio Sajawat', u = 'https://usa3.fastcast4u.com/proxy/radiosajawat?mp=/1' },
        { n = 'Radio Sangam', u = 'https://streaming.radio.co/s58948a3f0/listen' },
        { n = 'Radio Saptarang', u = 'https://stream-58.zeno.fm/ttcsc4tf8yzuv' },
        { n = 'Radio Sargam', u = 'https://stream.fijivillage.com/radiosargam' },
        { n = 'Radio SBS', u = 'https://solid48.streamupsolutions.com/proxy/radiosbs/radiosbs' },
        { n = 'Radio Schizoid - Chillout Ambient', u = 'http://94.130.113.214:8000/chill' },
        { n = 'Radio Schizoid - Dub Techno', u = 'http://94.130.113.214:8000/dubtechno' },
        { n = 'Radio Schizoid - Progressive Psychedelic Trance', u = 'http://94.130.113.214:8000/prog' },
        { n = 'Radio Schizoid - Psychedelic Trance', u = 'http://94.130.113.214:8000/schizoid' },
        { n = 'Radio SD 908 FM', u = 'https://uk2.internet-radio.com/proxy/radiosdapp?mp=/stream' },
        { n = 'Radio Spice 1049 FM', u = 'https://stream.lava.net.au/au_wa_878fm_radiospice' },
        { n = 'Radio Sports Flashes', u = 'https://funasia.streamguys1.com/live13' },
        { n = 'Radio Suno 917 FM', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/SUNO917_SC' },
        { n = 'Radio Suno Malayalam 917', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SUNO917_SC' },
        { n = 'Radio Taj', u = 'http://s1.voscast.com:9484/;' },
        { n = 'Radio Tarana', u = 'http://stream.zeno.fm/t2rrw8uavp8uv' },
        { n = 'Radio Terna 904 FM', u = 'https://radio.garden/api/ara/content/listen/MzpZd2nQ/channel.mp3' },
        { n = 'Radio Thamil HD', u = 'https://live.cmr24.net/CMR/TamilHD-MQ/icecast.audio' },
        { n = 'Radio Tirur', u = 'https://sonic01.instainternet.com/8002/stream' },
        { n = 'Radio Udaan', u = 'https://stream.radioudaan.com/listen/radio_udaan/radio.mp3' },
        { n = 'Radio Voxa', u = 'https://stream.zeno.fm/zrfx7zy2wwzuv.aac' },
        { n = 'Radio Wow', u = 'https://stream.zeno.fm/d22wrdbst5quv' },
        { n = 'Radio Zindagi', u = 'https://us9.maindigitalstream.com/ssl/RadioZindagi' },
        { n = 'Radio-Beat-Thaalam', u = 'https://www.liveradio.es/http://live.exertion.in:8050/radio.mp3' },
        { n = 'Radio-Ilmussalaf', u = 'https://darhdth.radioca.st/stream' },
        { n = 'Radio-Jn', u = 'https://stream.zeno.fm/0wck59rarchvv' },
        { n = 'Radio-Mallu', u = 'https://usa15.fastcast4u.com/proxy/radiomall/stream' },
        { n = 'Radio-Mist-Ooty', u = 'https://stream.zeno.fm/81gn28sbna0uv' },
        { n = 'Radio-Paramakurichi', u = 'https://vpmurugun.radioca.st/autodj' },
        { n = 'Radio-Petti-5-1', u = 'https://radiopetti.out.airtime.pro/radiopetti_a' },
        { n = 'Radio-Rock-On', u = 'https://node-13.zeno.fm/tcr3q3qx908uv' },
        { n = 'Radio-Suno-Tamil', u = 'https://18803.live.streamtheworld.com/RADIO_SUNO_TAMIL_S01.mp3' },
        { n = 'Radio-Tamizha-Fm', u = 'https://ec5.yesstreaming.net:1065/stream' },
        { n = 'Radio90Fm', u = 'https://ice42.securenetsystems.net/CR90?type=.mp3' },
        { n = 'Radioaashiqanaa', u = 'https://sonic.onlineaudience.co.uk/8114/stream' },
        { n = 'Radioazad', u = 'https://edge.mixlr.com/channel/uaphi' },
        { n = 'Radiobaingan', u = 'https://stream.zeno.fm/eyxg23ky4x8uv' },
        { n = 'Radiobenziger', u = 'https://radio.radiobenziger.com/stream?type=http&nocache=1169' },
        { n = 'Radiobollyfm', u = 'http://stream.zeno.fm/zu59ykebs2zuv' },
        { n = 'Radiocityfreedom', u = 'https://stream.zeno.fm/d6f5w51zrf9uv' },
        { n = 'Radiocityhindi', u = 'https://stream.zeno.fm/pxc55r5uyc9uv' },
        { n = 'Radiocityhiphop', u = 'https://stream.zeno.fm/dgrgdv2zrf9uv' },
        { n = 'Radiocitykannada', u = 'https://stream.zeno.fm/waxzfy3zrf9uv' },
        { n = 'Radiocitykannadagold', u = 'https://stream.zeno.fm/59g0g83zrf9uv' },
        { n = 'Radiocitymalayalam', u = 'https://www.liveradio.es/http://69.162.124.24:8888/Malayalam' },
        { n = 'Radiodehotties', u = 'https://s6.myradiostream.com/15054/;' },
        { n = 'Radiofaza', u = 'https://radiocast.cr8tive-digital.com/radiofaza' },
        { n = 'Radiogirmit', u = 'https://stream.radiojar.com/g6dgm6m6p3hvv' },
        { n = 'Radiohaanji', u = 'http://stream.zeno.fm/unkxya7qf1duv.mp3' },
        { n = 'Radiokeralam', u = 'https://ice31.securenetsystems.net/RADIOKERAL' },
        { n = 'Radiolalsalam', u = 'https://stream.zeno.fm/f3nc8x3tywzuv' },
        { n = 'Radiomadurai', u = 'http://stream.zeno.fm/1ycmepnthkhvv' },
        { n = 'Radiomalayalam', u = 'https://radiomalayalamfm.com/radio/8000/radio.mp3' },
        { n = 'Radiomaria', u = 'https://dreamsiteradiocp2.com/proxy/rmindia1?mp=/stream' },
        { n = 'Radiomattoli', u = 'https://cast1.my-control-panel.com/proxy/radiomattoli/stream' },
        { n = 'Radiomediavillage', u = 'https://443-1.autopo.st/183/stream' },
        { n = 'Radiomythri', u = 'https://stream.zeno.fm/ekthuu9bfwzuv' },
        { n = 'Radionev 24X Hits Music Station', u = 'https://a7.asurahosting.com:8140/radio.mp3' },
        { n = 'Radioolive', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/OLIVE1063.mp3' },
        { n = 'Radioonattukara', u = 'https://stream.zeno.fm/fu94u25kqd0uv' },
        { n = 'Radiopalakkad', u = 'https://stream.zeno.fm/qgqrxfte41zuv' },
        { n = 'Radiopalamadom', u = 'http://stream.zeno.fm/fbbg2pbbmbruv' },
        { n = 'Radiopunjabitoday', u = 'http://stream.zeno.fm/019324w4ez4tv' },
        { n = 'Radiorang', u = 'https://stream.zeno.fm/n58tt09cqchvv' },
        { n = 'Radiosunokannada', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_SUNO_MELODY_S06.mp3' },
        { n = 'Radiotamilan', u = 'http://stream.zeno.fm/x7a1sy3svxhvv' },
        { n = 'Radiotarana', u = 'https://peridot.streamguys1.com:7150/Tarana.aac' },
        { n = 'Rafaradio', u = 'https://gains.reviveradio.net/proxy/rafaradio?mp=/stream' },
        { n = 'Rafi Hit Songs', u = 'https://stream-143.zeno.fm/0zkr7x8ztm0uv?zs=WTPQx8TiQXSo11XU0iyTAQ' },
        { n = 'Ragamradio', u = 'https://stream.zeno.fm/xwlwqmiogncvv' },
        { n = 'Rajini-Radio', u = 'https://stream.zeno.fm/aqp97f3z238uv' },
        { n = 'Rangeela Radio', u = 'https://rangeelaradio.radioca.st/;' },
        { n = 'Rangilo Gujarati', u = 'http://s9.voscast.com:7402/' },
        { n = 'Recastfm', u = 'https://usa8.fastcast4u.com/proxy/auralradio?mp=/1/;stream.mp3' },
        { n = 'Red FM 889', u = 'https://ice9.securenetsystems.net/CIRVFM' },
        { n = 'Retro Ma', u = 'https://stream-154.zeno.fm/b6augfmdanzuv' },
        { n = 'Retrobollywood', u = 'https://stream.zeno.fm/g372rxef798uv' },
        { n = 'Reviveradiomalayalam', u = 'https://gains.reviveradio.net/proxy/revivemalayalam?mp=/stream' },
        { n = 'Rocker Radio Geetmala', u = 'https://stream.zeno.fm/du9443htcfhvv' },
        { n = 'Roobam-Fm', u = 'https://s3.radio.co/sadfae7495/listen' },
        { n = 'Roq Raw Radio', u = 'https://mystation.micast.media/radio/8090/radio.mp3' },
        { n = 'Russia-Tamil-Radio', u = 'https://stream.zeno.fm/r2ff41404k8uv' },
        { n = 'Sabras Radio', u = 'https://radio.canstream.co.uk:8025/live.mp3' },
        { n = 'Sahara FM Tamil', u = 'https://azuracast.vibesounds.in:8000/radio.mp3' },
        { n = 'Sai-Dheepam-Fm', u = 'https://stream.zeno.fm/ut4syfwb1k8uv' },
        { n = 'Sakkath Radio', u = 'https://stream.zeno.fm/3e6k4ryerd0uv' },
        { n = 'Sakkath Radio Kannada', u = 'https://node-31.zeno.fm/fcsk9ryerd0uv?rj-ttl=5&rj-tok=AAABdXnVZ3sA-61zQpwDIgRWvw' },
        { n = 'Sandesh Radio', u = 'http://radio.garden/api/ara/content/listen/Myo7zNpV/channel.mp3?1667634784436' },
        { n = 'Sangeet 1061 FM', u = 'https://www.radiomast.io/stream/22e2c991-fc0c-4242-8cba-0a64d0aea809/listen?_=1' },
        { n = 'Sangeet Radio FM 951 AM 1460 Houston, TX, US', u = 'https://ice8.securenetsystems.net/SGTRADIO' },
        { n = 'Sangeet Samvaad', u = 'https://n08.radiojar.com/7mh06pa8uwzuv.mp3' },
        { n = 'Sangeethamee Jeevitham FM', u = 'http://stream.zeno.fm/7u8rbyz6568uv' },
        { n = 'Sangeetmalaradio', u = 'https://rs.suricloud.com/radio/8030/radio.mp3' },
        { n = 'Sargakshetra-89-6-Fm', u = 'https://edge.mixlr.com/channel/ugbfe' },
        { n = 'Sayajifm', u = 'https://sayajifm.radioca.st/stream' },
        { n = 'Sbspopdesi', u = 'http://sbs-ice.streamguys1.com/sbs-popdesi' },
        { n = 'Senthamil-Fm', u = 'https://stream.zeno.fm/5yf5swm7u7zuv' },
        { n = 'Shahul Radio', u = 'https://stream.zeno.fm/vwmp35nb038uv' },
        { n = 'Shaiva Lahari', u = 'https://samcloud.spacial.com/api/listen?sid=107886&rid=186750&f=mp3,any&br=128000,any&m=pls&t=ssl' },
        { n = 'Shalom Radio', u = 'http://stream.radio.co/s1383afdc9/listen' },
        { n = 'Shalombeatsradiotelugu', u = 'http://rd.shalombeatsradio.com:9190/stream' },
        { n = 'Shalomradio', u = 'https://stream.radio.co/s1383afdc9/listen?ver=828256' },
        { n = 'Shreyaghosal', u = 'https://drive.uber.radio/uber/bollywoodshreyaghosal/icecast.audio' },
        { n = 'Shripad Radio', u = 'https://shripadradio.radioca.st/;' },
        { n = 'Shuddh Desi Radio', u = 'https://streamer.radio.co/se30891e37/listen' },
        { n = 'Shyamradio', u = 'https://stream.zeno.fm/7dqtawdfmzzuv.aac' },
        { n = 'Sikhnet Radio', u = 'http://radio2.sikhnet.com:8010/stream' },
        { n = 'Sirpi-Fm', u = 'https://sirpifmhd-unicast2u.radioca.st/stream' },
        { n = 'Sitara FM', u = 'https://server6.radio-streams.net:18048/stream' },
        { n = 'Sivan-Radio', u = 'https://sivanradio.radioca.st/stream' },
        { n = 'Slbc-Tamil-National-Service', u = 'https://stream.zeno.fm/xekhrn4zetzuv' },
        { n = 'Songs P K Radio', u = 'http://107.182.234.197:7425/' },
        { n = 'Sooriyan FM', u = 'https://radio.lotustechnologieslk.net:8006/;stream.mp3' },
        { n = 'Spice FM', u = 'https://spice988fm.radioca.st/stream' },
        { n = 'Spooler POD Radio', u = 'https://cast5.asurahosting.com/proxy/spooler/stream' },
        { n = 'Sri Harmandir Sahib Live Kirtan', u = 'https://radio.sikhnet.com/proxy/channel9/live' },
        { n = 'Ssradionatham', u = 'https://spserver.sscast2u.in/ssradionatham/stream' },
        { n = 'Sstamilradio', u = 'https://stream.rcast.net/68750' },
        { n = 'Star Radio Malayalam', u = 'http://stream.zeno.fm/rqrhkw0dvp8uv' },
        { n = 'Sudarfm', u = 'https://stream.zeno.fm/r7a6hvh2yf8uv' },
        { n = 'Sun-Tamil-Radio', u = 'https://stream.zeno.fm/yavek61461zuv.aac' },
        { n = 'Suno Sharda - 908FM', u = 'https://streamasiacdn.atc-labs.com/shardaradio.aac' },
        { n = 'Sunrise Radio', u = 'https://stream1.themediasite.co.uk/8070/stream' },
        { n = 'Sunrisefm BRX01', u = 'http://stream.sunrisefm.nl:9600/stream' },
        { n = 'Suvidharadio', u = 'https://my.ssl-stream.com/Suvidha_Radio' },
        { n = 'Swaranjali', u = 'https://stream.zeno.fm/x7mve2vt01zuv' },
        { n = 'Swarnanjalidevotionalradio', u = 'https://stream.zeno.fm/zkqsxrd1h2zuv' },
        { n = 'Sweety FM', u = 'https://centova71.instainternet.com/proxy/sweetyfm?mp=/stream2' },
        { n = 'Swisstamilradio', u = 'https://usa19.fastcast4u.com/swiss' },
        { n = 'Taj 923 FM', u = 'https://ice66.securenetsystems.net/TAJ' },
        { n = 'Tamil Amuthu Radio', u = 'https://stream.zeno.fm/p88vvwd0gm0uv' },
        { n = 'Tamil Cholai Online Radio', u = 'https://radio.perthtamiltalkies.com.au/radio/8010/tamilcholai' },
        { n = 'Tamil Old Hits FM', u = 'https://a9oldhits-a9media.radioca.st/stream' },
        { n = 'Tamil Panpalai Gold', u = 'https://tamilpanpalai.radioca.st/ind' },
        { n = 'Tamil Sun FM', u = 'http://cp.usa2.fastcast4u.com:2199/tunein/tamilsun.pls' },
        { n = 'Tamil-2021-Latest-Hits', u = 'https://stream.zeno.fm/dkxftg6k7tzuv.aac' },
        { n = 'Tamil-Amuthu-Bakthi-Radio', u = 'https://stream.zeno.fm/bpc3ucypmm0uv' },
        { n = 'Tamil-Amuthu-Chennai-Radio', u = 'https://stream.zeno.fm/k9e5pmbktp8uv' },
        { n = 'Tamil-Amuthu-Covai-Radio', u = 'https://stream.zeno.fm/dzxv07vktp8uv' },
        { n = 'Tamil-Amuthu-Kovilpatti-Radio', u = 'https://stream.zeno.fm/4cmhxc3ktp8uv' },
        { n = 'Tamil-Amuthu-Madurai-Radio', u = 'https://stream-156.zeno.fm/utmhndkgtp8uv?zs=J185Dl-ASQW-m1uTNJ2mUg' },
        { n = 'Tamil-Amuthu-Mellisai-Radio', u = 'https://stream.zeno.fm/bfh4ywts2f8uv' },
        { n = 'Tamil-Amuthu-Sivakasi-Radio', u = 'https://stream.zeno.fm/nxggffwgtp8uv' },
        { n = 'Tamil-Amuthu-Trichy-Radio', u = 'https://stream.zeno.fm/feyrkb9htp8uv' },
        { n = 'Tamil-Latest-Hits-Radio', u = 'https://stream.zeno.fm/dkxftg6k7tzuv' },
        { n = 'Tamil-Panpalai-Oceania', u = 'https://tamilpanpalai.radioca.st/stream' },
        { n = 'Tamilaruvifm', u = 'https://servidor18-4.brlogic.com:7740/live' },
        { n = 'Tamilcomedyradio', u = 'https://stream.zeno.fm/tmgktm50dzzuv' },
        { n = 'Tamilkuyilradio', u = 'http://stream.zeno.fm/yp73agy93qzuv' },
        { n = 'Tamilosaifm', u = 'https://usa15.fastcast4u.com/proxy/tamilosaifm?mp=/1' },
        { n = 'Tamilragam', u = 'https://cast4.asurahosting.com/proxy/neville/stream' },
        { n = 'Telangana FM Siddipet', u = 'http://198.178.123.5:12682/;' },
        { n = 'Thaalam-Fm', u = 'https://ec4.yesstreaming.net:1990/stream' },
        { n = 'Thaalam-Radio', u = 'https://thaalam.out.airtime.pro/thaalam_b' },
        { n = 'Thamil-Thai-Fm', u = 'https://www.liveradio.es/http://radio.massstream.net:8010/stream' },
        { n = 'Thavakalai-Radio', u = 'https://mars.streamerr.co/8274/stream' },
        { n = 'Thayagam-Tamil-Radio', u = 'https://s3.yesstreaming.net:17045/stream' },
        { n = 'The Better FM', u = 'https://iceant.eclipse-streaming.co.za:8443/TWR-music.mp3' },
        { n = 'The-Leader-Fm', u = 'https://stream.zeno.fm/whwy245c2wzuv' },
        { n = 'Thean-Tamil-Osai', u = 'https://www.liveradio.es/http://192.95.39.65:5187/stream' },
        { n = 'Thenaruvi-Fm', u = 'https://thenaruvivaanoli.radioca.st/stream' },
        { n = 'Thendral-Fm-Radio', u = 'https://stream.zeno.fm/xzt706p3h2zuv' },
        { n = 'Thendral-Fm-Slbc', u = 'https://www.liveradio.es/http://220.247.227.20:8000/Threndralstream' },
        { n = 'Thenkasi-Fm-Radio', u = 'https://stream.zeno.fm/1wq6xebz6k0uv' },
        { n = 'Thentamilradio', u = 'https://usa9.fastcast4u.com/proxy/thentamilfm?mp=/;' },
        { n = 'Theophony Tamil Christian Radio', u = 'https://usa19.fastcast4u.com:5480//stream' },
        { n = 'Tick Tock Radio - 1992', u = 'https://streaming.ticktock.radio/tt/1992/icecast.audio' },
        { n = 'Tick Tock Radio - 1993', u = 'https://streaming.ticktock.radio/tt/1993/icecast.audio' },
        { n = 'Tick Tock Radio - 1994', u = 'https://streaming.ticktock.radio/tt/1994/icecast.audio' },
        { n = 'Tick Tock Radio - 2022', u = 'https://streaming.ticktock.radio/tt/2022/icecast.audio' },
        { n = 'Tinder Radio', u = 'https://streaming.exclusive.radio/er/bollywood/icecast.audio' },
        { n = 'Tori Live Radio', u = 'http://173.203.133.187:9700/;' },
        { n = 'Tori-Live-8000', u = 'http://173.203.133.187:9700/;stream/1' },
        { n = 'Translation Of The Quran In Kannada', u = 'https://server3.quraan.us:8034/' },
        { n = 'TRT Tamil Oli FM', u = 'https://radio13.pro-fhi.net:19236/stream.mp3' },
        { n = 'Tubetamilfm', u = 'http://stream.zeno.fm/p5k41f436qzuv' },
        { n = 'Tune India Radio', u = 'https://s2.radio.co/se5e166e2f/listen#.mp3' },
        { n = 'Tuneindiaradio', u = 'https://s2.radio.co/se5e166e2f/listen' },
        { n = 'Twr-India-Tamil', u = 'https://fm.radio882.com/radio/8010/tamil.mp3' },
        { n = 'Udit Narayan', u = 'https://stream.zeno.fm/ke8m4vr3ss8uv' },
        { n = 'Ujala Radio', u = 'https://stream.ujala.nl/ujala' },
        { n = 'Ujalaradio', u = 'https://server4.ujala.nl/stream/2/listen.mp3' },
        { n = 'Ullasam-Fm', u = 'https://eu10.fastcast4u.com:6740/stream' },
        { n = 'Unity101', u = 'https://ssl.canstream.co.uk:8701/live.mp3' },
        { n = 'Ustamilfm', u = 'https://streaming.radio.co/s0cfc93915/listen' },
        { n = 'Vaanambadi-Vaanoli', u = 'https://usa9.fastcast4u.com/proxy/vaanambadifm?mp=/1' },
        { n = 'Vadivelucomedyradio', u = 'https://stream.zeno.fm/02n962ezyp8uv' },
        { n = 'Vagai-Tamil-Fm', u = 'https://vtfm2020-vtfm.radioca.st/stream' },
        { n = 'Vaigai FM', u = 'https://cast1.my-control-panel.com/proxy/geethan3/stream' },
        { n = 'Vaigai-Fm', u = 'https://cast1.asurahosting.com/proxy/geethan3/stream' },
        { n = 'Vaikhari', u = 'http://stream.zeno.fm/p2ysncnc1rhvv' },
        { n = 'Vaikhari-Bh', u = 'http://stream.zeno.fm/emkyc4gx398uv' },
        { n = 'Vanavilfm - ARR Radio', u = 'https://s7.yesstreaming.net:8038/stream' },
        { n = 'Vanavilfm - Radio Maestro', u = 'https://s7.yesstreaming.net:8092/stream' },
        { n = 'Vaniradio', u = 'https://spserver.sscast2u.in/8166/stream' },
        { n = 'Vannam-Radio', u = 'https://usa13.fastcast4u.com/proxy/gtcfm?mp=/1' },
        { n = 'Vasantham-Fm', u = 'https://cp12.serverse.com/proxy/vasanthamfm?mp=/stream' },
        { n = 'Vdesi', u = 'https://stream.radio.co/s42e977b6c/listen' },
        { n = 'Vettri-Vaanoli', u = 'https://www.liveradio.es/http://s2.voscast.com:12136/;stream.mp3?1639674365578' },
        { n = 'Vijay FM', u = 'http://stream.zeno.fm/qnu9r38twchvv' },
        { n = 'Vijay-Radio', u = 'https://stream.zeno.fm/x8byqha4b48uv' },
        { n = 'VIJAYFM', u = 'https://vijayfm-prabak78.radioca.st/stream' },
        { n = 'Vivasayi-Radio', u = 'https://stream.zeno.fm/5mm4974xk2zuv' },
        { n = 'VSVP Tech FM', u = 'http://stream.zeno.fm/egprld1sdsvvv' },
        { n = 'West Indian Vibes Radio', u = 'https://s6.citrus3.com:8396/stream' },
        { n = 'Worldtoworldradio', u = 'https://streaming.radio.co/s4f2cc35de/listen' },
        { n = 'Yaazhisai-Fm', u = 'https://stream.zeno.fm/nxb2dpmmhm8uv' },
        { n = 'YQ Radio Qatar', u = 'https://stream.zeno.fm/1cfdt0n57p8uv' },
        { n = 'Yugamradio', u = 'https://s6.yesstreaming.net:19012/stream;' },
        { n = 'Підсунути Свиню', u = 'https://stream.zenolive.com/u5enyd4c28quv' },
        { n = 'اذاعة القرآن الكريم', u = 'http://stream.radiojar.com/0tpy1h0kxtzuv' },
        { n = 'தமிழ் வானொலி​ TAMIL Radio', u = 'http://stream.zeno.fm/ncw879a2h8quv' },
    }
}
