return {
    ['islamic_republic_of_iran'] = {
        { n = 'Caltexmusic', u = 'http://n13.radiojar.com/cp13r2cpn3quv?rj-ttl=5&rj-tok=AAABeB5OHJQA07FIiDdZAZNHWw' },
        { n = 'Coran Radio', u = 'https://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABhdgGORQA-2acfyF3_4WY2g' },
        { n = 'Enationfm', u = 'http://dal4.ir.enationfm.stream:8308/;' },
        { n = 'Faz', u = 'http://www.radiofaaz.com:8000/radiofaaz' },
        { n = 'Go', u = 'https://stream.zeno.fm/v5kxmagseg0uv' },
        { n = 'Hamsafar', u = 'http://stream.radiojar.com/pyea7q9h5ehvv.m3u' },
        { n = 'Iran International HTTPS Stream', u = 'https://stream.radiojar.com/iintl_c' },
        { n = 'Iran On Air', u = 'http://ice41.securenetsystems.net/KIRN' },
        { n = 'Parsa', u = 'http://parsa.icdndhcp.com:18000/stream' },
        { n = 'Radio Eram', u = 'http://37.59.47.192:8200/;stream.mp3' },
        { n = 'Radio Faaz', u = 'https://free.rcast.net/230792' },
        { n = 'Radio Farda', u = 'https://stream.radiojar.com/cp13r2cpn3quv' },
        { n = 'Radio Khatereh', u = 'https://servidor22-5.brlogic.com:7160/live?source=website' },
        { n = 'Radio Mojahed - رادیو مجاهد', u = 'https://s2.radio.co/s830691c74/listen' },
        { n = 'Radio Mojdeh', u = 'http://ic2326.c1261.fast-serv.com/rm128' },
        { n = 'Radio Navahang', u = 'https://navairan.com/;stream.nsv' },
        { n = 'Radio Negah Roshan', u = 'https://r.ngr1.ir/stream.ogg.m3u' },
        { n = 'Radio Persian', u = 'http://r.pgbu.ir:8000/live' },
        { n = 'Radio Sarcheshme', u = 'http://sarcheshmeh.icdndhcp.com:18452/stream' },
        { n = 'Radiosimorgh', u = 'https://stream.zeno.fm/jl8n7thgcdftv' },
        { n = 'Radiosimorgh Authentic Iranian Music', u = 'https://stream.zeno.fm/9svfnobkrxrvv' },
        { n = 'Radioyar', u = 'https://shoutcast.glwiz.com/RadioYAR.mp3' },
        { n = 'آونگ کلاپ', u = 'https://stream.zeno.fm/fpabqr8pd9zuv' },
        { n = 'القارئ محمد أيوب', u = 'https://qurango.net/radio/mohammed_ayyub' },
        { n = 'امبدد', u = 'http://auds1.intacs.com/adorationgospelfm' },
    }
}
