return {
    ['new_zealand'] = {
        { n = '100,3FM South Canterbury', u = 'http://uk4-vn.mixstream.net:8066/stream/1/' },
        { n = '2XS FM Palmerston North', u = 'http://125.236.204.178:8001/listen.mp3' },
        { n = '3ABN Australia Radio', u = 'https://stream.3abnaustralia.org.au:8443/stream' },
        { n = '531 Pi', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/531PIAAC_SC?dist=onlineradiobox' },
        { n = '8KNZ || Christchurch, NZ', u = 'http://radio8k.out.airtime.pro:8000/radio8k_a' },
        { n = '912 Oamaru FM', u = 'https://usa1-vn.mixstream.net/8096/listen.mp3' },
        { n = '95Bfm', u = 'https://streams.95bfm.com/stream128' },
        { n = 'Akaroa World Radio', u = 'https://n07.radiojar.com/k0t12bsns1duv?rj-ttl=5&rj-tok=AAABf7nGP10A7NK4A0_6v63i4w' },
        { n = 'Badradio 247 OG Phonk, Memphis, Houston, Trap Trill', u = 'https://s2.radio.co/s2b2b68744/listen' },
        { n = 'Bay FM 1007', u = 'https://s38.myradiostream.com:8876/;;?listening-from-radio-garden=1686796930' },
        { n = 'Beachfm 1063', u = 'http://s8.myradiostream.com:58408/' },
        { n = 'Big River FM', u = 'http://bigriver.broadcast.co.nz/bigriverfm.mp3' },
        { n = 'Brian FM 912 Wanganui NZ', u = 'https://ais-sa1.streamon.fm/7100_128k.aac' },
        { n = 'CFM Coromandel', u = 'https://stream.cfm.co.nz/low' },
        { n = 'Chill-Radio', u = 'https://media-sov.musicradio.com/Chill' },
        { n = 'Classic1027', u = 'http://edge.iono.fm/xice/49_high.aac' },
        { n = 'Compass FM', u = 'http://stream.compassfm.org.nz:8000/Compass_FM_104.9' },
        { n = 'Cool Blue Taupo', u = 'http://falcon.shoutca.st:8166/stream' },
        { n = 'Dave FM', u = 'http://davefmradio.no-ip.org:8000/stream' },
        { n = 'Drop FM', u = 'https://s2.radio.co/s7649837db/listen' },
        { n = 'East FM', u = 'http://listen.eastfm.nz/stream.mp3' },
        { n = 'Easy 80S', u = 'http://procyon.shoutca.st:8032/;' },
        { n = 'Gaia FM New Zealand', u = 'http://s2.stationplaylist.com:9000/gaiafm.aac' },
        { n = 'Galaxy 107 FM Kawerau', u = 'http://s39.myradiostream.com:14858/;listen.mp3' },
        { n = 'Gone Country', u = 'https://usa10.fastcast4u.com:6010/?type=http&nocache=1676417570' },
        { n = 'Heads FM Mangawhai 1064', u = 'https://headsfm.radioca.st/stream' },
        { n = 'Jakemusic', u = 'https://camera.jakebriggs.com/jakemusic' },
        { n = 'Jazzgrooveorg - Smooth Jazz 64K', u = 'http://streams.radiomast.io/4fdf004c-c2f3-49c1-bdb1-22e208d48780' },
        { n = 'KAOS Blenheim NZ', u = 'http://74.91.125.187:8068/stream' },
        { n = 'Kiwi Folk Radio', u = 'https://streamer.radio.co/sde527a41e/listen' },
        { n = 'KIX FM', u = 'https://stream.kixfm.co.nz:8178/stream' },
        { n = 'Libertynz On The Wireless', u = 'https://stream.zeno.fm/lamr6x1fxrruv.pls' },
        { n = 'Lifefm', u = 'http://rhema-radio.streamguys1.com/rhema-lifefm.mp3' },
        { n = 'MAD FM Auckland 1067', u = 'https://madfm-gecko.radioca.st/stream' },
        { n = 'Mai FM', u = 'https://ais-sa1.streamon.fm/7102_128k.aac' },
        { n = 'Metalradioconz', u = 'http://curiosity.shoutca.st:9073/stream' },
        { n = 'MIX FM Wellington', u = 'https://stream.mixfm.nz/' },
        { n = 'Mountainside FM', u = 'http://stream.nrgkits.co.nz:5000/mountainside' },
        { n = 'Mouthfull Radio', u = 'https://mouthfull-radio.radiocult.fm/stream' },
        { n = 'Mushroom Escape', u = 'https://cast3.my-control-panel.com/proxy/jonatha1/escape?1664781783632' },
        { n = 'Mushroom FM', u = 'https://www.mushroomfm.com/media/listen.pls' },
        { n = 'Niu FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/NIUFM.mp3?dist=onlineradiobox' },
        { n = 'Oamaru Heritage Radio', u = 'http://202.9.116.204:8000/ohrweb' },
        { n = 'One Christian Radio', u = 'https://radio.wanderingsheep.net:33001/onechristianradio' },
        { n = 'Paekakariki 882FM', u = 'https://icecast.groundtruth.co.nz/paekakfm.aac' },
        { n = 'Positively Morrinsville 877FM', u = 'https://c16.radioboss.fm:8262/stream?1652324863134' },
        { n = 'Power Hit FM 878 - Christchurch, NZ', u = 'http://listen.powerhitfm.co.nz:16100/stream' },
        { n = 'Radijohan', u = 'http://69.30.214.54:13740/?type=http&nocache=1708209708?0.5747864581171453' },
        { n = 'Radio - X', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SAM02AAC65_SC?dist=onlineradiobox' },
        { n = 'Radio Bay FM 1007', u = 'https://s38.myradiostream.com:8876/;;?listening-from-radio-garden=1686969300' },
        { n = 'Radio Control 994FM', u = 'https://michae14-gecko.radioca.st/stream' },
        { n = 'Radio Hydra', u = 'https://streaming.radio.co/sed9109681/listen' },
        { n = 'Radio One 91FM', u = 'https://play.r1.co.nz/live' },
        { n = 'Radio Robotic', u = 'https://stream.zeno.fm/rhscse2a41zuv' },
        { n = 'Radio Rock FM', u = 'http://www.radiorockfm.co.nz:8000/listenlive' },
        { n = 'Radio Samoa 1593Am', u = 'http://radiosamoa.stream.broadcast.co.nz:8000/rsamoa48k' },
        { n = 'Radio Spice Auckland, New Zealand', u = 'http://stream9.broadcast.co.nz:8000/radiospicewebsiteaudio.mp3' },
        { n = 'Radio Te Aroha 88FM', u = 'https://c2.radioboss.fm:18440/stream' },
        { n = 'Radio Woodville', u = 'http://219.88.73.120:88/broadwave.mp3' },
        { n = 'Radioactivefm 886', u = 'https://radio123-gecko.radioca.st/radioactivefm' },
        { n = 'Radiowave NZ', u = 'https://listen.radioking.com/radio/106324/stream/145267' },
        { n = 'RAG-FM 1077FM', u = 'https://cast6.asurahosting.com/proxy/ragfmcom/stream' },
        { n = 'RDU', u = 'https://rdu985fm-gecko.radioca.st/stream' },
        { n = 'RDU 985FM', u = 'https://rdu985fm-gecko.radioca.st/listen.pls?sid=1' },
        { n = 'Retro Hit Radio', u = 'https://riphel02.radioca.st/stream' },
        { n = 'Rhema', u = 'http://rhema-radio.streamguys1.com/rhema.mp3' },
        { n = 'RNZ - Radio New Zealand Classic', u = 'http://radionz-ice.streamguys.com/concert.mp3' },
        { n = 'RNZ - Radio New Zealand International', u = 'http://radionz-ice.streamguys.com/international.mp3' },
        { n = 'RNZ Concert AAC+', u = 'http://radionz-ice.streamguys.com/fallback-concert_aac128' },
        { n = 'RNZ Pacific 64Kbps', u = 'http://radionz-ice.streamguys.com/international_aac64' },
        { n = 'RNZ Parliament', u = 'http://radionz-ice.streamguys.com/parliament.mp3' },
        { n = 'Ski FM', u = 'https://s2.radio.co/s6436891bc/listen' },
        { n = 'Sleep Radio', u = 'https://cast4.asurahosting.com:2199/tunein/sleeprad.pls' },
        { n = 'Smash 107FM', u = 'https://s19.myradiostream.com/:18892/?type=http&nocache=1653124007?0.30724640509725076' },
        { n = 'Smooth 1056FM', u = 'https://servidor26.brlogic.com:7110/live' },
        { n = 'Sounds Vagrant Radio', u = 'https://admin.soundsvagrant.live/listen/sounds_vagrant/high.mp3' },
        { n = 'Sub FM', u = 'https://fmsub.radioca.st/stream?type=http&nocache=140' },
        { n = 'Switch FM Gisborne', u = 'http://s8.myradiostream.com:56886/listen.m4a' },
        { n = 'The Generator', u = 'https://s1.myradiostream.com/:14268/?type=http&nocache=1608640718?0.7458407789862892' },
        { n = 'The Generator FM', u = 'https://s1.myradiostream.com/14268/stream/1/' },
        { n = 'The Most FM 1044', u = 'http://gordon.mostfm.com:8000/high' },
        { n = 'The Rhythm 89FM', u = 'http://stream.zeno.fm/7v9aaqeqhs8uv' },
        { n = 'The Studio 881FM Dunedin', u = 'http://s23.myradiostream.com/:16100/listen.mp3' },
        { n = 'Tiri 2', u = 'https://servidor34-4.brlogic.com:7138/live?source=website' },
        { n = 'TLC Radio Northland', u = 'http://203.118.136.79:88/broadwave.mp3' },
        { n = 'True Light 878FM', u = 'http://stream.truelightfm.co.nz:8000/mp3' },
        { n = 'UP FM 1075', u = 'https://stream.upfm.live/radio/8000/radio.mp3' },
        { n = 'Wandering Sheep Radio - Christian Smooth Jazz', u = 'http://radio.wanderingsheep.tv:8021/christianjazz' },
        { n = 'Wandering Sheep Radio - Hope Alive', u = 'http://radio.wanderingsheep.tv:8012/hopealive' },
        { n = 'Wandering Sheep Radio - Jazz Cafe', u = 'http://radio.wanderingsheep.tv:8000/jazzcafe' },
        { n = 'WCR 876 FM', u = 'http://stream2.nrgkits.co.nz:5000/wcrfm' },
        { n = 'West FM Swing Radio', u = 'http://westfm.freeddns.org:8000/westfm' },
        { n = 'World FM Tawa 882', u = 'http://www.worldfm.co.nz:8882/worldfm.aac' },
        { n = 'Xs80S', u = 'http://s1.myradiostream.com:12508/listen.mp3' },
        { n = 'ZFM Global', u = 'http://nebula.shoutca.st:8545/stream/1/' },
    }
}
