return {
    ['paraguay'] = {
        { n = '100% Reggaeton Radio', u = 'https://stream-148.zeno.fm/qmhf2yd9dm0uv' },
        { n = '1140Am Central Radio', u = 'https://stream.zeno.fm/blkeeuikomhvv' },
        { n = '943 FM Del Este', u = 'http://radio.cdehosting.net:8040/;' },
        { n = 'CFA Radio', u = 'https://rds3.desdeparaguay.net:8002/cfa' },
        { n = 'Cuevas FM 917', u = 'https://radio.host.com.py:7020/;' },
        { n = 'Cáritas AM 680', u = 'http://200.1.201.244:8000/680AM' },
        { n = 'Educación FM 997', u = 'https://proxy01.servidorenlinea.net/cdehosting/8050/;' },
        { n = 'Estacion 105 1051 FM', u = 'http://radio.host.com.py:9460/;' },
        { n = 'Fabulosa FM 1045', u = 'https://radio.host.com.py:7034/;' },
        { n = 'Monumental 1080 AM', u = 'https://mdstrm.com/audio/62d81ca6a459e4082203c95b/icecast.audio' },
        { n = 'Radio Digital 885 Fm Paraguay', u = 'http://streaming.camaronhosting.com:8036/' },
        { n = 'RADIO EXITOS DE AYER', u = 'http://stream.zeno.fm/hvnh6d5uebruv' },
        { n = 'Radio Impacto 953', u = 'https://radio.host.com.py:7137/;' },
        { n = 'Radio Impacto 953 FM', u = 'http://radio.host.com.py:9714/stream' },
        { n = 'Radio Líder 1023 FM', u = 'http://stream.radiios.com:9066/;' },
        { n = 'RADIO MARIA PARAGUAY', u = 'http://dreamsiteradiocp.com:8090/stream' },
        { n = 'Radio OBEDIRA Online', u = 'https://s17.ssl-stream.com/proxy/obedira?mp=/live' },
        { n = 'Radio Universo 925 Fm', u = 'http://radio.cdehosting.net:8042/stream' },
        { n = 'RADIO VALLENATOS CLÁSICOS', u = 'http://stream.zeno.fm/z07vyxbqz8quv' },
        { n = 'Rockpop Paraguay', u = 'https://cp9.serverse.com/proxy/rockandpop/stream' },
        { n = 'Super Radio', u = 'https://c32.radioboss.fm:8139/stream' },
        { n = 'Tereré Mix Paraguay', u = 'https://stream.zeno.fm/a0z8gjrlucluv' },
    }
}
