return {
    ['peru'] = {
        { n = 'Aero Music', u = 'http://stream.zeno.fm/n652n9msaq8uv' },
        { n = 'Altamar Ilo', u = 'https://cloudstream2030.conectarhosting.com/9380/stream' },
        { n = 'Andina Radio', u = 'http://panel.innovatestream.pe:7058/;' },
        { n = 'Andina Radio 980 AM', u = 'http://167.114.118.120:7058/;' },
        { n = 'Antena Sur 903 FM', u = 'https://stream.zeno.fm/tu63bf6g31zuv' },
        { n = 'Asia La Extrema 1059 FM', u = 'http://167.114.118.120:7678/;' },
        { n = 'Asia La Radio', u = 'http://167.114.118.120:7804/;' },
        { n = 'Az Retro Peru', u = 'https://stream.zeno.fm/v7kvqunmwzzuv' },
        { n = 'Baladitas', u = 'http://stream.zeno.fm/hf2gsfm1mp8uv?1649692370879' },
        { n = 'Boleros Inolvidables Fmlima', u = 'https://stream.zeno.fm/5t45zksv7mruv' },
        { n = 'Carolina FM', u = 'https://turadio.accesopanel.com:7028/;' },
        { n = 'Chalaca', u = 'https://conectperu.com:7041/stream?icy=http' },
        { n = 'Chami Radio 1040 AM', u = 'https://centova.heplayer.com/proxy/stereon1/stream' },
        { n = 'CJ Rad', u = 'https://stream.zeno.fm/xvnzmkxzfrhtv' },
        { n = 'Conexion Kpop', u = 'https://centova.heplayer.com/proxy/conexion/stream' },
        { n = 'Conga Blue', u = 'https://radio.plhradio.com/8014/stream' },
        { n = 'Corporación Radial EL - Ocalli, Luya', u = 'https://stream.zeno.fm/ve5kqm6deq3vv' },
        { n = 'Cuba Mania', u = 'https://radio.plhradio.com/8004/stream' },
        { n = 'De Amor Y Salsa', u = 'https://radio.plhradio.com/8008/stream' },
        { n = 'Digital Play FM', u = 'https://dpfmadmin.radioca.st/stream' },
        { n = 'Doble Nueve - Classic', u = 'http://149.56.241.147:8008/stream?icy=http' },
        { n = 'Doble Nueve - Heritage', u = 'http://149.56.241.147:8006/stream?icy=http' },
        { n = 'Doble Nueve - Live', u = 'http://149.56.241.147:8002/stream?icy=http' },
        { n = 'Doble Nueve - Millenial', u = 'http://149.56.241.147:8004/stream' },
        { n = 'El Sembrador Radio 590 AM Y 1001 FM', u = 'https://panel.streamenviron.com:8158/stream.mp3' },
        { n = 'Electro Radio Live', u = 'https://stream-142.zeno.fm/93kksqvkeg8uv?zs=N9EUqjz8RdOQAaV215SUFg' },
        { n = 'Estacion 90S', u = 'https://radio.livestreamingmundial.com:7041/stream' },
        { n = 'Estación Alpamayo', u = 'https://eu47-sonic.instainternet.com/8096/stream' },
        { n = 'Estación Solar 1033 FM', u = 'http://167.114.118.119:7330/;' },
        { n = 'Estudio J 973 FM', u = 'https://stream.zeno.fm/qusmdw24a48uv' },
        { n = 'Exa FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac' },
        { n = 'Fama Sur Tarata', u = 'https://sp.oyotunstream.com/9326/stream' },
        { n = 'Fidelísima Radio 1077 FM', u = 'https://st3.inkaniserver.net:8008/stream' },
        { n = 'Filarmonía', u = 'https://c22.radioboss.fm:8100/stream' },
        { n = 'Filarmonía OCR-4V, 1027 Mhz FM, Lima IRTP', u = 'https://c22.radioboss.fm:18100/live' },
        { n = 'Flow Cristiano', u = 'https://mediastreamm.com:8054/stream?icy=http' },
        { n = 'Fmlima', u = 'https://stream.zeno.fm/qotg58sxvehvv' },
        { n = 'FRECUENCIA 1330 AM Parque Azangaro Miraflores LUIS ANGEL ANCON PATIÑO', u = 'https://turadio.accesopanel.com/8360/stream' },
        { n = 'Gen X', u = 'https://turadio.accesopanel.com/8526/stream' },
        { n = 'Generacion Kpop', u = 'http://stream9.mexiserver.com:8242/stream' },
        { n = 'Hisparockas', u = 'https://stream.zeno.fm/nhu7v3guz08uv' },
        { n = 'Jazzcontempo', u = 'https://cast4.asurahosting.com/proxy/fernand4/stream' },
        { n = 'JVM La Estación', u = 'https://stream.laut.fm/jvmlaestacion' },
        { n = 'Ke Brava', u = 'https://stream.zenolive.com/59947b1wfuquv' },
        { n = 'La Incontrastable Radio', u = 'https://stream.zeno.fm/vkhw2yc0mfhvv' },
        { n = 'La Jefa Perú', u = 'http://167.114.118.119:7320/' },
        { n = 'La Mejor Música Del Mundo', u = 'https://stream.zeno.fm/n54r7dsxs98uv' },
        { n = 'La Noventera', u = 'https://host.gometri.com/proxy/lanoventera/stream/' },
        { n = 'La Radio De Cushta Galiano', u = 'http://stream.zeno.fm/z27q1ywrt98uv' },
        { n = 'La Salsa Maestra', u = 'https://stream.zeno.fm/c1skkw28pfeuv' },
        { n = 'La Sonera Radio', u = 'https://tupanel.info:8300/listen.pls?sid=1' },
        { n = 'La Ñ Fmlima', u = 'https://stream.zeno.fm/tk4wmqvnnnruv' },
        { n = 'Levelhits', u = 'https://radio.pjcks.com/7234/stream' },
        { n = 'Mambo INN Radio', u = 'https://radio.perustream.com:7000/stream' },
        { n = 'Mega StR Peru', u = 'http://stream.zeno.fm/m0gb9v7aqs8uv' },
        { n = 'Melodia Arequipa', u = 'http://stream.radiomelodia.com.pe:8000/radio.mp3' },
        { n = 'MGR Radio Mara Gamero Dj Ethamx', u = 'https://stream-154.zeno.fm/fdhacwakavkuv' },
        { n = 'MI Radio Percy Altamirano Dj Ethamx', u = 'https://stream-170.zeno.fm/g9afqk829ibtv' },
        { n = 'Moderna Radio Papá', u = 'https://radio.transmite.pe/8020/stream/;type=mp3' },
        { n = 'Nueva Q', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRP_NQAAC.aac?csegid=1010&dist=1010&_=767257' },
        { n = 'Nuevaolera', u = 'https://stream.zeno.fm/4q99spjike0uv' },
        { n = 'Onda Cero Te Activa', u = 'https://mdstrm.com/audio/6598b65ab398c90871aff8cc/icecast.audio' },
        { n = 'Onda Popular', u = 'https://dattavolt.com/8278/stream?1634322652441' },
        { n = 'Orbita Radio Dance', u = 'http://topradio.pro:8090/autodj' },
        { n = 'Panamericana Latino Refrescante', u = 'https://mdstrm.com/audio/6598b76c6c07d80644b7321f/icecast.audio' },
        { n = 'Panamericana Retro Rock', u = 'https://mdstrm.com/audio/6598b728d982060896866b8a/icecast.audio' },
        { n = 'Panamericana Salsa Power', u = 'https://mdstrm.com/audio/6598b751261d9e088a6deadd/icecast.audio' },
        { n = 'PBO Radio', u = 'http://n06.radiojar.com/2fse67zuv8hvv?1669054401&rj-tok=AAABhJtuNOUAIi7Le3h5PA-2VA&rj-ttl=5' },
        { n = 'Peru Folk Radio', u = 'https://raymistream.net/listen/perufolkradio/live' },
        { n = 'Peruana Radio', u = 'https://cloudstream2036.conectarhosting.com/8352/stream' },
        { n = 'Radio - Congreso Del Perú', u = 'https://vivo.miradio.in/8048/stream' },
        { n = 'Radio 1160 Peru', u = 'https://us-b4-p-e-pb13-audio.cdn.mdstrm.com/live-audio-aw/6598b6e1261d9e088a6de859?aid=658ddcc0b2c7835d48fee06d&pid=G3FnIvg2s2uxHg1lIbLUlWa3cFT5KPBg&sid=XAAefdCCMC9B9MvNg9TwqdstYTKnk3li&uid=Nkdb2uczAeFQEIGw1fojci2BEYfd4Tye&es=us-b4-p-e-pb13-audio.cdn.mdstrm.com&ote=1711464716330&ot=YgiDR9HDtOJKN3UCFo0-xg&proto=https&pz=us&cP=128000&awCollectionId=658ddcc0b2c7835d48fee06d&liveId=6598b6e1261d9e088a6de859' },
        { n = 'Radio A 949', u = 'https://stream.zeno.fm/qxsaiqu7pn4tv' },
        { n = 'Radio Aire', u = 'https://stream-150.zeno.fm/2a2qb8z1a5zuv?zs=KCNxf0MEQ1aTZiARpyhokg' },
        { n = 'Radio Alegria - La Rompe', u = 'https://radio.sistemasandinos.org:10974/;stream' },
        { n = 'Radio Altamar', u = 'http://cloudstream2030.conectarhosting.com:9380/stream/' },
        { n = 'Radio Altura Pasco, Macusani 1009 Fm', u = 'http://167.114.118.120:7816/' },
        { n = 'Radio Amo La Música', u = 'http://stream.zeno.fm/aqmct15qmchvv' },
        { n = 'Radio Andina Tarata', u = 'http://sp.oyotunstream.com:8064/listen.pls' },
        { n = 'Radio Antena 5 Cusco 1600 AM Más Que Una Radio', u = 'https://stream.zeno.fm/pkvdsllgubgtv' },
        { n = 'Radio Armonía', u = 'https://radio.sistemasandinos.org:10978/;' },
        { n = 'Radio Arumarka 1073 Fm Puno', u = 'https://radios.sonidoshd.com/8038/;' },
        { n = 'Radio Bahía 1031 FM - Pisco', u = 'http://167.114.118.119:7494/;' },
        { n = 'Radio Baladitas', u = 'https://stream.zeno.fm/hf2gsfm1mp8uv' },
        { n = 'Radio Buenaza Digital', u = 'https://turadio.accesopanel.com/8486/stream' },
        { n = 'Radio Caramelo', u = 'https://panelautodj.innovatestream.pe:10857/stream' },
        { n = 'Radio Casma', u = 'https://radio.livestreamingmundial.com:7110/stream' },
        { n = 'Radio Chalaca Callao', u = 'https://conectperu.com/8084/stream' },
        { n = 'Radio Chocolate Rock Pop', u = 'https://stream.zeno.fm/g2w7ukzh64zuv' },
        { n = 'Radio Ciberplus', u = 'https://stream.zeno.fm/rn84grzfr2zuv/;' },
        { n = 'Radio Clasica Rockpop', u = 'https://sonicpanel.globalstream.pro/8042/stream' },
        { n = 'Radio Concierto - FM 951', u = 'https://conectperu.com/8012/stream' },
        { n = 'Radio Condor Pasa', u = 'https://sonic.globalstream.pro/8056/stream' },
        { n = 'Radio Conoden', u = 'http://stream.zeno.fm/wxpchhfw44zuv' },
        { n = 'RADIO CORAL 975 FM', u = 'https://maximacenterdata.com/8052/stream' },
        { n = 'Radio Corazón 943 FM Lima', u = 'https://mdstrm.com/audio/5fada514fc16c006bd63370f/icecast.audio' },
        { n = 'Radio Cumbia Mix', u = 'https://mdstrm.com/audio/6598b6ab95a235085823b24f/icecast.audio' },
        { n = 'Radio Cumbia OAQ-9H, 1071 Mhz FM, Chachapoyas, Amazonas', u = 'http://167.114.118.120:7698/;' },
        { n = 'Radio Cumbre', u = 'https://stream.zeno.fm/t8b5cmybtd0uv' },
        { n = 'Radio Cutivalú', u = 'https://7.innovatestream.pe:2020/stream/radiocutivalu/stream' },
        { n = 'Radio Deep Music', u = 'https://mpc1.mediacp.eu:8092/stream' },
        { n = 'Radio Del Amor', u = 'https://stream.zeno.fm/z7re4u64gd0uv' },
        { n = 'Radio Diamante', u = 'https://stream.zeno.fm/8s6b3v091k8uv' },
        { n = 'Radio Ebenezer', u = 'https://strm.dal.s02.oneofthebest.org/listen/8090_radio_ebenezer/radio.mp3' },
        { n = 'Radio Ebenezer Perú', u = 'https://stream.zeno.fm/43k7fdktv38uv' },
        { n = 'Radio Ecuajey', u = 'https://radio.plhradio.com/8002/stream' },
        { n = 'Radio Estacion Techno', u = 'http://stream.zeno.fm/t3sqkau72rhvv' },
        { n = 'Radio Estrella Trujillo 1027 Trujillo', u = 'https://radio.datahost.pe/9660/stream' },
        { n = 'RADIO EXITOSA 955 FM', u = 'https://exitosa.cusac.online/79525baf-b0f5-4013-a8bd-3c5c293c6561' },
        { n = 'Radio Fantasía Iquitos 883', u = 'https://sp.oyotunstream.com:10943/stream?icy=http' },
        { n = 'Radio Felicidad 889', u = 'https://mdstrm.com/audio/5fad731fcf097a068af3c8f7/icecast.audio' },
        { n = 'Radio Fiesta 98', u = 'http://s9.voscast.com:8496/;' },
        { n = 'Radio Frecuencia 100 - Trujillo', u = 'http://oyotunstream.com:7066/;' },
        { n = 'Radio Full Perú', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.119:7566/stream' },
        { n = 'Radio Funky Hits', u = 'https://stream-163.zeno.fm/57h4vyd5pf9uv' },
        { n = 'Radio Girasol', u = 'https://miradioperu.com/8008/stream' },
        { n = 'Radio Huancayo', u = 'https://cloud9.ldwebstudios.net:7000/;' },
        { n = 'Radio Huancayo Cumbia', u = 'https://stream.zeno.fm/ghubws78ipxuv' },
        { n = 'Radio Inkafuego En Vivo', u = 'https://radiohd.us/8022/stream' },
        { n = 'Radio JHC 1077 FM', u = 'https://sp.oyotunstream.com:10979/;' },
        { n = 'Radio Karicia', u = 'https://shoutcast.tmcreativos.com/proxy/radiokar?mp=/stream' },
        { n = 'RADIO KISS FM', u = 'https://maximacenterdata.com/8058/stream' },
        { n = 'Radio La Cheverísima - Utcubamba', u = 'https://sp.onliveperu.com/8114/stream/;' },
        { n = 'Radio La Fuerte', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.119:7322/stream' },
        { n = 'Radio La Gloria Es De Dios', u = 'https://radio101.mjwebexperts.com/8006/stream' },
        { n = 'Radio La Inolvidable OBT-4C, 937 Mhz FM, Lima', u = 'http://provisioning.streamtheworld.com/pls/CRP_LI.pls' },
        { n = 'RADIO LA MEGA 967 FM PERU', u = 'https://us-b4-p-e-pb13-audio.cdn.mdstrm.com/live-audio-aw/5fada56fe4e09508207a7951?' },
        { n = 'Radio La Nueva', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.120:7248/stream' },
        { n = 'Radio La Poderosa', u = 'https://turadio.accesopanel.com/8204/stream' },
        { n = 'Radio La Poderosa 982 FM Lima Perú', u = 'http://stream.zeno.fm/8dppgdapxneuv' },
        { n = 'Radio La Unika', u = 'https://cloud9.ldwebstudios.net:7011/;' },
        { n = 'Radio La Vaca', u = 'https://radio.streamingnacional.online/8168/stream' },
        { n = 'Radio La Voz Del Nor Oriente - Utcubamba', u = 'https://sp.onliveperu.com:7038/;' },
        { n = 'RADIO LA VOZ DEL PUEBLO SAN ISIDRO', u = 'https://servermax2.azuracast.com.es/listen/lavozdelpueblo/sanisidro' },
        { n = 'Radio La Zona 905 FM, Lima', u = 'https://mdstrm.com/audio/5fada54116646e098d97e6a5/icecast.audio' },
        { n = 'Radio Latidos 947 FM Huaral', u = 'https://radio.pjcks.com/9944/stream' },
        { n = 'Radio Loreto', u = 'https://sp.oyotunstream.com/8006/stream' },
        { n = 'Radio Los Angeles - Chepen', u = 'http://94.23.159.187:9950/;' },
        { n = 'RADIO MAGICA 883 FM PERU', u = 'https://25093.live.streamtheworld.com/MAG_SC?' },
        { n = 'Radio Marañon 961 FM', u = 'http://167.114.118.120:7112/;' },
        { n = 'Radio Maria Peru OAX-4M, 580 Khz AM OBT-4Z 977 Mhz FM, Lima', u = 'http://dreamsiteradiocp4.com:8020/' },
        { n = 'Radio Matucana 1029 FM, Lima', u = 'http://radio.transmite.pe:9316/;' },
        { n = 'RADIO MAXIMA DEL PERU Fono+51-925691328 PEDREGAL - MAJES', u = 'https://servermax2.azuracast.com.es/listen/maximafm/radio.mp3' },
        { n = 'RADIO MAXIMA DEL PERU Fono+51-925691328 SAN ISIDRO', u = 'https://servermax2.azuracast.com.es/listen/maximafm/sanisidro' },
        { n = 'RADIO MAXIMA DEL PERU ICA SISTEMA DRM SEÑAL MUNDIAL', u = 'https://servermax2.azuracast.com.es/listen/maximafm/ica' },
        { n = 'RADIO MEGA MIX 967 FM Perú', u = 'https://mdstrm.com/audio/5fada56fe4e09508207a7951/icecast.audio' },
        { n = 'RADIO MEGATRON MIX', u = 'https://maximacenterdata.com/8084/megatronmix' },
        { n = 'RADIO METROPOLITANA SEÑAL DIGITAL- LUIS ALBERTO TEJADA TORANZO', u = 'https://radios.sonidoshd.com/8082/stream' },
        { n = 'Radio Milenium - Bagua Grande', u = 'https://sp.onliveperu.com/8102/stream' },
        { n = 'Radio Miraflores TV', u = 'https://eu47-sonic.instainternet.com/8016/;' },
        { n = 'RADIO MIX 1035', u = 'http://stream.zeno.fm/ug8papw4nbruv' },
        { n = 'RADIO MODA 973 FM PERU', u = 'https://25063.live.streamtheworld.com/CRP_MOD_SC?' },
        { n = 'Radio Moda FM 973', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRP_MODAAC.aac' },
        { n = 'RADIO MUNICIPAL MONZÓN', u = 'http://stream.zeno.fm/bqwzcuy64qzuv' },
        { n = 'Radio Mágica 883 FM OCX-4G, Lima, Perú', u = 'http://playerservices.streamtheworld.com/pls/MAG_AAC.pls' },
        { n = 'Radio Nacional Peru - La Primera', u = 'https://rponline.presidencia.gob.bo/stream' },
        { n = 'Radio Nova', u = 'https://panel.innovatestream.pe:10989/stream' },
        { n = 'RADIO NOVA CHIMBOTE', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.120:7166/stream' },
        { n = 'Radio Nova Peru', u = 'https://panel.innovatestream.pe:10990/undefined' },
        { n = 'Radio Nova Trujillo', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.120:7168/stream' },
        { n = 'Radio Nueva Q OCZ-4P, 1071 Mhz, Lima', u = 'http://playerservices.streamtheworld.com/pls/CRP_NQ.pls' },
        { n = 'Radio Nueve Mix', u = 'http://stream.zeno.fm/tekhthm0pf9uv' },
        { n = 'RADIO OASIS 931 FM', u = 'https://maximacenterdata.com/8132/stream' },
        { n = 'Radio Ocalli - Luya', u = 'https://stream.zeno.fm/rn6uzquuqv8uv' },
        { n = 'Radio Ondas Del Huallaga', u = 'https://cloud9.ldwebstudios.net:7005/;' },
        { n = 'Radio Panamericana', u = 'https://mdstrm.com/audio/6598b62dded1380470f4e539/icecast.audio' },
        { n = 'Radio Paz 1120 AM', u = 'https://serverssl.innovatestream.pe:8080/http://167.114.118.119:7112/;' },
        { n = 'RADIO PERFECCION FM', u = 'https://maximacenterdata.com/8092/stream' },
        { n = 'Radio Pirata Mix - Cajabamba', u = 'http://167.114.118.120:7628/;' },
        { n = 'Radio Planeta 1077', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRP_PLAAAC.aac?csegid=1010&dist=1010&_=928052' },
        { n = 'Radio Planeta OCZ-4L, 1077 Mhz FM, Lima', u = 'http://playerservices.streamtheworld.com/pls/CRP_PLA.pls' },
        { n = 'RADIO PLATINUM 1029 FM', u = 'http://stream.zeno.fm/59sn98mhanruv.pls' },
        { n = 'Radio Positiva Tacna', u = 'http://sp.oyotunstream.com:8034/' },
        { n = 'Radio Reggae Cusco', u = 'https://stream.zeno.fm/xbp613h3e8zuv' },
        { n = 'Radio Ritmo Romántica', u = 'http://playerservices.streamtheworld.com/pls/CRP_RIT.pls' },
        { n = 'Radio Rock Hits', u = 'https://live.radiorockhits.online/listen/radiorockhits/radio.mp3' },
        { n = 'Radio Románticas Inolvidables Fmlima', u = 'https://stream.zeno.fm/6m1ba7yt3vduv' },
        { n = 'Radio RPP Mundial', u = 'https://us-b4-p-e-cg11-audio.cdn.mdstrm.com/live-audio-aw/5faee885eb830d06cf22ed4a' },
        { n = 'RADIO RUMBA HUANUCO', u = 'https://stream-176.zeno.fm/06cude657zhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIwNmN1ZGU2NTd6aHZ2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InhpV2FhSXNSU2NpRTF4VlItNmhQZkEiLCJpYXQiOjE3MTYzOTE5NTIsImV4cCI6MTcxNjM5MjAxMn0.f4Pl9cAClLSGCGrevzbILBXaI_jS0fm17vjS-di1DIk' },
        { n = 'Radio Sabrosa Sullana', u = 'https://stream.zeno.fm/zc1h9dv6pa0uv' },
        { n = 'Radio Salsa Calle Latina', u = 'https://stream-160.zeno.fm/erhrz6fdbnruv' },
        { n = 'Radio Salsa Peru', u = 'https://stream.zeno.fm/f19941g3teruv' },
        { n = 'Radio San Martín', u = 'https://conectperu.com:7020/stream?icy=http' },
        { n = 'Radio Santa Catalina', u = 'http://stream.zeno.fm/5zkxx7zp5gruv/;' },
        { n = 'Radio Satélite 1007 FM, Callao', u = 'https://conectperu.com/8166/stream' },
        { n = 'Radio Shack Music', u = 'https://c30.radioboss.fm:18415/stream' },
        { n = 'RADIO SINPATRONES FM SEÑAL DIGITAL DIRECCION JUAN JOSE PALLE', u = 'https://radios.sonidoshd.com/8342/stream' },
        { n = 'Radio Sol De Los Andes', u = 'https://cloudstream2036.conectarhosting.com/8036/stream' },
        { n = 'Radio Sonrisa-Chachapoyas', u = 'https://radios.sonidoshd.com/8110/stream' },
        { n = 'Radio Sotelo Ancash, Llamellín 1013 Fm', u = 'https://stream.zenolive.com/unde9yxcyzzuv' },
        { n = 'Radio Stereo 99 - Bagua Grande', u = 'https://sechin.grupocentroserver.com/radio/8300/radio.mp3' },
        { n = 'Radio Stereo G La Grande - Rodriguez De Mendoza', u = 'https://dattavolt.com/8138/stream' },
        { n = 'Radio Stereo Mix Ferreñafe', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.119:7280/stream' },
        { n = 'Radio Stereo TV', u = 'https://sp.onliveperu.com/8098/stream' },
        { n = 'Radio Studio 97', u = 'https://sechin.grupocentroserver.com/radio/8140/radio.mp3' },
        { n = 'Radio Super A1', u = 'http://radio.transmite.pe:9308/stream?icy=http' },
        { n = 'Radio Synthpop', u = 'https://radio.blueditor.com/8250/stream;' },
        { n = 'RADIO TRINIDAD 1070 AM', u = 'https://maximacenterdata.com/8056/stream' },
        { n = 'Radio Tropicana Paita', u = 'http://167.114.118.120:6010/listen.pls?sid=1' },
        { n = 'Radio Turbo Mix Cajamarca 710 Am', u = 'http://167.114.118.120:7626/stream' },
        { n = 'Radio Turbo Mix Cajamarca 925 Fm', u = 'http://167.114.118.120:7624/stream' },
        { n = 'Radio TV Ilucán', u = 'http://167.114.118.120:7820/;stream' },
        { n = 'Radio Un Hueco En El Espacio', u = 'https://cloudstream2032.conectarhosting.com/8106/stream' },
        { n = 'RADIO UNICAR', u = 'https://maximacenterdata.com/8086/stream' },
        { n = 'Radio UPN', u = 'https://serverssl.innovatestream.pe:8080/167.114.118.119:7216/stream' },
        { n = 'Radio Victor Music Perú', u = 'https://stream-149.zeno.fm/wymz9unt88quv?zs=j57_3aS2T--Zd_IslHw07A' },
        { n = 'Radio Victoria FM - Chachapoyas', u = 'https://serverssl.innovatestream.pe:8080/http://167.114.118.119:7068/stream/1/' },
        { n = 'Radio Vinilo Perú - Lima', u = 'http://167.114.118.120:7246/;' },
        { n = 'Radio Wari', u = 'https://radio.transmite.pe/9306/stream' },
        { n = 'Radio Xtrema - Chachapoyas', u = 'https://stream.zeno.fm/ktk1db7xywzuv' },
        { n = 'Radio Zona 5 933 - Chiclayo', u = 'http://167.114.118.120:7216/;' },
        { n = 'Radio Zona Privada Tacna 967', u = 'https://stream-42.zeno.fm/mmdbr61v1qruv' },
        { n = 'Radio90Schimbote', u = 'https://stream-162.zeno.fm/04fmqb2xwd0uv?zs=U7C6x5MaR56uI35rU7KJjA' },
        { n = 'RADIOMAR', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRP_MARAAC.aac?csegid=1010&dist=1010&_=737686' },
        { n = 'Radiomar Plus 1063 Lima', u = 'http://playerservices.streamtheworld.com/m3u/CRP_MARAAC.m3u' },
        { n = 'Radiomix AQP Dj Ethamx', u = 'https://stream-174.zeno.fm/qa5aurigvoivv' },
        { n = 'Radiomix AQP Rock-Pop En Español Dj Ethamx', u = 'https://stream-150.zeno.fm/mwxnk1y5btvvv' },
        { n = 'Radionuevaq', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CRP_NQAAC.aac?csegid=1010&dist=1010&_=558458' },
        { n = 'Radiorockpe', u = 'https://turadio.accesopanel.com:7031/stream' },
        { n = 'Radiotv Qorisonqo', u = 'https://stream.zeno.fm/ar6g4002a5zuv' },
        { n = 'Radiotv-Espiritu Santo A Las Naciones', u = 'http://stream.zeno.fm/3khgtfrpktzuv' },
        { n = 'RAM Cusco', u = 'http://stream.laut.fm/ramcusco' },
        { n = 'RCS Lima Stereo', u = 'http://stream.zeno.fm/scy8h669dchvv' },
        { n = 'Rock And Pop Classics', u = 'https://stream.zeno.fm/kusrlthtbhltv' },
        { n = 'Rockpop', u = 'http://stream.zeno.fm/0k6va3rg8rhvv' },
        { n = 'RPP Mundial Check 25112022', u = 'https://us-b4-p-e-qg12-audio.cdn.mdstrm.com/live-audio-aw/5faee885eb830d06cf22ed4a' },
        { n = 'RRI', u = 'https://dattavolt.com/8164/stream' },
        { n = 'Salkantay', u = 'https://serverssl.innovatestream.pe:8080/http://167.114.118.119:7662/' },
        { n = 'Señal Pitara Radio', u = 'http://conectperu.com:8082/stream' },
        { n = 'Sikodark', u = 'https://stream.zeno.fm/3ungez6rvy8uv' },
        { n = 'Smooth Jazz Instrumental', u = 'https://stream-155.zeno.fm/00rt0rdm7k8uv' },
        { n = 'Sol Frecuencia Primera Radio', u = 'https://cast6.asurahosting.com/proxy/solfrecu/stream' },
        { n = 'Sonorama Radio', u = 'https://eu47-sonic.instainternet.com:7059/' },
        { n = 'Stereo Andina', u = 'http://stream.zeno.fm/92et355merruv' },
        { n = 'Stereolima', u = 'https://panel.innovatestream.pe/8042/stream' },
        { n = 'Studio 92 925 FM Lima', u = 'https://mdstrm.com/audio/5fada553978fe1080e3ac5ea/icecast.audio' },
        { n = 'Studio Mix - Progreso, Amazonas En Vivo', u = 'https://stream.zenolive.com/de2yzp59mg0uv' },
        { n = 'Top Latino', u = 'http://online.radiodifusion.net:8020/stream' },
        { n = 'Tropical-Tarapoto', u = 'https://shoutcast.tmcreativos.com/proxy/radiotropical?mp=/stream' },
        { n = 'Vinilos', u = 'https://radio.plhradio.com/8006/stream' },
        { n = 'Vital FM', u = 'https://cast.vox.live7.la:8501/stream' },
        { n = 'Viva FM Smart', u = 'https://tupanel.info:8780/stream' },
        { n = 'Z Rock Pop', u = 'https://radioz.egostreaming.pe/radio/3e4f6a1b2c3d4e567890abcd/' },
        { n = 'Zona Musical Esterio * Perú', u = 'http://stream.zeno.fm/83eddkwsa78uv' },
        { n = 'Zona Radio Activa Chimbote', u = 'https://serverssl.innovatestream.pe:8080/http://184.154.28.210:9940/stream?icy=http' },
        { n = 'ZOOM FM', u = 'http://stream.zeno.fm/bccsy18t25quv.m3u' },
    }
}
