return {
    ['saudi_arabia'] = {
        { n = '---تراتيل قصيرة متميزة---', u = 'https://qurango.net/radio/tarateel' },
        { n = '905 Heart FM', u = 'https://radio.905heartfm.com:8000/radio.mp3' },
        { n = 'A F R O 505 By MX2', u = 'https://stream.zeno.fm/7wozjkc8x0vvv' },
        { n = 'Alifalif FM', u = 'https://alifalifjobs.com/radio/8000/AlifAlifLive.mp3' },
        { n = 'Asmaaxxʙʏ MX2', u = 'https://stream.zeno.fm/nkukhjz4vgtuv' },
        { n = 'BBC World Service', u = 'http://stream.live.vc.bbcmedia.co.uk/bbc_world_service' },
        { n = 'Beyond Retro', u = 'https://likeradiostream.com/likeretro' },
        { n = 'Deped Radio 1278 AM', u = 'http://58.97.187.52:5007/rp4' },
        { n = 'Favradio FM 1015', u = 'http://stream.hornhost.com:8109/' },
        { n = 'Fred Film Radioلغة عربية', u = 'https://s10.webradio-hosting.com/proxy/fredradioar/stream' },
        { n = 'HOUB Radio حُب', u = 'http://nap.casthost.net:8028/stream' },
        { n = 'Maura AR', u = 'https://stream.zeno.fm/fpasc3up26ptv' },
        { n = 'Mp3Quran Main', u = 'https://qurango.net/radio/mix' },
        { n = 'MX2', u = 'https://stream.zeno.fm/66gp9qukxaquv' },
        { n = 'Neon Radio - 80S 90S Pop Dance', u = 'https://live.flashbackcentral.co.uk/radio/8050/tunein.mp3' },
        { n = 'OFW Tambayan FM 1007', u = 'https://stream-170.zeno.fm/82bb4d2uz68uv?zs=CnZDUKriSmSeaRAwyMpGoQ&zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI4MmJiNGQydXo2OHV2IiwiaG9zdCI6InN0cmVhbS0xNzAuemVuby5mbSIsImp0aSI6IkNuWkRVS3JpU21TZWFSQXd5TXBHb1EiLCJpYXQiOjE3MTI4MzUxMDgsImV4cCI6MTcxMjgzNTE2OH0.eNzYZ6jQPY5RL2uohAGhp8G7cFwGXB9BjFUeX7mysXo&zttl=5' },
        { n = 'Old Time Radio USA', u = 'https://ais-sa3.cdnstream1.com/2607_128.mp3' },
        { n = 'PHR 1053 FM Precious Hearts Radio', u = 'https://stream-172.zeno.fm/yyzp7bv9qchvv?zs=FS8fstfMQw-0L-XNabOKtg&zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ5eXpwN2J2OXFjaHZ2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsImp0aSI6IkZTOGZzdGZNUXctMEwtWE5hYk9LdGciLCJpYXQiOjE3MTI5Mjg1MDQsImV4cCI6MTcxMjkyODU2NH0.lfZDEwX6ZNFFGIqdubaoRgrWWlEpvGJp4jIbELmANmg&zttl=5' },
        { n = 'Quran Radio', u = 'https://n09.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABjKoABHgAdULpynjQ7EwB6A' },
        { n = 'Radio Disney 1110 AM', u = 'https://listen.radioking.com/radio/453221/stream/508076' },
        { n = 'Radio Maria Middle East', u = 'http://dreamsiteradiocp2.com/proxy/rmphilippine?mp=/stream?ver=748140' },
        { n = 'Remix S-DJ', u = 'https://stream.zeno.fm/pdeizhgrtrstv' },
        { n = 'Rotana FM', u = 'http://curiosity.shoutca.st:6035/;' },
        { n = 'Saudi Quran1', u = 'http://n01.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABjrUiYUAAxwNU2wDdcOap9w' },
        { n = 'Sky Radio', u = 'https://cp11.serverse.com/proxy/skyradio/stream' },
        { n = 'Sunnah Radio', u = 'http://andromeda.shoutca.st:8189/stream' },
        { n = 'UFM 955', u = 'https://gbradio.cdn.tibus.net/U105?_=477645' },
        { n = 'Voice Of Grace', u = 'https://securestreams5.reliastream.com:1820/;' },
        { n = 'W ʙʏ MX2', u = 'https://stream.zeno.fm/rduelmumm6buv' },
        { n = 'إذاعة السنة', u = 'http://andromeda.shoutca.st:8189/live' },
        { n = 'إذاعة طريق السلف', u = 'https://airtime.salafwayfm.ly/' },
        { n = 'القارئ علي الحذيفي رواية قالون', u = 'https://qurango.net/radio/ali_alhuthaifi_qalon' },
        { n = 'القارئ محمد أيوب', u = 'https://qurango.net/radio/mohammed_ayyub' },
        { n = 'تفسير بن عثيمين', u = 'https://qurango.net/radio/tafseer' },
        { n = 'راديو الشرق مع بلومبرغ', u = 'https://l3.itworkscdn.net/asharqradioalive/asharqradioa/icecast.audio' },
        { n = 'صور من حياة الصحابة', u = 'https://qurango.net/radio/sahabah' },
        { n = 'مختصر السيرة', u = 'https://qurango.net/radio/almukhtasar_fi_alsiyra' },
        { n = 'مقدمة رسالة ابن أبي زيد القيرواني1', u = 'https://www.al-badr.net/download/esound/choroohat/abuzaid_alkirawani/001.mp3' },
    }
}
