return {
    ['serbia'] = {
        { n = 'Active Radio Bečej', u = 'http://active96-naxinacional.streaming.rs:8555/' },
        { n = 'Ami Naxi Radio Kikinda', u = 'http://185.119.88.88:8005/' },
        { n = 'Antena Krusevac', u = 'http://antenaradio.org:4560/;stream.nsv' },
        { n = 'Antena Radio Bor', u = 'http://37.120.184.200:8018/' },
        { n = 'Antena Radio Kruševac', u = 'http://antenaradio.org:4560/listen.pls' },
        { n = 'AS FM', u = 'https://mastermedia.shoutca.st/proxy/radioasfm?mp=/stream' },
        { n = 'B92', u = 'http://stream.b92.net:7999/radio-b92.mp3.m3u' },
        { n = 'BANKER', u = 'http://banker96-naxinacional.streaming.rs:8540/' },
        { n = 'Bela Crkva', u = 'http://belacrkva32.streaming.rs:8140/listen.pls' },
        { n = 'Belami Radio', u = 'http://92.60.230.200:5040/listen.pls' },
        { n = 'Boemi Radio', u = 'https://radio.dukahosting.com/8144/stream' },
        { n = 'Bravo FM 1037Mhz', u = 'http://91.221.134.252:8002/;*.mp3' },
        { n = 'Bum Bum Radio', u = 'http://bumbum-stream.netlogic.rs:8000/listen.pls' },
        { n = 'Cool Radio', u = 'http://176.9.30.66/cool64' },
        { n = 'Cool Radio Serbia', u = 'http://live.coolradio.rs/cool320' },
        { n = 'Dasko I Mladja', u = 'http://172.105.250.193:8000/stream' },
        { n = 'Deluxe Radio', u = 'http://cmr-hosting.com:8408/;*.mp3' },
        { n = 'Egata Radio', u = 'http://stream.zeno.fm/kcn3b5gfuhruv' },
        { n = 'Focus Radio', u = 'https://streamer.radio.co/s34d2c17d8/listen' },
        { n = 'Folk Radio Beograd', u = 'http://usa6.fastcast4u.com:5010/stream' },
        { n = 'Fox Radio', u = 'http://stream.foxradio.rs:8545/;stream.mp3' },
        { n = 'Gudalo I Struna', u = 'https://stream.zeno.fm/kpcnnvbdfjtvv' },
        { n = 'HIT FM Acoustic', u = 'http://streaming.hitfm.rs/acoustic.mp3' },
        { n = 'Hit FM Radio Beograd', u = 'http://streaming.hitfm.rs:8000/hit' },
        { n = 'Ifm Narodni Radio', u = 'http://91.228.254.72:7000/;stream.nsv' },
        { n = 'Ifm Radio', u = 'http://91.228.254.72:8000/;stream.nsv' },
        { n = 'Jack Folk Radio', u = 'http://185.105.4.53:401/;' },
        { n = 'JAT Radio', u = 'https://streaming.radiojat.rs/radiojat.mp3' },
        { n = 'Kiss FM', u = 'https://cast2.my-control-panel.com/proxy/kissdoog/stream' },
        { n = 'Kragujevac Plaza Radio', u = 'http://109.206.96.18:8020/;stream.nsv' },
        { n = 'Laguna', u = 'https://live.radiolaguna.rs/laguna' },
        { n = 'Lid Radio', u = 'http://213.239.205.210:8064/' },
        { n = 'Lotel Radio', u = 'https://s1.skeletor.rs/lotel' },
        { n = 'Lux Naxi Radio', u = 'http://lux-naxinacional.streaming.rs:8605/listen.pls' },
        { n = 'Lux Radio', u = 'https://lux-naxinacional.streaming.rs:8607/;' },
        { n = 'MB Radio', u = 'http://188.40.95.74:8100/;' },
        { n = 'Moj Radio', u = 'http://eu4.fastcast4u.com:5692/' },
        { n = 'Mugadavanje', u = 'https://radio.mugadavanje.rs/listen/mugadavanje/mugadavanje' },
        { n = 'Muzicki Radio 101', u = 'https://as1.radioserveri.com:8090/radio.mp3' },
        { n = 'Muzički Radio Fan', u = 'http://stream.fanradio.info:9000/listen.pls' },
        { n = 'Mária Rádió Szerbia', u = 'http://dreamsiteradiocp.com:8014/;' },
        { n = 'Nas Radio 107,80 Zabalj', u = 'https://radio.dukahosting.com:7043/;' },
        { n = 'NAS Radio 978', u = 'https://radio.dukahosting.com:7045/;' },
        { n = 'Naxi - Hype', u = 'https://naxidigital-hype128ssl.streaming.rs:8272/;stream.nsv' },
        { n = 'Naxi 70-E 3', u = 'https://naxidigital-70s128ssl.streaming.rs:8382/;' },
        { n = 'Naxi 70E', u = 'https://naxidigital-70s128ssl.streaming.rs:8042/;' },
        { n = 'Naxi 80-E Radio', u = 'https://naxidigital-80s128ssl.streaming.rs:8042/;' },
        { n = 'Naxi 90S', u = 'https://naxidigital-90s128ssl.streaming.rs:8282/;stream.nsv' },
        { n = 'Naxi Adore', u = 'https://naxidigital-adore128ssl.streaming.rs:8332/;stream.nsv' },
        { n = 'NAXI ART RADIO 102,2 Mhz', u = 'https://naxiartradio-naxinacional.streaming.rs:8627/;stream.mp3' },
        { n = 'Naxi Blues', u = 'https://naxidigital-blues128ssl.streaming.rs:8312/;stream.nsv' },
        { n = 'Naxi Boem Radio', u = 'https://naxidigital-boem128ssl.streaming.rs:8162/;' },
        { n = 'Naxi Cafe Radio', u = 'https://naxidigital-cafe128ssl.streaming.rs:8022/;' },
        { n = 'Naxi Chillwave', u = 'https://naxidigital-chillwave128ssl.streaming.rs:8322/;stream.nsv' },
        { n = 'Naxi Classic Radio', u = 'https://naxidigital-classic128ssl.streaming.rs:8032/;' },
        { n = 'Naxi Clubbing Radio', u = 'https://naxidigital-clubbing128ssl.streaming.rs:8092/;' },
        { n = 'Naxi Dance Radio', u = 'https://naxidigital-dance128ssl.streaming.rs:8112/;' },
        { n = 'Naxi Evergreen Radio', u = 'https://naxidigital-evergreen128ssl.streaming.rs:8012/;' },
        { n = 'Naxi Ex-Yu Rock Radio', u = 'http://naxidigital-exyurock128.streaming.rs:8400/' },
        { n = 'Naxi Exyu Radio', u = 'https://naxidigital-exyu128ssl.streaming.rs:8242/;stream.nsv' },
        { n = 'Naxi Exyu Radio HTTP', u = 'http://naxidigital-exyu48.streaming.rs:8245/' },
        { n = 'Naxi EXYU Rock', u = 'http://naxidigital-exyurock48.streaming.rs:8405/' },
        { n = 'Naxi Fitness', u = 'https://naxidigital-fitness128ssl.streaming.rs:8292/;stream.nsv' },
        { n = 'Naxi Fresh Radio', u = 'https://naxidigital-fresh128ssl.streaming.rs:8212/;stream.nsv' },
        { n = 'Naxi Gold Radio', u = 'https://naxidigital-gold128ssl.streaming.rs:8062/;stream.nsv' },
        { n = 'Naxi House Radio', u = 'https://naxidigital-house128ssl.streaming.rs:8002/;' },
        { n = 'Naxi Hype Radio', u = 'https://naxidigital-hype128ssl.streaming.rs:8272/;' },
        { n = 'Naxi Jazz Radio', u = 'https://naxidigital-jazz128ssl.streaming.rs:8172/;stream.nsv' },
        { n = 'Naxi Kids Radio', u = 'https://naxidigital-kids128ssl.streaming.rs:8052/;' },
        { n = 'Naxi Kids SERBIA', u = 'http://naxidigital-kids128.streaming.rs:8050/' },
        { n = 'Naxi Latino Radio', u = 'https://naxidigital-latino128ssl.streaming.rs:8232/;stream.nsv' },
        { n = 'Naxi Lounge Radio', u = 'https://naxidigital-lounge128ssl.streaming.rs:8252/;stream.nsv' },
        { n = 'Naxi Love Radio', u = 'https://naxidigital-love128ssl.streaming.rs:8102/;' },
        { n = 'Naxi MAX', u = 'http://max96-naxinacional.streaming.rs:8530/;stream.nsv' },
        { n = 'Naxi MIX', u = 'https://naxidigital-mix128ssl.streaming.rs:8222/;stream.nsv' },
        { n = 'Naxi Planeta Radio', u = 'http://planeta96-naxinacional.streaming.rs:8520/;' },
        { n = 'Naxi Radio - Cafe Radio', u = 'http://naxidigital-cafe128.streaming.rs:8020/;stream.nsv' },
        { n = 'Naxi Radio - Lounge', u = 'http://naxidigital-lounge128.streaming.rs:8250/listen.pls' },
        { n = 'Naxi Radio - Rock', u = 'http://naxidigital-rock128.streaming.rs:8180/;stream.nsv' },
        { n = 'Naxi Radio 016', u = 'https://naxiradio016-naxinacional.streaming.rs:8637/;.mp3?_=1' },
        { n = 'Naxi Radio Chillwave', u = 'http://naxidigital-chillwave128.streaming.rs:8320/listen.pls' },
        { n = 'Naxi Rock Radio', u = 'https://naxidigital-rock128ssl.streaming.rs:8182/;' },
        { n = 'No Limit Radio', u = 'http://webradio.sksyu.net:8000/nolimithq.ogg' },
        { n = 'Nostalgie Radio Belgrade - 105,2 Mhz', u = 'https://nostalgie128ssl.streaming.rs:9252/;stream.mp3' },
        { n = 'Nostalgija Radio', u = 'http://nostalgie128.streaming.rs:9250/;' },
        { n = 'Nova S', u = 'http://radio.novas.tv/novas.mp3' },
        { n = 'OK Plus Radio', u = 'https://stream.okplus.rs/listen/plus/radio.mp3' },
        { n = 'OK Prelo Radio', u = 'https://stream.okplus.rs/listen/prelo/radio.mp3' },
        { n = 'OK Radio', u = 'https://sslstream.okradio.net/?type=http&nocache=8804' },
        { n = 'OK Radio Plus', u = 'http://live.okplus.rs:8000/;stream.nsv' },
        { n = 'OK Radio Prelo', u = 'http://live.okplus.rs:8050/;*.mp3' },
        { n = 'Op Top Radio', u = 'http://213.239.205.210:8112/;' },
        { n = 'Pannon Rádió', u = 'http://breddstream.unrealhosting.hu:4120/;' },
        { n = 'Pink Radio', u = 'http://pink.exyuserver.com/;stream.mp3' },
        { n = 'Play', u = 'http://stream.playradio.rs:8001/play.aac.m3u' },
        { n = 'Play Radio Party', u = 'https://stream.playradio.rs:8443/party.mp3' },
        { n = 'Play Radio Rock', u = 'https://stream.playradio.rs:8443/rock.mp3' },
        { n = 'Play Radio Serbia', u = 'https://stream.playradio.rs:8443/play.mp3' },
        { n = 'Prvi Radio Novi Sad', u = 'https://mastermedia.shoutca.st/proxy/prviradions?mp=/stream' },
        { n = 'Radio 012', u = 'http://144.76.219.22:8762/;' },
        { n = 'Radio 021', u = 'https://radio.dukahosting.com/8006/stream' },
        { n = 'Radio 3', u = 'http://radio3-128.streaming.rs:9200/' },
        { n = 'Radio 3 LIVE', u = 'https://radio3-64ssl.streaming.rs:9212/;stream.nsv' },
        { n = 'Radio 31 Plus', u = 'https://cast4.asurahosting.com/proxy/dejan/stream' },
        { n = 'Radio 34', u = 'http://stream.radio34.rs:8889/;*.mp3' },
        { n = 'Radio 4P Narodna Muzika', u = 'http://server4p.com:8002/stream' },
        { n = 'Radio Aparat', u = 'http://ca3.rcast.net:8060/;stream.mp3;' },
        { n = 'Radio Apatin', u = 'http://apatin96-naxinacional.streaming.rs:8500/listen.pls' },
        { n = 'Radio As', u = 'http://185.102.239.216:8000/;' },
        { n = 'Radio B92', u = 'http://stream.b92.net:7999/radio-b92.mp3' },
        { n = 'Radio Balkan Narodna', u = 'https://radiobalkan.live/radio/live/narodna.mp3' },
        { n = 'Radio Balkan Trending', u = 'https://radiobalkan.live/radio/live/trending.mp3' },
        { n = 'Radio Balkan Zabavna', u = 'https://radiobalkan.live/radio/live/zabavna.mp3' },
        { n = 'Radio Banja 2', u = 'https://stream.iradio.pro/proxy/radiobanja2?mp=/stream' },
        { n = 'Radio Banker', u = 'http://banker96-naxinacional.streaming.rs:8540/;' },
        { n = 'Radio Belle Amie Niš', u = 'http://92.60.230.200:5040/' },
        { n = 'Radio Beseda', u = 'http://radio.eparhijabacka.info:8000/RadioBeseda' },
        { n = 'Radio Blagovesnik', u = 'http://radio.eparhijabacka.info:8000/RadioBlagovesnik' },
        { n = 'Radio Bubamara', u = 'http://92.60.230.200:5010/;*.mp3' },
        { n = 'Radio Cer', u = 'http://stream1.contrateam.com:8040/listen.pls' },
        { n = 'Radio Cvrčak', u = 'http://stream.iradio.pro:8190/;' },
        { n = 'Radio D', u = 'http://213.239.205.210:6010/listen.pls' },
        { n = 'Radio Desetka', u = 'http://pink.exyuserver.com/;*.mp3' },
        { n = 'Radio Diskos', u = 'https://eu8.fastcast4u.com/proxy/znedel032?mp=/1' },
        { n = 'Radio Dženarika', u = 'http://stream.dzenarika.net:8000/stream' },
        { n = 'Radio Džuboks', u = 'http://176.9.59.144:8090/dzuboks' },
        { n = 'Radio Fantasy Vrbas', u = 'http://109.206.96.34:8575/;stream.nsv' },
        { n = 'Radio Fruska Gora', u = 'https://stream.iradio.pro/proxy/radiofruskagora?mp=/stream' },
        { n = 'Radio Futog', u = 'https://radio.dukahosting.com:7001/' },
        { n = 'Radio Gaga', u = 'https://onlineradiobox.com/json/rs/gaga/play?platform=web' },
        { n = 'Radio Gračanica', u = 'http://188.40.95.74:8012/;' },
        { n = 'Radio In', u = 'https://radioinnis-naxinacional.streaming.rs:8622/;' },
        { n = 'Radio IN Beograd', u = 'https://radio3-64ssl.streaming.rs:9212/;*.mp3' },
        { n = 'Radio K4', u = 'http://fm.radiokfor.com:8090/listen.pls' },
        { n = 'Radio Klas', u = 'http://195.201.172.217:9014/;' },
        { n = 'Radio Kolo', u = 'https://mars.streamerr.co/8280/stream' },
        { n = 'Radio Kolubara 96,9', u = 'https://stream.iradio.pro/proxy/radiokolubara?mp=/1' },
        { n = 'Radio Kosava 1', u = 'https://main.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava 2', u = 'https://kosava2.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Classic', u = 'https://klasik.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Folk 1', u = 'https://folk1.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Folk 2', u = 'https://folk2.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Folk 3', u = 'https://folk3.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Info', u = 'https://info.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Kids', u = 'https://kids.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Koncert 1', u = 'https://koncert1.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Latino', u = 'https://latino.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Kosava Love 1', u = 'https://love.radiokosava.rs/;stream.mp3' },
        { n = 'Radio Košava Fm', u = 'https://main.radiokosava.rs/;' },
        { n = 'Radio Krajina 019', u = 'https://cmr-hosting.com:7021/;' },
        { n = 'Radio Kulska Komuna', u = 'http://as.q-media.rs:8000/mp3' },
        { n = 'Radio Levač', u = 'http://213.239.205.210:8046/' },
        { n = 'Radio Ljubav', u = 'http://ljubav.streaming.rs:9340/listen.pls' },
        { n = 'Radio Lola', u = 'http://s2.tdiradio.com:8000/radiolola.mp3' },
        { n = 'Radio Lola - Domaca', u = 'https://streaming.tdiradio.com/radiolola.mp3' },
        { n = 'Radio Mackica - Narodna Muzika', u = 'http://cast2.name.ba:8153/;stream.nsv' },
        { n = 'Radio Mackica - Zabavna Muzika', u = 'http://cast2.name.ba:8157/;stream.nsv' },
        { n = 'Radio Magnum', u = 'http://magnum.web-srbija.net:8121/;stream.nsv' },
        { n = 'RADIO MARIA SERBIA', u = 'http://dreamsiteradiocp.com:8012/stream' },
        { n = 'RADIO MARIA SERBIA HUNG', u = 'http://dreamsiteradiocp2.com:8062/stream' },
        { n = 'Radio Mačkica', u = 'http://cast2.name.ba:8153/;*.mp3' },
        { n = 'Radio Morava', u = 'https://e3.radiomorava.rs/radio/8000/radiomorava128.mp3' },
        { n = 'Radio Naxi', u = 'https://naxi128ssl.streaming.rs:9152/' },
        { n = 'Radio Nostalgija', u = 'http://nostalgie128.streaming.rs:9250/' },
        { n = 'Radio Nostalgija AAC', u = 'http://nostalgie48.streaming.rs:9270/listen.pls' },
        { n = 'Radio Novosti', u = 'http://www.radionovosti.rs:443/radionovosti56s.mp3.m3u' },
        { n = 'Radio Novosti Ex-Yu', u = 'http://novosti.radiostreaming.rs/novosti2' },
        { n = 'Radio Pingvin', u = 'http://uzivo4.radiopingvin.com:8187/domaci1' },
        { n = 'Radio Pink Int', u = 'http://pink.exyuserver.com/stream;' },
        { n = 'Radio Podrinje', u = 'https://s1.skeletor.rs/podrinje' },
        { n = 'Radio Podrinje Loznica', u = 'http://s1.skeletor.rs:8000/podrinje' },
        { n = 'Radio Puls Grocka', u = 'http://176.9.59.144:8090/puls' },
        { n = 'Radio Razbibriga', u = 'http://213.239.205.210:8001/stream' },
        { n = 'Radio Ritam Srca', u = 'https://s4.radio.co/s0f65dad2d/listen' },
        { n = 'Radio Ruf', u = 'http://77.46.153.156:8000/;' },
        { n = 'Radio S', u = 'http://live.radio.si/radios' },
        { n = 'Radio San Loznica', u = 'https://s1.skeletor.rs/san' },
        { n = 'Radio SKAY', u = 'http://185.119.89.63:8000/;' },
        { n = 'Radio Slavoslovlje', u = 'http://radio.eparhijabacka.info:8000/RadioSlavoslovlje' },
        { n = 'Radio Sljivovica', u = 'http://stream.iradio.pro:8114/;stream.nsv' },
        { n = 'Radio Slobodna Evropa', u = 'http://rfe05.akacast.akamaistream.net/7/510/437763/v1/ibb.akacast.akamaistream.net/rfe05?download=1' },
        { n = 'Radio Slovo Ljubve', u = 'http://160.153.245.85:8000/' },
        { n = 'Radio Song Niš', u = 'http://stream.zeno.fm/wn6rxh42czzuv' },
        { n = 'Radio Stara Čaršija', u = 'http://radio.dukahosting.com:8026/;' },
        { n = 'Radio Starcevo', u = 'http://mpc2.mediacp.eu:8350/listen.pls?sid=1' },
        { n = 'Radio Stari Grad', u = 'http://stream.rsg.rs:8043/;stream.nsv' },
        { n = 'Radio Strela 907 FM - Veliki Popovic-Despotovac', u = 'http://176.9.59.144:8090/strela?type=http' },
        { n = 'Radio Strela Veliki Popović', u = 'http://176.9.59.144:8090/strela' },
        { n = 'Radio Studio B', u = 'http://radio.studiob.rs:8004/' },
        { n = 'Radio Sunset', u = 'http://cmr-hosting.com:8425/stream' },
        { n = 'Radio Tavor', u = 'http://radio.eparhijabacka.info:8000/RadioTavor' },
        { n = 'Radio TRI', u = 'https://radiotri-128.streaming.rs:9302/;stream.mp3' },
        { n = 'Radio Užice', u = 'http://uzice.yunethosting.net:8000/stream' },
        { n = 'Radio Vihor Mladenovac', u = 'https://stream.radiovihor.rs/' },
        { n = 'Radio VIP', u = 'http://vip128.streaming.rs:8110/listen.pls' },
        { n = 'Radio Vladimirci', u = 'http://icecast.astratelekom.com:8000/vladimirci' },
        { n = 'Radio Zelengrad - Milwaukee - USA', u = 'http://usa5.fastcast4u.com:16276/;stream.nsv' },
        { n = 'Radio Šajkaška', u = 'http://91.228.254.72:8000/listen.pls' },
        { n = 'Radio Šumadinac', u = 'https://media.srb-streaming.com/stream/radio-sumadinac-uzivo' },
        { n = 'Radio Šumadinac Južni Vetar', u = 'https://media.srb-streaming.com/stream/radio-sumadinac-juzni' },
        { n = 'Radio Šumadinac Krajiška', u = 'https://media.srb-streaming.com/stream/radio-sumadinac-krajiska' },
        { n = 'Radio Šumadinac Narodna', u = 'https://media.srb-streaming.com/stream/radio-sumadinac-narodna' },
        { n = 'Radioaparat', u = 'http://ca3.rcast.net:8060/' },
        { n = 'RADIOD59B', u = 'http://stream.radiojar.com/gn6dqzhf9mzuv.m3u' },
        { n = 'Red Radio Beograd', u = 'https://stream.redradio.rs/sid=1' },
        { n = 'Resavski Radio', u = 'https://e3.radiomorava.rs/radio/8010/resavskiradio128.mp3' },
        { n = 'Rock Radio Belgrade Рок Радио Београд', u = 'https://edge9.pink.rs/rockstream' },
        { n = 'Rock Radio Beograd', u = 'https://edge9.pink.rs/rockstream/' },
        { n = 'RSG Party Time', u = 'https://stream.rsg.rs/partytime/' },
        { n = 'RSG Radio Stari Grad', u = 'https://stream.rsg.rs/live/' },
        { n = 'RSG Relax', u = 'https://stream.rsg.rs/relax/' },
        { n = 'Sun Radio Novi Sad', u = 'http://stream.radiojar.com/4qawu2xta2zuv.mp3' },
        { n = 'Super FM', u = 'http://onair.superfm.rs/superfm.mp3' },
        { n = 'Super FM Beograd', u = 'https://onair.superfm.rs/superfm.mp3' },
        { n = 'Szabadkai Magyar Rádió', u = 'http://breddstream.unrealhosting.hu:4110/;' },
        { n = 'TDI BEZ REKLAMA', u = 'https://streaming.tdiradio.com/tdiradiobezreklama.mp3' },
        { n = 'TDI House', u = 'http://streaming.tdiradio.com:8000/house.mp3' },
        { n = 'TDI Radio', u = 'http://streaming.tdiradio.com:8000/tdiradio' },
        { n = 'TDI Radio - Classics', u = 'http://streaming.tdiradio.com:8000/classics' },
        { n = 'TDI Radio - Love', u = 'http://streaming.tdiradio.com:8000/love' },
        { n = 'TDI Radio - Top 40', u = 'http://streaming.tdiradio.com:8000/top40' },
        { n = 'TOP FM Belgrade - 106,8 Mhz', u = 'https://topfm64ssl.streaming.rs:9287/;stream.mp3' },
        { n = 'Undergrand Radio', u = 'http://stream.zeno.fm/rp1swb5pgzzuv' },
        { n = 'Usce Shopping Radio', u = 'http://naxidigital-usce128.streaming.rs:8000/;stream.nsv' },
        { n = 'Ušće Shoping Radio', u = 'http://109.206.96.18:8000/;' },
        { n = 'VIP Radio', u = 'http://vip128.streaming.rs:8110/;stream.nsv' },
        { n = 'Vladix 2 Rock', u = 'http://vladix.dukahosting.com:8022/;stream.nsv' },
        { n = 'Vladix 4 Rok', u = 'http://vladix.dukahosting.com:8010/;stream.nsv' },
        { n = 'Vladix Radio', u = 'http://vladix.dukahosting.com:8000/;stream.nsv' },
        { n = 'Vudulicious Caffe Radio', u = 'http://109.206.96.34:8200/;stream.nsv' },
        { n = 'WTF Radio', u = 'http://live.wtfradio.rs/wtfradio.mp3' },
        { n = 'Yu Novi Pazar', u = 'https://yuradio.ipradio.rs:9036/;' },
        { n = 'Čivijaš Radio', u = 'https://media.srb-streaming.com/tunein/radio-civijas/stream/pls' },
    }
}
