return {
    ['singapore'] = {
        { n = '938 Now Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/938NOWAAC.aac' },
        { n = '973FM Blasts That Last', u = 'http://c16.radioboss.fm:8115/autodj' },
        { n = '973FM: Blasts That Last Radio', u = 'https://c16.radioboss.fm:18115/stream?icecast' },
        { n = '987', u = 'https://14033.live.streamtheworld.com/987FM_SC' },
        { n = '987FM', u = 'https://22393.live.streamtheworld.com/987FM_PREM.aac' },
        { n = 'AXR Manila', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/AXR_MANILA.mp3' },
        { n = 'AXR Singapore', u = 'http://singaporestream.axr.online/' },
        { n = 'Bible Witness Web Radio', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SP_R3179571_SC' },
        { n = 'Capital 958 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/CAPITAL958FMAAC.aac' },
        { n = 'Class 95 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/CLASS95AAC.aac' },
        { n = 'CNA 938', u = 'https://22893.live.streamtheworld.com/938NOW_SC' },
        { n = 'CNA 938 Live Singapore', u = 'http://playerservices.streamtheworld.com/pls/938NOW_PREM.pls' },
        { n = 'Eight FM', u = 'https://mediaprima.rastream.com/mediaprima-onefm' },
        { n = 'GOLD 905', u = 'https://22403.live.streamtheworld.com/GOLD905_SC' },
        { n = 'Gold 905 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/GOLD905AAC.aac' },
        { n = 'Jia 883 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/883JIAAAC.aac' },
        { n = 'Kiss92', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/KISS_92_SC' },
        { n = 'Love 972', u = 'http://22903.live.streamtheworld.com/LOVE972FMAAC.aac' },
        { n = 'Mediacorp 987 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/987FMAAC.aac' },
        { n = 'Money 893 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/MONEY_893AAC.aac' },
        { n = 'Money FM 893', u = 'https://22243.live.streamtheworld.com/MONEY_893AAC.aac?dist=sphradio-web&tdsdk=js-2.9&swm=false&pname=TDSdk&pversion=2.9&banners=none&burst-time=15&sbmid=f94bbefc-acee-4c13-ed7b-9accdb44b7a2' },
        { n = 'Oli 968 FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/OLI968FMAAC.aac' },
        { n = 'Oli 968 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/OLI968FMAAC.aac' },
        { n = 'ONE FM', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/one_FM_913AAC.aac?dist=radiosingaporeapp' },
        { n = 'One FM 913', u = 'https://playerservices.streamtheworld.com/pls/ONE_FM_913AAC.pls' },
        { n = 'ONE FM 913 SPH AAC', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/ONE_FM_913AAC.aac' },
        { n = 'Pergas Radio', u = 'https://s3.radio.co/saf69a95b8/low' },
        { n = 'Power 98 Love Songs', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/POWER98_LOVESONGS.mp3' },
        { n = 'Radio Melody With Brother Bjorn', u = 'https://ssl.geckohost.nz/proxy/bjorn?mp=/stream&1703130377563' },
        { n = 'RIA 897', u = 'https://22393.live.streamtheworld.com/RIA897FM_SC' },
        { n = 'Ria 897 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/RIA897FMAAC.aac' },
        { n = 'Singapore Chinese POP YES FM 933', u = 'https://22893.live.streamtheworld.com/YES933_SC?dist=radiosingapore' },
        { n = 'SPH 963 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/HAO_963AAC.aac' },
        { n = 'Symphony 924 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/SYMPHONY924AAC.aac' },
        { n = 'Ufm 1003', u = 'http://28093.live.streamtheworld.com/UFM_1003AAC.aac' },
        { n = 'UFM 1003 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/UFM_1003AAC.aac' },
        { n = 'Warna 942 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/WARNA942FMAAC.aac' },
        { n = 'Yes 933', u = 'http://28453.live.streamtheworld.com/YES933AAC.aac' },
        { n = 'YES 933 Radio', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/YES933AAC.aac' },
    }
}
