return {
    ['south_africa'] = {
        { n = '5FM', u = 'http://25483.live.streamtheworld.com/5FMAAC.aac' },
        { n = '702 Johannesburg', u = 'http://playerservices.streamtheworld.com/m3u/FM702.m3u' },
        { n = '702 Talk Radio Johannesburg', u = 'https://23543.live.streamtheworld.com/FM702AAC.aac' },
        { n = '919', u = 'https://edge.iono.fm/xice/112_low.aac' },
        { n = '947', u = 'http://playerservices.streamtheworld.com/m3u/FM947.m3u' },
        { n = '947 Highveld Stereo', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/FM947_SC' },
        { n = 'African Praise Radio', u = 'https://fastcast4u.com/player/africanpraiserad/?pl=winamp&c=African Praise Radio' },
        { n = 'Al-Ansaar Radio', u = 'https://al-ansaar.simplestreaming.co.za/listen/al-ansaar_radio/radio.mp3' },
        { n = 'Algoa FM', u = 'http://edge.iono.fm/xice/54_high.mp3' },
        { n = 'Amapiano FM', u = 'https://stream.zeno.fm/xs6zeac1ts8uv' },
        { n = 'Bloem Radio Digital', u = 'https://9300.co.za/listen/bloem_radio_digital/radio.mp3' },
        { n = 'Bok Radio', u = 'https://bokradio.highquality.radiostream.co.za/' },
        { n = 'Bokradio', u = 'http://bokradio.highquality.radiostream.co.za/' },
        { n = 'Bosveld Stereo', u = 'http://capeant.antfarm.co.za:8000/Bosveld' },
        { n = 'Box Afrofusion Amapiano', u = 'https://play.streamafrica.net/afrofusionamp' },
        { n = 'Cape Talk', u = 'http://playerservices.streamtheworld.com/m3u/CAPE_TALK.m3u' },
        { n = 'Capital Radio 604', u = 'https://stream.galaxywebsolutions.com/proxy/capitalradio604?mp=/stream' },
        { n = 'Capricorn FM', u = 'http://edge.iono.fm/xice/67_medium.aac' },
        { n = 'CCFM 1075', u = 'https://edge.iono.fm/xice/69_medium.aac' },
        { n = 'Chai FM', u = 'https://zas1.ndx.co.za:8008/stream?1702143258610' },
        { n = 'Channel Islam International', u = 'http://edge.iono.fm/xice/109_medium.aac' },
        { n = 'Classic FM 1027', u = 'http://edge.iono.fm/xice/49_medium.aac?p=embed' },
        { n = 'Cliff Central', u = 'https://edge.iono.fm/xice/cliffcentral_live_medium.aac' },
        { n = 'East Coast Gold', u = 'https://live.ecr.co.za/ecrgoldhigh.mp3' },
        { n = 'East Coast Radio', u = 'https://live.ecr.co.za/ecrhigh.mp3?aw_0_pinpoll=1,2,9&awparams=companionAds:true' },
        { n = 'ECR - East Coast Radio -Kwazulu Natal', u = 'https://edge.iono.fm/xice/ecr_live_medium.aac' },
        { n = 'Emzini Fm Radio', u = 'http://stream.zeno.fm/2kbssevq5tjvv' },
        { n = 'Express-Fm Digital', u = 'http://198.7.59.28:34235/stream' },
        { n = 'Faithofgodseedchurch', u = 'http://stream.laut.fm/faithofgodseedchurch.pls' },
        { n = 'Gaysa Radio', u = 'https://zas1.ndx.co.za:8018/stream' },
        { n = 'Groot FM', u = 'https://cast3.my-control-panel.com/proxy/grootfm/stream?1682362396578' },
        { n = 'Harties FM', u = 'https://s5.radio.co/s68c6f4028/listen' },
        { n = 'Heaven FM', u = 'https://stream.zeno.fm/eequgfw72hhvv' },
        { n = 'Helderberg FM', u = 'https://helderberg.highquality.radiostream.co.za/' },
        { n = 'Hellenic Radio', u = 'http://iceant.eclipse-streaming.co.za/Hellenic' },
        { n = 'Hot 1027 FM', u = 'https://edge.iono.fm/xice/57_high.aac' },
        { n = 'Hot 1027 FM Club', u = 'https://edge.iono.fm/xice/306_high.aac' },
        { n = 'Hot 1027FM', u = 'https://edge.iono.fm/xice/57_medium.aac?ref=https://hot1027.co.za/&adToken' },
        { n = 'HOT 919', u = 'http://edge.iono.fm/xice/57_medium.mp3' },
        { n = 'IFM 1022', u = 'http://s7.voscast.com:9538/;stream1700094931336/1' },
        { n = 'Ilizwi Fm', u = 'https://sv2.famcast.co.za/proxy/ilizwi_fm/stream' },
        { n = 'Impala Radio', u = 'https://maggie.torontocast.com:8014/stream' },
        { n = 'Jacaranda', u = 'https://live.jacarandafm.com/jacarandahigh.mp3' },
        { n = 'Jacaranda FM', u = 'https://edge.iono.fm/xice/jacarandafm_live_medium.aac' },
        { n = 'Jacarandahigh', u = 'https://edge.iono.fm/xice/jacarandafm_live_high.aac' },
        { n = 'Jakaranda FM', u = 'https://edge.iono.fm/xice/jacarandafm_live_high.mp3' },
        { n = 'JOY GOSPEL RADIO', u = 'https://servidor17.brlogic.com:7012/live' },
        { n = 'Joyful FM', u = 'http://c15.radioboss.fm:8218/stream' },
        { n = 'Jozi FM', u = 'https://edge.iono.fm/xice/51_medium.aac' },
        { n = 'Jozi FM Hifi Aac', u = 'https://edge.iono.fm/xice/51_high.aac' },
        { n = 'Katlego Fm', u = 'https://streaming.live365.com/a26642' },
        { n = 'Kaya FM', u = 'https://edge.iono.fm/xice/82_medium.aac' },
        { n = 'Kfm', u = 'http://25583.live.streamtheworld.com/KFM_SC' },
        { n = 'KFM 945', u = 'https://25483.live.streamtheworld.com/KFM_192AAC.aac' },
        { n = 'KM RADIO', u = 'https://centova.hostingelectrica.net/proxy/kmradio?mp=/stream&1704296313782' },
        { n = 'Kurara FM', u = 'https://stream.zeno.fm/gvmschcf9yzuv' },
        { n = 'Lekker FM', u = 'https://zas3.ndx.co.za:8002/stream' },
        { n = 'Link FM RSA-EC', u = 'https://de2.streamingpulse.com/ssl/LinkFM' },
        { n = 'Lister FM', u = 'http://www.adhocstreaming.co.za:8000/LuisterFM' },
        { n = 'LM Radio South Africa', u = 'http://cast.fabrik.fm:8008/' },
        { n = 'Loca FM', u = 'https://s3.we4stream.com:2020/stream/locafm' },
        { n = 'Mabopane Rise Radio', u = 'https://stream.zeno.fm/kyap8zs093yvv' },
        { n = 'Magic 828', u = 'http://cast.fabrik.fm:8106/' },
        { n = 'Metro FM SA', u = 'https://27993.live.streamtheworld.com/METROFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=496fec8c-5809-460a-beb7-3545115118ca' },
        { n = 'MFM', u = 'https://edge.iono.fm/xice/46_medium.aac' },
        { n = 'Mix 938 FM', u = 'https://edge.iono.fm/xice/113_medium.aac' },
        { n = 'NCDOH Radio The Healthy Sound From Northern Cape Department Of Health', u = 'https://stream-154.zeno.fm/grjnbwcxbneuv' },
        { n = 'OFM 94 97 FM Bloemfontein', u = 'http://edge.iono.fm/xice/ofm_live_medium.aac' },
        { n = 'Orania Radio', u = 'https://eclipse-radio2.eclipse-streaming.co.za/listen/radio_orania/radio.mp3' },
        { n = 'Pep Feel Good Fm', u = 'https://edge.iono.fm/xice/feelgood_live_high.aac' },
        { n = 'Perron FM', u = 'https://zas7.ndx.co.za:8044/stream?1694973588521' },
        { n = 'Pitch Radio', u = 'http://stream.zeno.fm/etw8vx9knm0uv' },
        { n = 'Power 987', u = 'https://edge.iono.fm/xice/65_medium.aac' },
        { n = 'Pretoria FM', u = 'http://capeant.antfarm.co.za:8000/ptafm' },
        { n = 'PSH Radio', u = 'https://radio2.whazup.mobi/listen/psh_radio/pshlive.aac?1725024971931' },
        { n = 'Radio 2000', u = 'http://27743.live.streamtheworld.com/RADIO2000AAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=8310c16e-1928-4209-9339-97787465358b' },
        { n = 'Radio 2000 SABC', u = 'http://25483.live.streamtheworld.com/RADIO2000AAC.aac?dist=triton-widget&tdsdk=js-2.9&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=3e99e625-68d3-4273-8866-a73f7d8fe4d8' },
        { n = 'Radio 786', u = 'http://stream.krypton.co.za:8040/stream/' },
        { n = 'Radio Free Tankwa', u = 'https://samcloud.spacial.com/api/listen?sid=69819&m=sc&rid=155682' },
        { n = 'Radio Fynbos - Stilbaai', u = 'https://stream-152.zeno.fm/w0cyqt4cyy8uv?zs=KrkViuxOTr6gZl4perU1jA' },
        { n = 'Radio Islam', u = 'http://stream.radioislam.org.za:7542/radioislam.mp3' },
        { n = 'Radio Islam International', u = 'http://listen.radioislam.co.za:8080/radioislam.mp3' },
        { n = 'RADIO NAMAKWALAND', u = 'https://zas3.ndx.co.za:8034/stream' },
        { n = 'Radio Orania', u = 'https://saukradio.com/wp-content/uploads/2021/07/5-Julie-Orania.mp3' },
        { n = 'Radio Pulpit', u = 'https://edge.iono.fm/xice/189_medium.aac?ref=https://www.radiopulpit.co.za/&adToken' },
        { n = 'Radio Turf 1038 FM', u = 'https://sv2.famcast.co.za/proxy/radioturf/stream' },
        { n = 'Radio Veritas', u = 'https://zas5.ndx.co.za:9618/stream?1702476652972' },
        { n = 'Rainbow FM', u = 'https://edge.iono.fm/xice/237_low.aac' },
        { n = 'Replay Radio', u = 'http://stream.zeno.fm/a5r2rwnnffhvv' },
        { n = 'RISE FM', u = 'https://edge.iono.fm/xice/73_medium.aac?ref=https://risefm.co.za/&adToken' },
        { n = 'RSG', u = 'http://25443.live.streamtheworld.com/RSGAAC.aac?dist=triton-widget&tdsdk=js-2.9&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=05b99128-657f-4c70-b58c-df652bf26291' },
        { n = 'SAFFA Onair World Radio', u = 'http://stream.zeno.fm/k8cqvwu2za0uv' },
        { n = 'SAFM', u = 'http://25433.live.streamtheworld.com/SAFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=8af09f6c-1528-4186-9e2b-4f0275cc87b9' },
        { n = 'Salaammedia', u = 'https://iceant.antfarm.co.za/Salaam' },
        { n = 'SFM Streek Radio', u = 'http://capeant.antfarm.co.za:8000/SFM' },
        { n = 'Simply Making Success Radio', u = 'https://stream.zeno.fm/ylvoyhv6tbntv' },
        { n = 'Sky Alpha HD', u = 'https://sv2.famcast.co.za/proxy/skyalphahd?mp=/stream' },
        { n = 'Smile 904 FM', u = 'https://edge.iono.fm/xice/212_medium.aac' },
        { n = 'Starfm', u = 'https://edge.iono.fm/xice/112_medium.aac' },
        { n = 'Talk Radio 702', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/FM702_192AAC.aac' },
        { n = 'TAMBO FM', u = 'https://listen.radioking.com/radio/326599/stream/374668?fbclid=IwAR3lWR7ZdVVmZBSBedW_Cv1xF_Q7KzGmUQ0stgVCc_A7kx8Cf3Ncek1ntxk' },
        { n = 'Thobelafm', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/THOBELAAAC.aac' },
        { n = 'Trufm SABC', u = 'http://25483.live.streamtheworld.com/TRUFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=ccfa99e2-501e-41aa-ba19-701128ad7a93' },
        { n = 'Tuks FM', u = 'http://edge.iono.fm/xice/tuksfm_live_medium.aac' },
        { n = 'Tygerberg 104FM', u = 'http://zas6.ndx.co.za:8007/' },
        { n = 'Ubuntufm', u = 'https://streaming.coollective.nl:8443/UbuntuFM' },
        { n = 'Uniquefive HD Radio', u = 'http://stream.zeno.fm/a4t818ymva0uv' },
        { n = 'Viva Nation Radio', u = 'https://servidor34-3.brlogic.com:7056/live?source=website' },
    }
}
