return {
    ['spain'] = {
        { n = '#1 HITS 80S', u = 'https://makri.cdnstream.com/1898_128' },
        { n = '#1 Splash 90S', u = 'https://c4.auracast.net/radio/8050/radio.mp3' },
        { n = '#1 Splash 90S Dance', u = 'https://c6.auracast.net/radio/8090/radio.mp3' },
        { n = '#1 Splash Coffee', u = 'https://ais-sa2.cdnstream1.com/2345_128.mp3' },
        { n = '#1 Splash Lounge', u = 'https://ais-sa2.cdnstream1.com/2209_128.mp3' },
        { n = '#1 Splash Spa', u = 'https://ais-sa2.cdnstream1.com/2347_128.mp3' },
        { n = '+Buena FM', u = 'https://sonic.mediatelekom.net/8156/stream' },
        { n = '1 Oldies', u = 'https://80sexitos.stream.laut.fm/80sexitos' },
        { n = '1 Slow-Radio - Lautfm', u = 'https://1slowradio.stream.laut.fm/1_slowradio' },
        { n = '1000 80S Hits', u = 'https://ais-sa9.cdnstream1.com/1898_128' },
        { n = '1000 HITS 80S', u = 'http://c2.auracast.net:8048/stream' },
        { n = '1000 HITS Classical', u = 'https://ais-sa2.cdnstream1.com/2208_128.mp3' },
        { n = '1000 Hits Spain', u = 'https://c2.auracast.net:8022/;' },
        { n = '1000 Oldies', u = 'https://c3.auracast.net/radio/8010/;' },
        { n = '24FM Axarquía 1039', u = 'https://axarquia.emisiononline.es:8030/radio.mp3' },
        { n = '77 RADIO LA PALMA FM 883 - 998', u = 'https://radioserver11.profesionalhosting.com/proxy/suoqgqzc?mp=/stream' },
        { n = '80S Super Dancefloor', u = 'https://s41.myradiostream.com:33604/;' },
        { n = '90 FM 952', u = 'http://185.23.192.118:8010/;' },
        { n = '999 Plaza Radio Valencia', u = 'https://stream1.solstreaming.com:8112/stream' },
        { n = '999 Valencia Radio', u = 'http://stream1.solstreaming.com:8010/stream' },
        { n = 'A Rádio POP', u = 'https://pop.jmvstream.com/stream' },
        { n = 'A Xente De Teo', u = 'https://axentedeteo.ddns.net/radio/8000/radio.mp3' },
        { n = 'AB95FM', u = 'https://stream-157.zeno.fm/dwqgk9dxs98uv' },
        { n = 'Adagio Radio HD', u = 'https://stream.tunerplay.com/radio/8010/adagioradioHD.mp3' },
        { n = 'Adagioradio', u = 'https://stream.tunerplay.com/radio/8010/adagioradio.mp3' },
        { n = 'Agro Radio 1030', u = 'https://sonicpanel.streamsolutions.us/8038/stream' },
        { n = 'Alcúdia Ràdio', u = 'https://enacast.com/alcudiaradio/streams/HD' },
        { n = 'Altafulla Ràdio', u = 'https://enacast.com/altafullaradio/streams/HD' },
        { n = 'Ames Radio', u = 'https://radioserver11.profesionalhosting.com/proxy/pkg78640?mp=/stream;&_=1#.mp3' },
        { n = 'Amor FM', u = 'https://stream.zeno.fm/fqmu9c005hhvv' },
        { n = 'Antena 2000', u = 'https://eu1.fastcast4u.com/proxy/antena2000?mp=/1' },
        { n = 'Antena Caro', u = 'http://streaming.enantena.com:8000/antenacaro128.mp3' },
        { n = 'Antena CEMU', u = 'https://sonic.mediatelekom.net/9980/stream' },
        { n = 'Antena Cemu Radio 892 FM', u = 'http://str1.mediatelekom.net:8110/;' },
        { n = 'Antena Huelva 973 FM', u = 'http://stm1.emiteonline.com:8024/antenahuelva' },
        { n = 'Aqua Radio', u = 'https://quincy.torontocast.com:2260/;' },
        { n = 'Armonía Duero 1077 FM', u = 'http://s5.myradiostream.com:42840/listen.mp3' },
        { n = 'Arraio Irratia', u = 'http://irratia.arraio.eus:9001/irratia.ogg' },
        { n = 'Atlántico Radio 883 FM', u = 'https://streaming.atlanticoradio.es/atlanticoradio' },
        { n = 'Bakanos FM 970 - 971', u = 'https://stream.zeno.fm/cxmx1evtzwzuv' },
        { n = 'Bayradio Spain', u = 'https://securestreams2.autopo.st:1317/stream?1715088808599' },
        { n = 'BBN Spanish', u = 'https://streams.radiomast.io/475ebed1-595e-4717-b888-64fe8fc6b09f' },
        { n = 'Beach Grooves Radio', u = 'https://stream.beachgrooves.com:9000/;' },
        { n = 'Beachgrooves Radio', u = 'https://stream.beachgrooves.com:9000/stream' },
        { n = 'BENICARLO RADIO By Xopo', u = 'https://streaming.enacast.com/radiobenicarlo128.mp3' },
        { n = 'Berea FM 921', u = 'https://eu1.lhdserver.es:8039/stream' },
        { n = 'Bilbo Hiria Irratia', u = 'https://server8.emitironline.com:18392/stream' },
        { n = 'Blue Marlin Ibiza', u = 'https://ibizasonica.streaming-pro.com:8001/bluemarlin' },
        { n = 'Bohemia FM 931', u = 'http://5.135.183.124:8042/stream' },
        { n = 'Boom FM Granada 1038', u = 'http://streaming.elitecomunicacion.es:8086/;' },
        { n = 'Bside', u = 'https://flow.emisiononline.es/radio/8010/bside.aac' },
        { n = 'C DIAL Baladas', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL_03.mp3' },
        { n = 'C DIAL Latino', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL_02AAC_SC' },
        { n = 'Cadena 100', u = 'http://cadena100-streamers-mp3.flumotion.com/cope/cadena100.mp3' },
        { n = 'Cadena Dial', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL.mp3' },
        { n = 'Cadena Dial - Arahal', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/DIAL_ASO_MORON.mp3' },
        { n = 'Cadena Digital 978 FM', u = 'http://185.23.192.118:8006/;' },
        { n = 'CADENA JOVEN RADIO 1073 FM', u = 'https://antares.dribbcast.com/proxy/cadenajovenradio?mp=/stream' },
        { n = 'Cadena Mix FM', u = 'https://ns6.emisionlocal.com/proxy/radiomix?mp=/stream' },
        { n = 'Cadena SER', u = 'https://20073.live.streamtheworld.com/CADENASER_SC' },
        { n = 'Cadena Ser +', u = 'https://27953.live.streamtheworld.com/CADENASER_ALT1AAC.aac' },
        { n = 'Cadena Ser + Bilbao', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_BILBAO.mp3' },
        { n = 'Cadena Ser + Cadiz - 932 FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_CADIZ.mp3' },
        { n = 'Cadena Ser + Córdoba - 1020 FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_CORDOBA.mp3' },
        { n = 'Cadena Ser + Elche', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_ASO_ELCHE.mp3' },
        { n = 'Cadena Ser + Gandia', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_ASO_GANDIA.mp3' },
        { n = 'Cadena Ser + Granada', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_MAS_GRANADA.mp3' },
        { n = 'Cadena Ser + Madrid', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_MADRID.mp3' },
        { n = 'Cadena Ser + Sevilla', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_SEVILLA.mp3' },
        { n = 'Cadena Ser + Tenerife', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_TENERIFE.mp3' },
        { n = 'Cadena Ser + Valencia', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_VALENCIA.mp3' },
        { n = 'Cadena Ser - Las Palmas', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_LAS_PALMAS.mp3' },
        { n = 'Cadena Ser - Radio León', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_LEON.mp3' },
        { n = 'Cadena SER - Radio Morón', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_MORON.mp3' },
        { n = 'Cadena SER - Radio Valencia', u = 'http://provisioning.streamtheworld.com/pls/SER_VALENCIA.pls' },
        { n = 'Cadena SER - Radio Valladolid', u = 'https://25603.live.streamtheworld.com/SER_VALLADOLID_SC' },
        { n = 'Cadena SER - Radio Vigo', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_VIGO.mp3' },
        { n = 'Cadena SER - Radio Zamora', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_ZAMORA.mp3' },
        { n = 'Cadena SER - Ràdio Barcelona', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_BARCELONA.mp3' },
        { n = 'Cadena SER Almería 882 FM', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_ALMERIA.mp3' },
        { n = 'Cadena Ser Cartagena', u = 'https://23553.live.streamtheworld.com/SER_CARTAGENA.mp3' },
        { n = 'Cadena SER Extremadura', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_EXTREMADURAAAC.aac' },
        { n = 'Cadena Ser Guadix', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_GUADIXAAC_SC' },
        { n = 'Cadena Ser Haro Rioja Alta Radio Haro', u = 'http://streaming.capsulaimposible.com:8000/radioharo.mp3' },
        { n = 'Cadena Ser Mallorca', u = 'http://provisioning.streamtheworld.com/pls/SER_MALLORCA.pls' },
        { n = 'Cadena SER Málaga', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/SER_MALAGA.mp3' },
        { n = 'Cadena SER Pontevedra', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_PONTEVEDRA.mp3' },
        { n = 'Cadena SER Radio Ferrol', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_FERROL.mp3' },
        { n = 'Cadena SER Radio MADRID', u = 'http://server7.20comunicacion.com:8040/' },
        { n = 'Cadena SER Radio Menorca', u = 'http://server10.emitironline.com:8040/' },
        { n = 'Cadena SER Radio San Sebastián', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_PONTEVEDRAAAC.aac' },
        { n = 'Cadena SER Sevilla', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_SEVILLA.mp3' },
        { n = 'Cafe Del Mar Channel 2', u = 'https://s4.radio.co/seeae9c220/listen' },
        { n = 'Cafe Mambo Ibiza Radio', u = 'http://streamer.radio.co/sd7b28e5f3/listen' },
        { n = 'Café Del Mar', u = 'https://streams.radio.co/se1a320b47/listen' },
        { n = 'Calafell Ràdio', u = 'http://streaming.enantena.com:8000/calafellradio128.mp3?_=1' },
        { n = 'Calimbre Radio', u = 'https://control.streaming-pro.com:6048/stream' },
        { n = 'Canal 4 Tenerife', u = 'https://panel5.soydigital.fm/8024/live' },
        { n = 'Canal Axarquía 896 FM', u = 'http://radioserver11.profesionalhosting.com:9177/live' },
        { n = 'Canal Ebro Radio', u = 'http://streaming.capsulaimposible.com:8000/stream/2/canalebro.mp3' },
        { n = 'Canal Metropol 1026 FM', u = 'https://radioserver11.profesionalhosting.com/proxy/pkg78607?mp=/stream' },
        { n = 'Candela Radio 914 FM', u = 'https://radio.streamenginelogin.com:8002/stream' },
        { n = 'Candil Radio', u = 'https://candilradio.com/liveradio/candil/live.mp3' },
        { n = 'Cantabria FM 899', u = 'http://stream.zeno.fm/jndgdm0esn9vv' },
        { n = 'Carrusel FM', u = 'http://server6.20comunicacion.com:8921/;' },
        { n = 'Castro Punto Radio 882 FM', u = 'https://server8.emitironline.com:10891/;' },
        { n = 'Catalunya Informació Catinfo', u = 'https://shoutcast.ccma.cat/ccma/catalunyainformacioHD.mp3' },
        { n = 'Catalunya Música Catmúsica', u = 'https://shoutcast.ccma.cat/ccma/catalunyamusicaHD.mp3' },
        { n = 'Catalunya Radio', u = 'https://shoutcast.ccma.cat/ccma/catalunyaradioHD.mp3' },
        { n = 'Chanquete FM 995', u = 'http://185.23.192.118:8008/;' },
        { n = 'Chocolate FM', u = 'http://streaming5.elitecomunicacion.es:8082/live.mp3' },
        { n = 'Chocolate FM [Calidad Móvil-Low Bandwidth]', u = 'http://streaming5.elitecomunicacion.es:8082/live32.aac' },
        { n = 'Chocolate FM HD', u = 'http://streaming5.elitecomunicacion.es:8030/live.mp3' },
        { n = 'Classic Old Time Radio', u = 'http://stream.zeno.fm/b6v6nu8uhnruv' },
        { n = 'Closta Blanca Radio', u = 'http://stream.costablancaradio.nl/costablancaradio' },
        { n = 'Color Estéreo 1037 FM', u = 'https://azura5.emisiononline.es/listen/colorestereo/radio.mp3' },
        { n = 'Colsub-Lounge', u = 'http://stream.exeamedia.com:5086/Colsub-lounge' },
        { n = 'COPE + Sevilla', u = 'http://wecast09-h-cloud.flumotion.com/copesedes/sevilla-mas.mp3' },
        { n = 'Cope Carballiño', u = 'http://radio.copecarballino.es:8000/directo.mp3' },
        { n = 'Costa Del Mar - Chillout AAC 96Kbps', u = 'http://stream.cdm-chillout.com:8020/stream-AAC-Chill' },
        { n = 'Costa Del Mar Smooth Jazz', u = 'https://radio4.cdm-radio.com:18024/stream-mp3-Smooth' },
        { n = 'CUAC FM MP3', u = 'https://streaming.cuacfm.org/cuacfm-128k.mp3' },
        { n = 'Dance Wave Retro', u = 'https://retro.dancewave.online/retrodance.flac.ogg' },
        { n = 'Das Inselradio Malorca', u = 'https://addrad.io/445fxk9' },
        { n = 'Decada FM 1001', u = 'http://streaming5.elitecomunicacion.es:8230/;' },
        { n = 'Decibelia FM', u = 'https://streaming.shoutcast.com/decibelia' },
        { n = 'Digital Hits FM', u = 'https://dhits.frilab.com:8443/dhits' },
        { n = 'DISCO MUSIC RADIO', u = 'https://discomusicradio.com:8100/;' },
        { n = 'Distinta FM SANTANDER - CANTABRIA896LLUCMAJOR - MALLORCA1079', u = 'http://ns100.emisionlocal.com:8050/;stream.mp3' },
        { n = 'DMT-FM - EU Server 320K', u = 'https://dc1.serverse.com/proxy/ywycfrxn/live' },
        { n = 'Dos FM Radio 977 1010', u = 'https://control.streaming-pro.com:8008/stream' },
        { n = 'Dublab BCN', u = 'https://dublabbcn.out.airtime.pro/dublabbcn_a' },
        { n = 'Dunas FM 944 Y 942', u = 'https://sonic.mediatelekom.net/8424/stream/;' },
        { n = 'Dynamis Radio 875 FM Madrid', u = 'https://control.streaming-pro.com:8014/stream' },
        { n = 'Ecuashyri Radio 1037 FM', u = 'http://streaming.hdserver.biz:9336/;/stream' },
        { n = 'Efecto FM 890Mhz', u = 'http://directo.efectofm.es:19000/;' },
        { n = 'EITB Irratia', u = 'http://mp3-eitb.stream.flumotion.com/eitb/eitbmusika.mp3' },
        { n = 'Eixample Barcelona Radio', u = 'https://directe.eixamplebarcelonaradio.com:8443/radioOnline' },
        { n = 'El 9 FM', u = 'http://radio.el9fm.cat:8000/stream' },
        { n = 'El Salto Radio', u = 'https://radio.radiobot.org/listen/salto/elsaltoradio.mp3' },
        { n = 'Electrodanceworld Radio', u = 'http://stream.zeno.fm/s70bvdgqks8uv' },
        { n = 'Elite Radio Guadix', u = 'https://streaming2.elitecomunicacion.es:2199/tunein/eliteguadix.pls' },
        { n = 'Eme Radio', u = 'https://streaming.enacast.com/emeradiofmHD.mp3' },
        { n = 'ENERGIA FM - CARAVACA DE LA CRUZ 900', u = 'http://streaming5.elitecomunicacion.es:8128/caravaca?type=.mp3' },
        { n = 'Energía Flamenca', u = 'https://axarquia.emisiononline.es/radio/8020/radio.mp3' },
        { n = 'Energía Vintage', u = 'https://axarquia.emisiononline.es/radio/8000/radio.mp3' },
        { n = 'Es Mi Radio', u = 'http://streaming.elitecomunicacion.es:8038/live' },
        { n = 'Escuela Abierta FM 1075', u = 'http://streaming.elitecomunicacion.es:8042/;' },
        { n = 'Espacio4Fm', u = 'https://stream-64.zeno.fm/fz0bc82wn0hvv?zs=KXaURSY1Roe-rptKdjdkkw' },
        { n = 'Espana Network', u = 'https://cast3.asurahosting.com/proxy/paolo/stream' },
        { n = 'Esplugues FM', u = 'https://antares.dribbcast.com/proxy/espluguesfm?mp=/stream' },
        { n = 'Esradio', u = 'http://livestreaming.esradio.fm/stream64.mp3' },
        { n = 'Esradio AAC HQ', u = 'https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-high.aac' },
        { n = 'Esradio Asturias', u = 'http://server9.emitironline.com:8822/radio' },
        { n = 'Esradio Galicia', u = 'https://libertaddigital-radio-live2.flumotion.com/libertaddigital/ld-live2-low.mp3' },
        { n = 'Esradio Granada', u = 'https://azura.abcorp.es/listen/esradio_granada/radio.mp3' },
        { n = 'Esradio Madrid', u = 'https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-med.aac' },
        { n = 'Esradio MP3 HQ', u = 'https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-high.mp3' },
        { n = 'Esradio Principal', u = 'https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-low.mp3' },
        { n = 'Esradio Sevilla', u = 'https://libertaddigital-radio-live3.flumotion.com/libertaddigital/ld-live3-low.aac' },
        { n = 'Esradio Tenerife', u = 'https://panel5.soydigital.fm/8024/live?1678446871465' },
        { n = 'Esradioaac', u = 'http://livestreaming9.esradio.fm/aaclive32' },
        { n = 'Essere Web Radio', u = 'https://nr9.newradio.it/proxy/essereas?mp=/stream?ext=.mp3' },
        { n = 'Estéreo Latino 1038 FM', u = 'http://server3.20comunicacion.com:8028/;' },
        { n = 'Europa FM Guipuzcoa', u = 'https://stream.zeno.fm/se76qau1hc9uv' },
        { n = 'Euskadi Irratia', u = 'http://mp3-eitb.stream.flumotion.com/eitb/euskadiirratia.mp3' },
        { n = 'Exito Radio', u = 'http://5.135.183.124:9252/stream' },
        { n = 'Feel Good Radio Costa Del Sol', u = 'https://caster05.streampakket.com/proxy/8321/stream' },
        { n = 'Felove Biblia En Español', u = 'http://radio.produccionescasaverde.com:8696/autodj' },
        { n = 'Fiebre Latina Radio 966 FM', u = 'https://eu1.lhdserver.es:9035/stream' },
        { n = 'FIESTA FM LEVANTE - ALICANTE 88,4 ELCHE 952', u = 'http://cdn4.onstream.audio:9181/stream' },
        { n = 'Flaix FM', u = 'https://stream.flaixfm.cat/icecast' },
        { n = 'FORMULA 10 MUSICA', u = 'https://formula10musica.stream.laut.fm/formula10musica' },
        { n = 'Formula 30', u = 'http://stm1.emiteonline.com:8001/formula30' },
        { n = 'Fred Film Radioespañol', u = 'https://s10.webradio-hosting.com/proxy/fredradiosp/stream' },
        { n = 'Free FM 80S San Francisco', u = 'https://freefm80.radioca.st/' },
        { n = 'Free FM Chill New York', u = 'https://freefmchill.radioca.st/' },
        { n = 'Free FM Classical', u = 'https://stream.zeno.fm/x5jlpogsaedvv' },
        { n = 'Free FM Classics', u = 'https://xxdelgado.radioca.st/' },
        { n = 'Free FM Love', u = 'http://stream.zeno.fm/umsptm6rvy8uv' },
        { n = 'Free FM Madrid', u = 'https://rocafmadrid.radioca.st/stream' },
        { n = 'Free FM New York', u = 'https://rocafmadrid.radioca.st/' },
        { n = 'Free FM Sports', u = 'https://stream.zeno.fm/31nnibfpnxktv' },
        { n = 'Free FM Top 100', u = 'http://stream.zeno.fm/a5h7vfret68uv' },
        { n = 'Funky Corner Radio Spain', u = 'https://ais-sa2.cdnstream1.com/2447_96.aac' },
        { n = 'FUNKY TRACKS RADIO Barcelona', u = 'http://streaming2.elitecomunicacion.es:8134/stream' },
        { n = 'FÓRMULA FUN', u = 'https://s30.myradiostream.com/30464/listen.mp3' },
        { n = 'Gaztea Irratia', u = 'http://mp3-eitb.stream.flumotion.com/eitb/gaztea.mp3' },
        { n = 'Gente Radio', u = 'https://pr1cen101.emisionlocal.com/proxy/genteradio?mp=/live' },
        { n = 'Giralda FM', u = 'https://server1.radiocast.es/listen/radio_giralda/giraldaweb' },
        { n = 'Gladys Palmera Coleccion', u = 'http://streams.radio.co/s496c4d2e8/listen' },
        { n = 'Gladys Palmera Latin Fresh', u = 'https://streamer.radio.co/s00c7ec6fa/listen' },
        { n = 'Gladys Palmera Radio Online', u = 'http://streamer.radio.co/sb28a7fb81/listen' },
        { n = 'Globo FM', u = 'http://sonic.sistemahost.es:8200/' },
        { n = 'Gracia Celestial', u = 'https://stream4.305stream.com:9463/stream' },
        { n = 'HAPPYFM - FUERTEVENTURA', u = 'https://control.streaming-pro.com:6003/live' },
        { n = 'Happyfm-Fuerteventura', u = 'https://happyfuerteventura.streaming-pro.com:6003/live' },
        { n = 'Hit FM', u = 'https://adhandler.kissfmradio.cires21.com/get_link?url=https://bbhitfm.kissfmradio.cires21.com/bbhitfm.mp3' },
        { n = 'Hit FM', u = 'https://adhandler.kissfmradio.cires21.com/get_link?url=https://bbhitfm.kissfmradio.cires21.com/bbhitfm.mp3' },
        { n = 'Hit Radio', u = 'http://stm1.emiteonline.com:8004/hitelgrado' },
        { n = 'Hits 1 Ibiza', u = 'https://player.ibiza.hits1radio.com/' },
        { n = 'Hits1', u = 'https://player.hd.hits1radio.com/' },
        { n = 'Hitz 90S FM', u = 'https://stream.zeno.fm/1q3dwmd6yf8uv' },
        { n = 'Hitz Latino FM', u = 'http://stream.zeno.fm/aq899a53rs8uv' },
        { n = 'Hola 957 FM 1 Costa Calma', u = 'http://5.135.183.124:8207/stream' },
        { n = 'Holiday Gym FM', u = 'http://holidaygym.emitironline.com/' },
        { n = 'IB3 Ràdio Mallorca', u = 'https://icecast.ib3radio.com/ib3radio.mp3' },
        { n = 'IB3 Ràdio Menorca', u = 'http://streaming01.ib3radio.com:8000/ib3radio_menorca' },
        { n = 'IBI RADIO By Xopo', u = 'https://streaming.enacast.com/radioibiSD.mp3' },
        { n = 'Ibiza 1', u = 'https://stream.ibiza1.hits1radio.com/' },
        { n = 'Ibiza Global Classics', u = 'https://control.streaming-pro.com:8000/ibizaglobalclassics.mp3' },
        { n = 'Ibiza Global Radio', u = 'http://ibizaglobalradio.streaming-pro.com:8024/' },
        { n = 'Ibiza Relax', u = 'http://54.38.43.201:8036/stream-128kmp3-IbizaRelax' },
        { n = 'Ibiza Sonica', u = 'https://ibizasonica.streaming-pro.com:8000/ibizasonica' },
        { n = 'Ibiza Sonica Club', u = 'https://ibizasonica.streaming-pro.com:8011/sonicaclub' },
        { n = 'Ibiza Sonicalm', u = 'https://ibizasonica.streaming-pro.com:8014/sonicalm' },
        { n = 'Ibiza Stardust Radio', u = 'https://www.radioking.com/play/ibiza-stardust-radio-1' },
        { n = 'Icat FM', u = 'https://shoutcast.ccma.cat/ccma/icatHD.mp3' },
        { n = 'Ilovemusicradio', u = 'https://streams.ilovemusic.de/iloveradio36.mp3' },
        { n = 'INFORMA RADIO', u = 'https://24x7.red:42045/informa' },
        { n = 'Inolvidable FM', u = 'https://uk1.streamingpulse.com/ssl/inolvidablefm' },
        { n = 'Inselradio Mallorca', u = 'http://addrad.io/445fxk9' },
        { n = 'Interradio Tenerife', u = 'https://server8.emitironline.com:8200/;' },
        { n = 'Intimidad Relax', u = 'https://eu1.lhdserver.es:9121/stream' },
        { n = 'Jazz Radio Bcn', u = 'http://stream.zeno.fm/u40kkya8hg8uv' },
        { n = 'Jazz Radio Spain', u = 'https://stream.tunerplay.com/radio/8020/jazzradiospain.mp3' },
        { n = 'Jose Antonio Ruiz Garcíaº', u = 'https://radiobot.radioslibres.info/listen/radio_almaina/radio.mp3' },
        { n = 'KISS FM', u = 'https://adhandler.kissfmradio.cires21.com/get_link?url=https://bbkissfm.kissfmradio.cires21.com/bbkissfm.mp3' },
        { n = 'Kiss FM España', u = 'https://live.kissfm.ro/kissfm.aacp' },
        { n = 'Kiss Music FM', u = 'https://stream.zeno.fm/aq899a53rs8uv' },
        { n = 'Kiss-Fm Madrid', u = 'https://kissfm.kissfmradio.cires21.com/kissfm.mp3' },
        { n = 'La Clave Stereo 936', u = 'https://stream.integracionvirtual.com/proxy/laclavestereo?mp=/stream' },
        { n = 'La Cuarta FM', u = 'http://radio.amgroupmkt.com:1050/stream' },
        { n = 'La Disco Radio', u = 'https://sonic.sistemahost.es/8086/stream;' },
        { n = 'La Flamenca', u = 'https://stream.emisorasmusicales.net/listen/la_flamenca/laflamenca.mp3' },
        { n = 'La Fresca FM', u = 'http://stream.produccionesdale.com:8899/moviles' },
        { n = 'LA KALLE 888 FM', u = 'https://icecasthd.net/proxy/lakalle/lakalle' },
        { n = 'La Mega', u = 'https://stream.emisorasmusicales.net/listen/la_mega/lamega.mp3' },
        { n = 'La Mega Estación', u = 'https://eu1.lhdserver.es:9049/stream?1630947253320' },
        { n = 'La Mega Radio', u = 'http://streaming2.elitecomunicacion.es:8220//stream?type=.mp3' },
        { n = 'La Plana Ràdio', u = 'https://enacast.com/laplanaradio/streams/HD' },
        { n = 'La Urban Radio', u = 'https://st1.urbanrevolution.es:8443/laurbanfm.mp3' },
        { n = 'Ladiez', u = 'https://panel5.soydigital.fm/8030/stream' },
        { n = 'Lleida Radio Ua1 1045 FM', u = 'https://panel5.soydigital.fm/8032/stream' },
        { n = 'Loca FM', u = 'https://s3.we4stream.com:2020/stream/locafm' },
        { n = 'Loca FM 80S', u = 'http://s02.fjperezdj.com:8075/live' },
        { n = 'Loca FM Ambient', u = 'http://s02.fjperezdj.com:8036/live' },
        { n = 'Loca FM Chillout', u = 'http://s02.fjperezdj.com:8006/live' },
        { n = 'LOCA FM DANCE', u = 'http://s02.fjperezdj.com:8025/live' },
        { n = 'Loca FM Deep Techno', u = 'http://s02.fjperezdj.com:8066/live' },
        { n = 'LOCA FM House', u = 'http://s02.fjperezdj.com:8026/live' },
        { n = 'Loca FM Industrial', u = 'http://s02.fjperezdj.com:8076/live' },
        { n = 'Loca FM Live', u = 'http://s3.we4stream.com:8045/liv' },
        { n = 'LOCA FM Techhouse', u = 'http://s02.fjperezdj.com:8046/live' },
        { n = 'LOCA FM Techno', u = 'http://s02.fjperezdj.com:8050/live' },
        { n = 'Loca FM Urban', u = 'http://locafm02.we4stream.com:8015/live' },
        { n = 'Loca Progressive House', u = 'https://s02.fjperezdj.com:8056/live?listening-from-radio-garden=1647634146' },
        { n = 'Locafm Melodic Deep', u = 'http://s02.fjperezdj.com:8056/live' },
        { n = 'LOCAFM REMEMBER', u = 'http://s02.fjperezdj.com:8035/live' },
        { n = 'Lola Fm', u = 'https://srv7031.dns-lcinternet.com/8096/stream' },
        { n = 'Los 40 Catalunya', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CAT_SC' },
        { n = 'LOS 40 Classic', u = 'https://25633.live.streamtheworld.com/LOS40_CLASSIC.mp3' },
        { n = 'Los 40 Dance', u = 'http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_DANCE_SC' },
        { n = 'LOS 40 Principales España', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/Los40.mp3' },
        { n = 'Los 40 Sur', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_ASO_MORON.mp3' },
        { n = 'Los 40 Urban', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_URBAN.mp3' },
        { n = 'Los Megaexitos', u = 'https://losmegaexitos.radioca.st/lms' },
        { n = 'LOS40 Classic', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CLASSIC.mp3' },
        { n = 'Lounge Radio Ibiza', u = 'https://stream.laut.fm/lounge-radio-ibiza' },
        { n = 'LOVE RADIO - Loveradio', u = 'https://loveradio.streamingmedia.it/espana' },
        { n = 'Mad Radio Barcelona', u = 'https://c2.radioboss.fm/stream/588' },
        { n = 'Makina Fm', u = 'https://stream.zeno.fm/roqewn7dp4gtv' },
        { n = 'Makina Fm 1067', u = 'https://stream-155.zeno.fm/roqewn7dp4gtv?zs=pHT3yBVRSCuhAS6RsOSNiQ' },
        { n = 'Mallorca Sunshine Radio', u = 'https://mallorcasunshine--di--nacs-ais-lgc--05--cdn.cast.addradio.de/mallorcasunshine/live/mp3/high' },
        { n = 'Mambo Radio', u = 'https://streamer.radio.co/sd7b28e5f3/listen' },
        { n = 'Marca Valladolid', u = 'https://radiomarcavalladolid.streaming-pro.com:6106/radiomarca.mp3' },
        { n = 'Marea FM', u = 'https://sonic.mediatelekom.net/9016/stream' },
        { n = 'Mediterrani FM Barcelona', u = 'https://listen1.myradio24.com/37511' },
        { n = 'Megastar FM', u = 'https://megastar-cope-rrcast.flumotion.com/cope/megastar.mp3' },
        { n = 'Mi Amigo Radio, De Échte', u = 'https://stan319bisbis.radioca.st/stream' },
        { n = 'Misterio FM', u = 'https://stream-38.zeno.fm/zr1ntv61fchvv?zs=B6YIARuRSaujjyuQoZxg0g' },
        { n = 'Mix Radio Gran Canaria', u = 'https://mixfm.radionetz.de/mixfm.mp3' },
        { n = 'Mix80Radio', u = 'https://stream.tunerplay.com/radio/8040/radio.mp3' },
        { n = 'Monster Radio', u = 'https://monster.canarysat.eu/monster' },
        { n = 'Montserrat Ràdio', u = 'https://enacast.com/radioabadiademontserrat/streams/HD' },
        { n = 'Mortalfm', u = 'http://server6.20comunicacion.com:8044/;' },
        { n = 'Mucho Baile', u = 'https://str1.mediatelekom.net/proxy/muchobaileradio/stream' },
        { n = 'Multicanal Radio', u = 'https://a2.asurahosting.com:8800/radio.mp3' },
        { n = 'Musicbox', u = 'http://stm1.emiteonline.com:8025/musicbox' },
        { n = 'Muy Buena Valencia', u = 'https://stream.emisorasmusicales.net/listen/muybuena/muybuena.mp3' },
        { n = 'Naiz: Irratia', u = 'https://zuzenean.naiz.eus/naiz_irratia.mp3' },
        { n = 'Nostalgia', u = 'https://azura.abcorp.es/listen/nostalgia/live' },
        { n = 'Ona Malgrat', u = 'http://streaming.enantena.com:8000/onamalgrat128.mp3' },
        { n = 'Ona Mediterrània', u = 'https://enacast.com/onamediterrania/streams/HD' },
        { n = 'Onda 10', u = 'https://stream.laut.fm/onda10' },
        { n = 'Onda 80 Radio Bellvitge', u = 'https://antares.dribbcast.com/proxy/onda80/stream' },
        { n = 'Onda Aragonesa', u = 'http://eu1.lhdserver.es:9046/stream' },
        { n = 'Onda Aranjuez', u = 'http://server8.emitironline.com:18544/stream' },
        { n = 'Onda Cero Cinca', u = 'https://sonando-us.digitalproserver.com/litera.aac' },
        { n = 'Onda Digital Fm Guadalajara', u = 'http://radio.serviciosderadio.com:8060/radio.mp3' },
        { n = 'Onda Musical De Yecla', u = 'https://stream.zeno.fm/89t31p4mdwzuv' },
        { n = 'Onda Torrente Radio', u = 'http://5.135.183.124:8073/stream' },
        { n = 'Onda Vasca', u = 'http://www.ondavasca.com:8000/bizkaia' },
        { n = 'Onda Vasca Gipuzkoa', u = 'http://www.ondavasca.com:8000/gipuzkoa' },
        { n = 'Onda Wantuki', u = 'https://stream.zeno.fm/5dfkzqm70s8uv' },
        { n = 'Ondamar80', u = 'https://antares.dribbcast.com/proxy/ondamar80?mp=/live' },
        { n = 'Only Romantic Radio', u = 'https://stream.laut.fm/only-romantic-radio' },
        { n = 'Openlab Radio', u = 'https://ice04.fluidstream.net/openlab.mp3' },
        { n = 'Oro', u = 'http://185.23.192.118:8002/;' },
        { n = 'Otaku Musicradio', u = 'http://kathy.torontocast.com:2880/listen.pls?sid=1' },
        { n = 'Passion Ibiza Radio', u = 'https://www.radioking.com/play/passion-ibiza-radio1/485588' },
        { n = 'Pepe Radio', u = 'http://server10.emitironline.com:8032/' },
        { n = 'Perfect Deep House', u = 'https://stream.radiojar.com/asngk2sg798uv?1659885393' },
        { n = 'Play Trance Radio Uplifting Only Channel High Quality', u = 'https://streaming.playtrance.com/playtrance-uplifting-high' },
        { n = 'Playfm', u = 'http://radioplaneta.emitironline.com:8000/' },
        { n = 'Playtrance Radio - Main Channel', u = 'https://live-ff.playtrance.com/playtrance-main.mp3' },
        { n = 'Pontevedra Viva', u = 'https://server8.emitironline.com:9402/radio' },
        { n = 'Punk', u = 'https://punkirratia.net:8443/punk' },
        { n = 'Punt 7 Ràdio', u = 'https://enacast.com/punt7radiosantceloni/streams/HD' },
        { n = 'Pure Ibiza Radio', u = 'https://pureibizaradio.clubbingradios.com:9518/PureIbizaRadio' },
        { n = 'Qfm', u = 'http://51.255.235.165:5092/;' },
        { n = 'RAC1', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RAC_1.mp3' },
        { n = 'RAC1 +1', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RAC_MES_1.mp3' },
        { n = 'RAC105', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RAC105.mp3' },
        { n = 'Radio 1 Hits 90S', u = 'http://c4.auracast.net:8050/stream' },
        { n = 'Radio 4G', u = 'http://sergiobastida.es:8000/radio4gmurcia' },
        { n = 'Radio 5 RNE Córdoba', u = 'https://f141.rndfnk.com/star/crtve/rne5/cor/aac/128/stream.aac?cid=01GEPXCEBXZ55V5Q46BA5MKGQJ&sid=2Ijj8gOaUIfAlXbKakMiT1ah6Uk&token=EltrTn6HzLi0eEmfDXHoz0vVYnz6083DqWp5D3DcZfo&tvf=hjpV5gOaLxdmMTQxLnJuZGZuay5jb20' },
        { n = 'Radio 90', u = 'http://giss.tv:8000/r90.mp3' },
        { n = 'Radio 90 FM Valencia', u = 'http://stream.radio90.fm:2000/ios' },
        { n = 'Radio Agueda', u = 'http://str1.mediatelekom.net:8736/live' },
        { n = 'Radio Almaina 64Kbps', u = 'https://radiobot.radioslibres.info/public/radio_almaina/playlist.pls' },
        { n = 'Radio Aspe', u = 'http://streaming.enantena.com:8000/radioaspe128.mp3' },
        { n = 'Radio Ateos De Barcelona', u = 'https://servidor25.brlogic.com:7054/live' },
        { n = 'Radio Averroes', u = 'http://streamer.flexitech.se:8080/radioa' },
        { n = 'Radio Balear 999 Palma De Mallorca', u = 'http://server6.20comunicacion.com:8076/' },
        { n = 'Radio Balkoning', u = 'http://radio.123automate.it/balkoning' },
        { n = 'Radio Bilbao SER', u = 'https://25553.live.streamtheworld.com/SER_BILBAO.mp3' },
        { n = 'RADIO BOB', u = 'https://streams.radiobob.de/bob-national/mp3-192/homepage?mode=preroll&cb=286873666' },
        { n = 'Radio Bolero Alcoy 977 FM', u = 'https://romanticafm.radioca.st/' },
        { n = 'Radio Brand', u = 'https://radiobrand.es:8084/RadioBrand' },
        { n = 'Radio Cadena Stereo España', u = 'http://stream.zeno.fm/kpe30u471mruv' },
        { n = 'Radio Calima', u = 'https://escucha.calima.fm/stream' },
        { n = 'Radio Callao Madrid', u = 'https://server8.emitironline.com:18176/stream' },
        { n = 'Radio Carrizal', u = 'http://streaming.enantena.com:8000/radiocarrizal128.mp3' },
        { n = 'Radio Casares', u = 'http://srv0435.lcinternet.com:9507/stream' },
        { n = 'Radio Castelldefels', u = 'https://streaming.enacast.com/radiocastelldefels128.mp3' },
        { n = 'Radio Crónicas Folk', u = 'http://antares.dribbcast.com/proxy/rcfm?mp=/stream' },
        { n = 'Radio Del Hogar De La Brisa', u = 'http://stream.zeno.fm/4vwgvyq82k8uv' },
        { n = 'Radio Disco Melodia FM', u = 'https://sonic.mediatelekom.net/8020/stream' },
        { n = 'Radio El Palmar', u = 'http://topradio.one:8027/autodj' },
        { n = 'Radio España', u = 'https://stream.zeno.fm/7ywx2u45vv8uv' },
        { n = 'Radio España - Directo', u = 'http://stream.zeno.fm/ocinyyji4rntv' },
        { n = 'Radio Esport Valencia', u = 'https://streaming.radioesport914.com:58000/stream' },
        { n = 'Radio Esquina', u = 'http://argentina.republicahosting.com:8138/stream' },
        { n = 'Radio Europa', u = 'https://server9.emitironline.com:19144/' },
        { n = 'Radio Euskadi', u = 'http://mp3-eitb.stream.flumotion.com/eitb/radioeuskadi.mp3' },
        { n = 'Radio Faro De Gracia', u = 'https://radiorfg.com/listen/radio_faro_de_gracia/radio.mp3' },
        { n = 'Radio Filispim', u = 'https://streaming.cuacfm.org/filispim.mp3' },
        { n = 'Radio Guiniguada', u = 'https://stream.zeno.fm/49c0fmrwhrhvv' },
        { n = 'Radio Hogar De La Brisa', u = 'http://stream.zeno.fm/ra4a8ebe0rhvv' },
        { n = 'Radio Hora', u = 'https://s5.radio.co/s58f5759a4/listen' },
        { n = 'Radio Humor FM', u = 'https://stream.radiohumorfm.com/stream' },
        { n = 'Radio Intercontinental - Madrid', u = 'https://cast5.servcast.net/proxy/inter/stream' },
        { n = 'Radio Jesus', u = 'https://paginas.moisespaulino.com/proxy/radiojesus/stream' },
        { n = 'Radio La Roda', u = 'http://94.76.165.97:9830/;stream.mp3' },
        { n = 'Radio Laredo', u = 'https://radio.radiolaredo.com/8002/strem' },
        { n = 'Radio Libertad', u = 'https://server9.emitironline.com:19482/stream?cb=1708722000350' },
        { n = 'Radio Linguas', u = 'https://radiolinguas.eu:8001/radiolinguas' },
        { n = 'Radio Líder', u = 'http://server9.emitironline.com:8200/stream' },
        { n = 'Radio Líder Santiago', u = 'https://server8.emitironline.com:18520/stream' },
        { n = 'Radio Maktub NJ', u = 'http://str1.mediatelekom.net:8077/live' },
        { n = 'RADIO MARCA', u = 'https://25633.live.streamtheworld.com/RADIOMARCA_NACIONAL.mp3' },
        { n = 'Radio MARCA Asturias', u = 'https://streaming.enacast.com/radiomarcaasturiasHD.mp3' },
        { n = 'Radio Marca Madrid', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOMARCA_NACIONAL_SC' },
        { n = 'Radio Marca Malaga', u = 'https://malagafm.streaming-pro.com:8131/malagafmmobile' },
        { n = 'Radio Marca Málaga', u = 'http://malagafm.streaming-pro.com:8130/malagafmmobile' },
        { n = 'Radio Maria Spain Espana', u = 'http://dreamsiteradiocp.com:8060/;stream.mp3' },
        { n = 'Radio Marina Blanes', u = 'https://streaming.enacast.com/radiomarina128.mp3' },
        { n = 'RADIO MARÍA ESPAÑA', u = 'http://dreamsiteradiocp2.com:8006/stream' },
        { n = 'Radio Matorral', u = 'https://topradio.uno/proxy/radiomatorral/stream' },
        { n = 'Radio Mi Amigo International', u = 'https://procyon.shoutca.st:2199/tunein/rmai.pls' },
        { n = 'Radio Molins', u = 'https://enacast.com/radiomolinsderei/streams/HD' },
        { n = 'Radio Monteolivete', u = 'http://online.monteolivete.org:8030/stream' },
        { n = 'Radio Moscatel 1071 FM Axarquía - España', u = 'https://axarquia.emisiononline.es/radio/8040/radio.mp3' },
        { n = 'Radio Nacional De España - Radio 5 Todo Noticias', u = 'https://d131.rndfnk.com/star/crtve/rne5/main/mp3/128/stream.mp3?aggregator=tunein&cid=01GEP4MW5CAHPYP1EXHVKWFJ8W&sid=2OeE42hivuba6dTGvjnMGjKByQe&token=cdczXcnimVx4AY4iamqYbTMdu3cK7oBxmS2UQN9cWc0&tvf=pdPcDBxuVxdkMTMxLnJuZGZuay5jb20' },
        { n = 'Radio Nacional De España - Radio Clasica', u = 'https://f141.rndfnk.com/star/crtve/rnerc/main/mp3/128/stream.mp3?cid=01GEM633TKTAHEB3GYTNAEZB90&sid=2OeEj3cbhDQiZQY1d3kTqQyea1Y&token=cHn_jT-26Z0rPqXMo0QMJUWS-2ZjHiwAiKVk3Y_JrX4&tvf=IU7TAmhuVxdmMTQxLnJuZGZuay5jb20' },
        { n = 'Radio Nature', u = 'https://stream.zeno.fm/3ac97ysh6f0uv.aac' },
        { n = 'Radio Nervión', u = 'https://gruponervion.streaming-pro.com:6131/' },
        { n = 'Radio Nostalgia Spain', u = 'http://streamingv2.shoutcast.com/nostalgiaspain' },
        { n = 'Radio Oro Marbella', u = 'http://185.23.192.118:8004/;stream.mp3' },
        { n = 'Radio Palafolls', u = 'http://streaming.enantena.com:8000/radiopalafolls128.mp3' },
        { n = 'Radio Pineda 946', u = 'https://streaming.enacast.com/radiopineda56.mp3' },
        { n = 'Radio Planeta', u = 'http://radioplaneta.emitironline.com/radio' },
        { n = 'Radio Planeta Costa Del Sol', u = 'https://radioplaneta.emitironline.com/radio' },
        { n = 'Radio Popular', u = 'https://stream.mediasector.es/listen/radio_popular/radiopopular.mp3' },
        { n = 'Radio Popular Herri Irratia - Bilbao', u = 'http://79.137.33.224/radiopopular2' },
        { n = 'Radio Radio Network', u = 'http://radioradio.es:8000/listen.pls' },
        { n = 'Radio Relativa', u = 'https://streamer.radio.co/sd6131729c/listen' },
        { n = 'Radio Remember Last', u = 'https://node-25.zeno.fm/5nvz43btqg8uv?rj-ttl=5&rj-tok=AAABd24dwXQAYQSRcz9whBAeXA' },
        { n = 'Radio Sefarad', u = 'https://www2.radiosefarad.com/joomla/images/mp3/sefaradparaweb.mp3' },
        { n = 'Radio Sevillanas', u = 'http://radio.wesped.com:8000/stream' },
        { n = 'Radio Sin Barreras', u = 'https://live.radiosinbarreras.com/radio/8020/stream' },
        { n = 'Radio Sintonia', u = 'https://eu1.lhdserver.es:8055/stream' },
        { n = 'Radio Sitges', u = 'https://s2.radio.co/s8e5dffe5e/listen' },
        { n = 'Radio Todo Exitos', u = 'http://cervera.eldialdigital.com:7999/autodj' },
        { n = 'Radio Tomares', u = 'http://stream1.aljamir.com:8174/stream.mp3' },
        { n = 'Radio Topo', u = 'https://radiobot.radioslibres.info/radio/8060/radio.mp3' },
        { n = 'Radio Universidad De Navarra 983 FM', u = 'https://s2.radio.co/sb23429e9f/listen' },
        { n = 'Radio Unión Catalunya', u = 'http://srv0435.lcinternet.com:9522/stream' },
        { n = 'Radio Vallekas', u = 'https://radio.radiobot.org/listen/rvk/rvk.mp3' },
        { n = 'Radio Vila-Real', u = 'http://www.radiovila-real.es/player/?pl=vlc&c=Radio VIla-real 92.2 Fm' },
        { n = 'Radio Vilafant', u = 'https://sonic.mediatelekom.net/9986/stream' },
        { n = 'Radio Vilasound Ibiza 927 FM', u = 'https://s9.citrus3.com:8174/stream' },
        { n = 'Radio Villaba', u = 'https://srv7041.dns-lcinternet.com/8042/stream' },
        { n = 'Radio Villena', u = 'https://25603.live.streamtheworld.com/SER_VILLENA.mp3' },
        { n = 'Radio Voz A Coruña', u = 'https://live.radiovoz.es/mp3/stream_coruna.mp3' },
        { n = 'Radio90 FM Valencia', u = 'https://stream.radio90.fm:2002/web' },
        { n = 'Radiocable', u = 'https://radio.radiobot.org/listen/radiocable/radio.mp3' },
        { n = 'RADIOLE España', u = 'https://20043.live.streamtheworld.com/RADIOLE.mp3' },
        { n = 'Radiolé', u = 'https://provisioning.streamtheworld.com/pls/RADIOLEAAC.pls' },
        { n = 'Radiomv Spanish', u = 'https://ice.radiomv.co:8440/spanish.mp3' },
        { n = 'Radios Libres', u = 'https://radiobot.radioslibres.info/listen/radio_cadenazo_libre/cadenazo.mp3' },
        { n = 'Radioteletaxi', u = 'http://radiott-web.streaming-pro.com:6103/radiott.mp3' },
        { n = 'Radiotop20Es', u = 'https://sonic.sistemahost.es/8014/stream' },
        { n = 'Radiovoz Lugo', u = 'http://live.radiovoz.es/mp3/stream_lugo.mp3' },
        { n = 'Remember The Music FM 966', u = 'https://eu1.lhdserver.es:9041/stream' },
        { n = 'Remember VIP Radio', u = 'http://node-19.zeno.fm/471az1pu2nhvv?rj-ttl=5&aw_0_req_lsid=47ff91dffd57dbf75dd0fb53d70887a6&acu-uid=592123274268&bsw-uid=821f026b-0bba-437a-8608-4175e0f8681a&amb-uid=4433801850266558616&rj-tok=AAABgvsOIBIA01PqCt44uBvX-A&aw-uid=7d8ef8fede4e9d48810209d9211a4b12&dyn-uid&dbm-uid=CAESEE2_JyH-nO_DIddQW1whFfI&mm-uid=ef936263-16b7-4900-8f84-e3367baa5653&triton-uid=cookie:e618ff5c-77ba-49f3-ac6e-b9c6b093d00f&zs=l4i70_8iS4m6nNOBdKq6LA&an-uid=4758170041402249417' },
        { n = 'Remember Vip Techno', u = 'https://stream-153.zeno.fm/xilwjn4t17qvv' },
        { n = 'RIBA-ROJA RADIO By Xopo', u = 'https://streaming.enacast.com/radioribarroja128.mp3' },
        { n = 'RNE - R1 --> CYL', u = 'https://d111.rndfnk.com/star/crtve/rne1/cyl/mp3/128/stream.mp3?cid=01GEP0DN8GCZC2C0SGZXHEXY4M&sid=2HgFnxXLclfo0GsautZRhy4u66Y&token=tN3XDHB3LAFM4SJMXWQyFE1-8wss_wt4LPu18-kNSTw&tvf=PPaFOYl8KBdkMTExLnJuZGZuay5jb20' },
        { n = 'RNE - R1 --> Madrid', u = 'https://d121.rndfnk.com/star/crtve/rne1/mad/mp3/128/stream.mp3?cid=01GEM7S23A9B744SKFN04XA893&sid=2HgEg5aD71G8EuEf67MKTba5AnL&token=n_qXJorii6EVsZ_IP-RSzQP8sRamUc8gqb1nDnqiNT8&tvf=HHgasgd8KBdkMTIxLnJuZGZuay5jb20' },
        { n = 'RNE - R5 --> CYL', u = 'https://d131.rndfnk.com/star/crtve/rne5/vll/mp3/128/stream.mp3?cid=01GEPV7WKAZ76GE8RY96MABK2Q&sid=2KOwF9j2zTSpS2d7Vzm2JlIGObT&token=OFo8rpIZ5IV_j9VLJVCWOFNFyzX5dnsD1-yebzJNl7Q&tvf=uIWMDWLROhdkMTMxLnJuZGZuay5jb20' },
        { n = 'RNE - R5 --> Madrid', u = 'https://d121.rndfnk.com/star/crtve/rne5/mad/mp3/128/stream.mp3?cid=01GEP4QN2TSXQQDS2JQA783NYX&sid=2HgHkKUje0YQl468xMDmJHKhDmz&token=bRjUW1ZmpjTaF8EgRmo3u6OCUep9WTHKjib0rpzUUzw&tvf=FG8P7Wd9KBdkMTIxLnJuZGZuay5jb20' },
        { n = 'RNE - R5 --> Valencia', u = 'https://f131.rndfnk.com/star/crtve/rne5/vlc/mp3/128/stream.mp3?cid=01GEP70HQKHM3WJB5GHG662KX3&sid=2HgIGK1NtDDUVhSnKN9RWpCUKWE&token=r4st34giurxRWd0CMkMBmwayGa2nB6j_aUgMn_xD7vs&tvf=RH0CSKN9KBdmMTMxLnJuZGZuay5jb20' },
        { n = 'RNE - Radio 5 Huesca', u = 'https://dispatcher.rndfnk.com/crtve/rne5/ter/mp3/high?idasset=6116428' },
        { n = 'RNE - Radio 5 Teruel', u = 'https://dispatcher.rndfnk.com/crtve/rne1/ara/mp3/high?idasset=3893524' },
        { n = 'RNE 1 - Zaragoza', u = 'https://dispatcher.rndfnk.com/crtve/rne5/zgz/mp3/high?idasset=3894741' },
        { n = 'RNE Andalucía', u = 'https://f141.rndfnk.com/star/crtve/rne5/gra/mp3/128/stream.mp3?cid=01GEPXW032X3Y2SXM6M4X4F1X4&sid=2ar1MBXpFkcnL6WuaxAXO1hEITa&token=L_nTm1RjUems0IjZMMQ_ZzFu3XQ_1_faFzfSM3OR5t8&tvf=06JeYFmsqRdmMTQxLnJuZGZuay5jb20' },
        { n = 'RNE Murcia', u = 'https://d121.rndfnk.com/star/crtve/rne1/mur/mp3/128/stream.mp3?cid=01GEP3ZKY6YSV20P6RMNTKNDD6&sid=2ar2W2AJRHCleglLtfnn6nLklsU&token=25qdZ9PRjFVlFZkLiFrLLCHGs5cDbRXkhlVCjXwNN8Q&tvf=kGi_U96sqRdkMTIxLnJuZGZuay5jb20' },
        { n = 'RNE Radio 1 Galicia', u = 'https://dispatcher.rndfnk.com/crtve/rne1/gal/mp3/high' },
        { n = 'RNE Radio 5 Cartagena', u = 'https://d121.rndfnk.com/star/crtve/rne5/crt/mp3/128/stream.mp3?cid=01GEPY85J4FZ50K0956C6QZ4TT&sid=2ar1h9FifG7sqNVZxCzJSo1f7fk&token=TVD8UCJOI3n7sREjfbHHyvVozfE9KGpEyZVnRwsqUsU&tvf=k-AvSYCsqRdkMTIxLnJuZGZuay5jb20' },
        { n = 'RNE Radio 5 Galicia', u = 'https://dispatcher.rndfnk.com/crtve/rne5/lcg/mp3/high' },
        { n = 'RNE Radio 5 Las Palmas', u = 'https://d121.rndfnk.com/star/crtve/rne5/lpa/mp3/128/stream.mp3?cid=01GEP4X9Y3EYSQDV2G2MRTWGGZ&sid=2KXdzbu8f6MPAaCmdrAfA7scSHY&token=wiTLRflaxoLHseM8UraPggqszRT9NNr2mUoTnKi8TdU&tvf=6Up4UpPDOxdkMTIxLnJuZGZuay5jb20' },
        { n = 'RNE Radio 5 Valencia', u = 'https://d131.rndfnk.com/star/crtve/rne5/vlc/aac/128/stream.aac?cid=01GEP70HQKHM3WJB5GHG662KX3&sid=2MHsjXUN7pFK03vBbXrL08rOPRJ&token=Gu5PoCVPt238lI_sOeSzHZPRNJrKj8eeS4mPRqXzSX4&tvf=AvB-hceGRxdkMTMxLnJuZGZuay5jb20' },
        { n = 'RNE Radio Nacional Almería', u = 'https://dispatcher.rndfnk.com/crtve/rne1/alm/mp3/high' },
        { n = 'Rocksateliteone', u = 'https://stream.tunerplay.com/radio/8050/rocksateliteradio.mp3' },
        { n = 'Romance 106Wner', u = 'https://s13.myradiostream.com/:41400/listen.mp3' },
        { n = 'RPV Gran Canaria', u = 'https://stream.radio-pv.com/' },
        { n = 'Rusradio Marbella', u = 'http://streaming.enacast.com:8000/rusradiomarbellaHD.mp3' },
        { n = 'Ràdio Abrera', u = 'http://streaming.enantena.com:8000/radioabrera128.mp3' },
        { n = 'Ràdio Altea', u = 'https://enacast.com/radioaltea/streams/HD' },
        { n = 'Ràdio Arenys', u = 'http://streaming.enantena.com:8000/radioarenysdemar128.mp3' },
        { n = 'Ràdio Arenys De Munt', u = 'https://enacast.com/radioarenysdemunt/streams/HD' },
        { n = 'Ràdio Balaguer', u = 'http://79.148.125.91:8020/;stream.nsv' },
        { n = 'Ràdio Capital', u = 'http://streaming.martiproduccions.com:8000/capitalhd' },
        { n = 'Ràdio El Vendrell', u = 'https://enacast.com/rtvelvendrell/streams/SD' },
        { n = 'Ràdio La Selva', u = 'https://enacast.com/radiolaselva/streams/SD' },
        { n = 'Ràdio Manlleu', u = 'https://enacast.com/radiomanlleu/streams/HD' },
        { n = 'Ràdio Marina', u = 'http://streaming.enantena.com:8000/radiomarina128.mp3' },
        { n = 'Ràdio Molins De Rei', u = 'http://streaming.enantena.com:8000/radiomolins.mp3' },
        { n = 'Ràdio Mollet', u = 'http://streaming.enantena.com:8000/radiomollet56.mp3' },
        { n = 'Ràdio Nova', u = 'http://radio.08-produccions.cat:8000/rvilanova.mp3' },
        { n = 'Ràdio Olot', u = 'http://chrome.frilab.com:8000/radiolot' },
        { n = 'Ràdio Pineda', u = 'http://streaming.enantena.com:8000/radiopineda56.mp3' },
        { n = 'Ràdio Ponts', u = 'https://enacast.com/radioponts/streams/HD' },
        { n = 'Ràdio Premià De Mar', u = 'http://streaming.enantena.com:8000/radiopremiademar128.mp3' },
        { n = 'Ràdio Puig-Reig', u = 'https://enacast.com/puigreig/streams/SD' },
        { n = 'Ràdio Riba-Roja', u = 'https://enacast.com/radioribarroja/streams/SD' },
        { n = 'Ràdio Ràpita', u = 'https://enacast.com/radiorapita/streams/SD' },
        { n = 'Ràdio Tàrrega', u = 'https://enacast.com/radiotarrega/streams/HD' },
        { n = 'Ràdio Ulldecona', u = 'https://enacast.com/radioulldecona/streams/HD' },
        { n = 'Ràdio Vic', u = 'http://streaming.enantena.com:8000/radiovic56.mp3' },
        { n = 'Ràdio Vilablareix', u = 'https://enacast.com/radiovilablareix/streams/SD' },
        { n = 'S+ Ibiza', u = 'https://ice.studiopiu.net/studiopiuibiza.aac' },
        { n = 'Scannerfm', u = 'https://eu10.fastcast4u.com/scannerfm' },
        { n = 'Segenswelle Espanol', u = 'http://segenswelle.de:8000/espanol' },
        { n = 'SER', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3' },
        { n = 'SER - Radio Pamplona', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_PAMPLONA.mp3' },
        { n = 'SER - Radio Zaragoza', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ZARAGOZA.mp3' },
        { n = 'SER -- CUELLAR', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_CUELLAR.mp3' },
        { n = 'SER Asturias', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_ASTURIAS.mp3' },
        { n = 'SER Catalunya', u = 'https://25553.live.streamtheworld.com/SER_CATAAC.aac' },
        { n = 'Ser Gandia', u = 'http://stream.radiogandia.com:8080/ser_high' },
        { n = 'SER Gijón', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_GIJON.mp3' },
        { n = 'Ser Soria', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SER_SORIA.mp3' },
        { n = 'Shock FM', u = 'https://streaming2.shock.fm:8040/normal' },
        { n = 'Smooth Jazz Classics By Cloud Jazz', u = 'https://stream-57.zeno.fm/w3phtkukfg8uv?zs=90IfdbcARnS99_b8RaX9sQ&acu-uid=736851429618&dyn-uid&an-uid=0&mm-uid=a42b63d5-b9eb-4f00-9692-60c79195c3a4&triton-uid=cookie:7e5c2d9b-9c30-46f6-b8b4-0354fd4dd340&amb-uid=3916839388731891724' },
        { n = 'Sol Radio', u = 'https://azura.abcorp.es/radio/8220/solradio' },
        { n = 'Spectrum FM Costa Almeria', u = 'https://eu8.fastcast4u.com/proxy/almeria2?mp=/1' },
        { n = 'Spektra FM Valencia', u = 'http://stm1.emiteonline.com:8008/spektrafm' },
        { n = 'Star People', u = 'http://2.139.144.101:8020/2?1508151505' },
        { n = 'Sunshine FM Costa Blanca', u = 'https://ice31.securenetsystems.net/SRFM?playSessionID=552CF0B4-E79E-4B4A-AC21DBC50B679DC6' },
        { n = 'Swing Latinos FM', u = 'https://eu1.lhdserver.es:9033/stream' },
        { n = 'Talk Radio Europe', u = 'http://s3.yesstreaming.net:7014/stream' },
        { n = 'Tenerife Sur Adeje', u = 'https://streaming.enacast.com/radiosuradeje128.mp3' },
        { n = 'Toma Radio', u = 'http://stvt.dynu.net:7008/directo' },
        { n = 'Top Radio 972 FM', u = 'http://provisioning.streamtheworld.com/pls/TOPRADIOAAC.pls' },
        { n = 'Totràdio', u = 'http://www.totradio.com:8000/128kbps' },
        { n = 'Urban Con Ñ', u = 'https://st1.urbanrevolution.es:8443/hispano' },
        { n = 'Vaughan', u = 'http://vaughanradioweb.streaming-pro.com:8057/;streamdemo_mp3.nsv' },
        { n = 'Vinilo FM Bizkaia', u = 'https://radio.vinilofm.es/radio/8000/bizkaia.mp3' },
        { n = 'Wapafm', u = 'https://eu1.lhdserver.es:3115/stream' },
        { n = 'Xanadú Radio Tenerife', u = 'https://server8.emitironline.com:10852/radio.mp3?1646071824637' },
        { n = 'Xtra FM', u = 'http://stream.internetgirona.com:8000/;' },
        { n = '华夏之声China FM·西班牙马德里FM929', u = 'https://radioserver12.profesionalhosting.com/proxy/pkg152387/stream' },
    }
}
