return {
    ['the_russian_federation'] = {
        { n = '-=- Relax-Fm -=-', u = 'http://ic4.101.ru:8000/stream/air/aac/64/200' },
        { n = '101,Ru Russian Dance', u = 'https://pub0302.101.ru:8443/stream/trust/mp3/128/17?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjQ5LjM3LjE1MS42IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6ODguMCkgR2Vja29cLzIwMTAwMTAxIEZpcmVmb3hcLzg4LjAiLCJ1aWRfY2hhbm5lbCI6IjE3IiwidHlwZV9jaGFubmVsIjoiY2hhbm5lbCIsImV4cCI6MTYxODUwMTYyM30.vsWQ1s12RL1P3yuD4Eb6E2Og6YaLbXceO-cfhhhwl5s' },
        { n = '101Ru - Boney M', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/114' },
        { n = '101Ru - Deep House', u = 'https://pub0202.101.ru:8000/stream/trust/mp3/128/173' },
        { n = '101Ru - Drum Bass', u = 'https://pub0302.101.ru:8000/stream/pro/aac/64/6?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjIxMi41MS4xNDIuMTY2IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IFVidW50dTsgTGludXggeDg2XzY0OyBydjo4OC4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvODguMCIsInVpZF9jaGFubmVsIjoiNiIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MTU0NjYxNDh9.ReVmj9UP8k1j83oPOXewKDc37Me9RpR3wA3nm5bMWmE' },
        { n = '101Ru - Electronic', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/132' },
        { n = '101Ru - French Chanson', u = 'http://ic6.101.ru:8000/stream/pro/aac/64/146' },
        { n = '101Ru - House', u = 'https://pub0202.101.ru:8000/stream/trust/mp3/128/10' },
        { n = '101Ru - Relax FM', u = 'https://ic4.101.ru:8000/stream/air/aac/64/200' },
        { n = '101Ru ABBA', u = 'http://pub0101.101.ru:8000/stream/pro/aac/64/104?' },
        { n = '101Ru Bard Songs - Авторская Песня', u = 'https://ic6.101.ru:8000/stream/pro/aac/64/35' },
        { n = '101Ru Italo Disco', u = 'http://pub0202.101.ru:8000/stream/pro/aac/64/161' },
        { n = '101Ru Techno', u = 'https://pub0302.101.ru:8000/stream/trust/mp3/128/18' },
        { n = '101Ru Trance', u = 'http://pub0101.101.ru:8000/stream/trust/mp3/128/19?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ijc5LjI1My4xMy43MSIsInVzZXJhZ2VudCI6Ik1vemlsbGFcLzUuMCAoWDExOyBMaW51eCB4ODZfNjQ7IHJ2Ojk0LjApIEdlY2tvXC8yMDEwMDEwMSBGaXJlZm94XC85NC4wIiwidWlkX2NoYW5uZWwiOiIxOSIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MzY4ODYwMzJ9.0vfq2B5eNRtuEwE42pHUS9Sf_GosTmrQs0aHcPvbFj8' },
        { n = '101Ru ДДТ', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/112?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ijg4LjIyMy42OC44NCIsInVzZXJhZ2VudCI6Ik1vemlsbGFcLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0OyBydjo5MS4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvOTEuMCBXYXRlcmZveFwvOTEuNC4yIiwidWlkX2NoYW5uZWwiOiIxMTIiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwiZXhwIjoxNjQxNjcxOTg3fQ.k_WsYHWH-yoxEogmsvirk_IcKDdHKpTLDj5rCoF0B2E' },
        { n = '101Ru Россия Топ 50', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/34?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjczLjEzMC4zNy43OSIsInVzZXJhZ2VudCI6InB5dGhvbi1yZXF1ZXN0c1wvMi4yNS4xIiwidWlkX2NoYW5uZWwiOiIzNCIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MTY0MzcyNDh9.LRVefwOLisK0VGs3qvDvuYZ31k4mW7VJFd4mbWQQlD8.aac' },
        { n = '101Ru СССР 30-50', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/46' },
        { n = '101Ru СССР 50-70', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/47' },
        { n = '101Ru: Виктор Цой И Группа «КИНО»', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/103?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ijc4LjEwMi4yMzEuMTYiLCJ1c2VyYWdlbnQiOiJNb3ppbGxhXC81LjAgKFdpbmRvd3MgTlQgNi4zOyBXaW42NDsgeDY0OyBydjo5NS4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvOTUuMCIsInVpZF9jaGFubmVsIjoiMTAzIiwidHlwZV9jaGFubmVsIjoiY2hhbm5lbCIsImV4cCI6MTY0MDY4NTcwNH0.lnoDlTGctdMYI221sL4xM2B60tGLcLY5nYiv8bu1vNs' },
        { n = '1023 FM Хомякс Луганск', u = 'https://radio.play-fm.ru:8001/homyak' },
        { n = '161 FM', u = 'http://stream.161.fm:8000/256' },
        { n = '16Bitfm Cafe', u = 'http://16bitfm.com:8000/cafe_mp3_128' },
        { n = '920 Москва FM', u = 'http://icecast.vgtrk.cdnvideo.ru:8000/moscowfm128' },
        { n = '[Rocktime-Radio]', u = 'http://a9.radioheart.ru:8049/rocktime' },
        { n = 'ABBA Radio', u = 'https://pub0102.101.ru:8443/stream/personal/aacp/64/1785788' },
        { n = 'Afrobeat Afrobeats - Radio Caprice', u = 'http://79.120.39.202:8000/afrobeat' },
        { n = 'Anima Amoris - Goa Psy Trance', u = 'http://amoris.sknt.ru/goa.mp3' },
        { n = 'Anima Amoris [Trance]', u = 'http://anima.sknt.ru/trance.mp3' },
        { n = 'Anima Amoris Dub Techno', u = 'https://amoris.sknt.ru/dubtechno' },
        { n = 'Anima Amoris Dub Techno Mix', u = 'http://amoris.sknt.ru/dubtechnomix.mp3' },
        { n = 'Anima Amoris Minimal Deep Techno', u = 'https://amoris.sknt.ru/minimal.mp3' },
        { n = 'Anisonfm', u = 'http://anison.fm/anison.m3u' },
        { n = 'Antidot', u = 'https://135.125.205.200:8443/main' },
        { n = 'Atmosfera 128', u = 'http://185.64.76.49:8000/128' },
        { n = 'Badbeatradio', u = 'http://misato.ru-hoster.com:8061/badbeatradio' },
        { n = 'BAG', u = 'http://radio-holding.ru:9000/rfm_aac_64' },
        { n = 'Best Deep FM', u = 'https://myradio24.org/5129_320.m3u' },
        { n = 'Best FM', u = 'http://nashe.streamr.ru/best-128.mp3' },
        { n = 'Beta Anonfm', u = 'https://radio.anonymous.delivery/music.mp3' },
        { n = 'Big Room', u = 'https://pub0302.101.ru:8443/stream/trust/mp3/128/220' },
        { n = 'Biker FM', u = 'https://listen4.myradio24.com/69846' },
        { n = 'Bleeplove Chiptune Radio', u = 'https://stream-152.zeno.fm/gyazcly9dfotv?zs=4n2MPkZJRImNtNA8HGWuFw' },
        { n = 'Blues - Caprice Radio', u = 'http://79.120.77.11:8000/blues' },
        { n = 'Bolshoye Radio', u = 'http://listen.myradio24.com:9000/8286' },
        { n = 'C-Pop Chinese Popular Music', u = 'http://213.141.131.10:8000/cpop' },
        { n = 'Capital FM Moscow', u = 'http://icecast.vgtrk.cdnvideo.ru/capitalfmmp3' },
        { n = 'Caprice Radio - Dark Psy', u = 'http://79.111.119.111:8000/darkpsytrance' },
        { n = 'Cassiopeia Station Наука', u = 'https://stream.cassiopeia-station.ru:1095/stream' },
        { n = 'Chill Russia', u = 'https://chillrussia.ru/chillradio' },
        { n = 'Clavecincembaloharpsichord - Radio Caprice', u = 'http://213.141.131.10:8004/clavecin' },
        { n = 'Coffee FM', u = 'https://stream.pcradio.ru/Vintazh_kafe-med' },
        { n = 'Comedy Radio', u = 'http://pub0302.101.ru:8000/stream/reg/mp3/128/region_comedy_31' },
        { n = 'Comedy Radio New Link', u = 'http://ic6.101.ru:8000/stream/air/aac/64/202' },
        { n = 'Comfort FM', u = 'https://listen7.myradio24.com/118966' },
        { n = 'CORE Radio', u = 'http://194.58.97.117:8000/coreradio' },
        { n = 'Countryfolk Blues - Radio Caprice', u = 'http://79.120.77.11:8004/countryblues' },
        { n = 'CRN - Hardcore Raphorrorcore', u = 'http://79.120.39.202:8000/hardcorerap' },
        { n = 'CRN - Hip-Hop', u = 'http://79.120.77.11:8000/hiphop' },
        { n = 'CRN - Old School Hip-Hoprap', u = 'http://213.141.131.10:8000/oldschoolhiphop' },
        { n = 'CRN - Rap', u = 'http://79.120.77.11:8000/rap' },
        { n = 'Dance 90', u = 'https://ppr90.status-media.ru/ppr_90.mp3' },
        { n = 'Dancehall Raggamuffin - Caprice Radio', u = 'http://79.111.14.76:8000/dancehall' },
        { n = 'Deep One', u = 'https://stream.deep1.ru/deep1mp3' },
        { n = 'DEEPZONE', u = 'https://radio.deepzone.ru/listen/deepzone/deep256.acc' },
        { n = 'DFM', u = 'https://dfm.hostingradio.ru/dfm96.aacp?0.28225617725168517' },
        { n = 'DFM - Breakbeat', u = 'https://dfm-breakbeat.hostingradio.ru/breakbeat96.aacp' },
        { n = 'DFM - Chill', u = 'https://dfm-dfmchill.hostingradio.ru/dfmchill96.aacp' },
        { n = 'DFM - Dancehall', u = 'https://dfm-dancehall.hostingradio.ru/dancehall96.aacp' },
        { n = 'DFM - Gangsta Deep', u = 'https://dfm-gangstadeep.hostingradio.ru/gangstadeep96.aacp' },
        { n = 'DFM - Insomnia', u = 'https://dfm-insomnia.hostingradio.ru/insomnia96.aacp' },
        { n = 'DFM - Organic House', u = 'https://dfm-organichouse.hostingradio.ru/organichouse96.aacp' },
        { n = 'DFM - Party', u = 'https://dfm-party.hostingradio.ru/dfmparty96.aacp' },
        { n = 'DFM - Pop Dance', u = 'https://dfm-popdance.hostingradio.ru/popdance96.aacp' },
        { n = 'DFM - Tech House', u = 'https://dfm-techhouse.hostingradio.ru/techhouse96.aacp' },
        { n = 'DFM - Vocal Trance', u = 'https://dfm-trance.hostingradio.ru/trance96.aacp' },
        { n = 'DFM DANCE GOLD 2000S', u = 'https://dfm-dancegold00.hostingradio.ru/dancegold0096.aacp' },
        { n = 'DFM DISCO', u = 'https://dfm-disco.hostingradio.ru/disco96.aacp' },
        { n = 'DFM POP GOLD 2000S', u = 'https://dfm-popgold00.hostingradio.ru/popgold0096.aacp' },
        { n = 'DFM RUSSIAN DANCE', u = 'https://dfm-dfmrusdance.hostingradio.ru/dfmrusdance96.aacp?0.9987259013359274' },
        { n = 'DFM Trap', u = 'https://dfm-dfmtrap.hostingradio.ru/dfmtrap96.aacp' },
        { n = 'DFM Дискач 90-Х', u = 'https://dfm-disc90.hostingradio.ru/disc9096.aacp' },
        { n = 'Dinamit FM', u = 'https://myradio24.org/76923' },
        { n = 'Discoteca 80', u = 'https://pub0302.101.ru:8443/stream/pro/aac/64/1?' },
        { n = 'Discovertranceradio MP3 HQ Stereo 192Kbits', u = 'http://www.discovertrance.com/DiscoverTrance-high.m3u' },
        { n = 'DNB FM', u = 'https://air.dnbfm.ru/listen/player/qplay' },
        { n = 'Donat FM - European Hits', u = 'http://c6.radioboss.fm:8089/autodj' },
        { n = 'Donat FM - Russian Rock', u = 'http://c6.radioboss.fm:8097/autodj' },
        { n = 'DONAT FM - Музыка СССР', u = 'http://c6.radioboss.fm:8098/stream' },
        { n = 'DONAT FM - Русская Поп-Музыка', u = 'http://c6.radioboss.fm:8099/stream' },
        { n = 'DONAT FM - Русский Рок', u = 'http://c6.radioboss.fm:8097/stream' },
        { n = 'DONAT FM - Шансон', u = 'http://c6.radioboss.fm:8096/stream' },
        { n = 'Echo ЭХО Online', u = 'https://i1.echofm.online:8443/stream' },
        { n = 'Enigmatic 3 - Magnetic Chillout', u = 'http://radio.enigmatic.su:8050/radio' },
        { n = 'Enigmatic Immersion', u = 'http://radio.enigmatic.su:8040/radio' },
        { n = 'Enigmatic Station 1', u = 'http://listen2.myradio24.com:9000/8226' },
        { n = 'Europa Plus', u = 'http://ep256.hostingradio.ru:8052/europaplus256.mp3' },
        { n = 'Europa Plus Acoustic', u = 'http://epdop.hostingradio.ru:8033/acoustic128.mp3' },
        { n = 'Europapplus Party', u = 'http://epdop.hostingradio.ru:8033//epparty128.mp3' },
        { n = 'Europapplus Top 40', u = 'http://eptop128.streamr.ru/' },
        { n = 'Fitness Radio', u = 'https://stream.mixadance.fm/fitness' },
        { n = 'Fresh FM', u = 'https://a2.radioheart.ru:8007/live' },
        { n = 'Fusion', u = 'https://stream.fusionradio.ru:1045/stream' },
        { n = 'Garage FM Online', u = 'http://music.garagefm.ru:8005/Garagefm128' },
        { n = 'German Deutsche Hip-Hop Rap - Caprice Radio', u = 'http://213.141.131.10:8000/germanrap' },
        { n = 'Heavy Music Atmospheric Radio', u = 'http://stream.heavy-music.net:8176/stream' },
        { n = 'HIP HOP RADIO', u = 'https://tntradio.hostingradio.ru:8027/hhr128.mp3' },
        { n = 'HIT FM', u = 'https://hitfm.hostingradio.ru/hitfm96.aacp' },
        { n = 'Https:Streamstudio21Rustudio2196Aacp', u = 'https://stream.studio21.ru/studio2196.aacp' },
        { n = 'Ibiza', u = 'http://radiorecord.hostingradio.ru/ibiza96.aacp' },
        { n = 'Ifree FM', u = 'https://fm.ifree.pro:1045/stream' },
        { n = 'Instrumental Jazz', u = 'https://jfm1.hostingradio.ru:14536/ijstream.mp3' },
        { n = 'Invoice Радио', u = 'https://listen.myrh.ru/id079040' },
        { n = 'Italo Disco - Caprice Radio', u = 'http://79.111.119.111:8000/italodisco' },
        { n = 'JAZZ MANOUCHE GYPSY JAZZ GYPSY SWING - Radio Caprice', u = 'http://79.120.77.11:8004/manouche' },
        { n = 'Kamchatka Live Chillout', u = 'https://radio.kamchatkalive.ru:8103/chillout' },
        { n = 'Kinozaltv', u = 'https://listen4.myradio24.com/kinozaltv' },
        { n = 'Komsomolskaya Pravda', u = 'http://kraskp.ru:8000/mskregion' },
        { n = 'L-Radio', u = 'https://air.unmixed.ru/lradio256' },
        { n = 'Like FM Moscow, Russia', u = 'http://pub0302.101.ru:8000/stream/air/aac/64/219' },
        { n = 'Luxury Lounge - Chillwave Retrowave', u = 'http://188.40.109.122:8000/ices2' },
        { n = 'Luxury Lounge - Late Night, Deep Sleep Meditation', u = 'http://188.40.109.122:8000/ices3' },
        { n = 'Luxury Lounge - Level 2', u = 'http://188.40.109.122:8000/ices' },
        { n = 'Made In Russia Dance Radio', u = 'https://listen7.myradio24.com/9083' },
        { n = 'MAXIMUM', u = 'https://maximum.hostingradio.ru/maximum96.aacp' },
        { n = 'MAYAK', u = 'http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_64kbps' },
        { n = 'Metaradio', u = 'https://s2.metaradio.ru/mradio.aacp' },
        { n = 'Mixadance FM', u = 'https://stream.mixadance.fm/mixadance' },
        { n = 'Mixcult', u = 'http://radio.mixcult.net:8000/MixCult_256kbps' },
        { n = 'Monsters Of Rock USSR', u = 'https://stream-51.zeno.fm/6nbz7p2w908uv' },
        { n = 'Monte Carlo Gold Collection', u = 'https://montecarlo.hostingradio.ru/mcgold96.aacp' },
        { n = 'Monte Carlo Moscow', u = 'https://montecarlo.hostingradio.ru/montecarlo96.aacp' },
        { n = 'Moskva FM', u = 'http://icecast.vgtrk.cdnvideo.ru/moscowfm128?v=1550419566950' },
        { n = 'MOTORADIO', u = 'http://stream.motoradio.online:8000/high-aac' },
        { n = 'Musical Decadence Radio', u = 'https://stream.musicaldecadence.ru/live' },
        { n = 'Nashe Radio', u = 'http://nashe1.hostingradio.ru/nashe-128.mp3' },
        { n = 'Nebula', u = 'https://cast4.my-control-panel.com/proxy/nebulara/stream' },
        { n = 'NRJ Russia', u = 'https://srv02.gpmradio.ru:8443/stream/air/aac/64/99' },
        { n = 'Omsk FM', u = 'http://www.omskfm.ru:8000/881-128.mp3' },
        { n = 'Premium', u = 'https://listen2.rpfm.ru/premium128' },
        { n = 'Promodj - Dubstep', u = 'http://radio.promodj.com/dubstep-192' },
        { n = 'Promodj - Too Deep', u = 'http://radio.promodj.com:8000/toodeep-192' },
        { n = 'Promodj - Trance', u = 'http://radio.promodj.com/fullmoon-192' },
        { n = 'Promodj - Yoo', u = 'http://radio.promodj.com:8000/yo-192' },
        { n = 'Promodj Too Nu', u = 'http://radio.promodj.com/toonu-192' },
        { n = 'Promodj Top100', u = 'http://radio.promodj.com/top100-192' },
        { n = 'Provodach', u = 'https://station.waveradio.org/provodach' },
        { n = 'RADCAP: ATMOSPHERIC AMBIENT BLACK METAL', u = 'http://79.120.39.202:8000/aabmds' },
        { n = 'RADCAP: PROGRESSIVE BLACK POST-BLACK BLACKGAZE', u = 'http://79.111.14.76:8000/postblack' },
        { n = 'RADCAP: TRIP-HOP', u = 'http://79.111.14.76:8000/triphop' },
        { n = 'Radio 2000X', u = 'http://air.radio2000x.com:8000/stream' },
        { n = 'Radio 7 Moscow', u = 'https://emgregion.hostingradio.ru:8064/moscow.radio7.mp3' },
        { n = 'Radio Anonymous', u = 'http://anon.fm:8000/radio.m3u' },
        { n = 'Radio Caprice - Acoustic Guitar', u = 'http://79.120.39.202:8000/acousticguitar.m3u' },
        { n = 'Radio Caprice - African Folk Ethnic Music 320K', u = 'http://79.120.39.202:8004/africanfolk' },
        { n = 'Radio Caprice - Atmosphericambient Black Metal', u = 'http://79.120.39.202:8002/aabmds' },
        { n = 'Radio Caprice - Baroque', u = 'http://79.111.14.76:8000/baroque' },
        { n = 'Radio Caprice - Blues Rock', u = 'http://79.120.39.202:8002/bluesrock' },
        { n = 'Radio Caprice - Bossa Nova', u = 'http://79.111.14.76:8002/bossanova' },
        { n = 'Radio Caprice - Breakbeat', u = 'https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://79.120.39.202:9051/listen.pls&t=.pls' },
        { n = 'Radio Caprice - Brutal Death Metal', u = 'http://79.111.119.111:8000/brutaldeathmetal.m3u' },
        { n = 'Radio Caprice - Chicago Blues', u = 'http://79.111.14.76:8000/chicagoblues' },
        { n = 'Radio Caprice - Chiptune', u = 'http://79.111.119.111:8004/chiptune' },
        { n = 'Radio Caprice - Classical Baroque', u = 'http://79.111.14.76:8002/baroque' },
        { n = 'Radio Caprice - Contemporary Jazz', u = 'http://79.111.119.111:8002/contemporaryjazz' },
        { n = 'Radio Caprice - Cyberpunk', u = 'http://79.120.12.130:8004/cyberpunk' },
        { n = 'Radio Caprice - Dark Electro Aggrotech', u = 'http://79.120.39.202:8002/darkelectro' },
        { n = 'Radio Caprice - Deathcore', u = 'http://79.111.14.76:8000/deathcore' },
        { n = 'Radio Caprice - Deep Chill House [2]', u = 'http://79.120.39.202:8000/deephouse' },
        { n = 'Radio Caprice - Dub Techno [1]', u = 'http://79.120.39.202:8002/dubtechno' },
        { n = 'Radio Caprice - Dub Techno [2]', u = 'http://79.120.39.202:8000/dubtechno' },
        { n = 'Radio Caprice - Easy Listening', u = 'http://79.111.14.76:8002/easylistening' },
        { n = 'Radio Caprice - Electroclash Synthcore Tech Pop Nouveau Disco [2]', u = 'http://79.120.39.202:8000/electroclash' },
        { n = 'Radio Caprice - Erotic', u = 'http://79.120.39.202:8000/erotic' },
        { n = 'Radio Caprice - Eurobeathi-Nrg', u = 'http://79.120.39.202:9159/listen.pls' },
        { n = 'Radio Caprice - Female Vocal In Metal Music', u = 'http://79.111.14.76:8000/femalemetal?type=.mp3' },
        { n = 'Radio Caprice - Folk Black Metal', u = 'http://79.120.12.130:8002/folkblackmet' },
        { n = 'Radio Caprice - Folk Death Metal', u = 'http://79.120.12.130:8000/folkdeathmet' },
        { n = 'Radio Caprice - Folk Metal', u = 'http://79.120.39.202:8000/folkmetal.m3u' },
        { n = 'Radio Caprice - Forest Psytrance', u = 'http://213.141.131.10:8004/forestpsytrance' },
        { n = 'Radio Caprice - Free Jazz', u = 'http://79.111.14.76:8002/freejazz' },
        { n = 'Radio Caprice - Funky House [3]', u = 'http://213.141.131.10:8004/funkyhouse' },
        { n = 'Radio Caprice - Future Garage Chillstep Deep Post Dubstep', u = 'http://79.120.39.202:8002/futuregarage' },
        { n = 'Radio Caprice - Gabber Early Mainstream Hardcore', u = 'http://213.141.131.10:8002/gabber' },
        { n = 'Radio Caprice - Gothic Black Metal', u = 'http://79.120.39.202:8000/gothblackmet' },
        { n = 'Radio Caprice - Guitar Jazz', u = 'http://79.120.77.11:8002/guitarjazz' },
        { n = 'Radio Caprice - Harp', u = 'http://213.141.131.10:8000/harp' },
        { n = 'Radio Caprice - Heavy Metal', u = 'http://79.111.14.76:8000/heavymetal.m3u' },
        { n = 'Radio Caprice - Indian Folk', u = 'http://79.111.14.76:8000/indianfolk' },
        { n = 'Radio Caprice - Instrumental Metal', u = 'http://79.111.119.111:8004/instrumentalmetal' },
        { n = 'Radio Caprice - Instrumental Music', u = 'http://79.120.77.11:8002/instrumental' },
        { n = 'Radio Caprice - Instrumental Rock', u = 'http://79.120.39.202:8002/instrumentalrock' },
        { n = 'Radio Caprice - Lo-Fi', u = 'http://79.111.14.76:8000/lo-fi' },
        { n = 'Radio Caprice - Medieval Folk', u = 'http://213.141.131.10:8004/medievalfolk' },
        { n = 'Radio Caprice - Medieval Music', u = 'http://213.141.131.10:8000/medieval' },
        { n = 'Radio Caprice - Melodic Death Metal', u = 'http://79.120.77.11:8002/melodicdeath' },
        { n = 'Radio Caprice - Melodic Heavy Metal', u = 'http://79.111.119.111:8000/melodicheavy.m3u' },
        { n = 'Radio Caprice - Melodic Power Metal', u = 'http://79.111.119.111:8000/melodicpower.m3u' },
        { n = 'Radio Caprice - Metalcore', u = 'http://79.120.39.202:8000/metalcore.m3u' },
        { n = 'Radio Caprice - Minimal Tech House [1]', u = 'http://79.111.119.111:8002/mintechhouse' },
        { n = 'Radio Caprice - Minimal Tech House [2]', u = 'http://79.111.119.111:8000/mintechhouse' },
        { n = 'Radio Caprice - Minimal Tech House [3]', u = 'http://79.111.119.111:8004/mintechhouse' },
        { n = 'Radio Caprice - Minimal Techno [1]', u = 'http://79.120.39.202:8002/mintechno' },
        { n = 'Radio Caprice - Minimal Techno [2]', u = 'http://79.120.39.202:8000/mintechno' },
        { n = 'Radio Caprice - Music Of Siberia Mongolia', u = 'http://79.111.119.111:8004/siberia' },
        { n = 'Radio Caprice - Neurofunk', u = 'http://79.111.119.111:8004/neurofunk' },
        { n = 'Radio Caprice - New Age', u = 'http://79.120.77.11:8002/newage' },
        { n = 'Radio Caprice - Nu Metal 128', u = 'http://79.111.14.76:8000/numetal' },
        { n = 'Radio Caprice - Old School Hip-Hop Rap', u = 'http://213.141.131.10:8002/oldschoolhiphop' },
        { n = 'Radio Caprice - Piano', u = 'http://79.120.77.11:8002/piano' },
        { n = 'Radio Caprice - Piano Jazz Stride Ragtime', u = 'http://79.111.119.111:8002/pianojazz' },
        { n = 'Radio Caprice - Post-Rock', u = 'http://79.111.14.76:8004/postrock' },
        { n = 'Radio Caprice - Power Metal', u = 'http://79.120.77.11:8000/powermetal.m3u' },
        { n = 'Radio Caprice - Progressive Metal', u = 'http://79.120.77.11:8000/progmetal' },
        { n = 'Radio Caprice - Psychedelic Folk', u = 'http://213.141.131.10:8000/psychfolk.m3u' },
        { n = 'Radio Caprice - Psychedelic Rock', u = 'http://79.111.119.111:9027/listen.pls' },
        { n = 'Radio Caprice - PSYCHOBILLY', u = 'http://79.111.119.111:8002/psychobilly' },
        { n = 'Radio Caprice - Punk Post-Hardcore Emoscreamo', u = 'http://79.111.119.111:8000/screamoemo' },
        { n = 'Radio Caprice - Rock Metal Ballads', u = 'http://79.120.77.11:8002/rockballads' },
        { n = 'Radio Caprice - Russian Club Dance Music [3]', u = 'http://79.120.77.11:8004/clubru' },
        { n = 'Radio Caprice - Russian Pop Music', u = 'http://79.120.77.11:8000/popru' },
        { n = 'Radio Caprice - Russian Rock', u = 'http://79.120.77.11:9029/listen.pls' },
        { n = 'Radio Caprice - Soul Jazz', u = 'http://79.111.14.76:8002/souljazz' },
        { n = 'Radio Caprice - Space Music', u = 'http://79.111.119.111:8000/spacemusic' },
        { n = 'Radio Caprice - Speedmetal', u = 'http://79.111.119.111:8000/speedmetal' },
        { n = 'Radio Caprice - Symphonic Gothic Metal', u = 'http://213.141.131.10:8002/symphogoth' },
        { n = 'Radio Caprice - Symphonic Power Metal', u = 'http://213.141.131.10:8000/symphopower.m3u' },
        { n = 'Radio Caprice - Symponic Metal', u = 'http://79.120.77.11:8004/symphometal' },
        { n = 'Radio Caprice - Viking Metal', u = 'http://79.111.14.76:8000/vikingmetal.m3u' },
        { n = 'Radio Caprice - West Coast Hip-Hop, Gangsta Rap, G-Funk 320K', u = 'http://79.120.39.202:8004/gangstarap' },
        { n = 'Radio Caprice ACID CLUB GROOVE JAZZ', u = 'http://79.111.14.76:8000/acidjazz' },
        { n = 'Radio Caprice Dark Techno HQ', u = 'http://79.111.14.76:8000/darktechno' },
        { n = 'Radio Caprice Indie Electronic', u = 'http://79.111.119.111:8002/indieelectronic' },
        { n = 'Radio Caprice Industrialdarkritual Ambient', u = 'http://79.120.39.202:8002/darkambient' },
        { n = 'Radio Caprice Jazz Modern Creative', u = 'http://79.120.77.11:8000/mcreative' },
        { n = 'Radio Caprice Math Rock', u = 'http://79.120.39.202:8000/mathrock' },
        { n = 'Radio Caprice Minimalism', u = 'http://213.141.131.10:8000/minimalism' },
        { n = 'Radio Caprice Romantic Music Collection', u = 'http://79.120.39.202:8002/romantic' },
        { n = 'Radio Caprice Triphop', u = 'https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://79.111.14.76:9013/listen.pls&t=.pls' },
        { n = 'Radio Caprice-Gregorian Chant', u = 'http://213.141.131.10:8002/chants' },
        { n = 'Radio Chocolate', u = 'http://choco.hostingradio.ru:10010/fm' },
        { n = 'Radio DFM Ufa 915 FM', u = 'http://92.50.177.134:8000/dfm_ufa' },
        { n = 'Radio Fantastika', u = 'http://fantasyradioru.no-ip.biz:8002/live' },
        { n = 'Radio Fantastiki', u = 'http://fantasyradioru.no-ip.biz:8008/' },
        { n = 'Radio Gameplay', u = 'https://c22.radioboss.fm:8144/GamePlay' },
        { n = 'Radio Jazz 891 - Classic JAZZ', u = 'http://jfm1.hostingradio.ru:14536/ijstream.mp3' },
        { n = 'Radio Jazz 891 - JAZZ Legends', u = 'http://jfm1.hostingradio.ru:14536/jlstream.mp3' },
        { n = 'Radio Jazz 891 - JAZZ Vocals', u = 'http://jfm1.hostingradio.ru:14536/jvstream.mp3' },
        { n = 'Radio Jazz 891 FM', u = 'http://nashe.streamr.ru/jazz-128.mp3.m3u' },
        { n = 'Radio Kamchatka LIVE Chillout', u = 'http://radio.kamchatkalive.ru:8103/chillout' },
        { n = 'Radio Kontinental', u = 'http://stream01.radiocon.ru:8000/hum_tbk' },
        { n = 'Radio Maximum - Heavy 80S', u = 'https://maximum80.hostingradio.ru/max8096.aacp' },
        { n = 'Radio Maximum - Nirvana', u = 'https://maximum-nirvana.hostingradio.ru/nirvana96.aacp' },
        { n = 'Radio Maximum - Punk', u = 'https://maximum-punk.hostingradio.ru/maxpunk96.aacp' },
        { n = 'Radio Maximum - Rammstein', u = 'https://maximum-rammstein.hostingradio.ru/rammstein96.aacp' },
        { n = 'Radio Maximum - Russian Music', u = 'https://maximum-russian.hostingradio.ru/maxrussian96.aacp' },
        { n = 'Radio Monte Carlo - Bossa Nova', u = 'https://mc-mcbossa.hostingradio.ru/mcbossa96.aacp?listening-from-radio-garden=1645969315' },
        { n = 'Radio Monte Carlo 1059 FM', u = 'https://icecast227.ptspb.ru:8443/monte' },
        { n = 'Radio Monte Carlo Golf Club', u = 'http://montecarlo.hostingradio.ru/golfcup96.aacp' },
        { n = 'Radio Record - Disco Funk', u = 'https://radiorecord.hostingradio.ru/discofunk96.aacp' },
        { n = 'Radio Record - Main Channel', u = 'https://radiorecord.hostingradio.ru/rr_main96.aacp' },
        { n = 'Radio Record - Nu Dance', u = 'https://radiorecord.hostingradio.ru/nudance96.aacp' },
        { n = 'Radio Record - Reggae', u = 'http://radiorecord.hostingradio.ru/reggae96.aacp' },
        { n = 'Radio Record - Russian Gold', u = 'https://radiorecord.hostingradio.ru/russiangold96.aacp' },
        { n = 'Radio Record - Russian Hits', u = 'https://radiorecord.hostingradio.ru/russianhits96.aacp' },
        { n = 'Radio Record - Russian Mix', u = 'https://radiorecord.hostingradio.ru/rus96.aacp' },
        { n = 'Radio Record - Summer Dance', u = 'https://radiorecord.hostingradio.ru/summerparty96.aacp' },
        { n = 'Radio Record Ambient', u = 'http://radiorecord.hostingradio.ru/ambient96.aacp' },
        { n = 'Radio Record Breaks', u = 'https://radiorecord.hostingradio.ru/brks96.aacp' },
        { n = 'Radio Record Chill House', u = 'https://radiorecord.hostingradio.ru/organic96.aacp' },
        { n = 'Radio Record Chill-Out', u = 'https://radiorecord.hostingradio.ru/chil32.aacp' },
        { n = 'Radio Record Deep', u = 'http://radiorecord.hostingradio.ru/deep96.aacp' },
        { n = 'Radio Record Hardstyle', u = 'https://radiorecord.hostingradio.ru/teo96.aacp' },
        { n = 'Radio Record HQ', u = 'https://air.unmixed.ru/record320' },
        { n = 'Radio Record Liquid Funk', u = 'https://radiorecord.hostingradio.ru/liquidfunk96.aacp' },
        { n = 'Radio Record Lo-Fi', u = 'https://radiorecord.hostingradio.ru/lofi96.aacp' },
        { n = 'Radio Record Megamix', u = 'https://radiorecord.hostingradio.ru/mix96.aacp' },
        { n = 'Radio Record Organic', u = 'http://radiorecord.hostingradio.ru/organic96.aacp' },
        { n = 'Radio Record Phonk', u = 'http://radiorecord.hostingradio.ru/phonk96.aacp' },
        { n = 'Radio Record Rock', u = 'https://hls-01-radiorecord.hostingradio.ru/record-rock/playlist.m3u8' },
        { n = 'Radio Record Synthwave', u = 'http://radiorecord.hostingradio.ru/synth96.aacp' },
        { n = 'Radio Record Trancehouse', u = 'https://radiorecord.hostingradio.ru/trancehouse96.aacp' },
        { n = 'Radio Russkiy Hit', u = 'https://stream.n340.com/19_ruhit_24' },
        { n = 'Radio Sefon', u = 'http://193.42.108.9:8010/stream' },
        { n = 'Radio Sibir', u = 'https://stream.radiosibir.ru:8093/om2' },
        { n = 'Radio Transmit', u = 'http://21220.web.hosting-russia.ru:8000/transmit' },
        { n = 'Radio Ultra', u = 'http://nashe1.hostingradio.ru/ultra-192.mp3' },
        { n = 'Radio Источник', u = 'http://s0.radioheart.ru:8000/VM73179' },
        { n = 'Radiogora - Electro', u = 'http://listen.radiogora.ru:8000/electro128' },
        { n = 'Radiomv Russian', u = 'https://ice.radiomv.co:8440/russian.mp3' },
        { n = 'Radiomv Russian Music', u = 'https://ice.radiomv.co:8440/russian_music.mp3' },
        { n = 'Radiomv Russian Old Testament', u = 'https://ice.radiomv.co:8440/russian_old_testament.mp3' },
        { n = 'Radiorecordru Techno', u = 'https://radiorecord.hostingradio.ru/techno96.aacp' },
        { n = 'RCM DEEP', u = 'https://relay.radiotoolkit.com/rcmdeep' },
        { n = 'Record Chill House', u = 'https://radiorecord.hostingradio.ru/chillhouse96.aacp' },
        { n = 'Record Hard Bass', u = 'https://radiorecord.hostingradio.ru/hbass96.aacp' },
        { n = 'Record Minimal', u = 'https://radiorecord.hostingradio.ru/mini96.aacp' },
        { n = 'Record Neurofunk', u = 'https://radiorecord.hostingradio.ru/neurofunk96.aacp' },
        { n = 'Record Trance Classics', u = 'https://radiorecord.hostingradio.ru/trancehits96.aacp' },
        { n = 'Record Trancemission', u = 'https://radiorecord.hostingradio.ru/tm96.aacp' },
        { n = 'Relax FM', u = 'https://pub0302.101.ru:8443/stream/air/aac/64/200' },
        { n = 'Relax FM 90,8 Moscow', u = 'http://pub0302.101.ru:8000/stream/trust/mp3/128/264' },
        { n = 'Relax FM Latino', u = 'https://pub0302.101.ru:8443/stream/trust/mp3/128/265' },
        { n = 'Relax FM Nature', u = 'https://pub0101.101.ru/stream/trust/mp3/128/263' },
        { n = 'Relax Smooth Jazz', u = 'https://pub0202.101.ru:8443/stream/trust/mp3/128/31' },
        { n = 'Remix FM', u = 'http://air4.amgradio.ru/RemixFM' },
        { n = 'ROCK FM', u = 'http://nashe1.hostingradio.ru/rock-128.mp3' },
        { n = 'Rockabilly - Caprice Radio', u = 'http://79.111.14.76:8000/rockabilly' },
        { n = 'Rockfmru Heavy', u = 'https://jfm1.hostingradio.ru:14536/metal.mp3' },
        { n = 'Royal Radio 968FM', u = 'https://c22.radioboss.fm/stream/186' },
        { n = 'Royal Trip Hop', u = 'https://royalradio.space/TH' },
        { n = 'Russian Punk Rock', u = 'http://79.120.77.11:8000/punkru' },
        { n = 'Russian Radio Golden Gramophone', u = 'http://rr-zolotoigrammofon.hostingradio.ru/zolotoigrammofon96.aacp' },
        { n = 'Russian Rap Hip Hop - Caprice Radio', u = 'http://79.120.77.11:8000/rapru' },
        { n = 'Russkoe Radio', u = 'http://rusradio.hostingradio.ru/rusradio96.aacp' },
        { n = 'SECTOR Jazz', u = 'http://89.223.45.5:8000/jazz-flac' },
        { n = 'SECTOR | Progressive Channel', u = 'http://89.223.45.5:8000/progressive-160' },
        { n = 'Silver Rain', u = 'http://silverrain.hostingradio.ru/silver128.mp3' },
        { n = 'Soundpark Deep', u = 'https://relay1.radiotoolkit.com/spdeep' },
        { n = 'Sovietwave', u = 'http://station.waveradio.org/soviet.mp3' },
        { n = 'Space Rock - Radio Caprice Acc48', u = 'http://79.111.119.111:8002/spacerock' },
        { n = 'Spacesynthru', u = 'http://listen2.myradio24.com:9000/1987' },
        { n = 'Spinner - Bossa Nova', u = 'https://live.radiospinner.com/bossa-nova-64' },
        { n = 'Sputnik Europe', u = 'https://nfw.ria.ru/flv/audio.aspx?ID=75651129&type=mp3' },
        { n = 'Sputnik Europe High', u = 'https://nfw.ria.ru/flv/audio.aspx?ID=36292119&type=mp3' },
        { n = 'Sputnik News Belarussian', u = 'https://nfw.ria.ru/flv/audio.aspx?ID=68862011&type=mp3' },
        { n = 'Stand Up', u = 'https://pub0102.101.ru:8443/stream/pro/aac/64/447' },
        { n = 'Street Beat FM', u = 'https://glassroomrec.s02.radio-tochka.com:5015/stream' },
        { n = 'STUDIO 21', u = 'http://icecast-studio21.cdnvideo.ru/S21cl_1r' },
        { n = 'Studio 21 Санкт-Петербург 955 FM', u = 'http://emgregion.hostingradio.ru:8064/spb.s21.mp3' },
        { n = 'Super-Radio Remix', u = 'https://listen2.myradio24.com/serz' },
        { n = 'Sw-Radio Russisch', u = 'http://www.segenswelle.de:8000/russisch' },
        { n = 'Techno Trance Techtrance', u = 'http://213.141.131.10:8000/techtrance.m3u' },
        { n = 'Test', u = 'https://pub0302.101.ru:8000/stream/pro/aac/64/158?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ij' },
        { n = 'Thrash Heavy Metal - Caprice Radio', u = 'http://213.141.131.10:8000/thrashheavy' },
        { n = 'THT Music Radio', u = 'http://tntradio.hostingradio.ru:8027/tntradio128.mp3' },
        { n = 'ULTRA', u = 'http://nashe1.hostingradio.ru/ultra-256' },
        { n = 'Ultrafan', u = 'http://radioultrafan.ru:8000/192' },
        { n = 'Uralsound FM', u = 'http://62.16.40.250:8000/uralsoundfm' },
        { n = 'URALSOUND FM | DEEP HOUSE', u = 'https://5.restream.one/1392_1' },
        { n = 'Verdure Station', u = 'http://air.verdure.net:8881/stream' },
        { n = 'World Radio Network Russian WRN', u = 'http://shoutcast.wrn.org:8025/WRN-R' },
        { n = 'Xddance', u = 'http://94.241.171.205:8000/stream' },
        { n = 'XXL FM', u = 'http://91.211.246.42:8000/XXL-FM' },
        { n = 'Yoga Radio', u = 'http://play.yogaradio.fm:8000/YOGAr256.m3u' },
        { n = 'Z-FM Фронтовое', u = 'https://zfm.hostingradio.ru/zfm128.mp3' },
        { n = 'Автодор', u = 'https://avtodor-tr.hostingradio.ru/avtodortr128.mp3' },
        { n = 'Авторадио - FM 903 - Москва', u = 'http://ic4.101.ru:8000/v3_1' },
        { n = 'Авторадио Дискотека 90 Х', u = 'https://pub0202.101.ru:8443/stream/pro/aac/64/74' },
        { n = 'Авторская Песня101', u = 'https://pub0101.101.ru:8000/stream/pro/aac/64/35' },
        { n = 'Азбука Молитвы', u = 'https://radio.azbyka.ru/azbyka-molitvy' },
        { n = 'Анекдот Фм', u = 'http://ic6.101.ru:8000/stream/trust/mp3/128/20' },
        { n = 'Армейские Песни 18+', u = 'https://stream.pcradio.ru/Armejskie_pesni-med' },
        { n = 'Бард-Радио', u = 'https://listen.myrh.ru/Bard-Radio' },
        { n = 'Беседка Для Друзей', u = 'https://pub0301.101.ru:8443/stream/air/mp3/256/200' },
        { n = 'Бизнес FM', u = 'https://bfm.hostingradio.ru:9075/fm' },
        { n = 'Бизнес ФМ Санкт-Петербург 1074 FM', u = 'http://bfmreg.hostingradio.ru/spb.bfm128.mp3' },
        { n = 'Бобинаsu', u = 'https://cp.time4radio.ru/listen/bobinasu/160' },
        { n = 'Веда Радио', u = 'http://listen.vedaradio.fm:8000/high.m3u' },
        { n = 'Вера', u = 'http://77.39.8.49:8000/vera_air_96' },
        { n = 'Вести FM', u = 'http://icecast.vgtrk.cdnvideo.ru/vestifm' },
        { n = 'Вести FM AAC', u = 'https://icecast-vgtrk.cdnvideo.ru/vestifm_aac_32kbps' },
        { n = 'Вести ФМ', u = 'https://icecast-vgtrk.cdnvideo.ru/vestifm_mp3_64kbps' },
        { n = 'Весёлый Dance - Радио Ваня', u = 'https://stream.pcradio.ru/vanya_fundance-med' },
        { n = 'Вечная Молодость', u = 'http://misato.ru-hoster.com:8037/stream' },
        { n = 'Владивосток FM', u = 'http://vladfm.ru:8000/vfm?1702126392317' },
        { n = 'Волгоград ФМ', u = 'http://online.volgogradfm.ru:8000/vfm' },
        { n = 'Волшебный Шансон', u = 'https://chanson.hostingradio.ru:8041/chanson128.mp3' },
        { n = 'Вольтаж FM', u = 'https://radio.voltagefm.ru:9009/VOLTAGEFM' },
        { n = 'Всемирная Радиосеть World Radio Network – Russia', u = 'http://streaming.edmradio.online:8025/WRN-R' },
        { n = 'Всесоюзное Радио', u = 'https://stream.cassiopeia-station.ru:1045/stream' },
        { n = 'Высоцкий', u = 'https://rr-vysockij.hostingradio.ru/vysockij96.aacp' },
        { n = 'Говорит Москва', u = 'http://media.govoritmoskva.ru:8880/ru64.mp3' },
        { n = 'Голос Бирмы', u = 'https://listen4.myradio24.com/39982' },
        { n = 'Голос Свободной России', u = 'http://freerutube.info:8000/live' },
        { n = 'Гопфм', u = 'https://radiorecord.hostingradio.ru/gop96.aacp' },
        { n = 'Град Петров', u = 'http://stream.grad-petrov.ru:8093/aac' },
        { n = 'Гусьдипхаус', u = 'https://stream.radiogoose.ru:8120/play' },
        { n = 'Гусьолдскул', u = 'https://stream.radiogoose.ru:8010/play' },
        { n = 'Движуха', u = 'https://myradio24.org/78805' },
        { n = 'Детский Канал - Русское Радио', u = 'https://rr-detskijkanal.hostingradio.ru/detskijkanal96.aacp' },
        { n = 'Детское Радио', u = 'http://ic7.101.ru:8000/v14_1' },
        { n = 'ДЕТСКОЕ РАДИО [DETSKOE RADIO BABY FM', u = 'http://a5.radioheart.ru:8012/nonstop' },
        { n = 'Диполь', u = 'https://icecast-sibinformburo.cdnvideo.ru/dipolfm' },
        { n = 'Дискач 90S Мегахит ДНР', u = 'http://stream.laut.fm/radio90s' },
        { n = 'Диско-Радио SOVA', u = 'https://evcast.mediacp.eu:1965/stream' },
        { n = 'ДИСКОТЕКА 90-Х', u = 'https://radiorecord.hostingradio.ru/sd9096.aacp?0968d4a7' },
        { n = 'Дискотека СССР', u = 'http://pub0302.101.ru:8000/stream/pro/aac/64/144?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjUuMTguMjQ4Ljk4IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6ODIuMCkgR2Vja29cLzIwMTAwMTAxIEZpcmVmb3hcLzgyLjAiLCJ1aWRfY2hhbm5lbCI6IjE0NCIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MDU5NjQ1MTZ9.Ln1wEJ8cHHzK_Ea6Zr8J8acdny0R9ShZ_KUKVf6TmQA' },
        { n = 'Домашнее Радио', u = 'https://www.liveradio.es/http://83.234.148.77:8001/domashnee' },
        { n = 'Дорожное Радио', u = 'http://dorognoe.hostingradio.ru:8000/radio' },
        { n = 'Дорожное Радио Dorognoe Radio', u = 'http://dorognoe.hostingradio.ru:8000/dorognoe' },
        { n = 'Дорожное Радио Танцы По-Русски', u = 'https://dorognoe.hostingradio.ru:8000/dorognoe1945.mp3' },
        { n = 'Дядя Ваня На Даче 18+', u = 'https://ic1.radiosignal.one/vanya-mp3' },
        { n = 'Европа Плюс', u = 'http://ep128server.streamr.ru:8030/ep128' },
        { n = 'Европа Плюс Вологда 1002 FM', u = 'http://emgregion.hostingradio.ru:8064/vologda.europaplus.mp3' },
        { n = 'Жара FM', u = 'https://live1.zharafm.ru/internet' },
        { n = 'Женский Stand Up', u = 'https://pub0102.101.ru:8443/stream/pro/aac/64/448' },
        { n = 'Жития Святых', u = 'https://radio.azbyka.ru/lives' },
        { n = 'За Друзей', u = 'https://listen2.myradio24.com/8144' },
        { n = 'За Облаками', u = 'http://195.88.63.114:8000/zaoblakami?type=.pls' },
        { n = 'Звезда', u = 'https://icecast-zvezda.mediacdn.ru/radio/zvezda/zvezda_128' },
        { n = 'Звезда 956 FM', u = 'https://radio.mediacdn.ru/radio/zvezda/zvezda_96' },
        { n = 'Золотой Аккордеон', u = 'https://pub0102.101.ru:8443/stream/personal/aacp/64/387928?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI3NGNjODVmNDQyMmViMTJiMjExODFiZmZmMjhjMTI4MiIsIklQIjoiMTA5LjE2NS45My4yMTciLCJVQSI6Ik1vem' },
        { n = 'Золотой Граммофон', u = 'https://rr-zolotoigrammofon.hostingradio.ru/zolotoigrammofon96.aacp' },
        { n = 'Искатель', u = 'http://iskatel.hostingradio.ru:8015/iskatel-128.mp3' },
        { n = 'Казак FM', u = 'https://radio.mediacdn.ru/kazak_fm.mp3' },
        { n = 'Калина Красная', u = 'http://icecast-studio21.cdnvideo.ru/KalynaK_1a' },
        { n = 'Кальян Рэп DFM', u = 'https://dfm-kalianrap.hostingradio.ru/kalianrap96.aacp' },
        { n = 'Камеди Радио Екатеринбург', u = 'https://pub0202.101.ru:8443/stream/reg/mp3/128/region_comedy_9' },
        { n = 'Карнавал', u = 'https://stream03.pcradio.ru/carnavalfmru-hi' },
        { n = 'Кекс FM', u = 'https://dorognoe.hostingradio.ru/keksfm64.aac' },
        { n = 'Классика Жанра', u = 'https://s.fmplay.ru/e9d523c7' },
        { n = 'Комерсант Kommersant FM 936 Moscow', u = 'http://kommersant77.hostingradio.ru:8016/kommersant64.mp3' },
        { n = 'Коммерсант', u = 'http://kommersant77.hostingradio.ru:8016/kommersant128.mp3' },
        { n = 'Коммерсантъ FM 936', u = 'https://kommersant77.hostingradio.ru:8085/kommersant128.mp3' },
        { n = 'Комсомольская Правда', u = 'https://kpradio.hostingradio.ru:8000/64' },
        { n = 'Комсомольская Правда Воронеж 977 FM', u = 'http://kpradio.hostingradio.ru:8000/voroneg.radiokp128.mp3' },
        { n = 'Красное Радио', u = 'https://myradio24.org/zuek1917' },
        { n = 'Культура AAC+', u = 'https://icecast-vgtrk.cdnvideo.ru/kulturafm_aac_64kbps' },
        { n = 'Күңел Радиосы', u = 'http://live.kunelradio.ru:8000/128.mp3' },
        { n = 'Легенда', u = 'https://radiolegenda.ru:8001/64.aac' },
        { n = 'Лидер', u = 'https://stream.volnorez.com/live-app/900927' },
        { n = 'Магадан ФМ', u = 'https://myradio24.org/magadanfm' },
        { n = 'Макс FM', u = 'https://maksfm.hostingradio.ru/maksfm320.mp3' },
        { n = 'Мария FM', u = 'http://mariafm.ru:8000/maria-fm.mp3' },
        { n = 'Маруся FM', u = 'http://radio-holding.ru:9000/marusya_aac_64' },
        { n = 'Маруся ФМ', u = 'https://listen.vdfm.ru:8000/marusya' },
        { n = 'Межзвёздное Радио', u = 'https://myradio24.org/97557' },
        { n = 'Милицейская Волна', u = 'https://radiomv.hostingradio.ru:80/radiomv256.mp3' },
        { n = 'Милицейская Волна НН', u = 'https://radiomv.hostingradio.ru:80/radiomv128.mp3' },
        { n = 'Мир Шансона', u = 'https://stream03.pcradio.ru/mir_shansona-med' },
        { n = 'Модель Для Сборки', u = 'http://mds-station.com:8000/mds' },
        { n = 'МУЗКОМ', u = 'https://geshou.s02.radio-tochka.com:5005/stream' },
        { n = 'Мухомор', u = 'https://listen7.myradio24.com/muhomor' },
        { n = 'На Шашлыки - Радио Рекорд', u = 'https://hls-01-radiorecord.hostingradio.ru/record-nashashlyki/playlist.m3u8' },
        { n = 'Наше Радио', u = 'http://nashe.streamr.ru/nashe-128.mp3' },
        { n = 'Наше Радио Классик Рок', u = 'http://nashe1.hostingradio.ru/nasheclassic.mp3' },
        { n = 'Наше Радио Панки-Хой', u = 'http://nashe1.hostingradio.ru/nashepunks.mp3' },
        { n = 'НВДА', u = 'http://misato.ru-hoster.com:8014/stream' },
        { n = 'Неслучайное Радио', u = 'http://aska.ru-hoster.com:8006/stream' },
        { n = 'Новое Радио 911 Спб', u = 'http://emgspb.hostingradio.ru/novoespb128.mp3' },
        { n = 'Новое Радио Воронеж 985 FM', u = 'http://emgregion.hostingradio.ru:8064/voronezh.novoe.mp3' },
        { n = 'Ностальгия', u = 'https://stream03.pcradio.ru/nostalgia_su-med' },
        { n = 'Ностальгия - Дорожное Радио', u = 'http://stream1.hostingradio.ru:8010/19_mp3_128' },
        { n = 'Ночной Звонок', u = 'https://listen7.myradio24.com/74828' },
        { n = 'Орфей', u = 'https://orfeyfm.hostingradio.ru:8034/orfeyfm96.aacp' },
        { n = 'Папино Радио', u = 'http://a1.radioheart.ru:8001/RH58197' },
        { n = 'Первое Железнодорожное Радио', u = 'https://www.liveradio.es/http://1zd.su:8050/radio' },
        { n = 'Первое Сетевой', u = 'http://streamer.radiovseti.ru:8000/128' },
        { n = 'Пилигрим', u = 'http://radiopiligrim.ru:8000/live' },
        { n = 'Пилигрим Библия', u = 'http://radiopiligrim.ru:8000/bible' },
        { n = 'Пилот FM - Dance', u = 'https://online.pilotfm.ru/pilot_dance' },
        { n = 'Пионер FM Russian Wave', u = 'https://ppr90.status-media.ru/ru-wave.mp3' },
        { n = 'Пионер ФМ Кассета', u = 'https://ppr90.status-media.ru/kasseta.mp3' },
        { n = 'Питер FM - Санкт-Петербург 1009 Мгц', u = 'http://icecast-piterfm.cdnvideo.ru/piterfm' },
        { n = 'Планета ФМ', u = 'https://radio-24.ru/audio2.php?url=http://fm.media56.ru:8000/Planeta' },
        { n = 'Победа ФM', u = 'http://node0.craftradio.ru:8000/169_2FC31C8F' },
        { n = 'Подвижник', u = 'https://radio.podvizhnik.ru:8005/stream' },
        { n = 'Портал', u = 'https://icecast-ext.dimfm.ru/portal' },
        { n = 'Посад', u = 'https://a1.radioheart.ru:9001/RH4122' },
        { n = 'Прибой', u = 'http://77.232.167.247:1007/admin' },
        { n = 'Приморская Волна 900 FM', u = 'http://inhold.org:8000/primvolna-ussuriysk' },
        { n = 'Радио 107', u = 'http://62.183.34.109:8000/radio107_256.mp3' },
        { n = 'Радио 54', u = 'http://91.202.68.50:8000/;stream.mp3' },
        { n = 'Радио 7 На Семи Холмах', u = 'http://radio7server.streamr.ru:8040/radio7256.mp3' },
        { n = 'РАДИО ENERGY - Москва 1042 FM', u = 'http://pub0302.101.ru:8000/stream/air/aac/64/99' },
        { n = 'Радио Maximum', u = 'https://maximum.hostingradio.ru/maximum128.mp3' },
        { n = 'Радио Sputnik Россия 256 Кбитс', u = 'https://icecast-rian.cdnvideo.ru/voicerushi' },
        { n = 'Радио STORY FM', u = 'https://storyfm.hostingradio.ru:8031/storyfm128.mp3?1701610665147' },
        { n = 'Радио «Luxury Lounge»', u = 'http://188.40.109.122:8000/ices1' },
        { n = 'Радио «Комсомольская Правда» | КП Россия', u = 'http://kpradio.hostingradio.ru:8000/russia.radiokp128.mp3' },
        { n = 'Радио АЛЬФА', u = 'https://online.alfafm.ru/alfa_mp3' },
        { n = 'Радио Атмосфера', u = 'http://185.64.76.49:8000/128.m3u' },
        { n = 'Радио Бесконечность', u = 'https://misato.ru-hoster.com:8067/stream' },
        { n = 'РАДИО ВАНЯ', u = 'https://icecast-radiovanya.cdnvideo.ru/radiovanya' },
        { n = 'Радио Ваня - Не Лихие 90-Е', u = 'https://stream.pcradio.ru/vanya_90-med' },
        { n = 'Радио Вести ФМ', u = 'http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_192kbps' },
        { n = 'Радио Восток России', u = 'http://138.201.190.251:8000/;stream.nsv' },
        { n = 'Радио Гамаюн', u = 'https://gamaun.online:8025/radio' },
        { n = 'Радио Гордость', u = 'https://rgordost.hostingradio.ru/rgordost64.aacp' },
        { n = 'Радио Гусь', u = 'https://stream.radiogoose.ru:8000/play' },
        { n = 'Радио Дача', u = 'http://217.19.211.252:8022/RadioDacha' },
        { n = 'Радио Джаз 89,1FM', u = 'http://jazz.streamr.ru/jazz-128.mp3' },
        { n = 'РАДИО ДЛЯ ВЗРОСЛЫХ', u = 'http://listen6.myradio24.com:9000/alex542888' },
        { n = 'Радио Для Двоих', u = 'https://icecast-radiofortwo.cdnvideo.ru/radiofortwo' },
        { n = 'Радио Душевные Песни', u = 'http://1dp.5cdn.ru:8000/dushevniepesni?time=1682183806914' },
        { n = 'Радио Забытая Кассета', u = 'https://casseta-disco.ru:6275/stream?x=1711899723831' },
        { n = 'Радио ЗВЕЗДА - Центральная Россия', u = 'https://zvezda-radio128.mediacdn.ru/radio/zvezda/zvezda_128' },
        { n = 'Радио Искатель', u = 'https://iskatel.hostingradio.ru:8015/iskatel-128.mp3' },
        { n = 'Радио Классик Classic Gold', u = 'http://jfm1.hostingradio.ru:14536/gcstream.mp3' },
        { n = 'Радио Классик Classic Vocals', u = 'http://jfm1.hostingradio.ru:14536/cvstream.mp3' },
        { n = 'Радио Книга', u = 'http://bookradio.hostingradio.ru:8069/fm' },
        { n = 'Радио Книга Вслух', u = 'https://radio-soyuz.ru:1045/stream' },
        { n = 'Радио Крым', u = 'https://fm.1tvcrimea.ru:19000/stream.mp3?608bbb38' },
        { n = 'Радио Культура', u = 'http://icecast.vgtrk.cdnvideo.ru/kulturafm' },
        { n = 'Радио Культура Radio Kultura', u = 'http://icecast.vgtrk.cdnvideo.ru/kulturafm_mp3_192kbps' },
        { n = 'Радио Маяк', u = 'https://icecast-vgtrk.cdnvideo.ru/mayakfm' },
        { n = 'Радио Маяк Radio Mayak', u = 'http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_192kbps' },
        { n = 'Радио МЕГАПОЛИС', u = 'http://online.radio-megapolis.ru:8000/megapolis' },
        { n = 'Радио МИР', u = 'https://icecast-mirtv.cdnvideo.ru/radio_mir_256' },
        { n = 'Радио Мир Барнаул', u = 'https://icecast-mirtv.cdnvideo.ru/radio_mir4_256' },
        { n = 'Радио Монте Карло', u = 'https://montecarlo.hostingradio.ru/montecarlo128.mp3' },
        { n = 'Радио Монте Карло - Bossa Nova', u = 'https://mc-mcbossa.hostingradio.ru/mcbossa96.aacp' },
        { n = 'Радио Монте Карло - Chill Lounge', u = 'https://mc-chilllonge.hostingradio.ru/chilllonge96.aacp' },
        { n = 'Радио Монте Карло - Covers', u = 'https://mc-covers.hostingradio.ru/mccovers96.aacp' },
        { n = 'Радио Монте Карло - Meditation', u = 'https://mc-meditation.hostingradio.ru/meditation96.aacp' },
        { n = 'Радио Монте Карло - Wonderful Blues', u = 'https://mc-blues.hostingradio.ru/blues96.aacp' },
        { n = 'Радио Монте-Карло', u = 'https://mc-mcgold.hostingradio.ru/mcgold96.aacp' },
        { n = 'Радио Москвы', u = 'https://icecast-vgtrk.cdnvideo.ru/moscowtalk128?v=1640610887877' },
        { n = 'Радио Новая Жизнь', u = 'https://nlradio.stream/hifi' },
        { n = 'Радио НОД', u = 'https://s05.volnorez.com/live-app/855343' },
        { n = 'Радио Ностальжи Россия', u = 'http://listen7.myradio24.com:9000/alexx333.m3u' },
        { n = 'Радио Олдхит', u = 'http://radio.oldxit.ru:8030/radio' },
        { n = 'Радио Орфей - Клавир 256Kbps', u = 'https://channels.fonotron.ru:8000/Chan_77_256.mp3' },
        { n = 'Радио Орфей - Классика Без Границ 192Kbps', u = 'https://orfeyfm.hostingradio.ru:8034/orpheuscwb192.mp3' },
        { n = 'Радио Орфей - Классика Киномузыки', u = 'https://channels.fonotron.ru:8000/Chan_9_192.mp3' },
        { n = 'Радио Орфей - Классика Эстрады', u = 'https://channels.fonotron.ru:8000/Chan_7_192.mp3' },
        { n = 'Радио Орфей - Популярная Классика 256Kbps', u = 'https://channels.fonotron.ru:8000/Chan_72_256.mp3' },
        { n = 'Радио Орфей - Русская Классика 256Kbps', u = 'https://channels.fonotron.ru:8000/Chan_73_256.mp3' },
        { n = 'Радио Орфей 992 FM', u = 'http://orfeyfm.hostingradio.ru:8034/orfeyfm192.mp3' },
        { n = 'Радио Пассаж', u = 'http://listen.radiopassazh.ru/aac-48' },
        { n = 'Радио Патриот', u = 'http://radio.mixto.ru:8001/patriot' },
        { n = 'Радио Петербург', u = 'https://radio.5-tv.ru/radio.mp3' },
        { n = 'Радио Радонеж Москва 7292 УКВ', u = 'http://icecast.radonezh.cdnvideo.ru:8000/rad128' },
        { n = 'Радио Редкие Рыбы - Rare Fishes Radio', u = 'https://listen1.myradio24.com/8317' },
        { n = 'Радио Рекорд - Dream Dance', u = 'https://hls-01-radiorecord.hostingradio.ru/record-dream/playlist.m3u8' },
        { n = 'Радио Рекорд - Russian Gold', u = 'https://hls-01-radiorecord.hostingradio.ru/record-russiangold/playlist.m3u8' },
        { n = 'Радио Рекорд - Нафталин FM', u = 'https://hls-01-radiorecord.hostingradio.ru/record-naft/playlist.m3u8' },
        { n = 'РАДИО РЕКОРД 256K', u = 'http://radiorecord.hostingradio.ru/rr_spb' },
        { n = 'Радио Рекорд Black Rap', u = 'http://radiorecord.hostingradio.ru/yo96.aacp' },
        { n = 'Радио Рекорд Eurodance', u = 'http://radiorecord.hostingradio.ru/eurodance96.aacp' },
        { n = 'Радио Рекорд Jungle', u = 'http://radiorecord.hostingradio.ru/jungle96.aacp' },
        { n = 'Радио Рекорд Neurofunk', u = 'http://radiorecord.hostingradio.ru/neurofunk96.aacp' },
        { n = 'Радио Рекорд Rap Hits', u = 'http://radiorecord.hostingradio.ru/rap96.aacp' },
        { n = 'Радио Рекорд Remix', u = 'http://radiorecord.hostingradio.ru/rmx96.aacp' },
        { n = 'Радио Рекорд Russian Hits', u = 'http://radiorecord.hostingradio.ru/russianhits96.aacp' },
        { n = 'Радио Рекорд Russian Mix', u = 'http://radiorecord.hostingradio.ru/rus96.aacp' },
        { n = 'Радио Рекорд Медляк FM', u = 'http://radiorecord.hostingradio.ru/mdl96.aacp' },
        { n = 'Радио Рекорд Нафталин FM', u = 'http://radiorecord.hostingradio.ru/naft96.aacp' },
        { n = 'Радио Рекорд Основной Канал', u = 'http://radiorecord.hostingradio.ru/rr_main96.aacp' },
        { n = 'Радио Рекорд Супердискотека 90-Х', u = 'http://radiorecord.hostingradio.ru/sd9096.aacp' },
        { n = 'Радио Республика ФМ 1048 FM', u = 'http://193.228.161.99:8080/republic.fm' },
        { n = 'Радио Ретроклуб', u = 'http://retroclub.hostingradio.ru/retroclub128.aacp' },
        { n = 'Радио Родные Песни', u = 'https://rodpesni.amgradio.ru/rp' },
        { n = 'Радио Родных Дорог', u = 'http://stream1.radiord.ru:8000/live96.aac' },
        { n = 'Радио Романтика', u = 'https://pub0202.101.ru:8443/stream/air/aac/64/101' },
        { n = 'Радио России AAC', u = 'http://icecast.vgtrk.cdnvideo.ru/rrzonam_aac_32kbps' },
        { n = 'Радио России Radio Russia', u = 'http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps' },
        { n = 'Радио России Калуга', u = 'http://radio.gtrk-kaluga.ru/russiafm_kaluga' },
        { n = 'Радио России Приморье', u = 'http://mp3.vestiprim.ru:8000/Radio128' },
        { n = 'Радио Русские Песни', u = 'http://listen.rusongs.ru/ru-mp3-128' },
        { n = 'Радио Сахаров', u = 'https://icecast.correctiv.net/sacharow' },
        { n = 'Радио Сева Radio Seva Novgorodsev', u = 'https://seva.ru/radio/stream' },
        { n = 'Радио Сектор Sector Geny Flac', u = 'http://89.223.45.5:8000/geny-flac' },
        { n = 'Радио Сектор Sector NEXT Flac', u = 'http://89.223.45.5:8000/next-flac' },
        { n = 'Радио Сектор Sector Nota Flac', u = 'http://89.223.45.5:8000/nota-flac' },
        { n = 'Радио Сектор Sector Progressive Flac', u = 'http://89.223.45.5:8000/progressive-flac' },
        { n = 'Радио Сектор Sector SPACE', u = 'http://89.223.45.5:8000/space-160' },
        { n = 'Радио Сектор Sector SPACE Flac', u = 'http://89.223.45.5:8000/space-flac' },
        { n = 'Радио Советская ВОЛНА', u = 'https://www.liveradio.es/http://station.waveradio.org/soviet' },
        { n = 'Радио СПУТНИК Radio Sputnik', u = 'http://online.sputnikfm.ru:8000/sputnik_mp3' },
        { n = 'Радио СССР', u = 'https://myradio24.org/ussr' },
        { n = 'Радио ТВ Твоя Волна', u = 'https://icecast-tvoyavolna.cdnvideo.ru/tvoyavolna' },
        { n = 'Радио Турист', u = 'https://listen7.myradio24.com/turist' },
        { n = 'Радио Шансон - Radio Shanson', u = 'http://chanson.hostingradio.ru:8041/chanson256.mp3' },
        { n = 'Радио Шоколад', u = 'https://choco.hostingradio.ru:10010/fm' },
        { n = 'Радио Эрмитаж', u = 'http://hermitage.hostingradio.ru/hermitage128.mp3' },
        { n = 'Радио Юность', u = 'http://icecast-vgtrk.cdnvideo.ru/unost_mp3_192kbps' },
        { n = 'Радиоканал Мелодия', u = 'http://stream128.melodiafm.spb.ru:8000/melodia128' },
        { n = 'Радиола', u = 'http://online1.gkvr.ru:8000/radiola_eka_128.mp3' },
        { n = 'Радиостация Маяк Москва 128Kbs', u = 'http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_128kbps' },
        { n = 'Радонеж', u = 'http://icecast.radonezh.cdnvideo.ru:8000/rad' },
        { n = 'Ралио Релакс Москва 90,8 FM', u = 'http://pub0302.101.ru:8000/stream/air/aac/64/200' },
        { n = 'Рекорд Чилл', u = 'http://radiorecord.hostingradio.ru/chil96.aacp' },
        { n = 'Релиз', u = 'https://listen.myrh.ru/radioreliz' },
        { n = 'Ретро FM', u = 'http://retroserver.streamr.ru:8043/retro256.mp3' },
        { n = 'РЕТРО FM 320K', u = 'http://emgregion.hostingradio.ru:8064/moscow.retrofm.mp3' },
        { n = 'Ретро FM 70E', u = 'http://retro70.hostingradio.ru:8025/retro70-128.mp3' },
        { n = 'Ретро FM 90E', u = 'http://retro90.hostingradio.ru:8025/retro90-128.mp3' },
        { n = 'Ретро FM Санкт-Петербург 128 Kbps, Mp3', u = 'http://emgspb.hostingradio.ru/retrofmspb128.mp3' },
        { n = 'Ретро FM — Вечеринка', u = 'https://hls-01-retro-vecherinka.emgsound.ru/20/playlist.m3u8' },
        { n = 'Ретро ФМ', u = 'http://retroserver.streamr.ru:8043/retro128' },
        { n = 'Родные Нулевые - Русское Радио', u = 'https://rr-00.hostingradio.ru/rr0096.aacp' },
        { n = 'Рок АРСЕНАЛ - Rock Arsenal', u = 'http://online.rockarsenal.ru:8000/rockarsenal' },
        { n = 'Рок-Атака', u = 'https://myradio24.org/rockataka' },
        { n = 'Роксана Радиосы', u = 'https://listen1.myradio24.com/2761' },
        { n = 'Романтический Шансон', u = 'http://chanson.hostingradio.ru:8041/chanson-romantic256.mp3' },
        { n = 'Россия 90-Х', u = 'https://pub0202.101.ru:8443/stream/pro/aac/64/33' },
        { n = 'Рояль', u = 'https://c22.radioboss.fm:18186/stream' },
        { n = 'Русский Формат', u = 'https://casseta-disco.ru:1070/stream' },
        { n = 'Русское Радио', u = 'https://rusradio.hostingradio.ru/rusradio96.aacp' },
        { n = 'Русское Радио: Русский Рок', u = 'https://rr-russkijrok.hostingradio.ru/russkijrok96.aacp.m3u' },
        { n = 'Садовод', u = 'https://stream.cassiopeia-station.ru:1315/stream' },
        { n = 'СВЕЖЕЕ Europa Plus', u = 'http://hls-01-fresh.emgsound.ru/9/playlist.m3u8' },
        { n = 'Свободное Радио', u = 'http://nradio.net/free' },
        { n = 'СВОЕFM | DEEP RADIO', u = 'http://relay4.radiotoolkit.com/svoefm' },
        { n = 'Своё Радио', u = 'http://svoeradiofm.hostingradio.ru:8032/svoe-320.mp3' },
        { n = 'Серебряный Дождь', u = 'http://213.59.4.27:8000/silver128.mp3' },
        { n = 'Сказка FM', u = 'https://skazka.amgradio.ru/Skazka' },
        { n = 'Сказочное', u = 'https://listen6.myradio24.com/fairytale' },
        { n = 'Советская Классика', u = 'https://rr-sovclass.hostingradio.ru/sovclass96.aacp' },
        { n = 'Советская Эстрада', u = 'https://evcast.mediacp.eu:2075/stream' },
        { n = 'Советские Песни', u = 'https://sovetskie-pesni.ru:8005/stream' },
        { n = 'Соловьёв FM', u = 'https://solovievfm.hostingradio.ru/solovievfm32.aacp' },
        { n = 'Соловьёв LIVE', u = 'https://solovievfm.hostingradio.ru/solovievfm128.aacp' },
        { n = 'Соль Fm Соликамск', u = 'https://www.liveradio.es/http://solfm.ru:8000/online128' },
        { n = 'Союз ФМ', u = 'http://soyuzfm.su:8100//soyuzfm-320.mp3?1702169748633' },
        { n = 'Спокойное Радио', u = 'https://listen1.myradio24.com/6262' },
        { n = 'СПРАВЕДЛИВАЯ РОССИЯ', u = 'https://spravedlivo.hostingradio.ru:8022/spravedlivo128.mp3' },
        { n = 'Спутник', u = 'https://icecast-rian.cdnvideo.ru/voicerus' },
        { n = 'Спутник 912 Fm', u = 'https://stream03.pcradio.ru/sputnik_ria_ru-med' },
        { n = 'Старое Радио - Old Radio', u = 'http://195.91.237.50:8000/ices128' },
        { n = 'Старое Радио - Old Radio 32', u = 'http://195.91.237.50:8000/ices32' },
        { n = 'Старое Радио - Old Radio 64', u = 'http://195.91.237.50:8000/ices64' },
        { n = 'Старое Радио - Музыка', u = 'http://www.staroeradio.ru/music128.m3u' },
        { n = 'Старое Радио Детское - Old Radio Detskoe', u = 'http://195.91.237.50:8000/detskoe128' },
        { n = 'Старое Радио Детское - Old Radio Detskoe 64', u = 'http://195.91.237.50:8000/detskoe64' },
        { n = 'Старый Портфель', u = 'https://lk.castnow.ru:8100/oldbrief-320.mp3' },
        { n = 'Твой День', u = 'http://a7.radioheart.ru:8035/RH8851' },
        { n = 'Удалое Радио', u = 'http://l29.no-ip.org:8002/listen.pls' },
        { n = 'Умное Радио', u = 'http://umnoe.amgradio.ru/Umnoe' },
        { n = 'ХАЙП FM', u = 'https://hfm.amgradio.ru/HypeFM' },
        { n = 'ХИТ FM', u = 'https://hitfm.hostingradio.ru/hitfm128.mp3?48c22b78' },
        { n = 'Хорошее Радио', u = 'https://hr.amgradio.ru/Horoshee' },
        { n = 'Чипльдук', u = 'http://radio.4duk.ru/4duk128.mp3' },
        { n = 'Читаем Добротолюбие', u = 'https://radio.azbyka.ru/dobrotolubie' },
        { n = 'Читаем Евангелие', u = 'https://radio.azbyka.ru/evangelie' },
        { n = 'Шансон Без Цензуры', u = 'http://chanson.hostingradio.ru:8041/chanson-uncensored256.mp3' },
        { n = 'ШАНСОН БЕЗ ЦЕНЗУРЫ [CHANSONUNCENSORED]', u = 'http://chanson.hostingradio.ru:8041/chanson-uncensored128.mp3' },
        { n = 'Шансон Радио', u = 'http://chanson.hostingradio.ru:8041/chanson128.mp3' },
        { n = 'Эльдорадио Eldo Radio 1014 St Petersburg', u = 'http://emgspb.hostingradio.ru/eldoradio128.mp3' },
        { n = 'Эхо Online', u = 'https://noasrv.caster.fm:10034/stream' },
        { n = 'ЭХО Лосей', u = 'https://icecast-radioosc.cdnvideo.ru/radioosc64' },
        { n = 'Юмор FM', u = 'http://pub0101.101.ru:8000/stream/air/aac/64/102' },
        { n = 'Юнитон', u = 'https://online.uniton.ru/uniton/started_at_1715197553405' },
        { n = 'ЯНФМ Диско 90Х РФ', u = 'https://stream.laut.fm/radio90s' },
        { n = 'Ясен Бит 18+', u = 'https://5.restream.one/1198_1' },
    }
}
