return {
    ['the_united_kingdom'] = {
        { n = '#1980S Zoom', u = 'https://samcloud.spacial.com/api/listen?sid=111415&rid=194939&f=mp3,any&br=128000,any&m=sc' },
        { n = '10 Radio 1053 - Wiveliscombe', u = 'http://live.canstream.co.uk:8000/10radio.mp3' },
        { n = '100 Hitz', u = 'http://206.217.213.235:8290/' },
        { n = '100% Hip Hop | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape2' },
        { n = '1018 WCR FM', u = 'https://stream3.themediasite.co.uk:8312/stream?_=580911' },
        { n = '1059 Academy FM Folkestone', u = 'http://s2.xrad.io:8080/stream' },
        { n = '1078 Black Diamond FM', u = 'https://icecast-s.bdfm.radio/blackdiamondfm?icecast' },
        { n = '1940S Radio HS - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/1940sradio/stream' },
        { n = '1940S Radio Station', u = 'https://control.internet-radio.com:2199/tunein/1940sradio.pls' },
        { n = '1Mix EDM Radio', u = 'http://fr1.1mix.co.uk:8060/' },
        { n = '1Mix Radio - EDM UK 320Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/320h' },
        { n = '1Mix Radio - EDM UK 32Kb Aac+', u = 'http://fr2.1mix.co.uk:9000/aach' },
        { n = '1Mix Radio - House UK 128Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/128hb' },
        { n = '1Mix Radio - House UK 192Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/192hb' },
        { n = '1Mix Radio - House UK 320Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/320hb' },
        { n = '1Mix Radio - House UK 32Kb Aac+', u = 'http://fr2.1mix.co.uk:9000/aachb' },
        { n = '1Mix Radio - Trance #1 UK 128Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/128' },
        { n = '1Mix Radio - Trance #1 UK 192Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/192' },
        { n = '1Mix Radio - Trance #1 UK 320Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/320' },
        { n = '1Mix Radio - Trance #1 UK 32Kb Aac+', u = 'http://fr2.1mix.co.uk:9000/aac' },
        { n = '1Mix Radio - Trance UK 128Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/128b' },
        { n = '1Mix Radio - Trance UK 192Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/192b' },
        { n = '1Mix Radio - Trance UK 320Kb Mp3', u = 'http://fr2.1mix.co.uk:9000/320b' },
        { n = '24-7 Decades', u = 'https://antares.dribbcast.com:2199/tunein/s8120.pls' },
        { n = '24-7 Disco', u = 'https://antares.dribbcast.com/proxy/s8190/stream' },
        { n = '24-7 Dreamboats And Petticoats', u = 'https://antares.dribbcast.com:2199/tunein/s8100.pls' },
        { n = '24-7 Just Rock', u = 'https://antares.dribbcast.com:2199/tunein/s8170.pls' },
        { n = '24-7 Legends', u = 'https://antares.dribbcast.com:2199/tunein/s8160.pls' },
        { n = '24-7 Legends Classic Rock', u = 'https://antares.dribbcast.com:2199/tunein/s8180.pls' },
        { n = '24-7 Motown', u = 'https://antares.dribbcast.com:2199/tunein/s8110.pls' },
        { n = '24-7 Party', u = 'https://antares.dribbcast.com:2199/tunein/s8240.pls' },
        { n = '24-7 Psychedelic Rock', u = 'https://antares.dribbcast.com:2199/tunein/s8150.pls' },
        { n = '24-7 Reggae', u = 'https://antares.dribbcast.com:2199/tunein/s8200.pls' },
        { n = '24-7 Rock ‘N’ Roll', u = 'https://antares.dribbcast.com:2199/tunein/s8130.pls' },
        { n = '24-7 Soul', u = 'https://antares.dribbcast.com:2199/tunein/s8300.pls' },
        { n = '24-7 The 70S', u = 'https://antares.dribbcast.com:2199/tunein/s8260.pls' },
        { n = '24-7 The ’60S', u = 'https://antares.dribbcast.com:2199/tunein/s8220.pls' },
        { n = '242 RADIO', u = 'http://uk7.internet-radio.com:8168/stream' },
        { n = '247 Lofi Radio', u = 'https://ec3.yesstreaming.net:3755/stream' },
        { n = '247 Restaurant Radio', u = 'https://ec6.yesstreaming.net:1655/stream' },
        { n = '247 Spa Radio', u = 'https://ec6.yesstreaming.net:2915/stream' },
        { n = '4 To The Floor | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape5' },
        { n = '4Tunesfm', u = 'https://c30.radioboss.fm:18274/stream' },
        { n = '60 North Radio', u = 'https://cdn1.zetcast.net/stream' },
        { n = '60S Swinging Radio', u = 'http://s2.xrad.io:8058/listen.pls' },
        { n = '80S 90S', u = 'http://radioradio.ddns.net:8000/8090' },
        { n = '80S Heart', u = 'https://samcloud.spacial.com/api/listen?sid=111415&80s-heart&live' },
        { n = '80S Music Station MP3', u = 'http://stream.zeno.fm/1fm38n8f74zuv' },
        { n = '80S Rhythm', u = 'https://stream.mybroadbandradio.com/80srhythmhq/' },
        { n = '80S Zoom - London MP3', u = 'http://stream.zeno.fm/441fkks8ya0uv' },
        { n = '97 Country FM', u = 'https://vistaradio.streamb.live/SB00040?___cb=491767877535127' },
        { n = 'Aah Classical Radio - Bach', u = 'http://hearme.fm:10001/stream' },
        { n = 'ABC Oldies Radio', u = 'https://carina.streamerr.co/stream/abcoldiesradio' },
        { n = 'Ace Cafe Radio', u = 'https://listen.radioking.com/radio/69079/stream/106852' },
        { n = 'Actual Radio', u = 'https://securestreams.autopo.st:1174/;' },
        { n = 'Alpha Wave Radio', u = 'https://listentomystream.com:8068/stream' },
        { n = 'American Gold - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/americangold/stream' },
        { n = 'Anchor Radio', u = 'http://station.anchor.radio:8000/live192.mp3' },
        { n = 'Angel Radio HQ', u = 'http://s2.xrad.io:8522/listen.pls?sid=1' },
        { n = 'Arfm', u = 'http://108.163.245.230:9016/listen.pls' },
        { n = 'Atlantic 252', u = 'https://stream4.themediasite.co.uk:8042/' },
        { n = 'Aycliffe Radio', u = 'https://solid41.streamupsolutions.com/proxy/catidbxp?mp=/;type=mp3' },
        { n = 'Bailiwick Radio Classics', u = 'http://streaming.radio.co/s20224a067/listen' },
        { n = 'Banita Maxx Radio', u = 'http://91.232.4.33:9454/stream' },
        { n = 'Bar Latina Radio', u = 'https://s2.citrus3.com:2000/stream/barlatinaradio' },
        { n = 'BBC For Australasia', u = 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_australasia' },
        { n = 'BBC Tv', u = 'http://stream.live.vc.bbcmedia.co.uk/bbc_world_service?s=1619733260&e=1619747660&h=f8bc47f18c4b24de16cf2efa7951f91d' },
        { n = 'BBC World Service For East Asia', u = 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_east_asia' },
        { n = 'Bcfm 932', u = 'https://bcfmradiomain.radioca.st/live.mp3' },
        { n = 'BEST SMOOTH JAZZ - UK', u = 'http://64.95.243.43:8002/listen.pls?sid=1' },
        { n = 'Beware The Radio', u = 'https://bewaretheradio.out.airtime.pro/bewaretheradio_a' },
        { n = 'Beyond Radio', u = 'https://stream.beyondradio.co.uk/radio/8000/high' },
        { n = 'BFBS Beats', u = 'https://edge-audio-01-cr.sharp-stream.com/ssvcbfbs20.aac?device=bfbs_beats' },
        { n = 'BFBS Brunei', u = 'http://tx.sharp-stream.com/icecast.php?i=ssvcbfbs10.aac' },
        { n = 'BFBS Gurkha Radio', u = 'http://tx.sharp-stream.com/icecast.php?i=ssvcbfbs3.mp3' },
        { n = 'BFBS Scotland', u = 'http://tx.sharp-stream.com/icecast.php?i=ssvcbfbs18.aac' },
        { n = 'Big Beat Radio', u = 'http://s4.citrus3.com:8366/stream' },
        { n = 'Big L 1', u = 'http://stream4.nsupdate.info:8100/biglh.mp3' },
        { n = 'Bigrigfm', u = 'https://live.bigrig.fm/' },
        { n = 'Bloop London Radio', u = 'https://radio.canstream.co.uk:8058/live.mp3' },
        { n = 'Bolton FM', u = 'https://radio.canstream.co.uk:8083/live.mp3' },
        { n = 'Boom', u = 'http://edge-audio-03-gos2.sharp-stream.com/65_boom_radio_live_320' },
        { n = 'Boom Light', u = 'https://listen-boomradio.sharp-stream.com/65_boom_light_128_mp3' },
        { n = 'Boom Radio', u = 'https://listen-boomradio.sharp-stream.com/65_boom_radio_live_128' },
        { n = 'Boom Radio UK', u = 'https://listen-boomradio.sharp-stream.com/65_boom_radio_live_192' },
        { n = 'Boot Boy Radio', u = 'https://streaming04.liveboxstream.uk/proxy/dwain?mp=/stream' },
        { n = 'Box Laugh', u = 'https://play.streamafrica.net/laughnetwork' },
        { n = 'Box Office Radio', u = 'https://s2.citrus3.com:8400/stream' },
        { n = 'Box Old Time Radio', u = 'https://play.streamafrica.net/oldtimeradio' },
        { n = 'Breezy Radio UK', u = 'http://listen-nation.sharp-stream.com/breezyradiouk.mp3?ref=RF' },
        { n = 'Bristol Sound Webradio', u = 'https://thebristolsoundwebradio.stream.laut.fm/thebristolsoundwebradio' },
        { n = 'Britcom 1 - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/britcom1/stream' },
        { n = 'Britcom 2 - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/britcom2/stream' },
        { n = 'Britcom 3 - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/britcom3/stream' },
        { n = 'British Comedy 1', u = 'http://streaming04.liveboxstream.uk:8077/stream' },
        { n = 'British Comedy 2', u = 'http://streaming05.liveboxstream.uk:8009/stream' },
        { n = 'BSJ', u = 'http://64.95.243.43:8002/stream' },
        { n = 'Cam FM 972', u = 'https://stream.camfm.co.uk/camfm' },
        { n = 'Capital Chill', u = 'https://media-ssl.musicradio.com/CapitalChill' },
        { n = 'Capital Dance', u = 'https://icecast.thisisdax.com/CapitalDanceMP3' },
        { n = 'Capital FM AAC', u = 'http://ice-the.musicradio.com/Capital' },
        { n = 'Capital FM Birmingham', u = 'https://media-ice.musicradio.com/CapitalBirminghamMP3' },
        { n = 'Capital FM Cymru', u = 'http://media-ice.musicradio.com/CapitalCymru' },
        { n = 'Capital FM Edinburgh', u = 'http://ice-sov.musicradio.com/CapitalEdinburghMP3' },
        { n = 'Capital FM London', u = 'http://media-ice.musicradio.com/CapitalMP3' },
        { n = 'Capital FM Nottinghamshire', u = 'http://icecast.thisisdax.com/CapitalNottinghamshireMP3' },
        { n = 'Capital Nottinghamshire', u = 'https://media-ice.musicradio.com/CapitalNottinghamshireMP3' },
        { n = 'Capital UK', u = 'http://vis.media-ice.musicradio.com/CapitalUK' },
        { n = 'Capital XTRA', u = 'http://media-the.musicradio.com/CapitalXTRALondonMP3' },
        { n = 'Castle Radio', u = 'https://c36.radioboss.fm:8114/stream' },
        { n = 'Castledown FM', u = 'https://ukwesta.streaming.broadcast.radio/castledownfm?1724598379941' },
        { n = 'CDNX Radio', u = 'https://streaming.cdnx.co.uk/proxy/cx128mp3?mp=/stream&___cb=870564735813642' },
        { n = 'Celtic Music Radio', u = 'http://stream.celticmusicradio.net:8000/celticmusic.mp3' },
        { n = 'Centreforce Radio', u = 'https://listen.centreforceradio.com/96' },
        { n = 'Chocolate-Radiocom', u = 'https://stream.radio.co/sa7336b687/listen' },
        { n = 'Choice FM UK', u = 'https://cdn.choicefm.uk/stream;' },
        { n = 'Classic FM', u = 'http://media-ice.musicradio.com/ClassicFMMP3' },
        { n = 'Classic FM At The Movies', u = 'http://media-sov.musicradio.com/ClassicFM-M-Movies' },
        { n = 'Classic FM Essential Classical', u = 'https://icecast.thisisdax.com/ClassicFM-M-Essential' },
        { n = 'Classic FM Hall Of Fame', u = 'https://icecast.thisisdax.com/ClassicFM-M-HOF' },
        { n = 'Classic FM Music For Pets', u = 'https://media-ssl.musicradio.com/ClassicFM-M-Pets' },
        { n = 'Classic FM Relax', u = 'http://media-the.musicradio.com/ClassicFM-M-Relax' },
        { n = 'Classic FM UK', u = 'http://ice-the.musicradio.com/ClassicFMMP3' },
        { n = 'Classic FM Video Game Music', u = 'https://icecast.thisisdax.com/ClassicFM-M-Gaming' },
        { n = 'Coolvibes-Reloaded', u = 'http://boogie.vside-radio.com:8406/stream' },
        { n = 'Coran Radio', u = 'https://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABhdgGORQA-2acfyF3_4WY2g' },
        { n = 'Cosmic Fuzzfm', u = 'https://playerservices.streamtheworld.com/api/livestream-redirect/SAM04AAC335.mp3' },
        { n = 'Crackers Radio', u = 'https://crackersfresh.radioca.st/;' },
        { n = 'Crime Incorporated - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/crimeinc/stream' },
        { n = 'Cruiseone Radio', u = 'https://solid24.streamupsolutions.com/proxy/cmxicxxx?mp=/256kbps' },
        { n = 'Dance Anthems Radio', u = 'https://stream3.themediasite.co.uk/stream/danceanthems' },
        { n = 'Dance Revolution', u = 'https://s5.radio.co/s89dcf578d/listen' },
        { n = 'Dance UK', u = 'http://51.89.148.171:8022/stream/' },
        { n = 'Dance UK Danceradioukcom 48K AAC+', u = 'http://uk2.internet-radio.com:8024/stream' },
        { n = 'Dance UK Radio Danceradiouk', u = 'http://51.89.148.171:8022/stream' },
        { n = 'Dancefmlive Trance', u = 'https://broadcast.dancefmlive.com/radio/8010/radio.mp3' },
        { n = 'Danceradiouk - Dance UK', u = 'http://uk2.internet-radio.com:8024/listen.pls' },
        { n = 'Dandelion Radio', u = 'http://stream.dandelionradio.com:9414/' },
        { n = 'Davide Of MIMIC', u = 'https://streaming04.liveboxstream.uk/proxy/davideof?mp=/stream' },
        { n = 'Deepvibes Radio', u = 'http://88.208.218.19:8090/stream' },
        { n = 'Deepvibuk', u = 'http://deepvibes.co.uk:9106/' },
        { n = 'Different Drumz Dnb Radio', u = 'http://andromeda.shoutca.st:8031/' },
        { n = 'Dirty Radio For Underworld Fans', u = 'https://live.dirty.radio/stream' },
        { n = 'Discover Trance Radio', u = 'https://uk01.discovertrance.com/;.mp3' },
        { n = 'Diva Radio - Funk Disco Music Paradise', u = 'https://stream.deevaradio.net:10443/divaradiofunk' },
        { n = 'Diva Radio Disco', u = 'https://stream.deevaradio.net:10443/divaradiodisco' },
        { n = 'Divine Radio London', u = 'https://uk2.internet-radio.com/proxy/divinestream?mp=/stream' },
        { n = 'Djremix Club', u = 'http://curiosity.shoutca.st:8114/;' },
        { n = 'Dnb Liquified', u = 'http://antares.dribbcast.com:5000/stream' },
        { n = 'Dnb Station', u = 'http://dnbstation.com:8005/listen.mp3' },
        { n = 'Dnbradiocom', u = 'https://fw.dnbradio.com/dnbradio_main.mp3' },
        { n = 'Do You Radio', u = 'https://doyouworld.out.airtime.pro/doyouworld_a' },
        { n = 'Dragon Radio', u = 'https://listen-nation.sharp-stream.com/tcnationdigital.mp3' },
        { n = 'Drystone Radio', u = 'https://uksoutha.streaming.broadcast.radio/drystoneradio?1724596500437' },
        { n = 'Dubterrain', u = 'http://ic2255.c471.fast-serv.com/listen' },
        { n = 'Dune Radio', u = 'https://stream.aiir.com/3phqulqckaguv?_=981158' },
        { n = 'East Point Radio', u = 'https://streaming.radio.co/s3c76b154e/listen' },
        { n = 'Easy 50S', u = 'https://streaming.exclusive.radio/uber/easy50/icecast.audio' },
        { n = 'Easy Radio', u = 'https://listen-nation.sharp-stream.com/breezyradiouk.mp3' },
        { n = 'Eirewave UK', u = 'http://eirewave.ice.infomaniak.ch/eirewave-128.mp3' },
        { n = 'Energy 1058', u = 'http://tachyon.shoutca.st:8590/listen.pls' },
        { n = 'Energy FM - Dance Music Radio', u = 'https://radio.streemlion.com:1875/stream' },
        { n = 'England - Heart London Radio', u = 'http://ice-the.musicradio.com/HeartLondonMP3' },
        { n = 'Enjoy Radio', u = 'http://s2.citrus3.com:8098/stream' },
        { n = 'Erewash Sound', u = 'http://stream01.erewashsound.com/erewashaac' },
        { n = 'Eric Clapton', u = 'https://streaming.exclusive.radio/er/ericclapton/icecast.audio' },
        { n = 'Eruption Radio', u = 'http://streaming04.liveboxstream.uk:8116/stream' },
        { n = 'Exclusively ACDC', u = 'https://streaming.exclusive.radio/er/acdc/icecast.audio' },
        { n = 'Exclusively Dire Straits', u = 'https://streaming.exclusive.radio/er/direstraits/icecast.audio' },
        { n = 'Exclusively Supertramp', u = 'https://streaming.exclusive.radio/er/supertramp/icecast.audio' },
        { n = 'Expansions | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape3' },
        { n = 'Feelings | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape27' },
        { n = 'Field Recordings | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape23' },
        { n = 'Forest Gold', u = 'https://c2.prostream365.com:8000/live' },
        { n = 'Foundation FM', u = 'https://streamer.radio.co/s0628bdd53/listen' },
        { n = 'Fred Film Radio Extra', u = 'https://s10.webradio-hosting.com/proxy/fredradioec/stream' },
        { n = 'Frisk Radio', u = 'http://www.friskradio.com:8000/stream1' },
        { n = 'Frome FM 966', u = 'http://icecast.bargus.co.uk:8001/fromefm.mp3' },
        { n = 'FSN World News', u = 'https://www.fsnradionews.com/FSNNews/FSNWorldNews.mp3' },
        { n = 'FUBAR Radio', u = 'http://direct.sharp-stream.com/fubar_1.mp3?device=website' },
        { n = 'Fun Kids', u = 'https://listen-funkids.sharp-stream.com/funkids.mp3' },
        { n = 'Fun Kids Junior', u = 'http://listen-funkids.sharp-stream.com/funkidsjunior.mp3' },
        { n = 'FUNK2DISCO', u = 'http://stream.laut.fm/funk2disco' },
        { n = 'Funky SX', u = 'http://stream1.funkyessex.co.uk:8000/mp3128' },
        { n = 'Gaydio', u = 'http://stream.gaydio.co.uk/gaydionwhq.mp3' },
        { n = 'Gaydio Brighton', u = 'http://stream.gaydio.co.uk/gaydiosc.mp3' },
        { n = 'GB News', u = 'http://listen-gbnews.sharp-stream.com/gbnews.mp3' },
        { n = 'GB News UK 48K Eaac+', u = 'http://listen-gbnews.sharp-stream.com/gbnews.aac' },
        { n = 'Gen X Radio', u = 'https://s2.radio.co/sf25229e16/listen' },
        { n = 'Genx Radio', u = 'https://s2.radio.co/sf25229e16/low' },
        { n = 'Giants Of Jazz Radio', u = 'http://streaming.radio.co/s297e618a7/listen' },
        { n = 'Gold', u = 'https://media-ssl.musicradio.com/GoldMP3' },
        { n = 'Gold AM 1548 London', u = 'http://media-ice.musicradio.com/GoldMP3' },
        { n = 'Greatest Hits Non-Stop', u = 'https://s8.myradiostream.com/58238//listen.mp3' },
        { n = 'Groove London Radio', u = 'http://eu10.fastcast4u.com/groovelondon' },
        { n = 'Hard House UK Radio', u = 'http://hhuk.netmindz.net:8000/listen.pls' },
        { n = 'Hard Rock Hell', u = 'http://andromeda.shoutca.st:9254/stream' },
        { n = 'Harrogate Hospital Radio', u = 'https://us7.streamingpulse.com/1962/?pl=vlc&c=St. Ita\\\'s Hospital Radio' },
        { n = 'Hearme-Beethoven', u = 'http://hearme.fm:10003/stream' },
        { n = 'Heart', u = 'http://media-the.musicradio.com/HeartNorthLancsCumbria' },
        { n = 'Heart 70S', u = 'https://media-ssl.musicradio.com/Heart70sMP3' },
        { n = 'Heart 80S', u = 'https://media-ssl.musicradio.com/Heart80sMP3' },
        { n = 'Heart 90S', u = 'https://media-ssl.musicradio.com/Heart90sMP3' },
        { n = 'Heart Bath 1030', u = 'http://media-sov.musicradio.com/HeartBathMP3' },
        { n = 'Heart Cambridge 1030', u = 'http://ice-sov.musicradio.com/HeartCambridgeMP3' },
        { n = 'Heart Dance', u = 'https://media-ssl.musicradio.com/HeartDanceMP3' },
        { n = 'Heart Essex 963 1026', u = 'http://ice-sov.musicradio.com/HeartEssexMP3' },
        { n = 'Heart FM Birmingham', u = 'https://media-ssl.musicradio.com/HeartWestMids' },
        { n = 'Heart FM Glasgow', u = 'http://media-the.musicradio.com/HeartGlasgow?amsparams=playerid:UKRP;skey:1546958888' },
        { n = 'Heart Kent 1031 1028', u = 'http://media-sov.musicradio.com/HeartKent' },
        { n = 'Heart London 1062 [AAC]', u = 'http://media-ice.musicradio.com/HeartLondon' },
        { n = 'Heart London 1062 [MP3]', u = 'http://ice-sov.musicradio.com/HeartLondonMP3' },
        { n = 'Heart North Wales', u = 'http://media-ice.musicradio.com/HeartNorthWalesMP3' },
        { n = 'Heart North West 1054', u = 'http://media-the.musicradio.com/HeartNorthWest' },
        { n = 'Heart Oxfordshire 1026 974', u = 'http://media-sov.musicradio.com/HeartOxfordshireMP3' },
        { n = 'Heart Plymouth 970 966', u = 'http://media-sov.musicradio.com/HeartPlymouth' },
        { n = 'Heart South Coast 967 975', u = 'http://media-sov.musicradio.com/HeartHampshire' },
        { n = 'Heart Suffolk', u = 'http://ice-sov.musicradio.com/HeartSuffolkMP3' },
        { n = 'Heart Sussex 1024 1035', u = 'http://media-ice.musicradio.com/HeartSussexMP3?.mp3' },
        { n = 'Heart UK', u = 'http://media-ice.musicradio.com/HeartUKMP3' },
        { n = 'Heart West Wales', u = 'http://ice-sov.musicradio.com/HeartWestWalesMP3' },
        { n = 'Heart Wiltshire', u = 'https://media-ssl.musicradio.com/HeartWiltshireMP3' },
        { n = 'Heart Xmas', u = 'http://icecast.thisisdax.com/HeartXmasMP3' },
        { n = 'Heart Yorkshire', u = 'http://media-sov.musicradio.com/HeartYorkshire' },
        { n = 'Heckington Living Community Radio', u = 'https://streaming.live365.com/a52107' },
        { n = 'Heritage Chart Radio', u = 'https://s4.radio.co/sd5b175766/listen' },
        { n = 'Holiday Radio', u = 'http://ec1.yesstreaming.net:1540/stream' },
        { n = 'Hospital Radio Chelmsford', u = 'https://solid55.streamupsolutions.com/proxy/mmbdfslu?mp=//stream' },
        { n = 'Hospital Radio Perth', u = 'http://streaming.broadcastradio.com:9222/perth' },
        { n = 'Hot FM UK', u = 'http://chandra.shoutca.st:8009/;' },
        { n = 'Hot Gold', u = 'https://stream1.hippynet.co.uk/stream/hotgold/dorset' },
        { n = 'Hot Hits Ukcom', u = 'https://443-1.autopo.st/54/stream.mp3' },
        { n = 'Hot Radio', u = 'https://stream1.hippynet.co.uk/stream/hotradio/dorset' },
        { n = 'House Fusion Radio UK', u = 'https://housefusionradiouk.out.airtime.pro/housefusionradiouk_a' },
        { n = 'House Music Radio', u = 'https://uk4-vn.mixstream.net/8128/listen.mp3' },
        { n = 'House Nation UK', u = 'https://streaming.radio.co/s06bd9d805/listen' },
        { n = 'Https:Wwwdifferentdrumzcouk', u = 'https://differentdrumz.radioca.st/stream%20;' },
        { n = 'HWD Hospital Radio', u = 'https://streaming04.liveboxstream.uk/proxy/hwdhospi?mp=/stream' },
        { n = 'Hypedem Reggae Radio', u = 'https://mrwolfman2.radioca.st/;' },
        { n = 'I Like It Oldskool', u = 'https://ilikeitoldskool.radioca.st/stream' },
        { n = 'Iconicextra', u = 'https://ukbeatz.radioca.st/stream' },
        { n = 'Intamixx', u = 'https://intamixx.no-ip.com:8002/;' },
        { n = 'Intamixx 80S 90S Radio UK', u = 'https://radio.intamixx.uk:8443/radio2' },
        { n = 'Isle Of Wight Radio', u = 'https://s2.xrad.io:9598/listen.mp3?___cb=275280937051671' },
        { n = 'JAZZ CHILL', u = 'http://salalondon.ddns.net:8002/;.m3u' },
        { n = 'Jazz London Radio', u = 'http://radio.canstream.co.uk:8075/live.mp3' },
        { n = 'JAZZFM91', u = 'https://jazzfm91.streamb.live/SB00009' },
        { n = 'Just House Music', u = 'https://justhousemusic.radioca.st/stream' },
        { n = 'KFM Radio', u = 'https://s2.radio.co/s367e90f45/listen' },
        { n = 'KISS UK', u = 'https://live-kiss.sharp-stream.com/kiss100.mp3' },
        { n = 'Kmfm Canterbury', u = 'http://listen-kmfm.sharp-stream.com/kmfmcanterbury.mp3?ref=RB' },
        { n = 'Kmfm Medway', u = 'http://listen-kmfm.sharp-stream.com/kmfmmedway.mp3?ref=RB' },
        { n = 'Kniteforce Radio', u = 'https://kniteforce.out.airtime.pro/kniteforce_a' },
        { n = 'Kool FM', u = 'https://admin.stream.rinse.fm/proxy/kool/stream' },
        { n = 'LABR Love A Brother Radio', u = 'https://solid2.streamupsolutions.com:2199/tunein/mqxncdsf.pls' },
        { n = 'Labyrinth | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape31' },
        { n = 'Lazy Gold', u = 'https://stream-lazyradio.creativedork.com/' },
        { n = 'LBC London London Stream AAC', u = 'http://media-sov.musicradio.com/LBCLondon' },
        { n = 'LBC London London Stream MP3', u = 'http://media-ice.musicradio.com/LBCLondonMP3Low' },
        { n = 'LBC London National Stream', u = 'http://media-ice.musicradio.com/LBCUKMP3Low' },
        { n = 'LBC News', u = 'https://media-ssl.musicradio.com/LBCNewsUK' },
        { n = 'LBC Radio', u = 'http://media-sov.musicradio.com/LBC973MP3Low' },
        { n = 'LBC UK', u = 'http://media-ice.musicradio.com/LBCUK' },
        { n = 'LDC', u = 'http://stream.ldcradio.co.uk:8000/aac1' },
        { n = 'Leicester Community Radio', u = 'http://icecast.maxxwave.co.uk:8000/lcr_hq' },
        { n = 'Lifefmtv', u = 'https://streamer.radio.co/s1ed160262/listen' },
        { n = 'Like Country', u = 'http://likeradiostream.com/likecountry' },
        { n = 'London Greek Radio LGR', u = 'http://eco.onestreaming.com:8203/stream' },
        { n = 'London Music Radio 128K', u = 'https://stream.londonmusicradio.com:8005/128k' },
        { n = 'London Soul Radio', u = 'http://londonsoulradio.out.airtime.pro:8000/londonsoulradio_a' },
        { n = 'Loveradio Only Love Songs 70S80S90S', u = 'https://loveradio.streamingmedia.it/england' },
        { n = 'LV18 Radio Mi Amigo', u = 'https://n0c.radiojar.com/0e16w6ha74uvv?rj-ttl=5&rj-tok=AAABkUcb0WkA7LgvZIzrVWH30g' },
        { n = 'Magic FM London', u = 'http://edge-bauermz-01-gos2.sharp-stream.com/magic1054.mp3' },
        { n = 'Magic UK', u = 'http://www.radiofeeds.net/playlists/bauer.pls?station=magicnational-mp3' },
        { n = 'Majestic Jukebox Radio', u = 'https://uk3.internet-radio.com/proxy/majesticjukebox/live' },
        { n = 'Malvern Radio International - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/radiomalvernint/stream' },
        { n = 'Malvern Radio JRS - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/malvernradiojrs/stream' },
        { n = 'Manx Radio AM', u = 'http://tx.sharp-stream.com/icecast.php?i=manxradioam.mp3' },
        { n = 'Maritime Radio', u = 'https://mediacp.nkpa.co.uk/stream/maritime%E2%80%8B/MRMP3' },
        { n = 'Mark Radio', u = 'http://s7.citrus3.com:8002/stream' },
        { n = 'Masjid Quba London', u = 'http://livemasjid.net/masjidequba.mp3' },
        { n = 'Memory Lane | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape6' },
        { n = 'Mersey Radio', u = 'https://stream.shoutcastservices.com/proxy/merseyradio/stream' },
        { n = 'Mi-Soul', u = 'https://listen-misoul.sharp-stream.com/462_mi_soul_128_mp3' },
        { n = 'Midlands Radio Christmas MP3', u = 'http://stream.zeno.fm/b0ykm1bpb78uv' },
        { n = 'Mix 926', u = 'https://stream4.hippynet.co.uk/stream/8012/stream' },
        { n = 'Mix Radio', u = 'http://45.67.156.157:18006/live' },
        { n = 'Mixx Radio Preston', u = 'https://stream-hitsradio.creativedork.com/' },
        { n = 'Moe Lofi', u = 'http://stream.zeno.fm/3u1qndyk8rhvv' },
        { n = 'More Radio Eastbourne', u = 'http://s3.xrad.io:8090/stream/1/' },
        { n = 'Movedahouse', u = 'http://uk7.internet-radio.com:8000/stream' },
        { n = 'Mystery Train Radio', u = 'https://streamer.radio.co/sf662f27c0/listen' },
        { n = 'Naim Classical', u = 'http://mscp3.live-streams.nl:8250/class-high.aac' },
        { n = 'Naim Jazz', u = 'http://mscp3.live-streams.nl:8340/jazz-flac.flac' },
        { n = 'Naim Jazz [320K Aac]', u = 'http://mscp3.live-streams.nl:8340/jazz-high.aac' },
        { n = 'Naim Radio [320K Aac]', u = 'http://mscp3.live-streams.nl:8360/high.aac' },
        { n = 'Naim Radio [Lossless Flac]', u = 'http://mscp3.live-streams.nl:8360/flac.flac' },
        { n = 'Nation 60S', u = 'https://listen-nation.sharp-stream.com/nation60s.mp3' },
        { n = 'Nation Radio', u = 'http://listen-nation.sharp-stream.com/nationhulldab.mp3?ref=RF' },
        { n = 'Nation Radio 80S', u = 'http://listen-nation.sharp-stream.com/nationradio80s.mp3' },
        { n = 'Nation Radio South Coast Dorset', u = 'http://listen-nation.sharp-stream.com/nationdorsetdab.mp3?ref=RF' },
        { n = 'Nation Radio Wales', u = 'https://edge-ads-05-gos2.sharp-stream.com/tcnationi.aac' },
        { n = 'Neon Radio', u = 'https://live.flashbackcentral.co.uk/radio/8050/radio.mp3' },
        { n = 'Neon Radio - 80S 90S Pop Dance', u = 'https://live.flashbackcentral.co.uk/radio/8050/tunein.mp3' },
        { n = 'Netil Radio', u = 'https://netilradio.out.airtime.pro/netilradio_a' },
        { n = 'Nice Cream Blue', u = 'https://play.nicecream.fm/radio/8020/blue.mp3' },
        { n = 'NME 1', u = 'https://msmn3.co/proxy/x1mp33/stream' },
        { n = 'NME 1 - Classic New Indie Alt', u = 'http://svr1.msmn.co:8136/' },
        { n = 'NME 2', u = 'https://msmn3.co/proxy/x2mp33/stream' },
        { n = 'NME 2 - New Upfront Indie Alt', u = 'http://msmn.co:8118/;stream' },
        { n = 'Noisebox Radio', u = 'http://n11.radiojar.com/n1bs4ekbvuhvv?rj-ttl=5&rj-tok=AAABjE1UCSYASTnnnPAqWHT0-w' },
        { n = 'Nonstop80S Radio', u = 'https://listen.nonstopstreaming.net/ns80s' },
        { n = 'Nonstop90S Radio', u = 'https://listen.nonstopstreaming.net/ns90s' },
        { n = 'Nonstopdance Radio', u = 'https://listen.nonstopstreaming.net/nsd' },
        { n = 'Nonstopplay Dance Radio', u = 'http://stream.nonstopplay.co.uk/nsp-192k-mp3' },
        { n = 'Nonstopplay Pure Dance', u = 'http://stream.nonstopplay.co.uk/nsppd-32k-aac' },
        { n = 'Nonstopplaycom Dance Radio', u = 'http://stream.nonstopplay.co.uk/nsp-128k-mp3' },
        { n = 'Nostalgia Radio', u = 'https://s5.radio.co/s6211fbeed/listen' },
        { n = 'Not The BCFM Politics Show', u = 'http://uk3.internet-radio.com:8323/live' },
        { n = 'Noteradio', u = 'http://s5.citrus3.com:8028/stream' },
        { n = 'NTS Radio 1', u = 'http://stream-relay-geo.ntslive.net/stream' },
        { n = 'NTS Radio 2', u = 'http://stream-relay-geo.ntslive.net/stream2' },
        { n = 'Offshore Music Radio', u = 'http://bitsmitter.com:8000/' },
        { n = 'Offshore Music Station', u = 'http://bitsmitter.com:8000/omr%20;stream.mp3' },
        { n = 'Old Skool Rave Tapes', u = 'https://osrt.ovh:8000/listen' },
        { n = 'Oldskool UK', u = 'https://fastcast4u.com/player/osuk/?pl=vlc&c=OLDSKOOL UK' },
        { n = 'One Live', u = 'http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3' },
        { n = 'Original 106', u = 'https://listen-original.sharp-stream.com/original106.mp3' },
        { n = 'Osnfm', u = 'https://stream.stuallan.com/stream2' },
        { n = 'OSTM Radio', u = 'https://stream.zeno.fm/1vx25xbdmzzuv' },
        { n = 'Otaku | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape36' },
        { n = 'Panjab Radio London', u = 'http://s1.voscast.com:7918/stream' },
        { n = 'Paranormal UK Radio', u = 'http://s6.citrus3.com:8014/stream' },
        { n = 'Passion Radio', u = 'http://stream.mybroadbandradio.com/passionradio' },
        { n = 'Platinum Gold Radio', u = 'http://s2.voscast.com:10128/;' },
        { n = 'Play Radio', u = 'https://stream.radiojar.com/0zs50dbr274tv' },
        { n = 'PLAYBACKUK', u = 'https://chilledstreaming.com:8650/mobile.mp3' },
        { n = 'Point Blank FM 320KB', u = 'http://pointblankradio.co.uk:9002/stream' },
        { n = 'Point Blank Radio', u = 'https://pointblankradio.co.uk/stream.mp3?latency=high' },
        { n = 'Poolside | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape4' },
        { n = 'Pride Radio 90S', u = 'http://philae.shoutca.st:8807/stream' },
        { n = 'Psychedelic Secret Radio', u = 'https://solid48.streamupsolutions.com/proxy/bglsokon?mp=/=stream' },
        { n = 'Psystream', u = 'http://radio.psymusic.co.uk:8040/radio1_192k.mp3' },
        { n = 'Pure West Radio', u = 'https://uksoutha.streaming.broadcast.radio/stream/8580/purewest' },
        { n = 'Q Radio Mid Ulster', u = 'http://edge-audio-02-gos1.sharp-stream.com/qr1060.mp3' },
        { n = 'Q Radio Newry And Mourne', u = 'http://edge-audio-02-gos1.sharp-stream.com/qr1005.mp3' },
        { n = 'Quantum Radio', u = 'https://radio.erb.pw/listen/subspace/radio.mp3' },
        { n = 'Quasar Radio', u = 'https://ec2.yesstreaming.net:1935/stream' },
        { n = 'R5K', u = 'https://stream.r5k.net/' },
        { n = 'Radio Atlantic 80S', u = 'https://chasbo1978.radioca.st/stream' },
        { n = 'Radio Caroline', u = 'http://78.129.202.200:8040/;' },
        { n = 'Radio Caroline [48K Aac+]', u = 'http://sc5.radiocaroline.net:8010/listen.pls' },
        { n = 'Radio Caroline AAC 96 Kbps', u = 'http://78.129.202.200:8030/;' },
        { n = 'Radio Caroline Flashback', u = 'http://sc2.radiocaroline.net:10558/listen.pls' },
        { n = 'Radio Caroline North Ross Revenge Live Broadcasts', u = 'http://sc2.radiocaroline.net:8100/listen.pls' },
        { n = 'Radio Central 24', u = 'https://casper.radioca.st/;' },
        { n = 'Radio Christmas', u = 'https://streaming.radiochristmas.co.uk/RadioChristmas' },
        { n = 'Radio Dream', u = 'http://ec5.yesstreaming.net:3590/stream' },
        { n = 'Radio England - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/radioengland/stream' },
        { n = 'Radio Gibraltar Plus', u = 'http://s2.myradiostream.com:32910/;' },
        { n = 'Radio Harrow', u = 'http://listen.radioharrow.org/live.mp3' },
        { n = 'Radio Jackie Hiend', u = 'http://media.radiojackie.com:5873/' },
        { n = 'Radio Le Mans RS1', u = 'http://tx.sharp-stream.com/icecast.php?i=radioshow.mp3' },
        { n = 'Radio Le Mans RS2', u = 'http://tx.sharp-stream.com/icecast.php?i=radioshow2.mp3' },
        { n = 'Radio Maria England', u = 'https://dreamsiteradiocp5.com/proxy/rmengland?mp=/stream' },
        { n = 'Radio North Angus', u = 'https://uk3-vn.mixstream.net/8192/listen.mp3' },
        { n = 'Radio Royal', u = 'https://azuracast.radioroyal.org/listen/radioroyal/medium' },
        { n = 'Radio Silky', u = 'http://46.28.49.164:7226/stream' },
        { n = 'Radio X', u = 'http://media-the.musicradio.com/RadioXUK' },
        { n = 'Radio X Classic Rock', u = 'https://media-ice.musicradio.com/RadioXClassicRockMP3' },
        { n = 'Radio X London', u = 'http://media-the.musicradio.com/RadioXLondon' },
        { n = 'Radio X London MP3', u = 'http://media-the.musicradio.com/RadioXLondonMP3' },
        { n = 'Radio X Manchester', u = 'http://media-the.musicradio.com/RadioXManchester' },
        { n = 'Radioart: Greek Art For Kids', u = 'http://live.radioart.com/fGreek_art_for_kids.mp3' },
        { n = 'RADIOROSAK', u = 'https://stream.rcast.net/68127' },
        { n = 'Rafa Bible Radio English', u = 'https://gains.reviveradio.net/proxy/rafabibleradioeng?mp=/stream' },
        { n = 'Rage FM', u = 'http://uk2-pn.mixstream.net:8002/' },
        { n = 'RAM FM Eighties Hit Radio', u = 'https://usa1-vn.mixstream.net/8084/listen.mp3' },
        { n = 'Real Roots Radio', u = 'https://streams.radio.co/s1df61e0af/listen' },
        { n = 'Real World Sounds', u = 'http://uk5.internet-radio.com:8260/;stream' },
        { n = 'Redroad FM 1024', u = 'http://s45.myradiostream.com:13784/;' },
        { n = 'Rendell Radio', u = 'http://s10.myradiostream.com:34794/' },
        { n = 'Reprezent', u = 'http://radio.canstream.co.uk:8022/live.mp3' },
        { n = 'Resonance 1044FM', u = 'https://stream.resonance.fm/resonance?rp_source=1&___cb=309691324386261' },
        { n = 'Resonance Extra', u = 'http://stream.resonance.fm:8000/resonance-extra' },
        { n = 'Resonance FM 1044 - London', u = 'http://stream.resonance.fm:8000/resonance' },
        { n = 'Retro Soul Radio', u = 'http://46.28.49.164:7504/stream' },
        { n = 'Rewind Radio', u = 'http://s4.radio.co/s2eaa194f6/listen' },
        { n = 'Rhubarb Radio', u = 'https://securestreams2.autopo.st:1234/stream#.mp3?1702339792481' },
        { n = 'Rokit Radio 1940S Radio', u = 'https://streaming06.liveboxstream.uk/proxy/roksta13/stream' },
        { n = 'Rokit Radio : 1940S Radio', u = 'http://streaming06.liveboxstream.uk:8256/stream' },
        { n = 'Rokit Radio : Adventure Stories', u = 'https://streaming06.liveboxstream.uk/proxy/rokstar7/stream' },
        { n = 'Rokit Radio : American Comedy', u = 'http://streaming04.liveboxstream.uk:8162/stream' },
        { n = 'Rokit Radio : British Comedy 1', u = 'https://streaming04.liveboxstream.uk/proxy/roksta14/stream' },
        { n = 'Rokit Radio : British Comedy 2', u = 'https://streaming05.liveboxstream.uk/proxy/jondreas/stream' },
        { n = 'Rokit Radio : Classic Crime And Suspense', u = 'https://streaming04.liveboxstream.uk/proxy/roksta17/stream' },
        { n = 'Rokit Radio : Classic Old Time Radio Shows', u = 'https://streaming04.liveboxstream.uk/proxy/roksta18/stream' },
        { n = 'Rokit Radio : Comedy Gold', u = 'https://streaming06.liveboxstream.uk/proxy/rokstar8/stream' },
        { n = 'Rokit Radio : Saturn-X Radio Shows', u = 'https://streaming05.liveboxstream.uk/proxy/jondre03/stream' },
        { n = 'Rokit Radio : Science Fiction', u = 'http://streaming05.liveboxstream.uk:8110/stream' },
        { n = 'Rokit Radio Science Fiction', u = 'https://streaming05.liveboxstream.uk/proxy/roksta12/stream' },
        { n = 'RSTV - Rnb MP3', u = 'http://stream.zeno.fm/qm22c59vqnhvv' },
        { n = 'Rustradio', u = 'https://listen.rustradio.co.uk:8443/stream' },
        { n = 'SAB RADIO FOLKESTONE UK', u = 'https://spectrum.radioca.st/stream' },
        { n = 'Salaam Radio', u = 'https://radio.canstream.co.uk:8005/live.mp3' },
        { n = 'SAM FM Hampshire', u = 'https://listen-nation.sharp-stream.com/samfmhampshire.aac' },
        { n = 'Scotlander Radio', u = 'https://play.lallans.media/listen/scotlander_radio/radio.mp3' },
        { n = 'SD Radio', u = 'https://mystation.micast.media/radio/8020/radio.mp3' },
        { n = 'Select Radio', u = 'https://streaming05.liveboxstream.uk/proxy/selectr1/stream' },
        { n = 'Select Radio UK', u = 'http://streaming04.liveboxstream.uk:8062/' },
        { n = 'Shuffle 2', u = 'http://radio.streemlion.com:1460/stream' },
        { n = 'Signal Mix Radio Urban UK - Music, News Culture', u = 'https://a8.asurahosting.com:7410/radio.mp3' },
        { n = 'Sky News Radio Latest News UK', u = 'https://video.news.sky.com/snr/news/snrnews.mp3' },
        { n = 'Sky News UK', u = 'https://tunein.cdnstream1.com/3688_96.mp3?source=TuneIn' },
        { n = 'Skyline Radio - Wolverhampton MP3', u = 'http://stream.zeno.fm/gppe0uht9c0uv' },
        { n = 'Slow Focus | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape' },
        { n = 'Smooth Chill', u = 'https://media-ssl.musicradio.com/ChillMP3' },
        { n = 'Smooth Chill UK', u = 'http://icecast.thisisdax.com/SmoothChillMP3' },
        { n = 'Smooth Chill UK 48K AAC+', u = 'http://icecast.thisisdax.com/SmoothChill' },
        { n = 'Smooth Country', u = 'https://media-ssl.musicradio.com/SmoothCountry' },
        { n = 'Smooth Radio', u = 'http://media-the.musicradio.com/SmoothEastMids' },
        { n = 'Smooth Radio London 1022', u = 'http://media-the.musicradio.com/SmoothLondonMP3' },
        { n = 'Smooth Radio London, UK 48K Aac+', u = 'http://media-the.musicradio.com/SmoothLondon' },
        { n = 'Smooth Radio Suffolk', u = 'https://media-ssl.musicradio.com/SmoothSuffolk' },
        { n = 'Smooth Relax', u = 'https://icecast.thisisdax.com/SmoothRelaxMP3' },
        { n = 'Smooth Scotland', u = 'http://media-the.musicradio.com/SmoothScotland' },
        { n = 'Soho Radio London', u = 'https://sohoradiomusic.doughunt.co.uk:8010/128mp3' },
        { n = 'Solar Radio', u = 'https://listen-msmn.sharp-stream.com/solarlow.mp3' },
        { n = 'Solid Gold Gem AM', u = 'http://4483.cloudrad.io:8130/;' },
        { n = 'Solid Soul Grooves Radio - Stourbridge MP3', u = 'http://stream.zeno.fm/u08ymmrybg8uv' },
        { n = 'Sonatica Classical Radio', u = 'http://orion.shoutca.st:8742/160' },
        { n = 'Soul City FM', u = 'http://radioradio.ddns.net:8000/soul' },
        { n = 'SOUL RADIO Only Classic Soul', u = 'https://listen.soulradio.uk/uk' },
        { n = 'SOULPOWER-RADIOCOM', u = 'https://s2.radio.co/sb0964023c/listen' },
        { n = 'Space Unicorn Radio Not Https', u = 'http://spaceunicorn.radio:8000/stream' },
        { n = 'Starpoint Radio', u = 'https://stream2.hippynet.co.uk/stream/starpointradiohigh' },
        { n = 'Station X - Northern Soul', u = 'http://161.97.144.188:4000/' },
        { n = 'Stellar Attraction', u = 'http://level5technologysolutions.net:8010/stream' },
        { n = 'Stirling Community Radio', u = 'https://streaming.broadcastradio.com:11855/castlesound?8852' },
        { n = 'Stones Live - The 247 Maidstone United Radio Station', u = 'https://uk5.internet-radio.com/proxy/stoneslive?mp=/stream;' },
        { n = 'Storm Radio', u = 'https://streaming.radio.co/s6df48fd88/listen' },
        { n = 'Strange Radio - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/strangeradio/stream' },
        { n = 'Street Sounds Radio', u = 'https://streaming.broadcastradio.com:10525/streetsd' },
        { n = 'Stu Allan Radio', u = 'https://stream.stuallan.com/stream1' },
        { n = 'Sun FM', u = 'http://edge-ads-03-gos2.sharp-stream.com/sunfmi.aac' },
        { n = 'Sunny G Community Radio', u = 'https://streaming06.liveboxstream.uk/proxy/gary1?mp=/stream' },
        { n = 'Surf Rock Radio', u = 'http://139.162.89.191:8020/radio.mp3' },
        { n = 'SVETUR', u = 'http://svetur.intellmedia.lt:8282/tiesiogiai.mp3' },
        { n = 'Sweat | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape24' },
        { n = 'Switch FM London', u = 'https://stream.switchfm.co.uk/listen/switchfm/switchfm.mp3' },
        { n = 'SWU FM', u = 'https://admin.stream.rinse.fm/proxy/swu/stream' },
        { n = 'Talk Radio UK', u = 'http://radio.talkradio.co.uk/stream-mobile?ref=rf' },
        { n = 'Talkradio', u = 'http://radio.talkradio.co.uk/stream' },
        { n = 'Talksport', u = 'http://radio.talksport.com/stream?aisGetOriginalStream=true' },
        { n = 'Talksport 2', u = 'http://radio.talksport.com/stream2?awparams=platform:ts-web&amsparams=playerid:ts-web;' },
        { n = 'Team-Fm', u = 'http://178.159.3.22:8124/live' },
        { n = 'Teamsport Radio', u = 'https://uksouth1.juiceboxradio.com/tsradionational' },
        { n = 'Techno - FM - Channel', u = 'https://stream.techno.fm/radio1-320k.mp3' },
        { n = 'Technofm', u = 'http://stream.techno.fm/radio.mp3' },
        { n = 'Technofm 320 Kbit', u = 'http://stream.techno.fm/radio320.mp3' },
        { n = 'Teenage Kicks Radio', u = 'https://onlineradiobox.com/json/fr/teenagekicks/play' },
        { n = 'The Ambientscape Project', u = 'https://listen.radioking.com/radio/504205/stream/561655' },
        { n = 'The British Home Front Radio Service', u = 'https://solid24.streamupsolutions.com/proxy/mmpplqiv?mp=/;type=mp3' },
        { n = 'The English 909 Radio', u = 'https://www.radioking.com/play/the-english-909' },
        { n = 'The Groove', u = 'http://uk7.internet-radio.com:8352/' },
        { n = 'The Sounds Of GTA | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape33' },
        { n = 'The Source FM', u = 'http://live.canstream.co.uk:8000/sourcefm.mp3' },
        { n = 'The Thread 1028FM', u = 'http://radio.canstream.co.uk:8035/canal.mp3' },
        { n = 'The Tube | NTS', u = 'https://stream-mixtape-geo.ntslive.net/mixtape26' },
        { n = 'The Voice Of Doom', u = 'https://streaming.galaxywebsolutions.com:9046/stream' },
        { n = 'Thezone', u = 'http://uk1.internet-radio.com:8355/stream' },
        { n = 'This Is The Coast', u = 'https://streaming.broadcastradio.com:10765/thisisthecoast' },
        { n = 'Times Radio', u = 'https://timesradio.wireless.radio/stream' },
        { n = 'Times Radio UK', u = 'http://timesradio.wireless.radio/stream' },
        { n = 'Times Radio UK 48K AAC', u = 'http://timesradio.wireless.radio/stream-mobile?ref=rf' },
        { n = 'Tonic Ska Radio', u = 'https://eu10.fastcast4u.com/tonicska' },
        { n = 'Total Soul UK 192Kb Mp3', u = 'https://onair7.xdevel.com/proxy/xautocloud_atvn_1069?mp=/;1/' },
        { n = 'Trancetechnic Radio', u = 'https://s11.ssl-stream.com/ssl/trancete?mp=/stream' },
        { n = 'Treehouse Giant Jukebox', u = 'http://s6.autopo.st:8515/jukebox' },
        { n = 'Treehouse Radio', u = 'http://s6.autopo.st:8515/live' },
        { n = 'Truckersfm', u = 'http://radio.truckers.fm/' },
        { n = 'TWR UK', u = 'https://direct.sharp-stream.com/twruk.mp3' },
        { n = 'U105', u = 'http://gbradio.cdn.tibus.net/U105?ref=rf' },
        { n = 'Ujima Radio', u = 'https://radio.canstream.co.uk:8037/live.mp3' },
        { n = 'UK Bass', u = 'https://ukbassradio.com/stream' },
        { n = 'UK Bass Radio', u = 'https://www.ukbassradio.com/stream' },
        { n = 'UK Health Radio', u = 'https://streaming.radio.co/s8e535ff20/listen' },
        { n = 'UK Hits - London MP3', u = 'http://stream.zeno.fm/dpqrqe9nrv8uv' },
        { n = 'UK Roots FM 2024 03', u = 'http://138.201.198.218:8043/;' },
        { n = 'Underground Bass', u = 'http://65.108.124.70:7200/stream' },
        { n = 'V2 Radio', u = 'http://stream.v2radio.co.uk/V2RadioHQAACP' },
        { n = 'Venture Radio - Pumpkin FM', u = 'https://cast2.asurahosting.com/proxy/ventureradio/stream' },
        { n = 'Vintage Radio Birkenhead', u = 'https://streaming04.liveboxstream.uk/proxy/vintager/stream' },
        { n = 'Virgin Radio Anthems', u = 'https://radio.virginradio.co.uk/stream-anthems' },
        { n = 'Virgin Radio Chilled', u = 'https://radio.virginradio.co.uk/stream-chilled' },
        { n = 'Virgin Radio UK', u = 'https://radio.virginradio.co.uk/stream' },
        { n = 'Virgin Radio UK', u = 'https://radio.virginradio.co.uk/stream' },
        { n = 'WBLS Radio', u = 'http://s2.myradiostream.com:3604/;' },
        { n = 'World Radio Network Russian WRN', u = 'http://shoutcast.wrn.org:8025/WRN-R' },
        { n = 'WOTR Hymns', u = 'http://wotrstream.com:8025/hymns' },
        { n = 'WRN Europe', u = 'http://shoutcast.wrn.org:8026/' },
        { n = 'XL:UK Radio', u = 'https://s3.radio.co/s113a5dc46/listen' },
        { n = 'Xtra Hot', u = 'https://stream1.hippynet.co.uk/stream/xtrahot/live' },
        { n = 'YO1 Extra', u = 'http://ec1.yesstreaming.net:1490/stream' },
        { n = 'Yo1 Radio', u = 'https://stream1.themediasite.co.uk:8026/?_=215164' },
        { n = 'Your Hits Digital', u = 'https://stream-yourhitsdigital.creativedork.com/' },
    }
}
