local stations = {
    {name = "Albania News 24 TV", url = "http://tv.balkanweb.com:8081/news24/livestream/playlist.m3u8"},
    {name = "ARNAVUT FM", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "Chill Radio", url = "http://eu8.fastcast4u.com/proxy/chillradio?mp=/1"},
    {name = "CLUB FM", url = "https://cp1.sednastream.com/proxy/clubfm?mp=/stream"},
    {name = "Club FM Kosova", url = "https://cp1.sednastream.com/proxy/clubfmkosova?mp=/stream"},
    {name = "Phish Radio", url = "https://streaming.radio.co/sd71de59b3/listen"},
    {name = "Play Radio Albania", url = "http://n01.radiojar.com/sx7zrht0pg0uv?rj-ttl=5&rj-tok=AAABkY8dSngAM9EXtb4tNrGUHw"},
    {name = "Radio Burimi", url = "https://stream-154.zeno.fm/vzp9uf0u3ehvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ2enA5dWYwdTNlaHZ2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InlUcEFvdVpzVEhDRm01ZlpYbjl5cnciLCJpYXQiOjE3MjQ2OTQ1ODIsImV4cCI6MTcyNDY5NDY0Mn0.fVZknZO2d-uizbhwbjV-hFdSI6vNlOwe8NpnmBIiiqo"},
    {name = "Radio DJ", url = "https://radio.albaniaradiodj.al/stream"},
    {name = "RADIO MARIA ALBANIA", url = "http://dreamsiteradiocp2.com:8028/stream"},
    {name = "Radio Ora News", url = "https://radio.oranews.tv:8443/stream"},
    {name = "Radio Tirana 1", url = "http://79.106.48.2:8000/radiotirana1"},
    {name = "Radio-Bllaca", url = "https://stream-174.zeno.fm/0smrlmhdbxuuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIwc21ybG1oZGJ4dXV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik9HckxLOGNnU3d1eXB4LWxhd1lla0EiLCJpYXQiOjE3MjQ3MDM0MDAsImV4cCI6MTcyNDcwMzQ2MH0.2R54Q5GumCOfVy4IWz0xsFQxEjSA4H0Tvez0Os1LZfU"},
    {name = "Radioone", url = "https://cp1.sednastream.com/proxy/radioone94?mp=/stream"},
    {name = "Raduo-Bllaca", url = "https://stream-174.zeno.fm/0smrlmhdbxuuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIwc21ybG1oZGJ4dXV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjlHUGRxSldOUzF5aHFVOXJOeGp2S2ciLCJpYXQiOjE3MjQ2OTQ5NTksImV4cCI6MTcyNDY5NTAxOX0.dNJUtXNYqurTDQSbw07aYwTCNeEi5jEiWwJrtLWEt38"},
    {name = "RTSH Radio Tirana International", url = "http://79.106.48.2:8000/rti"},
    {name = "Sasaram", url = "http://air.pc.cdn.bitgravity.com/air/live/pbaudio075/chunklist.m3u8"},
    {name = "Test", url = "http://stream-uk1.radioparadise.com/aac-320"},
    {name = "Tirana Jazz Radio", url = "https://live.tiranajazzradio.com:8443/stream"},
    {name = "Top Albanian Radio", url = "https://live.top-media.al/tar"},
    {name = "Translation Of The Quran In Albanian", url = "https://server3.quraan.us:8008/"},
    {name = "إذاعة القرآن الكريم", url = "http://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABkY2S0NEAjh4snuVYw4bZbw"},
    {name = "اذاعة القرآن الكريم", url = "http://n08.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABkY-LeRQATQpndTy4Ye02dw"},
}

return stations
