local stations = {
    {name = "Alger Chaine 3", url = "https://webradio.tda.dz/Chaine3_64K.mp3"},
    {name = "إذاعة البهجة", url = "https://webradio.tda.dz/ElBahdja_64K.mp3"},
    {name = "15-Tizi-Ouzou", url = "https://webradio.tda.dz/TiziOuzou_64K.mp3"},
    {name = "Antinea Radio", url = "https://listen.radioking.com/radio/6640/stream/347"},
    {name = "JOW Radio", url = "https://str0.creacast.com/jowradio"},
    {name = "Chaine 1", url = "https://webradio.tda.dz/Chaine1_64K.mp3"},
    {name = "El Bahdja Fm", url = "http://webradio.tda.dz:8001/ElBahdja_64K.mp3"},
    {name = "إذاعة الجزائر الدولية", url = "https://webradio.tda.dz/Internationale_64K.mp3"},
    {name = "جو راي", url = "https://ice.creacast.com/jowradio-rai"},
    {name = "1011 ALGERİA FM", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "إذاعة القرآن الكريم", url = "http://stream.radiojar.com/0tpy1h0kxtzuv"},
    {name = "Hits 1 Algérie", url = "https://radio12.pro-fhi.net/listen/whmnrlow/stream"},
    {name = "Jil Fm Dz", url = "https://webradio.tda.dz/Jeunesse_64K.mp3"},
    {name = "Beur FM", url = "https://beurfm.ice.infomaniak.ch/beurfm-high.mp3"},
    {name = "Hits1 Algérie", url = "https://player.mc.hits1radio.com/"},
    {name = "Radio Soummam", url = "https://webradio.tda.dz/Bejaia_64K.mp3"},
    {name = "EXA FM: موسيقى البوب ​​باللغتين الإنجليزية والإسبانية", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "إذاعة ماهر المعيقلي", url = "https://backup.qurango.net/radio/maher"},
    {name = "تفسير بن عثيمين رحمه الله", url = "https://qurango.net/radio/tafseer"},
    {name = "جو راديو", url = "https://ice.creacast.com/jowradio"},
    {name = "ديني راديو", url = "https://ice.creacast.com/jowradio-diny"},
    {name = "1090 FM Christmas Kids", url = "http://stream.dar.fm/97821"},
    {name = "صور من حياة الصحابة", url = "https://qurango.net/radio/sahabah"},
    {name = "Zaman FM", url = "https://webradio.tda.dz/Zamen_64K.mp3"},
    {name = "Radio Dzair Raina", url = "https://radiodzair.net:8060/raina?shoutcast"},
    {name = "Radio Dzair", url = "https://radiodzair.net:8000/dzair?shoutcast"},
    {name = "Radio Dzair Sahara", url = "https://radiodzair.net:8040/sahara?shoutcast"},
    {name = "جو راب", url = "https://ice.creacast.com/jowradio-jow_rap"},
    {name = "صوت الغد استراليا", url = "http://s4.voscast.com:7648/;stream.mp3"},
    {name = "Radio Dzair Izuran", url = "https://radiodzair.net:8030/izuran?shoutcast"},
    {name = "مختصر السيرة", url = "https://qurango.net/radio/almukhtasar_fi_alsiyra"},
    {name = "النهج الواضح", url = "https://node33.obviousapproach.com:9000/stream"},
    {name = "France Maghreb 2", url = "https://francemaghreb2.ice.infomaniak.ch/francemaghreb2-high.mp3"},
    {name = "Syria Sat", url = "http://radioliveb.rtv.gov.sy:8002/Sat"},
    {name = "Al Quran Radio", url = "https://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABhdgGORQA-2acfyF3_4WY2g"},
    {name = "Radio Dzair Aurès", url = "https://radiodzair.net:8050/aures?shoutcast"},
    {name = "Radio Dzair Andaloussia", url = "https://radiodzair.net:8020/andaloussia?shoutcast"},
    {name = "Radio Dzair Orientale", url = "https://radiodzair.net:8070/orientale?shoutcast"},
    {name = "جو افريقيا", url = "https://ice.creacast.com/jowradio-north_africa"},
    {name = "القارئ محمد أيوب", url = "https://qurango.net/radio/mohammed_ayyub"},
    {name = "Ghardaia", url = "https://webradio.tda.dz/Ghardaia_64K.mp3"},
    {name = "مختصر التفسير", url = "https://qurango.net/radio/mukhtasartafsir"},
    {name = "إذاعة طريق السلف", url = "https://airtime.salafwayfm.ly/"},
    {name = "Ghorbadz", url = "https://stream-150.zeno.fm/y9rchc1djgavv?zs=bcPxFTkWTZOhirTC49uQiQ"},
    {name = "Radio Blida 7H-20H", url = "https://webradio.tda.dz/Blida_64K.mp3"},
    {name = "Radio Tipaza 7H-20H", url = "https://webradio.tda.dz/Tipaza_64K.mp3"},
    {name = "Sleep", url = "http://65.109.81.84:9851/stream"},
    {name = "Beautiful Recitation", url = "https://qurango.net/radio/salma"},
    {name = "Radio Boumerdes 7H-20H", url = "https://webradio.tda.dz/Boumerdes_64K.mp3"},
}

return stations
