local stations = {
    {name = "1025 Medios Del Aire General Roca", url = "https://server6.hostradios.com:7041/;"},
    {name = "221Radio FM 1031", url = "https://radios.solumedia.com:10815/stream"},
    {name = "889 FM Radio Light", url = "http://streamall.alsolnet.com/radiolightfm"},
    {name = "90 Radio FM 901", url = "http://sonicpanel.hostradios.com:8108/;"},
    {name = "925 FM Radio 2000", url = "https://server6.hostradios.com/8390/stream"},
    {name = "945 Máxima FM", url = "http://server.laradio.online:8797/;"},
    {name = "961 Shopping Classics", url = "https://stream4.suenas.net/shoppingclassics"},
    {name = "@Twitradioo", url = "http://s2.netradiofm.com:6338/"},
    {name = "ABC Mundial Radio", url = "http://01.solumedia.com.ar:7054/;"},
    {name = "Acqua FM 1001", url = "https://strcdn.klm99.com:10985/acquavillagesell"},
    {name = "AIRE", url = "http://stm14.xcast.com.br:8248/"},
    {name = "Aire Libre 963 Río Grande", url = "http://streamingraddios.net:9277/stream"},
    {name = "Alegría FM 997", url = "http://radio.solumedia.com.ar:8004/;"},
    {name = "Am 1050 San Francisco", url = "https://vps-2333016-x.dattaweb.com/listen/am_1050_radio_san_francisco/radio.mp3"},
    {name = "AM 530 Somos Radio", url = "https://ipanel.instream.audio:7000/stream"},
    {name = "AM 750 Una Señal", url = "https://26673.live.streamtheworld.com/AM750AAC_SC"},
    {name = "AM CUMBRE 1400", url = "https://cdn.instream.audio/:9366/stream"},
    {name = "AM1330 Rosario", url = "http://s2.argentina-streaming.com:8156/;"},
    {name = "AM750", url = "https://26673.live.streamtheworld.com/AM750AAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=0d038027-7e61-45c6-bf8e-03d246e129b7"},
    {name = "Andina FM 929", url = "https://streaming01.shockmedia.com.ar:10801/stream?icy=http"},
    {name = "Antena Libre 891 Argentina Universidad Conahue", url = "http://cdn.instream.audio:9140/stream"},
    {name = "Antena Libre 891 FM", url = "https://cdn.instream.audio/:9140/stream"},
    {name = "Antena Nueve 943 FM", url = "https://radios.solumedia.com:10918/;"},
    {name = "Antena Uno 923FM Posadas", url = "https://radios.solumedia.com:10818/;"},
    {name = "Arco Iris FM 981", url = "http://centova.questreaming.com:4058/;"},
    {name = "Aspen 1023", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ASPEN.mp3"},
    {name = "Beat 90200", url = "http://radio02.ferozo.com:8850/stream"},
    {name = "Beat Digital Radio", url = "http://stream.zeno.fm/9s7nnwmknkhvv.m3u"},
    {name = "Beatradio - General Pico", url = "https://server.ohradio.com.ar:7043/stream"},
    {name = "Binaural Rock Radio", url = "http://01.solumedia.com.ar:7870/;"},
    {name = "Blue FM 1007 Ciudad De Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/BLUE_FM_100_7AAC.aac"},
    {name = "BRH - Bahía Radio Hits", url = "https://miestacion.turadioonline.com.ar/8158/stream"},
    {name = "Bunker FM 919", url = "https://azura.derflusweb.com/radio/8010/radio.mp3"},
    {name = "Cadena 3 Cordoba", url = "https://liveradio.mediainbox.net/radio3.mp3"},
    {name = "Cadena Alegría - Córdoba", url = "https://streaming.escuchanosonline.com:7101/stream"},
    {name = "Cadena Express 881 FM", url = "https://streamall.alsolnet.com/cadenaexpress"},
    {name = "Cadena Sur 945 FM", url = "https://streaming.radiosenlinea.com.ar/8860/stream"},
    {name = "CAFF", url = "https://streams.radio.co/s6b80bc417/listen"},
    {name = "Campeones Radio", url = "https://01.solumedia.com.ar:7193/stream"},
    {name = "Chacarereando", url = "https://streamconex.com:8212/;"},
    {name = "Cienradios - 90S Internacional", url = "https://27603.live.streamtheworld.com/90INTER_PYTAAC.aac?"},
    {name = "Cienradios - Adulto Contemporáneo", url = "https://24363.live.streamtheworld.com/ADULTOCONTEMPORANEO_PYTAAC.aac?"},
    {name = "Cienradios - Enamorados", url = "https://27573.live.streamtheworld.com/ENAMORADOS_PYTAAC.aac?"},
    {name = "Cienradios - Grandes Del Rock", url = "https://27393.live.streamtheworld.com/GRANDESDELROCK_PYTAAC.aac?"},
    {name = "Cienradios - Música De Películas", url = "https://27603.live.streamtheworld.com/PELICULAS_PYTAAC.aac?"},
    {name = "Cienradios - Música Romántica", url = "https://26643.live.streamtheworld.com/ROMANTICA_PYTAAC.aac?"},
    {name = "Cienradios - Nuevos Clásicos Internacional", url = "https://26593.live.streamtheworld.com/NCINTER_PYTAAC.aac?"},
    {name = "Cienradios - Pop", url = "https://27603.live.streamtheworld.com/POP_PYTAAC.aac?"},
    {name = "Cienradios - Top 40", url = "https://19793.live.streamtheworld.com/TOP40_PYTAAC.aac?"},
    {name = "CLASS FM 919", url = "http://streaming01.dwservers.net:8400/;"},
    {name = "Classique: Una Radio De Clásicos", url = "https://01.solumedia.com.ar:8562/stream"},
    {name = "CNN AM 950 Arg AAC Alta V3 Ciudad De Buenos Aires", url = "http://unlimited2-ar.dps.live/cnn-ar/aac/icecast.audio"},
    {name = "Concepto FM 955", url = "https://radios.solumedia.com:6002/;"},
    {name = "Concepto FM 955 Mhz", url = "http://radios.solumedia.com:6002/stream"},
    {name = "Concierto FM 947", url = "https://01.solumedia.com.ar:8112/stream"},
    {name = "Conexion Bariloche 939 FM", url = "https://streamconex.com:2000/stream/ConexioxBariloche"},
    {name = "Continental 590 AM Ciudad De Bs As 110 Kbps Mp3", url = "https://alpha.radioplayer.com.ar/stream/continental"},
    {name = "Cosmos Fm", url = "http://s28.myradiostream.com:28240/listen.m4a"},
    {name = "CVC La Voz Urbano", url = "https://chat-assets.frontapp.com/v1/149be82f568687535638c72a66facc34.ogg"},
    {name = "D Sports Radio", url = "http://provisioning.streamtheworld.com/pls/DSPORTSRADIO.pls"},
    {name = "Dale FM 931", url = "https://streaming01.shockmedia.com.ar:10891/;?hash=1659583597942"},
    {name = "De La Costa Radio 1033", url = "http://01.solumedia.com.ar:8176/stream"},
    {name = "De La Mujer", url = "http://165.227.209.68:9990/;stream.mp3"},
    {name = "De La Nueva Bahía 1061 FM", url = "https://radios.solumedia.com/6136/stream"},
    {name = "Del Bosque Radio 891 FM", url = "https://streaming01.shockmedia.com.ar:10598/stream/1/"},
    {name = "Delta 903", url = "https://cdn.instream.audio//:9069//stream"},
    {name = "Delta 903 Buenos Aires", url = "https://cdn.instream.audio/:9069/stream?in_device_id=wp-5270c502-0535-444e-975b-d49592d1d988"},
    {name = "Diamante Fm 957 Mhz", url = "https://proxy01.servidorenlinea.net/streaming1/8014/;"},
    {name = "DIVA´S + MÚSICA FM 899", url = "https://radios.solumedia.com/6490/stream"},
    {name = "Doble A", url = "https://sonic.host-live.com/8268/stream"},
    {name = "Doctor Rock FM 929", url = "http://server.laradio.online:8683/stream/;"},
    {name = "Dr Rock FM 929", url = "http://server.laradio.online:8683/;?"},
    {name = "DS Radio Horizonte 945 FM", url = "http://streaming.radiosenlinea.com.ar:9058/stream/;"},
    {name = "Dsports Radio FM1031", url = "https://24493.live.streamtheworld.com/DSPORTSRADIOAAC.aac"},
    {name = "Eclipse FM 1015 Mhz", url = "https://01.solumedia.com.ar:8746/stream"},
    {name = "Ecos De Mis Cerros", url = "https://masservidor.net:7163/;"},
    {name = "EDI RADIO", url = "https://radio.forensedigital.gt:8090/stream"},
    {name = "El Destape Radio", url = "https://ipanel.instream.audio/8004/stream"},
    {name = "El Paraíso Radio", url = "https://streaming.radiosenlinea.com.ar/9022/stream"},
    {name = "Elite FM 1015", url = "https://radios.solumedia.com/6314/stream"},
    {name = "Emisora Del Este 989 FM Y 981 FM", url = "https://streaming.radiosenlinea.com.ar/8008/;"},
    {name = "Emisora Educativa El Hornero 1077 FM", url = "https://secure.streaming01.dwservers.net/8650/;"},
    {name = "Estacion Del Centro 957 FM", url = "http://stream01.insidetec.com:9040/fm957"},
    {name = "Estacion Victoria 907", url = "http://01.solumedia.com.ar:7786/;"},
    {name = "Estacion XLW", url = "http://radio.solumedia.com.ar:7009/;"},
    {name = "Estación Del Siglo Rio Grande FM 1053", url = "http://streamall.alsolnet.com/estaciondelsigloaudio"},
    {name = "Estación Latidos", url = "http://streaming01.shockmedia.com.ar:8162/"},
    {name = "Estación Mix", url = "http://stream.laut.fm/estacionmix"},
    {name = "Estación Vinilo 891", url = "http://173.255.205.241:1127/;"},
    {name = "Estilos FM 927", url = "http://server12.veemesoft.com.ar:19466/;"},
    {name = "Estirpe Nacional 1250 AM", url = "https://b2-f000.radiocut.com.ar/file/radiocut-2023/estirpe/171/577/1715771741.157-180.010.mp3"},
    {name = "Evolution FM 1019", url = "https://radios.solumedia.com:6140/stream"},
    {name = "Exa FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "F 887 FM", url = "https://server4.hostradios.com/8308/stream"},
    {name = "F5 Radio 1045 FM", url = "http://streaming.shockmedia.com.ar/8724/stream"},
    {name = "Fahrenheit FM 887 Rosario", url = "https://streaming.redboing.com/radio/8010/radio.aac"},
    {name = "FM 1023", url = "https://radios.solumedia.com:6276/stream"},
    {name = "Fm 1061 Estacion 2", url = "https://emisora.zonasinergia.com/8068/stream"},
    {name = "FM 2000 957", url = "http://nvradios.com:9358/;"},
    {name = "Fm 941 Onda Horizonte", url = "http://s1.radiosnethosting.com:9816/;"},
    {name = "Fm 955 Republica", url = "https://edge-st1-audio.masterhost.com.ar/listen/radio_republica_955/radio.mp3"},
    {name = "FM 965 - Residencias", url = "https://01.solumedia.com.ar:8592/stream"},
    {name = "FM 981 Perez Millan", url = "https://server.radiostreaming.com.ar/8470/stream"},
    {name = "FM 999 Olavarría", url = "https://streamall.alsolnet.com/la99olavarria"},
    {name = "FM Actualidad 937", url = "https://server4.hostradios.com/8348/stream/;"},
    {name = "FM Agua 999", url = "https://alpha.radioplayer.com.ar:9162/fmagua999"},
    {name = "FM Alba 893", url = "https://server6.hostradios.com/8246/stream"},
    {name = "FM Alegría 1017 General Pico", url = "https://streaming.radiosenlinea.com.ar/8856/stream/1/"},
    {name = "Fm Alpha 915", url = "http://radio.solumedia.com.ar:8984/stream"},
    {name = "FM ALTITUD 947", url = "https://server.radiostreaming.com.ar/8118/stream"},
    {name = "Fm Amanecer 1013", url = "http://centova.radiosnethosting.com:9870/stream"},
    {name = "FM Amiga 909", url = "http://streaming.conexionproductora.com.ar:19976/;"},
    {name = "FM Amistad 957", url = "https://cdn.instream.audio/:9099/stream"},
    {name = "FM Argentina", url = "http://sonicpanel.hostradios.com:8168/;"},
    {name = "FM Armonía 1051", url = "https://radiosar.com:9346/stream"},
    {name = "FM Arroyos 1033", url = "https://stream.radioservice.org:7014/stream"},
    {name = "FM Atlantic 1059", url = "http://server1.veemesoft.com.ar:26511/;"},
    {name = "FM BAND NEWS 895", url = "https://streaming01.shockmedia.com.ar:10486/"},
    {name = "FM Barrancas 987", url = "https://server.radiostreaming.com.ar/8152/stream"},
    {name = "FM Blackie 891", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/BLACKIE_89_1.mp3"},
    {name = "FM Bragado FM 955", url = "http://sonic.dattalive.com:8310/stream"},
    {name = "FM Brisa 917", url = "https://stream.sistemaultra.com.ar:18144/;"},
    {name = "FM BUENAS NUEVAS 981", url = "https://streaming01.shockmedia.com.ar:10538/stream?icy=http"},
    {name = "FM Calchaqui", url = "https://server.ohradio.com.ar/9856/stream"},
    {name = "FM Calchaqui 1011", url = "http://server.ohradio.com.ar:9856/;"},
    {name = "FM Caldén 999", url = "http://server1.veemesoft.com.ar:6340/;"},
    {name = "FM Capital 977", url = "https://secure.streaming01.dwservers.net/8700/;"},
    {name = "FM Carolina 1029", url = "http://server1.veemesoft.com.ar:26629/;"},
    {name = "FM CENTENARIO 993", url = "https://streaming.radiosenlinea.com.ar/9694/stream"},
    {name = "FM Centro Basavilbaso 1051", url = "https://streamconex.com:8030/stream"},
    {name = "FM Cielo 887", url = "https://server6.hostradios.com:7108/stream"},
    {name = "FM Cosecha", url = "http://www.genexservicios.com:8068/;"},
    {name = "FM CRISTAL 977", url = "https://streaming.radiosenlinea.com.ar/8520/stream"},
    {name = "Fm Dale 961", url = "http://01.solumedia.com.ar:8238/"},
    {name = "FM Del Viento 1049", url = "https://cdn.instream.audio/:9125/stream"},
    {name = "FM Ecos 1043", url = "http://stm34.veemesoft.com.ar:28350/"},
    {name = "FM EL CHUBUT", url = "https://radios.streamingdha.com.ar:9382/;"},
    {name = "FM ESPERANZA 1071 MHZ", url = "https://streaming01.shockmedia.com.ar:10404/stream?icy=http"},
    {name = "FM ESTACION PLUS 993", url = "https://proxy01.servidorenlinea.net/streaming1/8078/;"},
    {name = "FM Estación Popular 1011", url = "https://streaming.escuchanosonline.com:7298/;"},
    {name = "FM Estudio Dos 1059", url = "https://streamall.alsolnet.com/fmestudiohd"},
    {name = "FM EXITO 991", url = "https://01.solumedia.com.ar:8178/;"},
    {name = "FM Federal 995", url = "http://51.161.119.117:8176/stream"},
    {name = "FM Galaxia 887", url = "https://vps-2333016-x.dattaweb.com/listen/fm_galaxia_88.7_cadena_3_san_francisco/radio.mp3"},
    {name = "FM Galeno 1007 Mhz", url = "https://server.radiostreaming.com.ar/8486/stream?1722566655035"},
    {name = "Fm Impacto 1067", url = "https://radios.streamingdha.com.ar:9252/;"},
    {name = "FM Imperio", url = "http://argentina.republicahosting.com:8417/stream"},
    {name = "FM Inti 995Mhz", url = "https://server.ohradio.com.ar/8274/stream"},
    {name = "FM LA 20", url = "http://01.solumedia.com.ar:8386/;stream.nsv"},
    {name = "FM La Boca 901 Buenos Aires", url = "https://s24.myradiostream.com/:14984/listen.mp3?nocache=1674464727"},
    {name = "FM La Uni 917", url = "http://cdn.instream.audio:9275/stream.m3u"},
    {name = "FM LA VOZ TRENEL 965", url = "http://centova.radiosnethosting.com:9824/;"},
    {name = "FM Laser 985 - General Pico", url = "https://streamconex.com:8076/stream/"},
    {name = "FM Latidos 951 - General Pico", url = "https://streamconex.com:8150/stream"},
    {name = "Fm Latina 925 Salta", url = "http://streaming.radiosenlinea.com.ar:9640/;"},
    {name = "FM Latina 997", url = "https://emisora.zonasinergia.com:7101/stream"},
    {name = "FM Millenium 1067", url = "https://player.questreaming.com/?pl=vlc&c=fmmilenium"},
    {name = "FM Plus 931 Rosario", url = "http://fmplus.radio.rosario3.com:8006/"},
    {name = "FM Poder", url = "http://server.ohradio.com.ar:8206/stream',"},
    {name = "FM Punta 881", url = "https://server7.hostradios.com/8140/stream"},
    {name = "FM Rock Zarate | FM 1033", url = "https://sonic.dattalive.com:10821/stream"},
    {name = "FM Sol Y Luna 1041 Mhz", url = "http://s2.argentina-streaming.com/8432/stream"},
    {name = "FM Universidad - 1057 UTN Paraná", url = "https://sc.dattalive.com/8206/stream"},
    {name = "FM Universidad 987 - Universidad Nacional De Misiones", url = "https://fm.unam.edu.ar/fm"},
    {name = "FM1051", url = "http://173.255.205.241:8180/;"},
    {name = "FMQ", url = "http://streamlky.alsolnet.com:443/radiofmq"},
    {name = "Frecuencia Arena 983", url = "https://stream.serviciowebdigital.com/8854/stream"},
    {name = "Frecuencia Urbana 887 General Roca", url = "https://sc.dattalive.com:10929/stream"},
    {name = "Fresh Radio FM 1029FM", url = "https://streaming.escuchanosonline.com:7011/stream"},
    {name = "Gravity Radio", url = "https://stream.xweb.ar/8024/stream"},
    {name = "Guajira Radio", url = "http://01.solumedia.com.ar:8252/stream"},
    {name = "HIT RADIO FFH 128K AAC Argentina", url = "http://mp3.ffh.de/radioffh/hqlivestream.aac"},
    {name = "Horizonte 1031 - Santa Rosa", url = "http://sslstream.online:8204/live"},
    {name = "Horizonte Perfil 1019", url = "https://26343.live.streamtheworld.com/SAM06AAC243_SC"},
    {name = "IMPACTO FM REALICO - LA PAMPA", url = "http://streaming01.shockmedia.com.ar:9722/reproductores/?idr=NTQz"},
    {name = "Itunes TOP 40 FFH 128K AAC Argentina", url = "https://mp3.ffh.de/ffhchannels/hqtop40.aac"},
    {name = "K2 RADIO 963 FM", url = "https://cdn.instream.audio/:9568/stream"},
    {name = "Kiss FM 951 Rosario", url = "https://streaming.redboing.com/radio/8060/radio.mp3"},
    {name = "KLA Radio 971", url = "https://streamconex.com:8104/stream?1722096115054"},
    {name = "La 100 - 999 FM - Grupo Clarín - Buenos Aires, Argentina", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/FM999_56.mp3"},
    {name = "La 100 Clásicos - Disco Retro Clásicos", url = "https://27323.live.streamtheworld.com/FCLASICOS_56AAC.aac?"},
    {name = "La 2X4", url = "https://media.radios.ar:9270/"},
    {name = "La 97", url = "https://streaming01.shockmedia.com.ar:10586/stream"},
    {name = "La 97 Radio Fueguina Rio Grande Y Ushuaia", url = "https://streamall.alsolnet.com/radiofueguina"},
    {name = "La Cacharpaya", url = "http://streaming01.shockmedia.com.ar:9360/stream"},
    {name = "La City", url = "http://01.solumedia.com.ar:7485/;"},
    {name = "La Colectiva", url = "https://radios.solumedia.com/6198/stream"},
    {name = "La Estación FM 1079", url = "http://01.solumedia.com.ar:2199/tunein/chicossrl.pls"},
    {name = "La Estación Fm 1079 Salta", url = "http://radio.solumedia.com.ar:8462/stream"},
    {name = "La Hit Córdoba", url = "http://stm23.veemesoft.com.ar:24308/;"},
    {name = "La Popu", url = "https://liveradio.mediainbox.net/popular.mp3"},
    {name = "La Popu 923", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/lapopu.mp3?dist=c3-web"},
    {name = "LA RADIO 1047", url = "https://server.laradio.online:2199/tunein/laradio1047.pls"},
    {name = "La Radio 935", url = "https://01.solumedia.com.ar:8494/stream"},
    {name = "La Radio De Los Lentos", url = "https://01.solumedia.com.ar:7828/stream"},
    {name = "La Rocka Rck FM 1073", url = "http://cdn.instream.audio:8137/stream"},
    {name = "La Super Radio 963 General Roca", url = "https://sc.dattalive.com/8070/stream"},
    {name = "La Supersonica", url = "https://c11.radioboss.fm:8093/stream"},
    {name = "LA990", url = "https://21933.live.streamtheworld.com/AM990.mp3"},
    {name = "Larz", url = "https://streamlky.alsolnet.com/larz"},
    {name = "Lola", url = "https://cdn.instream.audio/:9081/stream"},
    {name = "Los 40 Arg FM 1055 Bs As Version 1", url = "https://frontend.radiohdvivo.com/los40/live"},
    {name = "Los 40 Argentina", url = "https://alpha.radioplayer.com.ar/stream/los40"},
    {name = "LT20 Radio Junin AM 1470", url = "http://01.solumedia.com.ar:8260/;"},
    {name = "LU11 Radioemisora Del Oeste Trenque Lauquen", url = "https://radiosar.com:7045/stream"},
    {name = "LU15 Radio Viedma AM 800 Rio Negro", url = "https://alpha.radioplayer.com.ar:9206/LU15AM800"},
    {name = "LU19 Radio Cipolletti AM690", url = "https://sonic.dattalive.com/8064/stream"},
    {name = "LU24 Radio Tres Arroyos", url = "https://streaming01.shockmedia.com.ar:10889/stream?icy=http"},
    {name = "LU33 Emisora Pampeana AM 890 - Santa Rosa", url = "http://01.solumedia.com.ar:8324/stream"},
    {name = "LU6 - Radio Atlantica - Mar Del Plata", url = "http://173.255.205.241:9090/;stream.nsv"},
    {name = "LU6 Emisora Atlántica AM 760 Mar Del Plata", url = "http://173.255.205.241:7070/;"},
    {name = "LV11", url = "https://streaming.evolucionstreaming.com/8040/stream?hash=16935913338https://streaming.evolucionstreaming.com/8040/stream?hash=1693591333817"},
    {name = "Magic Box FM 1073", url = "https://stream01.server-inside.com.ar:9652/magicbox"},
    {name = "Magic Kids FM", url = "http://argentina.republicahosting.com:8197/stream"},
    {name = "Malva FM - General Pico", url = "https://cdn.instream.audio/:9310/stream"},
    {name = "Marea FM", url = "https://sonic.mediatelekom.net/9016/stream"},
    {name = "María Argentina", url = "http://dreamsiteradiocp.com:8004/"},
    {name = "Mañana Intensa", url = "https://server.streamcasthd.com/8272/stream"},
    {name = "Mediterraneo 983 Mhz", url = "https://streaming01.radiosenlinea.com.ar:10996/stream"},
    {name = "Meridiano FM 985", url = "https://streaming.escuchanosonline.com:7346/stream"},
    {name = "Metro 951", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/METRO.mp3"},
    {name = "Milenium 1067 FM", url = "https://sonicpanel.hostradios.com/8002/stream"},
    {name = "Mitre AM 790 AAC Alta Ciudad De Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/AM790_56AAC.aac"},
    {name = "Modo Radio 1069", url = "https://streaming01.shockmedia.com.ar:10609/stream"},
    {name = "Ndr Radio", url = "https://streamconex.com:8096/;?listening-from-radio-garden=1640125124"},
    {name = "Neo Net Music", url = "https://sonic.dattalive.com/8670/stream"},
    {name = "Net Classic FM 903 San Lorenzo", url = "https://alpha.radioplayer.com.ar:9232/netclassic903"},
    {name = "Net80 Radio", url = "https://streaming.escuchanosonline.com/8274/stream"},
    {name = "NQP Radio", url = "http://cdn.instream.audio:8111/stream"},
    {name = "Nuestra FM La Adela FM 1075", url = "http://server1.veemesoft.com.ar:10147/;"},
    {name = "OK FM Arroyito", url = "http://audio.questreaming.com:27156/"},
    {name = "Planet Music Bahía Blanca", url = "https://strcdn.klm99.com:10987/planetbahia"},
    {name = "Planet Music Mar Del Plata 1011", url = "https://strcdn.klm99.com:10991/planetmdp"},
    {name = "Planet Music Pinamar 995", url = "https://strcdn.klm99.com:10984/planetpinamar"},
    {name = "Planet Music Villa Gesell 919", url = "https://strcdn.klm99.com:10986/planetvillagesell"},
    {name = "Plus 931 FM", url = "http://fmplus.radio.rosario3.com:8006/fmplus"},
    {name = "Pontiac Rock", url = "https://radios.solumedia.com/6268/stream"},
    {name = "Punto Y Coma", url = "http://01.solumedia.com.ar:7810/;"},
    {name = "Q103 Radio", url = "http://01.solumedia.com.ar:7139/;"},
    {name = "Radiactiva 1007", url = "http://sh4.radioonlinehd.com:8533/stream"},
    {name = "Radio 1: Electriccircus", url = "https://radio.eduneu.ar/public/radio1/playlist.pls"},
    {name = "Radio 2 1230 AM", url = "http://radio2.radio.rosario3.com:8000/prueba2"},
    {name = "Radio Activa FM 969 - Ing Mashwitz", url = "http://streaming01.shockmedia.com.ar:9332/stream"},
    {name = "RADIO ARIAS FM 911 JUJUY", url = "https://cdn.instream.audio/:9095/stream"},
    {name = "Radio Azul Tolhuin FM 1009", url = "http://genexservicios.com:8310/;?1666493861674"},
    {name = "RADIO BEAT 975 FM", url = "http://audio.questreaming.com:27902/;"},
    {name = "Radio Bicentenario Tucumán", url = "http://01.solumedia.com.ar:7792/;stream/1"},
    {name = "Radio Boing 973 Rosario", url = "https://streaming.redboing.com/radio/8000/radio.aac"},
    {name = "Radio Britannia", url = "http://01.solumedia.com.ar:8472/stream/;"},
    {name = "Radio Buenos Aires LS6 AM 1350 Khz", url = "https://nl.digitalrm.pt:8052/stream"},
    {name = "Radio Cadena 3", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO3_SC"},
    {name = "Radio Cadena Norte FM", url = "http://centova.questreaming.com:26834/;"},
    {name = "Radio Cadena Sol 1065 FM", url = "http://www.genexservicios.com:8294/;"},
    {name = "RADIO CADENA VIDA 953 FM", url = "https://host.serviceinfinito.com.ar:7006/;"},
    {name = "Radio Cantilo", url = "http://radio.solumedia.com.ar:7231/stream"},
    {name = "Radio Caput", url = "http://69.64.46.123:8132/stream?type=.mp3"},
    {name = "Radio Centinela", url = "https://01.solumedia.com.ar:8050/stream"},
    {name = "RADIO CENTRO", url = "https://sonicpanel.hostradios.com/8710/stream"},
    {name = "Radio Centro 993 - General Pico", url = "https://https.nvradios.com/radio/9340/radio.mp3"},
    {name = "Radio Cielo - FM 1069 Mhz Zarate", url = "http://streamall.alsolnet.com:443/radiocielo"},
    {name = "Radio Ciudad AM 1110", url = "https://media.radios.ar:1110/"},
    {name = "Radio Comunitaria FM Punta Del Indio", url = "http://streaming.conexionproductora.com.ar:9650/"},
    {name = "Radio Comunitaria Laquintapata", url = "http://server3.veemesoft.com.ar:26429/;"},
    {name = "Radio Con Vos 899 FM", url = "https://www.surfmusic.de/m3u/radio-con-vos-89-9-fm,20048.m3u"},
    {name = "Radio Concierto 965 FM", url = "https://vivohd.fmradioconcierto.com.ar:8000/radio.mp3"},
    {name = "RADIO CONCIERTO 971 MHZ", url = "https://vivohd.fmradioconcierto.com.ar:8000/status-json.xsl//radio.mp3"},
    {name = "Radio Continental", url = "https://alpha.radioplayer.com.ar/stream/cadenacontinental"},
    {name = "Radio Cool FM 1037", url = "https://radios.solumedia.com:10805/stream/1/"},
    {name = "Radio Cristiana FM 883", url = "https://rr5100.globalhost1.com/8540/;"},
    {name = "Radio Cultura", url = "https://streaming.escuchanosonline.com:7035/stream"},
    {name = "Radio De Clásicos 1069 FM - Saladillo", url = "http://streamconex.com:8118/stream"},
    {name = "Radio De Tango", url = "https://fair.entic.net:8010/tango"},
    {name = "Radio Del Plata", url = "https://streaming01.shockmedia.com.ar:10217/stream"},
    {name = "Radio Del Puerto FM 921 Barranqueras Chaco", url = "https://streaming.escuchanosonline.com:7106/stream"},
    {name = "Radio Digital San Luis 1011 FM", url = "https://streamconex.com:8062/;"},
    {name = "Radio Disney Argentina 943", url = "https://provisioning.streamtheworld.com/pls/DISNEY_ARG_BA_ADP.pls"},
    {name = "Radio Disney Argentina 943 Ciudad De Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_ARG_BA.mp3"},
    {name = "RADIO DON", url = "https://01.solumedia.com.ar:8936/stream"},
    {name = "Radio Dos Corrientes FM 993 Ciudad De Corrientes", url = "https://radios.solumedia.com/6396/stream"},
    {name = "Radio El Mundo - AM 1070", url = "https://streaming.escuchanosonline.com:7118//stream?type=http&nocache=1"},
    {name = "Radio Espiritu Santo", url = "http://01.solumedia.com.ar:7802/;"},
    {name = "Radio Estacion Sur", url = "http://88.198.9.174:8196/live"},
    {name = "Radio Estelar - Classicos", url = "http://01.solumedia.com.ar:7607/;"},
    {name = "Radio Estudios Max", url = "http://streaming.shockmedia.com.ar:8002/stream"},
    {name = "Radio Flow", url = "http://stream.zeno.fm/5rxr1mcdcxhvv.m3u"},
    {name = "Radio Flow On", url = "http://stream.zeno.fm/5rxr1mcdcxhvv.pls"},
    {name = "Radio FM Ayres 965 Mhz", url = "https://server.ohradio.com.ar/8050/stream"},
    {name = "Radio Gráfica", url = "http://radio13.servidorderadio.net:8110/"},
    {name = "Radio Impacto", url = "https://server.streamcasthd.com/8022/stream"},
    {name = "Radio Impacto Cordoba", url = "http://sonic.cloudstreaming.eu:9992/;"},
    {name = "Radio Infinity", url = "https://sonic.dattalive.com/8192/stream"},
    {name = "Radio Influencia", url = "http://genexservicios.com:8134/;?1713795357814"},
    {name = "Radio Jornada FM 919", url = "https://edge-st1-audio.masterhost.com.ar/listen/jornada_online_mdz/radio.mp3"},
    {name = "Radio Kermés Comunitaria", url = "http://server.laradio.online:8599/;"},
    {name = "Radio La Plaza 947", url = "https://radio.arcast.net:1045/stream"},
    {name = "Radio La Red AM 910", url = "https://21933.live.streamtheworld.com/LA_RED_AM910AAC.aac"},
    {name = "Radio La Red AM 910 Ciudad De Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LA_RED_AM910AAC.aac"},
    {name = "Radio Las Rosas", url = "http://streaming01.shockmedia.com.ar:9676/;"},
    {name = "Radio Latina FM 1011", url = "http://streaming.latina101.com.ar:9000/Repetidoras"},
    {name = "Radio Legislatura", url = "http://186.189.66.4:8100/source"},
    {name = "Radio Longplay", url = "http://server.ohradio.com.ar:9352/;"},
    {name = "RADIO MARIA ARGENTINA", url = "http://dreamsiteradiocp.com:8004/stream"},
    {name = "Radio Maxi FM", url = "http://cloudstream2036.conectarhosting.com:8140/listen.pls"},
    {name = "Radio Mitre", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/AM790_56AAC_SC"},
    {name = "Radio Mitre AM 790 Buenos Aires", url = "https://24273.live.streamtheworld.com/AM790_56AAC.aac"},
    {name = "Radio Monk", url = "http://streaming01.shockmedia.com.ar:9858/;"},
    {name = "Radio Más", url = "http://nvradios.com:9384/;"},
    {name = "Radio Natagalá FM 947 Resistencia Chaco", url = "http://radio02.ferozo.com:8704/;"},
    {name = "Radio Norte", url = "https://icecast.hostingbahia.com.ar:8002/live?90131"},
    {name = "Radio Norte Bahia", url = "http://icecast.hostingbahia.com.ar:8002/live?1475282235673"},
    {name = "Radio Noticias FM 995 - Santa Rosa", url = "http://stream01.insidetec.com:9014/radionoticias"},
    {name = "Radio NOW 979", url = "https://ipanel.instream.audio:7002/stream?_=18fea7232d5"},
    {name = "Radio On The Route", url = "http://01.solumedia.com.ar:7345/;"},
    {name = "Radio Onda | Tigre Argentina", url = "http://149.202.235.235:8011/live"},
    {name = "Radio Orión", url = "http://01.solumedia.com.ar:7834/stream?icy=http"},
    {name = "Radio Patagonia Puerto Madryn FM 1055", url = "https://stream.servidorm24.net:7004/stream"},
    {name = "Radio Piamonte - FM Tiempo 925", url = "https://server.radiostreaming.com.ar/8288/stream;?1721304335025"},
    {name = "Radio Pueblo De Maria", url = "http://01.solumedia.com.ar:7018/;"},
    {name = "Radio Quilpo", url = "https://https.nvradios.com/radio/9352/radio.mp3"},
    {name = "Radio República", url = "http://streamlky.alsolnet.com:443/republica99"},
    {name = "Radio Rivadavia AM 630 Ciudad De Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac"},
    {name = "Radio Saint Germain", url = "http://173.255.205.241:8200/"},
    {name = "Radio Santa Cecilia", url = "https://01.solumedia.com.ar:8492/stream"},
    {name = "Radio Semilla FM 1065 - IMPA", url = "https://sslstream.online:7091/;"},
    {name = "Radio Sublime Gracia", url = "https://stream.consultoradas.com/8174/stream"},
    {name = "Radio Suquia", url = "https://streaming01.shockmedia.com.ar:10945/"},
    {name = "Radio Sur - FM 883 Mhz", url = "https://01.solumedia.com.ar:8020/stream"},
    {name = "Radio Sur FM 883", url = "http://01.solumedia.com.ar:8020/stream"},
    {name = "Radio Sur FM 901", url = "https://ssl.dainusradio.com/shoutcast2/9848/"},
    {name = "Radio Tecnoteca", url = "https://server7.hostradios.com:8142/stream"},
    {name = "Radio Trend Topic", url = "https://sonic.dattalive.com/8480/stream"},
    {name = "Radio Trinchera", url = "https://server7.hostradios.com/8316/stream"},
    {name = "Radio Universidad - FM911 UTN Resistencia", url = "http://01.solumedia.com.ar:8336/"},
    {name = "Radio Universidad - FM935 La Tecno UTN Tierra Del Fuego", url = "http://streamall.alsolnet.com/latecno"},
    {name = "Radio Universidad - UNLP - AM 1390", url = "https://statics-v2.streema.com/static/audios/sample.ea78c3d52389.mp3"},
    {name = "Radio Universidad AM580", url = "https://radios.solumedia.com:10976/stream"},
    {name = "Radio Universidad CALF Neuquén", url = "https://cdn.instream.audio/:9032/stream?in_device_id=wp-5270c502-0535-444e-975b-d49592d1d988"},
    {name = "Radio Universo FM1003 Carhue", url = "http://server11.veemesoft.com.ar:28918/Stream/;"},
    {name = "Radio Unlu", url = "http://144.217.30.219:8043/"},
    {name = "Radio UNR", url = "https://cdn.instream.audio/:9202/stream"},
    {name = "Radio UTN Bahia Blanca - FM 935", url = "https://sonic.cloudstreaming.eu:10986/;"},
    {name = "Radio Valle Viejo", url = "https://stm2.livecastradio.com:9379/stream"},
    {name = "Radio Vitalista", url = "http://01.solumedia.com.ar:7169/;"},
    {name = "Radio Vos 887", url = "http://centova1.veemesoft.com.ar:12378/;"},
    {name = "Radio Vos Salta 901", url = "http://streaming01.shockmedia.com.ar:9200/;"},
    {name = "RADIO ZETA 945 Mhz, La Plata Buenos Airesargentina", url = "https://server.ohradio.com.ar/9650/stream"},
    {name = "Radiovision 995 Fm", url = "https://cdn.instream.audio/:9061/stream?in_device_id=wp-e80516ae-250e-4455-ac11-14ce5f370cc8"},
    {name = "Ranquel FM", url = "https://server6.hostradios.com/8556/stream/;type=mp3"},
    {name = "RBD Radio Multimedia", url = "https://streaming.radiosenlinea.com.ar:10637/live?_=1"},
    {name = "Rc", url = "http://radio13.servidorderadio.net:9648/"},
    {name = "REAL POLITIK FM", url = "https://01.solumedia.com.ar:8638/stream?icy=http"},
    {name = "Red 92", url = "https://radios.solumedia.com/6426/stream"},
    {name = "Renacer Fm 975", url = "https://emisora.brotherservicios.com/8018/stream"},
    {name = "Revuelto Radio", url = "https://cdn.instream.audio:9097/stream"},
    {name = "Rincón Gaucho", url = "https://dj91.hostingnuclear.com/9952/stream"},
    {name = "Rio FM 1043 General Belgrano", url = "https://sonicpanel.hostradios.com/8032/stream"},
    {name = "Rio FM 969 Rosario", url = "https://streaming.redboing.com/radio/8070/radio.mp3"},
    {name = "Rio Negro Radio 919 General Roca", url = "https://01.solumedia.com.ar:7004/stream"},
    {name = "Rivadavia", url = "https://24383.live.streamtheworld.com/RIVADAVIAAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=300x250%2C728x90&burst-time=15&sbmid=9892438b-a3ed-44ab-d837-6399dac0aa64"},
    {name = "Rock And Pop FM 959 Rock Pop Ciudad De Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ROCKANDPOPAAC.aac"},
    {name = "RPM Oldies Retro Hits", url = "https://radios.solumedia.com/6118/stream"},
    {name = "S", url = "https://stream.almadinafm.com/;stream.mp3"},
    {name = "San Roque Fm, 979 Mhz", url = "https://s21.myradiostream.com/10952/listen.mp3"},
    {name = "Sensation Radio 1075 Neuquén", url = "http://radio01.ferozo.com:8976/;stream.nsv"},
    {name = "Si 989 FM", url = "http://server.laradio.online:8202/;"},
    {name = "Simphony San Isidro FM 913 Mhz", url = "http://cdn.instream.audio:8129/stream.m3u"},
    {name = "Somos Radio - AM 530 Radio De Las Madres De Plaza De Mayo", url = "https://cdn.instream.audio:9288/stream"},
    {name = "Spacio Fm Metan", url = "https://sonic.dattalive.com/8598/stream"},
    {name = "TD Radio", url = "http://149.202.235.235:8133/live"},
    {name = "The Musical Box Radio", url = "http://albireo.shoutca.st:9740/stream"},
    {name = "Tiempo 975 FM", url = "https://sc.host-live.com/8166/stream"},
    {name = "TMB The Musical Box", url = "https://tmbradio.radioca.st/stream"},
    {name = "Universidad Claf 1037 Mhz", url = "http://cdn.instream.audio:9032/stream"},
    {name = "UNRC Radio", url = "https://server6.hostradios.com:7280/stream"},
    {name = "Urbana Play 1043", url = "https://ice1.edge-apps.net/urbana.audio"},
    {name = "VIP Radio", url = "https://server6.hostradios.com:7232/;?"},
    {name = "Wclassicradio", url = "http://server.ohradio.com.ar:9604/stream/;"},
    {name = "XRADIO 991", url = "https://radios.streamingdha.com.ar/9826/;"},
}

return stations
