local stations = {
    {name = "   Radio Disney 94.3 - Buenos Aires, Argentina", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_ARG_BA_ADP.aac"},
    {name = " FM 94.3 Radio Municipal de Toay", url = "http://servidor.ilive.com.ar:9678/;"},
    {name = " La SuperSonica", url = "https://c11.radioboss.fm:8093/stream"},
    {name = " Radio Mitre", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/AM790_56AAC_SC"},
    {name = "_Boca Juniors FM", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "@twitradioo", url = "http://s2.netradiofm.com:6338/"},
    {name = "101.5Music - La Radio de la Música", url = "http://190.1.0.5:8035/;"},
    {name = "102.5 Medios del Aire (General Roca)", url = "https://server6.hostradios.com:7041/;"},
    {name = "107.9 El Observador", url = "https://s8.stweb.tv/observador/live/playlist.m3u8"},
    {name = "107.9 El Observador version 2", url = "http://s8.stweb.tv:1935/observador/live/playlist.m3u8"},
    {name = "107.9 El Observador version 3", url = "https://s8.stweb.tv/observador/live/playlist.m3u8"},
    {name = "221Radio (FM 103.1)", url = "https://radios.solumedia.com:10815/stream"},
    {name = "550 AM La Primera ", url = "https://s2.argentina-streaming.com:10851/stream"},
    {name = "88.9 FM Radio Light", url = "http://streamall.alsolnet.com/radiolightfm"},
    {name = "90 Radio (FM 90.1)", url = "http://sonicpanel.hostradios.com:8108/;"},
    {name = "92.5 FM Radio 2000", url = "https://server6.hostradios.com/8390/stream"},
    {name = "94.5 Máxima FM ", url = "http://server.laradio.online:8797/;"},
    {name = "96.1 Shopping Classics", url = "https://stream4.suenas.net/shoppingclassics"},
    {name = "98.5 Orfeo FM", url = "https://vps-6de10815.vps.ovh.ca:10970/;"},
    {name = "ABC Mundial Radio", url = "http://01.solumedia.com.ar:7054/;"},
    {name = "Aborigen Radio FM 105.3", url = "https://server.laradio.online:18446/live"},
    {name = "Acqua FM 100.1", url = "https://strcdn.klm99.com:10985/acquavillagesell"},
    {name = "Activa FM 93.5", url = "https://streaming5.locucionar.com/proxy/activafm?mp=/stream"},
    {name = "AIRE", url = "http://stm14.xcast.com.br:8248/"},
    {name = "Aire Libre 96.3 Río Grande", url = "http://streamingraddios.net:9277/stream"},
    {name = "Aire Libre 96.3 Río Grande ", url = "http://streamingraddios.net:9277/"},
    {name = "Aire Libre 96.3 Río Grande ", url = "http://streamingraddios.net:9277/stream?type=http&nocache=160387"},
    {name = "Alegría FM 99.7", url = "http://radio.solumedia.com.ar:8004/;"},
    {name = "Alternativa 99.3 FM", url = "https://radio01.ferozo.com/proxy/ra01000727?mp=/stream"},
    {name = "Alternativa FM 107.1", url = "http://audio.questreaming.com:25181/;"},
    {name = "Always Hits Radio", url = "https://stream.zeno.fm/yqb6aauhtv8uv"},
    {name = "Am 1050 San Francisco ", url = "https://vps-2333016-x.dattaweb.com/listen/am_1050_radio_san_francisco/radio.mp3"},
    {name = "AM 1230 Creativa", url = "https://streaming3.locucionar.com/proxy/creativaonline?mp=/stream"},
    {name = "AM 1270 - Radio Provincia de Buenos Aires", url = "https://streaming.provinciaradio.com.ar:7008/am"},
    {name = "AM 1440 IMPACTO", url = "https://server.laradio.online:58165/live?1721826220781"},
    {name = "AM 530 Somos radio", url = "https://ipanel.instream.audio:7000/stream"},
    {name = "Am 630 Jujuy", url = "https://stream.arcast.com.ar/radio/am630.stream/playlist.m3u8"},
    {name = "AM 750 Una señal", url = "https://26673.live.streamtheworld.com/AM750AAC_SC"},
    {name = "AM 830 LT8 Rosario", url = "https://stream.lt8.com.ar:8443/lt8radio.mp3"},
    {name = "AM 830 Radio del Pueblo", url = "https://streaming6.locucionar.com:24248/stream"},
    {name = "AM Con Vos 1420. AM 1420", url = "https://us9.maindigitalstream.com/ssl/7192"},
    {name = "AM CUMBRE 1400", url = "https://cdn.instream.audio/:9366/stream"},
    {name = "AM CUMBRE 1400", url = "https://cdn.instream.audio/:9366/stream"},
    {name = "AM1330 Rosario", url = "http://s2.argentina-streaming.com:8156/;"},
    {name = "AM750", url = "https://26673.live.streamtheworld.com/AM750AAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=0d038027-7e61-45c6-bf8e-03d246e129b7"},
    {name = "AM750", url = "https://26673.live.streamtheworld.com/AM750AAC.aac"},
    {name = "AM750", url = "https://26673.live.streamtheworld.com/AM750AAC.aac"},
    {name = "Amadeus", url = "https://streamingradiolinks.xyz/8484/;"},
    {name = "AMADEUS", url = "http://18.220.84.192:8484/;"},
    {name = "Amadeus 91.1", url = "https://streamingradiolinks.xyz/8484/;"},
    {name = "Amadeus 91.1", url = "https://streamingradiolinks.xyz/8484/;"},
    {name = "Animal FM 100.7", url = "https://radio02.ferozo.com/proxy/ra02001217?mp=/stream"},
    {name = "Antena 1 91.5 FM", url = "https://s3.netradiofm.com/p/9008/stream"},
    {name = "Antena 1 radio", url = "https://streaming.escuchanosonline.com/8268/stream"},
    {name = "Antena 98.9", url = "http://server1.veemesoft.com.ar:8064/live"},
    {name = "antena libre 89.1 argentina universidad conahue", url = "http://cdn.instream.audio:9140/stream"},
    {name = "Antena Libre 89.1 FM", url = "https://cdn.instream.audio/:9140/stream"},
    {name = "Antena Nueve 94.3 FM", url = "https://radios.solumedia.com:10918/;"},
    {name = "Antena Uno 92.3FM Posadas", url = "https://radios.solumedia.com:10818/;"},
    {name = "Aquí Cosquín Radio", url = "https://kappa.radioplayer.com.ar:9354/aquicosquin937"},
    {name = "Arco Iris FM 98.1 ", url = "http://centova.questreaming.com:4058/;"},
    {name = "Argantina  Pop", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "Aries FM 91.1", url = "https://streaming3.locucionar.com/proxy/ariesonline?mp=/stream"},
    {name = "Aspen 102.3", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ASPEN.mp3"},
    {name = "Bar de Blues Radio", url = "https://streamingraddios.online/proxy/bardeblues?mp=/stream"},
    {name = "Beat 90200", url = "http://radio02.ferozo.com:8850/stream"},
    {name = "Beat Digital Radio", url = "http://stream.zeno.fm/9s7nnwmknkhvv.m3u"},
    {name = "BeatRadio - General Pico", url = "https://server.ohradio.com.ar:7043/stream"},
    {name = "Beats Radio 100.5 FM", url = "https://streaming.shockmedia.com.ar/9778/stream"},
    {name = "berlin 107.9", url = "http://s8.stweb.tv/berlin/live/playlist.m3u8"},
    {name = "Berlín 107.9", url = "https://s8.stweb.tv/berlin/live/playlist.m3u8"},
    {name = "Big FM 91.9 Rosario", url = "https://radio01.ferozo.com/proxy/ra01000666?mp=/stream;\\"},
    {name = "Binaural Rock Radio", url = "http://01.solumedia.com.ar:7870/;"},
    {name = "Blackie 89.1", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/BLACKIE_89_1.mp3"},
    {name = "Blend Radio", url = "https://sysmedia.com.ar:8100/blendradio_web"},
    {name = "blu fm", url = "https://icecasthd.net/proxy/blufm/stream"},
    {name = "Blue 100.7 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/BLUE_FM_100_7AAC.aac"},
    {name = "Blue FM 100.7. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/BLUE_FM_100_7AAC.aac"},
    {name = "Blur fm", url = "http://live.radiovague.com:8000/blurfm03"},
    {name = "Blur Radio", url = "https://live.radiovague.com:8443/blurfm04"},
    {name = "BRH - Bahía Radio Hits", url = "https://miestacion.turadioonline.com.ar/8158/stream"},
    {name = "Bunker FM 91.9", url = "https://azura.derflusweb.com/radio/8010/radio.mp3"},
    {name = "Cadena 103 103.1 FM", url = "https://stream.arcast.com.ar/cadena103audio/cadena103audio.stream/playlist.m3u8"},
    {name = "Cadena 3", url = "http://server.laradio.online:8018/stream"},
    {name = "Cadena 3 Cordoba", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/radio3.mp3"},
    {name = "Cadena 3 Cordoba", url = "https://liveradio.mediainbox.net/radio3.mp3"},
    {name = "Cadena Alegría - Córdoba", url = "https://streaming.escuchanosonline.com:7101/stream"},
    {name = "Cadena Cumbia Latina 89.3 FM", url = "https://stream-160.zeno.fm/60pqgs97f2zuv?zs=BCmVbzf4RheaQLwJZpq_Og"},
    {name = "Cadena Eco AM 1220", url = "https://node-35.zeno.fm/uyd6h9w162quv?rj-ttl=5&rj"},
    {name = "Cadena Energy", url = "http://innovatingthenet.com.ar:8001/energyai.mp3"},
    {name = "Cadena Express 88.1 FM", url = "https://streamall.alsolnet.com/cadenaexpress"},
    {name = "Cadena Heat", url = "https://liveradio.mediainbox.net/fmcordoba.mp3"},
    {name = "Cadena Heat", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/cadenaheat.mp3?dist=c3-web"},
    {name = "Cadena Integración 92.1 FM", url = "https://streaming1.locucionar.com/proxy/cadintegracion?mp=/stream"},
    {name = "Cadena Melodías 99.1", url = "https://tolkien.republicahosting.net:2381/live"},
    {name = "Cadena Nueve 89.9 FM", url = "https://radio01.ferozo.com/proxy/ra01000626/?mp=/;"},
    {name = "Cadena Oh 94.1 FM", url = "https://stream.arcast.com.ar/cadenaoh/cadenaoh.stream/playlist.m3u8"},
    {name = "Cadena Rio FM 88.7", url = "https://radio02.ferozo.com/proxy/ra02001342?mp=/stream"},
    {name = "Cadena Ser Argentina 100.9 FM", url = "https://server.laradio.online:58381/live"},
    {name = "Cadena Space 96.9 FM", url = "http://52.9.150.45:8000/;"},
    {name = "Cadena Sur 94.5 FM", url = "https://streaming.radiosenlinea.com.ar/8860/stream"},
    {name = "CAFF", url = "https://streams.radio.co/s6b80bc417/listen"},
    {name = "Campeones radio", url = "https://01.solumedia.com.ar:7193/stream"},
    {name = "Chacarereando", url = "https://streamconex.com:8212/;"},
    {name = "Chajarí al Día 940 AM", url = "http://190.185.128.226:8001/AM940"},
    {name = "Chascomús AM 1520", url = "https://streaming1.locucionar.com/proxy/radiochascomus?mp=/stream"},
    {name = "Chaski Radio", url = "https://server.laradio.online/proxy/ruben_mansilla?mp=/stream"},
    {name = "Cienradios - 80s Internacional", url = "https://24283.live.streamtheworld.com/80INTERNACIONAL_PYTAAC.aac?"},
    {name = "Cienradios - 90s Internacional", url = "https://27603.live.streamtheworld.com/90INTER_PYTAAC.aac?"},
    {name = "Cienradios - Adulto Contemporáneo", url = "https://24363.live.streamtheworld.com/ADULTOCONTEMPORANEO_PYTAAC.aac?"},
    {name = "Cienradios - Enamorados", url = "https://27573.live.streamtheworld.com/ENAMORADOS_PYTAAC.aac?"},
    {name = "Cienradios - Grandes del Rock", url = "https://27393.live.streamtheworld.com/GRANDESDELROCK_PYTAAC.aac?"},
    {name = "Cienradios - Música de Películas", url = "https://27603.live.streamtheworld.com/PELICULAS_PYTAAC.aac?"},
    {name = "Cienradios - Música en Vivo", url = "https://24223.live.streamtheworld.com/MUSICAENVIVO_PYTAAC.aac?"},
    {name = "Cienradios - Música Romántica", url = "https://26643.live.streamtheworld.com/ROMANTICA_PYTAAC.aac?"},
    {name = "Cienradios - Nuevos Clásicos Internacional", url = "https://26593.live.streamtheworld.com/NCINTER_PYTAAC.aac?"},
    {name = "Cienradios - Pop", url = "https://27603.live.streamtheworld.com/POP_PYTAAC.aac?"},
    {name = "Cienradios - Rock Nacional", url = "https://27583.live.streamtheworld.com/NACIONAL_PYTAAC.aac?"},
    {name = "Cienradios - The Beatles y Artistas Relacionados", url = "https://24233.live.streamtheworld.com/JOHNPAULGEORGERINGO_PYTAAC.aac?"},
    {name = "Cienradios - Top 40", url = "https://19793.live.streamtheworld.com/TOP40_PYTAAC.aac?"},
    {name = "Cienradios Radio X", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOX_56AAC.aac"},
    {name = "Cítrica Radio", url = "http://alpha.radioplayer.com.ar:9132/citrica885"},
    {name = "CLASS FM 91.9", url = "http://streaming01.dwservers.net:8400/;"},
    {name = "Classic Hits - Éxitos que no pasan de moda", url = "https://stream-151.zeno.fm/7st5b8derm0uv?"},
    {name = "Classique FM 106.5 FM", url = "https://radio.solumedia.com.ar:8562/;"},
    {name = "Classique: Una radio de clásicos", url = "https://01.solumedia.com.ar:8562/stream"},
    {name = "Classique: Una radio de clásicos", url = "https://01.solumedia.com.ar:8562/stream"},
    {name = "Club De Los Libros Libros Intocables - Radio Online", url = "http://stream.zeno.fm/fdnbtq898a0uv"},
    {name = "CNN AM 950 Arg. AAC Alta V3. Ciudad de Buenos Aires", url = "http://unlimited2-ar.dps.live/cnn-ar/aac/icecast.audio"},
    {name = "CNN Radio La Plata", url = "https://streaming01.shockmedia.com.ar/8206/stream"},
    {name = "CNN Radio Rafaela FM 92.1", url = "http://streaming.mv-comunicaciones.online:8050/cnnradiorafaela"},
    {name = "Compacto FM 88.1", url = "https://streaming2.locucionar.com/proxy/fmcompacto?mp=/stream"},
    {name = "Comunidad Fan FM 105.1 Rosario", url = "https://radio02.ferozo.com/proxy/ra02001326?mp=/stream"},
    {name = "Concepto FM 95.5", url = "https://radios.solumedia.com:6002/;"},
    {name = "Concepto FM 95.5 MHz", url = "http://radios.solumedia.com:6002/stream"},
    {name = "Conciencia FM 104.9", url = "https://streaming3.locucionar.com/proxy/concienciafm1049?mp=/stream"},
    {name = "Concierto FM 93.3", url = "https://server.laradio.online/proxy/alberto_prados?mp=/stream&1714852023731"},
    {name = "Concierto FM 94.7", url = "https://01.solumedia.com.ar:8112/stream"},
    {name = "Conexion Bariloche 93.9 FM", url = "https://streamconex.com:2000/stream/ConexioxBariloche"},
    {name = "Contacto 95.3", url = "https://streamlov.alsolnet.com/fmcontctoradio/live/playlist.m3u8"},
    {name = "continental", url = "https://alpha.radioplayer.com.ar/stream/cadenacontinental"},
    {name = "continental", url = "https://alpha.radioplayer.com.ar/stream/cadenacontinental"},
    {name = "continental", url = "https://alpha.radioplayer.com.ar/stream/cadenacontinental"},
    {name = "Continental 590 AM. Bs. As. Version 1", url = "https://frontend.radiohdvivo.com/continental/live"},
    {name = "Continental 590 AM. Ciudad de Bs. As. 110 Kbps Mp3", url = "https://alpha.radioplayer.com.ar/stream/continental"},
    {name = "Continental 590 AM. Ciudad de Bs. As. Version 2", url = "https://kappa.radioplayer.com.ar/stream/continental"},
    {name = "Cosmos Fm", url = "http://s28.myradiostream.com:28240/listen.m4a"},
    {name = "Cristal FM", url = "https://radio02.ferozo.com/proxy/ra02001330?mp=/stream"},
    {name = "Cristal FM 107.9", url = "https://radio02.ferozo.com/proxy/ra02001330?mp=/stream"},
    {name = "CRISTAL FM Noetinger", url = "https://radio02.ferozo.com/proxy/ra02001324?mp=/stream"},
    {name = "CSC Radio FM 106.5", url = "https://server.laradio.online:58844/live"},
    {name = "CVC La Voz Urbano ", url = "https://chat-assets.frontapp.com/v1/149be82f568687535638c72a66facc34.ogg"},
    {name = "CVC La Voz Urbano ", url = "https://chat-assets.frontapp.com/v1/149be82f568687535638c72a66facc34.ogg"},
    {name = "CVC La Voz Urbano ", url = "https://chat-assets.frontapp.com/v1/149be82f568687535638c72a66facc34.ogg"},
    {name = "CVC La Voz Urbano ", url = "https://chat-assets.frontapp.com/v1/149be82f568687535638c72a66facc34.ogg"},
    {name = "CVC La Voz Urbano ", url = "https://chat-assets.frontapp.com/v1/149be82f568687535638c72a66facc34.ogg"},
    {name = "D Sports Radio", url = "http://provisioning.streamtheworld.com/pls/DSPORTSRADIO.pls"},
    {name = "D Sports Radio 103.1 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DSPORTSRADIOAAC.aac"},
    {name = "d-Sports radio", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DSPORTSRADIOAAC.aac"},
    {name = "Dale FM 93.1", url = "https://streaming01.shockmedia.com.ar:10891/;?hash=1659583597942"},
    {name = "Dale FM 93.1", url = "https://streaming01.shockmedia.com.ar:10891/;"},
    {name = "De La Costa Radio 103.3", url = "http://01.solumedia.com.ar:8176/stream"},
    {name = "De la Mujer", url = "http://165.227.209.68:9990/;stream.mp3"},
    {name = "De la Nueva Bahía 106.1 FM", url = "https://radios.solumedia.com/6136/stream"},
    {name = "Del Bosque Radio 89.1 FM", url = "https://streaming01.shockmedia.com.ar:10598/stream/1/"},
    {name = "Del Sol FM 89.9", url = "https://streaming2.locucionar.com/proxy/delsolfm?mp=/stream"},
    {name = "Delta 90.3", url = "https://cdn.instream.audio//:9069//stream"},
    {name = "Delta 90.3", url = "https://cdn.instream.audio/:9069/stream"},
    {name = "Delta 90.3", url = "https://cdn.instream.audio/:9069/stream?in_device_id=wp-0bd8ae0e-61bb-4c85-8d42-818ab95f0da2"},
    {name = "Delta 90.3 Buenos Aires", url = "https://cdn.instream.audio/:9069/stream?in_device_id=wp-5270c502-0535-444e-975b-d49592d1d988"},
    {name = "Diamante Fm 95.7 MHz", url = "https://proxy01.servidorenlinea.net/streaming1/8014/;"},
    {name = "diferente FM 89.5 Mhz", url = "https://stream.zeno.fm/rfemgbu579avv"},
    {name = "Digital FM 102.1", url = "https://turadioenvivo.com/proxy/fmdigital/stream"},
    {name = "DIGITAL FM 104.9", url = "https://stream.zeno.fm/pewavgmncv8uv"},
    {name = "Digital FM 91.9", url = "https://stream.arcast.com.ar/radio/puntal.stream/playlist.m3u8"},
    {name = "DINAMICA FM 88.3", url = "https://stream.zeno.fm/2qfxz4z9hfhvv"},
    {name = "Dinamo FM 100.9", url = "http://01.solumedia.com.ar:8144/;"},
    {name = "DIVA´S + MÚSICA FM 89.9", url = "https://radios.solumedia.com/6490/stream"},
    {name = "DNA radio FM", url = "https://usa13.fastcast4u.com/proxy/dnaradiofm?mp=/;"},
    {name = "Doble A", url = "https://sonic.host-live.com/8268/stream"},
    {name = "Doctor Rock FM 92.9", url = "http://server.laradio.online:8683/stream/;"},
    {name = "Dorado FM 98.3", url = "https://streamingraddios.online/proxy/dora?mp=/stream"},
    {name = "Dr. Rock FM 92.9", url = "http://server.laradio.online:8683/;?"},
    {name = "DS Radio Horizonte 94.5 FM", url = "http://streaming.radiosenlinea.com.ar:9058/stream/;"},
    {name = "DSports Radio FM103.1", url = "https://24493.live.streamtheworld.com/DSPORTSRADIOAAC.aac"},
    {name = "Eclipse FM 101.5 MHz", url = "https://01.solumedia.com.ar:8746/stream"},
    {name = "Eco Medios 1220 AM", url = "https://stream.zeno.fm/uyd6h9w162quv"},
    {name = "Ecos de mis Cerros", url = "https://masservidor.net:7163/;"},
    {name = "EDI RADIO", url = "https://radio.forensedigital.gt:8090/stream"},
    {name = "edutecnica salta", url = "http://stream.zeno.fm/20ddyt65hfhvv"},
    {name = "El Destape", url = "https://ipanel.instream.audio/8004/stream"},
    {name = "El Destape Radio", url = "https://ipanel.instream.audio/8004/stream"},
    {name = "El Destape Radio", url = "https://ipanel.instream.audio/8004/stream"},
    {name = "el destape sin fin", url = "https://ipanel.instream.audio/8004/stream"},
    {name = "El Hacedor Radio Online", url = "https://stream.zeno.fm/f7vpqramxrhvv"},
    {name = "El Paraíso Radio", url = "https://streaming.radiosenlinea.com.ar/9022/stream"},
    {name = "El Rayo FM 101.9", url = "http://server2.veemesoft.com.ar:12506/;"},
    {name = "El Sol Sale Para Todos", url = "https://stream-149.zeno.fm/f2r6c55tfm8uv?zs=0bETJ17OROmPAcBC7sTCfA1z9tfAnkFPQOSUgpGNW9qLafhxs0GpRHxD0FFqGjax8Is9A-3D"},
    {name = "Elite FM 101.5", url = "https://radios.solumedia.com/6314/stream"},
    {name = "Emisora del Este 98.9 FM y 98.1 FM", url = "https://streaming.radiosenlinea.com.ar/8008/;"},
    {name = "Emisora Educativa El Hornero 107.7 FM", url = "https://secure.streaming01.dwservers.net/8650/;"},
    {name = "Enjoy Radio", url = "http://argentina.republicahosting.com:8261/stream"},
    {name = "ESPACIAL 105.1 FM", url = "https://chino.republicahosting.com:2282/live"},
    {name = "Estación 711 95.7 FM", url = "https://server.laradio.online:55330/live"},
    {name = "Estacion del Centro 95.7 FM", url = "http://stream01.insidetec.com:9040/fm957"},
    {name = "Estación Del Siglo Rio Grande FM 105.3", url = "http://streamall.alsolnet.com/estaciondelsigloaudio"},
    {name = "Estación Latidos", url = "http://streaming01.shockmedia.com.ar:8162/"},
    {name = "Estación Luz 103.5 FM", url = "https://sonic.host-live.com/8218/stream"},
    {name = "Estación Mix  ", url = "http://stream.laut.fm/estacionmix"},
    {name = "Estación Quince Cincuenta 1550 AM", url = "http://streaming2.locucionar.com:8312/stream"},
    {name = "Estación San Pedro 88.7 FM", url = "http://streaming.escuchanosonline.com/8780/stream"},
    {name = "Estación Urbana 104.7 FM", url = "https://streaming2.locucionar.com/proxy/estacionurbana?mp=/stream"},
    {name = "Estacion Victoria 90.7", url = "http://01.solumedia.com.ar:7786/;"},
    {name = "Estación Vinilo 89.1", url = "http://173.255.205.241:1127/;"},
    {name = "Estacion X 93.5 FM", url = "https://streaming6.locucionar.com:24060/stream"},
    {name = "Estacion XLW", url = "http://radio.solumedia.com.ar:7009/;"},
    {name = "Estilos FM 92.7", url = "http://server12.veemesoft.com.ar:19466/;"},
    {name = "Estirpe Nacional 1250 AM", url = "https://b2-f000.radiocut.com.ar/file/radiocut-2023/estirpe/171/577/1715771741.157-180.010.mp3"},
    {name = "Evolution FM 101.9", url = "https://radios.solumedia.com:6140/stream"},
    {name = "Exa FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "Exclusiva FM 97.7", url = "http://streaming2.locucionar.com:8269/stream"},
    {name = "Expo Radio FM 94.3", url = "https://radios.tecnosoul.com.ar:8001/exporadio"},
    {name = "F! 88.7 FM", url = "https://server4.hostradios.com/8308/stream"},
    {name = "F5 Radio 104.5 FM", url = "http://streaming.shockmedia.com.ar/8724/stream"},
    {name = "Fahrenheit FM 88.7 Rosario", url = "https://streaming.redboing.com/radio/8010/radio.aac"},
    {name = "Feeling 91.7", url = "http://turadioenvivo.com:8430/stream"},
    {name = "Feeling 91.9 FM", url = "http://turadioenvivo.com:8430/stream"},
    {name = "Feeling FM 91.7", url = "http://turadioenvivo.com:8430/stream"},
    {name = "Feeling FM 97.1 - Corrientes, Argentina", url = "http://turadioenvivo.com:8430/stream"},
    {name = "Fisherton", url = "http://23.111.184.195:8140/radio.mp3.m3u"},
    {name = "Fisherton Classic (Rosario)", url = "https://media425.digitar.net:8081/fishertonclassic.mp3"},
    {name = "Fisherton CNN Rosario", url = "https://media425.digitar.net:8141/radio.mp3"},
    {name = "FM 102.3", url = "https://radios.solumedia.com:6276/stream"},
    {name = "FM 102.5", url = "https://streaming1.locucionar.com/proxy/cayetano1025?mp=/stream"},
    {name = "FM 103.1 DirecTV Sports Radio - Argentina", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DSPORTSRADIOAAC.aac"},
    {name = "FM 105.7", url = "https://streaming3.locucionar.com/proxy/fm1057?mp=/stream"},
    {name = "Fm 106.1 Estacion 2", url = "https://emisora.zonasinergia.com/8068/stream"},
    {name = "FM 106.7 Rosario", url = "https://media425.digitar.net:8011/cadena3.mp3"},
    {name = "FM 89.3 Santa María de las Misiones", url = "https://vps-c0159cbc.vps.ovh.ca/9682/;"},
    {name = "FM 90 Saladillo FM 90.7", url = "https://chino.republicahosting.com:2316/live"},
    {name = "Fm 90.7 General Paz - Grupo Tiempo", url = "http://stream.zeno.fm/915tpe38dchvv"},
    {name = "FM 90.9 Rosario", url = "https://streaming2.locucionar.com/proxy/radiobt?mp=/stream"},
    {name = "Fm 94.1 Onda Horizonte", url = "http://s1.radiosnethosting.com:9816/;"},
    {name = "FM 94.3 Radio Municipal de Toay", url = "http://51.79.51.128:9678/;"},
    {name = "FM 94.5 Bariloche", url = "https://server1.streamingradio.online/proxy/002/stream:7287"},
    {name = "FM 95.5 RADIO REPUBLICA", url = "https://edge-st1-audio.masterhost.com.ar/listen/radio_republica_955/radio.mp3"},
    {name = "Fm 95.5 Republica ", url = "https://edge-st1-audio.masterhost.com.ar/listen/radio_republica_955/radio.mp3"},
    {name = "FM 95.7 Un Concepto de Radio ", url = "https://vps-6de10815.vps.ovh.ca/8136/stream"},
    {name = "FM 96.5 - Residencias", url = "https://01.solumedia.com.ar:8592/stream"},
    {name = "FM 97.9 Vida", url = "https://streaming450tb.locucionar.com/proxy/fmvida979?mp=/stream"},
    {name = "FM 97.9 Vida", url = "https://streaming450tb.locucionar.com/proxy/fmvida979?mp=/stream"},
    {name = "FM 97.UNE - Provincia de Buenos Aires", url = "https://streaming.provinciaradio.com.ar:3352/fm"},
    {name = "FM 97.UNE - Provincia de Buenos Aires", url = "https://streaming.provinciaradio.com.ar:3352/fm"},
    {name = "FM Activa 91.5", url = "https://streaming5.locucionar.com/proxy/fmactivasegui?mp=/stream"},
    {name = "FM Actualidad 93.7", url = "https://server4.hostradios.com/8348/stream/;"},
    {name = "FM Ahijuna 94.7", url = "http://stream.ahijuna.fm/aire.mp3"},
    {name = "FM ALAS - Correa (Sta Fe)", url = "http://stream.zeno.fm/7bs1rw5zw8quv"},
    {name = "FM ALAS - Correa (Sta Fe)", url = "http://stream.zeno.fm/7bs1rw5zw8quv"},
    {name = "FM Alegría 101.7 General Pico", url = "https://streaming.radiosenlinea.com.ar/8856/stream/1/"},
    {name = "FM ALEJANDRO 104.1", url = "https://vps-c0159cbc.vps.ovh.ca/8026/;"},
    {name = "FM ALTITUD 94.7", url = "https://server.radiostreaming.com.ar/8118/stream"},
    {name = "fm amanecer 101.3", url = "http://centova.radiosnethosting.com:9870/stream"},
    {name = "FM Atlantic 105.9", url = "http://server1.veemesoft.com.ar:26511/;"},
    {name = "FM atlántica 98.5", url = "https://streaming1.locucionar.com/proxy/fmatlantica?"},
    {name = "FM Bahía Engaño 104.5", url = "https://sc.dattalive.com/8010/stream"},
    {name = "FM Bariloche", url = "https://streaming1.locucionar.com/proxy/colgados?mp=/stream"},
    {name = "FM Bragado FM 95.5 ", url = "http://sonic.dattalive.com:8310/stream"},
    {name = "FM Calchaqui", url = "https://server.ohradio.com.ar/9856/stream"},
    {name = "FM Cariló 104.3", url = "http://fmcarilo.ddns.net:8000/;"},
    {name = "FM Chalten 106.3", url = "https://streaming1.locucionar.com/proxy/fmchalten1063?mp=/stream"},
    {name = "Fm Ciudad", url = "https://streaming6.locucionar.com:24028/stream"},
    {name = "Fm Ciudad", url = "https://streaming6.locucionar.com:24028/stream"},
    {name = "Fm ciudad", url = "https://streaming6.locucionar.com:24028/stream"},
    {name = "Fm ciudad", url = "https://streaming6.locucionar.com:24028/stream"},
    {name = "FM CIUDAD 94.7", url = "https://streaming6.locucionar.com:24028/stream"},
    {name = "FM Color 99.3 (General Roca)", url = "https://streamingraddios.online/proxy/cozzi?mp=/stream"},
    {name = "FM Córdoba", url = "https://liveradio.mediainbox.net/fmcordoba.mp3"},
    {name = "FM Cosecha", url = "http://www.genexservicios.com:8068/;"},
    {name = "FM CRISTAL 97.7", url = "https://streaming.radiosenlinea.com.ar/8520/stream"},
    {name = "Fm Cumbiambera", url = "https://streaming1.locucionar.com/proxy/fmcumbiambera?mp=/stream"},
    {name = "Fm Dale 96.1", url = "http://01.solumedia.com.ar:8238/"},
    {name = "FM de la Costa 90.5", url = "https://streaming1.locucionar.com/proxy/delacosta905?mp=/stream"},
    {name = "FM De la Isla 91.1 Mhz", url = "https://streaming1.locucionar.com/proxy/fmisla911?mp=/stream"},
    {name = "FM DEL ESTE 99.3", url = "https://radio01.ferozo.com/proxy/ra01000956?mp=/stream"},
    {name = "FM DIGITAL 93.7", url = "https://stream.radioinfo.ar/p/5336/stream/?type=http&nocache=1"},
    {name = "FM ECLIPSE 106.3", url = "http://uk6freenew.listen2myradio.com:31284/;"},
    {name = "FM Eclipse 90.5", url = "https://streaming2.locucionar.com/proxy/fmeclipse905?mp=/stream"},
    {name = "Fm Eclipse96.3 MHz", url = "https://sonic.dattalive.com/8422/stream"},
    {name = "FM Ecos 104.3", url = "http://stm34.veemesoft.com.ar:28350/"},
    {name = "FM EL CHUBUT", url = "https://radios.streamingdha.com.ar:9382/;"},
    {name = "FM en Transito", url = "https://cdn.instream.audio/:9110/stream"},
    {name = "FM ESTACION PLUS 99.3", url = "https://proxy01.servidorenlinea.net/streaming1/8078/;"},
    {name = "FM Estación Popular 101.1", url = "https://streaming.escuchanosonline.com:7298/;"},
    {name = "FM Estudio Dos 105.9", url = "https://streamall.alsolnet.com/fmestudiohd"},
    {name = "FM EXITO 99.1", url = "https://01.solumedia.com.ar:8178/;"},
    {name = "FM Federal 99.5", url = "https://sonic.host-live.com/8176/stream"},
    {name = "FM Federal 99.5", url = "http://51.161.119.117:8176/stream"},
    {name = "FM Fenix", url = "http://www.fmfenix.com.ar:8000/fmfenix.ogg"},
    {name = "FM Fénix Martinez", url = "http://stream.zeno.fm/uvcx5phxhrhvv"},
    {name = "FM Futuro  - 93.1 Escobar", url = "http://streaming2.locucionar.com:8682/stream"},
    {name = "FM Galaxia 88.7", url = "https://vps-2333016-x.dattaweb.com/listen/fm_galaxia_88.7_cadena_3_san_francisco/radio.mp3"},
    {name = "FM Galeno 100.7 Mhz", url = "https://server.radiostreaming.com.ar/8486/stream?1722566655035"},
    {name = "FM Impacto - Villa Gesell", url = "https://masstreaming.online/8392/stream"},
    {name = "fm impacto 106.7", url = "https://radios.streamingdha.com.ar:9252/;"},
    {name = "FM IMPACTO 95.5 La Radio de la noticias Villa Gesell", url = "https://masstreaming.online/8392/stream"},
    {name = "FM Imperio", url = "http://argentina.republicahosting.com:8417/stream"},
    {name = "FM Inti 99.5Mhz", url = "https://server.ohradio.com.ar/8274/stream"},
    {name = "FM LA 20", url = "http://01.solumedia.com.ar:8386/;stream.nsv"},
    {name = "FM La Boca 90.1 Buenos Aires", url = "https://s24.myradiostream.com/:14984/listen.mp3?nocache=1674464727"},
    {name = "FM La Patriada", url = "https://server.laradio.online/proxy/fm_la_patriada?mp=/stream"},
    {name = "FM La Ruta", url = "http://turadioenvivo.com:11020/stream"},
    {name = "FM La Tribu 88.5 Buenos Aires", url = "https://radio01.ferozo.com/proxy/ra01000659?mp=/stream"},
    {name = "FM La Uni 91.7", url = "http://cdn.instream.audio:9275/stream.m3u"},
    {name = "FM Laser", url = "https://streamconex.com:8076/stream/"},
    {name = "FM Laser", url = "https://streamconex.com:8076/stream/"},
    {name = "FM Laser 98.5 - General Pico", url = "https://streamconex.com:8076/stream/"},
    {name = "FM Latidos 95.1 - General Pico", url = "https://streamconex.com:8150/stream"},
    {name = "Fm Latina 92.5 Salta", url = "http://streaming.radiosenlinea.com.ar:9640/;"},
    {name = "FM Latina 99.7", url = "https://emisora.zonasinergia.com:7101/stream"},
    {name = "FM Masters Ushuaia", url = "https://streamlky.alsolnet.com/fmmastersenlace"},
    {name = "FM Millenium 106.7", url = "https://player.questreaming.com/?pl=vlc&c=fmmilenium"},
    {name = "FM Plus 93.1 Rosario", url = "http://fmplus.radio.rosario3.com:8006/"},
    {name = "FM Poder", url = "http://server.ohradio.com.ar:8206/stream',"},
    {name = "FM Punta 88.1 ", url = "https://server7.hostradios.com/8140/stream"},
    {name = "FM Reconquista 89.5", url = "http://aler.org:8000/radiofmreconquista.ogg"},
    {name = "FM Rock Zarate | FM 103.3", url = "https://sonic.dattalive.com:10821/stream"},
    {name = "FM Rock Zarate | FM 103.3", url = "https://sonic.dattalive.com:10821/stream"},
    {name = "FM Sensaciones 95.1", url = "https://chino.republicahosting.com:2318/live"},
    {name = "Fm Sierras 107.9 Mhz ", url = "http://giss.tv:8000/fmsierras.mp3"},
    {name = "Fm Sierras 107.9Mhz", url = "http://giss.tv:8000/fmsierras.mp3"},
    {name = "FM Sol 88.3", url = "http://sonicpanel.hostradios.com:10060/Stream/;"},
    {name = "FM Sol 88.3", url = "https://sonicpanel.hostradios.com/10060/stream"},
    {name = "FM Soldados 87.5", url = "https://radio02.ferozo.com/proxy/ra01000409?mp=/stream"},
    {name = "FM Sur Quilmes", url = "http://streamall.alsolnet.com:443/fmsurquilmeshd"},
    {name = "Fm Sur Quilmes", url = "http://streamall.alsolnet.com:443/fmsurquilmeshd"},
    {name = "FM TIEMPO 103.5", url = "https://streaming3.locucionar.com/proxy/fmtiempo1035?mp=/stream"},
    {name = "FM TIEMPO 92.5", url = "https://streaming3.locucionar.com/proxy/fmtiempo925?mp=/stream"},
    {name = "FM Tiempo 95.5 MHz", url = "https://streaming2.locucionar.com/proxy/fmtiempo?mp=/stream"},
    {name = "Fm Tropical", url = "http://server.laradio.online:25060/stream"},
    {name = "Fm Trópico 977 Jujuy", url = "https://stream.arcast.com.ar/radio/tropico.stream/playlist.m3u8"},
    {name = "FM TRUJUI 90.1 Mhz", url = "https://masstreaming.online:8376/"},
    {name = "FM Universidad - 105.7 UTN Paraná", url = "https://sc.dattalive.com/8206/stream"},
    {name = "FM Universidad 107.5 UNLP", url = "http://163.10.186.71:8001/broadwavehigh.mp3"},
    {name = "FM Universidad 98.7 - Universidad Nacional de Misiones", url = "https://fm.unam.edu.ar/fm"},
    {name = "FM Universo", url = "https://servidor1.hostradios.com:8070/stream"},
    {name = "FM UTN Mendoza", url = "http://streaming.fmutn.com.ar:8000/FMUTN#;.mp3"},
    {name = "FM105.1", url = "http://173.255.205.241:8180/;"},
    {name = "FM105.7", url = "https://streaming3.locucionar.com/proxy/fm1057?mp=/stream"},
    {name = "FMi 99.1", url = "https://ssl.radiosnethosting.com/index.php?port=9808"},
    {name = "FMI TUCUMAN", url = "https://ssl.radiosnethosting.com/index.php?port=9808"},
    {name = "FMQ", url = "https://streamlky.alsolnet.com/radiofmq"},
    {name = "FMQ", url = "http://streamlky.alsolnet.com:443/radiofmq"},
    {name = "FMQ 93.5", url = "https://streamlky.alsolnet.com/radiofmq"},
    {name = "Frecuencia Arena 98.3", url = "https://stream.serviciowebdigital.com/8854/stream"},
    {name = "Frecuencia City", url = "http://stream.zeno.fm/0bcakrbrbqjuv"},
    {name = "Frecuencia City", url = "http://stream.zeno.fm/0bcakrbrbqjuv"},
    {name = "Frecuencia Digital 99.1 FM", url = "https://radios.streamingdha.com.ar/8022/;"},
    {name = "Frecuencia Patagonia FM 99.3", url = "http://server.laradio.online:9188/live"},
    {name = "Frecuencia Urbana 88.7 General Roca", url = "https://sc.dattalive.com:10929/stream"},
    {name = "Fresh Radio FM 102.9FM", url = "https://streaming.escuchanosonline.com:7011/stream"},
    {name = "Futura FM 90.5", url = "https://streamer.fmfutura.com.ar/vivo.mp3"},
    {name = "FutuRÖck", url = "https://mdstrm.com/audio/5d9d019112cbbb45d6a50960/live.m3u8"},
    {name = "FutuRock", url = "https://mdstrm.com/audio/5d9d019112cbbb45d6a50960/live.m3u8"},
    {name = "Gamba FM (Córdoba)", url = "https://servidor1.hostradios.com:8132/stream"},
    {name = "GLAM FM", url = "https://streaming2.locucionar.com/proxy/glam963?mp=/stream"},
    {name = "Glam Fm  96.3", url = "https://streaming2.locucionar.com/proxy/glam963?mp=/stream"},
    {name = "Gravity Radio", url = "https://stream.xweb.ar/8024/stream"},
    {name = "Guajira Radio", url = "http://01.solumedia.com.ar:8252/stream"},
    {name = "Hechos De Tango Radio Online", url = "https://argentina.republicahosting.com:1376/live"},
    {name = "HIT RADIO FFH. 128K AAC. Argentina", url = "http://mp3.ffh.de/radioffh/hqlivestream.aac"},
    {name = "Hollywood 101.3", url = "https://radio02.ferozo.com/proxy/ra02001328?mp=/stream"},
    {name = "Hollywood FM 101.3 Rosario", url = "https://radio02.ferozo.com/proxy/ra02001328?mp=/stream"},
    {name = "Horizonte 103 Pinamar", url = "http://horizonte103.ddns.net:8000/;"},
    {name = "Horizonte 103.1 - Santa Rosa", url = "http://sslstream.online:8204/live"},
    {name = "IMPACTO FM REALICO - LA PAMPA", url = "http://streaming01.shockmedia.com.ar:9722/reproductores/?idr=NTQz"},
    {name = "in.radio", url = "https://stream.zeno.fm/n1f4vputgqbuv"},
    {name = "InfoPico Radio 99.9", url = "https://streaming3.locucionar.com/proxy/infopico999?mp=/stream"},
    {name = "InfoPico Radio 99.9 - General Pico", url = "https://streaming3.locucionar.com/proxy/infopico999?mp=%2Fstream"},
    {name = "iTUNES TOP 40 FFH. 128K AAC. Argentina", url = "https://mp3.ffh.de/ffhchannels/hqtop40.aac"},
    {name = "jaja cba", url = "https://streaming5.locucionar.com/proxy/radiojaja?mp=/stream"},
    {name = "Javeriana Estereo", url = "https://radio06.cehis.net:9001/stream"},
    {name = "Jazz cafe", url = "https://radio.netyco.com:18056/"},
    {name = "K2 RADIO 96.3 FM", url = "https://cdn.instream.audio/:9568/stream"},
    {name = "Kiss FM 95.1 Rosario", url = "https://streaming.redboing.com/radio/8060/radio.mp3"},
    {name = "KLA Radio 97.1", url = "https://streamconex.com:8104/stream?1722096115054"},
    {name = "La 100", url = "https://24233.live.streamtheworld.com/FM999_56AAC.aac"},
    {name = "La 100", url = "https://24233.live.streamtheworld.com/FM999_56AAC.aac"},
    {name = "La 100 - 99.9 FM - Grupo Clarín - Buenos Aires, Argentina", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/FM999_56.mp3"},
    {name = "La 100 Clásicos - Disco Retro Clásicos", url = "https://27323.live.streamtheworld.com/FCLASICOS_56AAC.aac?"},
    {name = "La 2x4", url = "https://storage.googleapis.com/m-infra.appspot.com/public/webchat/sent.mp3"},
    {name = "La 2x4", url = "https://media.radios.ar:9270/"},
    {name = "La 95 - FM 95.3", url = "https://sonic.cloudstreaming.eu:10989/;"},
    {name = "La 97", url = "https://streaming01.shockmedia.com.ar:10586/stream"},
    {name = "La 97", url = "https://streaming01.shockmedia.com.ar:10586/stream"},
    {name = "La 97 Radio Fueguina Rio Grande y Ushuaia", url = "https://streamall.alsolnet.com/radiofueguina"},
    {name = "La Cacharpaya", url = "http://streaming01.shockmedia.com.ar:9360/stream"},
    {name = "La City", url = "http://01.solumedia.com.ar:7485/;"},
    {name = "La Colectiva", url = "https://radios.solumedia.com/6198/stream"},
    {name = "La Colectiva", url = "https://radios.solumedia.com/6198/stream"},
    {name = "La Estación FM 107.9", url = "http://01.solumedia.com.ar:2199/tunein/chicossrl.pls"},
    {name = "La Estación Fm 107.9 Salta ", url = "http://radio.solumedia.com.ar:8462/stream"},
    {name = "La familiera 97.7 Gemeral Roca", url = "https://stream.zeno.fm/wusafz982hhvv"},
    {name = "La Formidable FM", url = "http://s7.voscast.com:8278/;"},
    {name = "La Hit Córdoba", url = "http://stm23.veemesoft.com.ar:24308/;"},
    {name = "La Korneta FM 92,5", url = "https://base.redenfoques.com.ar:8060/lakorneta"},
    {name = "La Popu", url = "https://liveradio.mediainbox.net/popular.mp3"},
    {name = "La Popu 92.3", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/lapopu.mp3?dist=c3-web"},
    {name = "La Primera AM 550 Neuquen", url = "https://sonic.dattalive.com/8296/stream"},
    {name = "LA RADIO 104.7", url = "https://server.laradio.online:2199/tunein/laradio1047.pls"},
    {name = "La Radio 104.7 FM. Resistencia Chaco. Julio Wajcman", url = "https://server.laradio.online/proxy/laradio1047"},
    {name = "La Radio 93.5", url = "https://01.solumedia.com.ar:8494/stream"},
    {name = "La radio de Chivilcoy", url = "https://streaming1.locucionar.com/proxy/laradiodechivilcoy?mp=/stream"},
    {name = "La Radio de la Gente LU12 AM 680 Rio Gallegos ", url = "https://sa.mp3.icecast.magma.edge-access.net/LOA_LaOpinionAustral"},
    {name = "La Radio De Los Lentos", url = "https://01.solumedia.com.ar:7828/stream"},
    {name = "La Ranchada FM103.9", url = "https://server.laradio.online/proxy/javier_diaz01?mp=/stream"},
    {name = "La Red", url = "https://21933.live.streamtheworld.com/LA_RED_AM910AAC.aac"},
    {name = "La Red Pampeana", url = "http://server.laradio.online:9033/live"},
    {name = "La Rocka RcK FM 107.3", url = "http://cdn.instream.audio:8137/stream"},
    {name = "La Super Radio 96.3 General Roca", url = "https://sc.dattalive.com/8070/stream"},
    {name = "La voz de VCI", url = "http://stream.zeno.fm/ke2bvwydmzzuv"},
    {name = "LA990", url = "https://21933.live.streamtheworld.com/AM990.mp3"},
    {name = "Lalala Radio La música de Luis Alberto Spinetta", url = "http://server.laradio.online:25311/live"},
    {name = "LaRadioDeLosLentos - Just Ballads", url = "https://01.solumedia.com.ar:7828/stream"},
    {name = "Larz", url = "https://streamlky.alsolnet.com/larz"},
    {name = "Laser Max 103.3", url = "https://streaming5.locucionar.com/proxy/lasermax1033?mp=/stream"},
    {name = "Latina 101.1 Argentina", url = "http://streaming.latina101.com.ar:8080/RadioLatina"},
    {name = "Level Rock FM", url = "https://streaming2.locucionar.com/proxy/levelrock?mp=/stream"},
    {name = "Lico Radio", url = "http://radios.solumedia.com:6226/stream"},
    {name = "Lola", url = "https://cdn.instream.audio/:9081/stream"},
    {name = "Los 40 - Argentina", url = "https://edge03.radiohdvivo.com/stream/los40"},
    {name = "Los 40 Argentina", url = "https://alpha.radioplayer.com.ar/stream/los40"},
    {name = "Los 40 Argentina", url = "https://alpha.radioplayer.com.ar/stream/los40"},
    {name = "LRA1 Radio Nacional Argentina", url = "https://sa.mp3.icecast.magma.edge-access.net/sc_rad1"},
    {name = "LRI890 Radio UNDAV ", url = "http://radiostream.undav.edu.ar:8002/radioundav"},
    {name = "LT 15 Concordia", url = "https://lt15concordia.radioca.st/stream"},
    {name = "LT14 Nacional Gral. Urquiza AM 1260 - Paraná", url = "http://ea.mp3.icecast.magma.edge-access.net:7200/sc_rad44"},
    {name = "LT20 Radio Junin AM 1470", url = "http://01.solumedia.com.ar:8260/;"},
    {name = "LT7 Radio Provincia de Corrientes", url = "http://turadioenvivo.com:11045/stream"},
    {name = "LT8 AM830", url = "http://stream.lt8.com.ar:8080/lt8radio.mp3"},
    {name = "LT9 Radio Brigadier López La Líder", url = "https://streaming1.locucionar.com/proxy/lt9?mp=/stream?rand=718352759"},
    {name = "LU100 Radio Capital AM 1040 - Santa Rosa", url = "http://144.91.98.151:8289/;"},
    {name = "LU11 Radioemisora del Oeste Trenque Lauquen", url = "https://radiosar.com:7045/stream"},
    {name = "LU12 La Radio De La Gente, Rio Gallegos", url = "https://sa.mp3.icecast.magma.edge-access.net/LOA_LaOpinionAustral"},
    {name = "LU14 Radio Provincia de Santa Cruz AM 830 khz", url = "https://transmision-lu14.santacruz.gob.ar/lu14.mp3"},
    {name = "LU15 Radio Viedma AM 800 Rio Negro", url = "https://alpha.radioplayer.com.ar:9206/LU15AM800"},
    {name = "LU18 AM 640 Radio del Valle (Rio Negro)", url = "https://streamingraddios.online/proxy/valle?mp=/stream"},
    {name = "LU19 Radio Cipolletti AM690", url = "https://sonic.dattalive.com/8064/stream"},
    {name = "LU20 Radio Chubut", url = "https://streaming1.locucionar.com/proxy/radiochubut?mp=/stream"},
    {name = "LU20 Radio Chubut Trelew AM 580", url = "https://streaming1.locucionar.com/proxy/radiochubut?mp=/stream"},
    {name = "LU22 Radio Tandil AM1140", url = "https://streaming01.shockmedia.com.ar/8170/live"},
    {name = "LU24 Radio Tres Arroyos", url = "https://streaming01.shockmedia.com.ar:10889/stream?icy=http"},
    {name = "LU33 Emisora Pampeana AM 890 - Santa Rosa", url = "http://01.solumedia.com.ar:8324/stream"},
    {name = "LU6 - Radio Atlantica  - Mar del Plata", url = "http://173.255.205.241:9090/;stream.nsv"},
    {name = "LU6 Atlántica Latina FM 93.3 Mar Del Plata", url = "http://173.255.205.241:7070/;"},
    {name = "LU6 Emisora Atlántica AM 760 Mar Del Plata", url = "http://173.255.205.241:7070/;"},
    {name = "LU6 Radio Atlántica", url = "http://173.255.205.241:9090/"},
    {name = "LU6 Radio Atlántica Mar Del Plata AM 760 Khz", url = "http://173.255.205.241:9090/"},
    {name = "LU9 Emisora Mar Del Plata AM 670", url = "https://servidor1.hostradios.com:8110/stream?1668514689750"},
    {name = "Lu9 Radio Mar del Plata", url = "https://servidor1.hostradios.com:8110/stream"},
    {name = "LV11", url = "https://streaming.evolucionstreaming.com/8040/stream?hash=16935913338https://streaming.evolucionstreaming.com/8040/stream?hash=1693591333817"},
    {name = "M90 89.9 FM", url = "http://23.111.184.195:8030/m90.mp3"},
    {name = "M90 Vintage FM 94.1 Rosario", url = "http://23.111.184.195:8020/mileniumrosario.mp3"},
    {name = "Magic Box FM 107.3", url = "https://stream01.server-inside.com.ar:9652/magicbox"},
    {name = "Magic Kids FM", url = "http://argentina.republicahosting.com:8197/stream"},
    {name = "Magica. FM 99.9. Barranqueras. Chaco. Version 1", url = "https://streaming5.locucionar.com/proxy/radiomagica999?mp=/stream"},
    {name = "Malva FM - General Pico", url = "https://cdn.instream.audio/:9310/stream"},
    {name = "Mañana Intensa", url = "https://server.streamcasthd.com/8272/stream"},
    {name = "MARAGATA FM 97.5", url = "https://streaming2.locucionar.com/proxy/maragata975?mp=/stream"},
    {name = "Marea FM", url = "https://sonic.mediatelekom.net/9016/stream"},
    {name = "María Argentina", url = "http://dreamsiteradiocp.com:8004/"},
    {name = "Mas que Musica", url = "https://radios.solumedia.com:6276/stream"},
    {name = "Master FM 105.5", url = "https://ssl.radiosnethosting.com/index.php?port=9168/;stream.mp3"},
    {name = "Mediterraneo 98.3 Mhz", url = "https://streaming01.radiosenlinea.com.ar:10996/stream"},
    {name = "Meridiano 107.1 FM", url = "http://23.111.184.195:8050/fmmeridiano.mp3"},
    {name = "Metro 95.1", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/METRO.mp3"},
    {name = "Metro FM 95.1. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/METROAAC.aac"},
    {name = "Milenium 106.7 FM", url = "https://sonicpanel.hostradios.com/8002/stream"},
    {name = "Milenium 94.1 FM", url = "http://23.111.184.195:8020/mileniumrosario.mp3"},
    {name = "Mitre AM 790. AAC Alta. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/AM790_56AAC.aac"},
    {name = "Mitre Rosario", url = "https://media425.digitar.net:8091/mitre.mp3"},
    {name = "Modo Radio 106.9", url = "https://streaming01.shockmedia.com.ar:10609/stream"},
    {name = "Nacional Clásica fm 96.7", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad37"},
    {name = "Nacional Perito Moreno - LRA56 AM860", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad34"},
    {name = "Nacional Rock FM 93.7", url = "https://sa.mp3.icecast.magma.edge-access.net/sc_rad39"},
    {name = "Nacional San Juan - LRA23 AM910", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad23"},
    {name = "Ndr Radio", url = "https://streamconex.com:8096/;?listening-from-radio-garden=1640125124"},
    {name = "Neo Net Music", url = "https://sonic.dattalive.com/8670/stream"},
    {name = "Net Classic FM 90.3 San Lorenzo", url = "https://alpha.radioplayer.com.ar:9232/netclassic903"},
    {name = "Net80 Radio", url = "https://streaming.escuchanosonline.com/8274/stream"},
    {name = "NQP Radio", url = "http://cdn.instream.audio:8111/stream"},
    {name = "Nuestra FM La Adela FM 107.5", url = "http://server1.veemesoft.com.ar:10147/;"},
    {name = "Nuevos Aires FM 99.7", url = "http://streamingv2.shoutcast.com/NuevosAiresFM997_192.mp3"},
    {name = "OK FM Arroyito", url = "http://audio.questreaming.com:27156/"},
    {name = "Patagonia Dinámica 105.5 - General Pico", url = "https://chino.republicahosting.com:2311/live"},
    {name = "Planet Music Bahía Blanca", url = "https://strcdn.klm99.com:10987/planetbahia"},
    {name = "Planet Music Mar del PLata 101.1", url = "https://strcdn.klm99.com:10991/planetmdp"},
    {name = "Planet Music Pinamar 99.5", url = "https://strcdn.klm99.com:10984/planetpinamar"},
    {name = "Planet Music Villa Gesell 91.9", url = "https://strcdn.klm99.com:10986/planetvillagesell"},
    {name = "Plus 93.1 FM", url = "http://fmplus.radio.rosario3.com:8006/fmplus"},
    {name = "Pobre Johnny", url = "https://stream4.suenas.net/pobrejohnny"},
    {name = "Pontiac Rock", url = "https://radios.solumedia.com/6268/stream"},
    {name = "Pop 101.5 FM. Ciudad de Buenos Aires", url = "https://ny2.stweb.tv/popradio/live/chunks.m3u8"},
    {name = "Pop Radio 101.5", url = "https://popradio.stweb.tv/popradio/live/chunks.m3u8"},
    {name = "Pop Radio 101.5", url = "https://popradio.stweb.tv/popradio/live/playlist.m3u8"},
    {name = "Pop Radui FM 101.5. Ciudad de Bs. As. Version 2", url = "https://popradio.stweb.tv/popradio/live/playlist.m3u8"},
    {name = "Power Paraná", url = "https://player.xcast.com.br/proxy/7232/"},
    {name = "Punto y Coma", url = "http://01.solumedia.com.ar:7810/;"},
    {name = "Q103 Radio", url = "http://01.solumedia.com.ar:7139/;"},
    {name = "Qacttus Radio", url = "http://argentina.republicahosting.com:8244/stream"},
    {name = "Quality X - 89.7 FM", url = "https://stream.qualityradio.com.ar/qualityx"},
    {name = "Radiactiva 100.7", url = "http://sh4.radioonlinehd.com:8533/stream"},
    {name = "Radio 10", url = "https://radio10.stweb.tv/radio10/live/chunks.m3u8"},
    {name = "Radio 10", url = "https://radio10.stweb.tv/radio10/live/playlist.m3u8"},
    {name = "Radio 10", url = "https://radio10.stweb.tv/radio10/live/playlist.m3u8"},
    {name = "Radio 2", url = "https://cdn.instream.audio/:9056/stream?_=1680ada412b"},
    {name = "Radio 2 1230 AM", url = "http://radio2.radio.rosario3.com:8000/prueba2"},
    {name = "Radio 21 FM 90.1 - Caleta Olivia", url = "https://cdn.instream.audio/:9135/stream"},
    {name = "Radio 5 100.5 - General Pico", url = "https://streaming2.locucionar.com/proxy/radio5fm/stream"},
    {name = "Radio Activa FM 96.9 - Ing. Mashwitz", url = "http://streaming01.shockmedia.com.ar:9332/stream"},
    {name = "RADIO AMA 92.9 FM", url = "https://panel.nexolife.ar/stream/laradio923"},
    {name = "Radio Amanecer", url = "https://streaming2.locucionar.com/proxy/radioamanecer?mp=/stream"},
    {name = "Radio Argentina - AM 570", url = "http://server.laradio.online:25224/live.mp3"},
    {name = "RADIO ARIAS FM 91.1 JUJUY", url = "https://cdn.instream.audio/:9095/stream"},
    {name = "Radio Asamblea - FM 94.1 mhz", url = "http://server.laradio.online:25057/live?type=.mp3"},
    {name = "Radio Autonoma Piuke", url = "http://base.redenfoques.com.ar:8000/piuke"},
    {name = "Radio Azul LU10 AM 1320 khz Azul Buenos Aires", url = "https://vps-c0159cbc.vps.ovh.ca/3008/;"},
    {name = "Radio Azul Tolhuin FM 100.9", url = "http://genexservicios.com:8310/;?1666493861674"},
    {name = "RADIO BEAT 97.5 FM", url = "http://audio.questreaming.com:27902/;"},
    {name = "Radio Belgrano - AM 650", url = "http://server.laradio.online:25223/live.mp3"},
    {name = "Radio Belgrano AM 650 khz Buenos Aires", url = "https://server.laradio.online:15223/live.mp3"},
    {name = "Radio Berlin", url = "https://s8.stweb.tv/berlin/live/playlist.m3u8"},
    {name = "Radio Berlín 107.9 FM", url = "https://s8.stweb.tv/berlin/live/chunks.m3u8"},
    {name = "Radio Bicentenario", url = "http://01.solumedia.com.ar:7792/;stream/1"},
    {name = "Radio Bicentenario Tucumán", url = "http://01.solumedia.com.ar:7792/;stream/1"},
    {name = "Radio Boing 97.3 Rosario", url = "https://streaming.redboing.com/radio/8000/radio.aac"},
    {name = "Radio Brisas 98.5", url = "https://radio.ecolan.com:8443/stream.mp3"},
    {name = "Radio Britannia", url = "http://01.solumedia.com.ar:8472/stream/;"},
    {name = "Radio Buenos Aires LS6 AM 1350 khz", url = "https://nl.digitalrm.pt:8052/stream"},
    {name = "Radio Cadena 3", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO3_SC"},
    {name = "Radio Cadena 94.9 FM", url = "http://server1.veemesoft.com.ar:9416/;"},
    {name = "Radio Cadena Norte FM", url = "http://centova.questreaming.com:26834/;"},
    {name = "Radio Cadena Sol 106.5 FM", url = "http://www.genexservicios.com:8294/;"},
    {name = "RADIO CADENA VIDA 95.3 FM", url = "https://host.serviceinfinito.com.ar:7006/;"},
    {name = "Radio Cantilo", url = "http://radio.solumedia.com.ar:7231/stream"},
    {name = "Radio Caput", url = "http://69.64.46.123:8132/stream?type=.mp3"},
    {name = "Radio Centinela", url = "https://01.solumedia.com.ar:8050/stream"},
    {name = "RADIO CENTRO", url = "https://sonicpanel.hostradios.com/8710/stream"},
    {name = "Radio Centro 99.3 - General Pico", url = "https://https.nvradios.com/radio/9340/radio.mp3"},
    {name = "Radio chascomús La voz Regional AM 1520 khz", url = "https://streaming1.locucionar.com/proxy/radiochascomus?mp=/stream"},
    {name = "Radio Cielo - FM 106.9 mhz (Zarate)", url = "http://streamall.alsolnet.com:443/radiocielo"},
    {name = "Radio City - 107.1", url = "http://190.52.32.13:1935/radiocity/live_1/chunklist_w1583615162.m3u8"},
    {name = "Radio city 107.1 - Jujuy", url = "http://190.52.32.13:1935/radiocity/live_1/chunklist_w232887204.m3u8"},
    {name = "Radio City juy", url = "https://5cd577a3dd8ec.streamlock.net/radiocity/live_1/chunklist_w1831978817.m3u8"},
    {name = "Radio Ciudad 88.1 - Jujuy", url = "http://181.177.20.20:8000/radiociudad"},
    {name = "Radio Ciudad AM 1110 ", url = "https://media.radios.ar:1110/"},
    {name = "Radio Comunitaria Cuyum", url = "https://radios.liberaturadio.org/Cuyum"},
    {name = "Radio Comunitaria Cuyum", url = "https://radios.liberaturadio.org/Cuyum"},
    {name = "Radio Comunitaria FM Punta del Indio", url = "http://streaming.conexionproductora.com.ar:9650/"},
    {name = "Radio Comunitaria LaQuintaPata", url = "http://server3.veemesoft.com.ar:26429/;"},
    {name = "Radio Con Aguante - Piezas de Realidad", url = "https://streaming01.shockmedia.com.ar/9536/;?1718973618118"},
    {name = "Radio Con Vos 89.9", url = "https://server1.stweb.tv/rcvos/live/playlist.m3u8"},
    {name = "Radio Con Vos 89.9 FM", url = "https://www.surfmusic.de/m3u/radio-con-vos-89-9-fm,20048.m3u"},
    {name = "Radio Concierto 96.5 FM", url = "https://vivohd.fmradioconcierto.com.ar:8000/radio.mp3"},
    {name = "RADIO CONCIERTO 97.1 MHZ", url = "https://vivohd.fmradioconcierto.com.ar:8000/status-json.xsl//radio.mp3"},
    {name = "Radio Continental", url = "https://alpha.radioplayer.com.ar/stream/cadenacontinental"},
    {name = "Radio Cool FM 103.7", url = "https://radios.solumedia.com:10805/stream/1/"},
    {name = "Radio Cristiana 95.7", url = "http://genexservicios.com:8098/listen.asx"},
    {name = "Radio Cristiana fm 88.3", url = "https://rr5100.globalhost1.com/8540/stream;"},
    {name = "Radio Cristiana FM 88.3", url = "https://rr5100.globalhost1.com/8540/;"},
    {name = "Radio Cultura", url = "https://streaming.escuchanosonline.com:7035/stream"},
    {name = "Radio de Clásicos 106.9 FM - Saladillo", url = "http://streamconex.com:8118/stream"},
    {name = "Radio De la Azotea", url = "http://149.202.235.235:8164/;stream/1"},
    {name = "Radio De La Costa 101.9 FM", url = "https://streaming2.locucionar.com/proxy/porlavida102?mp=/stream"},
    {name = "Radio de tango", url = "https://fair.entic.net:8010/tango"},
    {name = "Radio DeeJay 92.5", url = "http://streaming.radiosenlinea.com.ar:9640/"},
    {name = "Radio del Plata", url = "https://streaming01.shockmedia.com.ar:10217/stream"},
    {name = "Radio del Puerto. FM 92.1. Barranqueras. Chaco", url = "https://streaming.escuchanosonline.com:7106/stream"},
    {name = "Radio Digital San Luis 101.1 FM", url = "https://streamconex.com:8062/;"},
    {name = "Radio Disney - Argentina FM 94.3", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_ARG_BA_ADP.aac"},
    {name = "Radio Disney (Argentina) - 94.3 FM - LRL301 - Ciudad de Buenos Aires, Argentina", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_ARG_BAAAC.aac"},
    {name = "Radio Disney Argentina", url = "https://24223.live.streamtheworld.com/DISNEY_ARG_BA_ADP/HLS/playlist.m3u8"},
    {name = "Radio Disney Argentina 94.3", url = "https://provisioning.streamtheworld.com/pls/DISNEY_ARG_BA_ADP.pls"},
    {name = "Radio Disney Argentina 94.3. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_ARG_BA.mp3"},
    {name = "RADIO DON", url = "https://01.solumedia.com.ar:8936/stream"},
    {name = "Radio Dos Corrientes FM 99.3. Ciudad de Corrientes", url = "https://radios.solumedia.com/6396/stream"},
    {name = "Radio El Mundo - AM 1070", url = "https://streaming.escuchanosonline.com:7118//stream?type=http&nocache=1"},
    {name = "Radio Emanuel FM 88.9", url = "https://rr5100.globalhost1.com/8546/;"},
    {name = "Radio Espiritu Santo", url = "http://01.solumedia.com.ar:7802/;"},
    {name = "Radio Estacion Sur", url = "http://88.198.9.174:8196/live"},
    {name = "Radio Estacion Sur", url = "http://88.198.9.174:8196/live"},
    {name = "Radio Estelar - Classicos", url = "http://01.solumedia.com.ar:7607/;"},
    {name = "Radio Estudios Max", url = "http://streaming.shockmedia.com.ar:8002/stream"},
    {name = "Radio Fan Castelli", url = "http://streaming5.locucionar.com:23184/stream"},
    {name = "Radio Fiesta 91.7", url = "http://190.52.32.13:1935/radiofiesta/live_1/playlist.m3u8"},
    {name = "Radio Fiesta 97.1 Jujuy", url = "https://5cd577a3dd8ec.streamlock.net/radiofiesta/live_1/playlist.m3u8"},
    {name = "Radio Flow", url = "http://stream.zeno.fm/5rxr1mcdcxhvv.m3u"},
    {name = "Radio Flow On", url = "http://stream.zeno.fm/5rxr1mcdcxhvv"},
    {name = "Radio Flow On", url = "http://stream.zeno.fm/5rxr1mcdcxhvv.pls"},
    {name = "Radio FM Gualamba 93.7. Resistencia Chaco", url = "https://ssl.radiosnethosting.com/index.php?port=9072"},
    {name = "Radio FM Profesional 89.9", url = "http://vps-c0159cbc.vps.ovh.ca/10006/;"},
    {name = "Radio FM UTN 94.5 - Regional Mendoza", url = "http://streaming.fmutn.com.ar:8000/FMUTN#;.mp3"},
    {name = "Radio Futura - FM 90.5 mhz", url = "https://streamer.fmfutura.com.ar/vivo.mp3"},
    {name = "Radio General Conesa AM 1420", url = "https://streaming01.radiosenlinea.com.ar/8490/stream"},
    {name = "Radio General Guemes AM 1050 Buenos Aires", url = "https://sonic.dattalive.com/8482/stream"},
    {name = "radio Gráfica ", url = "http://radio13.servidorderadio.net:8110/"},
    {name = "radio Gráfica ", url = "http://radio13.servidorderadio.net:8110/"},
    {name = "Radio Grafica", url = "http://radio13.servidorderadio.net:8110/api/v3/widgetsview?id=100&option=big&ssl=1&auto=0"},
    {name = "Radio Horizonte 94.3", url = "https://26453.live.streamtheworld.com/SAM06AAC243_SC"},
    {name = "Radio Impacto", url = "https://server.streamcasthd.com/8022/stream"},
    {name = "Radio Impacto Cordoba", url = "http://sonic.cloudstreaming.eu:9992/;"},
    {name = "Radio Impacto de Vida", url = "https://streaming2.locucionar.com/proxy/impactodevida?mp=/stream"},
    {name = "Radio Infinity", url = "https://sonic.dattalive.com/8192/stream"},
    {name = "Radio Influencia", url = "http://genexservicios.com:8134/;?1713795357814"},
    {name = "Radio Jornada", url = "https://edge-st1-audio.masterhost.com.ar/listen/jornada_online_mdz/radio.mp3"},
    {name = "Radio Jornada FM 91.9", url = "https://edge-st1-audio.masterhost.com.ar/listen/jornada_online_mdz/radio.mp3"},
    {name = "Radio Kermes", url = "https://server.laradio.online/proxy/radiokermes?mp=/stream&1706361379922"},
    {name = "Radio Kermés Comunitaria", url = "http://server.laradio.online:8599/;"},
    {name = "Radio La Luna AM 1140", url = "https://server.ohradio.com.ar/9344/stream"},
    {name = "radio La Nave", url = "https://stream.zeno.fm/7zb5ppzk0mruv.aac"},
    {name = "Radio La Plata 90.9", url = "https://radios.solumedia.com/6348/stream"},
    {name = "Radio La PLaza 94.7", url = "https://radio.arcast.net:1045/stream"},
    {name = "Radio La Red", url = "https://24283.live.streamtheworld.com/LA_RED_AM910AAC_SC"},
    {name = "Radio La Red AM 910", url = "https://21933.live.streamtheworld.com/LA_RED_AM910AAC.aac"},
    {name = "Radio La Red AM 910. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LA_RED_AM910AAC.aac"},
    {name = "Radio Las Rosas", url = "http://streaming01.shockmedia.com.ar:9676/;"},
    {name = "Radio Latina 100.9 (General Roca) ", url = "https://streamingraddios.online/proxy/luradioe?mp=/stream"},
    {name = "Radio Latina FM 101.1", url = "http://streaming.latina101.com.ar:9000/Repetidoras"},
    {name = "Radio Legislatura", url = "http://186.189.66.4:8100/source"},
    {name = "Radio Libre 93.5 General Pico", url = "https://streaming1.locucionar.com/proxy/libre935?mp=/stream"},
    {name = "Radio Life Rio Grande TDF ", url = "http://delta.radioplayer.com.ar:9220/radiolife"},
    {name = "Radio Longplay", url = "http://server.ohradio.com.ar:9352/;"},
    {name = "Radio Magic FM 100.9 Tigre", url = "https://radio01.ferozo.com/proxy/ra01000677/?mp=/stream"},
    {name = "RADIO MARIA ARGENTINA", url = "http://dreamsiteradiocp.com:8004/stream"},
    {name = "Radio Más", url = "http://nvradios.com:9384/;"},
    {name = "Radio Maxi FM", url = "http://cloudstream2036.conectarhosting.com:8140/listen.pls"},
    {name = "Radio Meridiano", url = "http://23.111.184.195:8050/fmmeridiano.mp3"},
    {name = "Radio Mitre", url = "https://buecrplb01.cienradios.com.ar/Mitre790.aac"},
    {name = "Radio Mitre AM 790 Buenos Aires", url = "https://24273.live.streamtheworld.com/AM790_56AAC.aac"},
    {name = "Radio Mitre AM 790 Buenos Aires", url = "https://24273.live.streamtheworld.com/AM790_56AAC.aac"},
    {name = "Radio Mitre AM 790 Buenos Aires version 3", url = "https://24273.live.streamtheworld.com/AM790_56AAC.aac"},
    {name = "Radio Mitre AM 790 Buenos Aires version 5", url = "https://24273.live.streamtheworld.com/AM790_56AAC.aac"},
    {name = "Radio Monk", url = "http://streaming01.shockmedia.com.ar:9858/;"},
    {name = "Radio nacional AM 870", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad1"},
    {name = "Radio Nacional Córdoba - LRA7 AM750", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad7"},
    {name = "Radio Nacional Folklorica 98.7", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad38"},
    {name = "Radio Nacional Rock 93.7", url = "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad39"},
    {name = "Radio Nacional Santa Rosa AM 730", url = "https://sa.mp3.icecast.magma.edge-access.net/sc_rad3"},
    {name = "Radio Natagalá FM 94.7. Resistencia Chaco", url = "http://radio02.ferozo.com:8704/;"},
    {name = "Radio Nordeste FM 102.7. Resistencia. Chaco", url = "http://turadioenvivo.com:11027/stream"},
    {name = "Radio Norte", url = "https://icecast.hostingbahia.com.ar:8002/live?90131"},
    {name = "Radio Norte Bahia", url = "http://icecast.hostingbahia.com.ar:8002/live?1475282235673"},
    {name = "Radio Noticias FM 99.5 - Santa Rosa.", url = "http://stream01.insidetec.com:9014/radionoticias"},
    {name = "Radio Noticias FM 99.5 - Santa Rosa.", url = "http://stream01.insidetec.com:9014/radionoticias"},
    {name = "Radio NOW 97.9", url = "https://ipanel.instream.audio:7002/stream?_=18fea7232d5"},
    {name = "Radio On The Route", url = "http://01.solumedia.com.ar:7345/;"},
    {name = "Radio Onda | Tigre Argentina", url = "http://149.202.235.235:8011/live"},
    {name = "RADIO ONE 103.7", url = "https://s8.stweb.tv/one/live/playlist.m3u8"},
    {name = "Radio One 103.7", url = "https://s8.stweb.tv/one/live/playlist.m3u8"},
    {name = "Radio Orión", url = "http://01.solumedia.com.ar:7834/stream?icy=http"},
    {name = "Radio Patagonia Puerto Madryn FM 105.5", url = "https://stream.servidorm24.net:7004/stream"},
    {name = "Radio Piamonte - FM Tiempo 92.5", url = "https://server.radiostreaming.com.ar/8288/stream;?1721304335025"},
    {name = "Radio Provincia", url = "http://streaming.provinciaradio.com.ar:7007/am"},
    {name = "Radio Provincia - AM1270", url = "https://streaming.provinciaradio.com.ar:7008/am"},
    {name = "Radio Provincia - FM 97.UNE", url = "http://streaming.provinciaradio.com.ar:3351/fm"},
    {name = "Radio Provincia AM 1270", url = "https://streaming.provinciaradio.com.ar:7008/am"},
    {name = "Radio Provincia de Santa Cruz AM 830 khz Rio Gallegos", url = "https://transmision-lu14.santacruz.gob.ar/lu14.mp3"},
    {name = "Radio Provincia del Chaco FM 101.5. Resistencia Chaco", url = "https://debred5.ecomchaco.com.ar:8443/radioecom"},
    {name = "Radio Provincia FM 97.UNE", url = "https://streaming.provinciaradio.com.ar:3352/fm"},
    {name = "Radio Pueblo de Maria", url = "http://01.solumedia.com.ar:7018/;"},
    {name = "Radio Quilpo", url = "https://https.nvradios.com/radio/9352/radio.mp3"},
    {name = "Radio Rebelde AM 740", url = "http://stream.radiojar.com/qkxht62hy8hvv"},
    {name = "Radio Recuerdos 106.7", url = "http://198.204.234.10:8580/stream"},
    {name = "Radio República", url = "http://streamlky.alsolnet.com:443/republica99"},
    {name = "Radio Rio Cuarto", url = "https://server6.hostradios.com/8552/stream/;/;type=mp3"},
    {name = "Radio Rio Cuarto", url = "https://server6.hostradios.com/8552/stream/;/;type=mp3"},
    {name = "Radio Rivadavia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC_SC?dist=triton-widget&pname=tdwidgets"},
    {name = "Radio Rivadavia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIA.mp3"},
    {name = "Radio Rivadavia AM 630. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac"},
    {name = "Radio Saint Germain", url = "http://173.255.205.241:8200/"},
    {name = "Radio Saladillo", url = "https://chino.republicahosting.com:2316/live"},
    {name = "Radio Santa Cecilia", url = "https://01.solumedia.com.ar:8492/stream"},
    {name = "Radio Semilla FM 106.5 - IMPA", url = "https://sslstream.online:7091/;"},
    {name = "Radio Shopping", url = "https://stream4.suenas.net/shoppingclassics"},
    {name = "Radio Sublime Gracia", url = "https://stream.consultoradas.com/8174/stream"},
    {name = "Radio Sudamericana 100.5 - Corrientes Capital", url = "http://turadioenvivo.com:8530/stream?1562165478826"},
    {name = "Radio Suquia", url = "https://streaming01.shockmedia.com.ar:10945/"},
    {name = "Radio Sur - FM 88.3 mhz", url = "https://01.solumedia.com.ar:8020/stream"},
    {name = "Radio Sur FM 88.3", url = "http://01.solumedia.com.ar:8020/stream"},
    {name = "Radio Sur FM 90.1", url = "https://ssl.dainusradio.com/shoutcast2/9848/"},
    {name = "Radio Tandil - LU22 AM140", url = "https://streaming01.shockmedia.com.ar/8170/live"},
    {name = "Radio Tecnoteca", url = "https://server7.hostradios.com:8142/stream"},
    {name = "Radio Tiempo Villa Mercedes", url = "https://stream-152.zeno.fm/6v6wmf2sivevv?zs=n7o6R7wmQQmLfi8nD1ADNA"},
    {name = "Radio Trend Topic", url = "https://sonic.dattalive.com/8480/stream"},
    {name = "Radio Universidad", url = "http://163.10.186.70:8002/stream"},
    {name = "Radio Universidad - FM91.1 UTN Resistencia", url = "http://01.solumedia.com.ar:8336/"},
    {name = "Radio Universidad - FM93.5 La Tecno (UTN Tierra del Fuego)", url = "http://streamall.alsolnet.com/latecno"},
    {name = "Radio Universidad - UNLP - AM 1390", url = "https://statics-v2.streema.com/static/audios/sample.ea78c3d52389.mp3"},
    {name = "Radio Universidad AM580", url = "https://radios.solumedia.com:10976/stream"},
    {name = "Radio Universidad CALF Neuquén", url = "https://cdn.instream.audio/:9032/stream?in_device_id=wp-5270c502-0535-444e-975b-d49592d1d988"},
    {name = "radio universidad de rosario", url = "https://cdn.instream.audio/:9202/stream"},
    {name = "Radio Universidad FM 93.5 Rio Grande", url = "http://streamall.alsolnet.com/latecno"},
    {name = "Radio Universidad Mendoza", url = "https://fm.uncu.edu.ar/"},
    {name = "Radio Universidad Rosario", url = "https://cdn.instream.audio/:9202/stream"},
    {name = "Radio Universo FM100.3 Carhue", url = "http://server11.veemesoft.com.ar:28918/Stream/;"},
    {name = "Radio UNLu", url = "http://144.217.30.219:8043/"},
    {name = "Radio Unlu", url = "http://144.217.30.219:8043/"},
    {name = "Radio Uno Ingeniero Jacobacci FM 105.5", url = "https://ssl.radiosnethosting.com/index.php?port=8642/;stream.mp3"},
    {name = "Radio UNR", url = "https://cdn.instream.audio/:9202/stream"},
    {name = "RADIO UNR", url = "https://cdn.instream.audio/:9202/stream"},
    {name = "Radio UTN Bahia Blanca - FM 93.5", url = "https://sonic.cloudstreaming.eu:10986/;"},
    {name = "Radio UTN Mendoza 94.5", url = "http://streaming.fmutn.com.ar:8000/FMUTN"},
    {name = "Radio Valle Viejo", url = "https://stm2.livecastradio.com:9379/stream"},
    {name = "Radio Verdad (Villa Dolores)", url = "https://streaming1.locucionar.com/proxy/radioverdad?mp=/stream"},
    {name = "Radio Verdad Villa Dolores", url = "https://streaming1.locucionar.com/proxy/radioverdad?mp=/stream"},
    {name = "Radio Vitalista", url = "http://01.solumedia.com.ar:7169/;"},
    {name = "Radio Vos 88.7", url = "http://centova1.veemesoft.com.ar:12378/;"},
    {name = "Radio Vos Salta 90.1", url = "http://streaming01.shockmedia.com.ar:9200/;"},
    {name = "Radio Zero MAR DEL PLATA 98.9 - MENDOZA 91.1 - PINAMAR 107.5", url = "http://online.radiozero.fm:8020/mp3"},
    {name = "RADIO ZETA 94.5 Mhz, La Plata Buenos Aires...ARGENTINA", url = "https://server.ohradio.com.ar/9650/stream"},
    {name = "Radio zity", url = "http://190.52.32.13:1935/radiocity/live_1/chunklist_w232887204.m3u8"},
    {name = "Radio5 100.5 - General Pico", url = "http://streaming2.locucionar.com:9089/"},
    {name = "Radiofonica 100.7", url = "https://radio02.ferozo.com/proxy/ra02000290?mp=/stream"},
    {name = "RadioOne", url = "https://one.stweb.tv/one/live/playlist.m3u8"},
    {name = "RadioTV AN24", url = "https://cdn.instream.audio:2199/tunein/radiotva.pls"},
    {name = "Radiovision 99.5 fm", url = "https://cdn.instream.audio/:9061/stream?in_device_id=wp-e80516ae-250e-4455-ac11-14ce5f370cc8"},
    {name = "Radiovision Comodoro Rivadavia FM 99.5 ", url = "https://cdn.instream.audio/:9061/stream?in_device_id=wp-5270c502-0535-444e-975b-d49592d1d988"},
    {name = "RAE - Argentina al Mundo", url = "https://sa.mp3.icecast.magma.edge-access.net/sc_rad35"},
    {name = "RAE - Argentina al mundo", url = "https://sa.mp3.icecast.magma.edge-access.net/sc_rad35"},
    {name = "Ranquel FM", url = "https://server6.hostradios.com/8556/stream/;type=mp3"},
    {name = "RBD Radio Multimedia", url = "https://streaming.radiosenlinea.com.ar:10637/live?_=1"},
    {name = "rc", url = "http://radio13.servidorderadio.net:9648/"},
    {name = "RC 107.1", url = "http://190.52.32.13:1935/radiocity/live_1/chunklist_w1583615162.m3u8"},
    {name = "REAL POLITIK FM", url = "https://01.solumedia.com.ar:8638/stream?icy=http"},
    {name = "Red 92", url = "https://radios.solumedia.com/6426/stream"},
    {name = "Red 92", url = "https://radios.solumedia.com/6426/stream"},
    {name = "Red Santa Fe Fm 106.3", url = "http://190.7.30.53:8010/redsantafe.mp3"},
    {name = "Remanente de efraim", url = "https://stream.zeno.fm/vxqg94xspc9uv"},
    {name = "Renacer fm 97.5", url = "https://emisora.brotherservicios.com/8018/stream"},
    {name = "Renacer fm 97.5", url = "https://emisora.brotherservicios.com/8018/stream"},
    {name = "RetroMusic San Justo", url = "http://178.32.146.184:5938/;"},
    {name = "Revuelto Radio", url = "https://cdn.instream.audio:9097/stream"},
    {name = "Rincón Gaucho", url = "https://dj91.hostingnuclear.com/9952/stream"},
    {name = "Rio FM 104.3 General Belgrano", url = "https://sonicpanel.hostradios.com/8032/stream"},
    {name = "Rio FM 96.9 Rosario", url = "https://streaming.redboing.com/radio/8070/radio.mp3"},
    {name = "Rio Negro Radio 91.9 (General Roca)", url = "https://01.solumedia.com.ar:7004/stream"},
    {name = "Rioseco FM", url = "http://argentina.republicahosting.com:8236/stream"},
    {name = "Rivadavia", url = "https://24383.live.streamtheworld.com/RIVADAVIAAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=300x250%2C728x90&burst-time=15&sbmid=9892438b-a3ed-44ab-d837-6399dac0aa64"},
    {name = "Rivadavia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC_SC?dist=triton-widget&pname=tdwidgets"},
    {name = "Rivadavia AM 630 AAC Alta. Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac"},
    {name = "Rivadavia Rosario FM 106.3 Rosario", url = "https://radio02.ferozo.com/proxy/ra02001331?mp=/stream"},
    {name = "Rock And More", url = "https://streaming01.shockmedia.com.ar/8616/;"},
    {name = "rock and pop 89.7 FM", url = "https://streamlky.alsolnet.com/rockandpop_128k"},
    {name = "Rock And Pop FM 95.9 (Rock & Pop) Ciudad de Buenos Aires", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ROCKANDPOPAAC.aac"},
    {name = "Rock RA", url = "http://stream.zeno.fm/mbketaeaqhguv"},
    {name = "Rock ra", url = "https://stream.zeno.fm/mbketaeaqhguv"},
    {name = "RPM Oldies & Retro Hits", url = "https://radios.solumedia.com/6118/stream"},
    {name = "RPM Oldies & Retro Hits", url = "https://radios.solumedia.com/6118/stream"},
    {name = "s", url = "https://stream.almadinafm.com/;stream.mp3"},
    {name = "s", url = "https://stream.almadinafm.com/;stream.mp3"},
    {name = "San Roque Fm, 97.9 Mhz", url = "https://s21.myradiostream.com/10952/listen.mp3"},
    {name = "Sensation Radio 107.5 Neuquén", url = "http://radio01.ferozo.com:8976/;stream.nsv"},
    {name = "Si", url = "https://argentina.republicahosting.com:2022/live"},
    {name = "Si 98.9 FM", url = "http://server.laradio.online:8202/;"},
    {name = "Simphony San Isidro FM 91.3 Mhz", url = "http://cdn.instream.audio:8129/stream.m3u"},
    {name = "Skorpio Vicuña Mackenna FM 102.5", url = "https://radios.streamingdha.com.ar/8052/;"},
    {name = "Solo Vinilo", url = "http://stream.zeno.fm/7p5tn0dfam8uv"},
    {name = "Solo Vinilo Classic Rock Hits", url = "https://stream-153.zeno.fm/eyf4f0dfam8uv?"},
    {name = "Somos Radio", url = "https://ipanel.instream.audio:7000/stream"},
    {name = "Sonifo FM 103.5 - El clásico sonido de Buenos Aires", url = "https://stream.serviciowebdigital.com/8780/stream"},
    {name = "Soplo de Bendición ", url = "http://stream.laut.fm/soplodebendicionradio"},
    {name = "Soy un Clasico", url = "https://streaming1.locucionar.com/proxy/soyunclasico?mp=/stream"},
    {name = "Spacio Fm Metan", url = "https://sonic.dattalive.com/8598/stream"},
    {name = "Sudaca FM", url = "https://sudaca.redenfoques.com.ar/sudaca"},
    {name = "T&D Radio", url = "http://149.202.235.235:8133/live"},
    {name = "The Musical Box Radio", url = "http://albireo.shoutca.st:9740/stream"},
    {name = "Tiempo 97.5 FM", url = "https://sc.host-live.com/8166/stream"},
    {name = "TMB The Musical Box", url = "https://tmbradio.radioca.st/stream"},
    {name = "Tropibox FM 107.1", url = "http://69.64.46.123:8015/stream?1571687077817,"},
    {name = "Una Radio Muchas Voces", url = "https://stream.radios.red/unaradio.ogg"},
    {name = "UnDinamo", url = "https://cdn.instream.audio/:9339/stream?in_device_id=WPU32ffbfaa3cd8ebaaa8f64ec868bf4b88XY177fdfd79a7"},
    {name = "Undinamo", url = "https://cdn.instream.audio/:9339/stream?in_device_id=WPU32ffbfaa3cd8ebaaa8f64ec868bf4b88XY177fdfd79a7"},
    {name = "Universidad Claf 103.7 Mhz", url = "http://cdn.instream.audio:9032/stream"},
    {name = "UNQRadio - FM 91.5", url = "http://170.210.74.75:8000/fm915.mp3"},
    {name = "UNRC Radio", url = "https://server6.hostradios.com:7280/stream"},
    {name = "Urbana Play 104.3", url = "https://vmf.edge-apps.net/playlist/urbana.m3u8/play.m3u8"},
    {name = "Urbana Play 104.3", url = "https://ice1.edge-apps.net/urbana.audio"},
    {name = "Urbana Play 104.3", url = "https://vmf.edge-apps.net/playlist/urbana.m3u8/play.m3u8"},
    {name = "Vale 97.1", url = "http://vale.stweb.tv:1935/vale/live/playlist.m3u8"},
    {name = "Vale 97.5", url = "https://vale.stweb.tv/vale/live/chunks.m3u8"},
    {name = "VIP Radio", url = "https://server6.hostradios.com:7232/;?"},
    {name = "VIVA 102.3", url = "http://streaming1.locucionar.com:12072/stream"},
    {name = "Vorterix (2023)", url = "https://ice2.edge-apps.net/radio1_high-20057.audio"},
    {name = "WAN Radio", url = "http://69.64.46.123:8009/autodj"},
    {name = "WClassicRadio", url = "http://server.ohradio.com.ar:9604/stream/;"},
    {name = "X1 POP Radio", url = "http://x1.xsminternet.com:58090/stream/1/"},
    {name = "X1 Radio 80s", url = "http://x1.xsminternet.com:58090/stream/2/"},
    {name = "X1 Radio ELECTRO", url = "https://x1.xsminternet.com:58091/stream/3/"},
    {name = "XRADIO 99.1 ", url = "https://radios.streamingdha.com.ar/9826/;"},
    {name = "Yo Argentino Radio", url = "http://argentina.republicahosting.com:8285/stream"},
}

return stations
