local stations = {
<<<<<<< HEAD
    {name = "1027 DIGITAL FM", url = "https://cp4.lorini.net:36187/stream"},
    {name = "935 La Gran FM", url = "https://stream-55.zeno.fm/hcddm386za0uv?%20zs=_PyMMSYIRRmVntwZ85BL8g"},
    {name = "973 FM Maracay", url = "http://station.asawstreaming.com:8010/;"},
    {name = "999 Festiva FM", url = "https://acp2.lorini.net:28018/stream"},
    {name = "Acción 1045 FM La Diferencia En El Dial", url = "https://stream.intervalohost.com/accionfm/stream"},
    {name = "Activa 889FM", url = "https://stream.zeno.fm/w3gzdxagmh0tv"},
    {name = "Activa FM 1049", url = "https://stream.zeno.fm/t31pbasum7zuv"},
    {name = "Adulto Joven 881", url = "https://server6.globalhostla.com:9168/stream"},
    {name = "Alba Ciudad 963 FM", url = "https://envivo.albaciudad.org/albaciudad.mp3"},
    {name = "Alba Ciudad Radio 936 Fm16K", url = "https://envivo.albaciudad.org/alba16.mp3"},
    {name = "Amiga FM 939", url = "https://stream.zeno.fm/dr612ew61rhvv"},
    {name = "Andes 893 FM", url = "http://streamingned.com:7098/;"},
    {name = "Aragueña FM 995", url = "https://stream.zeno.fm/1crdje0gynatv"},
    {name = "Audaz FM 945", url = "https://servers58.com/proxy/audaz?mp=/stream"},
    {name = "Autentica 1075 FM", url = "https://stream.zeno.fm/8v5et2n6bzzuv"},
    {name = "AUTENTIK 1007 FM", url = "https://server6.globalhostla.com:9228/stream"},
    {name = "Autopista Estereo 1047 Fm", url = "https://server6.globalhostla.com:9486/stream"},
    {name = "Bahiafmnet", url = "https://laradiossl.online:10379/live"},
    {name = "Baladas Y Algo Mas", url = "http://streamingned.com:7286/;"},
    {name = "BANDERA 1057 FM", url = "http://streamingned.com:7148/;"},
    {name = "Bella FM 969", url = "https://server6.globalhostla.com:9380/stream"},
    {name = "Betel 1021 FM", url = "https://stream.zeno.fm/npnxhehm64zuv"},
    {name = "C-Oye 891 FM", url = "http://streamingned.com:7146/;"},
    {name = "CADENA DIGITAL FM 995", url = "https://server6.globalhostla.com:9288/stream"},
    {name = "Calle 989 FM", url = "https://cloudstream2030.conectarhosting.com/8076/;"},
    {name = "CANAIMA STEREO", url = "https://stream.zeno.fm/cd7isb0ojlruv"},
    {name = "Candela Pura 919", url = "https://server6.globalhostla.com:9020/stream"},
    {name = "Capital 999 FM", url = "http://live2.rcast.net:8520/;stream.mp3"},
    {name = "CAQUETIA 891 FM", url = "https://stream.zeno.fm/hmpo3e3iifatv"},
    {name = "Cardenales 921 FM", url = "https://sp4.colombiatelecom.com.co/8082/stream"},
    {name = "Carismah FM 1011", url = "https://cp2.lorini.net:41036/CarismahFM"},
    {name = "CDR 987 FM", url = "https://laradiossl.online:8347/;"},
    {name = "Cima 951 FM", url = "https://stream.zeno.fm/naa84dtd6f8uv"},
    {name = "Circuito Comunión Nueva Bolivia 931 FN", url = "https://stream.zeno.fm/abkmpazmyk8uv"},
    {name = "Circuito Comunión Santa Elena De Arenales 1011 FM", url = "https://stream.zeno.fm/ksh16ht4na0uv"},
    {name = "CIRCUITO DINAMICA 1033 FM", url = "https://acp2.lorini.net:36075/stream"},
    {name = "CIRCUITO DINAMICA 939 FM", url = "https://acp2.lorini.net:30090/stream"},
    {name = "CIRCUITO DINAMICA 955 FM", url = "https://acp2.lorini.net:41066/stream"},
    {name = "Circuito X", url = "http://cp2.lorini.net:39500/stream"},
    {name = "Circuito X 897 FM", url = "http://cp2.lorini.net:39500/;mp312844|mp312844"},
    {name = "Clasicos 909 FM El Tigre", url = "http://acp2.lorini.net:2030/clasicoseltigre"},
    {name = "Comunion 975 Fm", url = "https://stream.zeno.fm/cy3ef0frwmzuv"},
    {name = "Contacto FM 937", url = "https://laradiossl.online:10058/;"},
    {name = "Cool Radio Web", url = "https://stream.zeno.fm/omuwlrerlxhvv"},
    {name = "Costa 1055 FM", url = "https://stream.zeno.fm/ixlhtprdocktv"},
    {name = "Costa Del Sol 931 FM", url = "https://cast4.asurahosting.com/tunein/sol.pls"},
    {name = "COSTERA 1027 FM", url = "https://streamingned.com:7112/stream"},
    {name = "DECIBEL 887 FM", url = "https://stream.zeno.fm/b8xv6835gd0uv"},
    {name = "Diamante FM 919", url = "https://stream.zeno.fm/n4tcsndvtxhvv"},
    {name = "Digital FM 969", url = "https://server6.globalhostla.com:9240/stream"},
    {name = "Dinamik 899 FM", url = "https://stream.zeno.fm/wmnqq0m2uk8uv"},
    {name = "DJ Carlos Radio", url = "https://sc10.conectarhosting.com/proxy/djcarlo1?mp=/stream"},
    {name = "Dj Shaggy Venezuela", url = "http://51.255.123.116:9226/"},
    {name = "DJ Shaggy Venezuela Radio", url = "https://laradiossl.online:9226/;"},
    {name = "Electrik 977 FM", url = "https://streamingned.com:7044/stream"},
    {name = "Elite 1037 FM", url = "https://stream.zeno.fm/awromk7ut4svv"},
    {name = "Época FM 887", url = "https://sp.wnetserver.com/8026/stream"},
    {name = "Esencia 887 FM", url = "https://stream.zeno.fm/lozraai0qlgvv"},
    {name = "Espacio 961 FM", url = "https://radiointernet.co/8004/stream"},
    {name = "Espacio Network", url = "https://acp2.lorini.net:28050/stream"},
    {name = "Espectaculo 1007 FM", url = "https://laradiossl.online:10583/;?_=2#.mp3"},
    {name = "Evolussiun 929 FM", url = "https://laradiossl.online:8150/live"},
    {name = "Exa FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "EXITOS 1009 FM", url = "https://radio.webtuya.com/8076/stream"},
    {name = "Éxitos 1031 FM", url = "http://ur58.lorini.net:50004/EXITOS1031FM.aac"},
    {name = "Éxitos 897 FM", url = "https://acp4-cdn.lorini.net/proxy/30000?mp=/stream"},
    {name = "Éxitos 905 FM", url = "https://acp4-cdn.lorini.net/proxy/10109?mp=/stream"},
    {name = "Éxitos 931 FM", url = "https://acp4-cdn.lorini.net/proxy/15012?mp=/stream"},
    {name = "EXITOS 953 FM", url = "https://acp4-cdn.lorini.net/proxy/10004?mp=/stream"},
    {name = "Éxitos 997 FM", url = "https://acp4-cdn.lorini.net/proxy/25006?mp=/stream"},
    {name = "Éxitos 999", url = "https://acp4.lorini.net/proxy/ur2070?mp=/stream"},
    {name = "Extremo 895 FM", url = "https://c2.radioshdstreaming.com:8190/extremo.aac"},
    {name = "Fama 981 FM", url = "https://server6.globalhostla.com:9356/stream"},
    {name = "Favorita 1061 FM", url = "https://sp.wnetserver.com/8046/stream"},
    {name = "Felina Estéreo", url = "https://servers58.com/proxy/felinaestereo?mp=//;type=mp3"},
    {name = "FIESTA 1021 FM", url = "https://server6.globalhostla.com:9028/stream"},
    {name = "Fiesta 1059 FM", url = "https://stream.zeno.fm/et7xq0a4p48uv"},
    {name = "Fiesta 1065", url = "https://server6.globalhostla.com:9012/stream"},
    {name = "Fiesta 891 FM", url = "https://acp2.lorini.net:36050/stream"},
    {name = "Fiesta Latina 1061 Fm", url = "https://stream.zeno.fm/e2kzfpr34d0uv/;type=mp3"},
    {name = "FM Mundial 1041", url = "https://onlineradiobox.com/json/ve/lafmmundial/play?platform=web"},
    {name = "Guanareña 983 FM", url = "https://laradiossl.online:10175/;?_=1#.mp3"},
    {name = "Hot 941", url = "https://server6.globalhostla.com:9016/stream"},
    {name = "IMPACTO RADIO 973 FM", url = "https://server6.globalhostla.com:9414/stream"},
    {name = "La Cumanesa 1053", url = "https://laradiossl.online:10774/live"},
    {name = "La Mega 1073", url = "https://acp4.lorini.net/proxy/ur2050?mp=/stream"},
    {name = "La Mega 965 Maracay", url = "https://acp4-cdn.lorini.net/proxy/15010?mp=/stream"},
    {name = "La Radio Del Sur", url = "http://190.202.130.61:8000/lrds"},
    {name = "La Romantica 889", url = "https://server6.globalhostla.com:8068/stream"},
    {name = "Lasser 977 FM", url = "https://server6.globalhostla.com:8010/stream"},
    {name = "Magic Radio 925 Maracay", url = "https://cloudstream2030.conectarhosting.com/8324/;"},
    {name = "Maxi Radio Digital", url = "https://guri.tepuyserver.net/8010/stream"},
    {name = "Onda 1079 La Superestación", url = "https://acp4.lorini.net/proxy/ur2060?mp=/stream"},
    {name = "Orbita 1075 FM Puerto La Cruz", url = "https://cast20.plugstreaming.com:2000/stream/orbitaplc/;"},
    {name = "Orbita 901 FM El Tigre", url = "https://cast20.plugstreaming.com:2020/stream/orbitaeltigre/;"},
    {name = "Orbita FM 963 Anaco", url = "https://cast10.plugstreaming.com:2000/stream/orbitaanaco/;"},
    {name = "Planeta 1053 Caracas FM", url = "https://cast10.plugstreaming.com:2020/stream/planetafm/;"},
    {name = "PLENITUD 909", url = "https://sp.wnetserver.com/8060/stream"},
    {name = "Radio 2000", url = "https://streaming.adclichosting.com:8030/radio2000.mp3"},
    {name = "RADIO ACTIVA 1035 MERIDA", url = "https://stream.zeno.fm/3gch5vc20a0uv"},
    {name = "Radio Dinã¡Mica 1490 AM", url = "https://guri.tepuyserver.net/8040/stream"},
    {name = "Radio Dinámica 929", url = "https://guri.tepuyserver.net/8012/stream"},
    {name = "RADIO EDUCATIVA DE VENEZUELA", url = "https://stream.zeno.fm/8vd9wvkvv8jvv"},
    {name = "Radio Nacional De Venezuela", url = "http://rnv.lorini.net:29100/RNVINFORMATIVO"},
    {name = "Radio Okey 1049 Tucupita", url = "https://stream-150.zeno.fm/9v1hr7ekzk8uv?zs=OUXqin1ySEe0qxB9jq6byQ"},
    {name = "Radio Rio 1069 FM", url = "https://live.ajfnetwork.com.ve/8010/stream"},
    {name = "RADIO RUMBOS 670 AM", url = "https://stream.zeno.fm/c3q3w8zfe18uv?triton-uid-cookie%3A0fae79a4-e789-4b9b-9ca7-d30ae705f0a6"},
    {name = "Radio Sol 891", url = "https://stream-67.zeno.fm/r2errtf2uk8uv"},
    {name = "Radio Sol 891 Maturin", url = "https://stream-67.zeno.fm/r2errtf2uk8uv?%20zs=7GPKP3MTQtWE9TZYVk5Khg"},
    {name = "Radio Sonora 995 FM", url = "http://stream.zeno.fm/n8zghua6u68uv"},
    {name = "Radioalterna", url = "https://server01.heplayer.com:7027/"},
    {name = "Redpres Radio", url = "https://stream.zeno.fm/qjgbevaswlfuv/"},
    {name = "RNV Activa", url = "http://rnv.lorini.net:29010/RNVACTIVA"},
    {name = "Rocafm Clasicos Caracas", url = "http://protostar.shoutca.st:8370/"},
    {name = "RQ 910 AM", url = "http://streaming3.globalhost.net.ve:9014/stream"},
    {name = "Rumba 1001 Barquisimeto FM", url = "https://cast10.plugstreaming.com:2020/stream/r1001/;"},
    {name = "Rumba 1049 Anzoategui FM", url = "https://cast10.plugstreaming.com:2020/stream/r1049/;"},
    {name = "Rumba 981 FM", url = "https://cast20.plugstreaming.com:2020/stream/r981/;"},
    {name = "RUMBA STEREO 947 FM", url = "https://server6.globalhostla.com:2000/tunein/sc_stereo/stream/pls"},
    {name = "Telesur", url = "https://cdnesmain.telesur.ultrabase.net/mbliveMain/audio/playlist.m3u8"},
    {name = "Tu Amiga Radio", url = "https://audio0stream.com:8010/turadioamiga"},
    {name = "Unión Radio 903 FM Caracas", url = "http://ur58.lorini.net:2080/stream"},
    {name = "VTV Venezuela", url = "https://radio.gmsiptv.com/vtvve"},
    {name = "Zona Musical Fm", url = "https://stream-149.zeno.fm/t9fhqcsiao2uv?zs=gyKTx5SuR4SIvrC0xE8KfQ"},
=======
    {name = "Espacio Network", url = "https://acp2.lorini.net:28050/stream"},
    {name = "Rocafm Clasicos Caracas", url = "http://protostar.shoutca.st:8370/"},
>>>>>>> 7d1f32cebb0f314e8136a3afc632dac88694d724
}

return stations
