local stations = {
    {name = [[1009 Play FM]], url = [[https://us-b4-p-e-cg11-audio.cdn.mdstrm.com/live-audio-aw/5c8d6406f98fbf269f57c82c?aid=5c58a34e176c2c0813b22e4b&pid=Ql4AZKEuVpQM2Jpoecpv6WD3zPUjAB3w&sid=EYmy5HhBuX32ghmNxUQ3DSFWf8Ea6bSw&uid=OMy2xYVLOifVKkwrcb4kiWw2W4ICBTii&es=us-b4-p-e-cg11-audio.cdn.mdstrm.com&ote=1724946954406&ot=lDMX9lFvGUqJONslsCIkzA&proto=https&pz=us&cP=128000&awCollectionId=5c58a34e176c2c0813b22e4b&liveId=5c8d6406f98fbf269f57c82c&listenerId=OMy2xYVLOifVKkwrcb4kiWw2W4ICBTii]]},
    {name = [[13C]], url = [[https://us-b4-p-e-qg12-audio.cdn.mdstrm.com/live-audio-aw/5c915497c6fd7c085b29169d/playlist.m3u8]]},
    {name = [[13C Radio]], url = [[https://us-b4-p-e-qg12-audio.cdn.mdstrm.com/live-audio-aw/5c915497c6fd7c085b29169d/playlist.m3u8?aid=5c58a34e176c2c0813b22e4b&pid=SHtgF6zFcapLyZYKr17jXZPbjHLhPe8v&sid=7FYDeaRBwks6XwPtwLmd82XYedTzSGYC&uid=emr2dfysWscIx8TzIC6qvpmEoIj3CdPr&es=us-b4-p-e-qg12-audio.cdn.mdstrm.com&ote=1724926344007&ot=Cr6idWBqlCM5dBP4GnVDxQ&proto=https&pz=us&cP=128000&awCollectionId=5c58a34e176c2c0813b22e4b&liveId=5c915497c6fd7c085b29169d&listenerId=emr2dfysWscIx8TzIC6qvpmEoIj3CdPr]]},
    {name = [[80Sflashback Radio]], url = [[https://c23.radioboss.fm:8129/stream]]},
    {name = [[Activa]], url = [[http://27393.live.streamtheworld.com/ACTIVA_SC]]},
    {name = [[Actual Fm]], url = [[http://archi-us.digitalproserver.com/actual.aac]]},
    {name = [[ADN]], url = [[https://27413.live.streamtheworld.com/ADNAAC.aac]]},
    {name = [[ADN Radio]], url = [[https://19793.live.streamtheworld.com:443/ADNAAC.aac]]},
    {name = [[AE Radio]], url = [[https://tls-cl.cdnz.cl/aeradio/live/playlist.m3u8]]},
    {name = [[Almeyda]], url = [[https://sonic.streamingchilenos.com/9974/stream.aac]]},
    {name = [[Alta Fidelidad Radio]], url = [[https://s21.myradiostream.com/:14464/;?type=http&nocache=1724080980?0.022147003328686576]]},
    {name = [[Alternativa FM]], url = [[https://radio.tvstream.cl/8056/stream]]},
    {name = [[Alternativa FM Caldera Bahía Inglesa 1013]], url = [[http://stream-176.zeno.fm/ax3kqn9f31zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJheDNrcW45ZjMxenV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IldDNGczcGhfVGpDR2s5R1VPVGFvbkEiLCJpYXQiOjE3MjQ4NDMwMTEsImV4cCI6MTcyNDg0MzA3MX0.sTYxAy_V2GkzNcoPrK_SveRLs8qEgCrTKyD6PerQ4YU]]},
    {name = [[BEAT FM - La Radio Que Te Mueve - Valle Aconcagua 987]], url = [[https://audio.streaminghd.cl:2000/stream/beatfm-sanfelipe]]},
    {name = [[Beethoven - Santiago FM]], url = [[https://unlimited4-us.dps.live/beethovenfm/aac/icecast.audio]]},
    {name = [[Beethoven FM Relanzada]], url = [[http://unlimited3-cl.dps.live/beethovenfm/gotardis/audio/now/livestream1.m3u8]]},
    {name = [[Beethovenfm]], url = [[https://unlimited3-cl.dps.live/beethovenfm/go/audio/now/livestream1.m3u8]]},
    {name = [[Bio Bio Valparaíso]], url = [[http://unlimited11-cl.dps.live/biobiovalparaiso/aac/icecast.audio]]},
    {name = [[Bío-Bío Concepción 981]], url = [[https://unlimited3-cl.dps.live/biobioconcepcion/aac/icecast.audio]]},
    {name = [[Bío-Bío Los Ángeles 967]], url = [[https://unlimited11-cl.dps.live/biobiolosangeles/aac/icecast.audio]]},
    {name = [[Biobio Chile]], url = [[https://unlimited3-cl.dps.live/biobiosantiago/aac/icecast.audio]]},
    {name = [[Blaster Radio]], url = [[https://s2.mkservers.space/blaster/]]},
    {name = [[Blu FM 949]], url = [[https://sonic.nnw.cl:7009/;]]},
    {name = [[Bonita]], url = [[https://sonicpanel.chileservidores.cl/8032/stream]]},
    {name = [[Boogaclub]], url = [[http://stream-176.zeno.fm/777prr0xfm8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI3NzdwcnIweGZtOHV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImlTb3BjM2p3U1FDV0pqcWFDMEc2Z1EiLCJpYXQiOjE3MjQ4MTg3NjMsImV4cCI6MTcyNDgxODgyM30.fL-xVydrRXHNrL6ZlumIodpwwz27aD9HBF8BXv9k1KI]]},
    {name = [[C Y S Dalcahue]], url = [[http://streaming.chiloestreaming.com:9542/]]},
    {name = [[Carabineros De Chile Radio]], url = [[https://sonic01.instainternet.com/8374/stream]]},
    {name = [[Carnaval Aconcagua]], url = [[http://sonando.us.digitalproserver.com/carnaval_aconcagua.aac]]},
    {name = [[Carnaval Curicó]], url = [[http://sonando.us.digitalproserver.com/carnaval_curico.aac]]},
    {name = [[Carnaval Punta Arenas]], url = [[http://sonando.us.digitalproserver.com/carnaval_puntaarenas.aac]]},
    {name = [[Carnaval Quillota]], url = [[http://sonando.us.digitalproserver.com/carnaval_quillota.aac]]},
    {name = [[Carnaval San Antonio]], url = [[http://sonando.us.digitalproserver.com/carnaval_sanantonio.aac]]},
    {name = [[Carnaval Viña Del Mar]], url = [[http://sonando.us.digitalproserver.com/carnaval_vinadelmar.aac]]},
    {name = [[Chercan Radio]], url = [[https://stream-172.zeno.fm/es9h0crh74zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJlczloMGNyaDc0enV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlVObkMzLWZ1U2tpelJxbUZfaDJXR1EiLCJpYXQiOjE3MjQ4MzE4MjQsImV4cCI6MTcyNDgzMTg4NH0.4VFKjHsjYXP4eSfAgwNrhc5w6fz6TUcewE3EkDZ4yw4]]},
    {name = [[City Radio POP]], url = [[http://cityradio.ddns.net:8000/citypop]]},
    {name = [[CITYRADIO - CHILE]], url = [[http://cityradio.ddns.net:8000/cityradio48flac]]},
    {name = [[CLG Radio 935 FM]], url = [[https://sonic.portalfoxmix.club/8012/streamstream]]},
    {name = [[CLUB DANCE CHILE]], url = [[https://audio.bitsur.cl/8002/stream]]},
    {name = [[Cobrox Radio]], url = [[http://65.108.120.179:8672/cobroxradio]]},
    {name = [[Código Metal Radio]], url = [[https://streaming.viphosting.cl/8012/stream]]},
    {name = [[Concierto]], url = [[http://27433.live.streamtheworld.com/CONCIERTO_SC]]},
    {name = [[Conexion Radio]], url = [[https://tunein.radiomaniacos.cl/conexionradio]]},
    {name = [[Contemporánea]], url = [[http://sonando.us.digitalproserver.com/contemporanea_aconcagua.aac]]},
    {name = [[Cooperativa]], url = [[https://unlimited3-cl.dps.live/cooperativafm/mp3/icecast.audio]]},
    {name = [[Corazon]], url = [[http://24483.live.streamtheworld.com:3690/CORAZON_SC]]},
    {name = [[CQX PMONTT]], url = [[http://5.9.65.9:8083/stream]]},
    {name = [[CQX-OSORNO]], url = [[http://5.9.65.9:8065/stream]]},
    {name = [[Cys Radio 963 FM Dalcahue]], url = [[http://streaming.chiloestreaming.com:9542/;]]},
    {name = [[De Culto Radio]], url = [[https://ascl.denial.cl:8014/stream]]},
    {name = [[De Los Recuerdos]], url = [[http://sonando.us.digitalproserver.com/fmdelosrecuerdos.aac]]},
    {name = [[Desierto FM]], url = [[https://broadcast.radio247.net/radio/8100/stream]]},
    {name = [[Diferencia FM 893]], url = [[https://sonic-cl.streaming-chile.com/8092/stream]]},
    {name = [[Digital 1041 FM - ARICA]], url = [[https://radio.digitalfm.cl:8000/arica]]},
    {name = [[Digital 1055 FM - CONCEPCIÓN]], url = [[https://radio.digitalfm.cl:8000/concepcion1]]},
    {name = [[Digital 1055 FM - TALCA]], url = [[https://radio.digitalfm.cl:8000/talca]]},
    {name = [[Digital 895 FM - CALAMA]], url = [[https://radio.digitalfm.cl:8000/calama1]]},
    {name = [[Digital 949 FM - VALPARAISO]], url = [[https://radio.digitalfm.cl:8000/valparaiso1]]},
    {name = [[Digital 971 FM - ANTOFAGASTA]], url = [[https://radio.digitalfm.cl:8000/antofagasta1]]},
    {name = [[Digital 977 FM - LA SERENA]], url = [[https://radio.digitalfm.cl:8000/laserena1]]},
    {name = [[Digital 991 FM - IQUIQUE]], url = [[https://radio.digitalfm.cl:8000/iquique1]]},
    {name = [[Digital 991 FM - PUNTA ARENAS]], url = [[https://radio.digitalfm.cl:8000/ptaarenas]]},
    {name = [[Digital FM]], url = [[https://unlimited11-cl.dps.live/digitalfm/aac/icecast.audio]]},
    {name = [[Distorsión FM]], url = [[https://tunein.radiomaniacos.cl/distorsion.mp3]]},
    {name = [[DJS EN ACCION CLUB]], url = [[https://cast3.asurahosting.com/proxy/djsenacc/stream]]},
    {name = [[Duna]], url = [[https://hls-audio-cl-1-isp.dps.live/duna/gotardis/audio/now/livestream1.m3u8]]},
    {name = [[Ecos Del Litoral]], url = [[https://studio19.radiolize.com/radio/8030/radio.mp3]]},
    {name = [[El Conquistador Fm Santiago]], url = [[https://stream10.usastreams.com/9314/stream/]]},
    {name = [[En La Noticia Radio 1011 FM]], url = [[http://streaming.chiloestreaming.com:9920/;]]},
    {name = [[Estacion Araucanìa - Temuco 943 FM]], url = [[https://sonic.wmchile.cl/8010/stream]]},
    {name = [[ESTACION DEL PODER]], url = [[http://stream-172.zeno.fm/t7cdutykw38uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ0N2NkdXR5a3czOHV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImxhTjJWelNPU0l1NXp0WXRDWUpiYWciLCJpYXQiOjE3MjQ4NTIyMzcsImV4cCI6MTcyNDg1MjI5N30.kO-2mBcHtCaaWiIkvu7a7wq9I8nJqW4l3lf4JPyFwVM]]},
    {name = [[Estación FM 931]], url = [[http://sonic.streamingchilenos.com:9902/;]]},
    {name = [[ESTRELLA DEL MAR]], url = [[https://streaming.chiloestreaming.com/9626/;]]},
    {name = [[Europa Beat]], url = [[https://s4.radio.co/s13e4f2090/listen]]},
    {name = [[Exa FM]], url = [[https://27063.live.streamtheworld.com:443/XHPSFMAAC.aac]]},
    {name = [[Exitos La Popular]], url = [[https://servers58.com/proxy/sc_relpcl?mp=/;&1578827059272]]},
    {name = [[Exitosa]], url = [[https://stream-160.zeno.fm/dg69bex4gxquv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJkZzY5YmV4NGd4cXV2IiwiaG9zdCI6InN0cmVhbS0xNjAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjgyMktIU21wVFVTc3pwV09tM0xBbmciLCJpYXQiOjE3MjQ4NDQwODAsImV4cCI6MTcyNDg0NDE0MH0.Q0xipUenfe1rrPbnp7TvQaG1Btaz4k2rq_XuZ85jP7k]]},
    {name = [[Fanatica CHILL]], url = [[http://ascl.denial.cl:8004/]]},
    {name = [[Fanatica DANCE]], url = [[http://ascl.denial.cl:8030/]]},
    {name = [[Fanatica INDIE]], url = [[http://ascl.denial.cl:8008/]]},
    {name = [[Fanatica POP]], url = [[http://ascl.denial.cl:8010/]]},
    {name = [[Fanática UNO]], url = [[http://ascl.denial.cl:8042/;]]},
    {name = [[Femenina FM]], url = [[http://archi-us.digitalproserver.com/femenina.aac]]},
    {name = [[Festival]], url = [[https://stream.festival.cl/1]]},
    {name = [[FM Dos]], url = [[http://24283.live.streamtheworld.com:3690/FMDOSAAC_SC]]},
    {name = [[FM Okey]], url = [[https://streaming.fmokey.cl/moviles.mp3]]},
    {name = [[FM Oyeme]], url = [[https://sonic.portalfoxmix.club/8128/stream]]},
    {name = [[FM Siete Rock]], url = [[https://sp1.streamingssl.com/8036/stream]]},
    {name = [[Frecuencia Rock 953]], url = [[http://audio.streaminghd.cl:9206/stream]]},
    {name = [[Futuro]], url = [[http://26663.live.streamtheworld.com/FUTUROAAC_SC]]},
    {name = [[FUTURO Chile]], url = [[https://24233.live.streamtheworld.com:443/FUTUROAAC.aac]]},
    {name = [[Gothic Metal Radio Chile]], url = [[http://209.126.107.182:8298/stream]]},
    {name = [[Guitarra Clásica]], url = [[http://stream-174.zeno.fm/qbhvtm7tzwzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJxYmh2dG03dHp3enV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InZhUTFXODNYU0ZtbmZLUXJwOC1EdmciLCJpYXQiOjE3MjQ4NTQzMDgsImV4cCI6MTcyNDg1NDM2OH0.gMDU8zK7A5R62KvgQJYa7I2dyq6Tm9c6e2g3Up2sRs0]]},
    {name = [[Guitarra Clásica Latam]], url = [[http://stream-173.zeno.fm/y3428vcm6yzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ5MzQyOHZjbTZ5enV2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InBFbnlxeWtGVGhpQ3dWR0dXLUtYZFEiLCJpYXQiOjE3MjQ3OTc0MzUsImV4cCI6MTcyNDc5NzQ5NX0.N1URlfL0bEFSTvH6IIVkC_f_l3xBd7D0i_Q3_jWCjf8]]},
    {name = [[Imagina]], url = [[http://27443.live.streamtheworld.com/IMAGINA_SC]]},
    {name = [[Impacto 80]], url = [[https://sonic.streamingchilenos.com/8228/;]]},
    {name = [[Insular FM]], url = [[https://sonic-us.streaming-chile.com:7023/live]]},
    {name = [[Isadora]], url = [[https://streaming.comunicacioneschile.net/9326/stream.aac]]},
    {name = [[Isla Negra]], url = [[https://radioislanegra.org/radio/8000/basic.aac]]},
    {name = [[Isla Negra Slowbeat]], url = [[https://radioislanegra.org/radio/8010/basic.aac]]},
    {name = [[Isla Negra Upbeat]], url = [[https://radioislanegra.org/radio/8030/basic.aac]]},
    {name = [[Jazz Y Más]], url = [[https://sonic-us.streaming-chile.com/8208/stream]]},
    {name = [[La Clave 929FM]], url = [[https://unlimited1-cl-isp.dps.live/laclavetv/laclavetv.smil/playlist.m3u8]]},
    {name = [[La Discusión]], url = [[http://archi-us.digitalproserver.com/la-discusion-fm.aac]]},
    {name = [[La Jaula Del Mono Radioactiva 19032023 - Tramo De 02:00 A 03:00\N\N]], url = [[https://sdmedia.radioactiva.cl/radioactiva/2023/3/19/activa_lajauladelmonoradioactiva_20230319_020000_030000.mp3?dist=radioactiva_cl-web-aod_play]]},
    {name = [[La Karibeña Chile]], url = [[http://5.9.65.9:8028/sanvicente]]},
    {name = [[La Más Kaliente]], url = [[https://audio1stream.com/8002/stream]]},
    {name = [[La Mega Fm]], url = [[https://sonic.portalfoxmix.club/8478/stream]]},
    {name = [[La Melinkana FM]], url = [[https://audio3.tustreaming.cl/7050/stream]]},
    {name = [[La Mexicana 953 San Vicente]], url = [[http://audio0.tustreaming.cl:7160/aire]]},
    {name = [[La Mexicana Chile]], url = [[https://audio0.tustreaming.cl/7170/casablanca]]},
    {name = [[La Retro 80S Chile]], url = [[https://s2.radio.co:80/s9ecef4f68/listen]]},
    {name = [[La Voz Del Cipres De Las Guaitecas]], url = [[https://live.lavozdelcipres.cl/radiomelinka.ogv]]},
    {name = [[Laretro]], url = [[http://s2.radio.co/s9ecef4f68/listen]]},
    {name = [[Libelulachilecl]], url = [[https://streaming.viphosting.cl/8278/;]]},
    {name = [[Libelulachilecom Señal 1]], url = [[https://streaming.viphosting.cl:7138/;]]},
    {name = [[Libelulachilecom Señal 2]], url = [[https://streaming.viphosting.cl:7124/;]]},
    {name = [[Libelulachilecom Señal 3]], url = [[https://streaming.viphosting.cl:7125/;]]},
    {name = [[Libelulachilecom Señal 4 Tangos Y Algo Más]], url = [[https://streaming.viphosting.cl:7126/;]]},
    {name = [[Llacolén]], url = [[http://sonando.us.digitalproserver.com/radiollacolen.aac]]},
    {name = [[Los 40 Principales Chile]], url = [[http://24253.live.streamtheworld.com/LOS40_CHILE_SC]]},
    {name = [[LOS40 Chile]], url = [[https://26493.live.streamtheworld.com:443/LOS40_CHILEAAC.aac]]},
    {name = [[Macarena]], url = [[https://sonic01.zglobalhost.com:7013/stream]]},
    {name = [[Maray]], url = [[https://video.mediawebchile.com:2000/stream/8212/stream]]},
    {name = [[María]], url = [[http://dreamsiteradiocp4.com:8024/]]},
    {name = [[Mi Radio]], url = [[https://audio1.tustreaming.cl/9020/stream]]},
    {name = [[Musicoop]], url = [[https://sonic.portalfoxmix.club/8486/stream]]},
    {name = [[Nostalgica]], url = [[https://unlimited5-us.dps.live/nostalgica/aac/icecast.audio]]},
    {name = [[NUEVO STYLO CHILOE]], url = [[http://stream-153.zeno.fm/nzk58p79b9quv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJuems1OHA3OWI5cXV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InBTVGlVa0RsUUptMkFoNzkwTV9ldkEiLCJpYXQiOjE3MjQ4MzY3NzIsImV4cCI6MTcyNDgzNjgzMn0.k76Jc8iJlSAA6jTVygYwWnB_BK472fjcVY3ygWCv0Jk]]},
    {name = [[Oasis FM Chile]], url = [[https://us-b4-p-e-qg12-audio.cdn.mdstrm.com/live-audio-aw/5c915497c6fd7c085b29169d/playlist.m3u8?aid=5c58a34e176c2c0813b22e4b&pid=wCfsPvJIKeNJWIZKGnixBD7JGoyaALrT&sid=6GRbZPqz1zcUgbwJhL8TPipntujGkOOt&uid=yPpLQftHX2fUMjokRv7g8FVJhqtBqYxd&es=us-b4-p-e-qg12-audio.cdn.mdstrm.com&ote=1724901258365&ot=VI964H2qJcZkQTFlrCLaYQ&proto=https&pz=us&cP=128000&awCollectionId=5c58a34e176c2c0813b22e4b&liveId=5c915497c6fd7c085b29169d&listenerId=yPpLQftHX2fUMjokRv7g8FVJhqtBqYxd]]},
    {name = [[Oceano FM La Serena Y Coquimbo]], url = [[https://audio2.tustreaming.cl/9025/stream]]},
    {name = [[Pampa Y Mar FM 1023 – Región De Tarapacá]], url = [[https://sp1.streamingssl.com/8052/stream]]},
    {name = [[Pirinola]], url = [[http://curiosity.shoutca.st:6451/autodj]]},
    {name = [[Polarisima FM]], url = [[https://cdn1.onstream.audio:8085/stream]]},
    {name = [[Portales Digital]], url = [[https://stream.polarhost.cl/portalesdigital]]},
    {name = [[Positiva]], url = [[https://unlimited4-us.dps.live/positiva/aac/icecast.audio]]},
    {name = [[Positiva FM]], url = [[http://unlimited4-us.dps.live/positiva/aac/icecast.audio]]},
    {name = [[Principios Radio]], url = [[https://stream-168.zeno.fm/i5darmt2oi7tv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJpNWRhcm10Mm9pN3R2IiwiaG9zdCI6InN0cmVhbS0xNjguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkVyZnhRbFNFU1lPeVF6dHJxa05za0EiLCJpYXQiOjE3MjQ4NTQ2NzcsImV4cCI6MTcyNDg1NDczN30.yBOWGgbebbSqMviEwU4liL8ub0r96hlmX48wcapAZH4]]},
    {name = [[Pudahuel]], url = [[http://26583.live.streamtheworld.com/PUDAHUEL_SC]]},
    {name = [[Radio]], url = [[https://panelradio.online:19008/aac]]},
    {name = [[Radio Estacion Del Poder]], url = [[http://stream-172.zeno.fm/t7cdutykw38uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ0N2NkdXR5a3czOHV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkgyZE4wSGRWUzN1VWYzaTFlckJ1amciLCJpYXQiOjE3MjQ4MTE2MzQsImV4cCI6MTcyNDgxMTY5NH0.yU7bynkz_PYEKX9l52SKvLZwuYXa3extg2yPbl98kRM]]},
    {name = [[Radio 18 De Octubre]], url = [[http://stream-172.zeno.fm/vyuyg4n18vzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ2eXV5ZzRuMTh2enV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjR1OGxDemZIVHdHVXRYLS1OTlJ0bEEiLCJpYXQiOjE3MjQ4MzA4MzcsImV4cCI6MTcyNDgzMDg5N30.DoEn1GQDMsnxd_KH87nKGdnbjQsqD9FFIp5Y7Uifivk]]},
    {name = [[RADIO 24-7 CHILE]], url = [[https://broadcast.radio247.net/radio/8000/;]]},
    {name = [[RADIO ACTIVA 925 Cl]], url = [[http://stream-155.zeno.fm/pvs6hqz3crtvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwdnM2aHF6M2NydHZ2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlgtSzBrVERqVGQ2aUtBSENqcXdYTEEiLCJpYXQiOjE3MjQ4MDM4OTEsImV4cCI6MTcyNDgwMzk1MX0.tb9SBPzYB0GEVGuSzfMbF1BOg9kQf6TOpnudKiS9BaQ]]},
    {name = [[RADIO ACTIVA 925]], url = [[http://stream-157.zeno.fm/pvs6hqz3crtvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwdnM2aHF6M2NydHZ2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjF2R2JYN1RBUVdxOGlZU2U5SDFLOUEiLCJpYXQiOjE3MjQ4MDM0NjUsImV4cCI6MTcyNDgwMzUyNX0.WYRvXDErXzQaVgk6GmZQ3NNP2kH9rdB1Ifv_KNNoGiw]]},
    {name = [[RADIO ACTIVA 925°]], url = [[http://stream-158.zeno.fm/pvs6hqz3crtvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwdnM2aHF6M2NydHZ2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjkxR3loRDVWU3llME5mOVg4cEhYeEEiLCJpYXQiOjE3MjQ4NjI2NDIsImV4cCI6MTcyNDg2MjcwMn0.2ft7X_aelI_3ZEhXFjOHIo6rWXiF0j94THg_wnTAUuE]]},
    {name = [[Radio Agricultura]], url = [[http://unlimited4-us.dps.live/agricultura/mp3/icecast.audio?]]},
    {name = [[Radio Agricultura Santiago]], url = [[http://unlimited4-us.dps.live/agricultura/mp3/icecast.audio]]},
    {name = [[Radio Alegría Del Transporte 907 FM]], url = [[http://streaming01.xhost.cl/8048/;]]},
    {name = [[Radio Amiga De Talca]], url = [[http://archi-us.digitalproserver.com/amiga.aac]]},
    {name = [[Radio Amiga Fm 1007]], url = [[https://audio-edge-5bkfj.fra.h.radiomast.io/aff8c0f0-5d0c-41d6-83b2-71daff574701]]},
    {name = [[Radio Amistad 1019 FM]], url = [[https://audio.jcrdmedia.com/8018/stream]]},
    {name = [[Radio Arcoiris FM 993]], url = [[https://audio2.tustreaming.cl/7210/stream]]},
    {name = [[Radio Armonía Oficina]], url = [[http://encoder.armoniaoficina.cl:3032/1.mp3]]},
    {name = [[Radio Austral CD97]], url = [[http://archi-us.digitalproserver.com/austral.aac]]},
    {name = [[Radio Bahía Caldera]], url = [[https://sonic.sistemahost.es/8020/stream]]},
    {name = [[Radio Barquito FM]], url = [[https://centova.streaming-chile.com/proxy/radiobarquito?mp=/radiobarquito_live]]},
    {name = [[Radio BBN]], url = [[https://audio-edge-es6pf.mia.g.radiomast.io/475ebed1-595e-4717-b888-64fe8fc6b09f]]},
    {name = [[RADIO BEETHOVEN]], url = [[https://unlimited5-us.dps.live/beethovenfm/gotardis/audio/now/livestream1.m3u8]]},
    {name = [[Radio Beethoven FM]], url = [[http://unlimited4-us.dps.live/beethovenfm/aac/icecast.audio]]},
    {name = [[Radio Bio Bio]], url = [[https://unlimited3-cl.dps.live/biobiosantiago/mp3/icecast.audio]]},
    {name = [[Radio Bio Bio Temuco]], url = [[https://unlimited3-cl.dps.live/biobiotemuco/aac/icecast.audio]]},
    {name = [[Radio Bio-Bio Puerto Montt]], url = [[https://unlimited3-cl.dps.live/biobiopuertomontt/mp3/icecast.audio]]},
    {name = [[Radio Biobio Valparaiso]], url = [[http://unlimited3-cl.dps.live/biobiovalparaiso/mp3/icecast.audio]]},
    {name = [[Radio Canina]], url = [[https://us-b4-p-e-zs14-audio.cdn.mdstrm.com/live-audio/601dd58c5fcd44672749652a/601de1cd07ba40129dbcd35e/icecast.audio?aid=601dd58c5fcd44672749652a&pid=2CO9pwN2IMQXqyZOMVy0UqbZ8B8VuFSZ&sid=A6SqTOIEKLsqnabujBWlE27cEDtvrPFE&uid=NZM7MUDbxDx8QcrusxpSEtcQiY1COefs&es=us-b4-p-e-zs14-audio.cdn.mdstrm.com&ote=1724947553881&ot=Mis_K110fkIDabzMdN63hQ&proto=https&pz=us&cP=128000]]},
    {name = [[Radio Caracol]], url = [[http://sonando.us.digitalproserver.com/caracol590.aac]]},
    {name = [[Radio Caramelo 913 FM]], url = [[https://audio5.tustreaming.cl/8004/stream]]},
    {name = [[Radio Caribe FM 955]], url = [[http://149.56.241.149:8118/stream]]},
    {name = [[RADIO CARICIA FM]], url = [[https://sonic.portalfoxmix.club/8244/stream/]]},
    {name = [[RADIO CAROLINA Cl]], url = [[http://stream-158.zeno.fm/sri2de2qdlivv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJzcmkyZGUycWRsaXZ2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjhyYVQ3ME9oU0ZXcmVHMllSeXg0eXciLCJpYXQiOjE3MjQ4NDMyOTcsImV4cCI6MTcyNDg0MzM1N30.riFiDz73tVuFb4gvf-USfGOr9rcHlS0g3jsrGVSziJo]]},
    {name = [[Radio Catalina]], url = [[https://streaming.comunicacioneschile.net/9398/stream/]]},
    {name = [[Radio Central Clasista De Trabajadores]], url = [[http://stream-176.zeno.fm/m5fw6rwx2tzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJtNWZ3NnJ3eDJ0enV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjZUcVB6aDM5UzR5d2hrQ2xfV2NHbnciLCJpYXQiOjE3MjQ4MTk1NTMsImV4cCI6MTcyNDgxOTYxM30.-zA04fbNUDUHPhBByk5oz06VECvq4m4nGc1X0WuR3Zo]]},
    {name = [[Radio Centro Cristiano]], url = [[https://vivo.miradio.in:7008/]]},
    {name = [[Radio Club 80]], url = [[https://stream.radioclub80.cl:8002/clasicos80.mp3]]},
    {name = [[Radio Cobremar - Chañaral FM 899]], url = [[https://audio.bitsur.cl/8066/stream]]},
    {name = [[Radio Colocolo]], url = [[https://audio2.tustreaming.cl:10997/stream]]},
    {name = [[Radio Colombina]], url = [[https://cast.radioservicios.cl:8314/radio]]},
    {name = [[Radio Cómplices]], url = [[https://streaming.comunicacioneschile.net:7007/;]]},
    {name = [[Radio Concierto Chile]], url = [[https://24483.live.streamtheworld.com:443/CONCIERTOAAC.aac]]},
    {name = [[Radio Contacto]], url = [[https://streaming.comunicacioneschile.net/8038/stream]]},
    {name = [[Radio Contexto Ñuble]], url = [[https://streaming.viphosting.cl/8028/stream]]},
    {name = [[Radio Contigo]], url = [[http://streaming.comunicacioneschile.net:9318/stream]]},
    {name = [[Radio Cordillera Pinto]], url = [[https://stream-151.zeno.fm/u33nhd4bf2zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ1MzNuaGQ0YmYyenV2IiwiaG9zdCI6InN0cmVhbS0xNTEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InMwcjZSdm9vUV9LNkpPaXFzWXlJUkEiLCJpYXQiOjE3MjQ4NjE3NjksImV4cCI6MTcyNDg2MTgyOX0.xojAXGye02dy7_1gD9jCNDuJoZH0f3l-oE0ClpLSjF8]]},
    {name = [[Radio Crystal Cabildo 1019]], url = [[https://radiolatina.live/9980/;]]},
    {name = [[Radio Crystal La Ligua 1053 FM]], url = [[https://radiolatina.live/9984/;]]},
    {name = [[Radio Crystal Petorca 1023 FM]], url = [[https://stm2.srvif.com:8024/stream]]},
    {name = [[Radio Crystal San Felipe 1065 FM]], url = [[https://radiolatina.live/9982/;]]},
    {name = [[Radio Definitiva]], url = [[http://192.198.83.230:8772/;]]},
    {name = [[Radio Destino]], url = [[http://radio.streemlion.com:3780/stream]]},
    {name = [[Radio Dinámica 1007 FM]], url = [[https://streaming.comunicacioneschile.net/8030/stream]]},
    {name = [[Radio Dinámica Digital 1033 FM]], url = [[https://panelradio.online:18882/mp3]]},
    {name = [[Radio Disney - Santiago FM 953]], url = [[https://21933.live.streamtheworld.com:443/DISNEY_CHI_SA_ADP.aac]]},
    {name = [[Radio Dixi 1069 FM]], url = [[https://sonic.portalfoxmix.cl/9940/stream]]},
    {name = [[Radio Dulce 953 En La Ligua]], url = [[https://stream-164.zeno.fm/3yv0enxnp7zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIzeXYwZW54bnA3enV2IiwiaG9zdCI6InN0cmVhbS0xNjQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IldDREQ4RkcwUnBDQ3owaWlac2xCd1EiLCJpYXQiOjE3MjQ4MDgyMzYsImV4cCI6MTcyNDgwODI5Nn0.XVkTljcEq8dfgDNh9EkYZ5sMCAcCzMniHNueQroMenY]]},
    {name = [[Radio Dulce CALERA - QUILLOTA 957 FM]], url = [[https://stream-158.zeno.fm/bx6zuwssrnjvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJieDZ6dXdzc3JuanZ2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjlmN09pX3RmU0FHNTZaTkxwTUwxaHciLCJpYXQiOjE3MjQ4MDcxNjEsImV4cCI6MTcyNDgwNzIyMX0.M3C0D_Tg7jCul01rT_RMzcqVyDkTefmOvN5iMeZvBqE]]},
    {name = [[Radio Dulce CASABLANCA 979 FM]], url = [[https://stream-163.zeno.fm/yo6udiulqhbvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ5bzZ1ZGl1bHFoYnZ2IiwiaG9zdCI6InN0cmVhbS0xNjMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkdFeGdyRnNlUUp5bzZ2Qm43dmNWLUEiLCJpYXQiOjE3MjQ4MDgyMzAsImV4cCI6MTcyNDgwODI5MH0.1WKwPFq7ZIHNWOMnz_vfS3EoL4ZvMFX54gBrdAia_DI]]},
    {name = [[Radio Dulce ILLAPEL 983 FM]], url = [[https://stream-155.zeno.fm/kc5hofr05tavv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJrYzVob2ZyMDV0YXZ2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkJyYjlkVnhjUVJ5OXNkTG1VdDdiVnciLCJpYXQiOjE3MjQ4MTE5OTUsImV4cCI6MTcyNDgxMjA1NX0.pQlzwDWgLUp9YCbYqdkUBQz08nS93aLP72CEzVwmeXY]]},
    {name = [[Radio Dulce LA LIGUA - PAPUDO ZAPALLAR 953 FM]], url = [[https://stream-162.zeno.fm/3yv0enxnp7zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIzeXYwZW54bnA3enV2IiwiaG9zdCI6InN0cmVhbS0xNjIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjY0dG9UWG4zUzRXZXludi1iM182MUEiLCJpYXQiOjE3MjQ4NTk2NzgsImV4cCI6MTcyNDg1OTczOH0.Be9dCFs5BXSGCFWcUc-i2khll6CmowoZdoCfroHFsto]]},
    {name = [[Radio Dulce LLAY-LLAY 1019 FM]], url = [[http://200.24.229.253:8240/stream/9/;]]},
    {name = [[Radio Dulce PETORCA- -CABILDO 1047 FM]], url = [[https://stream-155.zeno.fm/uftblekcpxguv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ1ZnRibGVrY3B4Z3V2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImNGVlk0Tmx2UUZhU0pBT0NZdlI4QXciLCJpYXQiOjE3MjQ4MDk3ODgsImV4cCI6MTcyNDgwOTg0OH0.V3w5-GPmDwmHzr8WIGPzKKUACBJqiKvo__uRIc3SIG8]]},
    {name = [[Radio Dulce SAN FELIPE Y LOS ANDES 1003 FM]], url = [[https://stream-156.zeno.fm/dzvavezs85ouv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJkenZhdmV6czg1b3V2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImVTcl9IdHNyU2NpYVdJeDQwMTVHSWciLCJpYXQiOjE3MjQ4MDU0OTksImV4cCI6MTcyNDgwNTU1OX0.cEefTUUjSRKfq0bhj0qSj0pDhU5sCp2FOC7hnfA1gEw]]},
    {name = [[Radio Ecos Del Valle]], url = [[https://streaming.chiloestreaming.com:10946/;]]},
    {name = [[Radio El Carbón]], url = [[https://unlimited11-cl.dps.live/elcarbon/aac/icecast.audio]]},
    {name = [[Radio El Conquistador]], url = [[https://stream10.usastreams.com/9314/stream]]},
    {name = [[RADIO EL LOA 1011 FM]], url = [[http://us9.maindigitalstream.com:7258/stream]]},
    {name = [[Radio Emilia 1075]], url = [[https://sp001.servidoresph.com:8040/index.htmlCHUMILLASsid=1]]},
    {name = [[Radio Encanto 885 FM]], url = [[https://archi-us.digitalproserver.com/encanto_ovalle.aac]]},
    {name = [[RADIO ENTRE OLAS 931 FM]], url = [[https://archi-us.digitalproserver.com/entreolas.aac]]},
    {name = [[Radio Estación FM 931]], url = [[http://sonic.streamingchilenos.com:9902/stream]]},
    {name = [[Radio Estallido Tuitero]], url = [[https://stream-171.zeno.fm/ws9z11fhrd0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ3czl6MTFmaHJkMHV2IiwiaG9zdCI6InN0cmVhbS0xNzEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjRrMVcwUjNZUzFDeHRDVk1IcWU2S1EiLCJpYXQiOjE3MjQ4MzI4NzUsImV4cCI6MTcyNDgzMjkzNX0.l4IrFYW8jzqc3AXX1fImFjCFc9Sn6WkVSz8zW-IBhbs]]},
    {name = [[Radio Estrella Del Norte]], url = [[http://sonic.portalfoxmix.cl:8424/;]]},
    {name = [[Radio Éxitos La Popular 1061 FM]], url = [[http://livehd.cdn.felpysolutions.us/proxy/sc_relpcl]]},
    {name = [[Radio Exquisita FM]], url = [[http://ascl.denial.cl:8002/stream]]},
    {name = [[Radio FM Centro 917]], url = [[https://s02.azuracast.cl/radio/8210/fmcentro]]},
    {name = [[Radio Futuro]], url = [[https://21933.live.streamtheworld.com:443/FUTURO_SC]]},
    {name = [[Radio Fututo]], url = [[https://24363.live.streamtheworld.com:443/FUTURO_SC]]},
    {name = [[Radio Gatuna]], url = [[https://us-b4-p-e-qg12-audio.cdn.mdstrm.com/live-audio/601dd58c5fcd44672749652a/611d9db704b775082811559e/icecast.audio?aid=601dd58c5fcd44672749652a&pid=eOpIeivdZtOxkbE5TBt4mRlL0SXL24aU&sid=Yoy6G4zr6zTVBLNdoD47cWFe5ZuH2U78&uid=CoW24qTDht1IrvTDWNdsu977WkIrtmVw&es=us-b4-p-e-qg12-audio.cdn.mdstrm.com&ote=1724946418769&ot=-6VfhONlXC3KfCahPOosvA&proto=https&pz=us&cP=128000]]},
    {name = [[Radio Guayacán]], url = [[https://sonic.mallocohosting.cl/8038/stream]]},
    {name = [[Radio Iglesia Cristiana La Serena]], url = [[https://servidor32.brlogic.com:7050/live]]},
    {name = [[Radio Ignacio Serrano]], url = [[https://sonic.portalfoxmix.club/8242/stream/]]},
    {name = [[Radio Interamericana]], url = [[https://sonando-us.digitalproserver.com/radiointeramericana.aac]]},
    {name = [[RADIO ISLA ONLINE]], url = [[https://sp.totalstreaming.net:8018/stream]]},
    {name = [[Radio Islam Chile]], url = [[https://centova.neonetwork.cl:9031/live]]},
    {name = [[Radio Kurruf]], url = [[https://radio.latina.red/radiokurruf.mp3]]},
    {name = [[Radio Las Nieves]], url = [[https://audio2.tustreaming.cl:10987/stream]]},
    {name = [[Radio Lautaro Talca]], url = [[https://audio2.tustreaming.cl/7320/stream]]},
    {name = [[Radio Libra]], url = [[http://sonando.us.digitalproserver.com/libra.aac]]},
    {name = [[Radio Lola]], url = [[https://centova.neonetwork.cl:9154/stream]]},
    {name = [[RADIO MANANTIAL DE VIDA]], url = [[https://audio3.tustreaming.cl/7080/stream]]},
    {name = [[Radio Marcela]], url = [[http://archi-us.digitalproserver.com/marcelafm.aac]]},
    {name = [[RADIO MARIA CHILE]], url = [[http://dreamsiteradiocp.com:8066/stream]]},
    {name = [[RADIO MAXIMA FM +51-925691328 PERU]], url = [[https://servermax2.azuracast.com.es/listen/maximafm/antofagasta]]},
    {name = [[RADIO MAXIMA FM VALPARAISO 969 - Fono+51-925691328]], url = [[https://servermax2.azuracast.com.es/listen/maximafm/radio.mp3]]},
    {name = [[Radio Millenium Network]], url = [[http://5.9.65.9:8030/stream.aac]]},
    {name = [[Radio Nativa FM]], url = [[http://stm3.srvif.com:8090/;]]},
    {name = [[Radio Nuble 897 Fm]], url = [[http://streaming.comunicacioneschile.net:9358/;]]},
    {name = [[Radio Nuevo Mundo Ovalle]], url = [[http://192.99.16.17:8102/stream]]},
    {name = [[RADIO NUEVO S CHILOE FM]], url = [[http://stream-153.zeno.fm/nzk58p79b9quv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJuems1OHA3OWI5cXV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjBCdVA2TWYtU0lXVVlzRnRqTWk4eVEiLCJpYXQiOjE3MjQ4MTcyNTgsImV4cCI6MTcyNDgxNzMxOH0.7BReRHJDCcdTvNEasduFBgnAT1TzcGI2Zx6yQIDv4iM]]},
    {name = [[Radio Paula]], url = [[http://unlimited3-cl.dps.live/radiopaula/gotardis/audio/now/livestream1.m3u8]]},
    {name = [[Radio Paula FM - 1037 Mhz - Laja HD]], url = [[http://stream.radiopaulafm.com:8500/stream.mp3]]},
    {name = [[RADIO PAULINA]], url = [[https://sp1.streamingssl.com/8058/stream]]},
    {name = [[Radio Pauta]], url = [[https://unlimited5-us.dps.live/radiopauta/gotardis/audio/now/livestream1.m3u8]]},
    {name = [[Radio Placeres]], url = [[https://sonic.streamingchilenos.com/9856/;]]},
    {name = [[Radio Polarisima]], url = [[http://cdn1.onstream.audio:8085/autodj]]},
    {name = [[Radio Portales]], url = [[https://stream.polarhost.cl/portales_am]]},
    {name = [[Radio Porvenir]], url = [[https://stream-153.zeno.fm/q3k1bhxe468uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJxM2sxYmh4ZTQ2OHV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImRtTElqRG5sU21hZWtyR3RpcWdtUGciLCJpYXQiOjE3MjQ4MTA2MDIsImV4cCI6MTcyNDgxMDY2Mn0.BNEFZMdiNVmZE57N2kLqdmfHeSmg_s202KsZor_IsHE]]},
    {name = [[Radio Principios]], url = [[http://stream-170.zeno.fm/i5darmt2oi7tv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJpNWRhcm10Mm9pN3R2IiwiaG9zdCI6InN0cmVhbS0xNzAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik5Rcml3VTZqVGw2WncyeDFkeWZHaHciLCJpYXQiOjE3MjQ4MjUwNTIsImV4cCI6MTcyNDgyNTExMn0.qPeaF5eLynGpy7urz2wrigtcbB4uojzprn3lmGVtwHY]]},
    {name = [[Radio Pudahuel]], url = [[https://26653.live.streamtheworld.com/PUDAHUEL_SC]]},
    {name = [[Radio Rara]], url = [[http://190.3.169.87:9952/;]]},
    {name = [[Radio Refugio Limache]], url = [[http://procyon.shoutca.st:8114/stream]]},
    {name = [[Radio Remid FM Chile]], url = [[http://stream-151.zeno.fm/jj3nmqosbd3uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJqajNubXFvc2JkM3V2IiwiaG9zdCI6InN0cmVhbS0xNTEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjFMLTNZZTdHVGEybWxDV0tCZXdYX2ciLCJpYXQiOjE3MjQ4NjAwNjAsImV4cCI6MTcyNDg2MDEyMH0.yuUfVRbQpiegFahaahQz5nWo9gJj7cehrwTsbSwDTqM]]},
    {name = [[Radio Retro Online]], url = [[https://sonic.streamingchilenos.com/8138/stream]]},
    {name = [[Radio RTL]], url = [[http://radio.mediadev.cl:8090/rtl_curico]]},
    {name = [[Radio San Joaquin]], url = [[http://espora.org:8000/radiosanjoaquin.mp3]]},
    {name = [[RADIO SANFURGO]], url = [[http://176.31.241.17:7112/]]},
    {name = [[Radio Sol 977]], url = [[https://us9.maindigitalstream.com/ssl/7389]]},
    {name = [[Radio Sol Classic]], url = [[https://us9.maindigitalstream.com/ssl/radiosol]]},
    {name = [[Radio Tornagaleones]], url = [[http://tornagaleones.ddns.net:9000/stream]]},
    {name = [[Radio Toromondo]], url = [[https://cast4.ceomedia.cl/proxy/toromondo/stream]]},
    {name = [[Radio Udec]], url = [[https://audio.divalstream.com:7019/stream]]},
    {name = [[Radio Unab Chile]], url = [[https://cast4.ceomedia.cl/proxy/unab/stream]]},
    {name = [[Radio Universidad De Chile]], url = [[https://streamuchile.teslati.com/liveruch]]},
    {name = [[Radio Universidad Del Bío-Bío]], url = [[http://146.83.195.22:8000/stream.ogg]]},
    {name = [[Radio USM]], url = [[https://streamssl.eu:1288/stream?type=http&nocache=64]]},
    {name = [[Radio Vale FM CHILE]], url = [[https://sp1.streamingssl.com/8056/stream]]},
    {name = [[Radio Valentin Letelier]], url = [[https://cast235.indax.cl/8026/stream]]},
    {name = [[RADIO VALLE]], url = [[https://panelradio.online:18369/mp3]]},
    {name = [[Radio Viaducto]], url = [[http://stream-175.zeno.fm/1ame8uqs7x8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIxYW1lOHVxczd4OHV2IiwiaG9zdCI6InN0cmVhbS0xNzUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkdFcm1xUVA3UnQyU0pmRXpGcmtncXciLCJpYXQiOjE3MjQ4MDMyNTcsImV4cCI6MTcyNDgwMzMxN30.A0ZEFAMuVAExkZA0j6pZF84WjknC-kHTydorDNJBHH0]]},
    {name = [[Radio XQA5]], url = [[https://archi-us.digitalproserver.com/xqa-5.aac]]},
    {name = [[Radioactiva]], url = [[http://27323.live.streamtheworld.com/ACTIVA_SC]]},
    {name = [[Radioactiva 925 FM]], url = [[http://24223.live.streamtheworld.com/ACTIVAAAC_SC]]},
    {name = [[Radiofavoritaranchera]], url = [[https://stream-154.zeno.fm/pdlp0sxtdjkvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwZGxwMHN4dGRqa3Z2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IllJNzlEbl9sUzhPbWF0X1NuellzdkEiLCJpYXQiOjE3MjQ4NDY3NzcsImV4cCI6MTcyNDg0NjgzN30.2YLWDSQSeLOAiXym5a51hVQUqt4IowetuM232076aKY]]},
    {name = [[Radiomenap Chile]], url = [[https://sonicpanel.streaming10.net/8008/stream]]},
    {name = [[Radiomix]], url = [[https://video.mediawebchile.com:2000/stream/radiomixsc/stream]]},
    {name = [[Radios Disney Chile]], url = [[https://24493.live.streamtheworld.com/DISNEY_CHI_SA_ADP/HLS/playlist.m3u8]]},
    {name = [[Raxies FM]], url = [[https://stream-171.zeno.fm/annpmyskb4jtv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhbm5wbXlza2I0anR2IiwiaG9zdCI6InN0cmVhbS0xNzEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im9XVnRjd2t5UzZxeVJwdjY3UnI2TFEiLCJpYXQiOjE3MjQ4MzE1MTksImV4cCI6MTcyNDgzMTU3OX0.wjyeDeNL6OTcKgd7npFd_UKrbHZHn3Ew_5ASoKnTS-o]]},
    {name = [[Retro Plus]], url = [[https://scl.edge.grupoz.cl/retroplus16@grupoz.cl_retrolive/live/playlist.m3u8]]},
    {name = [[Ritmo FM]], url = [[https://sonic.portalfoxmix.cl/9976/stream]]},
    {name = [[Ritoque]], url = [[http://sonando.us.digitalproserver.com/ritoquefm_aac]]},
    {name = [[Ritoque FM]], url = [[https://archi-us.digitalproserver.com/ritoquefm_aac]]},
    {name = [[Rock Pop M]], url = [[http://27413.live.streamtheworld.com:3690/ROCK_AND_POP_SC]]},
    {name = [[Rock And Pop]], url = [[http://27263.live.streamtheworld.com/ROCK_AND_POP_SC]]},
    {name = [[Rockpop Chile]], url = [[https://21933.live.streamtheworld.com:443/ROCK_AND_POPAAC_SC]]},
    {name = [[RT Noticias]], url = [[https://audio1.tustreaming.cl/9850/stream]]},
    {name = [[Silens Clamor]], url = [[https://www.silensclamor.com/live]]},
    {name = [[Sintonizados Con Cristo Radio - IMPCH San Miguel]], url = [[https://audio.streaminghd.cl:9130/live]]},
    {name = [[Sonar 1053 FM]], url = [[https://us-b4-p-e-zs14-audio.cdn.mdstrm.com/live-audio-aw/5c915724519bce27671c4d15?aid=5c58a34e176c2c0813b22e4b&property=radiobox&pid=2fpbhaJswcOt9T61jHY432TrYlwnSoyH&sid=svOoNUIvjLGoKJhyxbyXUVNhFaeFGpL6&uid=vFCE2AEpWpdAYjhSZCietmVFu0XJMVvZ&es=us-b4-p-e-zs14-audio.cdn.mdstrm.com&ote=1724945792598&ot=lBHJU9ZrTnqwx6SwbSF0SA&proto=https&pz=us&cP=128000&awCollectionId=5c58a34e176c2c0813b22e4b&aw_0_1st.playerId=radiobox&liveId=5c915724519bce27671c4d15&propertyName=radiobox&propertyType=rss-app&listenerId=vFCE2AEpWpdAYjhSZCietmVFu0XJMVvZ]]},
    {name = [[Star Radio]], url = [[https://stream-172.zeno.fm/sowa6evoo9kvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJzb3dhNmV2b285a3Z2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjQ4R05Yc1hWU2gyb0VZUERUT285SUEiLCJpYXQiOjE3MjQ4NDc5NTgsImV4cCI6MTcyNDg0ODAxOH0.iAAWMzKMsYBJpHY975i7jOkQPFkykpncBpIJm6cuQXA]]},
    {name = [[Sunrise]], url = [[https://sonic-cl.streaming-chile.com/8044/stream]]},
    {name = [[Sunrise Dance Mix]], url = [[https://sonic-cl.streaming-chile.com/8054/stream]]},
    {name = [[Sunrise Lounge]], url = [[https://sonic-cl.streaming-chile.com/8098/stream]]},
    {name = [[Super Stereo 5]], url = [[https://audio-edge-3mayu.fra.h.radiomast.io/radioblues-flac]]},
    {name = [[Super45Fm]], url = [[https://s4.radio.co/s421105570/listen]]},
    {name = [[UCV Radio]], url = [[https://sonando-us.digitalproserver.com/ucvradio]]},
    {name = [[UCV Radio Vivan Los Lentos]], url = [[https://sonando-us.digitalproserver.com/ucvradio2]]},
    {name = [[Universidad Católica De Valparaíso]], url = [[http://sonando.us.digitalproserver.com/ucvradio]]},
    {name = [[Unlimited80S]], url = [[https://listen.radioking.com/radio/676744/stream/741724]]},
    {name = [[Vilas Radio 1001]], url = [[https://sonic.streamingchilenos.com/8072/stream]]},
    {name = [[Vilas Radio 981]], url = [[https://sonic.portalfoxmix.club/8042/stream]]},
    {name = [[VLN Radio]], url = [[https://sonando-us.digitalproserver.com/vln_lo]]},
    {name = [[World Hits Radio]], url = [[https://stream-157.zeno.fm/6vytsnbkb8zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI2dnl0c25ia2I4enV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjVPWUpZMHFwVHFHZDhRZmdFTUppTHciLCJpYXQiOjE3MjQ4NjI3ODgsImV4cCI6MTcyNDg2Mjg0OH0.BHwusJgn6o9Q9Vcr8M9lWrSeTknLlQU9DZnupb5G6RA]]},
    {name = [[Yamato]], url = [[https://on.yamato.cl/radio/8010/play]]},
}

return stations
