local stations = {
    {name = "JC La Bruja", url = "http://s7.yesstreaming.net:8040/stream?1655753305283"},
    {name = "La Radio Redonda Quito - 969 FM", url = "http://laredondafm.makrodigital.com:9560/stream"},
    {name = "La Voz De Los Caras 953 FM", url = "http://streaming.hdserver.biz:9368/stream"},
    {name = "Fabu 1057 FM", url = "https://alba-ec-fabu-fabuguayaquil.stream.mediatiquestream.com/chunks.m3u8"},
    {name = "Ecua Stereo Bohemia", url = "https://stream-172.zeno.fm/xlrqrx7wuwcvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4bHJxcng3d3V3Y3Z2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IklUd3RoTE1oUzlpallETzFNVWJrMlEiLCJpYXQiOjE3MjQ4NDk5NzUsImV4cCI6MTcyNDg1MDAzNX0.UM5ldIXfSR7LFsqnw-CQY3BO8erNgp_DjZJAtJYAgvA"},
    {name = "La Radio Redonda 993 Guayaquil", url = "https://laredondafm.makrodigital.com/stream/radiolaredondaguayaquil"},
    {name = "La Super Deportiva 917 Fm", url = "http://190.123.34.101:8001/stream"},
    {name = "Cuenca TV", url = "http://stream-157.zeno.fm/63eny6sypuhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI2M2VueTZzeXB1aHZ2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlVIdldFN0MwUkdPSDdVRVVKMTc2YWciLCJpYXQiOjE3MjQ4MDIwNTQsImV4cCI6MTcyNDgwMjExNH0.0HdEpgVF0yTQfVzY6h7EZ0I5A6wQpfTif5v0zuBOYKY"},
    {name = "Amazonas FM 921", url = "https://dattavolt.com/8346/stream"},
    {name = "Cómplice FM 997 FM", url = "https://dattavolt.com/8422/stream"},
    {name = "La Radio Redonda 969 Quito", url = "https://laredondafm.makrodigital.com/stream/radiolaredondaquito"},
    {name = "La Main Street Radios Ecuador Online", url = "https://radiolatina.info/9930/stream"},
    {name = "La Chismosa", url = "https://sp.dattavolt.com/8052/stream"},
    {name = "La M3G4", url = "http://gradio.net:8000/lam3g4"},
    {name = "OE Radio - Ondas De Esperanza", url = "http://eu1.fastcast4u.com:10936/"},
    {name = "Color Stereo 1053 FM", url = "https://cloudstream2032.conectarhosting.com/9470/;"},
    {name = "La 961 - Suprema Estacion", url = "https://dattavolt.com/8150/stream"},
    {name = "Antena Uno 905", url = "https://dattavolt.com/8202/stream"},
    {name = "Conecta 2 Radio", url = "https://radio.conecta2service.com/8060/stream"},
    {name = "Café Radio 917 FM", url = "https://usa3.lhdserver.es:8139/stream"},
    {name = "Católica Cuenca 981 FM", url = "https://radiohdstreaming.com/radio/8230/catolica"},
    {name = "Amena Radio", url = "https://srv.amenaradio.com.es/listen/amena-radio/stream"},
    {name = "Jumbo Deep Radio", url = "http://stream-158.zeno.fm/juhqepbmmxqvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJqdWhxZXBibW14cXZ2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik5CZjVGc3JTU3IyMDFTUU5GSnE4SGciLCJpYXQiOjE3MjQ4MzAwNDEsImV4cCI6MTcyNDgzMDEwMX0.J-_e-co2_Y2cRknGyirh7pGwwbmhMx8ylcHptpPUMZs"},
    {name = "LA CUMBRE RADIO", url = "https://stream-174.zeno.fm/bp7fnhwzo4bvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJicDdmbmh3em80YnZ2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlUwbE5PNjZzU0JtRU5GdVRtOEgwRVEiLCJpYXQiOjE3MjQ4NDQzNTgsImV4cCI6MTcyNDg0NDQxOH0.iFVfE57XRpfCNBVI-buIeZKsxf-7-Ui2Oy869k1qDA8"},
    {name = "Expresiun FM 1029", url = "https://usa3.lhdserver.es:8031/stream"},
    {name = "Municipal 720 AM", url = "https://grupomundodigital.com:8588/live"},
    {name = "Municipal FM 1029", url = "https://grupomundodigital.com:8577/stream"},
    {name = "La Victoria FM", url = "http://stream-174.zeno.fm/b3v617nkbrzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJiM3Y2MTdua2JyenV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Inl3amlpNHNlU2lpOWJLOUt3NW9NS1EiLCJpYXQiOjE3MjQ4NDQ5MjgsImV4cCI6MTcyNDg0NDk4OH0.I15n1Ag8poVriExEd-lKEW_wJqqDyZfcxXv4rP1N_uc"},
    {name = "La Coquetisima Online", url = "http://stream-163.zeno.fm/529kmm15gv8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI1MjlrbW0xNWd2OHV2IiwiaG9zdCI6InN0cmVhbS0xNjMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImZ3cFZiNkxXVEZXNXU0YS1ZdHdqVXciLCJpYXQiOjE3MjQ4NDQ2ODQsImV4cCI6MTcyNDg0NDc0NH0.lvVF8JDaiKXjwdYwAxxwSRmB_z5oEEFTeJ-fWh7s1IQ"},
    {name = "Area Deportiva", url = "https://cast.uncuartocomunicacion.com/listen/areadeportivafm/live"},
    {name = "Exa FM Ibarra - 939 FM - Ibarra, Ecuador", url = "https://streamingecuador.net:7030/stream"},
    {name = "Cañar Stereo 973 FM", url = "https://ecuamedios.net:10937/stream"},
    {name = "Besame", url = "http://stream-155.zeno.fm/5xq756t2gchvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI1eHE3NTZ0MmdjaHZ2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InhzUmxzcnhkUzdlQ2FIXzI5UlZWemciLCJpYXQiOjE3MjQ4MDU1MDQsImV4cCI6MTcyNDgwNTU2NH0.uGD8Qv6WWGNSTQLxwDKACEYUZY-c1r83aHDi5jHTTB0"},
    {name = "La Dinastia FM", url = "http://stream-163.zeno.fm/204egk2n5ehvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIyMDRlZ2sybjVlaHZ2IiwiaG9zdCI6InN0cmVhbS0xNjMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImxzYzdpZHp2UnBpODJJQ1pTYkxIX0EiLCJpYXQiOjE3MjQ4MTk3NDIsImV4cCI6MTcyNDgxOTgwMn0.UI1odr33LA43zxJmJLLup8Yk08w23rlExE_hWIIcfCo"},
    {name = "Corp Stereo 941", url = "http://stream-164.zeno.fm/rgbmruwhtuhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJyZ2JtcnV3aHR1aHZ2IiwiaG9zdCI6InN0cmVhbS0xNjQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkFkTHh2WXJRUXdTOGU0NmJ5WDh4VVEiLCJpYXQiOjE3MjQ4NTEwNDgsImV4cCI6MTcyNDg1MTEwOH0.iCVbtq5gFLGN1pWsvpef9VRi4H7NxyZYW97GsYa-MIE"},
    {name = "Atenas FM 957", url = "https://stream-160.zeno.fm/grqrmw9ezs8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJncnFybXc5ZXpzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImlUUkpERjhjU2ZXT0dwMkdwSEJfSlEiLCJpYXQiOjE3MjQ4MDU1NzAsImV4cCI6MTcyNDgwNTYzMH0.PB1jyk-wn9CXa-E54CiRZv2_qEGp3XlubmsC8u5_6gk"},
    {name = "La Tukka Ec", url = "http://grupomundodigital.com:8673/live"},
    {name = "Modelo 977 FM", url = "https://usa3.lhdserver.es:8197/stream"},
    {name = "Oxigeno 1005 FM", url = "https://sonic.dattalive.com/8384/stream"},
    {name = "La Voz Del Tomebamba", url = "https://streamingecuador.com:8074/lavozdeltomebamba"},
    {name = "La Radio Redonda Guayaquil", url = "https://laredondafm.makrodigital.com:9550/stream"},
    {name = "ASTRO RADIO", url = "https://stream-173.zeno.fm/ewdz55ik9xftv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJld2R6NTVpazl4ZnR2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InhjMWF6WnVxUm9lWFlCN2w5eHZaLUEiLCJpYXQiOjE3MjQ4MjY0MzksImV4cCI6MTcyNDgyNjQ5OX0.ynmMFZ5mbgOoGg7mUrTeJkSrcOJoYidG4RghhXcDe7s"},
    {name = "La Mejor Radio - 1039 FM - HCRA - Ibarra, Ecuador", url = "https://streamingecuador.net:8214/lamejor"},
    {name = "HCJB La Voz De Los Andes 893 FM", url = "https://streamingecuador.net:8287/hcjb"},
    {name = "DIBLU FM 889", url = "https://streamingecuador.net:9002/stream"},
    {name = "KCH FM Radio", url = "https://streamingecuador.net:7075/stream"},
    {name = "Armonica FM", url = "https://armonicafm.makrodigital.com:9570/stream"},
    {name = "Radio Andina", url = "https://grupomundodigital.com:8580/stream"},
    {name = "RADIO ANTENA SUR 895FM LA Señal DE ORO DESDE PONCE ENRIQUEZ", url = "https://grupomundodigital.com:8504/antenashd"},
    {name = "LV Radio Satelital FM", url = "http://stream-155.zeno.fm/ech627b6u18uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJlY2g2MjdiNnUxOHV2IiwiaG9zdCI6InN0cmVhbS0xNTUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InQ3V3huS2dPUjl5Z3pvQlJ3VDNRSWciLCJpYXQiOjE3MjQ4MzgyMDksImV4cCI6MTcyNDgzODI2OX0.ZgQTvTGUF5sBl8GRhC9c9oMWME4HaApUvjbgzLDrg7M"},
    {name = "Radio Amiga", url = "http://190.57.161.179:8000/stream"},
    {name = "Radio Aventura 1071 FM", url = "http://streaming.hdserver.biz:9424/stream"},
    {name = "Contigo Fm", url = "https://panel.innovatestream.pe:10852/stream"},
    {name = "Contigo FM 1049", url = "https://panel.innovatestream.pe:10852/;"},
    {name = "La Voz Del Tomebamba 1070 AM", url = "https://streamingecuador.net:8074/lavozdeltomebamba"},
    {name = "Radio Canela 1065 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradiotungurahua"},
    {name = "Radio Coqueta 965 FM", url = "http://cloudstream2032.conectarhosting.com:8214/;"},
    {name = "Los 40 Ecuador", url = "https://streamingecuador.com:7051/stream"},
    {name = "PM RADIO Quevedo", url = "https://as100.globalhost1.com/8010/stream"},
    {name = "Radio Canela Napo 1061 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradionapo"},
    {name = "RADIO BURBUJA BALZAR 895 FM", url = "https://stream-176.zeno.fm/1pdnsbf5w8ftv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIxcGRuc2JmNXc4ZnR2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkNUbm10dlVjVEJLczU5ZFRscjd0RnciLCJpYXQiOjE3MjQ4MzMyNjEsImV4cCI6MTcyNDgzMzMyMX0.qgIUszeK4hpVw8MUgOvs_NH69b6uBFvOCWJd7SwVWQo"},
    {name = "Radio Armonía 1001 FM", url = "https://radiohdstreaming.com/radio/8040/armonia"},
    {name = "Play FM 953", url = "https://streamingecuador.net:8008/radioplayfm"},
    {name = "Radio HCJB German", url = "http://segenswelle.de:8000/hcjb"},
    {name = "RADIO ESTELAR 1065 FM", url = "https://dattavolt.com/8152/stream"},
    {name = "Newstalk ZB Auckland", url = "https://ais-nzme.streamguys1.com/nz_002_aac"},
    {name = "Radio Makro Digital", url = "http://streamingecuador.net:7000/stream"},
    {name = "Radio 11Q 1049 FM", url = "https://streamingecuador.net:8012/radio11q"},
    {name = "Radio América 1045 FM", url = "https://streamingecuador.com:7030/stream?1657848016283"},
    {name = "Radio Antena 3 917 FM", url = "https://streamingecuador.net:9368/radioantena3"},
    {name = "RADIO IMPACTO 1079", url = "https://cast.uncuartocomunicacion.com/listen/radioimpacto/live"},
    {name = "Radio Evolución", url = "https://stream.gradio.net/evolucion"},
    {name = "Radio Maria Cuenca", url = "http://radioserver11.profesionalhosting.com:9069/stream"},
    {name = "Radio Lío", url = "https://usa3.lhdserver.es:8259/stream"},
    {name = "Radio La Metro Stereo", url = "https://alba-ec-lametro-lametro.stream.mediatiquestream.com/chunks.m3u8"},
    {name = "RADIO CALIDA 1029 FM", url = "https://streamingecuador.com:7048/stream"},
    {name = "Radio Marejada 1009 FM", url = "http://streaming.hdserver.biz:9330/stream"},
    {name = "Estelar Costa 931 FM", url = "https://sv70.ecuaradiotv.net:8000/estelarcosta"},
    {name = "Radio Canela Sucumbíos 945 FM", url = "https://canelaradio.makrodigital.com:9230//stream"},
    {name = "Radio Mokawa 939 FM", url = "http://stream.hdserver.biz:9474/stream"},
    {name = "Radio Centro 1013 FM", url = "https://streamingecuador.com:7046/stream"},
    {name = "Radio La Voz Del Tambo", url = "https://server.efrasystem.com:7068/live"},
    {name = "RADIO ECOS DE RUMIÑAHUI 889 FM", url = "https://streamingecuador.com:9040/stream"},
    {name = "Radio Elite 997 FM", url = "https://streamingecuador.net:8135/radioelite"},
    {name = "Radio Samantha 893 FM", url = "http://5.135.183.124:8153/stream"},
    {name = "Radio Sonoonda 997 FM", url = "http://5.135.183.124:8040/stream"},
    {name = "Gualaceo Stereo 927", url = "https://stream-158.zeno.fm/s74szs5uquhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJzNzRzenM1dXF1aHZ2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im1yZmlaalJNVFlXNkJKQXF2TWR2cmciLCJpYXQiOjE3MjQ4MjE2NTEsImV4cCI6MTcyNDgyMTcxMX0.-YnHsMxDvVSKeHCIuKzTLR8wbcIHplkj559kQNdmbFU"},
    {name = "Radio San Miguel 957 FM", url = "https://sonicpanel.cloudstreaming.eu/8126/stream"},
    {name = "Radio Scandalo 1037 FM", url = "http://str.manaideas.com:8000/;stream.mp3"},
    {name = "Radio La Red 1021 FM", url = "https://icecast.radiolared.com.ec/radiolared"},
    {name = "Mega St☆R Ecuador", url = "http://stream-158.zeno.fm/kc5hfz4aqs8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJrYzVoZno0YXFzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkdFWGJmTXlzUjJxLWJhX1U0RFNjZ2ciLCJpYXQiOjE3MjQ4MTk3NjEsImV4cCI6MTcyNDgxOTgyMX0.ckE585l4pVY4CwbWH8g6rzeseENNr2oKezh2xgZywPE"},
    {name = "Radio Super Sol", url = "http://streamingecuador.com:8002/radiosupersol"},
    {name = "Radio Popular 1230 AM", url = "http://stream-174.zeno.fm/py6f6znfntzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJweTZmNnpuZm50enV2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkNkS3JWSE9OU3FPVzZOYXh4cVdPWWciLCJpYXQiOjE3MjQ4NTEyNjMsImV4cCI6MTcyNDg1MTMyM30.-_OC2xkEspZebYYPxpGe6wB3U93V-h6wHDAHf82LiZg&1679303614411"},
    {name = "Radio Alegriafm", url = "https://cloudstream2032.conectarhosting.com/9376/;"},
    {name = "Radio Canela Morona Santiago 917 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradiomacas"},
    {name = "Radio Públicafm", url = "https://comep.radioca.st/stream"},
    {name = "Radio Atenas", url = "http://stream-160.zeno.fm/63feuw9ezs8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI2M2ZldXc5ZXpzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IndJUnNPako1UmxhcW1PZ1VINVJqdWciLCJpYXQiOjE3MjQ4NDk5MDEsImV4cCI6MTcyNDg0OTk2MX0.r7HyT6JHc0_araMr_8vaWLJVMcc6HXGe8OpIebZSCkA"},
    {name = "Radio Cristal 870 AM", url = "https://streaming.ecuastreaming.com/9958/stream"},
    {name = "Radio Pichincha Universal", url = "https://icecast.radiopichincha.com/radiopichincha"},
    {name = "Radio Punto Rojo 897 FM", url = "https://streamingecuador.net:9086/stream"},
    {name = "Radio Quito 760 AM", url = "https://streamingecuador.net:8332/radioquito?1679294453918"},
    {name = "Radio La Otra - 913 FM", url = "https://laotrafm.makrodigital.com/stream/laotrafmquito"},
    {name = "Radio Magica 877 Ecuador", url = "http://usa10.fastcast4u.com:1680/"},
    {name = "RCN CATOLICA NACIONAL", url = "https://dattavolt.com/8358/stream"},
    {name = "Radio Nexo", url = "http://stream-162.zeno.fm/xvyq4g94fchvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4dnlxNGc5NGZjaHZ2IiwiaG9zdCI6InN0cmVhbS0xNjIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im0zeENVQU5kUzdPa3YtNFpNRjVrYnciLCJpYXQiOjE3MjQ4MzgyMTksImV4cCI6MTcyNDgzODI3OX0.Fqq9Wv__sBeXZOH7B07mxtGCrdXX0B6ySp0dD5MWubU"},
    {name = "RADIO MARIA ECUADOR", url = "http://dreamsiteradiocp4.com:8010/stream"},
    {name = "Radio Nuevo Tiempo 921 FM", url = "https://stream.live.novotempo.com/radio/smil:rntQuitoEC.smil/playlist.m3u8"},
    {name = "Radio Corazón De Jesús FM", url = "http://stream-172.zeno.fm/cu68600hswzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJjdTY4NjAwaHN3enV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlVKcWk1NHZuVDJxQXpfeENoOWxkZ0EiLCJpYXQiOjE3MjQ4MzU1NjQsImV4cCI6MTcyNDgzNTYyNH0.7JfTB2OIiruZtcoqU-5olpgiRHtEzlxfAqKVUfmSEB0"},
    {name = "Radio Pasion", url = "http://streamingecuador.net:7500/stream"},
    {name = "Radio Olímpica 963 FM", url = "http://stream.hdserver.biz:9320/stream"},
    {name = "Radio Mágica 877 Ecuador", url = "https://usa10.fastcast4u.com:1680/;?type=http&nocache=1683302387"},
    {name = "Retro Music By Pelambre Records", url = "http://streamingecuador.net:9300/stream"},
    {name = "Exa FM 925 Ecuador", url = "http://26673.live.streamtheworld.com:3690/ECUADORAAC_SC"},
    {name = "Radio Fuego 1065 FM", url = "https://streamingecuador.net:8005/radiofuego"},
    {name = "Radio Gitana 949 FM", url = "https://s7.yesstreaming.net:8078/live"},
    {name = "RCS Imbabura Stereo", url = "http://stream-157.zeno.fm/kewgx19v438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJrZXdneDE5djQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Il9sZHNvQWtNUk11bEtva0wwVjJwR0EiLCJpYXQiOjE3MjQ4MTA3NzUsImV4cCI6MTcyNDgxMDgzNX0.2bAgGptzyBd4SLqO2TO37BmxNjYPcERSQ_terkJ7nsg"},
    {name = "Radio Vigia Fm", url = "https://streamingecuador.com:9070/radiovigia"},
    {name = "RCS Morona Santiago Stereo", url = "http://stream-160.zeno.fm/2r6uvhcw438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIycjZ1dmhjdzQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InJtd1hvSXNtVHlpZkFSRXBrOF9pMWciLCJpYXQiOjE3MjQ4NTA1NjMsImV4cCI6MTcyNDg1MDYyM30.aLUVe9eT4m_O4EN799Em8Fr5-SbOJSd_1JoAfFCY4O4"},
    {name = "RCS Orellana Stereo", url = "http://stream-162.zeno.fm/pb4351gw438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwYjQzNTFndzQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlZJMXRqbGhKVFptcjd5QndHQ21GZ2ciLCJpYXQiOjE3MjQ4MjU5MjAsImV4cCI6MTcyNDgyNTk4MH0.ynduS1zFlVGwXd5DZbXHrjr2fbJ7Vdi81rMwmni6VRE"},
    {name = "Turbo Imparable", url = "http://sonic.portalfoxmix.cl:8394/stream/;"},
    {name = "Radio Señal Pirata", url = "https://radios.sonidoshd.com/8222/stream"},
    {name = "Super 949", url = "https://dattavolt.com/8028/stream"},
    {name = "Tres Patines", url = "https://ssl.nexuscast.com:8043/;"},
    {name = "Somos Radio Familia 969", url = "https://cloudstream2030.conectarhosting.com/8206/;"},
    {name = "Radio Platinum Fm", url = "https://streamingecuador.com:8160/radioplatinum"},
    {name = "Tambo Stereo FM", url = "http://stream-159.zeno.fm/uqwrvvpvhm0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ1cXdydnZwdmhtMHV2IiwiaG9zdCI6InN0cmVhbS0xNTkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkE5U2ZXX1R0VHJTWWtzVTVYRTA0aGciLCJpYXQiOjE3MjQ4NTAxODIsImV4cCI6MTcyNDg1MDI0Mn0.Jqv0y0IxcqrizYE2IFb-OZ40AWAXB08t2WVSDcTDy1E"},
    {name = "RCS Noticias", url = "http://stream-158.zeno.fm/mz04b1exz08uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJtejA0YjFleHowOHV2IiwiaG9zdCI6InN0cmVhbS0xNTguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IldrNDZHQTVIUTlPMXZfNVlmLWgxV1EiLCJpYXQiOjE3MjQ4Mjc4OTMsImV4cCI6MTcyNDgyNzk1M30.OUqi54fb5jY_itpTv6WZeJiipcgRD1LbzegujTjF9sM"},
    {name = "Radio Ultimito Mix", url = "https://usa4.fastcast4u.com/proxy/rwrw1?mp=/1"},
    {name = "Radio Romance 901 FM", url = "https://streamingecuador.net:9090/stream"},
    {name = "Radio Son De Manta 933 FM", url = "http://grupomundodigital.com:8649/live"},
    {name = "Radio Xtrema FM", url = "https://s1.raudiostream.com:8004/stream"},
    {name = "Virgen De Guadalupe Radio", url = "http://stream-176.zeno.fm/9f0rk1re508uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5ZjByazFyZTUwOHV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InN4M0pGUWNHUlJXRlQ3QWNKcGxwZmciLCJpYXQiOjE3MjQ4MzQ0NzUsImV4cCI6MTcyNDgzNDUzNX0.1q1N-z70x6e5uGiwM-8xx6R0JmHLbgXwmCRQ41VGOP4"},
    {name = "Radio Zaracay 1005 FM", url = "http://stream-163.zeno.fm/as3xhhc0ts8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhczN4aGhjMHRzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InRoVzlmYldCVFRhVlcxaWNGT3lBYmciLCJpYXQiOjE3MjQ4MTkwMjcsImV4cCI6MTcyNDgxOTA4N30.A1IrMmS90GFADQoWZQfmRlUDj-G_ErHAApEA_ZHTtv0&_=1"},
    {name = "Radio Super Sol - 963 FM", url = "https://streamingecuador.com:8002/radiosupersol"},
    {name = "RCS Manabi Stereo", url = "http://stream-157.zeno.fm/esda9vaw438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJlc2RhOXZhdzQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ik5NQUplc0lPVHU2NG0zZ0t4RW1sbXciLCJpYXQiOjE3MjQ3NzU0NDEsImV4cCI6MTcyNDc3NTUwMX0.OvpCYuCgaE_CpXWm_fvg1-AHOWQMW0j-pnCg8BXzzQs"},
    {name = "RCS Guayas Stereo", url = "http://stream-157.zeno.fm/75b5ah2v438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI3NWI1YWgydjQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImJDZUtBaDkwVGtLMEdXVlIyd3BTTWciLCJpYXQiOjE3MjQ3ODkzODgsImV4cCI6MTcyNDc4OTQ0OH0.yJ5XDQGeEq3HFEhvdwfZeoPZP2AOukL0DOr2a2PC3JQ"},
    {name = "RCS El Oro Stereo", url = "http://stream-159.zeno.fm/v4bvybbw438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ2NGJ2eWJidzQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IklHVGJoRTEwUS0ybzBOajlZaE96X1EiLCJpYXQiOjE3MjQ4MzQzMDUsImV4cCI6MTcyNDgzNDM2NX0.wAMuKv_9hRNCuqvHuF0AImj90Jl-fW1nLqqmrMY6N5I"},
    {name = "RVT Satelital 915 FM", url = "http://209.208.111.122:8000/rvtpeninsula"},
    {name = "Mega St☆R", url = "http://stream-156.zeno.fm/4xcrps37zs8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI0eGNycHMzN3pzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkVPVzRNREd6VFIyOHM4dmZydmJhVWciLCJpYXQiOjE3MjQ4MzgyMDgsImV4cCI6MTcyNDgzODI2OH0.pSvkoof80dMFx2o9FciBoF-_25bkad_o4ToIlrba2PY"},
    {name = "Radio Canela Guayas", url = "https://canelaradio.makrodigital.com/stream/canelaradioguayaquil"},
    {name = "Radio Canela Manabí 1025 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradiomanabi"},
    {name = "Tu Voz Stereo", url = "http://stream-162.zeno.fm/zy7aqxp4q98uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ6eTdhcXhwNHE5OHV2IiwiaG9zdCI6InN0cmVhbS0xNjIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlNnSlZ2SVMzUkplazB6b2szNXhOQXciLCJpYXQiOjE3MjQ4MTI3MTMsImV4cCI6MTcyNDgxMjc3M30.LRd3nnPRD8W7tci6hpRaepuIvWpvlHwNIy55oxkFmfs"},
    {name = "RSN La Indestructible", url = "https://stream-153.zeno.fm/wahxwkbdaoduv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ3YWh4d2tiZGFvZHV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InZjeS1pNTJUUWpHUzd2aGV5bGhMTnciLCJpYXQiOjE3MjQ4Mjk0MDAsImV4cCI6MTcyNDgyOTQ2MH0.s_ZleKHf1ePwV40khBDlDjne0j4ZEEvrI_QxZx-vy3o"},
    {name = "RTP 965 FM", url = "https://streamingecuador.net:8167/radiotropicana"},
    {name = "RNC La Mundialista 1033 FM AAC", url = "https://streamingecuador.net:7008/radiornc"},
    {name = "Radio HCJB German 32Kbps", url = "http://segenswelle.de:8000/hcjb-aac"},
    {name = "Radio Cadena Stereo Country", url = "http://stream-160.zeno.fm/wyr2sxuito5vv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ3eXIyc3h1aXRvNXZ2IiwiaG9zdCI6InN0cmVhbS0xNjAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im5mMWtoWGppUlpxdks5OHR2MmxWcEEiLCJpYXQiOjE3MjQ4NDc4NDIsImV4cCI6MTcyNDg0NzkwMn0.G3u3WlFohcmzm3BKIhhhWnXWhQF4_R9tMiYiRPiLBx8"},
    {name = "Radio Gaviota 1051 FM", url = "https://streamingecuador.net:9000/radiogaviota"},
    {name = "RCS Quito Stereo", url = "http://stream-161.zeno.fm/p6dy80yt6s8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwNmR5ODB5dDZzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjFBT29pbUdHUS1XeVNZNldpem01eWciLCJpYXQiOjE3MjQ4MzY0NDUsImV4cCI6MTcyNDgzNjUwNX0.OvENU71-R4rPnp2nwPro9UiM0Bn_-vGt88KoWufOP9w"},
    {name = "RADIO TURBO", url = "https://streamingecuador.com/stream/radioturboambato"},
    {name = "Radio Onda Positiva 941 FM", url = "https://streamingecuador.net:8011/radioondapositiva"},
    {name = "Radio Cadena Stereo 1071", url = "http://stream-159.zeno.fm/10g8v80ta2zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIxMGc4djgwdGEyenV2IiwiaG9zdCI6InN0cmVhbS0xNTkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjhuWmRYNnFFUUVDbWhaYUFYWU1WdmciLCJpYXQiOjE3MjQ3Nzg5OTYsImV4cCI6MTcyNDc3OTA1Nn0.w78oZW0hEht0TQWaU4syFTslZJCvBbt0CWpSwmlJRx0"},
    {name = "Radio Rumba", url = "https://streamingecuador.net:8078/radiorumbanetwork"},
    {name = "Radio Tambo Mix", url = "https://stream-172.zeno.fm/gey7t9er11zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJnZXk3dDllcjExenV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im90SzV1YWhZUVN5SEs4NHRGOXVwdWciLCJpYXQiOjE3MjQ3NzEyNzIsImV4cCI6MTcyNDc3MTMzMn0.wauyUCwO7_sRJQjdufSfcJ9xLN2cRlx9q1DrUR8NUSs"},
    {name = "RADIO VALLE FM", url = "http://stream-152.zeno.fm/veu31437sm0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ2ZXUzMTQzN3NtMHV2IiwiaG9zdCI6InN0cmVhbS0xNTIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IndaTTlkOFZiUkJxcUFjaGIzaHJLOFEiLCJpYXQiOjE3MjQ4NDU2MzgsImV4cCI6MTcyNDg0NTY5OH0.9x2WKb8mcAvcGcdGmMwfON2wh4uc3T4D0RktnXFamH0"},
    {name = "RCS Mix", url = "http://stream-176.zeno.fm/17qka9nun2zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIxN3FrYTludW4yenV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkRXeXhqaE9EUXRHMWhEQVdxZWZGSEEiLCJpYXQiOjE3MjQ3Njg5ODgsImV4cCI6MTcyNDc2OTA0OH0.n3WHv64jxEq8xgzyO880K-mlUNucoBW6hLPDws7UkaQ"},
    {name = "RCS Chimborazo Stereo", url = "http://stream-161.zeno.fm/epr9867v438uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJlcHI5ODY3djQzOHV2IiwiaG9zdCI6InN0cmVhbS0xNjEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InVfX1d5N0sxUjN1RVp2a2tjcklsaVEiLCJpYXQiOjE3MjQ4NDExNTYsImV4cCI6MTcyNDg0MTIxNn0.35dngqZWBQ4FmxIZOvP8ycDs22YzfP6HIqRZu_Eghus"},
    {name = "San Fernando FM", url = "http://stream-161.zeno.fm/gqn5xf0fd18uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJncW41eGYwZmQxOHV2IiwiaG9zdCI6InN0cmVhbS0xNjEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkxpQUFXeWlIU1Rld2RtMVN2R2RoTmciLCJpYXQiOjE3MjQ4MDI1NDMsImV4cCI6MTcyNDgwMjYwM30.cCdzutVgJN75LRUKQE5sQHYmmQc4RTCxHOFQ8CX3IU0"},
    {name = "Radio Canela El Oro 1007 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradiomachala"},
    {name = "Radio Canela Azuay 1073 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradiocuenca"},
    {name = "Radio Canela Chimborazo 945 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradiochimborazo"},
    {name = "Radio Canela Loja 969 - 989 FM", url = "https://canelaradio.makrodigital.com/stream/canelaloja"},
    {name = "Radio Canela Imbabura 927 FM", url = "https://canelaradio.makrodigital.com/stream/canelaradioibarra"},
    {name = "Pagma Stereo FM \Alausi\", url = "http://stream-154.zeno.fm/tqwu1sku9c0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ0cXd1MXNrdTljMHV2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkdPT3hHYlBqUm5Lb3FOSkxxOG9DSFEiLCJpYXQiOjE3MjQ4MDIzMTYsImV4cCI6MTcyNDgwMjM3Nn0.n7Qa6iMyc_t7B3nGoL1Hus-x65xQ1m_tytQ2mbTHiBo"},
}

return stations
