local stations = {
    {name = "Sheger FM 1021", url = "https://stream.zenolive.com/y91n1vtbaw5tv"},
    {name = "Ethio FM 1078", url = "https://stream.zeno.fm/72y045deqeruv"},
    {name = "Fm Addis 971", url = "http://stream.zeno.fm/7tzrhrap7yzuv"},
    {name = "Ahadu Radio 943 Addis Abeba", url = "https://ahaduradio.com/station/983/?play=1"},
    {name = "Jano FM", url = "https://stream-54.zeno.fm/1cyn1as4v68uv?zs=6ALEcBPQR5Wq6_T-zr8TDw"},
    {name = "FM ADDIS 97-1", url = "https://stream.zeno.fm/rb6wbrap7yzuv"},
    {name = "TIRITA 976 FM", url = "https://stream.zeno.fm/x751reg18zhvv"},
    {name = "Voice Of Ethiopia", url = "https://node-34.zeno.fm/hubm64kkr2zuv"},
    {name = "Ethiopian Orthodox Church Mezmur", url = "https://stream.zeno.fm/pfaho9uockwuv"},
    {name = "Amharic Live Sport የኳስ ኮሜኔታተር", url = "https://stream.zeno.fm/bqtruhn4q98uv"},
    {name = "EBC NATIONAL RADIO", url = "https://stream.zeno.fm/ad402tap7yzuv"},
    {name = "Awash FM 907 Addis Abeba", url = "https://stream-161.zeno.fm/655zm6w4vc9uv"},
    {name = "Sheger FM", url = "https://stream.zeno.fm/y91n1vtbaw5tv"},
    {name = "Tizta ትዝታ FM", url = "https://stream.zeno.fm/55nlq5yzqlftv"},
    {name = "Sheger365", url = "https://stream.zeno.fm/hnx6hqn05bhvv"},
    {name = "Addis Music", url = "https://stream.zeno.fm/umguj2baxdctv"},
    {name = "Afro FM", url = "http://stream.zeno.fm/fu367ky6hkeuv"},
    {name = "Oromia Broadcasting Network", url = "https://stream.zeno.fm/9kha8gxkpd0uv"},
    {name = "Mirt Internet Radio", url = "http://stream.zeno.fm/akmuznguawzuv"},
    {name = "Addis Walta FM 1053", url = "https://stream.zeno.fm/t5td4ky6hkeuv"},
    {name = "Christian Mezmur Ethiopia", url = "https://stream.zeno.fm/0bws6ct0ey8uv"},
    {name = "Taem Radio ጣዕም ሬድዮ", url = "https://stream.zeno.fm/ffg8htkh1k0uv"},
    {name = "AXUMITE RADIO", url = "https://stream.zeno.fm/b9bn18xa2k8uv"},
    {name = "Rahel Radio", url = "https://stream.zenolive.com/vt1u6fr1h2zuv.aac"},
    {name = "Afro FM 1053", url = "https://stream.zenolive.com/t5td4ky6hkeuv.aac"},
    {name = "Yenevibe Radio", url = "https://stream.zeno.fm/5mz3qqftsnhvv"},
    {name = "Yengat Weg", url = "https://stream.zeno.fm/pp0d9hyddxquv"},
    {name = "Finfinnee Raadiyoo", url = "https://stream.zeno.fm/gtb0xm6vbm5tv"},
    {name = "Jazz Ethiopia World", url = "http://mediaserv38.live-streams.nl:8006/live"},
    {name = "Birhan Gospel Radio", url = "https://stream.zeno.fm/qt90skpqp0hvv"},
    {name = "DW Amharic", url = "https://dw.audiostream.io/dw/1027/mp3/64/dw08"},
    {name = "Betemeskel ቤተመስቀል ☦️", url = "https://stream.zeno.fm/xbpzacbw298uv"},
    {name = "Daily Hype Radio", url = "https://stream.zeno.fm/apzzddhstbruv"},
    {name = "Halaal Media", url = "https://stream.zeno.fm/rqx24qj7offvv"},
    {name = "EBC Radio 1047 Addis Abeba", url = "https://stream-25.zeno.fm/2xguamap7yzuv"},
    {name = "Voa", url = "https://voa13.akacast.akamaistream.net/7/681/437795/v1/ibb.akacast.akamaistream.net/voa13"},
    {name = "اذاعة القرآن الكريم", url = "http://stream.radiojar.com/0tpy1h0kxtzuv"},
    {name = "Hip Hop", url = "http://stream.rtlradio.de/rnb/mp3-192/"},
    {name = "Yonjon", url = "http://stream.zeno.fm/tkkjml4sqsguv"},
}

return stations
