local stations = {
    {name = "France Info", url = "http://direct.franceinfo.fr/live/franceinfo-midfi.mp3"},
    {name = "France Inter", url = "http://direct.franceinter.fr/live/franceinter-hifi.aac"},
    {name = "France Culture", url = "http://icecast.radiofrance.fr/franceculture-hifi.aac"},
    {name = "FIP", url = "http://icecast.radiofrance.fr/fip-hifi.aac"},
    {name = "RFI Afrique", url = "http://live02.rfi.fr/rfiafrique-64.mp3"},
    {name = "RMC FR", url = "https://audio.bfmtv.com/rmcradio_128.mp3"},
    {name = "Jazz Radio Blues", url = "http://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3"},
    {name = "Rfi-Chinese", url = "https://rfienchinois64k.ice.infomaniak.ch/rfienchinois-64.mp3"},
    {name = "RTL France", url = "http://streaming.radio.rtl.fr/rtl-1-44-128"},
    {name = "Nostalgie", url = "http://185.52.127.132/fr/30601/mp3_128.mp3?origine=fluxradios"},
    {name = "RFI Monde", url = "http://live02.rfi.fr/rfimonde-64.mp3"},
    {name = "Europe 1", url = "https://stream.europe1.fr/europe1.aac"},
    {name = "BFM Radio", url = "https://audio.bfmtv.com/bfmradio_128.mp3"},
    {name = "Radio Classique", url = "http://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3"},
    {name = "ABC Lounge Radio", url = "https://eu1.fastcast4u.com/proxy/kpmxz?mp=/1"},
    {name = "Jazz Radio", url = "http://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3"},
    {name = "Radio Nova", url = "http://novazz.ice.infomaniak.ch/novazz-128.mp3"},
    {name = "Eurodance 90 Radio", url = "https://stream-eurodance90.fr/radio/8000/128.mp3?1627933323"},
    {name = "Sud Radio", url = "https://ice.creacast.com/sudradio"},
    {name = "Radio Meuh", url = "http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3"},
    {name = "France Musique", url = "http://icecast.radiofrance.fr/francemusique-hifi.aac"},
    {name = "FIP Jazz", url = "http://icecast.radiofrance.fr/fipjazz-hifi.aac"},
    {name = "100% Radio 80", url = "http://100radio-80.ice.infomaniak.ch/100radio-80-128.mp3"},
    {name = "Jazz Radio Classic Jazz", url = "http://jazz-wr01.ice.infomaniak.ch/jazz-wr01-128.mp3"},
    {name = "La Grosse Radio Reggae", url = "http://hd.lagrosseradio.info/lagrosseradio-reggae-192.mp3"},
    {name = "Rfi-Afrique", url = "http://live02.rfi.fr/rfiafrique-96k.mp3"},
    {name = "FIP Reggae", url = "http://icecast.radiofrance.fr/fipreggae-hifi.aac"},
    {name = "Skyrock", url = "http://icecast.skyrock.net/s/natio_mp3_128k"},
    {name = "OUI FM", url = "https://ouifm.ice.infomaniak.ch/ouifm-high.mp3"},
    {name = "Yoga Chill", url = "http://178.32.111.41:8027/stream-128kmp3-YogaChill"},
    {name = "France Musique La Baroque", url = "http://icecast.radiofrance.fr/francemusiquebaroque-hifi.aac"},
    {name = "King Dub Radio", url = "http://london-dedicated.myautodj.com:8862/stream"},
    {name = "FIP Groove", url = "http://icecast.radiofrance.fr/fipgroove-hifi.aac"},
    {name = "Alternative Radio", url = "https://www.radioking.com/play/alternative-radio-1"},
    {name = "RFM", url = "http://stream.rfm.fr/rfm.mp3"},
    {name = "Jazz Radio Funk", url = "http://jazz-wr06.ice.infomaniak.ch/jazz-wr06-128.mp3"},
    {name = "FIP Electro", url = "http://icecast.radiofrance.fr/fipelectro-hifi.aac"},
    {name = "Radio Courtoisie", url = "https://ice.creacast.com/radio-courtoisie"},
    {name = "Chante France", url = "http://stream.chantefrance.com/Chante_France"},
    {name = "B4B Deep House", url = "http://www.b4bradio.com/flux/deep-house.m3u"},
    {name = "RTL2", url = "http://streaming.radio.rtl2.fr/rtl2-1-44-128"},
    {name = "FUN Radio", url = "http://icecast.funradio.fr/fun-1-44-128"},
    {name = "Roots Legacy Radio - Dub Radio", url = "http://rootslegacy.fr:8080/listen1"},
    {name = "* Meme Dans Les Orties *", url = "https://radio.sk8ter.org:8443/stream"},
    {name = "Generation Soul Disco Funk", url = "http://www.generationdiscofunk.com/pls/hd.m3u"},
    {name = "Chante France 80'S", url = "http://stream1.chantefrance.com/cf-80"},
    {name = "Jazz Radio Soul", url = "http://jazz-wr10.ice.infomaniak.ch/jazz-wr10-128.mp3"},
    {name = "Clazz - Radio Classique Et Jazz", url = "https://ice.creacast.com/clazz_hq_web.mp3"},
    {name = "Jazz Radio Latin Jazz", url = "http://jazz-wr09.ice.infomaniak.ch/jazz-wr09-128.mp3"},
    {name = "TSF Jazz", url = "http://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3"},
    {name = "FIP Rock", url = "http://icecast.radiofrance.fr/fiprock-hifi.aac"},
    {name = "Europe 2", url = "http://europe2.lmn.fm/europe2.mp3"},
    {name = "Reggaefr", url = "https://listen.radioking.com/radio/50473/stream/87415"},
    {name = "Pulsradio Trance", url = "http://213.251.190.165/pulstranceHD.mp3"},
    {name = "Latina Salsa", url = "http://latinasalsa.ice.infomaniak.ch/latinasalsa.mp3"},
    {name = "FM 80 Funky Music", url = "https://listen.radioking.com/radio/467555/stream/523739"},
    {name = "Algorythme Drum Bass", url = "https://radio9.pro-fhi.net/flux-endvtlna/stream"},
    {name = "Radio Libertaire France", url = "http://media.radio-libertaire.org:8080/radiolib.mp3"},
    {name = "Europe1", url = "http://stream.europe1.fr/europe1.aac"},
    {name = "FIP Pop", url = "https://icecast.radiofrance.fr/fippop-hifi.aac"},
    {name = "Chérie FM", url = "http://185.52.127.163/fr/30201/mp3_128.mp3?origine=tune-in-radio"},
    {name = "RMC Info Talk Sport", url = "https://audio.bfmtv.com/rmcradio_128.mp3?aw_0_1st.playerId=RMC_audio_web&aggregator=RMC_audio_web"},
    {name = "Galaxie New Wave", url = "https://www.radioking.com/play/galaxienewwave"},
    {name = "BFM Business", url = "http://bfmbusiness.bfmtv.com/bfmbradio-mp3"},
    {name = "ABC Lounge Jazz", url = "https://eu1.fastcast4u.com/proxy/kpmxz/stream"},
    {name = "Cinemix", url = "https://kathy.torontocast.com:1825/stream"},
    {name = "France Info Lofi", url = "http://direct.franceinfo.fr/live/franceinfo-lofi.mp3"},
    {name = "La Grosse Radio Rock", url = "http://hd.lagrosseradio.info/lagrosseradio-rock-192.mp3"},
    {name = "Coran Radio", url = "https://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABhdgGORQA-2acfyF3_4WY2g"},
    {name = "La Grosse Radio Métal", url = "http://hd.lagrosseradio.info/lagrosseradio-metal-192.mp3"},
    {name = "Le Bon Mix Hifi Flac 1411 Kbps", url = "https://stream10.xdevel.com/audio17s976748-2218/stream/icecast.audio"},
    {name = "FIP Musiques Du Monde", url = "http://icecast.radiofrance.fr/fipworld-hifi.aac"},
    {name = "Chillofi Radio: Relax Study Beats", url = "http://rdstream-0625.dez.ovh:8000/radio.mp3"},
    {name = "Radio Sympa", url = "https://radio11.pro-fhi.net:19095/stream"},
    {name = "Jazz Radio Piano Jazz", url = "http://jzr-piano.ice.infomaniak.ch/jzr-piano.mp3"},
    {name = "RFI En Español Radio Francia Internacional", url = "http://icepe1.infomaniak.ch/rfienespagnol-64.mp3"},
    {name = "B4B Radio DISCO FUNK", url = "https://eu10.fastcast4u.com:8120/"},
    {name = "Chante France 60'S", url = "http://stream.chantefrance.com/cf-60"},
    {name = "NRJ Latino Hits", url = "http://cdn.nrjaudio.fm/adwz1/fr/31409/mp3_128.mp3?origine=fluxradios"},
    {name = "Fip Monde", url = "http://direct.fipradio.fr/live/fipworld-hifi.aac"},
    {name = "Latina Reggaeton", url = "http://latinareggaeton.ice.infomaniak.ch/latinareggaeton.mp3"},
    {name = "FIP Hip Hop", url = "http://icecast.radiofrance.fr/fiphiphop-hifi.aac"},
    {name = "Jazz Radio Lounge", url = "http://jazzlounge.ice.infomaniak.ch/jazzlounge-high.mp3"},
    {name = "Generations RB", url = "http://generationfm-slowjam.ice.infomaniak.ch/generationfm-slowjam-high.mp3"},
    {name = "France Bleu Nord", url = "http://direct.francebleu.fr/live/fbnord-midfi.mp3"},
    {name = "France Musique Piano Zen", url = "http://icecast.radiofrance.fr/francemusiquepianozen-hifi.aac"},
    {name = "Generations Funk", url = "http://gene-wr05.ice.infomaniak.ch/gene-wr05.mp3"},
    {name = "La Patate Douce", url = "http://listen.radioking.com/radio/285742/stream/331753"},
    {name = "Radio Espérance Grégorien", url = "https://esperance.streamakaci.com/gregorien.mp3"},
    {name = "FIP Sacré Français", url = "http://icecast.radiofrance.fr/fipsacrefrancais-hifi.aac"},
    {name = "Frequence 3 Gold FLAC", url = "https://frequence3.net-radio.fr/frequence3gold.flac"},
    {name = "FIP Metal", url = "https://icecast.radiofrance.fr/fipmetal-hifi.aac?id=radiofrance"},
    {name = "Allzic Radio 2000S", url = "http://allzic49.ice.infomaniak.ch/allzic49.mp3"},
    {name = "France Musique La Jazz", url = "http://icecast.radiofrance.fr/francemusiquelajazz-hifi.aac"},
    {name = "Tropiques FM", url = "http://listen.radioking.com/radio/8916/stream/19088"},
    {name = "Fun Radio France", url = "http://icecast.funradio.fr/fun-1-44-128?listen=webCwsBCggNCQgLDQUGBAcGBg"},
    {name = "Rinse France", url = "https://radio10.pro-fhi.net/radio/9041/stream"},
    {name = "France Maghreb 2 Province", url = "http://francemaghreb2.ice.infomaniak.ch/francemaghreb2-high.mp3"},
    {name = "Radio Heavy Metal", url = "https://manager7.streamradio.fr:1435/stream"},
    {name = "Chante France Emotion", url = "http://stream.chantefrance.com/cf-emotion"},
    {name = "Radio 5050", url = "https://stream.radio5050.com/"},
    {name = "France Bleu Sud Lorraine", url = "http://direct.francebleu.fr/live/fbsudlorraine-midfi.mp3"},
    {name = "Chante France 70'S", url = "http://stream.chantefrance.com/cf-70"},
    {name = "France Bleu Paris", url = "http://direct.francebleu.fr/live/fb1071-midfi.mp3"},
    {name = "Morow Prog Rock Radio", url = "http://stream.fr.morow.com:8080/morow_hi.aacp"},
    {name = "Girl Power", url = "https://scoopgirls.ice.infomaniak.ch/radioscoop-girls-64.aac"},
    {name = "Jazz Radio Electro Swing", url = "http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3"},
    {name = "Latina Bachata", url = "https://latinabachata.ice.infomaniak.ch/latinabachata.mp3"},
    {name = "Radio Caroline", url = "http://radiocaroline.ice.infomaniak.ch/radiocaroline-128.mp3"},
    {name = "Radio Grenouille", url = "https://live.radiogrenouille.com:8443/live"},
    {name = "Blackbox FR", url = "https://blackbox-fr.ice.infomaniak.ch/blackbox-fr.mp3"},
    {name = "Canal Breizh", url = "http://cast.canalbreizh.bzh/canalbreizh-hd-mp3"},
    {name = "Jazz Radio Manouche", url = "http://jazz-wr02.ice.infomaniak.ch/jazz-wr02-128.mp3"},
    {name = "Fip Bordeaux", url = "http://icecast.radiofrance.fr/fipbordeaux-midfi.mp3?ID=76zqey582k"},
    {name = "Badradio 247 OG Phonk, Memphis, Houston, Trap Trill", url = "https://s2.radio.co/s2b2b68744/listen"},
    {name = "Djam Radio - Flac 1411 Kbps", url = "https://stream10.xdevel.com/audio15s976748-2280/stream/icecast.audio"},
    {name = "NRJ", url = "http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3?origine=fluxradios?1535727639539.mp3"},
    {name = "France Musique La BO", url = "http://icecast.radiofrance.fr/francemusiquelabo-hifi.aac"},
    {name = "FPP Fréquence Paris Plurielle Rfpp", url = "https://direct.rfpp.net/fpp.mp3"},
    {name = "Frequence 3", url = "http://hd.stream.frequence3.net/frequence3-256.mp3"},
    {name = "Rire Et Chansons Open Du Rire", url = "http://cdn.nrjaudio.fm/adwz1/fr/30443/mp3_128.mp3?origine=fluxradios"},
    {name = "MC Doualiya", url = "https://montecarlodoualiya128k.ice.infomaniak.ch/mc-doualiya.mp3"},
    {name = "RFM POP-ROCK", url = "https://stream.rfm.fr/rfm-wr10.aac"},
    {name = "France Musique | Classique Easy", url = "http://direct.francemusique.fr/live/francemusiqueeasyclassique-hifi.mp3"},
    {name = "Radio Ici Maintenant", url = "https://s64.radiolize.com/radio/8090/radio.mp3"},
    {name = "Jazz Radio Only Women", url = "http://jazz-wr16.ice.infomaniak.ch/jazz-wr16-128.mp3"},
    {name = "France Bleu Haute Normandie", url = "http://icecast.radiofrance.fr/fbhautenormandie-midfi.mp3"},
    {name = "123 All Classic Rock", url = "http://str4uice.streamakaci.com/4uclassicrock.mp3"},
    {name = "Le Son Parisien", url = "http://stream.lesonparisien.com/hi.mp3"},
    {name = "Phaune Radio", url = "http://stream.phauneradio.com/phaune_128"},
    {name = "Forum Angers", url = "http://webfor-angers.ice.infomaniak.ch/webfor-angers-128.mp3"},
    {name = "Jazz Radio Zen Attitude", url = "http://zen-attitude.ice.infomaniak.ch/zen-attitude.mp3"},
    {name = "Radio Galère", url = "http://www.radiogalere.org:8080/galere.mp3"},
    {name = "Radio Italopower", url = "http://www.italopower.com/stream/italopower.m3u"},
    {name = "Latcho Flamenco", url = "https://listen.radioking.com/radio/109486/stream/148513"},
    {name = "Buddha Beach", url = "https://radio4.vip-radios.fm:18054/stream-128kmp3-BuddhaBeach"},
    {name = "Radio Espérance", url = "https://esperance.streamakaci.com/esperance.mp3"},
    {name = "RFI Persian", url = "http://live02.rfi.fr/rfienpersan-64k.mp3"},
    {name = "France Musique | Concerts Radio France", url = "http://direct.francemusique.fr/live/francemusiqueconcertsradiofrance-hifi.mp3"},
    {name = "Swing FM - La Radio Du Hot-Club De Limoges", url = "http://swingfm.ice.infomaniak.ch/swingfm-128.mp3"},
    {name = "Allzic Radio Italia", url = "http://allzic35.ice.infomaniak.ch/allzic35.mp3"},
    {name = "Jazz Radio Jazz Cinema", url = "http://jzr-wr20.ice.infomaniak.ch/jzr-wr20.mp3"},
    {name = "Radio Nova Vintage", url = "http://nova-vnt.ice.infomaniak.ch/nova-vnt-128.mp3"},
    {name = "Radio Mozart", url = "https://streamingv2.shoutcast.com/Radio-Mozart"},
    {name = "ODS Radio", url = "http://ods.ice.infomaniak.ch/ods-high.mp3"},
    {name = "Yumi Co Radio", url = "https://yumicoradio.net:8443/stream"},
    {name = "D4B", url = "https://d4b.ice.infomaniak.ch/d4b-96.mp3"},
    {name = "Record Goa Psy", url = "https://radiorecord.hostingradio.ru/goa96.aacp"},
    {name = "RFI Russia", url = "https://rfiukraine.ice.infomaniak.ch/rfiukraine-96.mp3"},
    {name = "RFM 100% Français", url = "https://wr.lmn.fm/rfm-wr11.aac"},
    {name = "Crooner Radio Classic Gold", url = "http://croonerradio_classicgold.ice.infomaniak.ch/croonerradio-classicgold-midfi.mp3"},
    {name = "Generations Rap FR Gold", url = "http://gene-wr06.ice.infomaniak.ch/gene-wr06.mp3"},
    {name = "Allzic Radio Funk", url = "http://allzic08.ice.infomaniak.ch/allzic11.mp3"},
    {name = "Replay News", url = "http://replaynews.ice.infomaniak.ch/replaynews-192.mp3"},
    {name = "Generations Newjack", url = "http://generations-njs.ice.infomaniak.ch/generations-njs.mp3"},
    {name = "Radio Service", url = "http://serveur2.wanastream.com:46100/;634412117768079stream.nsv"},
    {name = "NRJ Electro", url = "http://cdn.nrjaudio.fm/adwz1/fr/55135/mp3_128.mp3"},
    {name = "SUN Hip Hop", url = "https://diffusion.lafrap.fr/sun-hip-hop.mp3"},
    {name = "Latina", url = "http://start-latina.ice.infomaniak.ch/start-latina-high.mp3"},
    {name = "OUI FM ROCK 80'S", url = "https://ouifmrock80s.ice.infomaniak.ch/ouifmeighties.mp3"},
    {name = "Radio Canut", url = "http://live.francra.org:8000/radiocanut"},
    {name = "Radio Maria France", url = "http://dreamsiteradiocp4.com:8056/"},
    {name = "Nostalgie New Wave France", url = "http://cdn.nrjaudio.fm/adwz1/fr/30703/mp3_128.mp3?origine=fluxradios"},
    {name = "Blackbox", url = "http://start-blackbox.ice.infomaniak.ch/start-blackbox-high.mp3"},
    {name = "Lamellotron", url = "https://listen.radioking.com/radio/477719/stream/534044"},
    {name = "Le Bon Mix Radio 979", url = "https://stream10.xdevel.com/audio13s976748-2017/stream/icecast.audio"},
    {name = "Radio 666", url = "https://stream2.radio666.net/remote192.aac"},
    {name = "RFI Tieng Viet", url = "http://live02.rfi.fr/rfivietnamien-96k.mp3"},
    {name = "Jazz Radio Stax And Motown", url = "http://jazz-wr15.ice.infomaniak.ch/jazz-wr15-128.mp3"},
    {name = "France Musique | Classique Plus", url = "http://direct.francemusique.fr/live/francemusiqueclassiqueplus-hifi.mp3"},
    {name = "Hag' FM", url = "https://hagfm.streamakaci.com/hagfm.mp3"},
    {name = "Le Mellotron", url = "https://www.lemellotron.com/stream"},
    {name = "France Bleu Loire Océan", url = "http://direct.francebleu.fr/live/fbloireocean-midfi.mp3"},
    {name = "MBS Good AAC 96", url = "http://mbs.ice.infomaniak.ch/mbs-96.aac"},
    {name = "SUN Soul Funk", url = "https://diffusion.lafrap.fr/sun-soul.funk.mp3"},
    {name = "OUI FM BLUES'N'ROCK", url = "https://ouifmbluesnrock.ice.infomaniak.ch/ouifmbluesnrock-128.mp3"},
    {name = "Galaxie Lounge", url = "https://www.radioking.com/play/galaxielounge"},
    {name = "Allzic Radio RB", url = "http://allzic08.ice.infomaniak.ch/allzic10.mp3"},
    {name = "Mouv' Rap Français", url = "https://icecast.radiofrance.fr/mouvrapfr-hifi.aac"},
    {name = "Radio Mix", url = "http://andromeda.shoutca.st:8427/stream"},
    {name = "Swigg", url = "https://start-adofm.ice.infomaniak.ch/start-adofm-high.mp3"},
    {name = "France Musique | La Jazz", url = "http://direct.francemusique.fr/live/francemusiquelajazz-hifi.mp3"},
    {name = "RADIO NOVA LA NUIT", url = "http://nova-ln.ice.infomaniak.ch/nova-ln-128.mp3"},
    {name = "Allzic Radio Classic", url = "http://allzic06.ice.infomaniak.ch/allzic06.mp3"},
    {name = "Jazz Radio Ladies Crooners", url = "http://jazzladiescrooners.ice.infomaniak.ch/jazzladiescrooners-high.mp3"},
    {name = "Jazz Radio Saxo Jazz", url = "http://jzr-saxo.ice.infomaniak.ch/jzr-saxo.mp3"},
    {name = "432Hz Radio", url = "http://stream.zeno.fm/er3nkny6fd0uv"},
    {name = "Crooner Radio Swing", url = "http://croonerradio_swing.ice.infomaniak.ch/croonerradio-swing-midfi.mp3"},
    {name = "Allzic Radio 80S", url = "http://allzic08.ice.infomaniak.ch/allzic08.mp3"},
    {name = "France Bleu Breizh Izel", url = "http://direct.francebleu.fr/live/fbbreizizel-midfi.mp3"},
    {name = "Allzic Classic Piano", url = "http://allzic47.ice.infomaniak.ch/allzic47.mp3"},
    {name = "Radio Pomme D'Api", url = "https://www.radiopommedapi.com/radio.aac"},
    {name = "La Grosse Tambouille", url = "https://lagrossetambouille.com//flux"},
    {name = "Radio Zinzine", url = "http://91.121.65.189:8000/3"},
    {name = "Le Grigri", url = "https://www.radioking.com/play/legrigri/273715"},
    {name = "Atlantica Oldies", url = "http://radios.topymedia.com:8052/stream/;.mp3"},
    {name = "Size Radio", url = "http://stream.radiojar.com/atr1e8aswa5tv.m3u"},
    {name = "Kif Radio", url = "http://eagle.streemlion.com:4168/stream"},
    {name = "OUI FM ROCK 90'S", url = "https://ouifmrock90s.ice.infomaniak.ch/ouifmnineties.mp3"},
    {name = "★ Radio Dijon Campus", url = "http://frequence.u-bourgogne.fr:8082/dijoncampus"},
    {name = "Kohina", url = "https://kohina.duckdns.org/icecast/stream.ogg"},
    {name = "VIRGIN RADIO FRANCE La Rock Station", url = "http://virageradio.ice.infomaniak.ch/virageradio-natio.mp3"},
    {name = "RTL 2", url = "https://icecast.rtl.fr/rtl2-1-44-128?listen=webGJmqBU59boQ7rZDjrGO5e4"},
    {name = "103 Radio", url = "http://streaming.103radio.fr/128"},
    {name = "#1 Splash Jazz", url = "https://ais-sa2.cdnstream1.com/2346_128.mp3"},
    {name = "Radio Octopus", url = "http://media.radio-octopus.org:8000/192.mp3"},
    {name = "B2B Dance Club", url = "https://www.b4bradio.com/flux/club-dance.m3u"},
    {name = "NRJ Deep House", url = "http://cdn.nrjaudio.fm/adwz1/fr/31437/mp3_128.mp3?origine=fluxradios"},
    {name = "Международное Французское Радио RFI", url = "http://live02.rfi.fr/rfirusse-96k.mp3"},
    {name = "Rire Et Chansons Blagues", url = "http://cdn.nrjaudio.fm/adwz1/fr/30411/mp3_128.mp3?origine=fluxradios"},
    {name = "Magic Radio", url = "http://mp3.magic-radio.net/flac.m3u"},
    {name = "VOLTING Radio", url = "https://player.volting.hits1radio.com/"},
    {name = "Pulsradio Hits", url = "http://193.200.43.23/hitpartyHD.mp3"},
    {name = "Radio Kerne", url = "http://radiokerne.ice.infomaniak.ch/radiokerne-192.mp3"},
    {name = "RCF Jerico Moselle", url = "http://rcf.streamakaci.com/rcf57.mp3"},
    {name = "RCF Occitanie", url = "https://rcf.streamakaci.com/rcfoccitanie.mp3"},
    {name = "Accent 4", url = "http://str0.creacast.com/accent4"},
    {name = "Allzic Radio Fitness", url = "http://allzic13.ice.infomaniak.ch/allzic13.mp3"},
    {name = "Planèta Occitània", url = "https://www.radioking.com/play/radio-planeta-occitania"},
    {name = "NRJ Toulouse", url = "http://cdn.nrjaudio.fm/audio1/fr/40011/aac_64.mp3"},
    {name = "France Bleu Armorique", url = "http://direct.francebleu.fr/live/fbarmorique-midfi.mp3"},
    {name = "FIP Jazz Hifiaac", url = "https://icecast.radiofrance.fr/fipjazz-hifi.aac"},
    {name = "France Inter La Musique D'Inter", url = "https://icecast.radiofrance.fr/franceinterlamusiqueinter-midfi.mp3"},
    {name = "Maxi France Radio", url = "https://stream.maxifrance.radio/stream"},
    {name = "Paris Chanson", url = "https://www.radioking.com/play/paris-chanson"},
    {name = "Paroles Et Musique", url = "http://www.pprb.fr:9505/mpd"},
    {name = "RFI Russe", url = "http://live02.rfi.fr/rfienrusse-64.mp3"},
    {name = "Pulsradio 80'S", url = "http://212.83.185.113/magicradioAAC64.mp3"},
    {name = "Radio Gâtine", url = "https://hosting.radiomedia.fr:1615/stream"},
    {name = "France Bleu Gard Lozère", url = "http://direct.francebleu.fr/live/fbgardlozere-midfi.mp3"},
    {name = "Crooner Radio Elvis Presley", url = "http://croonerradio_elvispresley.ice.infomaniak.ch/croonerradio-elvispresley-midfi.mp3"},
    {name = "Clubbin One", url = "https://player.clubbinone.hits1radio.com/"},
    {name = "Allzic Radio Dance Floor", url = "http://allzic07.ice.infomaniak.ch/allzic07.mp3"},
    {name = "Allzic Radio Gothique", url = "http://allzic27.ice.infomaniak.ch/allzic27.mp3"},
    {name = "Tout Nouveau, Tout FIP", url = "http://icecast.radiofrance.fr/fipnouveautes-hifi.aac"},
    {name = "Rire Et Chansons Duos", url = "http://cdn.nrjaudio.fm/adwz1/fr/55601/mp3_128.mp3?origine=fluxradios"},
    {name = "87,5 Nantes", url = "https://listen.radioking.com/radio/15130/stream/28217"},
    {name = "France Bleu Saint-Étienne Loire", url = "http://direct.francebleu.fr/live/fbstetienne-midfi.mp3"},
    {name = "France Bleu Touraine", url = "http://direct.francebleu.fr/live/fbtouraine-midfi.mp3"},
    {name = "Fréquence 3 - World FLAC", url = "https://frequence3.net-radio.fr/frequence3world.flac"},
    {name = "Rire Et Chansons Canular", url = "http://cdn.nrjaudio.fm/adwz1/fr/30413/mp3_128.mp3?origine=fluxradios"},
    {name = "Campus FM Toulouse", url = "http://live.radiocampus.org:8000/toulouse"},
    {name = "France Musique Concerts Radio France", url = "http://icecast.radiofrance.fr/francemusiqueconcertsradiofrance-hifi.aac"},
    {name = "Europaradio Jazz HD", url = "https://onair.europaradiojazz.org//radio//8000//hd"},
    {name = "Big Cactus Classic Rock", url = "http://radio12.pro-fhi.net/radio/9134/stream.mp3"},
    {name = "Alouette", url = "https://alouette.ice.infomaniak.ch/alouette-high.mp3"},
    {name = "M Radio Chansons D'Amour", url = "http://mfmwr-026.ice.infomaniak.ch/mfmwr-026.mp3"},
    {name = "Feeling Floyd Rock", url = "http://91.121.59.45:8013/stream"},
    {name = "Galaxie Vintage", url = "https://www.radioking.com/play/galaxievintage"},
    {name = "Virage Radio Rock 2000", url = "http://virage-rock-2000.ice.infomaniak.ch/virage-rock-2000.mp3"},
    {name = "Allzic Jazz Lounge", url = "http://allzic03.ice.infomaniak.ch/allzic03.mp3"},
    {name = "Allzic Radio Latino", url = "http://allzic39.ice.infomaniak.ch/allzic39.mp3"},
    {name = "Cause Commune Libre @ Toi", url = "http://vdl.stream-lat.org:8000/voixdulat_mp3"},
    {name = "Vibration 80'S", url = "http://vibration80s.ice.infomaniak.ch/vibration80s.mp3"},
    {name = "WAVE RADIO 898 Hossegor", url = "https://s34.myradiostream.com/12340/listen.mp3"},
    {name = "Chante France Nouveautés", url = "http://stream.chantefrance.com/cf-nouveautes.aac"},
    {name = "Mouv' Dancehall", url = "https://icecast.radiofrance.fr/mouvdancehall-hifi.aac"},
    {name = "Beur FM", url = "http://broadcast.infomaniak.ch/beurfm-high.mp3"},
    {name = "Mouv' - Rap US", url = "https://icecast.radiofrance.fr/mouvrapus-hifi.aac"},
    {name = "Allzic Radio Disco", url = "http://allzic36.ice.infomaniak.ch/allzic36.mp3"},
    {name = "MRADIO FRANCE", url = "http://mfm.ice.infomaniak.ch/mfm-64.aac"},
    {name = "Radio Rennes", url = "https://stream4.vestaradio.com/RADIORENNES"},
    {name = "Toutes Les Couleurs Du Trad", url = "https://my2.radiolize.com/radio/8100/radio.mp3"},
    {name = "Europe 2 Aac", url = "http://europe2.lmn.fm/europe2.aac"},
    {name = "Phare FM Louange", url = "http://str0.creacast.com/pharefm_louange"},
    {name = "Zen Online", url = "https://radio12.pro-fhi.net:19066/live"},
    {name = "EIPM", url = "https://stunnel1.cyber-streaming.com:9046/stream?type=http&nocache=30"},
    {name = "100% Radio Hit", url = "http://100radio-hit.ice.infomaniak.ch/100radio-hit-128.mp3"},
    {name = "Graffiti Urban Radio", url = "http://80.82.229.202/graffiti.mp3"},
    {name = "Starsystem FM Gérard", url = "http://radiosurle.net:8765/radiogerard"},
    {name = "Jazz Radio Jazz Fusion", url = "https://jazz-radio-fusion.ice.infomaniak.ch/jazz-radio-fusion.mp3"},
    {name = "Radio Mercure Beauvais", url = "https://live.radiomercure.fr/on-air//live"},
    {name = "Fip : Metal", url = "https://icecast.radiofrance.fr/fipmetal-hifi.aac"},
    {name = "Jazz Radio Groove", url = "http://jazz-wr08.ice.infomaniak.ch/jazz-wr08-128.mp3"},
    {name = "B4B DISCO FUNK OFFICIAL", url = "http://www.b4bradio.com/flux/dance-classics.m3u"},
    {name = "B4B CLUB DANCE OFFICIAL", url = "https://www.b4bradio.com/flux/deep-house.m3u"},
    {name = "Maxi 80", url = "http://audio1.maxi80.com/"},
    {name = "Algorythme UK Garage", url = "https://ukg.algorythmeradio.com/stream"},
    {name = "Couleurs JAZZ", url = "https://www.radioking.com/play/couleurs-jazz/216016"},
    {name = "France Bleu Orléans", url = "http://direct.francebleu.fr/live/fborleans-midfi.mp3"},
    {name = "Marianne Mélodie", url = "https://stream4.vestaradio.com/MarianneMelodie"},
    {name = "Chansons Oubliees Ou Presque", url = "https://manager7.streamradio.fr:2580/stream?1701295921862"},
    {name = "France Bleu Pays Basque", url = "http://direct.francebleu.fr/live/fbpaysbasque-midfi.mp3"},
    {name = "France Bleu Pays De Savoie", url = "http://direct.francebleu.fr/live/fbpaysdesavoie-midfi.mp3"},
    {name = "France Bleu Roussillon", url = "http://direct.francebleu.fr/live/fbroussillon-midfi.mp3"},
    {name = "OUI FM CLASSIC ROCK", url = "https://ouifm3.ice.infomaniak.ch/ouifm3.mp3"},
    {name = "Generations Reggaeton", url = "http://generations-rgton.ice.infomaniak.ch/generations-rgton.mp3"},
    {name = "France Bleu Vaucluse", url = "http://direct.francebleu.fr/live/fbvaucluse-midfi.mp3"},
    {name = "Virage Radio Rock 90", url = "http://vir-wr01.ice.infomaniak.ch/vir-wr01.mp3"},
    {name = "FREQUENCE 3 - DANCE FLAC [Powered By IKOULA] - M2 Club", url = "https://onair.net-radio.fr/frequence3dance.flac"},
    {name = "ESSENTIEL Radio", url = "http://essentielradioing.streamakaci.com/essentielradio.mp3"},
    {name = "Forum 2000", url = "http://forum2000.ice.infomaniak.ch/forum2000.mp3"},
    {name = "Cause Commune Fm", url = "https://icecast.libre-a-toi.org:8444/voixdulat_mp3"},
    {name = "Jazz Radio Contemporary Jazz", url = "http://jazz-wr05.ice.infomaniak.ch/jazz-wr05-128.mp3"},
    {name = "TEKNO1", url = "http://cressida.shoutca.st:8591/stream/1/"},
    {name = "Skyrock Klassics", url = "https://icecast.skyrock.net/s/klassiks_aac_64k?tvr_name=radiofr&tvr_section1=64aac"},
    {name = "Radio Choco", url = "https://radiochoco.com/sound"},
    {name = "PHAUNE", url = "http://stream.phauneradio.com/phaune_256"},
    {name = "Le Mouv'", url = "http://direct.mouv.fr/live/mouv-midfi.mp3"},
    {name = "Urban Hit Maroc", url = "https://urbanhitrai.ice.infomaniak.ch/urbanhitrai.mp3"},
    {name = "Radio Bonheur", url = "http://radiobonheur.ice.infomaniak.ch/radiobonheur-128-1.mp3"},
    {name = "Allzic Radio 90S", url = "http://allzic24.ice.infomaniak.ch/allzic24.mp3"},
    {name = "NRJ Bordeaux 102,4 FM", url = "http://cdn.nrjaudio.fm/audio1/fr/40001/aac_64.mp3"},
    {name = "Hits 1", url = "https://radio12.pro-fhi.net/live/Hits%201%20radio"},
    {name = "C Lab", url = "http://stream.c-lab.fr:8001/c-lab"},
    {name = "M Radio Culte Années 60 Et 70", url = "http://mfmwr-022.ice.infomaniak.ch/mfmwr-022.mp3"},
    {name = "21 RADIO DIJON", url = "http://82.64.123.204:8001/21radio"},
    {name = "Radio VINCI Autoroutes 1077 Sud Ouest", url = "http://str0.creacast.com/radio_vinci_autoroutes_3"},
    {name = "Bram FM 983", url = "https://hosting.studioradiomedia.fr:2550/stream"},
    {name = "Allzic Radio - Lounge", url = "http://allzic21.ice.infomaniak.ch/allzic21.mp3"},
    {name = "Allzic Radio Chill Out", url = "http://allzic53.ice.infomaniak.ch/allzic53.mp3"},
    {name = "100% Radio Souvenirs", url = "http://100radio-souvenirs.ice.infomaniak.ch/100radio-souvenirs-128.mp3"},
    {name = "JAZZ RADIO - Jazz Classique", url = "http://jazz-wr17.ice.infomaniak.ch/jazz-wr17-128.mp3"},
    {name = "Générations Lyon", url = "http://radiosun.ice.infomaniak.ch/radiosun-high.mp3"},
    {name = "New Morning Radio", url = "http://www.newmorning.com/newmorningradio.m3u"},
    {name = "France Musique | Ocora - Musiques Du Monde", url = "http://direct.francemusique.fr/live/francemusiqueocoramonde-hifi.mp3"},
    {name = "Radio Notre Dame", url = "https://windu.radionotredame.net/RadioNotreDame-Dab.mp3"},
    {name = "Generations", url = "http://generationfm.ice.infomaniak.ch/generationfm-high.mp3"},
    {name = "France Musique La Contemporaine", url = "http://icecast.radiofrance.fr/francemusiquelacontemporaine-hifi.aac"},
    {name = "Yiddish Pour Tous", url = "https://www.radioking.com/play/radio-yiddish-pour-tous"},
    {name = "Latina Kizomba", url = "http://latinakizomba.ice.infomaniak.ch/latinakizomba.mp3"},
    {name = "LYL Radio", url = "http://icecast.lyl.live/live"},
    {name = "RCJ", url = "http://str0.creacast.com/radio-rcj"},
    {name = "France Bleu Provence", url = "https://icecast.radiofrance.fr/fbprovence-midfi.mp3?ID=radiofrance"},
    {name = "Jazz Radio Jazzy French", url = "http://jazz-wr18.ice.infomaniak.ch/jazz-wr18-128.mp3"},
    {name = "Jazz Radio New Orleans", url = "http://jazz-wr03.ice.infomaniak.ch/jazz-wr03-128.mp3"},
    {name = "Canal B - 94Mhz", url = "http://stream.levillage.org/canalb"},
    {name = "NRJ Fiesta Latina", url = "http://cdn.nrjaudio.fm/adwz1/fr/55210/mp3_128.mp3?origine=fluxradios"},
    {name = "Galaxiemix", url = "https://fr.radioking.com/play/galaxiemix-1"},
    {name = "Akro Radio", url = "https://stream.akroradio.com:10012/AkroRadio"},
    {name = "Rock Folk Rock N Folk", url = "https://rockfolk.ice.infomaniak.ch/rockfolk.mp3"},
    {name = "M Radio Années 80", url = "http://mfm-thema.ice.infomaniak.ch/mfm-thema.mp3"},
    {name = "Generations Rap FR", url = "http://generationfm-rap.ice.infomaniak.ch/generationfm-rap-high.mp3"},
    {name = "Generations Rap US", url = "http://generationfm-underground.ice.infomaniak.ch/generationfm-underground-high.mp3"},
    {name = "Allzic Radio Classic Violon", url = "http://allzic48.ice.infomaniak.ch/allzic48.mp3"},
    {name = "France Bleu RCFM", url = "http://direct.francebleu.fr/live/fbfrequenzamora-midfi.mp3"},
    {name = "Generations Reggae", url = "http://generations-caraibes.ice.infomaniak.ch/generations-caraibes-high.mp3"},
    {name = "Alternantes", url = "http://diffusion.lafrap.fr/alternantes.mp3"},
    {name = "France Musique Classique Plus", url = "http://icecast.radiofrance.fr/francemusiqueclassiqueplus-hifi.aac"},
    {name = "Italo Radio FM", url = "http://danceradio1.shoutcaststream.com:8102/;"},
    {name = "Evasion FM Seine-Et-Marne Sud", url = "http://stream1.evasionfm.com/Sud77"},
    {name = "OÜI FM", url = "http://ouifm.ice.infomaniak.ch/ouifm-high.aac"},
    {name = "Generations RB Gold", url = "http://generations-rnb-gold.ice.infomaniak.ch/generations-rnb-gold.aac"},
    {name = "Wit FM Lounge", url = "http://witlounge.ice.infomaniak.ch/witlounge.mp3"},
    {name = "Allzic Radio Deep Disco", url = "http://allzic31.ice.infomaniak.ch/allzic31.mp3"},
    {name = "RFI Musique", url = "http://live02.rfi.fr/rfimusiquemonde-64k.mp3"},
    {name = "PBB Radio", url = "http://pbbradio.com:8001/128"},
    {name = "Tonic Radio Villefranche", url = "http://tonicradiovillefranche.ice.infomaniak.ch/tonicradiovillefranche.mp3"},
    {name = "Voltage", url = "http://start-voltage.ice.infomaniak.ch/start-voltage-high.mp3"},
    {name = "OUI FM ROCK 70'S", url = "https://ouifmrock70s.ice.infomaniak.ch/ouifmseventies.mp3"},
    {name = "Espace Dance 90", url = "http://espace-disco.ice.infomaniak.ch/espace-disco-high.aac"},
    {name = "Virage Radio", url = "http://virageradio.ice.infomaniak.ch/virageradio-high.mp3"},
    {name = "Here4Ears", url = "http://82.64.164.43:8000/stream"},
    {name = "Mydoom-666", url = "https://mydoom666.radio.fm/md666-128k"},
    {name = "Latina Fiesta", url = "https://latinafiesta.ice.infomaniak.ch/latinafiesta.mp3"},
    {name = "RTS Nîmes", url = "http://str0.creacast.com/rts-nimes"},
    {name = "Radio Espérance Enseignement", url = "https://esperance.streamakaci.com/enseignement.mp3"},
    {name = "F HITS Classics", url = "https://listen.fhits.fr/listen/f._hits_classics/fhits_classics_96.aac"},
    {name = "Allzic Radio - Zen", url = "http://allzic20.ice.infomaniak.ch/allzic20.mp3"},
    {name = "Europe 2 Hits", url = "https://europe2.lmn.fm/vr-wr4.mp3?aw_0_1st.playerid=lagardereappVirgin"},
    {name = "Sea FM", url = "https://live-seafm.fr/seafm.mp3"},
    {name = "Europe 2 New", url = "https://europe2.lmn.fm/vr-wr1.mp3?aw_0_1st.playerid=lagardereappVirgin"},
    {name = "Radio VINCI Autoroutes 1077 Auvergne Vallée Du Rhône", url = "http://str0.creacast.com/radio_vinci_autoroutes_5"},
    {name = "Le Bon Mix Dynamic - AAC192LC", url = "https://stream10.xdevel.com/audio15s976748-2112/stream/icecast.audio"},
    {name = "Generations Dance Hall", url = "http://generations-dancehall.ice.infomaniak.ch/generations-dancehall.mp3"},
    {name = "Voltage 2000", url = "http://voltage2000.ice.infomaniak.ch/voltage2000-128.mp3"},
    {name = "M Radio 2000", url = "https://mfmwr-020.ice.infomaniak.ch/mfmwr-020.mp3"},
    {name = "Alpes 1 Alpes Du Sud", url = "http://broadcast.infomaniak.ch/alpes1gap-high.mp3"},
    {name = "Nova La Plage", url = "https://nova-sm.ice.infomaniak.ch/nova-sm-128.mp3"},
    {name = "Free Dom 2", url = "http://freedomice.streamakaci.com/freedom2.mp3"},
    {name = "Génération JUL", url = "https://generations-jul.ice.infomaniak.ch/generations-jul.mp3"},
    {name = "M Radio - Nouveautés", url = "https://mfmwr-005.ice.infomaniak.ch/mfmwr-005.mp3"},
    {name = "Africa Radio Paris", url = "https://african1paris.ice.infomaniak.ch/african1paris-128.mp3"},
    {name = "47 FM", url = "http://47fm.ice.infomaniak.ch/47fm-agen.mp3"},
    {name = "Frequence Tropicale", url = "https://ecmanager2.pro-fhi.net:1640/stream"},
    {name = "Radio Evasion", url = "http://radioevasion.fr:8020/"},
    {name = "Hélène FM", url = "http://helenefm.ice.infomaniak.ch/helenefm-high.mp3"},
    {name = "Radio AC'S", url = "https://listen.radioking.com/radio/33824/stream/199675"},
    {name = "Radio Broussaille", url = "https://stream.radiobroussaille.fr:8443/broussaille-hifi"},
    {name = "M Radio N°1 Du Top 50 - Webradio", url = "http://mfmwr-007.ice.infomaniak.ch/mfmwr-007.mp3"},
    {name = "Forum", url = "http://start-forum.ice.infomaniak.ch/start-forum-high.mp3"},
    {name = "Est FM", url = "http://str0.creacast.com/estfm1"},
    {name = "Fréquence 3 Urban FLAC", url = "https://frequence3.net-radio.fr/frequence3urban.flac"},
    {name = "Radio Campus Paris", url = "https://www.radiocampusparis.org/stream/"},
    {name = "100% Radio Albi", url = "http://100radio-albi.ice.infomaniak.ch/100radio-albi-128.mp3"},
    {name = "Europe 1 Musique", url = "https://wr.lmn.fm/e1-wr5.aac?aw_0_1st.playerid=lgrdnwsRadioplayer"},
    {name = "L'Eko Des Garrigues", url = "http://91.121.159.124:8000/eko-des-garrigues-128k.mp3"},
    {name = "Galaxietek", url = "https://fr.radioking.com/play/galaxietek"},
    {name = "Soul Radio", url = "https://listen.soulradio.eu/eu"},
    {name = "Galaxie Radio", url = "https://www.radioking.com/play/galaxieradio"},
    {name = "Alouette Le Club", url = "https://alouetteleclub.ice.infomaniak.ch/alouetteleclub-128.mp3"},
    {name = "Atlantica Soleil", url = "http://radios.topymedia.com:8054/stream/;.mp3"},
    {name = "1000 Hits 90S", url = "https://c4.auracast.net:8050/;"},
    {name = "ISEKOI Radio", url = "https://isekoi-radio.com/listen/isekoi/radio.mp3"},
    {name = "Forum 90'S", url = "http://forum90s.ice.infomaniak.ch/forum90s.mp3"},
    {name = "Radio Scoop Lyon", url = "http://radioscooplyon.ice.infomaniak.ch/radioscoop-lyon-128.mp3"},
    {name = "Jazz", url = "https://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3"},
    {name = "Radio Prédication", url = "http://6302.cloudrad.io:8220/live"},
    {name = "Jazz Blues", url = "https://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3"},
    {name = "Jazz Saxo", url = "https://jzr-saxo.ice.infomaniak.ch/jzr-saxo.mp3"},
    {name = "Allzic Radio Black", url = "http://allzic04.ice.infomaniak.ch/allzic04.mp3"},
    {name = "Jazz Radio Black Music", url = "http://jazzblackmusic.ice.infomaniak.ch/jazzblackmusic-high.mp3"},
    {name = "Liberté FM", url = "https://stream.libertefm.fr/libertefm.192.mp3"},
    {name = "Néotrad", url = "http://radio6.pro-fhi.net/flux-hepcoiyb/stream"},
    {name = "Jazz Radio Happy Hour", url = "http://jazz-wr14.ice.infomaniak.ch/jazz-wr14-128.mp3"},
    {name = "Groove Cabane", url = "https://listen.radioking.com/radio/314264/stream/361499"},
    {name = "Radio Byte", url = "http://nebula.shoutca.st:8256/;"},
    {name = "FIP Groove Hifiaac", url = "https://icecast.radiofrance.fr/fipgroove-hifi.aac"},
    {name = "RJR - Radio Jeunes Reims AAC 128K", url = "https://stream.rjrradio.fr/rjr.aac"},
    {name = "RCA Nantes", url = "https://rcanantes.ice.infomaniak.ch/rcanantes-192.mp3"},
    {name = "Radio Prun'", url = "http://80.82.229.202/streamprun"},
    {name = "Hit Radio", url = "http://quasar.shoutca.st:8853/;"},
    {name = "France Bleu Besançon", url = "http://direct.francebleu.fr/live/fbbesancon-midfi.mp3"},
    {name = "Allzic Radio Rock FM", url = "https://allzic17.ice.infomaniak.ch/allzic17.mp3"},
    {name = "Radio Bach", url = "https://streamingp.shoutcast.com/Radio-Bach?lang=it-IT%2cit%3bq%3d0.9%2cen-US%3bq%3d0.8%2cen%3bq%3d0.7"},
    {name = "Radio BIP", url = "http://flux1.radiobip.fr:8000/live"},
    {name = "RFM 80", url = "http://stream.rfm.fr/rfm-wr4.mp3"},
    {name = "OUI FM ACOUSTIC", url = "https://ouifmacoustic.ice.infomaniak.ch/ouifmacoustic.mp3"},
    {name = "Vip-Radios - Healing Music", url = "http://178.32.111.41:8039/stream-128kmp3-HealingMusic"},
    {name = "100% Radio Catalogne", url = "http://100radio-perpignan.ice.infomaniak.ch/100radio-perpignan-128.mp3"},
    {name = "Nostalgie Nantes 968", url = "http://cdn.nrjaudio.fm/audio1/fr/40049/aac_64.mp3"},
    {name = "8Beats", url = "https://n10.radiojar.com/2fa4wbch308uv"},
    {name = "Radio Souvenir", url = "http://radio12.pro-fhi.net/live/RadioSouvenir.com"},
    {name = "Radio Dio", url = "https://live.aurafm.org/RadioDio"},
    {name = "RFM - La Radio Couleur", url = "https://stream.rfm.fr/rfm-wr3.aac"},
    {name = "ABC Dance", url = "https://www.radioking.com/play/abc-dance/374263"},
    {name = "Heavy1", url = "https://listen.radioking.com/radio/119653/stream/159127"},
    {name = "Bretagne 5", url = "http://bretagne5.streamakaci.com/bretagne5.mp3"},
    {name = "FIP Autour Du Groove", url = "http://direct.fipradio.fr/live/fip-webradio3.mp3"},
    {name = "Chaos Radio", url = "http://5.135.177.61:8000/;stream/1"},
    {name = "RJR - Radio Jeunes Reims MP3 128K", url = "https://stream.rjrradio.fr/rjr.mp3"},
    {name = "FIP Tout Nouveau, Tout FIP", url = "http://direct.fipradio.fr/live/fip-webradio5.mp3"},
    {name = "Allzik Disney", url = "https://allzic52.ice.infomaniak.ch/allzic52.mp3"},
    {name = "Virage Radio Rock 80", url = "http://virage-rock-80.ice.infomaniak.ch/virage-rock-80.mp3"},
    {name = "Allzic Radio Reggae", url = "http://allzic43.ice.infomaniak.ch/allzic43.mp3"},
    {name = "Redzing Radio", url = "https://redzingradio.com/stream"},
    {name = "M Radio Francophonie", url = "http://mfmwr-018.ice.infomaniak.ch/mfmwr-018.mp3"},
    {name = "Pulsradio 2000 64K AAC", url = "https://sc6.gergosnet.com:80/puls00AAC64.mp3"},
    {name = "Africa N°1", url = "http://african1paris.ice.infomaniak.ch/african1paris-64.mp3"},
    {name = "Génération Mix", url = "https://ecmanager2.pro-fhi.net/generationmix"},
    {name = "M Radio 100% Comédies Musicales", url = "http://mfmwr-014.ice.infomaniak.ch/mfmwr-014.mp3"},
    {name = "Vibration 90'S", url = "http://vibration90s.ice.infomaniak.ch/vibration90s.mp3"},
    {name = "Allzic Radio Blues", url = "http://allzic09.ice.infomaniak.ch/allzic09.mp3"},
    {name = "Radio VINCI Autoroutes 1077 Alpes Provence", url = "http://str0.creacast.com/radio_vinci_autoroutes_6"},
    {name = "Océane FM Lannion", url = "https://oceanelannion.ice.infomaniak.ch/oceanelannion-128.mp3"},
    {name = "Itrtamilradio", url = "https://radio5.pro-fhi.net/radio/9000/stream"},
    {name = "Dnbradiocom - Main Channel FR Mirror", url = "http://ildnb1.dnbradio.com:8000/dnbradio_main.mp3"},
    {name = "Hits1", url = "https://player.hd.hits1radio.com/"},
    {name = "B4B Dance Club", url = "https://eu10.fastcast4u.com:2650/"},
    {name = "France Bleu Occitanie", url = "http://direct.francebleu.fr/live/fbtoulouse-midfi.mp3"},
    {name = "Tsfjazz", url = "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3"},
    {name = "RFM Slow", url = "https://stream.rfm.fr/rfm-wr13.aac"},
    {name = "LOVE RADIO Only Love Songs 70S80S90S - Wwwloveradio", url = "https://loveradio.streamingmedia.it/france"},
    {name = "France Bleu 100% Chanson Française", url = "https://icecast.radiofrance.fr/fbchansonfrancaise-midfi.mp3"},
    {name = "Phare FM Hits", url = "http://str0.creacast.com/pharefmhits"},
    {name = "Classic FM", url = "http://classicfm.ice.infomaniak.ch/classic-fm.mp3"},
    {name = "SWEET FM ST CALAIS 72", url = "http://sweetfm-perche72.ice.infomaniak.ch/sweetfm-perche72-192.mp3"},
    {name = "Soulmet Radio", url = "http://radiart.eu:2199/tunein/soulmet.pls"},
    {name = "Adofm", url = "http://start-adofm.ice.infomaniak.ch/start-adofm-high.mp3"},
    {name = "Allzic Radio Hard Heavy", url = "http://allzic18.ice.infomaniak.ch/allzic18.mp3"},
    {name = "Europaradio Jazz", url = "https://onair.europaradiojazz.org/radio/8000/sd"},
    {name = "Vip-Radios - Time To Relax", url = "http://178.32.111.41:8048/stream-128kmp3-TimeToRelax"},
    {name = "Jazz Radio Afro", url = "https://jazz-radio-afro.ice.infomaniak.ch/jazz-radio-afro.mp3"},
    {name = "Sun Jazz", url = "http://80.82.229.202:8000/sun-jazz.mp3"},
    {name = "Fréquence 3", url = "http://ice.stream.frequence3.net/frequence3-128.mp3"},
    {name = "La Radio De Fifi", url = "http://laradiodefifi.ice.infomaniak.ch/laradiodefifi-192.mp3"},
    {name = "Radio Béton", url = "http://51.254.220.198:8000/stream.mp3"},
    {name = "All Piano Radio", url = "http://streamingp.shoutcast.com/JamendoLounge"},
    {name = "Jazzradiofr Jazz Classique", url = "https://jazz-wr17.ice.infomaniak.ch/jazz-wr17-128.mp3"},
    {name = "مختصر التفسير", url = "https://qurango.net/radio/mukhtasartafsir"},
    {name = "Croonerradio Julioiglesias", url = "http://croonerradio_julioiglesias.ice.infomaniak.ch/croonerradio-julioiglesias-midfi.mp3"},
    {name = "Retro Souvenirs Radio", url = "https://listen.radioking.com/radio/108/stream/890"},
    {name = "Jazz Piano", url = "https://jzr-piano.ice.infomaniak.ch/jzr-piano.mp3"},
    {name = "Radio Oldschool Corsica", url = "http://www.radiart.eu/tunein/radio_oldschool.pls"},
    {name = "Jazz Latin", url = "https://jazz-wr09.ice.infomaniak.ch/jazz-wr09-128.mp3"},
    {name = "Carocelt", url = "http://carocelt.ice.infomaniak.ch/carocelt-128.mp3"},
    {name = "Radio Presence Lot", url = "https://direct.radiopresence.com/radio-presence-lot"},
    {name = "RFM Lounge", url = "http://stream.rfm.fr/rfm-wr6.mp3"},
    {name = "Hotel Costes", url = "https://s3.radio.co/s39c195d74/listen"},
    {name = "Jazz Radio Gospel", url = "http://jazz-wr07.ice.infomaniak.ch/jazz-wr07-128.mp3"},
    {name = "Addict Alternative", url = "http://stream2.addictradio.net/addictalternative.mp3"},
    {name = "Radio 90 Dance", url = "http://radiart.eu:8394/live"},
    {name = "ABC Relax", url = "https://listen.abcrelax.com/"},
    {name = "Frequence Luz", url = "https://stream-ssl.radios-arra.fr:8443/frequenceluz"},
    {name = "Jazz Radio Reprises", url = "http://reprises.ice.infomaniak.ch/reprises-high.mp3"},
    {name = "Blagues Courtes", url = "https://radio.blagues-courtes.fr/stream"},
    {name = "FIP Hifiaac", url = "https://icecast.radiofrance.fr/fip-hifi.aac"},
    {name = "Jazz Radio Soul Food By DJ Philgood", url = "http://jazz-wr12.ice.infomaniak.ch/jazz-wr12-128.mp3"},
    {name = "Mouv' - 100% Mix", url = "https://icecast.radiofrance.fr/mouv100p100mix-hifi.aac"},
    {name = "Kiss FM De Saint-Tropez À Monaco", url = "http://kissfm.ice.infomaniak.ch/kissfm-128.mp3"},
    {name = "Radio Sans Pub", url = "http://live1.jupinfo.fr:8000/play"},
    {name = "Crooner Radio Dean Martin", url = "http://croonerradio_deanmartin.ice.infomaniak.ch/croonerradio-deanmartin-midfi.mp3"},
    {name = "MAXXI RMC", url = "http://2stream.dyndns.org:8000/maxxi"},
    {name = "Crooner Radio Love Romantique", url = "http://croonerradio_love.ice.infomaniak.ch/croonerradio-love-midfi.mp3"},
    {name = "Allzic Zouk", url = "http://allzic28.ice.infomaniak.ch/allzic28.mp3"},
    {name = "Mouv' Classics", url = "https://icecast.radiofrance.fr/mouvclassics-hifi.aac"},
    {name = "Jazz Swing Manouche Radio", url = "http://stream.radiojar.com/6rxpyrnzsv5tv"},
    {name = "M Radio - Tubes Du Grenier", url = "http://mfmwr-001.ice.infomaniak.ch/mfmwr-001.mp3"},
    {name = "France Bleu Isère", url = "http://direct.francebleu.fr/live/fbisere-midfi.mp3"},
    {name = "Frequence Paris Plurielle FPP", url = "http://direct.rfpp.net/fpp.mp3"},
    {name = "France Bleu Lorraine Nord", url = "http://direct.francebleu.fr/live/fblorrainenord-midfi.mp3"},
    {name = "Generations Rap US Gold", url = "http://gene-wr08.ice.infomaniak.ch/gene-wr08.mp3"},
    {name = "Radio Campus Lille", url = "http://radiocampuslille.ice.infomaniak.ch/radiocampuslille-128"},
    {name = "Radio Star VESOUL", url = "http://radiostar.ice.infomaniak.ch/radiostar-128.mp3"},
    {name = "Jade FM", url = "https://diffusion.lafrap.fr/radiochrono.mp3"},
    {name = "Radio Brony AAC+", url = "https://radiobrony.live/aac"},
    {name = "Radio44", url = "http://eu.publicssl.net:7020/"},
    {name = "Discover Trance", url = "https://uk01.discovertrance.com/;*.mp3"},
    {name = "Generations Girl", url = "http://generations-girls.ice.infomaniak.ch/generations-girls.mp3"},
    {name = "Mister Stuff", url = "http://82.64.4.42:8000/live.mp3"},
    {name = "Hit Radio Fr", url = "https://onlineradiobox.com/json/fr/hit/play?platform=web"},
    {name = "Radio Ellebore", url = "http://ellebore.ice.infomaniak.ch/playlists/ellebore-32.aac.pls"},
    {name = "Douce France", url = "https://stream.chantefrance.com/Chante_France.aac"},
    {name = "Laurent DINE IGLESIAS", url = "https://radio7.pro-fhi.net:19141/milleniumfm.mp3"},
    {name = "Pnode", url = "http://stream.p-node.org/dab.mp3"},
    {name = "M2 Rock", url = "http://live.m2stream.fr/m2rock-128.mp3"},
    {name = "Cinemusic Radio", url = "https://listen.radioking.com/radio/422/stream/62785"},
    {name = "Radio Sing Sing", url = "http://www.sing-sing-bis.org/confortaac.pls"},
    {name = "Wit FM 80'S", url = "http://wit80s.ice.infomaniak.ch/wit80s.mp3"},
    {name = "Maxi France", url = "https://sr3.publicssl.net/srv/8358/stream"},
    {name = "Mouv' R'N'B Soul", url = "https://icecast.radiofrance.fr/mouvrnb-hifi.aac"},
    {name = "Generations Soul", url = "http://gene-wr07.ice.infomaniak.ch/gene-wr07.aac"},
    {name = "Generations Freestyle", url = "http://gene-wr09.ice.infomaniak.ch/gene-wr09.aac"},
    {name = "Espace FM", url = "http://listen.radioking.com/radio/16769/stream/49487"},
    {name = "Radio Paris Obscur", url = "http://rocket.streamradio.fr:8190/stream"},
    {name = "Radio PFM", url = "https://diff.radiopfm.com/flux.mp3"},
    {name = "Europe 2 Mix Rock, Electro, Pop", url = "https://europe2.lmn.fm/vr-wr6.mp3?aw_0_1st.playerid=lagardereappVirgin"},
    {name = "Radio Secousse", url = "http://stream.secousse.org:8000/secousse"},
    {name = "La Note Picking Radio", url = "http://www.radioking.com/play/la-note-picking-radio"},
    {name = "Tsugi", url = "https://www.radioking.com/play/tsugi-radio"},
    {name = "Latina @Work", url = "https://latinawork.ice.infomaniak.ch/latinawork.mp3"},
    {name = "Radio Capsao Paris", url = "http://str0.creacast.com/capsao_j"},
    {name = "Nova Hiphop", url = "https://nova-odn.ice.infomaniak.ch/nova-odn-256.aac"},
    {name = "ALOUETTE MAINE ET LOIRE", url = "https://alouette-angers.ice.infomaniak.ch/alouette-angers-128.mp3"},
    {name = "Fréquence 7", url = "https://live.aurafm.org/Frequence7"},
    {name = "M Radio", url = "http://mfm.ice.infomaniak.ch/mfm-128.mp3"},
    {name = "Fly Foot Selecta", url = "https://manager5.streamradio.fr:1185/stream"},
    {name = "Allzic Radio Top 20", url = "http://allzic41.ice.infomaniak.ch/allzic41.mp3"},
    {name = "Allzic Radio Golds Français", url = "https://allzic30.ice.infomaniak.ch/allzic30.aac"},
    {name = "Radio VINCI Autoroutes 1077 Ouest Centre", url = "http://str0.creacast.com/radio_vinci_autoroutes_1"},
    {name = "Happyness Radio Oise", url = "https://azuracast-broadcast.happynessamiens.fr/listen/happyness_oise/player"},
    {name = "Air Connect Radio", url = "http://stream.airconnectradio.com:9003/ac192.mp3"},
    {name = "La Clé Des Ondes", url = "https://www.lacledesondes.fr/streaming?v=26"},
    {name = "Flash Musik 80S", url = "http://eu.publicssl.net:7010/32kbps"},
    {name = "NRJ Acoustic Hits", url = "http://cdn.nrjaudio.fm/adwz1/fr/30157/mp3_128.mp3"},
    {name = "Autoroute Info 1077 Zone Nord", url = "http://media.autorouteinfo.fr:8000/direct_nord.mp3"},
    {name = "Skyrock 100% FRANÇAIS", url = "https://icecast.skyrock.net/s/francais_aac_64k?tvr_name=radiofr&tvr_section1=64aac"},
    {name = "Nova Soul", url = "https://nova-soul.ice.infomaniak.ch/nova-soul-256.aac"},
    {name = "Skyrock Hits", url = "https://icecast.skyrock.net/s/hit_skyrock_aac_64k?tvr_name=radiofr&tvr_section1=64aac"},
    {name = "RSL Radio", url = "http://rslradio.ice.infomaniak.ch/rslradio-128.mp3"},
    {name = "RADIO FRANCIA INTERNACIONAL", url = "https://rfienespagnol64k.ice.infomaniak.ch/rfienespagnol-64.mp3"},
    {name = "NRJ La Playlist 100% Hits Français", url = "http://cdn.nrjaudio.fm/adwz1/fr/56699/mp3_128.mp3"},
    {name = "Enjoy 33", url = "http://radiotrg.ice.infomaniak.ch/radiotrg-high.mp3"},
    {name = "RCF Corsica", url = "http://rcf.streamakaci.com/rcf20.mp3"},
    {name = "Radio Présence Toulouse", url = "https://direct.radiopresence.com/presence"},
    {name = "Le Poste Parisien", url = "https://stream10.xdevel.com/audio12s976748-1798/stream/icecast.audio"},
    {name = "RCF Haute-Savoie", url = "http://rcf.streamakaci.com/rcf74.mp3"},
    {name = "Zebradio", url = "http://www.zebradio.fr:8000/player.mp3"},
    {name = "Radio Metal", url = "https://radio3.pro-fhi.net/live/Radio%20Metal"},
    {name = "Pulsradiocom", url = "http://icecast1.pulsradio.com:8080/pulstranceHD.mp3"},
    {name = "Fréquence 3 FLAC", url = "http://hd.stream.frequence3.net/frequence3.flac"},
    {name = "Phare FM Worship", url = "http://str30.creacast.com/pharefm_worship"},
    {name = "Radio RBS", url = "https://www.radioking.com/play/radio-rbs-1"},
    {name = "NRJ Happy Hits", url = "http://cdn.nrjaudio.fm/adwz1/fr/55127/mp3_128.mp3?origine=fluxradios"},
    {name = "VINYLTIMES", url = "https://listen.radioking.com/radio/7551/stream/385141"},
    {name = "Free FM Top100 Paris", url = "https://cosmo.streamerr.co/proxy/freefmtop/stream"},
    {name = "100% Radio Auch", url = "http://100radio-auch.ice.infomaniak.ch/100radio-auch-128.mp3"},
    {name = "Pulsrádio - França", url = "http://mp3.magic-radio.net/"},
    {name = "100% Radio Foix", url = "http://100radio-foix.ice.infomaniak.ch/100radio-foix-128.mp3"},
    {name = "Radio Equinoxe", url = "http://listen.radioking.com/radio/39218/stream/76118"},
    {name = "Europe 1 Musique Classique", url = "https://wr.lmn.fm/e1-wr3.aac?aw_0_1st.playerid=lgrdnwsRadioplayer"},
    {name = "Radio Lux", url = "http://5.39.71.39:8004/stream"},
    {name = "Wave Radio", url = "https://s34.myradiostream.com/:12340/listen.mp3"},
    {name = "LOR'FM", url = "http://lorfm.ice.infomaniak.ch/lorfm-128.mp3"},
    {name = "Fréquence 3 Urban", url = "https://frequence3.net-radio.fr/frequence3urban-128.mp3"},
    {name = "Radio Troutrou", url = "https://www.radioking.com/play/radio-troutrou/413698"},
    {name = "Virgin Radio Rock", url = "https://virginradio.ice.infomaniak.ch/virgin-radio.mp3"},
    {name = "Azot Radio", url = "https://azotradio1.ice.infomaniak.ch/azotradio1-128.mp3"},
    {name = "Jazz Only Women", url = "https://jazz-wr16.ice.infomaniak.ch/jazz-wr16-128.mp3"},
    {name = "NRJ At Work", url = "http://cdn.nrjaudio.fm/adwz1/fr/30033/mp3_128.mp3"},
    {name = "Jazz French", url = "https://jazz-wr18.ice.infomaniak.ch/jazz-wr18-128.mp3"},
    {name = "Horizon", url = "http://horizonradio-bethunelens.ice.infomaniak.ch/horizonradio-bethunelens-128"},
    {name = "Mistral FM Toulon", url = "http://mistralfm.ice.infomaniak.ch/mistralfm-high.mp3"},
    {name = "RTL", url = "https://icecast.rtl.fr/rtl-1-44-128"},
    {name = "Voltage 80'S", url = "http://voltage80s.ice.infomaniak.ch/voltage80s-128.mp3"},
    {name = "Impact FM", url = "http://impactfm.ice.infomaniak.ch/impactfm-128.mp3"},
    {name = "Voltage Lounge", url = "http://voltagelounge.ice.infomaniak.ch/voltagelounge-128.mp3"},
    {name = "Allzic Radio 50S", url = "http://allzic29.ice.infomaniak.ch/allzic29.mp3"},
    {name = "C9Radio", url = "https://stream.c9.fr/c9radio-flac.ogg.m3u"},
    {name = "France Musique Classique Easy", url = "http://icecast.radiofrance.fr/francemusiqueeasyclassique-hifi.aac"},
    {name = "Pure Vintage Radio", url = "http://www.radioking.com/play/pure-vintage-radio"},
    {name = "Jazz Radio Groov'Up", url = "http://jazz-wr13.ice.infomaniak.ch/jazz-wr13-128.mp3"},
    {name = "CLASSIC HITS RADIO", url = "http://www.play4.fr/play4-club.mp3"},
    {name = "Muzaiko", url = "http://fluo.muzaiko.saluton.dk:8000/radio.mp3"},
    {name = "Vibration", url = "http://vibration.ice.infomaniak.ch/vibration-high.mp3"},
    {name = "Radio Active", url = "http://radio-active.net:8000/active"},
    {name = "Radio Bazarnaom", url = "http://str20.creacast.com/bazarnaom"},
    {name = "Antenne D’Oc", url = "https://antennedoc.ice.infomaniak.ch/antennedoc-48.mp3"},
    {name = "Akroradio", url = "http://stream.akroradio.com:10012/AkroRadio"},
    {name = "Jazzradiofr Jazz Cinema", url = "https://jzr-wr20.ice.infomaniak.ch/jzr-wr20.mp3"},
    {name = "Crooner Radio Frenchy", url = "http://croonerradio_frenchy.ice.infomaniak.ch/croonerradio-frenchy-midfi.mp3"},
    {name = "Crooner Radio American", url = "http://croonerradio_american.ice.infomaniak.ch/croonerradio-american-midfi.mp3"},
    {name = "Radio Public Santé", url = "http://radiopublicsante.ice.infomaniak.ch/radiopublicsante-192.mp3"},
    {name = "Franceclassique Easy", url = "http://direct.francemusique.fr/live/francemusiqueeasyclassique-hifi.mp3?ID=76zqey582k"},
    {name = "France Bleu Drôme-Ardèche", url = "http://direct.francebleu.fr/live/fbdromeardeche-midfi.mp3"},
    {name = "Rockfolk Radio", url = "https://rockfolk.ice.infomaniak.ch/rockfolk.mp3?t=1641651522250"},
    {name = "Crooner Radio", url = "https://direct.croonerradio.fr/croonerradio-midfi.mp3"},
    {name = "La 1Ère Musique OCEAN INDIEN", url = "https://musique1.ice.infomaniak.ch/musique4-128.mp3"},
    {name = "France Musique Opéra", url = "https://icecast.radiofrance.fr/francemusiqueopera-hifi.aac"},
    {name = "Le Son Parisien Aac", url = "https://www.lesonparisien.com/stream/aac.m3u"},
    {name = "NRJ Dance", url = "http://cdn.nrjaudio.fm/adwz1/fr/30013/mp3_128.mp3"},
    {name = "France Bleu Gironde", url = "http://direct.francebleu.fr/live/fbgironde-midfi.mp3"},
    {name = "Atlantica Radio", url = "http://radios.topymedia.com:8000/stream/;.mp3"},
    {name = "M Radio - Années 80", url = "http://mfmwr-010.ice.infomaniak.ch/mfmwr-010.mp3"},
    {name = "Crooner Radio Christmas", url = "http://croonerradio_christmas.ice.infomaniak.ch/croonerradio-christmas-midfi.mp3"},
    {name = "Radio Kreiz Breizh", url = "https://stream.radios.bzh/listen/rkb/radio.mp3"},
    {name = "France Bleu Mayenne", url = "http://direct.francebleu.fr/live/fbmayenne-midfi.mp3"},
    {name = "VIRGIN RADIO FRANCE METAL", url = "http://virage-radio-metal.ice.infomaniak.ch/virage-radio-metal.mp3"},
    {name = "Radio Rencontre Dunkerque", url = "https://listen.radioking.com/radio/153745/stream/194338"},
    {name = "France Bleu Normandie Calvados - Orne", url = "http://direct.francebleu.fr/live/fbbassenormandie-midfi.mp3"},
    {name = "OUI FM BRING THE NOISE", url = "https://ouifmbringthenoise.ice.infomaniak.ch/ouifmbringthenoise.mp3"},
    {name = "Forum 80'S", url = "http://forum80s.ice.infomaniak.ch/forum80s.mp3"},
    {name = "SKY RADIO REUNION", url = "https://stream.mltbroadcast.fr:8110/skyrenuion.acc"},
    {name = "Oceane Nantes", url = "https://oceanenantes.ice.infomaniak.ch/oceanenantes-128.mp3"},
    {name = "OUI FM WOODSTOCK", url = "https://ouifmwoodstock.ice.infomaniak.ch/ouifmwoodstock.mp3"},
    {name = "Hit West Tours", url = "https://hitwest-tours.ice.infomaniak.ch/hitwest-tours-128.mp3"},
    {name = "Pistache La Radio", url = "https://rpstrm.pistache.org:9443/pistache.mp3"},
    {name = "Hit West Angers", url = "https://hitwest-angers.ice.infomaniak.ch/hitwest-angers-128.mp3"},
    {name = "Nova Danse", url = "https://nova-dance.ice.infomaniak.ch/nova-dance-128.mp3"},
    {name = "Radio Classique AAC", url = "http://radioclassique.ice.infomaniak.ch/radioclassique-high.aac"},
    {name = "Radio Saint Affrique", url = "http://stream.radios-arra.fr:8000/stafrique"},
    {name = "Sweet FM Angers", url = "http://sweetfm-angers.ice.infomaniak.ch/sweetfm-angers-192.mp3"},
    {name = "Kizrock Métal", url = "https://go.2stream.net/kizrock_metal"},
    {name = "Radio Presence Figeac", url = "http://direct.radiopresence.com/radio-presence-figeac"},
    {name = "AGORA CÔTE D’AZUR", url = "https://agoracotedazur.ice.infomaniak.ch/agoracotedazur.mp3"},
    {name = "Radio Presence Lourdes", url = "http://direct.radiopresence.com/radio-presence-lourdes"},
    {name = "RADIO COLLECTION", url = "https://www.radioking.com/play/radio-collection/296545"},
    {name = "Radio Sofa", url = "https://listen.radioking.com/radio/292531/stream/338878"},
    {name = "Lyon 1Ère", url = "http://statslive.infomaniak.ch/playlist/lyon1ere/lyon1ere-high.mp3/playlist.m3u"},
    {name = "Mfm Nouvelle Scène", url = "http://mfmwr-005.ice.infomaniak.ch/mfmwr-005.mp3"},
    {name = "RFI Anglais - English", url = "http://live02.rfi.fr/rfienanglais-64.mp3"},
    {name = "NRJ Hits 90", url = "http://cdn.nrjaudio.fm/adwz1/fr/55274/mp3_128.mp3"},
    {name = "OÜI FM Alternatif", url = "http://ouifm2.ice.infomaniak.ch/ouifm2.aac"},
    {name = "313 DBN Radio", url = "https://dbn313radio.radioca.st/stream"},
    {name = "France Culture 2", url = "https://icecast.radiofrance.fr/franceculture-hifi.aac"},
    {name = "Radio Monaco Mix DJ", url = "http://streaming503.radionomy.com/radio-monaco-mixdj"},
    {name = "LFM Radio 955", url = "http://str0.creacast.com/lfm"},
    {name = "Algorythme Lounge Bossa", url = "https://radio8.pro-fhi.net/flux-sinllzly/stream"},
    {name = "SUN Classique", url = "https://diffusion.lafrap.fr/sun-classique.mp3"},
    {name = "Radio Fuze", url = "https://stream-ssl.radios-arra.fr:8443/fuze"},
    {name = "Stone Rock Radio", url = "https://stonerockradio.radioca.st/stream"},
    {name = "Latina Love", url = "http://latinalove.ice.infomaniak.ch/latinalove.mp3"},
    {name = "FIP Autour Du Reggae", url = "http://direct.fipradio.fr/live/fip-webradio6.mp3"},
    {name = "Radioproxlabfr", url = "https://radio.proxlab.fr/radio/8000/radio.mp3"},
    {name = "Urban Hit - Latino", url = "http://urbanhitreggeaton.ice.infomaniak.ch/urbanhitreggeaton-128.mp3?"},
    {name = "NRJ Côte D'Azur 99,2 FM", url = "http://cdn.nrjaudio.fm/audio1/fr/40008/aac_64.mp3"},
    {name = "OUI FM ROCK 2000", url = "https://ouifmrock2000s.ice.infomaniak.ch/ouifmrock2000.mp3"},
    {name = "Crooner Radio Legends", url = "http://croonerradio_legends.ice.infomaniak.ch/croonerradio-legends-midfi.mp3"},
    {name = "FM43", url = "https://fm43.ice.infomaniak.ch/fm43-64.aac"},
    {name = "M Radio 100% Enfoirés", url = "http://mfmwr-011.ice.infomaniak.ch/mfmwr-011.mp3"},
    {name = "Radio ISA Voiron", url = "http://radioisavoiron.ice.infomaniak.ch/radioisavoiron-32.aac"},
    {name = "Top Music", url = "http://str0.creacast.com/topmusic1"},
    {name = "FC Radio", url = "http://fcradio.ice.infomaniak.ch/fcradio-64.aac"},
    {name = "RDWA Luc", url = "https://live.aurafm.org/R-Dwa-LUC"},
    {name = "Info RC", url = "https://live.aurafm.org/InfoRC"},
    {name = "VIRGIN RADIO FRANCE Radio Rock Français", url = "http://vir-wr02.ice.infomaniak.ch/vir-wr02.mp3"},
    {name = "M Radio Talents De La Télé", url = "http://mfmwr-025.ice.infomaniak.ch/mfmwr-025.mp3"},
    {name = "Urban Hit Rap FR", url = "https://urbanhitrapfr.ice.infomaniak.ch/urbanhitrapfr-128.mp3"},
    {name = "F HITS", url = "https://listen.fhits.fr/listen/f._hits/fhits_96.aac"},
    {name = "Station B", url = "http://fabrik-radio.fr:8000/stationb"},
    {name = "Allzic Radio Jazz", url = "https://allzic40.ice.infomaniak.ch/allzic40.aac"},
    {name = "Jet FM", url = "http://80.82.229.202/jetfm.mp3"},
    {name = "Djam Radio - AAC192LC", url = "https://stream9.xdevel.com/audio1s976748-1515/stream/icecast.audio"},
    {name = "Radio Espérance Parole De Dieu", url = "https://esperance.streamakaci.com/parole-de-dieu.mp3"},
    {name = "Vinci Version Pop Rock", url = "https://listen.radioking.com/radio/424771/stream/478231"},
    {name = "Europe 2 Happy Rock Hours", url = "https://europe2.lmn.fm/vr-wr5.mp3?aw_0_1st.playerid=lagardereappVirgin"},
    {name = "RCF Anjou", url = "http://rcf.streamakaci.com/rcf49.mp3"},
    {name = "Europe 2 Classics", url = "https://europe2.lmn.fm/vr-wr2.mp3?aw_0_1st.playerid=lagardereappVirgin"},
    {name = "Radio VINCI Autoroutes 1077 Côte D'Azur", url = "http://str0.creacast.com/radio_vinci_autoroutes_7"},
    {name = "Le Bon Mix Remix 80S 90S - AAC192LC", url = "https://stream10.xdevel.com/audio14s976748-1800/stream/icecast.audio"},
    {name = "Beemboomradio", url = "https://listen.radioking.com/radio/299368/stream/356549"},
    {name = "France", url = "https://stream-eurodance90.fr/radio/8000/128.mp3"},
    {name = "ABF Love", url = "http://abf.net-radio.fr/abflove.mp3"},
    {name = "Autoroute Info 1077 Zone Sud", url = "http://media.autorouteinfo.fr:8000/direct_sud.mp3"},
}

return stations
