local stations = {
    {name = "რადიო ძველი ქალაქი Старый Город", url = "http://iis.ge:8000/radiodk.mp3"},
    {name = "1011 RADİO TURKEY FM", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "Radio Amra", url = "https://streamer.radio.co/s34b5469e0/listen"},
    {name = "Dardimandi", url = "https://nue01-edge01.itdc.ge/fm-dardimandi-97.1/mono.m3u8"},
    {name = "არდაიდარდო", url = "https://tv.cdn.xsg.ge/cld9-0386/ardaidardo/tracks-a1/mono.m3u8"},
    {name = "Voice Of Abkhazia", url = "http://109.172.136.60:8081/broadwavelow.mp3"},
    {name = "რადიო ჩვენებური", url = "https://radio.cdn.xsg.ge/cld9-1050/chveneburi/index.m3u8"},
    {name = "რადიო დარდიმანდი", url = "http://109.172.136.60:8080/broadwavehigh.mp3"},
    {name = "Marneuli FM", url = "http://stream.it-solutions.ge:8000/mp3-radiomarneulifm"},
    {name = "Tbilisi FM 93,5", url = "http://iis.ge:8000/radiotbilisi.mp3"},
    {name = "ავტორადიო Avtoradio", url = "https://tv.cdn.xsg.ge/cld9-0386/avtoradio/tracks-a1/mono.m3u8"},
    {name = "რადიო იმედი Radio Imedi", url = "https://tv.cdn.xsg.ge/radioimedi/stream01/shoutcast"},
    {name = "Hereti FM", url = "http://iis.ge:8000/hereti.mp3"},
    {name = "რადიო ფორტუნა Radio Fortuna", url = "https://tv.cdn.xsg.ge/cld9-0386/fortuna/tracks-a1/mono.m3u8"},
    {name = "რადიო პალიტრა Radio Palitra", url = "https://radiostream.palitra.ge/stream.mp3"},
    {name = "LF Radio", url = "https://rtn.cdnstream1.com/2582_96.aac"},
    {name = "რადიო ჩევნებური Radio Chveneburi", url = "https://radio.cdn.xsg.ge/cld9-1050/chveneburi/tracks-a1/mono.m3u8"},
    {name = "Star FM", url = "https://streams.it1.ge/ogg-starfm"},
    {name = "რადიო ობიექტივი Radio Obieqtivi", url = "https://nue01-edge01.itdc.ge/fm-obieqtivi-105.1/mono.m3u8"},
    {name = "WVFJ 933 1021 The JOY FM", url = "https://rtn.cdnstream1.com/2576_96.aac?rand=81562"},
    {name = "Арадио Sputnik Аҧсны", url = "https://icecast-rian.cdnvideo.ru/voicesuh"},
    {name = "რადიო სივრცე Radio Sivrce", url = "https://proxy.streamer.mediabox.ge/ice/8000/sivrce"},
    {name = "რადიო პოზიტივი Radio Positive", url = "https://stream.radiojar.com/sr4vzamzfnruv"},
    {name = "რადიო აჭარა Radio Adjara", url = "https://edge.mixlr.com/channel/bzorq"},
    {name = "რადიო კომერსანტი Radio Commersant", url = "https://radio.cdn.xsg.ge/fm-commersant-95.5/tracks-a1/mono.m3u8"},
    {name = "უცნობი FM Ucnobi FM", url = "http://149.3.104.166:8000/stream.ogg"},
}

return stations
