local stations = {
    {name = "Radio HRN La Voz De Honduras", url = "https://ice42.securenetsystems.net/HRN"},
    {name = "XY 905 FM Tegucigalpa", url = "http://ice42.securenetsystems.net/XY905"},
    {name = "Radio Globo 885 HN", url = "https://stream.radiosmundiales.com:8016/GLOBO885"},
    {name = "Radio America 947 Tegucigalpa", url = "http://provisioning.streamtheworld.com/pls/AMERICA.pls"},
    {name = "EXA FM: Música Pop En Español E Inglés", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "Radio Moderna", url = "http://provisioning.streamtheworld.com/pls/MODERNAAAC.pls"},
    {name = "Estereo Clásica", url = "https://streaming.radio.co/s0c06b7076/listen"},
    {name = "Suave FM 1025 Tegucigalpa", url = "http://ice42.securenetsystems.net/SUAVE"},
    {name = "Musiquera 933 FM", url = "https://stream.zeno.fm/83h238tqsceuv"},
    {name = "La Top 1029 FM - San Pedro Sula, Honduras", url = "https://us9.maindigitalstream.com/ssl/latop102"},
    {name = "94 SU FM 941 Tegucigalpa", url = "http://ice42.securenetsystems.net/94SUFM"},
    {name = "Radio W107 1073 Tegucigalpa", url = "http://ic.streann.com:8000/w107"},
    {name = "Dee Jay", url = "https://stream.zeno.fm/6wpxyt9htg0uv"},
    {name = "Super 100 Tegucigalpa 1001", url = "http://provisioning.streamtheworld.com/pls/SUPER100.pls"},
    {name = "ROCK N' POP", url = "https://ice42.securenetsystems.net/ROCKNPOP"},
    {name = "Stereo Exitos 881 Tegucigalpa", url = "http://ice42.securenetsystems.net/EXITOS"},
    {name = "Radio Taulabe", url = "https://stream.playerlive.info:8151/stream/1/"},
    {name = "EXA FM Honduras: Tegucigalpa 1005 FM San Pedro Sula 893 FM Choluteca 959 FM Litoral 939 FM", url = "https://stream.zeno.fm/0n4tnx3wd5zuv"},
    {name = "Radio Activa Honduras", url = "https://stream.zeno.fm/6n7fp9t2pceuv"},
    {name = "Stereo Ceiba 999 - La Ceiba", url = "http://provisioning.streamtheworld.com/pls/RADIO_CEIBAAAC.pls"},
    {name = "Estereo Mil", url = "http://s6.streammonster.com:8003/;"},
    {name = "RADIO FÉNIX INTERNACIONAL", url = "http://listen.usuarios.space:8036/live"},
    {name = "GD Dubai", url = "https://streaming.exclusive.radio/er/gratefuldead/icecast.audio"},
    {name = "Vox FM Honduras - Tegucigalpa 1017 FM - San Pedro Sula 1061 FM", url = "https://ice42.securenetsystems.net/VOXFM"},
    {name = "RNH", url = "https://stream.zeno.fm/mb5f69fk0d0uv"},
    {name = "Stereo Dimensión - La 96", url = "https://rr5100.globalhost1.com:7328/stream"},
    {name = "1 FM Hits Radio", url = "https://stream.zeno.fm/yg1gkzwabzzuv"},
    {name = "DCR Difusora Cristiana De Radio 1031 FM", url = "http://stream.playerlive.info:8165/"},
    {name = "Cristal FM 889", url = "https://cristalfm-zikoxweb.radioca.st/;"},
    {name = "Estereo Sur 913 FM", url = "https://cast.az-streamingserver.com/proxy/estereosur2?mp=/stream"},
    {name = "Otoro Radio", url = "https://stream.playerlive.info:8089/live.aac"},
    {name = "LA RADIO GLOBAL", url = "https://sonicpanel.us/8022/stream"},
    {name = "Radioactiva 997 Honduras", url = "https://stream.zeno.fm/fh8qfg75puquv"},
    {name = "Cortés FM 1057", url = "https://cortesfm-zikoxweb.radioca.st/;"},
    {name = "Girasol Stereo 1023 FM", url = "https://stream.playerlive.info:8037/live.aac"},
    {name = "ABC Radio AM 550 FM 897", url = "http://137.184.101.169:8000/radio.mp3"},
    {name = "Conga FM 1037 San Pedro Sula", url = "http://tupropiaradio.net:8002/;"},
    {name = "Radio Radical", url = "https://stream.zeno.fm/vcumd3susq5vv"},
    {name = "Encuentro Digital 1043 FM", url = "https://stream.zeno.fm/n1dn94e661zuv"},
    {name = "Cadena Radial Del Centro 897 FM", url = "https://sonic.portalfoxmix.cl/8442/stream"},
    {name = "Stereo Cafe 1003 FM", url = "https://stream.zeno.fm/vt667xqryd0uv"},
    {name = "NUEVA VISIÓN 883 FM", url = "http://159.69.43.96:9304/;"},
    {name = "HRYW 959 Radio Panamericana - Tegucigalpa", url = "http://online.radiodifusion.net:1935/panam-hn/panam.stream/master.m3u8"},
    {name = "Stereo San Juan", url = "https://radios.sisc-tech.com:8020/radio.mp3"},
    {name = "Cortes FM", url = "https://cortesfm-zikoxweb.radioca.st/stream/1/"},
    {name = "Metrodigital Radio", url = "https://stream.zeno.fm/z9ugz9vsqfhvv"},
    {name = "Vinilo FM Honduras", url = "https://stream.zeno.fm/xwextarnscluv"},
    {name = "Master FM 969", url = "https://stream.zeno.fm/0c8utm1cckhvv"},
    {name = "Stereo Fe Tegucigalpa 989 FM - San Pedro Sula 1009 FM - Comayagua 1059 FM - Danlí 1063 FM - Choluteca 1007 FM", url = "https://media.cdebs.com/8008/stream"},
}

return stations
