local stations = {
    {name = "Newdanceradio", url = "http://stream.newdanceradio.ru/"},
    {name = "Ретро FM Рига Retro FM", url = "https://live.retrofm.lv/retrofmlatvia"},
    {name = "Radio ENERGYLV - Russian", url = "http://www.radioenergy.lv:9000/listen.pls"},
    {name = "Star Fm", url = "http://starfm.live.advailo.com/audio/mp3/icecast.audio"},
    {name = "European Hit Radio - Superhits", url = "http://stream.europeanhitradio.com:8000/Stream_21.aac"},
    {name = "Radio SWH", url = "http://80.232.162.149:8000/swh96mp3.m3u"},
    {name = "European Hit Radio - Russkie Hiti", url = "http://stream.europeanhitradio.com:8000/khr.aac"},
    {name = "Latvijas Radio 4", url = "http://lr4mp1.latvijasradio.lv:8020/;"},
    {name = "Latvijas Radio 2", url = "http://lr2mp1.latvijasradio.lv:8002/;"},
    {name = "Talsi Lounge", url = "http://radio.kuums.lv:5555/listen.pls"},
    {name = "Skonto", url = "https://stream.radioskonto.lv:8443/stereo"},
    {name = "Alise Plus", url = "http://fm2inet.aliseplus.lv:8080/"},
    {name = "TOP Radio", url = "https://topradio.live.advailo.com/topradio/mp3/icecast.audio"},
    {name = "Авторадио Латвия", url = "https://live.relaxfm.lv/03"},
    {name = "European Hit Radio - Party Service", url = "http://stream.europeanhitradio.com:8000/Stream_12.aac"},
    {name = "Radio TEV", url = "http://stream.radiotev.lv:8002/radiov"},
    {name = "European Hit Radio - Top 40", url = "http://stream.europeanhitradio.com:8000/Stream_27.aac"},
    {name = "Relax", url = "https://live.relaxfm.lv/02"},
    {name = "European Hit Radio - Remixes", url = "http://stream.europeanhitradio.com:8000/Stream_32.aac"},
    {name = "Latvijas Radio 1", url = "http://lr1mp1.latvijasradio.lv:8012/;"},
    {name = "European Hit Radio - Latviešu Hiti", url = "http://stream.europeanhitradio.com:8000/Stream_22.aac"},
    {name = "Latvijas Radio 3 - Klasika", url = "http://lr3mp0.latvijasradio.lv:8004/;"},
    {name = "XOFM", url = "https://live.xo.fm/xofm128"},
    {name = "European Hit Radio", url = "http://stream.europeanhitradio.com:8000/ehr.aac"},
    {name = "Radio SWH Rock", url = "http://80.232.162.149:8000/rock96mp3.m3u"},
    {name = "Radio SWH Gold", url = "http://80.232.162.149:8000/gold96mp3.m3u"},
    {name = "European Hit Radio - Fresh", url = "http://stream.europeanhitradio.com:8000/Stream_25.aac"},
    {name = "Radio Skonto", url = "https://stream.radioskonto.lv:8443/mp3"},
    {name = "Radio SWH LV", url = "https://live.radioswh.lv:8443/swh_lv"},
    {name = "European Hit Radio - Dance", url = "http://stream.europeanhitradio.com:8000/Stream_24.aac"},
    {name = "European Hit Radio - RNB", url = "http://stream.europeanhitradio.com:8000/Stream_11.aac"},
    {name = "Radio Roks", url = "https://live.relaxfm.lv/06"},
    {name = "Latgales Radio", url = "http://www.radiolg.lv:8000/128_aac.m3u"},
    {name = "European Hit Radio - Eurochart", url = "http://stream.europeanhitradio.com:8000/Stream_31.aac"},
    {name = "Radio 7", url = "https://listen.radio7.lv:2053/Radio7"},
    {name = "Eiropas Hītu Radio", url = "http://stream.europeanhitradio.com:8000/ehr.mp3"},
    {name = "LRMAROCKRADIO", url = "https://c22.radioboss.fm:18318/stream"},
    {name = "European Hit Radio - Darbam", url = "http://stream.europeanhitradio.com:8000/Stream_23.aac"},
    {name = "European Hit Radio - Acoustic", url = "http://stream.europeanhitradio.com:8000/Stream_18.aac"},
    {name = "Talsi Remix", url = "http://radio.kuums.lv:5555/"},
    {name = "Kurzemes Radio", url = "http://31.170.16.6:8000/"},
    {name = "Latvijas Kristīgais Radio", url = "https://radio.lkr.lv/;?type=http&nocache=40"},
    {name = "Radio SWH+", url = "http://80.232.162.149:8000/plus96mp3.m3u"},
    {name = "LV Radio 2", url = "http://lr2mp1.latvijasradio.lv:8002/"},
    {name = "Radio NABA", url = "http://nabamp0.latvijasradio.lv:8016/;"},
    {name = "Latvijas Radio 5", url = "http://lr5mp1.latvijasradio.lv:8012/;"},
    {name = "RADIO MARIA LATVIA", url = "http://dreamsiteradiocp2.com:8046/stream"},
    {name = "Radio SWH Kurzeme", url = "http://87.110.219.34:8000/swhmp3"},
    {name = "Radio SWH - Spin FM", url = "http://80.232.162.149:8000/spin96mp3.m3u"},
    {name = "LV Radio 4", url = "http://lr4mp1.latvijasradio.lv:8020/"},
    {name = "Skonto Plus", url = "https://stream.radioskontoplus.lv:8443/st128"},
    {name = "European Hit Radio - Rock", url = "http://stream.europeanhitradio.com:8000/Stream_37.aac"},
    {name = "Nordic Chillout Radio", url = "https://play.radioking.io/nordic-chillout-radio/736489"},
    {name = "European Hit Radio - Love Songs", url = "http://stream.europeanhitradio.com:8000/Stream_28.aac"},
    {name = "Swhplus", url = "http://80.232.162.149:8000/plus96mp3"},
    {name = "Radio ENERGYLV", url = "http://www.radioenergy.lv:8000/listen.pls"},
    {name = "LV Radio 1", url = "http://lr1mp1.latvijasradio.lv:8012/"},
    {name = "SWH", url = "http://80.232.162.149:8000/swh96mp3"},
}

return stations
