local stations = {
    {name = "1030 AM Ciudad De México - 1030 AM - XEQR-AM - Grupo Radio Centro - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_AMAAC.aac"},
    {name = "105 Digital Aguascalientes - 1053 FM - XHUZ-FM - Radiogrupo - Aguascalientes, AG", url = "http://201.159.48.106:8080/"},
    {name = "1071 FM Matamoros - 1071 FM - XHVTH-FM - Multimedios Radio - Matamoros, Tamaulipas", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XHVTHFM_SC"},
    {name = "1280 AM Puebla - 1280 AM - XEEG-AM - Radio Cañón NTR Medios De Comunicación - Puebla, PU", url = "https://streamingcwsradio30.com/8274/stream"},
    {name = "2021 FM - 923 FM - XHLY-FM - Cadena RASA - Morelia, MI", url = "http://s4.mexside.net:7040/;"},
    {name = "620", url = "https://statics-v2.streema.com/static/audios/sample.ea78c3d52389.mp3"},
    {name = "841 Radio FM 879", url = "https://sonic.sistemahost.es/8186/stream"},
    {name = "90S Dance By Mix Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR11_s01AAC.aac"},
    {name = "945 Radio Universidad UAA Universidad Autonoma De Aguascalientes", url = "https://streamingcwsradio30.com/8148/stream"},
    {name = "ABC Deportes Monterrey - 921 FM 660 AM - XHGBO-FM XEFZ-AM - Grupo Radio Alegría - General Bravo Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ABC_NOTICIAS_660AM.mp3"},
    {name = "Activa Hermosillo - 897 FM - XHEDL-FM - Grupo Radio SA - Hermosillo, Sonora", url = "http://www.tuasesorweb.com:8032/;"},
    {name = "Adictivo Radio - 903 FM", url = "http://s22.myradiostream.com:9504/stream"},
    {name = "Adictivo Radio Torreón - 903 FM - XHBP-FM - GPS Media - Torreón, CO Gómez Palacio, DG", url = "http://s22.myradiostream.com:9504/"},
    {name = "ADN 921 FM", url = "https://streamingcwsradio30.com/8322/stream"},
    {name = "ALFA 913 Ciudad De México - 913 FM - XHFAJ-FM - Grupo Radio Centro - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHFAJ_FMAAC.aac"},
    {name = "ALFA Monterrey - 1045 FM - XHMF-FM - Grupo Radio Centro - Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMF_FMAAC_SC"},
    {name = "Altamix", url = "https://serverssl.innovatestream.pe:8080/http://192.99.16.17:9366/;"},
    {name = "Altamix 919FM", url = "http://sp2.servidorrprivado.com:9366/;"},
    {name = "Altavoz Radio Culiacán 891 FM", url = "https://s2.mexside.net/8094/stream"},
    {name = "Altavoz Radio Mazatlán 1035 FM", url = "https://s2.mexside.net/8166/stream"},
    {name = "Altermedia Network", url = "http://cdn4.onstream.audio:9171/;"},
    {name = "Alternativa 98 Aguascalientes - 981 FM - XHNM-FM - Radio Y Televisión De Aguascalientes - Aguascalientes, Aguascalientes", url = "http://www.streamingcwsradio30.com:8016/stream"},
    {name = "Alternativa 981 FM", url = "http://www.streamingcwsradio30.com:8016/;"},
    {name = "AMOR 943 Irapuato - 943 FM - XHJTA-FM - Grupo ACIR - Irapuato, Guanajuato", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHJTAAAC.aac"},
    {name = "AMOR 953 San Luis Potosí - 953 FM - XHNB-FM - Grupo ACIR - San Luis Potosí, San Luis Potosí", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHNBFMAAC.aac"},
    {name = "AMOR Es Aguascalientes - 1045 FM - XHDC-FM - Grupo Radiofónico ZER - Aguascalientes, AG", url = "https://cast.zuperdns.net/8026/stream/"},
    {name = "AMOR Es Zacatecas - 993 FM - XHZAZ-FM - Grupo Radiofónico ZER - Zacatecas, ZA", url = "https://cast.zuperdns.net/8002/stream/"},
    {name = "Amor Puebla - 1033 FM - XHRH-FM - Grupo ACIR - Puebla, PU", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRHFMAAC.aac"},
    {name = "Amor Solo Pop Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR03_s01AAC.aac"},
    {name = "Amor Toluca - 925 FM - XHRJ-FM - Grupo ACIR - Toluca, EM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRJFMAAC.aac"},
    {name = "Antena - 1025 FM - XHES-FM - GRD Multimedia - Chihuahua, Chihuahua", url = "https://streamingcwsradio30.com:7093/stream"},
    {name = "Antena - 1025 FM [Chihuahua, Chihuahua]", url = "https://streamingcwsradio30.com:7093/;"},
    {name = "Arandas FM 1073", url = "https://live.zuperdns.net/1073/;"},
    {name = "Back FM Piedras Negras - 1009 FM - XHVM-FM - Grupo Zócalo - Piedras Negras, CO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHVMFMAAC.aac"},
    {name = "Baladas Románticas Radio", url = "https://media.streamingradiomx.com/listen/baladas_rom%C3%A1nticas_radio/radio.mp3"},
    {name = "BANDOLERA 1005 - 1005 FM - XHIDO-FM - NRM Comunicaciones - Tula, HG", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHIDOFMGAVCAAC.aac"},
    {name = "Bandolera Ciudad Del Carmen - 923 FM - XHPCDC-FM - NRM Comunicaciones - Ciudad Del Carmen, Campeche", url = "https://ss1.audiorama.com.mx:6570/stream"},
    {name = "BC 951 FM", url = "https://live.zuperdns.net/9510/;"},
    {name = "Bella Voces Radio", url = "http://radio.redcoahuila.net:8116/;"},
    {name = "Bibra Fm Los Mochis", url = "https://sp3.servidorrprivado.com:10828/stream"},
    {name = "BOLLOCKS Rock Metal Radio", url = "https://s44.myradiostream.com/6588/;?type=http&nocache=1571393528?0.9592127816686777"},
    {name = "BUENISIIMA 1530 Y 1590 CDMX - 1530 AM - XEUR-AM - Grupo Audiorama Comunicaciones - Ciudad De México", url = "http://s1.audiorama.mx:6678/stream"},
    {name = "BUENISIIMA 885 FM - CUERNAVACA", url = "http://s1.audiorama.mx:6628/;"},
    {name = "Buenisiima Acapulco - 1039 FM - XHPO-FM - Grupo Audiorama Comunicaciones - Acapulco, GR", url = "https://ss1.audiorama.com.mx:6606/stream"},
    {name = "Buenisiima Ciudad De México - 1530 AM - XEUR-AM - Grupo Audiorama Comunicaciones Radiorama - Ciudad De México", url = "https://ss1.audiorama.com.mx:6678/stream"},
    {name = "Buenisiima Mexicali - 850 AM - XEZF-AM - Grupo Audiorama Comunicaciones - Mexicali, BC", url = "https://ss1.audiorama.com.mx:6594/stream"},
    {name = "Cabo Mil - 963 FM - XHSJS-FM - San José Del Cabo, Baja California", url = "https://streamingcwsradio30.com:7070/stream"},
    {name = "Canal 98 La Maquina Del Sonido", url = "http://stream.zeno.fm/xmhshz1wyrquv.m3u"},
    {name = "Candela La Barca - 1047 FM - XHLB-FM - Cadena RASA - Jamay, JC", url = "http://s4.mexside.net:2086/"},
    {name = "Candela Morelia - 901 FM 570 AM - XHLQ-FM XELQ-AM - Cadena RASA - Morelia, MI", url = "http://s2.mexside.net:9088/stream2"},
    {name = "Candela Uruapan - 911 FM - XHFN-FM - Cadena RASA - Uruapan, MI", url = "http://167.114.116.223:3334/"},
    {name = "Caribe FM - 1019 FM - XHCBJ-FM - SQCS Sistema Quintanarroense De Comunicación Social - Cancún, Quintana Roo", url = "https://sp2.servidorrprivado.com/8042/stream"},
    {name = "Caxcán FM - 951 FM - XHJRS-FM - Grupo Radiofónico ZER - Jalpa, Zacatecas", url = "https://cast.zuperdns.net/8008/stream/;stream.mp3?nochache=0.3141970676706438"},
    {name = "Chetumal FM - 1009 FM - XHCHE-FM - SQCS Sistema Quintanarroense De Comunicación Social - Chetumal, Quintana Roo", url = "https://sp2.servidorrprivado.com/3981/stream"},
    {name = "Ciudadana 660 Ciudad De México - 660 AM - XEDTL-AM - IMER - Ciudad De México", url = "https://s2.mexside.net/8026/stream"},
    {name = "Classic - 1069 FM [Monterrey, Nuevo León]", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/CLASSIC106_SC.mp3"},
    {name = "Classic Monterrey - 1069 FM - XHPJ-FM - Multimedios Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/CLASSIC106AAC.aac"},
    {name = "Classic Rock Universal - Online - Grupo Radio Centro - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHNZ_COMAAC.aac"},
    {name = "Coahuila Hoy Radio Torreón - 975 FM - XHCSBB-FM - Grupo M Radio - Torreón, Coahuila", url = "https://s01.digitalserver.org:7022/live.mp3"},
    {name = "Conexión 927 Aguascalientes - 927 FM - XHCPDI-FM - Radio Y Televisión De Aguascalientes - Aguascalientes, Aguascalientes", url = "https://streamingcwsradio30.com:7008/;"},
    {name = "Contacto 1190 AM", url = "https://streamingcwsradio30.com/8240/stream"},
    {name = "Contacto 989 Chalco - 989 FM - XHCHAL-FM - Chalco, Estado De México", url = "https://stm11.xcast.com.br:9640/;"},
    {name = "Convoy En Vivo", url = "https://live.convoynetwork.com/stream"},
    {name = "Cristo Rey Radio 1110 AM", url = "https://live.turadio.stream/8026/stream"},
    {name = "Crystal 1049 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMLOFMAAC.aac"},
    {name = "Crystal 1061 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMYFMAAC.aac"},
    {name = "Crystal Toluca - 933 FM - XHEDT-FM - Grupo Siete - Toluca, Estado De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHEDTFMAAC.aac"},
    {name = "Cumbia Total Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR40_S01AAC.aac"},
    {name = "Cumbias Inmortales Radio Monterrey - Online - Wwwcumbiasinmortalescom - Grupo Digital Retroland - Monterrey, Nuevo León", url = "https://panel.retrolandigital.com/listen/cumbias_inmortales_radio/listen"},
    {name = "D95 - 949 FM - XHCHH-FM - Multimedios Radio - Chihuahua, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCHHFMAAC.aac"},
    {name = "D95 Chihuahua - 949 FM - XHCHH-FM - Multimedios Radio - Chihuahua, CH", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCHHFM_SC.mp3"},
    {name = "D99 Monterrey - 989 FM - XHJD-FM - Multimedios Radio - Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/D99_SC.mp3"},
    {name = "Digital 102-9 Monterrey - 1029 FM - XHMG-FM - Grupo Radio Alegría - Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/DIGITAL_1029FMAAC.aac"},
    {name = "Digital 995 FM", url = "https://sp5.servidorrprivado.com/8066/stream"},
    {name = "Digital Saltillo - 1065 FM - XHZCN-FM - RCG Media - Saltillo, Coahuila", url = "https://radio.rcg.com.mx:7000/"},
    {name = "Discos Guardados", url = "http://opml.radiotime.com/Tune.ashx?id=s298784&formats=mp3,aac,wma,ogg&partnerId=xwhZkVKi&filter=s:popular"},
    {name = "DK 1250 Guadalajara - 1250 AM - XEDK-AM - Radiorama - Guadalajara, JC", url = "http://192.99.16.17:9880/"},
    {name = "El Heraldo Radio 889 FM Acapulco", url = "https://radiovision.mi-radio.stream:11008/;"},
    {name = "El Kuino FM 961", url = "https://live.zuperdns.net/1961/;"},
    {name = "El Lobo Chihuahua - 1061 FM - XHSU-FM - Sistema Radio Lobo - Chihuahua, CH", url = "https://streamingcwsradio30.com/8172/stream"},
    {name = "El Patrón Córdoba - 945 FM - XHYV-FM - Oliva Radio - Córdoba, VE", url = "http://scc.cnwks.ws:8688/"},
    {name = "El Toque FM", url = "http://us10a.serverse.com:8207/"},
    {name = "El Y Ella 1037 FM", url = "https://radios.radiohd.com.mx/8272/;"},
    {name = "En Neza Radio Nezahualcóyotl - 973 FM - XHNEZ-FM - Voces Urbanas, Movimiento Alternativo De Información Social - Nezahualcóyotl, EM", url = "http://192.99.233.46:9754/"},
    {name = "Escuchaz", url = "https://stream3.mexiserver.com:10150/;"},
    {name = "España FM 929", url = "https://sh4.radioonlinehd.com:8526/stream"},
    {name = "Espectacular 917 FM", url = "http://hd.digitalradio.mx:5980/;"},
    {name = "Estrellas De Los 80S Radio Monterrey - Online - Wwwestrellasdelos80Scom - Grupo Digital Radioland - Monterrey, Nuevo León", url = "https://panel.retrolandigital.com/listen/estrellas_de_los_80s/listen"},
    {name = "Estéreo Istmo 963 FM", url = "https://s2.mexside.net/8038/stream"},
    {name = "Estéreo Pop 1033 FM Y 1070 AM Acapulco", url = "https://stream9.mexiserver.com/8170/stream"},
    {name = "Exa FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHEXA_SC"},
    {name = "EXA FM 1027 Nogales - 1027 FM - XHQT-FM - MVS Radio - Nogales, Sonora", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHQTAAC.aac"},
    {name = "EXA FM 1041 León - 1041 FM - XHMD-FM - MVS Radio - León, Guanajuato", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMDFMAAC.aac"},
    {name = "EXA FM 899 Puerto Vallarta - 899 FM - XHCCBB-FM - Alica Medios - Puerto Vallarta, Jalisco", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCCBBAAC.aac"},
    {name = "EXA FM 913 Córdoba - 913 FM - XHPT-FM - Radio Comunicaciones De Las Altas Montañas - Córdoba, Veracruz", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPTAAC.aac"},
    {name = "EXA FM 919 Ciudad Mante - 919 FM - XHRLM-FM - ORT Radio - Ciudad Mante, Tamaulipas", url = "https://s01.digitalserver.org:7034/;"},
    {name = "EXA FM 935 Irapuato - 935 FM - XHNY-FM - Irapuato, Guanajuato", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHNYAAC.aac"},
    {name = "EXA FM 941 Puebla - 941 FM - XHJE-FM - MVS Radio - Puebla, Puebla", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHJEFMAAC.aac"},
    {name = "EXA FM 945 Ciudad Victoria - 945 FM - XHBJ-FM - ORT Radio - Ciudad Victoria, Tamaulipas", url = "https://s01.digitalserver.org:7038/;"},
    {name = "EXA FM 955 Torreón - 955 FM - XHMP-FM - Grupo Radio Estéreo Mayran - Torreón, Coahuila", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMPAAC.aac"},
    {name = "EXA FM 983 Ciudad Juárezel Paso - 983 FM - XHPX-FM - MVS Radio - Ciudad Juárez, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPXAAC.aac"},
    {name = "EXA FM 993 Acapulco - 993 FM - XHNQ-FM - MVS Radio - Acapulco, Guerrero", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHNQAAC.aac"},
    {name = "EXA FM 993 Ciudad Obregón - 993 FM - XHOX-FM - Radio Grupo García De León - Ciudad Obregón, Sonora", url = "https://streamingcwsradio30.com:7056/"},
    {name = "EXA FM 997 Ciudad Del Carmen - 997 FM 1070 AM - XHIT-FM XEIT-AM - Radiorama - Ciudad Del Carmen, Campeche", url = "https://ss1.audiorama.com.mx:6674/stream"},
    {name = "Exa FM Aguascalientes - 973 FM - XHAGC-FM - Radio Universal - Aguascalientes, Aguascalientes", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHAGCAAC.aac"},
    {name = "Exa FM Campeche - 1003 FM - XHMI-FM - NCS Núcleo Comunicación Del Sureste - Campeche, CM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMI_SC"},
    {name = "Exa FM Colima - 997 FM - XHCOC-FM - JA Radio - Colima, Colima", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCOCFMAAC.aac"},
    {name = "Exa FM Cuernavaca - 957 FM - XHCT-FM - MVS Radio - Cuernavaca, MO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCTAAC.aac"},
    {name = "Exa FM Culiacán - 1017 FM - XHESA-FM - Grupo RSN - Culiacán, SI", url = "http://167.114.116.223:1082/;"},
    {name = "Exa FM El Paso - 983 FM - XHPX-FM - MVS Radio - Ciudad Juárez, CH", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPX_SC"},
    {name = "Exa FM Ensenada - 1041 FM - XHADA-FM - MVS Radio - Ensenada, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHADA_SC"},
    {name = "Exa FM Fresnillo - 1005 FM - XHFRE-FM - Grupo B15 - Fresnillo, Zacatecas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHFREAAC.AAC"},
    {name = "Exa FM Guadalajara - 1011 FM - XHMA-FM - MVS Radio - Guadalajara, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMAAAC.aac"},
    {name = "Exa FM Guasave - 981 FM - XHGSE-FM - Grupo RSN - Guasave, SI", url = "http://192.99.16.17:7841/;"},
    {name = "Exa FM León - 1041 FM - XHMD-FM - MVS Radio - León, GT", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMDFM_SC"},
    {name = "Exa FM Los Cabos - 1039 FM - XHCCAC-FM - MVS Radio - Los Cabos, Baja California Sur", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCCACAAC.aac"},
    {name = "Exa FM Los Mochis - 989 FM - XHMPM-FM - Grupo RSN - Los Mochis, SI", url = "https://sp2.servidorrprivado.com:10858/stream"},
    {name = "Exa FM Mazatlán - 897 FM - XHOPE-FM - GPM Grupo Promomedios - Mazatlán, SI", url = "http://audioout.gvstream.net/gpm-exa897.aac"},
    {name = "Exa FM Mexicali - 915 FM - XHJC-FM - MVS Radio - Mexicali, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHJCFM_SC"},
    {name = "Exa FM Monterrey - 973 FM - XHSR-FM - MVS Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRSMTYFMAAC.aac"},
    {name = "Exa FM Mérida - 993 FM - XHMRA-FM - MVS Radio - Mérida, YU", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMRA_SC"},
    {name = "Exa FM Oaxaca - 985 FM - XHNR-FM - ORO Organización Radiofónica De Oaxaca - Oaxaca, OA", url = "http://ororadio2.serverroom.us:4638/"},
    {name = "Exa FM San Juan Del Río - 991 FM - XHVI-FM - San Juan Del Río, Querétaro", url = "https://tv.radiohosting.online:8352/stream"},
    {name = "Exa FM Tampico - 953 FM - XHOX-FM - MVS Radio - Tampico, TM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHOXAAC.aac"},
    {name = "Exa FM Tehuacán - 1029 FM - XHWJ-FM - Radioth Comunicaciones - Tehuacán, PU", url = "http://pump.com.mx:8035/"},
    {name = "Exa FM Tijuana - 917 FM - XHGLX-FM - MVS Radio - Tijuana, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHGLXAAC.aac"},
    {name = "Exa FM Tuxtepec - 1013 FM - XHPTUX-FM - Grupo Rojaz - Tuxtepec, OA", url = "https://stream5.mexiserver.com:1007/stream"},
    {name = "Exa FM Veracruz - 933 FM - XHPS-FM - MVS Radio - Veracruz, VE", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFM_SC.aac"},
    {name = "Exa FM Zamora - 981 FM - XHPZAM-FM - Ilox Telecomunicaciones - Zamora, Michoacán", url = "http://live.exafmzamora.mx:55252/exafmzamora.mp3"},
    {name = "EXA FM: En Todas Partes Ponte Exa", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "Extremo Grupero Villaflores - 1039 FM - XHVF-FM - Radio Núcleo - Villaflores, CS", url = "http://s4.mexside.net:2044/;stream.nsv"},
    {name = "Fantasia W Radio 891 FM", url = "http://empresarios.mexicanradio.org:8344/stream.mp3"},
    {name = "FM 105 - 1053", url = "https://s01.digitalserver.org/9208/;"},
    {name = "FM Centro Apizaco - 1003 FM - XHXZ-FM - Apizaco, Tlaxcala", url = "https://radioenhd.com/8212/;"},
    {name = "FM Globo Monterrey - 881 FM - XHJM-FM - MVS Radio - Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHJMFM_SC"},
    {name = "Focus Radio Reynosa - 1670 AM - XEFCR-AM - Reynosa, TM", url = "https://stream9.mexiserver.com/8214/stream"},
    {name = "Free FM 80´S Mexico", url = "https://freefm80.radioca.st/"},
    {name = "Fusión Tijuana - 1025 FM - XHUAN-FM - IMER - Tijuana, Baja California", url = "https://s2.mexside.net/8036/stream"},
    {name = "Fusión Veracruz - 901 FM - XHLL-FM - Grupo Pazos - Veracruz, VE", url = "https://sgaudio.centrocibernetico.com/fusion"},
    {name = "GBR Gamebytesradio", url = "https://cp10.shoutcheap.com:2199/tunein/gbrgameb.pls"},
    {name = "Globo 1013 Ciudad Del Carmen - 1013 FM - XHMAB-FM - Organización Radio Carmen - Ciudad Del Carmen, Campeche", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMABAAC.aac"},
    {name = "Globo 881 Monterrey - 881 FM - XHJM-FM - MVS Radio - Monterrey, Nuevo León", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XHJMFMAAC.aac"},
    {name = "Globo 979 Mazatlán - 979 FM - XHMMS-FM - Grupo RSN - Mazatlán, Sinaloa", url = "https://sp2.servidorrprivado.com:10861/fmglobo"},
    {name = "Globo 987 Guadalajara - 987 FM - XHLC-FM - MVS Radio - Guadalajara, Jalisco", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHLCFMAAC.aac"},
    {name = "Globo 993 Tijuana - 993 FM - XHOCL-FM - MVS Radio - Tijuana, Baja California", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHOCLAAC.aac"},
    {name = "Globo 997 Ciudad Acuña - 997 FM - XHPL-FM - RCG Media - Ciudad Acuña, Coahuila", url = "http://radio.rcg.com.mx:8016/"},
    {name = "Grupera Morelia - 931 FM - XHLIA-FM - Grupo Radio SA - Morelia, Michoacán", url = "https://tuasesorweb.com:2000/stream/GruperaMorelia-Radiosa"},
    {name = "Génesis 981 Monterrey - 981 FM - XHRL-FM - Núcleo Radio Monterrey - Monterrey, Nuevo León", url = "https://streamingcwsradio30.com/8238/stream"},
    {name = "Hasta Que El Cuerpo Aguante Radio Aguascalientes - Online - Aguascalientes, AG", url = "https://s01.digitalserver.org/8110/stream"},
    {name = "Historia Y Corridos De LA COMADRE Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR06_s01AAC.aac"},
    {name = "Hits 885 Tampico - 885 FM - XHFW-FM - Multimedios Radio - Tampico, Tamaulipas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHFWAAC.aac"},
    {name = "Hits Chihuahua - 1037 FM - XHHEM-FM - Multimedios Radio - Chihuahua, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCHAFMAAC.aac"},
    {name = "HITS CHIHUAHUA 1037 FM Stream Updated", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHHEMFM.mp3"},
    {name = "Hits Monterrey - 1061 FM - XHITS-FM - Multimedios Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/HITS106AAC.aac"},
    {name = "Hits Torreón - 931 FM - XHCTO-FM - Multimedios Radio - Torreón, Coahuila", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCTOFM_SC"},
    {name = "Horizonte Ciudad De México - 1079 FM - XHIMR-FM - IMER - Ciudad De México", url = "http://s2.mexside.net/8014/stream"},
    {name = "HR URBANO", url = "http://jpdofunk3.com.br:8098/stream"},
    {name = "Imagen Mexicali - 1055 FM - XHCMS-FM - Grupo Imagen - Mexicali, Baja California", url = "http://mexicali.radio.wnsol.com:8340/"},
    {name = "Imagen Radio", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XEDAFM.mp3"},
    {name = "Imagen Radio 905", url = "http://provisioning.streamtheworld.com/pls/XEDAFM.pls"},
    {name = "Imagen Radio Bajío - 1059 FM [San Miguel De Allende, Guanajuato]", url = "http://radio.alphamx.net:8130/;stream.mp3"},
    {name = "Imagen Radio Guadalajara - 939 FM [Guadalajara, Jalisco]", url = "http://radio.wnsol.com:8240/;stream.mp3"},
    {name = "Imagen Radio Laguna - 1003 FM", url = "http://radio.wnsol.com:8068/;stream.mp3"},
    {name = "Imagen Radio Monterrey - 1077 FM [San Pedro Garza García, Nuevo León]", url = "http://monterrey.radio.wnsol.com:8260/;stream.mp3"},
    {name = "Imagen Radio Puebla - 1051 FM [Puebla, Puebla]", url = "http://puebla.radio.wnsol.com:8280/;stream.mp3"},
    {name = "Imagen Radio Querétaro - 947 FM [Querétaro, Querétaro]", url = "http://radio.wnsol.com:8070/;stream.mp3"},
    {name = "Imagen Radio Tamaulipas - 1031 FM [Tampico, Tamaulipas]", url = "http://tampico.radio.wnsol.com:8300/;stream.mp3"},
    {name = "Imagen Radio Veracruz - 925 FM - XHQRV-FM - Grupo Imagen - Veracruz, Veracruz", url = "http://veracruz.radio.wnsol.com:8310/stream"},
    {name = "Imperio - Corridos, Corridos Y Mas", url = "http://ice55.securenetsystems.net/DASH27"},
    {name = "Infonor Radio - Online [Saltillo, Coahuila]", url = "https://infonor.out.airtime.pro/infonor_a"},
    {name = "Inolvidable Jerez - 907 FM - XHJRZ-FM - Grupo Radiofónico ZER - Jerez, ZA", url = "https://cast.zuperdns.net/8014/stream"},
    {name = "Instrumental Hits Radio", url = "http://162.244.81.98:8130/listen"},
    {name = "Interferencia 1057 HD3 IMER", url = "https://s2.mexside.net/8022/stream"},
    {name = "Internet Public Radio", url = "https://c11.radioboss.fm:18270/stream"},
    {name = "Jalisco Radio", url = "https://sp2.servidorrprivado.com/8136/stream"},
    {name = "Jalisco Radio FM Ciudad Guzmán - 1071 FM - XHCGJ-FM - Gobierno Del Estado De Jalisco - Ciudad Guzmán, JC", url = "https://sp2.servidorrprivado.com/8136/cdadguzman"},
    {name = "Jalisco Radio FM Guadalajara - 963 FM - XEJB-FM - Gobierno Del Estado De Jalisco - Guadalajara, JC", url = "https://sp2.servidorrprivado.com/8136/guadalajarafm"},
    {name = "K Digital - 1027 FM - XHPQUI-FM - Tequisquiapan, Querétaro", url = "https://stream3.mexiserver.com:10167/stream?type=http&nocache=842;"},
    {name = "KE Navojoa - 1045 FM - XHKE-FM - Uniradio - Navojoa, Sonora", url = "https://streamingcwsradio30.com:7031/stream"},
    {name = "Kiuu - 911 FM [Torreón, Coahuila]", url = "https://streamingcwsradio30.com/8232/stream"},
    {name = "Kiuu Torreón - 911 FM - XHTC-FM - GREM Grupo Radio Estéreo Mayran - Torreón, Coahuila", url = "http://streamingcwsradio30.com/8232/stream"},
    {name = "KY Guadalajara - 947 FM - XHDK-FM - Grupo Audiorama Comunicaciones - Guadalajara, Jalisco", url = "https://ss1.audiorama.com.mx:6576/stream"},
    {name = "KY Magdalena De Kino - 907 FM - XHLDC-FM - Grupo Audiorama Comunicaciones - Magdalena De Kino, Sonora", url = "https://ss1.audiorama.com.mx:6620/stream"},
    {name = "KY Navojoa - 955 FM - XHNAS-FM - Grupo Audiorama Comunicaciones - Navojoa, Sonora", url = "https://ss1.audiorama.com.mx:6680/stream"},
    {name = "KY Nogales - 903 FM - XHXW-FM - Grupo Audiorama Comunicaciones - Nogales, Sonora", url = "https://ss1.audiorama.com.mx:6586/stream"},
    {name = "Ké Buena - 975 FM - KBNA-FM - Grupo Radio Centro - El Paso, Texas Ciudad Juárez, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KBNA975_FMAAC.aac"},
    {name = "La 99 Cuernavaca - 991 FM - XHMOR-FM - Grupo Diario De Morelos - Yautepec Cuernavaca, MO", url = "http://163.172.209.91:9175/live"},
    {name = "La Acerera Monclova - 881 FM 560 AM - XHGIK-FM XEGIK-AM - Grupo Kamar - Monclova, CO", url = "https://tv.radiohosting.online:8480/stream"},
    {name = "La B Grande De México Ciudad De México - 1220 AM - XEB-AM - IMER - Ciudad De México", url = "https://s2.mexside.net/8024/stream"},
    {name = "La Bestia Grupera 540 CDMX - 540 AM - XEWF-AM - Grupo Audiorama Comunicaciones - Ciudad De México", url = "https://ss1.audiorama.com.mx:6584/"},
    {name = "La Bestia Grupera Cancún - 915 FM 630 AM - XHCCQ-FM XECCQ-AM - Grupo Audiorama Comunicaciones - Cancún, Quintana Roo", url = "https://ss1.audiorama.com.mx:6672/;"},
    {name = "La Bestia Grupera Chihuahua - 993 FM - XHRPC-FM - Grupo Audiorama Comunicaciones - Chihuahua, CH", url = "https://ss1.audiorama.com.mx:6646/"},
    {name = "La Bestia Grupera Chilpancingo - 997 FM - XHEPI-FM - Grupo Audiorama Comunicaciones - Chilpancingo, GR", url = "https://ss1.audiorama.com.mx:6614/stream"},
    {name = "La Bestia Grupera Ciudad De México - 540 AM - XEWF-AM - Radiorama Grupo Audiorama Comunicaciones - Ciudad De México", url = "https://ss1.audiorama.com.mx:6584/stream"},
    {name = "La Bestia Grupera Cuautla - 1045 FM - XHCU-FM - Grupo Audiorama Comunicaciones - Cuautla, MO", url = "https://ss1.audiorama.com.mx:6624/"},
    {name = "La Bestia Grupera Culiacán - 1025 FM - XHWS-FM - Grupo RSN - Culiacán, SI", url = "https://sp3.servidorrprivado.com:10935/"},
    {name = "La Bestia Grupera Córdoba - 961 FM - XHSIC-FM - Radiorama - Córdoba, VE", url = "https://ss1.audiorama.com.mx:6656/"},
    {name = "La Bestia Grupera Guadalajara - 891 FM - XHGDA-FM - Grupo Audiorama Comunicaciones - Guadalajara, JC", url = "https://ss1.audiorama.com.mx:6630/guadalajara"},
    {name = "La Bestia Grupera León - 903 FM - XHML-FM - Grupo Audiorama Comunicaciones - León, Guanajuato", url = "https://ss1.audiorama.com.mx:6636/stream"},
    {name = "La Bestia Grupera Mexicali - 923 FM - XHMMF-FM - Grupo Audiorama Comunicaciones - Mexicali, Baja California", url = "https://ss1.audiorama.com.mx:6592/stream"},
    {name = "La Bestia Grupera Nogales - 1035 FM - XHRZ-FM - Grupo Audiorama Comunicaciones - Nogales, Sonora", url = "https://ss1.audiorama.com.mx:6638/stream"},
    {name = "La Bestia Grupera Tecomán - 905 FM - XHECO-FM - Radiorama Grupo Audiorama Comunicaciones - Tecomán, Colima", url = "https://ss1.audiorama.com.mx:6578/stream"},
    {name = "La Bestia Toluca - 1037 FM - XHQY-FM - Toluca, Estado De México", url = "http://s1.audiorama.mx:6660/"},
    {name = "La Bonita Del Norte Río Grande - 927 FM - XHPRGZ-FM - Comunicaciones JFJ - Río Grande, Zacatecas", url = "https://stream3.mexiserver.com:10131/;"},
    {name = "La Caliente - 923 FM [Torreón Coahuila]", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHTRRFM_SC.mp3?dist=MULTIMEDIOS-WEB"},
    {name = "La Caliente Chihuahua - 909 FM - XHAHC-FM - Multimedios Radio - Chihuahua, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHAHCFMAAC.aac"},
    {name = "La Caliente Delicias - 905 FM - XHHM-FM - GRD Multimedia - Delicias, Chihuahua", url = "https://streamingcwsradio30.com:7077/;"},
    {name = "La Caliente Ensenada - 921 FM - XHHC-FM - Multimedios Radio - Ensenada, Baja California", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHHCFMAAC.aac"},
    {name = "La Caliente Monterrey - 941 FM - XET-FM - Multimedios Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XETFMAAC.aac"},
    {name = "La Caliente Reynosa - 931 FM - XHAAA-FM - Multimedios Radio - Reynosa, Tamaulipas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHAAAFMAAC.aac"},
    {name = "La Caliente Tepic - 1057 FM - XHXT-FM - Multimedios Radio - Tepic, Nayarit", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHXTFMAAC.aac"},
    {name = "La Cañona Escuinapa", url = "https://sp2.servidorrprivado.com/8112/stream"},
    {name = "LA COMADRE - 1260 AM - XEL-AM - Grupo ACIR - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XELAMAAC.aac"},
    {name = "LA COMADRE 1055 Puebla - 1055 FM - XHHIT-FM - Grupo ACIR - Puebla, Puebla", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEHITAAC.aac"},
    {name = "LA COMADRE 985 Culiacán - 985 FM - XHCLI-FM - Grupo ACIR - Culiacán, Sinaloa", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCLIFMAAC.aac"},
    {name = "La Comadre Orizaba - 1003 FM - XHPP-FM - Grupo Radio Digital - Orizaba, VE", url = "http://hd.digitalradio.mx:6121/lacomadre"},
    {name = "La Comadre Pa Bailar Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR08_s01AAC.aac"},
    {name = "La Ele Fresnillo - 951 FM - XHEL-FM - Torres Corporativo - Fresnillo, ZA", url = "https://radioforte.com/8008/stream"},
    {name = "La Favorita", url = "http://streamvortex.com:10500/listen.pls?sid=1"},
    {name = "LA FIERA Veracruz - 941 FM - XHHV-FM - Grupo Pazos - Veracruz, Veracruz", url = "https://sg.centrocibernetico.com/lafiera"},
    {name = "La FQ", url = "https://s2.mexside.net/8056/stream"},
    {name = "La Gran AW Monterrey - 1013 FM - XHAW-FM - Multimedios Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHAWFM_SC.mp3"},
    {name = "La Grande De Tabasco Villahermosa - 897 FM - XHVX-FM - Grupo VX - Villahermosa, TB", url = "http://radio.golsystems.com.mx:8202/"},
    {name = "La Grande Del Sureste 903", url = "https://stream.freepi.io/8302/live"},
    {name = "La Grande Río Grande - 971 FM - XHZC-FM - Río Grande, ZA", url = "https://radioforte.com/8004/stream"},
    {name = "La Interesante 885 Los Mochis", url = "https://radio.reaktorweb.com/8024/stream"},
    {name = "La Interesante 945 Guasave", url = "https://radio.reaktorweb.com/8128/stream"},
    {name = "La Invasora Aguascalientes - 989 FM - XHERO-FM - Radiogrupo - Aguascalientes, AG", url = "http://201.159.48.105:8080/"},
    {name = "La Invasora Perote - 889 FM - XHBE-FM - Molina Comunicaciones - Perote, Veracruz", url = "https://sp2.servidorrprivado.com/8244/stream;"},
    {name = "La Invasora San Diego - XHTY-FM - 997 FM - Uniradio - Tijuana, Baja California", url = "https://streamingcwsradio30.com:7022/stream"},
    {name = "La Invasora Tijuana - XHA-FM - 945 FM - Uniradio - Tijuana, Baja California", url = "https://streamingcwsradio30.com:7023/stream"},
    {name = "La J Mexicana - 970 AM - XEJ-AM - Grupo Audiorama Comunicaciones - Ciudad Juárez, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEJ_AMAAC.aac"},
    {name = "La Jefa Camargo - 961 FM - XHEOH-FM - Camargo, Chihuahua", url = "https://dattavolt.com/8266/stream"},
    {name = "La Kaliente Aguascalientes - 1029 FM - XHEY-FM - Grupo Radiofónico ZER - Aguascalientes, AG", url = "https://cast.zuperdns.net/8024/stream/"},
    {name = "La Kaliente Ciudad Obregón - 929 FM - XHGON-FM - Grupo Radio SA - Ciudad Obregón, Sonora", url = "https://tuasesorweb.com:2000/stream/GruperaObregon/stream"},
    {name = "La Ke Buena Acayucan - 939 FM - XHEVZ-FM - Acayucan, VE", url = "https://secure.radiorama.mx:2170/"},
    {name = "La Ke Buena Campeche - 1027 FM - XHAC-FM - NCS Núcleo Comunicación Del Sureste - Campeche, CM", url = "https://sp2.servidorrprivado.com:10887/"},
    {name = "La Ke Buena Colima - 955 FM - XHCMM-FM - 955 FM - Luna Medios - Coalcomán, Michoacán", url = "https://radios.lunamedios.mx:8308/;"},
    {name = "La Ke Buena El Fuerte", url = "https://radio.reaktorweb.com/8132/stream"},
    {name = "La Ke Buena Guadalajara - 971 FM - XEBA-FM - Radiópolis - Guadalajara, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KEBUENA_GDLAAC.aac"},
    {name = "La Ke Buena Hidalgo - 1067 FM - XHQH-FM - Ixmiquilpan, Hidalgo", url = "http://cdn.instream.audio:9221/stream"},
    {name = "La Ke Buena Monterrey - 1037 FM - XHFMTU-FM - Multimedios Radio - Monterrey, Nuevo León", url = "https://mm.streamguys1.com/lakebuena-icy"},
    {name = "La Ke Buena Quiroga - XHPQGA-FM - 889 FM - Grupo Vox - Quiroga, Michoacán", url = "http://s4.mexside.net:8296/;"},
    {name = "La Kebuena Tuxtla 1001 FM", url = "https://stream.freepi.io/8306/live"},
    {name = "La Ley 1063", url = "https://audio.livecastnet.com:2555/stream"},
    {name = "La Ley Ojinaga - 1025 FM - XHHIH-FM - Sistema Radio Lobo - Ojinaga, Chihuahua", url = "http://162.212.56.146:9392/;"},
    {name = "La Lupe 640 Ciudad Juárez", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEJUAAM.mp3"},
    {name = "La Lupe 883 Fm Tepic", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPCTNFM_SC.mp3"},
    {name = "La Lupe Chihuahua - 1045 FM - XHCHA-FM - Multimedios Radio - Chihuahua, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHHEMFMAAC.aac"},
    {name = "La Lupe Ciudad Victoria - 953 FM - XHLRS-FM - Multimedios Radio - Ciudad Victoria, Tamaulipas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHLRSFMAAC.aac"},
    {name = "La Lupe Cuauhtémoc - 1033 FM - XHPCCC-FM - Multimedios Radio - Cuauhtémoc, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPCCCFMAAC.aac"},
    {name = "La Lupe Culiacán - 907 FM - XHCCCC-FM - Multimedios Radio - Culiacán, Sinaloa", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCCCCFMAAC.aac"},
    {name = "La Lupe Durango - 1029 FM - XHRPU-FM - Multimedios Radio - Durango, Durango", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRPU_FMAAC.aac"},
    {name = "La Lupe Ensenada - 947 FM - XHPENS-FM - Multimedios Radio - Ensenada, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHHCFM_SC"},
    {name = "La Lupe Fortín - 895 FM - XHFTI-FM - Multimedios Radio - Fortín De Las Flores, Veracruz", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHFTIFMAAC.aac"},
    {name = "La Lupe Guadalajara - 999 FM - XHKB-FM - Multimedios Radio - Guadalajara, Jalisco", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHKB_FMAAC.aac"},
    {name = "La Lupe León - 967 FM - XHPEBJ-FM - Multimedios Radio - León, Guanajuato", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPEBJFMAAC.aac"},
    {name = "La Lupe Linares - 1049 FM - XHLN-FM - Multimedios Radio - Linares, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHLNFMAAC.aac"},
    {name = "La Lupe Mazatlán - 921 FM - XHPMAZ-FM - Multimedios Radio - Mazatlán, Sinaloa", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHNMAZFMAAC.aac"},
    {name = "La Lupe Nuevo Laredo - 967 FM - XHGNK-FM - Multimedios Radio - Nuevo Laredo, Tamaulipas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHGNKFMAAC.aac"},
    {name = "La Lupe Parral - 1017 FM - XHHPR-FM - Multimedios Radio - Parral, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHHPRFMAAC.aac"},
    {name = "La Lupe San Luis Potosí - 1049 FM - XHCZ-FM - Multimedios Radio - San Luis Potosí, San Luis Potosí", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCZFMAAC.aac"},
    {name = "La Lupe Tampico - 949 FM - XHTW-FM - Multimedios Radio - Tampico, TM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHTW_SC"},
    {name = "La Lupe Tepic - 883 FM - XHPCTN-FM - Multimedios Radio - Compostelatepic, Nayarit", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPCTNFMAAC.aac"},
    {name = "La Lupe Tijuana - 953 FM - XHHIT-FM - Multimedios Radio - Tijuana, Baja California", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHHITFMAAC.aac"},
    {name = "La Lupe Xalapa - 1009 FM - XHPALV-FM - Multimedios Radio - Xalapa, Veracruz", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPALVFMAAC.aac"},
    {name = "La Líder Ameca - 991 FM - XHED-FM - Ameca, Jalisco", url = "https://sp3.servidorrprivado.com:10865/"},
    {name = "La Líder Stereo ZER Zacatecas - 965 FM - XHZER-FM - Grupo Radiofónico ZER - Zacatecas, ZA", url = "https://cast.zuperdns.net/8006/stream"},
    {name = "La Mejor 993 Tepic", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCCBFM.mp3"},
    {name = "La Mejor Acapulco - 1001 FM - XHSE-FM - MVS Radio - Acapulco, GR", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHSE_SC.aac"},
    {name = "La Mejor Ciudad Acuña - 1007 FM - XHHAC-FM - RCG Media - Ciudad Acuña, Coahuila", url = "https://radio.rcg.com.mx:7008/"},
    {name = "La Mejor Ciudad Obregón - 1033 FM - XHVJS-FM - Radio Grupo García De León - Ciudad Obregón, SO", url = "https://streamingcwsradio30.com:7058/;"},
    {name = "La Mejor Cuernavaca - 973 FM - XHVZ-FM - MVS Radio - Cuernavaca, MO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHVZ_SC"},
    {name = "La Mejor Culiacán - 1041 FM - XHECQ-FM - GPM Grupo Promomedios - Culiacán, SI", url = "https://icy.gvstream.live/gpm-cq.aac"},
    {name = "La Mejor Durango - 1037 FM - XHDGO-FM - Grupo Radio Carlos C Armas Vega - Durango, DG", url = "https://stream3.mexiserver.com:10055/stream"},
    {name = "La Mejor Ensenada - 1033 FM - XHENA-FM - MVS Radio - Ensenada, Baja California", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHENAAAC.aac"},
    {name = "La Mejor Estéreo Gallito - 971 FM [Torreón, Coahuila]", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPE_SC?"},
    {name = "La Mejor Fresnillo - 1079 FM - XHEMA-FM - Grupo Radiofónico B-15 - Fresnillo, ZA", url = "http://ais-sa2.cdnstream1.com/2384_128.mp3"},
    {name = "La Mejor Hermosillo - 985 FM - XHBH-FM - MVS Radio - Hermosillo, SO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHBH_SC"},
    {name = "La Mejor León - 999 FM - XHSO-FM - MVS Radio - León, GT", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHSOFM_SC"},
    {name = "La Mejor Los Mochis - 909 FM - XHHS-FM - Grupo RSN - Los Mochis, SI", url = "https://sp3.servidorrprivado.com:10929/"},
    {name = "La Mejor Mazatlán - 1027 FM - XHHW-FM - Grupo RSN - Mazatlán, SI", url = "http://167.114.116.223:1093/;"},
    {name = "La Mejor Mexicali - 1033 FM - XHVG-FM - MVS Radio - Mexicali, BC", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XHVGFM_SC"},
    {name = "La Mejor Oaxaca - 1017 FM - XHZB-FM - ORO Organización Radiofónica De Oaxaca - Oaxaca, OA", url = "http://ororadio.serverroom.us:9142/;stream.mp3"},
    {name = "La Mejor Puerto Escondido - 941 FM - XHEDO-FM - Puerto Escondido, OA", url = "https://stream9.mexiserver.com:7120/"},
    {name = "La Mejor Puerto Vallarta - 999 FM - XHCJX-FM - MVS Radio - Puerto Vallarta, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCJX_SC"},
    {name = "La Mejor Reynosa - 590 AM - XEFD-AM - Grupo Gape Radio - Reynosa, TM", url = "https://stream.zenolive.com/zr5fhpha568uv.m3u"},
    {name = "La Mejor Saltillo - 1025 FM - XHSHT-FM - MVS Radio - Saltillo, Coahuila", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHSHTAAC.aac"},
    {name = "La Mejor San Luis Potosí - 909 FM - XHWZ-FM - MG Radio - San Luis Potosí, San Luis Potosí", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHWZAAC.aac"},
    {name = "La Mejor Tampico - 1001 FM - XHJT-FM - MVS Radio - Tampico, TM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHJT_SC"},
    {name = "La Mejor Tehuacán - 1007 FM - XHGY-FM - Radioth Comunicaciones - Tehuacán, PU", url = "http://www.pump.com.mx:8030/"},
    {name = "La Mejor Tijuana - 907 FM - XHTIM-FM - MVS Radio - Tijuana, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHTIMAAC.aac"},
    {name = "La Mejor Tuxtepec - 1065 FM - XHXP-FM - ORP - Tuxtepec, OA", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHXP_SC"},
    {name = "La Mejor Veracruz - 1005 FM - XHVE-FM - MVS Radio - Veracruz, VE", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHVEFMAAC.aac"},
    {name = "La Mera Jefa 937 Guasave", url = "http://192.99.16.17:8804/stream.mp3"},
    {name = "La Mexicana 923 Culiacán", url = "https://sp2.servidorrprivado.com:10860//;stream.nsv"},
    {name = "La Mexicana Los Mochis - 933 FM - XHCF-FM - Grupo RSN - Los Mochis, SI", url = "http://167.114.116.223:1044/"},
    {name = "La Morrita 961 Los Mochis", url = "https://audiostreaming.luz.network/stream/19/;"},
    {name = "La Morrita 971 Mazatlán", url = "https://audiostreaming.luz.network/stream/11/;"},
    {name = "La Más Picuda 937 FM Acapulco", url = "https://radiovision.mi-radio.stream:11006/;"},
    {name = "La Nuestra Navojoa - 1270 AM - XEGL-AM - 642 Media - Navojoa, SO", url = "https://s5.mexside.net:8018/stream"},
    {name = "La Numero Uno 1049 FM", url = "http://13806.cloudrad.io:9260/live/;"},
    {name = "LA OCTAVA SPORTS - 1073 HD2 - XEQR-FM - Grupo Radio Centro - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XERC_AM_SC"},
    {name = "La Patrona - 899 FM [Bocoyna, Chihuahua]", url = "https://streamingcwsradio30.com/8130/stream"},
    {name = "La Patrona Escuinapa - 925 FM 570 AM - XHETD-FM XETD-AM - Alica Medios - Escuinapa, SI", url = "http://www.radiohosting.online/stream/?puerto=9884"},
    {name = "La Poderosa Aguascalientes - 1077 FM - XHYZ-FM - Radiogrupo - Aguascalientes, AG", url = "http://201.159.48.105:2871/"},
    {name = "La Poderosa Ciudad Acuña - 1570 AM - XERF-AM - IMER - Ciudad Acuña, Coahuila", url = "https://s2.mexside.net/8064/stream"},
    {name = "La Poderosa Tijuana - 860 AM - XEMO-AM - Uniradio - Tijuana, Baja California", url = "https://streamingcwsradio30.com:7024/stream"},
    {name = "La Poderosa Veracruz - 1069 FM -XHQT-FM - Grupo Avanradio Radiorama - Veracruz, Veracruz", url = "https://s2.mexside.net/8314/stream"},
    {name = "La Popular Cacahoatán - 891 FM - XHCAH-FM - IMER - Cacahoatán, CS", url = "https://s2.mexside.net/8052/stream"},
    {name = "La Primera Saltillo - 889 FM - XHAJ-FM - Grupo Multimedia El Diario De Coahuila - Saltillo, Coahuila", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHAJFMAAC.aac"},
    {name = "La Q - 940 AM - XEQ-AM - Radiópolis - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/BESAMEAAC.aac"},
    {name = "La Radio De Tabasco 1230 AM", url = "http://streamingcwsradio30.com:8264/"},
    {name = "La Ranchera", url = "https://live.zuperdns.net/9730/stream/;stream.mp3"},
    {name = "La Ranchera Aguascalientes - 1061 FM - XHLTZ-FM - Grupo Radiofónico ZER - Aguascalientes, AG", url = "https://cast.zuperdns.net/8022/stream/"},
    {name = "La Ranchera De Monterrey - 1050 AM - XEG-AM - Núcleo Radio Monterrey - Monterrey, NL", url = "http://streamingcwsradio20.com:9410/stream"},
    {name = "La Rancherita Los Mochis - 917 FM - XHECU-FM - Grupo Radio Centro - Los Mochis, SI", url = "http://c2009.streamguys1.com/Mochis2"},
    {name = "La Raza Hermosillo - 1051 FM - XHMMO-FM - Grupo Radio SA - Hermosillo, Sonora", url = "http://tuasesorweb.com:8058/stream"},
    {name = "La Raza Los Reyes - 925 FM - XHGQ-FM - Los Reyes, MI", url = "http://radiohosting.online:8574/stream"},
    {name = "La Reverenda - 937 FM - XHMRI-FM - Grupo Rivas - Mérida, YU", url = "https://s2.mexside.net:7080/"},
    {name = "La Reverenda De Oriente - 919 FM - XHMET-FM - Grupo Rivas - Temozón, YU", url = "https://s2.mexside.net:7082/"},
    {name = "La Sabrosita Monterrey - 957 FM - XHRK-FM - Grupo Radio Alegría - Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LASABROSITA_957FMAAC.aac"},
    {name = "La Santa - 919 FM [Torreón, Coahuila]", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCCAW.mp3"},
    {name = "La Sonora De Nogales - 1043 FM - XHAZE-FM - Nogales, Sonora", url = "https://stream9.mexiserver.com/8066/stream"},
    {name = "La Suavecita - 939 FM - KINT-FM - Entravision Communications - Ciudad Juárez, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KINTFMAAC.aac"},
    {name = "La Super KT Tecate - 885 FM - XHKT-FM - California Medios - Tecate, Baja California", url = "https://s2.mexside.net/8222/stream"},
    {name = "La Supersonica", url = "https://c11.radioboss.fm:8093/stream"},
    {name = "La T Grande Monterrey - 990 AM - XET-AM - Multimedios Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XETAMAAC.aac"},
    {name = "La Tapatía Guadalajara - 1035 FM - XHRX-FM - Radiorama - Guadalajara, JC", url = "http://192.99.16.17:3412/"},
    {name = "La Voz Del Pitic - 881 FM - XHRMO-FM - Democracia Y Deliberación Desértica, AC - Hermosillo, SO", url = "https://s5.mexside.net:8080/stream"},
    {name = "La Voz Zacatecas - 961 FM - XHGPE-FM - Grupo Imagenzac - Guadalupe, ZA", url = "https://sp2.servidorrprivado.com:10800/"},
    {name = "La Z 965 Los Mochis", url = "http://c2009.streamguys1.com/Mochis1"},
    {name = "La Z Ciudad Juárez - 1035 FM 720 AM - XHEM-FM XEJCC-AM - Grupo Audiorama Comunicaciones - Ciudad Juárez, Chihuahua", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHEM_FMAAC.aac"},
    {name = "La Z Morelia - 963 FM 1340 AM - XHCR-FM XECR-AM - Grupo TRENU - Morelia, MI", url = "http://srmx.ddns.net:8100/;"},
    {name = "La Zeta Hermosillo - 939 FM - XHMV-FM - Uniradio - Hermosillo, Sonora", url = "https://streamingcwsradio30.com:7027/stream?type=http&nocache=1"},
    {name = "La Zeta Navojoa - 889 FM - XHENS-FM - Uniradio - Navojoa, SO", url = "https://streamingcwsradio30.com:7032/stream"},
    {name = "La Única Fresnillo - 1033 FM - XHIH-FM - Torres Corporativo - Fresnillo, ZA", url = "https://radioforte.com/8006/stream"},
    {name = "Laredo Classic Hits Nuevo Laredo 1073 XHGTS-FM", url = "http://216.251.65.78:8000/"},
    {name = "Latidos FM - Online - Wwwlunamedioscom - Luna Medios - Colima, Colima", url = "https://rr5100.globalhost1.com/8002/stream"},
    {name = "Let It Beat Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR27_s01AAC.aac"},
    {name = "Like FM Cuauhtémoc - 983 FM - XHDT-FM - GRD Multimedia - Cuahtémoc, Chihuahua", url = "https://streamingcwsradio30.com:7085/;"},
    {name = "Like FM Delicias - 1013 FM - XHBN-FM - GRD Multimedia - Delicias, Chihuahua", url = "https://streamingcwsradio30.com:7082/;"},
    {name = "Lobos - 1035 FM [Hermosillo, Sonora]", url = "http://streamingcwsradio20.com:9422/;stream.mp3"},
    {name = "Lobos - 941 FM [Durango, Durango]", url = "http://streamingcwsradio10.com:9300/;stream.mp3"},
    {name = "Lobos - 955 FM [Zacatecas, Zacatecas]", url = "http://streamingcwsradio20.com:9420/;stream.mp3"},
    {name = "Lobos - 973 FM [Los Mochis, Sinaloa]", url = "http://streamingcwsradio20.com:9418/;stream.mp3"},
    {name = "Lobos FM Culiacán", url = "http://streamingcwsradio20.com:9330/;"},
    {name = "Lobos FM Laguna - 887 FM - XHLUAD-FM - Universidad Autónoma De Durango - Gómez Palacio, DG", url = "http://streamingcwsradio10.com:9302/"},
    {name = "Lokura 830 CDMX - 830 AM - XEITE-AM - Capital Media - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEITEAAC.aac"},
    {name = "Lokura FM Cancún - 993 FM - XHCQR-FM - Capital Media - Cancún, Quintana Roo", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCQRAAC.aac"},
    {name = "Lokura FM Ixtapan De La Sal - 995 FM - XHXI-FM - Capital Media - Ixtapan De La Sal, Estado De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHXIAAC.aac"},
    {name = "Lokura FM Morelia - 973 FM - XHORE-FM - Capital Media - Morelia, MI", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHOREAAC.aac"},
    {name = "Lokura FM Playa Del Carmen - 1063 FM - XHLAYA-FM - Capital Media - Playa Del Carmen, Quintana Roo", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHLAYAAAC.aac"},
    {name = "Lokura FM Toluca - 893 FM - XHCH-FM - Capital Media - Toluca, Estado De México", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XECHAAC.aac"},
    {name = "Los 40 Principales México", url = "http://provisioning.streamtheworld.com/pls/LOS40_MEXICO.pls"},
    {name = "LOS40", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_MEXICO_SC"},
    {name = "LOS40 Agua Prieta - 999 FM - XHNNO-FM - Grupo Radiofónico ZER - Agua Prieta, SO", url = "https://live.zuperdns.net/9990/stream/;stream.mp3"},
    {name = "LOS40 Aguascalientes - 957 FM - XHAGA-FM - Grupo Radiofónico Zer - Aguascalientes, Aguascalientes", url = "https://cast.zuperdns.net/8030/stream/;stream.mp3"},
    {name = "LOS40 Cuernavaca - 965 FM - XHJMG-FM - Grupo Mundo Comunicaciones - Cuernavaca, Morelos", url = "https://tv.radiohosting.online:8556/stream"},
    {name = "LOS40 Delicias - 1005 FM - XHBZ-FM - Sigma Radio - Delicias, Chihuahua", url = "http://sigmaradio.stream:9004/index?ver=249101"},
    {name = "LOS40 Ensenada - 969 FM - XHPSEN-FM - Radiópolis - Ensenada, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_ENSENADAAAC.aac"},
    {name = "LOS40 Guadalajara - 1027 FM - XEHL-FM - Radiópolis - Guadalajara, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_GDLAAC.aac"},
    {name = "LOS40 León - 931 FM - XHERZ-FM - Grupo Audiorama Comunicaciones - León, GT", url = "https://ss1.audiorama.com.mx:6634/"},
    {name = "LOS40 Mexicali - 907 FM - XHMOE-FM - Radiópolis - Mexicali, BC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_MEXICO2AAC.aac"},
    {name = "LOS40 Monterrey - 885 FM - XHWAG-FM - Radiópolis - Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_MTYAAC.aac"},
    {name = "LOS40 Playa Del Carmen - 961 FM - XHPPLY-FM - Cancún Playa Del Carmen, QR", url = "http://stream.zenolive.com/8pnsdde1sy8uv.m3u"},
    {name = "LOS40 Puerto Vallarta - 911 FM - XHPTOJ-FM - Radiópolis - Puerto Vallarta, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_VALLARTAAAC.aac"},
    {name = "LOS40 RGV Matamoros - 977 FM - XEEW-FM - Radiodual - Matamoros, TM", url = "http://radio.alphamx.net:8104/stream"},
    {name = "LOS40 Tuxtla 961", url = "https://stream.freepi.io/8308/live"},
    {name = "LOS40 Veracruz - 989 FM - XHWB-FM - Radiópolis - Veracruz, VE", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_VERAAC.aac"},
    {name = "LOUD Metal Radio Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR37_s01AAC.aac"},
    {name = "Love FM Chihuahua - 901 FM - XHUA-FM - Grupo Audiorama Comunicaciones - Chihuahua, CH", url = "https://ss1.audiorama.com.mx:6650/"},
    {name = "Love FM Guanajuato - 1015 FM - XHVLO-FM - Grupo Audiorama Comunicaciones - Guanajuato, GT", url = "https://ss1.audiorama.com.mx:6632/"},
    {name = "Love FM León - 1015 FM - XHVLO-FM - Grupo Audiorama Comunicaciones - León, Guanajuato", url = "https://ss1.audiorama.com.mx:6632/stream"},
    {name = "Love FM Tepic - 961 FM - XHEOO-FM - Grupo Audiorama Comunicaciones - Tepic, Nayarit", url = "https://ss1.audiorama.com.mx:6684/stream"},
    {name = "Lupe Zacatecas - 933 FM - XHEXZ-FM - Grupo Radiofónico ZER - Guadalupe, ZA", url = "https://cast.zuperdns.net/8010/stream/"},
    {name = "Magia 101 Aguascalientes - 1017 FM - XHUNO-FM - Radiogrupo - Aguascalientes, AG", url = "http://201.159.48.107:8080/"},
    {name = "Mas Flo Tijuana - 1077 FM - XHRST-FM - MLC Media - Tijuana, Baja California", url = "https://vsstreaming.com/8026/stream"},
    {name = "Mas Radio - 1079 FM - KCKO-FM - Mas Medios Nogales - Nogales, Sonora", url = "https://s5.mexside.net:8000/stream"},
    {name = "MATCH 1001 Culiacán - 1001 FM - XHCNA-FM - Grupo ACIR - Culiacán, Sinaloa", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCNAFMAAC.aac"},
    {name = "Match 895 FM Puerto Vallarta", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMEFMAAC.aac"},
    {name = "MATCH 975 León - 975 FM - XHPQ-FM - Grupo ACIR - León, Guanajuato", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPQFMAAC.aac"},
    {name = "MATCH 979 Querétaro - 979 FM - XHQTO-FM - Grupo ACIR - Querétaro, Querétaro", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHQTOAAC.aac"},
    {name = "Match Guadalajara - 903 FM - XHEMIA-FM - Grupo ACIR - Guadalajara, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEMIAAAC.aac"},
    {name = "Match Morelia - 939 FM - XHMO-FM - Morelia, MI", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMOFMAAC.aac"},
    {name = "Match Puebla - 901 FM - XHRS-FM - Grupo ACIR - Puebla, PU", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRSFMAAC.aac"},
    {name = "Maxiradiofm", url = "https://server1.maxiradiofm.com:8000/radio.mp3"},
    {name = "Media News 927 FM", url = "https://streamingcwsradio30.com:7061/;"},
    {name = "Mega 949 FM", url = "http://streamingcwsradio30.com:8262/"},
    {name = "Mega FM Tenosique -1029 FM - XHTQE-FM - CORAT Comisión De Radio Y Televisión De Tabasco - Tenosique, TB", url = "http://streamingcwsradio30.com:8262/mega"},
    {name = "Mega FM Villahermosa - 949 FM - XHTVH-FM - CORAT Comisión De Radio Y Televisión De Tabasco - Villahermosa, TB", url = "http://streamingcwsradio30.com:8262/stream"},
    {name = "Mexiquense Radio Amecameca - 917 FM - XHMEC-FM - Sistema Mexiquense De Medios Públicos - Amecameca, EM", url = "https://streamingcwsradio30.com:7047/;"},
    {name = "Mexiquense Radio Metepec - 1600 AM - XEGEM-AM - Sistema Mexiquense De Medios Públicos - Metepec, Estado De México", url = "https://streamingcwsradio30.com:7046/"},
    {name = "Mexiquense Radio Metepec - 917 FM - XHGEM-FM - Sistema Mexiquense De Medios Públicos - Metepec, EM", url = "https://streamingcwsradio30.com:7019/;"},
    {name = "Mexiquense Radio Valle De Bravo - 1045 FM - XHVAL-FM - Sistema Mexiquense De Medios Públicos - Valle De Bravo, EM", url = "https://streamingcwsradio30.com:7048/;"},
    {name = "Mexiquense Radio Zumpango - 885 FM - XHZUM-FM - Sistema Mexiquense De Medios Públicos - Zumpango, EM", url = "https://streamingcwsradio30.com:7049/mexiquense"},
    {name = "Milenio Radio Monterrey - 1037 HD3 - XHFMTU-FM - Multimedios Radio - Monterrey, Nuevo León", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/FMTU103HD3_SC"},
    {name = "Mix 927 Vallarta", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHVAYFMAAC_SC"},
    {name = "MIX Cancún - 931 FM - XHYI-FM - Grupo ACIR - Cancún, QR", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHYIFMAAC.aac"},
    {name = "MIX Cancún - 931 FM 580 AM - XHYI-FM XEYI-AM - Grupo ACIR - Cancún, QR", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XHYIFMAAC.aac"},
    {name = "MIX León - 1031 FM - XHXF-FM - Grupo ACIR - León, Guanajuato", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHXFAAC.aac"},
    {name = "MIX Morelia - 1017 FM - XHEMM-FM - Grupo ACIR - Morelia, MI", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHEMMAAC.aac"},
    {name = "MIX Pachuca - 925 FM - XHPK-FM - Grupo ACIR - Pachuca, Hidalgo", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPKFMAAC.aac"},
    {name = "MIX Puebla - 917 FM - XHRC-FM - Grupo ACIR - Puebla, Puebla", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRCFMAAC.aac"},
    {name = "MIX Puerto Vallarta - 927 FM - XHVAY-FM - Grupo ACIR - Puerto Vallarta, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHVAYFMAAC.aac"},
    {name = "MIX Toluca - 901 FM - XHENO-FM Grupo ACIR - Toluca, EM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHENOFMAAC.aac"},
    {name = "MVS Noticias - 1025 FM - XHMVS-FM - MVS Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMVSFM_SC"},
    {name = "Máxima 1067 FM", url = "http://192.99.16.17:3410/;"},
    {name = "MÁXIMA Ciudad Juárez - 991 FM - XHEPR-FM - Ciudad Juárez, Chihuahua", url = "https://streamingcwsradio30.com/8298/stream"},
    {name = "Máxima FM Cancún - 975 FM - XHCAN-FM - Grupo Radio SA - Cancún, Quintana Roo", url = "https://omegaingenieria.com:2020/stream/Maxima-Cancun"},
    {name = "Máxima FM Ciudad Del Carmen - 989 FM - XHCMN-FM - Grupo Radio SA - Ciudad Del Carmen, Campeche", url = "https://omegaingenieria.com:2020/stream/Maxima-Cd-del-Carmen"},
    {name = "Máxima FM Coatzacoalcos - 931 FM - XHCSV-FM - Grupo Radio SA - Coatzacoalcos, Veracruz", url = "https://omegaingenieria.com:2020/stream/Maxima-Coatzacoalcos"},
    {name = "Máxima FM Morelia - 1009 FM - XHI-FM - Grupo Radio SA - Morelia, Michoacán", url = "https://omegaingenieria.com:2020/stream/Maxima1009HD-Morelia"},
    {name = "Máxima FM Tapachula - 979 FM - XHMX-FM - Grupo Radio SA - Tapachula, Chiapas", url = "https://omegaingenieria.com:2020/stream/Maxima-Tapachula"},
    {name = "Máxima FM Tuxtla - 969 FM - XHKR-FM - Grupo Radio SA - Tuxtla Gutiérrez, Chiapas", url = "https://omegaingenieria.com:2020/stream/Maxima-Tuxtla"},
    {name = "Neo 1003 FM HD3 Mazatlán", url = "https://audiostreaming.luz.network/stream/15/;"},
    {name = "Neo 1013 HD3 Los Mochis", url = "https://audiostreaming.luz.network/stream/3/;"},
    {name = "Neo 941 HD3 Culiacán", url = "https://audiostreaming.luz.network/stream/9/;"},
    {name = "New Century By Match Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR04_s01AAC.aac"},
    {name = "Next FM Ciudad De México - Online - Next FM Radio - Ciudad De México", url = "https://s5.radio.co/seec9ed903/listen"},
    {name = "Nightwave Plaza", url = "http://radio.plaza.one/mp3"},
    {name = "Nuestra Radio Cristiana", url = "https://radiostreaming.privateserverid.com/8026/stream"},
    {name = "Oldies Internet Radio", url = "http://162.244.81.98:8140/listen"},
    {name = "Oldies Internet Radio - Online - Wwwoldiesinternetradiocom - Grupo Digital Retroland - Monterrey, Nuevo León", url = "https://panel.retrolandigital.com/listen/oldies_internet_radio/listen"},
    {name = "Ondas De Vida - 1440 AM - XEEST-AM - Grupo Siete - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEESTAMAAC.aac"},
    {name = "OPUS 94 945 CDMX - 945 FM - XHIMER-FM - IMER - Ciudad De México", url = "https://s2.mexside.net/8016/stream"},
    {name = "Opus 94 Ciudad De México - 945 FM - XHIMER-FM - IMER - Ciudad De México", url = "http://s2.mexside.net/8016/stream"},
    {name = "Ori Stereo Orizaba - 993 FM - XHORA-FM - Grupo Peláez Domínguez - Orizaba, Veracruz", url = "http://streamingcwsradio10.com:9316/;"},
    {name = "ORO Radio 1073 FM", url = "https://sp2.servidorrprivado.com/9318/stream"},
    {name = "Oro Radio Cananea - 1073 FM - XHSCAG-FM - Cananea Alternativa, AC - Cananea, SO", url = "http://192.99.16.17:9318/stream"},
    {name = "OYE 897 CDMX - 897 FM - XEOYE-FM - NRM Comunicaciones - Ciudad De México", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/XEOYEFMAAC.aac"},
    {name = "OYE Ciudad De México - 897 FM - XEOYE-FM - NRM Comunicaciones - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEOYEFM_SC"},
    {name = "Panda FM - Online - El Panda Zambrano - Ciudad De México", url = "http://65.21.202.84:8301/"},
    {name = "Panda Show Radio - Online - El Panda Zambrano - Ciudad De México", url = "http://65.21.202.84:8062/"},
    {name = "Planeta 997 Los Mochis", url = "http://c2009.streamguys1.com/Mochis4"},
    {name = "Polymarchs Foroactivo Radio", url = "https://turadio.accesopanel.com/8084/stream"},
    {name = "POP Extremo Navojoa - XHPJOA-FM - 981 FM - Expreso - Navojoa, SO", url = "https://www.popextremo.mx/envivo"},
    {name = "POP FM CDMX - Online - Wwwpopfmmx - Ciudad De México", url = "https://ice42.securenetsystems.net/POP"},
    {name = "Power 98 - 983 FM - XHMIX-FM - California Medios - La Rumorosa, Baja California", url = "https://s2.mexside.net/8220/stream"},
    {name = "PULSAR Tijuana - 1073 FM - XHFG-FM - Uniradio - Tijuana, Baja California", url = "https://streamingcwsradio30.com:7021/stream"},
    {name = "RADAR 1075 Querétaro - 1075 FM - XHQRO-FM - Grupo Radar - Querétaro, Querétaro", url = "https://radios.radiohd.com.mx/8268/stream"},
    {name = "RADAR 889 León - 889 FM - XHXV-FM - Grupo Radar - León, Guanajuato", url = "https://radios.radiohd.com.mx/8382/;"},
    {name = "Radiante - 911 FM [La Paz, Baja California Sur]", url = "https://streamingcwsradio30.com:7035/;"},
    {name = "Radiante 983 FM Puerto Vallarta", url = "https://streamingcwsradio30.com:7034/;"},
    {name = "RADIO 620 - 620 AM - XENK-AM - Cadena RASA - Ciudad De México", url = "https://s2.mexside.net/2102/stream"},
    {name = "Radio 710 Ciudad De México - 710 AM - XEMP-AM - IMER - Ciudad De México", url = "https://s2.mexside.net/8028/stream"},
    {name = "Radio 90S Dancemix", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR11_S01AAC.aac"},
    {name = "Radio Alegría Jalpa, Zac - 983 FM - XHFP-FM - Jalpa, ZA", url = "http://audioout.gvstream.net/radioalegria-jalpa.aac"},
    {name = "Radio Anime Nexus", url = "http://radio.animenexus.mx:8000/animenexus"},
    {name = "Radio Apostol", url = "https://sonicpanel.cloudstreaming.eu/8012/stream"},
    {name = "Radio Baladas Viejitas Pero Bonitas", url = "https://media.streamingradiomx.com/listen/radio_baladas_viejitas_bonitas/radio.mp3"},
    {name = "Radio BI Aguascalientes - 887 FM - XHBI-FM - Radiogrupo - Aguascalientes, AG", url = "http://201.159.48.107:2860/"},
    {name = "Radio BUAP - 969 FM - XHBUAP-FM - Benemérita Universidad Autónoma De Puebla BUAP - Puebla, Puebla", url = "http://148.228.50.32:8000/"},
    {name = "Radio Centro Y El Fonógrafo", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEN_AMAAC_SC.aac"},
    {name = "Radio Chetumal - 860 AM - XECTL-AM - SQCS Sistema Quintanarroense De Comunicación Social - Chetumal, Quintana Roo", url = "https://sp2.servidorrprivado.com/9132/stream"},
    {name = "Radio Chilango CDMX - 1053 FM - XHINFO-FM - Ciudad De México", url = "https://stream.radio.co/s938b68214/listen"},
    {name = "Radio Cristal 1240 AM Ciudad Juárez", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEWGAMAAC.aac"},
    {name = "Radio Disney CDMX - 921 FM - XHFO-FM - Grupo Siete - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHFOFMAAC.aac"},
    {name = "Radio Disney Mazatlán - 931 FM -XHMZT-FM - Grupo Siete - Mazatlán, Sinaloa", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHMZTFMAAC.aac"},
    {name = "Radio Disney Pachuca - 957 FM - XHMY-FM - Grupo Siete - Pachuca, Hidalg O", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPCAFMAAC.aac"},
    {name = "Radio Disney Toluca - 1021 FM - XHTOM-FM - Grupo Siete - Toluca, Estado De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHTOMFMAAC.aac"},
    {name = "Radio Doki", url = "https://kuronegai.radioca.st/stream"},
    {name = "Radio Educación Señal 1060 CDMX - 1060 AM - XECPAE-AM - Secretaria De Cultura - Ciudad De México", url = "https://s2.mexside.net/8172/stream"},
    {name = "Radio Educación SEÑAL 965 FM CDMX - 965 FM - XHEP-FM - Radio Educación - Ciudad De México", url = "https://s2.mexside.net/8174/stream"},
    {name = "Radio Esperanza Monterrey - 1140 AM - XEMR-AM - Grupo Radio Alegría - Apodaca Monterrey, NL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_ESPERANZA_1140AM.mp3"},
    {name = "Radio Felicidad Ciudad De México - 1180 AM - XEFR-AM - Grupo ACIR - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEFRAMAAC_SC.aac"},
    {name = "Radio Felicidad Toluca - 1029 FM - XHTOL-FM - Grupo ACIR - Toluca, EM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHTOLAAC.aac"},
    {name = "Radio Fórmula Campeche - 973 FM - XHRAC-FM - NCS Núcleo Comunicación Del Sureste - Campeche, Campeche", url = "https://sp2.servidorrprivado.com:10886/;"},
    {name = "Radio Guerrero 969 FM Acapulco", url = "https://radiovision.mi-radio.stream:11004/;"},
    {name = "Radio IMER Comitán - 1079 FM 540 AM - XHEMIT-FM XEMIT-AM - IMER - Comitán, CS", url = "https://s2.mexside.net/8050/stream"},
    {name = "Radio Infantil", url = "http://s01.digitalserver.org:9268/stream"},
    {name = "Radio Jerez Jerez - 891 FM - XHXM-FM - Grupo Radiofónico ZER - Jerez, ZA", url = "https://cast.zuperdns.net/8016/stream/"},
    {name = "Radio Lobo MX Hermosillo - Online - Wwwradiolobomx - Hermosillo, Sonora", url = "https://sp2.servidorrprivado.com/9302/stream"},
    {name = "Radio Lobo San José Iturbide - 883 FM - XHSJI-FM - Corporación Bajío Comunicaciones - San José Iturbide, GT", url = "https://radios.radiohd.com.mx/8270/;"},
    {name = "Radio Madera - 961 FM [Cd Madera, Chihuahua]", url = "https://streamingcwsradio30.com:7113/;"},
    {name = "RADIO MARIA MEXICO", url = "http://dreamsiteradiocp.com:8086/stream"},
    {name = "Radio Melchizedek", url = "http://usa19.fastcast4u.com:4840/live"},
    {name = "Radio Moyo Tecomán - Online - Tecomán, CL", url = "http://163.172.198.16:8541/;"},
    {name = "Radio Más", url = "https://streamingcwsradio30.com/8228/stream"},
    {name = "Radio NET Ciudad Juárez - 1490 AM - XECJC-AM - Ciudad Juárez, Chihuahua", url = "https://radioenhd.com:7010/stream"},
    {name = "Radio Ranchito Calvillo - 997 FM - XHPLVI-FM - Grupo ULTRA - Calvillo, AG", url = "https://streamingcwsradio30.com:7006/stream.mp3"},
    {name = "Radio Ranchito Guadalajara - 1370 AM - XEPJ-AM - Radiorama - Guadalajara, JC", url = "http://192.99.16.17:9870/"},
    {name = "Radio Ranchito Morelia - 1025 FM - XHRPA-FM - Grupo ULTRA - Morelia, MI", url = "https://streamingcwsradio30.com:7005/stream.mp3"},
    {name = "Radio REAL - Radio Fuera De La Radio", url = "https://c17.radioboss.fm:18042/stream"},
    {name = "Radio Reyna Tamazunchale - 973 FM - XHGI-FM - Reyna Irazábal Y Hermanos, SA De CV - Tamazunchale, San Luis Potosí", url = "https://stream9.mexiserver.com/8064/;"},
    {name = "Radio San Luis", url = "https://servidor18.brlogic.com:7178/live"},
    {name = "Radio Spider", url = "https://stream.zeno.fm/ullfy4hf9lhtv.m3u"},
    {name = "Radio Teocelo Teocelo - 1490 AM - XEYTM-AM - Teocelo, Veracruz", url = "https://s01.digitalserver.org/8102/stream"},
    {name = "Radio Torreon 963 FM", url = "https://s42.myradiostream.com/34112/;?type=http&nocache=1710339527?0.7279753097997177"},
    {name = "Radio Torreón - 963 FM - XHTOR-FM - Municipio De Torreón - Torreón, Coahuila", url = "https://s42.myradiostream.com/:34112/;?type=http&nocache=1677346569?0.48934032234407643"},
    {name = "Radio Turquesa Cancún - 1051 FM - XHNUC-FM - Grupo Turquesa - Cancún, QR", url = "http://184.154.45.106:8414/live"},
    {name = "Radio Uadeo Los Mochis - 893 FM - XHUDO-FM - Universidad Autónoma De Occidente - Los Mochis, Sinaloa", url = "https://xhudo-megacaster.radioca.st/stream"},
    {name = "Radio UAS 961 Culiacán", url = "https://stream9.mexiserver.com/8410/stream"},
    {name = "Radio UDEM Monterrey - 905 FM - XHUDEM-FM - Universidad De Monterrey - Monterrey, NL", url = "http://c3.radioboss.fm:8161/stream"},
    {name = "Radio UJAT Villahermosa - 961 FM - XHCPEK-FM - UJAT Universidad Juárez Autónoma De Tabasco - Villahermosa, Tabasco", url = "https://streamingcwsradio30.com/8212/stream"},
    {name = "Radio UNAM 961 CDMX - 961 FM - XEUN-FM - UNAM Universidad Autónoma De México - Ciudad De México", url = "https://tv.radiohosting.online:9484/stream"},
    {name = "Radio UNAM AM Ciudad De México - 860 AM - XEUN-AM - UNAM Universidad Autónoma De México - Ciudad De México", url = "https://tv.radiohosting.online:9486/stream"},
    {name = "Radio Universidad Uadec - 895 FM [Torreón, Coahuila]", url = "https://stream11.mexiserver.com:9003/;#.mp3"},
    {name = "Radio UPES 899 Culiacán", url = "https://dj.upes.edu.mx/radio/8000/radio.mp3"},
    {name = "Radio Variedades Los Mochis - 1035 FM - XHPNK-FM - Grupo Radio Centro - Los Mochis, SI", url = "http://c2009.streamguys1.com/Mochis3"},
    {name = "Radio Zacatecas - 979 FM - XHZH-FM - SIZART Sistema Zacatecano De Radio Y Televisión - Zacatecas, ZA", url = "https://streamingcwsradio30.com:7051/;"},
    {name = "Radio Zion Tijuana - 540 AM - XESURF-AM - Zion Multimedia - Tijuana, BC", url = "http://zionmultimedia.live/radio/8010/radio.mp3"},
    {name = "Radioamloorg", url = "http://stream.radioamlo.info:8010/;stream.mp3"},
    {name = "Radiomaya", url = "https://myradio24.org/edwyonz"},
    {name = "Radiomás Orizaba - 1055 FM - XHOBA-FM - RTV Radio Televisión De Veracruz - La Perla Orizaba, VE", url = "https://streamingcwsradio30.com/8228/laperlaorizaba"},
    {name = "Rclasicos 969 FM Santa Ana, México", url = "https://s2.mexside.net/8186/stream"},
    {name = "REACTOR 1057 Ciudad De México - 1057 FM - XHOF-FM - IMER - Ciudad De México", url = "http://s2.mexside.net/8002/stream"},
    {name = "Reactor 1057 FM HD1 XHOF IMER", url = "https://s2.mexside.net/8002/stream"},
    {name = "Región Laguna - 1035 FM [Torreón, Coahuila]", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHLZAAC.aac"},
    {name = "Retro 1075 GDL - 1075 FM - XHVOZ-FM - Grupo Audiorama Comunicaciones - Guadalajara, Jalisco", url = "https://ss1.audiorama.com.mx:6574/vibefm"},
    {name = "Retro FM Ciudad Del Carmen - 939 FM - XHPMEN-FM - Grupo Radio Carmen Radiorama - Ciudad Del Carmen, Campeche", url = "https://ss1.audiorama.com.mx:6572/"},
    {name = "Retro FM Córdoba - 881 FM - XHDZ - Grupo Audiorama Comunicaciones - Córdoba, Veracruz", url = "https://ss1.audiorama.com.mx:6658/;"},
    {name = "Roca Fm Clasicos Mexico", url = "https://xxdelgado.radioca.st/"},
    {name = "Rock 101", url = "https://s3.radio.co/s2c1cebae5/listen"},
    {name = "Romántica 1047 FM Acapulco", url = "https://radiovision.mi-radio.stream:11002/stream"},
    {name = "Romántica Ciudad De México - 1380 AM - XECO-AM - Radiorama - Ciudad De México", url = "https://ss1.audiorama.com.mx:6582/stream"},
    {name = "Romántica Delicias - 1021 FM - XHJK-FM - Sigma Radio - Delicias, CH", url = "http://sigmaradio.stream:9000/index"},
    {name = "RRR Aguascalientes - 895 FM - XHRRR-FM - Grupo Radiofónico ZER - Encarnación De Díaz, Jalisco Cerro De Los Gallos, Aguascalientes", url = "https://live.zuperdns.net/8950/stream"},
    {name = "SABROSITA Ciudad De México - 590 AM - XEPH-AM - NRM Comunicaciones - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEPHAMAAC.aac"},
    {name = "Salsa México - Online - Wwwsalsamexicocom - Independiente", url = "https://radiolatina.info/8064/stream"},
    {name = "Sensitiva Maravatio - 883 FM - XHPVAT-FM - Grupo LCL Comunicaciones - Maravatío, MI", url = "https://server.multimediamb.com/9324/sensitiva"},
    {name = "Señal 90 - 907 FM - XHOY-FM - Grupo Unidifusión - Guadalajara, Jalisco", url = "https://s2.yesstreaming.net:17042/stream"},
    {name = "Siempre 1003 FM HD4 Mazatlán", url = "https://audiostreaming.luz.network/stream/16/;?type=http&nocache=296307"},
    {name = "Simi Radio", url = "http://192.99.4.72:8200/;stream.mp3"},
    {name = "Simja Torah Radio", url = "http://204.12.193.98:8381/stream?type=http&nocache=10525"},
    {name = "SJ Saltillo - 1033 FM 930 AM - XHSJ-FM XESAME-AM - RCG Media - Saltillo, Coahuila", url = "https://radio.rcg.com.mx:7001/"},
    {name = "Sol FM Manzanillo - 897 FM 560 AM - XHMZA-FM XEMZA-AM - Grupo Radiofónico ZER - Cihuatlán, JC Manzanillo, CL", url = "https://live.zuperdns.net/1895/stream/;stream.mp3"},
    {name = "Sol Stereo Chetumal - 977 FM 1020 AM - XHWO-FM XEWO-AM - Chetumal, Quintana Roo", url = "https://securestream.mxradio.xyz/chetumal/"},
    {name = "Solteroshr", url = "http://jpdofunk3.com.br:8060/stream"},
    {name = "Soma:Suburbs Of Goa", url = "https://ice4.somafm.com/suburbsofgoa-128-aac"},
    {name = "Sonido Estrella Zacatecas - 899 FM - XHEPC-FM - Zacatecas, ZA", url = "https://radioforte.com/8010/stream"},
    {name = "Sonora Grupera Navojoa - 897 FM - XHPNAV-FM - Expreso - Navojoa, SO", url = "http://144.217.15.135:8000/stream/2/;"},
    {name = "Sounds Of Yesterday Iheart Radio - Online - ACIR Online Iheart Radio - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ACIR30_s01AAC.aac"},
    {name = "Stereo 1003 Hermosillo - 1003 FM - XHSD-FM - Hermosillo, SO", url = "https://streamingcwsradio30.com:7026/"},
    {name = "Stereo 91 Nuevo Laredo - 913 FM - XHNOE-FM - Nuevo Laredo, Tamaulipas", url = "http://216.251.65.74:8000/;"},
    {name = "Stereo Cien", url = "http://playerservices.streamtheworld.com/m3u/XHMMFMAAC.m3u"},
    {name = "Stereo Cristal Querétaro - 1011 FM - XHJHS-FM - Grupo Radar Corporación Bajío Comunicaciones - Querétaro, Querétaro", url = "https://radios.radiohd.com.mx/8274/stream"},
    {name = "Stereo Fresnillo Fresnillo - 1061 FM - XHRRA-FM - Grupo Radiofónico ZER - Fresnillo, ZA", url = "https://cast.zuperdns.net/8018/stream/"},
    {name = "Stereo Saltillo Saltillo - 935 FM - XHQC-FM - Multimedios Radio - Saltillo, Coahuila", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHQCFMAAC.aac"},
    {name = "Stereo Ticul Yucatán - Online - Ticul, YU", url = "https://stream.rcast.net/67256"},
    {name = "Stereo Uno", url = "https://audiostreaming.luz.network/stream/13/"},
    {name = "Stereo Uno 941 Culiacán", url = "https://audiostreaming.luz.network/stream/7/;"},
    {name = "Stereo Uno Los Mochis", url = "https://audiostreaming.luz.network/;"},
    {name = "Super - 925 FM [Chihuahua, Chihuahua]", url = "http://streamingcwsradio30.com:8126/;"},
    {name = "SUPER Acapulco - 945 FM - XHNU-FM - Grupo Audiorama Comunicaciones - Acapulco, GR", url = "https://ss1.audiorama.com.mx:6608/super"},
    {name = "SUPER Chilpancingo - 1027 FM 680 AM - XHCHG-FM XECHG-AM - Grupo Audiorama Comunicaciones - Chilpancingo, GR", url = "https://ss1.audiorama.com.mx:6616/super"},
    {name = "SUPER Colima - 989 FM - XHERL-FM - Radiorama - Colima, Colima", url = "https://ss1.audiorama.com.mx:6644/stream"},
    {name = "Super Estelar Ciudad Acuña - 929 FM - XHCDU-FM - Grupo Zócalo - Ciudad Acuña, CO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHCDUFMAAC.aac"},
    {name = "SUPER Mexicali - 899 FM - XHSOL-FM - Grupo Audiorama Comunicaciones - Mexicali, BC", url = "https://ss1.audiorama.com.mx:6590/"},
    {name = "SUPER Puerto Peñasco - 935 FM - XHPPO-FM - Grupo Audiorama Comunicaciones - Puerto Peñasco, SO", url = "https://ss1.audiorama.com.mx:6662/"},
    {name = "Super Stereo Miled 951 La Paz", url = "https://miledlapaz-cybertec.radioca.st/;"},
    {name = "Tabasco Hoy Radio Villahermosa - 909 FM - XHJAP-FM - Grupo Cantón - Villahermosa, Tabasco", url = "https://s31.myradiostream.com/:65286/listen.mp3"},
    {name = "Telediario Radio Torreón - 939 FM - XHWN-FM - Multimedios Radio - Torreón, Coahuila", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHWNFMAAC.aac"},
    {name = "The Lounge King Radio", url = "http://198.7.59.28:8423/;"},
    {name = "Titán Villahermosa - 1063 FM - XHRVI-FM - Publilu Medios - Villahermosa, Tabasco", url = "http://master.shoutcast.com:8000/titan-fm-106-3"},
    {name = "Tuba Stereo Tecuala - 925 FM 570 AM - XHETD-FM XETD-AM - Alica Medios - Tecuala, NA", url = "https://www.radiohosting.online/stream/?puerto=9884"},
    {name = "UAM Radio Ciudad De México - 941 FM - XHUAM-FM - UAM Universidad Autónoma Metropolitana - Ciudad De México", url = "https://stream5.mexiserver.com:1124/"},
    {name = "Ultra Gym Fitness Mexicali - Online - El Toque FM - Mexicali, Baja California", url = "http://us10a.serverse.com:8183/"},
    {name = "UNIVERSAL Ciudad De México - 881 FM - XHRED-FM - Grupo Radio Centro - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XERED_AMAAC.aac"},
    {name = "UNIVERSAL Guadalajara - 700 AM - XEDKR-AM - Grupo Radio Centro - Guadalajara, JC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEDKR_AMAAC.aac"},
    {name = "UNIVERSIDAD Tlaxcala - 995 FM - XHUTX-FM - Universidad Autónoma De Tlaxcala - Tlaxcala, TL", url = "http://radio11.mega00.com/8010/strem/1/"},
    {name = "Urbanfm", url = "http://jpdofunk3.com.br:8022/stream"},
    {name = "UVA 905 Aguascalientes - 905 FM - XHUVA-FM - Radiogrupo - Aguascalientes, AG", url = "http://201.159.48.106:1407/"},
    {name = "Vibe FM Guadalajara - 1075 FM - XHVOZ-FM - Grupo Audiorama Comunicaciones - Guadalajara, JC", url = "https://ss1.audiorama.com.mx:6574/"},
    {name = "Vibra FM Culiacán - 969 FM - XHVQ-FM - Grupo Vibra - Culiacán, Sinaloa", url = "https://sp2.servidorrprivado.com:10859/stream"},
    {name = "Vibra FM Guamúchil - 921 FM - XHGML-FM - Grupo Vibra - Guamúchil, Sinaloa", url = "https://sp3.servidorrprivado.com:10829/stream"},
    {name = "Vibra Radio 995 Mazatlán", url = "https://sp3.servidorrprivado.com:10827/stream?type=http&nocache=3"},
    {name = "Vida Acapulco - 897 FM - XHKJ-FM - Grupo Audiorama Comunicaciones - Acapulco, GR", url = "https://ss1.audiorama.com.mx:6610/vida"},
    {name = "Vida Piedras Negras - 999 FM - XHSG-FM - Grupo Audiorama Comunicaciones - Piedras Negras, Coahuila", url = "https://ss1.audiorama.com.mx:6670/stream/"},
    {name = "Vintage 1003 FM HD2 Mazatlán", url = "https://audiostreaming.luz.network/stream/14/;?type=http&nocache=296305"},
    {name = "Vintage 1013 HD2 Los Mochis", url = "https://audiostreaming.luz.network/stream/2/;"},
    {name = "Vintage 941 HD2 Culiacán", url = "https://audiostreaming.luz.network/stream/8/;"},
    {name = "Vive FM Doctor Arroyo - 965 FM - XHARR-FM - Sistema De Radio Y Televisión De Nuevo León - Doctor Arroyo, NL", url = "https://s2.mexside.net/8112/stream"},
    {name = "Vive FM Linares - 1033 FM - XHNAR-FM - Sistema De Radio Y Televisión De Nuevo León - Linares, NL", url = "https://s2.mexside.net/8098/stream"},
    {name = "Vive FM Montemorelos - 977 FM - XHLOS-FM - Sistema De Radio Y Televisión De Nuevo León - Montemorelos, Nuevo León", url = "https://s2.mexside.net/8104/stream"},
    {name = "Voces Acapulco - 921 FM - XHACD-FM - Grupo Audiorama Comunicaciones - Acapulco, Guerrero", url = "https://ss1.audiorama.com.mx:6612/stream"},
    {name = "Vox 973 FM", url = "https://stream.freepi.io/8330/live"},
    {name = "Vox Morelia - 1033 FM - XHMICH-FM - Grupo Vox - Morelia, Michoacán", url = "http://162.240.218.204:2084/stream"},
    {name = "W Deportes Ciudad De México - 730 AM - XEX-AM - Radiópolis - Ciudad De México", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/TDW730AMAAC.aac"},
    {name = "W Radio Ciudad De México XEW-AM 900 Khz, XEW-FM 969 Mhz Televisa Radio", url = "http://provisioning.streamtheworld.com/pls/W_RADIOAAC.pls"},
    {name = "W Radio Guadalajara - 1015 FM - XHWK-FM - Radiópolis - Guadalajara, Jalisco", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WRADIO_GDLAAC.aac"},
    {name = "W Radio Morelos 1001", url = "https://stream9.mexiserver.com:8342/steam"},
    {name = "XEBA Ke Buena 971 FM Guadalajara, JA", url = "http://provisioning.streamtheworld.com/pls/KEBUENA_GDLAAC.pls"},
    {name = "XEEW W1420 1420 AM Matamoros, TAM", url = "http://radio.alphamx.net:8100/stream"},
    {name = "XEH 1420 - Antologia Vallenata", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XEH_AMAAC.aac"},
    {name = "XEH-AM 1420 La H Monterrey, NL", url = "http://provisioning.streamtheworld.com/pls/XEH_AMAAC.pls"},
    {name = "XEHIT-AM 1310 Radio Felicidad Puebla, PU", url = "http://provisioning.streamtheworld.com/pls/XEHITAAC.pls"},
    {name = "XEHK La Voz De Guadalajara", url = "http://192.99.16.17:9890/"},
    {name = "XEJP-FM Joya 937 Mexico City, DF", url = "http://provisioning.streamtheworld.com/pls/XEJP_FMAAC.pls"},
    {name = "XEL-AM 1260 La Comadre Mexico City, DF", url = "http://provisioning.streamtheworld.com/pls/XELAMAAC.pls"},
    {name = "XEMIA-AM 850 San Pedro Tlaquepaque, JA", url = "http://provisioning.streamtheworld.com/pls/XEMIAAAC.pls"},
    {name = "XEQR Radio Centro 1030 AM Mexico City, DF", url = "http://playerservices.streamtheworld.com/pls/XEQR_AMAAC.pls"},
    {name = "XERC-FM 977 Radio Centro Mexico City, DF", url = "http://provisioning.streamtheworld.com/pls/XERC_FMAAC.pls"},
    {name = "XERED Radio RED 1110 AM Mexico City, DF", url = "http://playerservices.streamtheworld.com/pls/XERED_AMAAC.pls"},
    {name = "XEU Veracruz - 981 FM - XHU-FM - Grupo Pazos Radio - Veracruz, VE", url = "http://sgaudio.centrocibernetico.com/xeu"},
    {name = "XEWK W Radio 1190 AM Guadalajara, JA", url = "http://provisioning.streamtheworld.com/pls/WRADIO_GDLAAC.pls"},
    {name = "XEX 730 W Deportes Mexico City, DF", url = "http://provisioning.streamtheworld.com/pls/TDW730AMAAC.pls"},
    {name = "XHBIO - FIESTA MEXICANA - Grupo Promomedios Radio Guadalajara, Jalisco, Mexico", url = "https://strcdn.klm99.com/8130/stream?aw_0_1st.playerid=qZjjnm85&aw_0_1st.skey=1722099001&aw_0_1st.bundleId=tunein.com&listenerid=48213c18339e02bbc93dc6ed298c2192&aw_0_1st.abtest=&partnerId=qZjjnm85&aw_0_1st.stationId=s2996&aw_0_1st.premium=false&source=TuneIn&aw_0_1st.platform=tunein&aw_0_1st.genre_id=g2843&aw_0_1st.class=music&aw_0_1st.ads_partner_alias=emb.Web&aw_0_azn.planguage=%5ben%2c+es%5d"},
    {name = "XHCDU-FM Super Estelar 929 Ciudad Acuna, CO", url = "http://provisioning.streamtheworld.com/pls/XHCDUFMAAC.pls"},
    {name = "XHCLI-FM La Comadre 985 Culiacan, SI", url = "http://provisioning.streamtheworld.com/pls/XHCLIFMAAC.pls"},
    {name = "XHCNA-FM 1001 Radio Disney Culiacan, SI", url = "http://provisioning.streamtheworld.com/pls/XHCNAFMAAC.pls"},
    {name = "XHCP-FM Super Estelar 1079 Piedras Negras, CO", url = "http://provisioning.streamtheworld.com/pls/XHPCFMAAC.pls"},
    {name = "XHENO-FM Mix 901 Toluca, MX", url = "http://provisioning.streamtheworld.com/pls/XHENOFMAAC.pls"},
    {name = "XHFO Radio RED 921 FM Mexico City, DF", url = "http://playerservices.streamtheworld.com/pls/XHFO_FMAAC.pls"},
    {name = "XHGLX Exa FM 917 FM Tijuana, BN", url = "http://playerservices.streamtheworld.com/pls/XHGLX.pls"},
    {name = "XHGTS-FM Studio Feed", url = "http://216.251.87.95:8000/"},
    {name = "XHIDO-FM Super Stereo 1005 Tula, HG", url = "http://provisioning.streamtheworld.com/pls/XHIDOFMGAVCAAC.pls"},
    {name = "XHIK-FM Recuerdo 967 Piedras Negras, CO", url = "http://provisioning.streamtheworld.com/pls/XHIKFMAAC.pls"},
    {name = "XHLY Los 40 Principales 923 FM Morelia, MC", url = "http://s4.mexside.net:7040/stream"},
    {name = "XHME-FM 895 Radio Disney Puerto Vallarta, JA", url = "http://provisioning.streamtheworld.com/pls/XHMEFMAAC.pls"},
    {name = "XHMO-FM 939 Radio Disney Morelia, MC", url = "http://provisioning.streamtheworld.com/pls/XHMOFMAAC.pls"},
    {name = "XHNB-FM Amor 953 San Luis Potosi, SL", url = "http://provisioning.streamtheworld.com/pls/XHNBFMAAC.pls"},
    {name = "XHPI-FM Amor 931 Guadalajara, JA", url = "http://provisioning.streamtheworld.com/pls/XHPIFMAAC.pls"},
    {name = "XHPNS-FM 1071 Amor 107 Piedras Negras, CO", url = "http://provisioning.streamtheworld.com/pls/XHPNSFMAAC.pls"},
    {name = "XHPOP-FM 993 Radio Disney Mexico City, DF", url = "http://provisioning.streamtheworld.com/pls/XHPOPFMAAC.pls"},
    {name = "XHPQ-FM 975 Radio Disney Leon, GJ", url = "http://provisioning.streamtheworld.com/pls/XHPQFMAAC.pls"},
    {name = "XHQK-FM 985 La Comadre San Luis Potosi, SL", url = "http://provisioning.streamtheworld.com/pls/XHQKFMAAC.pls"},
    {name = "XHRC-FM Mix 917 Puebla, PU", url = "http://provisioning.streamtheworld.com/pls/XHRCFMAAC.pls"},
    {name = "XHRH-FM Amor 1033 Puebla, PU", url = "http://provisioning.streamtheworld.com/pls/XHRHFMAAC.pls"},
    {name = "XHRJ-FM Amor 925 Toluca, MX", url = "http://provisioning.streamtheworld.com/pls/XHRJFMAAC.pls"},
    {name = "XHRS-FM 901 Radio Disney Puebla, PU", url = "http://provisioning.streamtheworld.com/pls/XHRSFMAAC.pls"},
    {name = "XHSON Beat 1009 FM Mexico City, DF", url = "http://playerservices.streamtheworld.com/pls/XHSONFM.pls"},
    {name = "XHTA-FM Dinamica 945 Piedras Negras, CO", url = "http://provisioning.streamtheworld.com/pls/XHTAFMAAC.pls"},
    {name = "XHTIM La Mejor 907 FM Tijuana, BN", url = "http://playerservices.streamtheworld.com/pls/XHTIM.pls"},
    {name = "XHUIA-FM Ibero 9091 909 Mhz FM, Ciudad De México Universidad Iberoamericana", url = "http://noasrv.caster.fm:10182/live"},
    {name = "XHUIA-FM-HD2 Ibero 9092, Universidad Iberoamericana, Ciudad De México", url = "http://shaincast.caster.fm:20866/listen.mp3"},
    {name = "XHVAY-FM Amor 927 Puerto Vallarta, JA", url = "http://provisioning.streamtheworld.com/pls/XHVAYFMAAC.pls"},
    {name = "XHVM-FM 1009 Back FM Piedras Negras, CO", url = "http://provisioning.streamtheworld.com/pls/XHVMFMAAC.pls"},
    {name = "XLTN Radio Latina 1045 FM Tijuana, BN", url = "http://playerservices.streamtheworld.com/pls/XLTNFMAAC.pls"},
    {name = "Ya FM Veracruz - 1029 FM - XHTS-FM - Grupo Pazos - Veracruz, VE", url = "https://sgaudio.centrocibernetico.com/yafmveracruz"},
    {name = "YA FM Villahermosa - 957 FM - XHTAB-FM - Grupo Pazos - Villahermosa, Tabasco", url = "https://sg.centrocibernetico.com/yafmvillahermosa"},
    {name = "Yucatan Radio", url = "https://s2.mexside.net/8054/stream"},
    {name = "Yucatán FM Mérida - 929 FM - XHYUC-FM - IMER - Mérida, YU", url = "http://s2.mexside.net/8054/stream"},
    {name = "Zona Tres Guadalajara - 915 FM - XHGEO-FM - Grupo Promomedios - Guadalajara, Jalisco", url = "https://strcdn.klm99.com/8116/stream"},
    {name = "Zoom 95 Hermosillo - 955 FM - XHCD-FM - Hermosillo, Sonora", url = "http://148.251.92.113:8125/stream"},
    {name = "Zoom 955 Mexico", url = "http://148.251.92.113:8125/pls?1654674321025"},
    {name = "Éxitos 989 FM", url = "https://stream9.mexiserver.com/8420/stream"},
    {name = "Éxitos Matamoros - 913 FM - XHMLS-FM - Grupo Radio Avanzado - Matamoros, Tamaulipas", url = "https://ice8.securenetsystems.net/EXITO913"},
    {name = "Éxtasis Digital Guadalajara - 1059 FM - XHQJ-FM - Radiorama - Guadalajara, JC", url = "http://192.99.16.17:3414/;"},
    {name = "Órbita 1067 Ciudad Juárez - 1067 FM - XHUAR-FM - IMER - Ciudad Juárez, CH", url = "https://s2.mexside.net/8044/stream"},
}

return stations
