local stations = {
    {name = "Rcg Yug", url = "https://rtcg.ipradio.rs:9103/;"},
    {name = "Radio Elmag Pop Rock EX YU", url = "https://radio.elmag.me/poprock.mp3"},
    {name = "54HOUSEFM CLUB", url = "https://54house.fm:9013/stream"},
    {name = "Radio Porto Montenegro", url = "https://malta1491.startdedicated.de:8443/main"},
    {name = "Antena M", url = "http://radioservis.me:8010/antenamlive"},
    {name = "Skadar", url = "http://radioservis.me:8050/radioskadar"},
    {name = "Play Radio Montenegro", url = "https://stream.playradio.me:8443/play-me.mp3"},
    {name = "TDI Radio Crna Gora", url = "https://streaming.tdiradio.com/crnagora.mp3"},
    {name = "Reggaeneracija Montenegro", url = "http://5.189.179.77:8000/stream"},
    {name = "Radio Elmag Nostalgija", url = "https://radio.elmag.me/nostalgija.mp3"},
    {name = "Bum Radio", url = "https://r.name.ba:7324/;"},
    {name = "Radio Elmag Evergreen", url = "https://radio.elmag.me/evergreen.mp3"},
    {name = "Radio Danilovgrad", url = "http://sirius.shoutca.st:8604/stream"},
    {name = "Radio Glas Plava", url = "https://glasplava-rowrigos.radioca.st/"},
    {name = "Radio Crne Gore 1", url = "https://rtcg.ipradio.rs:9008/;"},
    {name = "Radio Bar - Crna Gora", url = "http://livestream.barinfo.me:9000/;*.mp3"},
    {name = "Radio Svetigora", url = "http://svetigoralive.com:8879/;"},
    {name = "Mag Radio", url = "http://radio.elmag.me/mag.mp3"},
    {name = "Drugačija Radio Stanica", url = "https://eu2.fastcast4u.com/proxy/mic0?mp=/stream"},
    {name = "Novi Elmag Radio", url = "http://radio.elmag.me/elmag.mp3"},
    {name = "Radio D Podgorica", url = "http://tachyon.shoutca.st:8289/xstream"},
    {name = "Radio Elmag Folk Gold", url = "https://radio.elmag.me/folkgold.mp3"},
    {name = "Radio Renome", url = "https://r.name.ba:7316/"},
    {name = "Radio Elmag Party", url = "https://radio.elmag.me/party.mp3"},
    {name = "Radio Elmag Izvorne I Starogradske", url = "https://radio.elmag.me/izvorne.mp3"},
    {name = "Radio Kotor", url = "https://stream.iradio.pro/proxy/radiokotor?mp=/stream"},
    {name = "РЦГ Classic", url = "https://rtcg1.ipradio.rs:9100/listen.pls"},
    {name = "Jupok Radio", url = "http://176.9.59.144:8062/"},
    {name = "Radio Elmag Love", url = "https://radio.elmag.me/love.mp3"},
    {name = "Radio Boka News", url = "http://bokanews.me:8000/source"},
    {name = "Bruškin", url = "https://player.radiobruskin.me/proxy/radiobruskin/stream"},
    {name = "Radio Elmag Caffe", url = "https://radio.elmag.me/cafe.mp3"},
    {name = "Radio Saraj", url = "https://eu4.fastcast4u.com/proxy/stilradiomk?mp=/s"},
    {name = "Radio Budva", url = "https://c8.radioboss.fm:18199/stream"},
    {name = "Radio Tivat", url = "https://radio.dukahosting.com/8008/stream"},
    {name = "Radio Bar", url = "http://livestream.barinfo.me:9000/;"},
    {name = "Radio Elmag Kids", url = "https://radio.elmag.me/kids.mp3"},
    {name = "City Radio", url = "http://eu7.fastcast4u.com:6166/;"},
    {name = "Aroma Radio", url = "http://5.63.151.52:7025/;"},
    {name = "Radio Berane", url = "https://stream.iradio.pro/proxy/radioberane?mp=/stream;"},
    {name = "Radio Fatih", url = "https://radioservis.me/radio/8070/radiofatih?1702660538716"},
    {name = "TURBO RADIO", url = "https://montestream.xyz/listen/turbo_radio/radio.mp3"},
    {name = "Radio Cetinje", url = "http://78.129.228.187:8007/stream"},
    {name = "Elmag Jazz", url = "http://radio.elmag.me/jazz.mp3"},
    {name = "Радио Жизнь", url = "https://stream.radio-zhizn.ru:8443/life"},
    {name = "Radio Petnjica", url = "https://ubnt.xtraya.com/radiopetnjica,mp3?t=1721723733130"},
    {name = "Radio Bijelo Polje", url = "http://136.243.134.202:8122/stream"},
    {name = "Radio Crne Gore 2 R98", url = "https://r98.ipradio.rs:10100/;"},
}

return stations
