local stations = {
    {name = "Kantipur FM", url = "https://radio-broadcast.ekantipur.com/stream"},
    {name = "Radio Nepal", url = "https://stream1.radionepal.gov.np/live/"},
    {name = "Ujyaalo 90 Network", url = "http://stream.zenolive.com/wtuvp08xq1duv"},
    {name = "Kalika FM 952 FM", url = "http://www.surfmusic.de/m3u/kalika-fm-95-2-fm,16363.m3u"},
    {name = "BBC Nepali", url = "https://stream.live.vc.bbcmedia.co.uk/bbc_nepali_radio"},
    {name = "Hits FM 912", url = "https://usa15.fastcast4u.com/proxy/hitsfm912?mp=/1"},
    {name = "Radio Audio", url = "https://stream.zeno.fm/fvrx47wpg0quv"},
    {name = "Kalika FM", url = "http://kalika-stream.softnep.com:7740/;"},
    {name = "Capital FM 924", url = "http://streaming.softnep.net:8037/;"},
    {name = "Radio Adhyatma Jyoti", url = "https://stream.hamropatro.com/8074"},
    {name = "Butwal FM 944", url = "http://www.surfmusic.de/m3u/butwal-fm-94-4,18031.m3u"},
    {name = "Radio Sathi", url = "http://live.itech.host:7115/live"},
    {name = "Khozee Radio", url = "http://216.55.141.189:8060/stream/1/"},
    {name = "Radio Himalaya", url = "https://live.itech.host/himalayaradio?1588276425741"},
    {name = "CIN Khabar", url = "https://streaming.softnep.net:10996/;stream.nsv&type=mp3&volume=60"},
    {name = "रेडियो हिमालय", url = "https://live.itech.host/himalayaradio"},
    {name = "Vijaya FM 1016", url = "https://live.itech.host:3320/stream"},
    {name = "Swadesh FM", url = "https://radio.garden/api/ara/content/listen/ApPqIXdm/channel.mp3?1700834587158"},
    {name = "Swadesh 932 FM", url = "http://216.55.141.189:8653/stream?type=http&nocache=66846"},
    {name = "Naya Radio", url = "http://live.itech.host:1110/;"},
    {name = "Chitwan Online FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SAM04AAC227_SC"},
    {name = "BFBS Gurkha Radio", url = "https://listen-ssvcbfbs.sharp-stream.com/ssvcbfbs3.aac"},
    {name = "Radiosagar", url = "https://eu1.fastcast4u.com/proxy/radiosag?mp=/stream/1/"},
    {name = "Radio Sahino", url = "http://live.itech.host:7093/live"},
    {name = "Ultimaě Radio", url = "https://ultimae-bofaradio.radioca.st/"},
}

return stations
