local stations = {
    {name = "100,3FM South Canterbury", url = "http://uk4-vn.mixstream.net:8066/stream/1/"},
    {name = "2XS FM Palmerston North", url = "http://125.236.204.178:8001/listen.mp3"},
    {name = "8KNZ", url = "http://radio8k.out.airtime.pro:8000/radio8k_a"},
    {name = "Bay FM 1007", url = "https://s38.myradiostream.com:8876/;;?listening-from-radio-garden=1686796930"},
    {name = "Beachfm 1063", url = "http://s8.myradiostream.com:58408/"},
    {name = "Classic1027", url = "http://edge.iono.fm/xice/49_high.aac"},
    {name = "Drop FM", url = "https://s2.radio.co/s7649837db/listen"},
    {name = "Easy 80S", url = "http://procyon.shoutca.st:8032/;"},
    {name = "Flava", url = "https://ais-nzme.streamguys1.com/nz_010_aac"},
    {name = "Gaia FM New Zealand", url = "http://s2.stationplaylist.com:9000/gaiafm.aac"},
    {name = "Galaxy 107 FM Kawerau", url = "http://s39.myradiostream.com:14858/;listen.mp3"},
    {name = "GOLD 1054 Auckland - New Zealand", url = "http://ais-nzme.streamguys1.com/nz_015_aac"},
    {name = "Gone Country", url = "https://usa10.fastcast4u.com:6010/;?type=http&nocache=1676417570"},
    {name = "Heads FM Mangawhai 1064", url = "https://headsfm.radioca.st/stream"},
    {name = "Hokonui", url = "https://ais-nzme.streamguys1.com/nz_013_aac"},
    {name = "Https:Badradionz - 247 PHONK", url = "https://s2.radio.co/s2b2b68744/listen"},
    {name = "KAOS Blenheim NZ", url = "http://74.91.125.187:8068/stream"},
    {name = "KIX FM", url = "https://stream.kixfm.co.nz:8178/stream"},
    {name = "Libertynz On The Wireless", url = "https://stream.zeno.fm/lamr6x1fxrruv.pls"},
    {name = "MAD FM Auckland 1067", url = "https://madfm-gecko.radioca.st/stream"},
    {name = "Mai FM", url = "https://ais-sa1.streamon.fm/7102_128k.aac"},
    {name = "Mouthfull Radio", url = "https://mouthfull-radio.radiocult.fm/stream"},
    {name = "Mushroom Escape", url = "http://mushroomfm.com/media/escape.pls"},
    {name = "One Christian Radio", url = "https://radio.wanderingsheep.net:33001/onechristianradio"},
    {name = "Positively Morrinsville 877FM", url = "https://c16.radioboss.fm:8262/stream?1652324863134"},
    {name = "Radijohan", url = "http://69.30.214.54:13740/;?type=http&nocache=1708209708?0.5747864581171453"},
    {name = "Radio - X", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SAM02AAC65_SC?dist=onlineradiobox"},
    {name = "Radio Bollybop", url = "https://s3.radio.co/s2f19d44d0/listen"},
    {name = "Radio Hydra", url = "https://streaming.radio.co/sed9109681/listen"},
    {name = "Radio Redwood", url = "http://123.255.61.226:8020/;?type=http&nocache=76646"},
    {name = "Radio Sangeet Masti", url = "https://servidor19-4.brlogic.com:7304/live?source=website"},
    {name = "Radio Te Aroha 88FM", url = "https://c2.radioboss.fm:18440/stream"},
    {name = "Radioactivefm 886", url = "https://radio123-gecko.radioca.st/radioactivefm"},
    {name = "RDU", url = "https://rdu985fm-gecko.radioca.st/stream"},
    {name = "RDU 985FM", url = "https://rdu985fm-gecko.radioca.st/listen.pls?sid=1"},
    {name = "Retro Hit Radio", url = "https://riphel02.radioca.st/;"},
    {name = "RNZ - Radio New Zealand Classic", url = "http://radionz-ice.streamguys.com/concert.mp3"},
    {name = "RNZ National", url = "http://radionz-ice.streamguys.com/national.mp3"},
    {name = "RNZ Parliament", url = "http://radionz-ice.streamguys.com/parliament.mp3"},
    {name = "Sleep Radio", url = "https://cast4.asurahosting.com:2199/tunein/sleeprad.pls"},
    {name = "Smooth 1056FM", url = "https://servidor26.brlogic.com:7110/live"},
    {name = "Switch FM Gisborne", url = "http://s8.myradiostream.com:56886/listen.m4a"},
    {name = "The Crush With DJ09", url = "http://ais-nzme.streamguys1.com/nz_045_aac"},
    {name = "The Generator", url = "https://s1.myradiostream.com/:14268/;?type=http&nocache=1608640718?0.7458407789862892"},
    {name = "The Generator FM", url = "https://s1.myradiostream.com/14268/stream/1/"},
    {name = "The Hits 896 Nelson - New Zealand", url = "http://ais-nzme.streamguys1.com/nz_020_aac"},
    {name = "The Rock - Nz'S #1 Rock Radio Station", url = "https://digitalstreams.mediaworks.nz/rock_net_icy"},
    {name = "The Station 1054FM", url = "https://ais-nzme.streamguys1.com/nz_125_aac"},
    {name = "Tiri 2", url = "https://servidor34-4.brlogic.com:7138/live?source=website"},
    {name = "UP FM 1075", url = "https://stream.upfm.live/radio/8000/radio.mp3"},
    {name = "Wandering Sheep Radio - Christian Smooth Jazz", url = "http://radio.wanderingsheep.tv:8021/christianjazz"},
    {name = "Wandering Sheep Radio - Hope Alive", url = "http://radio.wanderingsheep.tv:8012/hopealive"},
    {name = "Wandering Sheep Radio - Jazz Cafe", url = "http://radio.wanderingsheep.tv:8000/jazzcafe"},
    {name = "World FM Tawa 882", url = "http://www.worldfm.co.nz:8882/worldfm.aac"},
    {name = "Xs80S", url = "http://s1.myradiostream.com:12508/listen.mp3"},
    {name = "ZFM Global", url = "http://nebula.shoutca.st:8545/stream/1/"},
    {name = "ZM", url = "https://ais-nzme.streamguys1.com/nz_008_aac"},
}

return stations
