local stations = {
    {name = "Cawtv", url = "https://stream.zeno.fm/m8aakwyw9u8uv"},
    {name = "Clasica 1019FM", url = "http://streaming.clasicafm.com.ni:8050/clasica.mp3"},
    {name = "Estéreo Romance", url = "https://stereoromance.radioca.st/streams/128kbps.m3u"},
    {name = "Exa FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "Fiesta Latina 891 FM", url = "https://radios.solumedia.com/6596/stream"},
    {name = "La Nueva Radio | Nicaragua", url = "https://stream.zenolive.com/axr92qawesmtv"},
    {name = "La Voz Del Norte", url = "https://stream.zeno.fm/cbd1wweamzzuv"},
    {name = "Masaya Rebelde", url = "https://stream.zeno.fm/bhutktvbfv8uv"},
    {name = "Nicaragua Reggae Radiocom", url = "http://online.radiodifusion.net:8054/stream/1/"},
    {name = "Radio Católica De Nicaragua", url = "http://198.27.68.65:8555/listen.pls?sid=1"},
    {name = "Radio Comunidad", url = "https://stream.zeno.fm/q70e6btc2d0uv"},
    {name = "Radio Estereo Música", url = "http://stream.zenolive.com/8mwf6ssgtceuv.m3u"},
    {name = "Radio Estrella Del Mar", url = "https://streamer.radio.co/sd5242d0b6/listen"},
    {name = "RADIO FABULOSA 993 FM", url = "https://eu1-sonic.serverse.com/8008/stream"},
    {name = "Radio Hermanos", url = "https://stream.zenolive.com/vq7z0a3u7mruv"},
    {name = "Radio Juan Pablo Segundo 977 Fm", url = "https://dc2.serverse.com:8040/stream"},
    {name = "RADIO MARIA NICARAGUA", url = "http://dreamsiteradiocp4.com:8048/stream"},
    {name = "Radio Nicaragua", url = "https://online.radionicaragua.com.ni/stream.mp3"},
    {name = "Radio Oxigeno", url = "https://polaris.hostingnica.net/8060/stream/1/"},
    {name = "Radio República", url = "https://stream.zeno.fm/3kruxu5a9s8uv"},
    {name = "Radio Sendas FM", url = "http://74.91.125.187:8028/listen.pls?sid=1"},
    {name = "Radio Vandalica Nicaragua", url = "https://stream.zeno.fm/caq3fwn1fnruv"},
    {name = "Radio Vos Matagalpa", url = "https://c13.radioboss.fm:18504/radiovosmatagalpa"},
    {name = "Rock FM 1055", url = "https://securestream.us/radio/8050/radio.mp3"},
    {name = "Union Nacional Patriotica", url = "https://stream.zeno.fm/ap6umv11pzzuv"},
}

return stations
