local stations = {
    {name = "Blast Panama", url = "https://stream.mixesurbanospty.com:8020/blasturbana.mp3"},
    {name = "Los 40 Principales Panamá", url = "http://provisioning.streamtheworld.com/pls/LOS40_PAN.pls"},
    {name = "RADIO MARIA PANAMA", url = "http://dreamsiteradiocp.com:8082/stream"},
    {name = "Radio Disney Panamá", url = "http://ic.streann.com:8000/disneypanama"},
    {name = "Exa FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "Cool FM 893 Panama City", url = "http://provisioning.streamtheworld.com/pls/COOLFMAAC.pls"},
    {name = "LIKE 105 FM", url = "https://www.streaming507.net:8020/stream"},
    {name = "Festival 1540 AM", url = "http://streaming507.net:8128/stream"},
    {name = "Estéreo Azul 1009 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ESTEREOAZULAAC.aac"},
    {name = "Antena 8 1001 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/ANT8AAC.aac"},
    {name = "XTREME MUSIC RADIO", url = "https://radios.sonicp.com/8020/stream"},
    {name = "Original Stereo 907 FM", url = "http://rosetta.shoutca.st:8931/;"},
    {name = "AM Original 1180 Veraguas", url = "http://rosetta.shoutca.st:9264/stream"},
    {name = "Bendicion Radio 1380 AM", url = "https://cloudstream2036.conectarhosting.com/8018/stream"},
    {name = "CHT FM 1077", url = "https://radios.host-pa.com:8046/;"},
    {name = "Fabulosa Estéreo 1005 FM", url = "https://www.streaming507.net:8130/stream"},
    {name = "Crisol FM", url = "https://pcbrothers.net/8002/stream"},
    {name = "Flow 927 FM", url = "http://streaming507.net:9980/stream"},
    {name = "Rumba FM", url = "https://laradiossl.online:10355/;stream.nsv"},
    {name = "Toneflame Urban Radio", url = "https://dallas.myautodj.com:2199/proxy/toneflame/stream"},
    {name = "CPR LA PRIMERA 1011 FM", url = "https://sp2.servidorrprivado.com/8094/stream"},
    {name = "Faro De David 1045 FM", url = "https://tv.farodedavid.com:8002/live;"},
}

return stations
