local stations = {
    {name = "Polskie Radio Bialystok", url = "http://stream4.nadaje.com:15476/radiobialystok"},
    {name = "RADIO WIELKOPOLSKA", url = "http://217.182.76.63:8000/webstream"},
    {name = "Radio ZET Chilli", url = "https://ch.cdn.eurozet.pl/chi-net.mp3"},
    {name = "Super Nova Trzebnica", url = "http://ic1.smcdn.pl/1510-1.mp3"},
    {name = "13 ESKA 2", url = "https://radio.stream.smcdn.pl/icradio-p/6230-1.aac/playlist.m3u8"},
    {name = "357", url = "https://n-11-26.dcs.redcdn.pl/sc/o2/radio357/live/radio357_pr.livx?preroll=0"},
    {name = "4 Fun TV", url = "https://stream.4fun.tv:8888/hls/4f_high/index.m3u8"},
    {name = "4Fun Dance TV", url = "http://85.14.116.58:8001/4fundance.m3u"},
    {name = "4Fun Kids", url = "http://85.14.116.58:8001/4funkids"},
    {name = "4Fun Kids TV", url = "http://85.14.116.58:8001/4funkids.m3u"},
    {name = "4Fun Tv", url = "https://stream.4fun.tv:8888/hls/4f.m3u8"},
    {name = "4Funtv", url = "http://85.14.116.58:8001/4fun.m3u"},
    {name = "4Music", url = "https://s1.slotex.pl/shoutcast/7102/stream"},
    {name = "500 Party Hits - Open FM", url = "https://stream.open.fm/81"},
    {name = "80S Hits - Open FM", url = "https://stream.open.fm/3"},
    {name = "Akademickie Radio Centrum UMCS", url = "http://5.201.13.191/live"},
    {name = "Akademickie Radio Kampus", url = "http://193.0.98.66:8005/listen.pls"},
    {name = "Akademickie Radio LUZ", url = "http://stream.radioluz.pl:8000/luz_hifi.mp3"},
    {name = "Aniol Beskidów", url = "http://media.aniolbeskidow.pl:22000/listen.pls?sid=1"},
    {name = "Anty Radio", url = "https://an.cdn.eurozet.pl/ant-web.mp3?t=1713710188361"},
    {name = "Antyradio", url = "https://n-4-2.dcs.redcdn.pl/sc/o2/Eurozet/live/antyradio.livx?audio=5"},
    {name = "Antyradio Classic Rock", url = "https://an01.cdn.eurozet.pl/ANTCLA.mp3?redirected=01"},
    {name = "Antyradio Covers", url = "http://an.cdn.eurozet.pl/ANTCOV.mp3"},
    {name = "Antyradio Hard", url = "https://an05.cdn.eurozet.pl/ANTHAR.mp3"},
    {name = "Antyradio Made In Poland", url = "https://an04.cdn.eurozet.pl/ANTPOL.mp3?t=1668748669557?redirected=04"},
    {name = "Antyradio Makak", url = "http://an.cdn.eurozet.pl/ANTMAK.mp3"},
    {name = "Antyradio Unplugged", url = "https://an05.cdn.eurozet.pl/ANTUNP.mp3"},
    {name = "Antyradio Warszawa", url = "https://an.cdn.eurozet.pl/ant-web.mp3?t=1703697029993"},
    {name = "AWANGARDAFM", url = "https://stream.zeno.fm/mf9ewmbuaq8uv"},
    {name = "Bayerfm", url = "https://streaming.radio5.com.pl:8888/bayerfm"},
    {name = "BEST Radio 128Kbps", url = "http://stream.radiobest.eu:8000/128"},
    {name = "BEST Radio 192Kbps", url = "http://stream.radiobest.eu:8000/192"},
    {name = "BEST Radio 28Kbps", url = "http://stream.radiobest.eu:8000/28"},
    {name = "BEST Radio 64Kbps", url = "http://stream.radiobest.eu:8000/64"},
    {name = "Białoruskie Radio Racja", url = "http://air.racyja.com:8000/racja320"},
    {name = "Biblia - Radio Chrzescijanin", url = "http://radio.chrzescijanin.pl/biblia.m3u"},
    {name = "Blue Fm Poznan", url = "https://pl-play.adtonos.com/8102/radio-pogoda-pozna"},
    {name = "Bonton Chełm", url = "http://streaming.inten.pl:8022/bonton.mp3"},
    {name = "Chilli ZET", url = "https://n-4-1.dcs.redcdn.pl/sc/o2/Eurozet/live/chillizet.livx"},
    {name = "Chilli ZET Deep", url = "http://ch02.cdn.eurozet.pl/CHIDEP.mp3"},
    {name = "Chillizet Covers", url = "https://ch01.cdn.eurozet.pl/CHICOV.mp3"},
    {name = "Chillizet Ladies -Om", url = "https://ch01.cdn.eurozet.pl/CHILAD.mp3?t=1709721264195?redirected=01"},
    {name = "Chillout Radio", url = "http://panel.nadaje.com:9004/"},
    {name = "Chrześcijanin Smooth Jazz", url = "http://51.255.8.139:9760/"},
    {name = "Cmp3", url = "http://cmp3.eu/play.m3u"},
    {name = "Crema Café - Open FM", url = "https://stream.open.fm/76"},
    {name = "Cyberstacja", url = "https://sc.cyberstacja.pl:8000/radio.mp3"},
    {name = "Damismania Dj Radio", url = "http://s1.slotex.pl:7512/"},
    {name = "Dance - Open FM", url = "https://stream.open.fm/31"},
    {name = "Danismania DJ Radio", url = "https://s1.slotex.pl/shoutcast/7512/stream"},
    {name = "Disco Polo - Open FM", url = "https://stream.open.fm/21"},
    {name = "Disco Polo Music Polsat TV", url = "http://85.14.116.58:8001/discopolomusic.m3u"},
    {name = "Disco Radio", url = "http://kiyi.radioca.st:8108/stream"},
    {name = "Discopartypl - Disco Polo", url = "https://s1.slotex.pl/shoutcast/7432/stream?sid=1"},
    {name = "DISCOPARTYPL - Kanał Club", url = "https://s3.slotex.pl/shoutcast/7354/stream"},
    {name = "DISCOPARTYPL - Kanał Disco", url = "https://s1.slotex.pl/shoutcast/7432/stream"},
    {name = "DUBSTEP24H", url = "https://stream.24dubstep.pl/listen/dubstep24h/live"},
    {name = "Dwójka", url = "http://mp3.polskieradio.pl:8902/"},
    {name = "Eden Fm", url = "http://s1.slotex.pl:7402/"},
    {name = "El-Stacja", url = "http://radio.el-stacja.pl:8000/elstacjaap320.ogg"},
    {name = "El-Stacja [MQ]", url = "http://radio.el-stacja.pl:8000/elstacja.ogg"},
    {name = "El-Stacja HQ", url = "http://radio.el-stacja.pl:8000/elstacja320mp3"},
    {name = "Eska - Białystok", url = "https://waw.ic.smcdn.pl/2020-1.mp3"},
    {name = "ESKA - Do Pracy", url = "https://waw.ic.smcdn.pl/6140-1.mp3"},
    {name = "ESKA - Gorąca 20", url = "https://waw.ic.smcdn.pl/6130-1.mp3"},
    {name = "ESKA - Impreska", url = "https://waw.ic.smcdn.pl/6030-1.mp3"},
    {name = "Eska - Rzeszów", url = "http://ic1.smcdn.pl/2240-1.mp3"},
    {name = "ESKA - Summer City", url = "https://waw.ic.smcdn.pl/6120-1.mp3"},
    {name = "Eska -Rzeszów", url = "https://radio.stream.smcdn.pl/timeradio-p/2240-1.aac/playlist.m3u8"},
    {name = "ESKA 2 CLASSIC", url = "https://radio.stream.smcdn.pl/icradio-p/6040-1.aac/playlist.m3u8"},
    {name = "ESKA 2 KONIN", url = "http://ic1.smcdn.pl/1530-1.mp3"},
    {name = "Eska 2 Krakow", url = "https://radio.stream.smcdn.pl/timeradio-p/1070-1.aac/playlist.m3u8"},
    {name = "ESKA 2 PARTY", url = "https://radio.stream.smcdn.pl/icradio-p/6160-1.aac/playlist.m3u8"},
    {name = "ESKA 2 RZESZÓW", url = "http://ic1.smcdn.pl/1240-1.mp3"},
    {name = "Eska 2 Wroclaw", url = "https://radio.stream.smcdn.pl/timeradio-p/1180-1.aac/playlist.m3u8"},
    {name = "ESKA Białystok", url = "https://radio.stream.smcdn.pl/icradio-p/2020-1.aac/playlist.m3u8"},
    {name = "Eska Bydgoszcz", url = "https://radio.stream.smcdn.pl/icradio-p/2030-2.aac/playlist.m3u8"},
    {name = "ESKA DO PRACY", url = "http://ic1.smcdn.pl/6140-1.mp3"},
    {name = "Eska Gdańsk", url = "https://radio.stream.smcdn.pl/icradio-p/2170-1.aac/playlist.m3u8"},
    {name = "ESKA GO", url = "http://ic1.smcdn.pl/6200-1.mp3"},
    {name = "ESKA GORĄCA 100", url = "http://ic1.smcdn.pl/6120-1.mp3"},
    {name = "ESKA GORĄCA 20", url = "http://ic1.smcdn.pl/6130-1.mp3"},
    {name = "Eska Iława", url = "https://radio.stream.smcdn.pl/icradio-p/2440-1.aac/playlist.m3u8"},
    {name = "ESKA IMPRESKA", url = "http://ic1.smcdn.pl/6030-1.mp3"},
    {name = "Eska Koszalin", url = "https://radio.stream.smcdn.pl/icradio-p/2270-1.aac/playlist.m3u8"},
    {name = "Eska Leszno", url = "https://radio.stream.smcdn.pl/icradio-p/2080-1.aac/playlist.m3u8"},
    {name = "Eska Lublin 128", url = "https://ic2.smcdn.pl/2130-1.mp3"},
    {name = "ESKA Łódź", url = "https://radio.stream.smcdn.pl/icradio-p/2100-1.aac/playlist.m3u8"},
    {name = "Eska Płock", url = "http://www.emsoft.ct8.pl/inne/time.m3u?id=2250"},
    {name = "ESKA POZNAŃ", url = "https://ic2.smcdn.pl/2140-1.aac"},
    {name = "ESKA ROCK", url = "https://ic2.smcdn.pl/5380-1.mp3#ESKA_ROCK"},
    {name = "Eska Śląskie", url = "https://radio.stream.smcdn.pl/timeradio-p/2220-1.aac/playlist.m3u8"},
    {name = "Eska Szczecin", url = "http://ic1.smcdn.pl/2260-1.mp3"},
    {name = "Eska TV", url = "http://85.14.116.58:8001/eskatv.m3u"},
    {name = "Eska TV Extra", url = "http://85.14.116.58:8001/eskatvextra.m3u"},
    {name = "Eska Wrocław", url = "https://radio.stream.smcdn.pl/icradio-p/2180-1.aac/playlist.m3u8"},
    {name = "Eska Zamość 128", url = "https://ic2.smcdn.pl/2230-1.mp3"},
    {name = "Eskarock", url = "https://radio.stream.smcdn.pl/icradio-p/5380-1.aac/playlist.m3u8"},
    {name = "Flash Dance FM", url = "http://91.201.235.225:8017/;?icy=https"},
    {name = "Flash FM", url = "http://91.201.235.225:8017/stream/;"},
    {name = "Folk Radio", url = "https://streaming.g-news.pl:8030/fr1"},
    {name = "FSSPX Radio", url = "http://radio.fsspx.pl:8000/radio.mp3"},
    {name = "FTB Flash FM", url = "https://radioftb.net/flashfm.m3u"},
    {name = "Gdynia Radio", url = "http://51.255.8.139:8064/stream"},
    {name = "Głos Nadziei", url = "https://ssl-1.radiohost.pl:9548/index"},
    {name = "Gra Wrocław", url = "http://rmfstream2.interia.pl:8000/radio_gra_wroc"},
    {name = "Haloradio", url = "https://s3.radio.co/s6b9e36d1c/listen"},
    {name = "Hip-Hop PL - Open FM", url = "https://stream.open.fm/24"},
    {name = "Hit Radio", url = "http://51.255.8.139:9090/stream"},
    {name = "Hitradio 1067", url = "http://46.170.199.85:8000/;"},
    {name = "Hitradiopl", url = "http://51.255.8.139:9090/;"},
    {name = "House - Open FM", url = "https://stream.open.fm/5"},
    {name = "House Of Funk", url = "https://houseoffunk.eu:8443/live"},
    {name = "Http:Zt01Cdneurozetplzet-Oldmp3?Redirected=01", url = "http://zt01.cdn.eurozet.pl/zet-old.mp3?redirected=01"},
    {name = "Idź Pod Prąd FM", url = "http://idzpodprad.out.airtime.pro:8000/idzpodprad_a"},
    {name = "Impreza - Open FM", url = "https://stream.open.fm/2"},
    {name = "Internetowe Radio Mittendrin", url = "http://s1.slotex.pl:7592/stream"},
    {name = "Interstacja", url = "http://4stream.pl:18322/;stream.nsv"},
    {name = "Interstacja - Club", url = "http://4stream.pl:18268/;"},
    {name = "Interstacja - Disco Polo", url = "http://4stream.pl:18274/;"},
    {name = "Interstacja - Eurodance", url = "http://4stream.pl:18180/;"},
    {name = "Interstacja - Kanał Główny", url = "http://4stream.pl:18322/;?nocache=1618962538"},
    {name = "Interstacja - Najnowsze Hity", url = "http://4stream.pl:18410/;"},
    {name = "Interstacja - Oldies", url = "http://4stream.pl:18290/;"},
    {name = "Jazzkultura", url = "http://stream.radio.co/s1136b59f3/listen"},
    {name = "JEDYNKA", url = "http://stream3.polskieradio.pl:8900/;"},
    {name = "JEDYNKAPL", url = "https://stream11.polskieradio.pl/pr1/pr1.sdp/playlist.m3u8"},
    {name = "JUMP Radio", url = "http://radioo.eu:9900/"},
    {name = "Kapitał", url = "https://radiokapitalpl.out.airtime.pro/radiokapitalpl_a"},
    {name = "Katolickie Radio Diecezji Plockiej", url = "http://s1.slotex.pl:7760/"},
    {name = "Katolickie Radio Podlasie", url = "http://s1.slotex.pl:7038/"},
    {name = "Katolickie Radio Rzeszow - VIA", url = "http://62.133.128.18:8040/"},
    {name = "Kcht", url = "https://www.radioking.com/play/kcht/320404"},
    {name = "Kino Polska Muzyka", url = "http://85.14.116.58:8001/kinopolskamuzyka.m3u"},
    {name = "Kiss FM Poland", url = "https://streaming.g-news.pl:8090/kissfm"},
    {name = "Konin FM", url = "http://stream2.technologicznie.net/konin.fm"},
    {name = "Kujawy TV", url = "http://stream.kujawy.info:8080/live/broadcast.m3u8"},
    {name = "Lagoon FM", url = "https://s1.slotex.pl/shoutcast/7828/stream"},
    {name = "Leliwa", url = "https://streaming.g-news.pl/radio/8050/leliwa"},
    {name = "Lem FM", url = "http://n08.radiojar.com/2fa0gbhr9bhvv"},
    {name = "Lemfm", url = "https://stream.radiojar.com/2fa0gbhr9bhvv"},
    {name = "Listekfm", url = "http://stream10.hosterion.pl:8004/stream"},
    {name = "Liveatc EPWA Approach, Warszawa", url = "https://www.liveatc.net/play/epwa_app.pls"},
    {name = "Liveatc EPWA Tower, Warszawa", url = "https://www.liveatc.net/play/epwa2.pls"},
    {name = "Maxplay FM", url = "https://s1.slotex.pl/shoutcast/8880/stream"},
    {name = "Mazurske Radijo", url = "https://stream-172.zeno.fm/h6af85mhunhvv"},
    {name = "MC Radio", url = "http://stream4.nadaje.com:8624/mcradio"},
    {name = "Meloradio Acoustic", url = "https://ml.cdn.eurozet.pl/MELACO.mp3"},
    {name = "Meloradio Classics -Om", url = "https://ml01.cdn.eurozet.pl/MELCLA.mp3?t=1709720976687?redirected=01"},
    {name = "Meloradio Delicate", url = "https://ml06.cdn.eurozet.pl/MELDEL.mp3?redirected=06"},
    {name = "Meloradio FM", url = "https://r.dcs.redcdn.pl/sc/o2/Eurozet/live/meloradio.livx?audio=5"},
    {name = "Meloradio Opole", url = "https://ml02.cdn.eurozet.pl/mel-opl.mp3"},
    {name = "MELORADIO POZNAŃ", url = "http://ml03.cdn.eurozet.pl/mel-poz.mp3"},
    {name = "Meloradio Premium -Om", url = "https://ml01.cdn.eurozet.pl/MELPRE.mp3?t=1709720712400?redirected=01"},
    {name = "Meloradio Wrocław", url = "https://ml02.cdn.eurozet.pl/mel-wro.mp3"},
    {name = "Metal Live Radio", url = "https://s7.radiohost.pl:2199/tunein/merz.pls"},
    {name = "Mikrofon W Puszczy Zielonce", url = "https://zte.heterodyne.eu:8443/mic"},
    {name = "Minimal Mix Radio", url = "http://minimalmix.com/minimalmixradio.pls"},
    {name = "Mirage Space", url = "http://s0.radiohost.pl:9563/"},
    {name = "Modfm", url = "http://radio.modules.pl:8500/listen.pls"},
    {name = "Modulespl", url = "http://radio.modules.pl:8500/;stream/1"},
    {name = "Mojepolskieradio - Ballady", url = "http://stream3.polskieradio.pl:8074/"},
    {name = "Mojepolskieradio - Bohaterowie Naszych Lektur", url = "http://stream3.polskieradio.pl:8084/"},
    {name = "Mojepolskieradio - Classic Rock", url = "http://stream3.polskieradio.pl:8060/"},
    {name = "Mojepolskieradio - Czworka", url = "http://stream3.polskieradio.pl:8906/"},
    {name = "Mojepolskieradio - Genesis", url = "http://stream3.polskieradio.pl:8174/"},
    {name = "Mojepolskieradio - Historia Najnowsza - Polska", url = "http://stream3.polskieradio.pl:8082/"},
    {name = "Mojepolskieradio - Historia Zwiazku Radzieckiego", url = "http://stream3.polskieradio.pl:8112/"},
    {name = "Mojepolskieradio - Jedynka", url = "http://stream3.polskieradio.pl:8900/"},
    {name = "Mojepolskieradio - Las", url = "http://stream3.polskieradio.pl:8128/"},
    {name = "Mojepolskieradio - Mijaja Lata Zostaja Piosenki", url = "http://stream3.polskieradio.pl:8168/"},
    {name = "Mojepolskieradio - Nostalgia", url = "http://stream3.polskieradio.pl:8118/"},
    {name = "Mojepolskieradio - Pink Floyd", url = "http://stream3.polskieradio.pl:8070/"},
    {name = "Mojepolskieradio - Piosenki Niezaleznych", url = "http://stream3.polskieradio.pl:8178/"},
    {name = "Mojepolskieradio - Polskieradio24", url = "http://stream3.polskieradio.pl:8080/"},
    {name = "Mojepolskieradio - Potrojne Pasmo Przenoszenia", url = "http://stream3.polskieradio.pl:8138/"},
    {name = "Mojepolskieradio - Prog Rock", url = "http://stream3.polskieradio.pl:8062/"},
    {name = "Mojepolskieradio - Program Alternatywny", url = "http://stream3.polskieradio.pl:8134/"},
    {name = "Mojepolskieradio - Przeboje PRL", url = "http://stream3.polskieradio.pl:8066/"},
    {name = "Mojepolskieradio - Przezyjmy To Jeszcze Raz", url = "http://stream3.polskieradio.pl:8106/"},
    {name = "Mojepolskieradio - Radio Dzieciom", url = "http://stream3.polskieradio.pl:8916/"},
    {name = "Mojepolskieradio - Slynne Glosy I Wielkie Interpretacje", url = "http://stream3.polskieradio.pl:8160/"},
    {name = "Mojepolskieradio - Spotkanie Z Mistrzem", url = "http://stream3.polskieradio.pl:8104/"},
    {name = "Mojepolskieradio - Studio Reportazu", url = "http://stream3.polskieradio.pl:8108/"},
    {name = "Mojepolskieradio - Szanty", url = "http://stream3.polskieradio.pl:8120/"},
    {name = "Mojepolskieradio - Wieczor Odkrywcow", url = "http://stream3.polskieradio.pl:8102/"},
    {name = "Mojepolskieradio - Z Archiwum Radia Wolna Europa", url = "http://stream3.polskieradio.pl:8088/"},
    {name = "Mojepolskieradio - Z Dziejow Armii Krajowej", url = "http://stream3.polskieradio.pl:8054/"},
    {name = "Mojepolskieradio - Za Kulisami Bezpieki I Partii", url = "http://stream3.polskieradio.pl:8092/"},
    {name = "Mojepolskieradio - РАДИО ПОЛЬША", url = "http://stream3.polskieradio.pl:8914/"},
    {name = "MTV 00S TV", url = "http://85.14.116.58:8001/mtv00s.m3u"},
    {name = "Muzyczne Radio Tesia", url = "https://s1.slotex.pl/shoutcast/7514/stream"},
    {name = "Muzyka Do Snu - Open FM", url = "https://stream.open.fm/70"},
    {name = "Muzyka Dwoch Serc", url = "http://s3.slotex.pl:7272/"},
    {name = "Nadziejafm", url = "https://s5.radio.co/s34fca8455/listen"},
    {name = "Nasze Radio 104,7 Fm,Nasze Radio", url = "https://online.nasze.fm:8443/stream"},
    {name = "Nasze Radio 92,1 FM Nostalgicznie", url = "https://online.nasze.fm:9443/stream"},
    {name = "Neural Radio", url = "http://cast.magicstreams.gr:9111/stream"},
    {name = "Nick Music TV", url = "http://85.14.116.58:8001/nickmusic.m3u"},
    {name = "Norda FM", url = "http://ls.tkchopin.pl:1935/norda/nordafm_aac_128/playlist.m3u8"},
    {name = "Nowe Radio", url = "https://stream.profeto.pl/noweradio.mp3"},
    {name = "Off Radio Krakow", url = "http://stream4.nadaje.com:13332/offradiokrakow"},
    {name = "Open FM - Dzień Dobry", url = "http://stream.open.fm/69"},
    {name = "Open FM - Praca", url = "https://stream.open.fm/109?type=.aac"},
    {name = "Open Fm Alt Freszzz", url = "https://stream.open.fm/6?type=.aac"},
    {name = "Open Fm Edm Anthems", url = "https://stream.open.fm/361?type=.aac&user=800002302783&player_group=WWW"},
    {name = "OPEN IMPREZA", url = "http://stream.open.fm/2"},
    {name = "OPENFM - 90S Hits", url = "http://stream.open.fm/14"},
    {name = "OPENFM - Radio Złote Przeboje", url = "http://stream.open.fm/201"},
    {name = "Openfm Hip-Hop USA", url = "https://stream.open.fm/23?type=.aac&user=800037879065&player_group=WWW"},
    {name = "Openfm - 00S Hits", url = "http://stream.open.fm/72"},
    {name = "Openfm - 100% Grabaż", url = "http://stream.open.fm/114"},
    {name = "Openfm - 100% Hits", url = "http://stream.open.fm/64"},
    {name = "Openfm - 1001 Hits", url = "http://stream.open.fm/11"},
    {name = "Openfm - 500 Alternative Hits", url = "http://stream.open.fm/55"},
    {name = "Openfm - 500 Electronic Hits", url = "http://stream.open.fm/94"},
    {name = "Openfm - 500 Heavy Hits", url = "http://stream.open.fm/54"},
    {name = "Openfm - 500 Hip-Hop Hits", url = "http://stream.open.fm/84"},
    {name = "Openfm - 500 Party Hits", url = "http://stream.open.fm/81"},
    {name = "Openfm - 500 R'N'B Hits", url = "http://stream.open.fm/26"},
    {name = "Openfm - 500 Reggae Hits", url = "http://stream.open.fm/30"},
    {name = "Openfm - 500 Rock Hits", url = "http://stream.open.fm/82"},
    {name = "Openfm - 80S Hits", url = "http://stream.open.fm/3"},
    {name = "Openfm - Alt Café", url = "http://stream.open.fm/34"},
    {name = "Openfm - Alt Classic", url = "http://stream.open.fm/43"},
    {name = "Openfm - Alt Club", url = "http://stream.open.fm/9"},
    {name = "Openfm - Alt Freszzz", url = "http://stream.open.fm/6"},
    {name = "Openfm - Alt PL", url = "http://stream.open.fm/36"},
    {name = "Openfm - American Rock", url = "http://stream.open.fm/40"},
    {name = "Openfm - Ballady Wszech Czasow", url = "http://stream.open.fm/20"},
    {name = "Openfm - Bieganie", url = "http://stream.open.fm/116"},
    {name = "Openfm - Biesiada", url = "http://stream.open.fm/59"},
    {name = "Openfm - Biesiada Slaska", url = "http://stream.open.fm/66"},
    {name = "Openfm - Cardio", url = "http://stream.open.fm/141"},
    {name = "Openfm - Chillout", url = "http://stream.open.fm/33"},
    {name = "Openfm - Ciezkie Brzmienia", url = "http://stream.open.fm/13"},
    {name = "Openfm - Classic Hits", url = "http://stream.open.fm/46"},
    {name = "Openfm - Classic Metal", url = "http://stream.open.fm/108"},
    {name = "Openfm - Classic Party", url = "http://stream.open.fm/50"},
    {name = "Openfm - Classic Rock", url = "http://stream.open.fm/32"},
    {name = "Openfm - Crema Café", url = "http://stream.open.fm/76"},
    {name = "Openfm - Dance", url = "http://stream.open.fm/31"},
    {name = "Openfm - Disco Polo", url = "http://stream.open.fm/21"},
    {name = "Openfm - Disco Polo Classic", url = "http://stream.open.fm/49"},
    {name = "Openfm - Disco Polo Freszzz", url = "http://stream.open.fm/57"},
    {name = "Openfm - Do Auta Rock", url = "http://stream.open.fm/113"},
    {name = "Openfm - Dobranoc", url = "http://stream.open.fm/74"},
    {name = "Openfm - Dobry Wieczor", url = "http://stream.open.fm/137"},
    {name = "Openfm - Drum'N'Bass", url = "http://stream.open.fm/41"},
    {name = "Openfm - Dubstep", url = "http://stream.open.fm/68"},
    {name = "Openfm - EDM Anthems", url = "https://stream.open.fm/361?type=.aac&user=800037879065&player_group=WWW"},
    {name = "Openfm - Fitness", url = "http://stream.open.fm/65"},
    {name = "Openfm - Freszzz", url = "http://stream.open.fm/39"},
    {name = "Openfm - Giganci Rocka", url = "http://stream.open.fm/118"},
    {name = "Openfm - Grunge", url = "http://stream.open.fm/157"},
    {name = "Openfm - Gwiazdy", url = "http://stream.open.fm/58"},
    {name = "Openfm - Happy", url = "http://stream.open.fm/120"},
    {name = "Openfm - Hip-Hop Freszzz", url = "http://stream.open.fm/93"},
    {name = "Openfm - Hip-Hop Klasyk", url = "http://stream.open.fm/107"},
    {name = "Openfm - Hip-Hop PL", url = "http://stream.open.fm/24"},
    {name = "Openfm - Hip-Hop Ulica", url = "http://stream.open.fm/92"},
    {name = "Openfm - House", url = "http://stream.open.fm/5"},
    {name = "Openfm - Hygge", url = "http://stream.open.fm/138"},
    {name = "Openfm - Impreza PL", url = "http://stream.open.fm/12"},
    {name = "Openfm - Italo Disco", url = "http://stream.open.fm/27"},
    {name = "Openfm - Jazz", url = "http://stream.open.fm/166"},
    {name = "Openfm - Kids", url = "http://stream.open.fm/16"},
    {name = "Openfm - Klub 90", url = "http://stream.open.fm/8"},
    {name = "Openfm - Kolysanki", url = "http://stream.open.fm/142"},
    {name = "Openfm - Koncentracja", url = "http://stream.open.fm/161"},
    {name = "Openfm - Kraina Lagodnosci", url = "http://stream.open.fm/37"},
    {name = "Openfm - Latino Hits", url = "http://stream.open.fm/19"},
    {name = "Openfm - Lejdis Café", url = "http://stream.open.fm/48"},
    {name = "Openfm - Lejdis Party", url = "http://stream.open.fm/102"},
    {name = "Openfm - Love", url = "http://stream.open.fm/121"},
    {name = "Openfm - Miejska Stacja: Beats Bass", url = "http://stream.open.fm/106"},
    {name = "Openfm - Muzyka Filmowa", url = "http://stream.open.fm/38"},
    {name = "Openfm - Muzyka Klasyczna", url = "http://stream.open.fm/67"},
    {name = "Openfm - Muzyka Motywacyjna", url = "http://stream.open.fm/143"},
    {name = "Openfm - Najwieksze Przeboje XX W", url = "http://stream.open.fm/163"},
    {name = "Openfm - Nauka", url = "http://stream.open.fm/117"},
    {name = "Openfm - Odglosy Natury", url = "http://stream.open.fm/52"},
    {name = "Openfm - Po Polsku", url = "http://stream.open.fm/1"},
    {name = "Openfm - Po Polsku 6070", url = "http://stream.open.fm/17"},
    {name = "Openfm - Po Polsku 8090", url = "http://stream.open.fm/79"},
    {name = "Openfm - Polo Dance", url = "http://stream.open.fm/128"},
    {name = "Openfm - Polski Rock", url = "http://stream.open.fm/29"},
    {name = "Openfm - Polski Rock Classic", url = "http://stream.open.fm/45"},
    {name = "Openfm - Polskie Ballady", url = "http://stream.open.fm/165"},
    {name = "Openfm - Polskie Reggae", url = "http://stream.open.fm/22"},
    {name = "Openfm - Praca", url = "http://stream.open.fm/109"},
    {name = "Openfm - Praca Rock", url = "http://stream.open.fm/104"},
    {name = "Openfm - Punk Rock", url = "http://stream.open.fm/78"},
    {name = "Openfm - Radio Rak'N'Roll", url = "http://stream.open.fm/168"},
    {name = "Openfm - Relaks", url = "http://stream.open.fm/112"},
    {name = "Openfm - Retro Café", url = "http://stream.open.fm/25"},
    {name = "Openfm - Rock Ballady", url = "http://stream.open.fm/61"},
    {name = "Openfm - Rocks", url = "http://stream.open.fm/77"},
    {name = "Openfm - Sad", url = "http://stream.open.fm/103"},
    {name = "Openfm - Sexy: Soul R'N'B", url = "http://stream.open.fm/18"},
    {name = "Openfm - Smooth Jazz", url = "http://stream.open.fm/60"},
    {name = "Openfm - Spacer", url = "http://stream.open.fm/144"},
    {name = "Openfm - Szanty", url = "http://stream.open.fm/28"},
    {name = "Openfm - Top 20 Alt", url = "http://stream.open.fm/83"},
    {name = "Openfm - Top 20 Disco Polo", url = "http://stream.open.fm/53"},
    {name = "Openfm - Top 20 Hip-Hop", url = "http://stream.open.fm/98"},
    {name = "Openfm - Top 20 Impreza", url = "http://stream.open.fm/95"},
    {name = "Openfm - Top 20 PL", url = "http://stream.open.fm/97"},
    {name = "Openfm - Top 20 Pop", url = "http://stream.open.fm/96"},
    {name = "Openfm - Top 20 Rock", url = "http://stream.open.fm/99"},
    {name = "Openfm - Top Wszech Czasow - Polska", url = "http://stream.open.fm/152"},
    {name = "Openfm - Top Wszech Czasow - Rock", url = "http://stream.open.fm/153"},
    {name = "Openfm - Top Wszech Czasow - Swiat", url = "http://stream.open.fm/151"},
    {name = "Openfm - Trance", url = "http://stream.open.fm/7"},
    {name = "Openfm - Trening", url = "http://stream.open.fm/101"},
    {name = "Openfm - Tylko Polskie Przeboje", url = "http://stream.open.fm/111"},
    {name = "Openfm - We Dwoje", url = "http://stream.open.fm/4"},
    {name = "Openfm - Weekend Chill", url = "http://stream.open.fm/126"},
    {name = "Openfm - Weekend Hits", url = "http://stream.open.fm/127"},
    {name = "Openfm - Wesele", url = "http://stream.open.fm/110"},
    {name = "Openfm Trap USA", url = "https://stream.open.fm/354?type=.aac&user=800037879065&player_group=WWW"},
    {name = "Pallottifm", url = "http://s1.slotex.pl:7074/stream"},
    {name = "Pallotyńskie Radio Ewangelizacyjne Pallottifm", url = "http://s1.slotex.pl:7074/stream/"},
    {name = "Paranormalium", url = "http://shoutcast.paranormalium.pl:8000/5"},
    {name = "Park", url = "http://sluchaj1.radiopark.biz.pl:8048/"},
    {name = "Park FM", url = "https://sluchaj2.radiopark.biz.pl:8443/stream"},
    {name = "Paruzja", url = "http://194.59.141.118:8000/"},
    {name = "PLANETA FM", url = "http://pl01.cdn.eurozet.pl/pla-net.mp3"},
    {name = "PLUS", url = "http://plus-gdansk-01.eurozet.pl:8500/"},
    {name = "Plus Radio Legnicafm", url = "https://player.legnica.fm/listen/radio_plus_legnica/radio256.mp3"},
    {name = "Pogoda Wrocław", url = "https://pl-play.adtonos.com/8102/radio-pogoda-wrocaw?cache=1598128880"},
    {name = "Polen - Polskie Radio - Ballady", url = "http://mp3.polskieradio.pl:8074/"},
    {name = "Polka Jammer Station", url = "http://199.58.161.66/"},
    {name = "Polmax 2", url = "http://stream.zeno.fm/szxcunxzbceuv"},
    {name = "Polmax 3", url = "http://stream.zeno.fm/2p4yw9sd8yzuv"},
    {name = "Polmax FM", url = "http://stream.zeno.fm/1gg3kbnzbceuv"},
    {name = "Polmax Kolędy", url = "https://stream.zeno.fm/vorzdeodup8uv"},
    {name = "Polmax5", url = "https://stream.zeno.fm/dx7lqzh8saquv"},
    {name = "Polsat Music TV", url = "http://85.14.116.58:8001/polsatmusic.m3u"},
    {name = "Polskie Radio - Chopin Radio Chopin AAC+", url = "http://stream3.polskieradio.pl:8960/;"},
    {name = "Polskie Radio - Czwórka", url = "http://stream3.polskieradio.pl:8906/;stream"},
    {name = "Polskie Radio - Czwórka Program 4 AAC+", url = "http://stream3.polskieradio.pl:8956/;"},
    {name = "Polskie Radio 24", url = "http://stream3.polskieradio.pl:8080/;.mp3"},
    {name = "Polskie Radio 24 NEW STREAM", url = "https://stream15.polskieradio.pl/pr24/pr24.sdp/playlist.m3u8"},
    {name = "Polskie Radio Bajki Samograjki", url = "http://stream3.polskieradio.pl:8052/;stream"},
    {name = "Polskie Radio Białystok", url = "https://stream4.nadaje.com:15477/radiobialystok"},
    {name = "Polskie Radio Dla Ukrainyпольське Радіо Для України", url = "https://stream85.polskieradio.pl/radio_ukraina/ukraina.stream/playlist.m3u8"},
    {name = "Polskie Radio Dla Zagranicy", url = "http://stream3.polskieradio.pl:8908/"},
    {name = "Polskie Radio Gdańsk", url = "http://stream.task.gda.pl:8000/rg1"},
    {name = "Polskie Radio Jedynka", url = "http://mp3.polskieradio.pl:8900/;.mp3"},
    {name = "Polskie Radio Jedynka AAC", url = "http://stream3.polskieradio.pl:8950/;.mp3"},
    {name = "Polskie Radio Katowice", url = "http://stream4.nadaje.com:9212/radiokatowice"},
    {name = "Polskie Radio Kierowców", url = "http://stream3.polskieradio.pl:8918/"},
    {name = "Polskie Radio Kosmos", url = "http://mp3.polskieradio.pl:8008/"},
    {name = "Polskie Radio LAS", url = "http://mp3.polskieradio.pl:8128/"},
    {name = "Polskie Radio Poznań", url = "http://stream4.nadaje.com:8578/poznan"},
    {name = "Polskie Radio Program 1", url = "http://mp3.polskieradio.pl:8900/"},
    {name = "Polskie Radio Program 2", url = "http://stream3.polskieradio.pl:8952/;.mp3"},
    {name = "Polskie Radio Program 3", url = "http://stream3.polskieradio.pl:8954/;.mp3"},
    {name = "Polskie Radio Program 3 OGG", url = "http://41.dktr.pl:8000/trojka.ogg"},
    {name = "Polskie Radio RDC - Radio Dla Ciebie", url = "http://stream2.nadaje.com:11140/rdc"},
    {name = "Polskie Radio Szczecin 92FM", url = "http://stream4.nadaje.com:11986/prs"},
    {name = "Power TV", url = "http://85.14.116.58:8001/powertv.m3u"},
    {name = "PR - Las", url = "https://stream85.polskieradio.pl/omniaaxe/k75.stream/chunklist_.m3u8"},
    {name = "PR - Nostalgia", url = "https://stream85.polskieradio.pl/omniaaxe/k70.stream/chunklist_.m3u8"},
    {name = "PR - Pink Floyd", url = "http://mp3.polskieradio.pl:8070/"},
    {name = "PR - Szanty", url = "https://stream85.polskieradio.pl/omniaaxe/k71.stream/chunklist_.m3u8"},
    {name = "PR KIEROWCÓW", url = "http://stream3.polskieradio.pl:8918/;"},
    {name = "PR LAS ACC", url = "http://mp3.polskieradio.pl:8528/"},
    {name = "PR TRÓJKA", url = "http://mp3.polskieradio.pl:8904/;.mp3"},
    {name = "Praca Rock - Open FM", url = "https://stream.open.fm/104"},
    {name = "Pro-Radio", url = "http://www.proradio.pl/listen.pls"},
    {name = "Profetopl FM", url = "http://151.80.24.114/stream.mp3"},
    {name = "Program Pierwszy Polskiego Radia", url = "http://mp3.polskieradio.pl:8900/;"},
    {name = "Proradio", url = "http://radiointernetowe.net:7802/"},
    {name = "Przytulne FM", url = "https://s3.slotex.pl/shoutcast/7042/stream"},
    {name = "Punkowe Radio Underground", url = "http://s1.slotex.pl:7604/"},
    {name = "R357", url = "https://radio357.s3.eu-central-1.amazonaws.com/stream/29ce0221-3d37-47d9-97b9-559cfad16ed3.m3u8"},
    {name = "Radia Zet", url = "http://zet-net-01.cdn.eurozet.pl:8400/"},
    {name = "Radio", url = "https://c16.radioboss.fm:18014/stream"},
    {name = "Radio * 100 *", url = "http://stream.zeno.fm/sgzg9sfq1zhvv"},
    {name = "Radio 17", url = "https://emisja.radio17.pl/stream"},
    {name = "Radio 30 Lat RMF FM", url = "https://rs202-krk-cyfronet.rmfstream.pl/20LAT"},
    {name = "Radio 357", url = "http://193.222.135.71/378"},
    {name = "Radio 40Plus Forty Plus", url = "https://s1.slotex.pl/shoutcast/7178/stream"},
    {name = "Radio 5", url = "https://streaming.radio5.com.pl:8888/radio5suwalki"},
    {name = "Radio 7", url = "https://stream.radio7.pl/;"},
    {name = "Radio 7 Mlawa", url = "http://137.74.5.240:443/;"},
    {name = "Radio 90", url = "http://streams.radio90.pl:8000/radio90_128kbps_stereo.mp3"},
    {name = "Radio Afera", url = "http://radio.afera.com.pl/afera128.mp3"},
    {name = "Radio Afera 98,6 Mhz", url = "http://radio.afera.com.pl/afera64.aac"},
    {name = "Radio Ain Karim Skomielna Czarna", url = "https://stream.profeto.pl/radioainkarim.mp3"},
    {name = "Radio AKADERA", url = "http://stream4.nadaje.com:11846/;.m3u"},
    {name = "Radio Akord", url = "http://s1.slotex.pl:7122/"},
    {name = "Radio Aktywne", url = "https://listen.radioaktywne.pl:8443/ramp3"},
    {name = "Radio Alex", url = "https://proxima.shoutca.st/tunein/frradioq.pls"},
    {name = "RADIO ALEXRMF ON", url = "http://195.150.20.7/radio_alex"},
    {name = "Radio Anime24", url = "http://91.232.4.33:7028/;"},
    {name = "Radio Aniołek", url = "http://stream.zeno.fm/nvz73r6m7yzuv"},
    {name = "Radio Arkadia", url = "https://s1.slotex.pl/shoutcast/7238/stream"},
    {name = "Radio Armageddon", url = "https://ssl-1.radiohost.pl:11608/"},
    {name = "Radio Bahary", url = "https://s1.slotex.pl/shoutcast/7838/stream"},
    {name = "Radio Baobab", url = "http://stream.radiobaobab.pl:8000/radiobaobab.mp3"},
    {name = "Radio BEST", url = "https://s3.slotex.pl/shoutcast/7136/stream?sid=1"},
    {name = "RADIO BEZPIECZNA PODRÓŻ", url = "https://ssl-1.radiohost.pl:9344/live"},
    {name = "Radio Bezpieczna Podroz", url = "https://ssl-1.radiohost.pl:9162/stream"},
    {name = "Radio Biedrzychowice", url = "http://195.164.158.230:9070/stream"},
    {name = "Radio BIGBBS", url = "http://91.121.91.156:8000/"},
    {name = "Radio Blisko Tatr", url = "https://s1.slotex.pl/shoutcast/7442/stream"},
    {name = "Radio Bogoria", url = "http://s6.radiohost.pl:8888/;"},
    {name = "Radio Bonton", url = "https://streaming.inten.pl:8020/bonton.mp3"},
    {name = "Radio Centrum", url = "http://shot4.inten.pl:8888/rcfm.mp3.m3u"},
    {name = "Radio Centrum Lublin", url = "https://centrum.fm/wp-content/themes/responsive/images/playlist.m3u"},
    {name = "Radio Centrum Rzeszow", url = "http://62.93.41.27:8000/;stream/1"},
    {name = "Radio Chopin", url = "http://stream3.polskieradio.pl:8910/"},
    {name = "Radio Chrystusa Króla", url = "http://4stream.pl:18044/"},
    {name = "Radio Chrzescijanin - 2", url = "http://s1.slotex.pl:7002/;"},
    {name = "Radio Chrześcijanin Jakość Dźwięku MP3", url = "http://s1.slotex.pl:7002/mountpoint"},
    {name = "Radio Chrzescijanin Biblia", url = "http://s1.slotex.pl:7116/;"},
    {name = "Radio Chrzescijanin Dzieci", url = "http://s1.slotex.pl:7410/;"},
    {name = "Radio Chrzescijanin Muzyka Instrumentalna", url = "http://s1.slotex.pl:7172/"},
    {name = "Radio Cyganeczka", url = "https://s1.slotex.pl/shoutcast/7474/stream"},
    {name = "Radio Danielka", url = "http://s3.slotex.pl:7088/"},
    {name = "Radio Derf Blues Standards", url = "http://178.19.96.111:8011/"},
    {name = "Radio Derf Bluesrock", url = "http://178.19.96.111:8013/listen.pls"},
    {name = "Radio Derf Delta Blues", url = "http://178.19.96.111:8007/listen.pls"},
    {name = "Radio Derf Jazz", url = "http://178.19.96.111:8005/"},
    {name = "Radio Derf Polski Blues", url = "http://178.19.96.111:8026/listen.pls"},
    {name = "Radio Derf Soul", url = "http://178.19.96.111:8018/listen.pls"},
    {name = "Radio DHT Kanał Główny", url = "https://radiodht.com/stream_main/"},
    {name = "Radio Dimash", url = "https://samcloud.spacial.com/API/listen?sid=125052&rid=262397&f=mp3,any%20&br=128000,any&m=m3u"},
    {name = "Radio Disco Party - Disco Impreza", url = "https://s3.slotex.pl/shoutcast/7046/stream"},
    {name = "Radio Disco-Dance", url = "https://radiodd.cloud/radio/8000/radio.mp3"},
    {name = "Radio DJ Patryś", url = "https://radio.pejpal.cloud/stream"},
    {name = "Radio Dla Ciebie", url = "https://stream2.nadaje.com:11141/rdc"},
    {name = "Radio DOXA", url = "http://shot.inten.pl:10000/"},
    {name = "Radio Duch", url = "https://s1.slotex.pl/shoutcast/7174/stream"},
    {name = "Radio Dwójka AAC", url = "http://mp3.polskieradio.pl:8952/"},
    {name = "Radio Dzwiek", url = "http://s3.slotex.pl:7408/;"},
    {name = "Radio Elbląg", url = "http://stream.radiojar.com/q87xmtvrrg8uv.mp3"},
    {name = "Radio Elka Glogow", url = "http://live.elka.pl:8000/miedziowe.m3u"},
    {name = "Radio Elka Leszno", url = "http://live.elka.pl:8000/elka.fm.m3u"},
    {name = "Radio Elka Miedziowe", url = "http://live.elka.pl:8000/miedziowe.pl.m3u"},
    {name = "Radio Em", url = "http://194.181.177.253:8000/"},
    {name = "Radio EM Kielce", url = "http://emkielce.pl:8000/"},
    {name = "Radio Emaus", url = "http://stream.radioemaus.pl:8000/oggstream"},
    {name = "Radio Eska - Warszawa", url = "https://radio.stream.smcdn.pl/icradio-p/2380-1.aac/playlist.m3u8"},
    {name = "Radio Eska - Wrocław", url = "http://ic2.smcdn.pl/2180-1.mp3"},
    {name = "Radio ESKA Braniewo", url = "http://waw.ic.smcdn.pl/2520-2.aac"},
    {name = "Radio Eska Kraków", url = "http://ic1.smcdn.pl/2070-1.mp3"},
    {name = "Radio Eska Opole", url = "https://waw.ic.smcdn.pl/2120-1.mp3"},
    {name = "Radio Eska Warszawa", url = "https://waw.ic.smcdn.pl/2380-1.mp3"},
    {name = "Radio FAMA", url = "http://stream2.nadaje.com:8076/"},
    {name = "Radio Fama Slupsk", url = "http://stream3.nadaje.com:9024/listen.pls?sid=1"},
    {name = "Radio FAMA Tomaszów", url = "http://stream2.nadaje.com:8078/listen.pls"},
    {name = "Radio Famka", url = "http://stream4.nadaje.com:10118/famka.m3u"},
    {name = "Radio Fara", url = "http://62.133.128.22:8000/"},
    {name = "Radio Fest 1002 FM", url = "https://play.radiofest.pl:8443/fest"},
    {name = "Radio FIAT", url = "http://stream2.nadaje.com:8056/"},
    {name = "Radio Forever", url = "http://s1.slotex.pl:7134/"},
    {name = "Radio Forte", url = "http://s1.slotex.pl:7856/"},
    {name = "Radio Freee", url = "http://212.244.54.195:8000/radiofreee"},
    {name = "Radio Freee 899", url = "https://streaming.radio.lublin.pl:8843/radiofreeeacp"},
    {name = "Radio FTB - Club", url = "http://radioftb.net/club.m3u"},
    {name = "Radio FTB - DISCO POLO", url = "https://radioftb.net/disco.m3u"},
    {name = "Radio FTB Retro DJ", url = "http://radioftb.net/retrodj_ftb.m3u"},
    {name = "Radio FTB Trance", url = "https://radioftb.net/trance.m3u"},
    {name = "Radio Gdańsk REGIONY DAB2", url = "https://stream.task.gda.pl:8443/rg4"},
    {name = "Radio Glos", url = "http://87.204.92.180:8000/"},
    {name = "Radio Gniezno", url = "http://stream3.nadaje.com:8012/listen.pls"},
    {name = "Radio Gold Live", url = "http://s1.slotex.pl:7062/;"},
    {name = "Radio Góralskie", url = "https://s3.slotex.pl/shoutcast/7398/stream"},
    {name = "Radio Gorzów", url = "http://stream02.radiogorzow.pl:10115/"},
    {name = "Radio Gra Torun", url = "http://31.192.216.7:8000/radio_gra"},
    {name = "Radio Gra Wroclaw", url = "http://rmfstream2.interia.pl:8000/radio_gra"},
    {name = "Radio Guardian", url = "https://s1.slotex.pl/shoutcast/7508/stream"},
    {name = "Radio Hit", url = "http://46.170.199.85:8000/"},
    {name = "Radio Horyzont", url = "http://s1.slotex.pl:7328/"},
    {name = "Radio I", url = "https://ice2.radioi.pl:8443/stream"},
    {name = "Radio Imperium", url = "https://stream.radioimperium.pl:8443/stream"},
    {name = "Radio Imperium Gliwice", url = "http://91.193.208.8:8000/"},
    {name = "Radio Index", url = "https://www.wzielonej.pl/player/?pl=vlc&c=Index"},
    {name = "Radio Italo4You", url = "http://s6.radiohost.pl:8080/"},
    {name = "Radio Italo4You 256Kbps", url = "https://radioitalo4you.net/listen_url/italo4you_s0_256.pls"},
    {name = "Radio Italo4You 64Kbps", url = "http://s0.radiohost.pl:8018/Italo4you"},
    {name = "Radio Italodance", url = "http://radio.italodance.pl:7694/"},
    {name = "Radio Italodance Neo80S", url = "http://neo80s.italodance.pl:7750/"},
    {name = "Radio Jard", url = "http://online.jard.pl:8744/jard1"},
    {name = "Radio Jasna Gora", url = "http://online.radiojasnagora.pl:8000/rjg"},
    {name = "Radio Jedynka", url = "http://mp3.polskieradio.pl:8950/"},
    {name = "Radio Jura", url = "http://streams.radiojura.com.pl:8000/jura_128kbps_stereo.mp3"},
    {name = "Radio Jutrzenka", url = "http://sluchaj.radiojutrzenka.waw.pl:12854/test"},
    {name = "Radio Kampus", url = "http://193.0.98.66:8005/"},
    {name = "Radio Kampus 97,1 FM", url = "https://stream.radiokampus.fm/kampus"},
    {name = "Radio Karolinka", url = "http://91.232.4.33:8358/stream"},
    {name = "Radio Kaszebe", url = "http://stream3.nadaje.com:8048/"},
    {name = "Radio Kech Nowogard", url = "https://s3.slotex.pl/shoutcast/7016/stream"},
    {name = "Radio Kielce", url = "https://streaming.g-news.pl:8030/rk2"},
    {name = "Radio Kolobrzeg", url = "http://graj.radiokolobrzeg.pl:8000/"},
    {name = "Radio Koszalin", url = "http://91.232.4.33:9680/"},
    {name = "Radio Koszalin SA", url = "http://91.232.4.33:9680/stream"},
    {name = "Radio Koszalin Slupsk", url = "http://91.232.4.33:8240/stream2"},
    {name = "Radio Koszalin Słupsk", url = "https://ssl-1.radiohost.pl:8240/stream?type=https&nocache="},
    {name = "Radio Kraków", url = "https://stream3.nadaje.com:9117/radiokrakow"},
    {name = "Radio Krakow", url = "http://stream3.nadaje.com:9116/radiokrakow"},
    {name = "Radio Kraków - Sport", url = "http://stream3.nadaje.com:9128/radiokrakow"},
    {name = "Radio Kraków Kultura", url = "https://stream4.nadaje.com:9777/RKKultura"},
    {name = "Radio Kujawy", url = "http://radio.kujawy.info:9940/"},
    {name = "Radio Kuropatwa", url = "http://stream.radiojar.com/ypspphhxfm8uv"},
    {name = "Radio Lagoonfm", url = "http://s1.slotex.pl:7828/"},
    {name = "Radio Leliwa", url = "http://streaming.g-news.pl:8050/leliwa.m3u"},
    {name = "Radio Logos", url = "http://panel.nadaje.com:11058/"},
    {name = "Radio Lublin", url = "https://streaming.radio.lublin.pl:8843/128k"},
    {name = "Radio Łódź", url = "http://217.113.224.171/RadioLodz-1.mp3"},
    {name = "Radio Malbork", url = "http://stream3.nadaje.com:9022/"},
    {name = "Radio Manhattan", url = "http://s1.slotex.pl:7780/"},
    {name = "Radio Marconi PL", url = "https://stream12.hosterion.pl/stream/radiomarconi"},
    {name = "Radio Maryja", url = "https://usa12.fastcast4u.com/tunein/isnesllc.pls"},
    {name = "Radio Mbox", url = "https://s1.slotex.pl/shoutcast/7462/stream"},
    {name = "Radio Melody Express", url = "https://s1.slotex.pl/shoutcast/7588/stream"},
    {name = "Radio Miłosierdzie", url = "https://fastcast4u.com/player/milosierdzie/?pl=winamp&c=0"},
    {name = "Radio Mirage - Euro Dance", url = "http://s0.radiohost.pl:9569/;"},
    {name = "Radio Mirage - Italo Dance", url = "https://ssl-1.radiohost.pl:9569/stream"},
    {name = "Radio Mirage - Italodance Channel", url = "http://91.232.4.33:9569/Stream1"},
    {name = "Radio Mirage - Prywatka", url = "https://ssl-1.radiohost.pl:7214/stream?ver=661798"},
    {name = "Radio Mirage - Prywatka Channel", url = "http://91.232.4.33:7214/Stream1"},
    {name = "Radio Mirage - Space", url = "https://ssl-1.radiohost.pl:9563/stream?ver=987766"},
    {name = "Radio Mirage Prywatka", url = "http://91.232.4.33:7214/"},
    {name = "Radio Misiek", url = "http://stream.zeno.fm/5hfdntgf8yzuv"},
    {name = "Radio Moc", url = "https://www.4stream.pl/stream/18312"},
    {name = "Radio Moni Raj", url = "https://s1.slotex.pl/shoutcast/7646/stream"},
    {name = "Radio MORS", url = "https://player.mors.ug.edu.pl/streaming/proxy/"},
    {name = "Radio Na Stoku", url = "https://sluchaj.link:5443/nastoku"},
    {name = "Radio Na Tak", url = "http://c30.radioboss.fm/playlist/615/stream.m3u"},
    {name = "Radio Nakło", url = "http://sluchaj2.107i5.fm:10750/"},
    {name = "Radio Nestolatki", url = "https://s1.slotex.pl/shoutcast/7306/stream"},
    {name = "Radio Niepokalanow", url = "http://88.199.169.10:7600/rn.mp3"},
    {name = "Radio Nowej Generacji", url = "https://s1.slotex.pl/shoutcast/7488/stream"},
    {name = "Radio Nowinki", url = "http://nowinki.pk.edu.pl:8000/nowinki"},
    {name = "Radio Nowy Świat", url = "https://stream.open.fm/368?type=.aac&user=800043471858&player_group=WWW"},
    {name = "Radio Nowy Świat 256K", url = "https://go-audio.toya.net.pl/63214"},
    {name = "Radio Nowy Swiat OF", url = "https://stream.open.fm/368"},
    {name = "Radio Ocean Dusz", url = "http://s1.slotex.pl:7022/"},
    {name = "Radio OKO", url = "http://stream2.nadaje.com:8094/"},
    {name = "Radio Olsztyn", url = "http://213.73.25.178:7066/"},
    {name = "Radio One Planet", url = "https://s1.slotex.pl/shoutcast/7624/stream"},
    {name = "Radio Opatów", url = "http://stream2.nadaje.com:11144/;stream"},
    {name = "Radio Open FM - 00S Hits", url = "https://stream.open.fm/72"},
    {name = "Radio Open FM - American Rock", url = "https://stream.open.fm/40"},
    {name = "Radio Open FM - Disco Polo Classic", url = "https://stream.open.fm/49"},
    {name = "Radio Open FM - Italo Disco", url = "https://stream.open.fm/27"},
    {name = "Radio Open FM - Klub 90", url = "https://stream.open.fm/8"},
    {name = "Radio Open FM - Po Polsku 80", url = "https://stream.open.fm/79"},
    {name = "Radio Open FM - Rocks", url = "https://stream.open.fm/77"},
    {name = "Radio Open FM - Trance", url = "https://stream.open.fm/7"},
    {name = "Radio Opole", url = "http://dab.radio.opole.pl:8070/1"},
    {name = "Radio Opole 1", url = "http://193.47.151.4:9000/ro1mp3.m3u"},
    {name = "Radio Opole 2", url = "http://193.47.151.4:8060/1"},
    {name = "Radio Orbit", url = "https://streams.radio.co/sd1bcd1376/listen#.mp3"},
    {name = "Radio Orthodoxia", url = "https://stream.orthodoxia.pl/stream192.mp3"},
    {name = "Radio Ostrowiec 952 FM", url = "http://s1.slotex.pl:7050/stream/1/;?type=http"},
    {name = "Radio Parada 9600 Fm", url = "http://stream4.nadaje.com:15274/live"},
    {name = "Radio Park FM", url = "http://sluchaj.radiopark.com.pl:8048/"},
    {name = "Radio Party - Kanał Główny", url = "https://s2.radioparty.pl:8015/stream?nocache=4171"},
    {name = "Radio Pasja", url = "http://91.232.4.33:8049/"},
    {name = "Radio Pasja - Chillout", url = "http://91.232.4.33:8108/"},
    {name = "Radio Pasja - Chillout 128Kbs", url = "http://91.232.4.33:8108/stream2"},
    {name = "Radio Pasja - Dance", url = "http://91.232.4.33:9466/"},
    {name = "Radio Pasja - Dance 128Kbs", url = "http://91.232.4.33:9466/stream2"},
    {name = "Radio Pasja - Klubowa", url = "http://91.232.4.33:9460/"},
    {name = "Radio Pasja - Klubowa 128Kbs", url = "http://91.232.4.33:9460/stream2"},
    {name = "Radio Pasja - Pop", url = "http://91.232.4.33:8084/"},
    {name = "Radio Pasja - Pop 128Kbs", url = "http://91.232.4.33:8084/stream2"},
    {name = "Radio Pasja - Relaks", url = "http://91.232.4.33:8102/"},
    {name = "Radio Pasja - Relaks 128Kbs", url = "http://91.232.4.33:8102/stream2"},
    {name = "Radio Pasja 128Kbs", url = "http://91.232.4.33:8049/stream2"},
    {name = "Radio Pasja Warszawa", url = "http://91.232.4.33:8049/listen.pls?sid=2"},
    {name = "Radio Paweł", url = "https://s3.slotex.pl/shoutcast/7024/stream"},
    {name = "Radio Piekary", url = "https://stream.radiopiekary.pl/"},
    {name = "Radio Pielgrzym - Pieśni Po Polsku", url = "http://shoutcast.com.pl:9444/"},
    {name = "Radio Pielgrzym English", url = "http://shoutcast.com.pl:9448/"},
    {name = "Radio Pielgrzym Kazania", url = "http://radiointernetowe.net:9450/"},
    {name = "Radio Pik", url = "http://stream.radiopik.pl:9004/"},
    {name = "Radio Plus", url = "http://waw.ic.smcdn.pl/4990-1.aac"},
    {name = "Radio Plus 1061 Kraków", url = "https://waw.ic.smcdn.pl/4070-1.mp3"},
    {name = "Radio Plus Bydgoszcz", url = "https://pl.cdn.eurozet.pl/plu-bdg.mp3"},
    {name = "Radio Plus Gdansk", url = "https://pl05.cdn.eurozet.pl/plu-gdn.mp3"},
    {name = "Radio Plus Koszalin", url = "http://ic1.smcdn.pl/4270-1.aac"},
    {name = "Radio Plus Krakow", url = "https://ic2.smcdn.pl/4070-1.mp3"},
    {name = "Radio Plus Warszawa", url = "https://pl.cdn.eurozet.pl/plu-waw.mp3"},
    {name = "Radio Płońsk", url = "http://stream.radioplonsk.pl:9360/"},
    {name = "Radio Pogoda Poznań", url = "http://stream10.radioagora.pl/tuba138-1.mp3.m3u"},
    {name = "Radio Poland", url = "https://stream85.polskieradio.pl/pr5/pr5.sdp/playlist.m3u8"},
    {name = "Radio Praga", url = "https://stream12.hosterion.pl/stream/radiopragapl/stream"},
    {name = "Radio Prestige", url = "https://s3.slotex.pl/shoutcast/7076/stream?sid=1"},
    {name = "Radio Profeto", url = "https://stream.profeto.pl/stream.mp3"},
    {name = "Radio Puzzle", url = "http://s1.slotex.pl:7572/"},
    {name = "Radio Racja", url = "http://air.racyja.com:8000/aacp128"},
    {name = "Radio RAM", url = "http://stream4.nadaje.com:9220/ram"},
    {name = "Radio RAM AAC", url = "http://stream2.nadaje.com:9228/ram.aac"},
    {name = "Radio RDN Małopolska", url = "https://stream1.dabcom.pl/rdn_mpl"},
    {name = "Radio Rekord", url = "https://stream3.nadaje.com:8007/radom2"},
    {name = "Radio Rekord 89,6 FM - Ostrowiec", url = "https://stream4.nadaje.com:8309/ostrowiec"},
    {name = "Radio Rekord FM", url = "http://stream2.nadaje.com:8108/"},
    {name = "Radio Rekord Mazowsze", url = "http://stream3.nadaje.com:8086/ciechanow.m3u"},
    {name = "Radio Reset Obywatelski", url = "https://eu4.fastcast4u.com/proxy/radioreset?mp=/1"},
    {name = "Radio RM80", url = "http://91.232.4.33:9011/stream"},
    {name = "Radio RMF", url = "https://rs201-krk-cyfronet.rmfstream.pl/HARDHEAVY?listenerid=22faa5bd029362874d207dd68f5e4954&awparams=companionAds%3Atrue&aw_0_1st.version=1.1.4%3Ahtml5&aw_0_1st.playerid=RMF_Player_JS_P&aw_0_1st.skey=1649088434&aw_0_req.gdpr=false&aw_0_req.userConsentV2=CPW7rKhPW7rKhFKACAPLCHCgAAAAAEPAAB5YAAARTAJMNS8gC7EscGRaNKoUQIwrCQqgUAFFAMLREYAODgp2VgEuoAWACAVARgRAgxBRgwCAAQCAJCIgJACwQCIAiAAAAgARgIQAETAILACwMAgAFANCxACgAECQgyOCo5TAgIkWiglsrEEoK9hTCAMssAKBRGRUACJAgAWBkJCwcxwBICXCyQJMELxACMAA.YAAAD4AAAAAA&aw_0_1st.playerid=RMF_Player_JS_P&aw_0_1st.rmf_disable_preroll=true"},
    {name = "Radio RMF - 2000", url = "http://195.150.20.7/2000"},
    {name = "Radio RMF - 80S Disco", url = "http://31.192.216.10/80SDISCO"},
    {name = "Radio RMF Classic", url = "http://www.rmfon.pl/n/rmfclassic.pls"},
    {name = "Radio RMF FM", url = "http://www.rmfon.pl/n/rmffm.pls"},
    {name = "Radio RMF Hard And Heavy", url = "http://31.192.216.10/HARDHEAVY"},
    {name = "Radio RMF MAXX", url = "http://rs202-krk.rmfstream.pl/RMFMAXXX48"},
    {name = "Radio RMF MAXX Warszawa", url = "http://rs202-krk.rmfstream.pl/MAXXXWAW"},
    {name = "Radio RMF MAXXX", url = "https://rs9-krk2-cyfronet.rmfstream.pl/RMFMAXXX48"},
    {name = "Radio Rmf24Pl", url = "https://rs202-krk-cyfronet.rmfstream.pl/RMF24?aw_0_req.gdpr=false&aw_0_req.userConsentV2=&aw_0_1st.playerid=RMF_Player_JS_P&aw_0_1st.rmf_disable_preroll=true"},
    {name = "Radio Rodzina", url = "http://sluchaj.radiorodzina.pl/RadioRodzinaWroclawLIVE.mp3"},
    {name = "Radio Różaniec", url = "http://radio2.rozaniec.info:5696/listen.pls?sid=1"},
    {name = "RADIO RTO TRANCE", url = "http://s3.slotex.pl:7056/"},
    {name = "Radio Rumcajs", url = "http://sc1.readycast.org:8546/"},
    {name = "Radio Rzeszów", url = "https://streaming.g-news.pl:8040/rzeszow"},
    {name = "Radio Safira", url = "https://stream12.hosterion.pl/stream/safira"},
    {name = "Radio Safira Kanoe", url = "http://stream.zeno.fm/fxvq8uqcvuhvv"},
    {name = "Radio Savana", url = "https://s1.slotex.pl/shoutcast/7434/stream"},
    {name = "Radio Sekret", url = "https://s1.slotex.pl/shoutcast/7556/stream"},
    {name = "Radio Sierpc", url = "https://ssl-1.radiohost.pl:10700/stream"},
    {name = "Radio Silesia", url = "http://s1.slotex.pl:7926/"},
    {name = "Radio Silesia FM", url = "https://s1.slotex.pl/shoutcast/7926/stream?sid=1"},
    {name = "Radio Slask", url = "https://s1.slotex.pl:7022/stream"},
    {name = "Radio Slupsk", url = "http://91.232.4.33:8240/stream"},
    {name = "Radio SOK Sulecin", url = "https://s3.slotex.pl/shoutcast/7230/stream?sid=1"},
    {name = "Radio Spin", url = "http://s01.radiospin.pl:8080/listen.pls"},
    {name = "Radio Śpioch", url = "http://s1.slotex.pl:7138/"},
    {name = "Radio Stargard 90,3 FM - Twoje Pierwsze Radio", url = "http://51.77.59.65:8100/stream.mp3"},
    {name = "Radio Start", url = "https://s1.slotex.pl/shoutcast/7644/stream"},
    {name = "Radio Strefa FM", url = "http://play.strefa.fm:8000/strefa.ogg"},
    {name = "Radio SUD", url = "http://stream2.nadaje.com:8012/"},
    {name = "Radio Świnoujście", url = "http://185.243.52.116:8010/stream"},
    {name = "Radio Szczecin 64K AAC", url = "http://stream4.nadaje.com:11986/prs.aac"},
    {name = "Radio Szczecin Extra", url = "https://stream3.nadaje.com:8201/szczecinfm"},
    {name = "RADIO SZKOCJA", url = "http://s1.slotex.pl:7254/;"},
    {name = "Radio TCZEW", url = "http://195.191.180.5:8000/live"},
    {name = "RADIO TON PL", url = "http://s1.slotex.pl:7310/;"},
    {name = "Radio TOP80", url = "https://top80.pl:8000/listen.mp3"},
    {name = "Radio TPI", url = "https://s1.slotex.pl/shoutcast/7632/stream"},
    {name = "Radio TWR", url = "http://s1.slotex.pl:7504/"},
    {name = "Radio UWM FM", url = "http://213.184.18.156:8000/"},
    {name = "Radio Vanessa", url = "http://s1.slotex.pl:7358/;;"},
    {name = "Radio Victoria", url = "http://stream.v4.radiovictoria.pl:8176/;"},
    {name = "Radio Warmii I Mazur", url = "https://rostr1.radioolsztyn.pl:8843/RWiM"},
    {name = "Radio Warszawa 1062", url = "http://streaming01.technologicznie.net:8765/radio_warszawa.mp3"},
    {name = "RADIO WARTA", url = "http://s1.slotex.pl:7446/;"},
    {name = "Radio Weekend FM", url = "http://stream.weekendfm.pl:8000/weekendfm_najlepsza.aac"},
    {name = "Radio Wesole Slonzoki", url = "http://s1.radiohost.pl:8126/"},
    {name = "Radio Wesołe Slonzoki", url = "http://51.255.8.139:8380/stream"},
    {name = "Radio WNET", url = "https://media.wnet.fm/wnet.fm"},
    {name = "Radio Wroclaw", url = "http://stream4.nadaje.com:9240/prw"},
    {name = "Radio Wroclaw Kultura", url = "http://stream4.nadaje.com:9230/rwkultura"},
    {name = "Radio Zachod", url = "https://stream4.nadaje.com:10122/rz-20kbps.aac"},
    {name = "Radio Zachód AAC", url = "http://stream02.zachod.pl:10113/"},
    {name = "RADIO ZAWIERCIE", url = "https://ssl-1.radiohost.pl:9078/live"},
    {name = "Radio ZET", url = "https://zt01.cdn.eurozet.pl/zet-net.mp3?redirected=01"},
    {name = "Radio ZET - 2000", url = "https://zt04.cdn.eurozet.pl/ZET200.mp3"},
    {name = "Radio ZET 128", url = "https://n-11-21.dcs.redcdn.pl/sc/o2/Eurozet/live/audio.livx?audio=5"},
    {name = "Radio ZET 128 Kbps", url = "https://zt02.cdn.eurozet.pl/zet-old.mp3"},
    {name = "Radio Zet Love -Om", url = "https://zt06.cdn.eurozet.pl/ZETLOV.mp3?t=1709719922445?redirected=06"},
    {name = "Radio Zet Na Rower -Om", url = "https://zt06.cdn.eurozet.pl/ZETNAR.mp3?t=1709720397160?redirected=06"},
    {name = "Radio Zielona Góra RZG", url = "https://stream4.nadaje.com:10122/rzg-20kbps.aac"},
    {name = "Radio Ziemi Wieluńskiej", url = "https://stream2.nadaje.com:8023/;stream"},
    {name = "Radio Zlote Przeboje", url = "https://pl2-play.adtonos.com/zote-przeboje"},
    {name = "Radio Zlote Przeboje Wroclaw", url = "https://radiostream.pl/tuba8940-1.mp3"},
    {name = "Radio Złote Przeboje", url = "https://stream.open.fm/201"},
    {name = "Radio Złote Przeboje Białystok", url = "https://radiostream.pl/tuba8900-1.mp3?cache=1647512038"},
    {name = "Radio Złote Przeboje Wrocław", url = "https://radiostream.pl/tuba9-1.mp3"},
    {name = "Radio Znin FM", url = "http://stream4.nadaje.com:8052/"},
    {name = "Radio40Plus", url = "http://s1.slotex.pl:7178/listen.xtl?sid=1"},
    {name = "Radio7 Mława", url = "https://radio7.pl/listen.m3u"},
    {name = "Radiojazzfm", url = "https://radiojazz.out.airtime.pro/radiojazz_a"},
    {name = "Radiokulturapl", url = "http://51.255.8.139:9772/"},
    {name = "Radiopartypl", url = "http://s7.radioparty.pl:8000/"},
    {name = "Radiopartypl ACC+", url = "http://s2.radioparty.pl:7000/stream64aac"},
    {name = "Radiopartypl Dj Mixes Party", url = "http://djmixes.radioparty.pl:8035/"},
    {name = "Radiopartypl Energy 2000 AAC+", url = "http://s2.radioparty.pl:8040/energy2000"},
    {name = "Radiopartypl Energy2000", url = "http://energy2000.radioparty.pl:8005/"},
    {name = "Radiopartypl House Party", url = "http://house.radioparty.pl:8010/"},
    {name = "Radiopartypl Trance Party", url = "http://trance.radioparty.pl:8015/"},
    {name = "Radiopartypl Vocal Trance", url = "http://s2.radioparty.pl:8025/vocaltrance"},
    {name = "Radiopik", url = "http://stream1.radiopik.pl:9006/;"},
    {name = "Radiopoznanfm", url = "https://stream4.nadaje.com:8579/poznan_aac"},
    {name = "Radioradiofm", url = "https://c16.radioboss.fm/stream/14"},
    {name = "Radiospacja", url = "https://rdsp.out.airtime.pro/rdsp_a"},
    {name = "Radiospacja Openfm", url = "https://stream.open.fm/375"},
    {name = "Radiospin", url = "http://s01.toksyna.fm:8100/"},
    {name = "Ravefm", url = "http://ravefm.org:9850/ravefm"},
    {name = "Rekord Radio Świętokrzyskie", url = "http://stream4.nadaje.com:8308/ostrowiec"},
    {name = "RMC - RADIO MUZYKA CZLOWIEK", url = "http://s1.slotex.pl:7030/stream/"},
    {name = "Rmf", url = "http://195.150.20.242:8000/rmf_fm"},
    {name = "RMF 2 Pop", url = "http://195.150.20.8/RMF2"},
    {name = "RMF 2 Pop + FAKTY", url = "http://195.150.20.8/RMF2F"},
    {name = "RMF 20 Lat", url = "http://31.192.216.7/20LAT"},
    {name = "RMF 20 Lat + FAKTY", url = "http://31.192.216.7/20LATF"},
    {name = "RMF 2000", url = "http://31.192.216.7/2000"},
    {name = "RMF 2000 + FAKTY", url = "http://31.192.216.7/2000F"},
    {name = "RMF 4 DANCE RNB", url = "https://rs6-krk2.rmfstream.pl/rmf_4"},
    {name = "RMF 5 Lagodne Przeboje", url = "http://www.rmfon.pl/n/rmf5.pls"},
    {name = "RMF 5 Lagodne Przeboje + FAKTY", url = "http://31.192.216.8/RMF5F"},
    {name = "RMF 50S", url = "https://rs101-krk.rmfstream.pl/50S"},
    {name = "RMF 60S", url = "http://195.150.20.242:8000/rmf_60s"},
    {name = "RMF 70S", url = "http://31.192.216.7/70S"},
    {name = "RMF 70S Disco", url = "http://www.rmfon.pl/n/70sdisco.pls"},
    {name = "RMF 80S", url = "http://195.150.20.9/80S"},
    {name = "RMF 80S + FAKTY", url = "http://195.150.20.9/80SF"},
    {name = "RMF 80S Disco", url = "http://195.150.20.9/80SDISCO"},
    {name = "RMF 80S Disco + FAKTY", url = "http://195.150.20.9/80SDISCOF"},
    {name = "RMF 90S", url = "http://31.192.216.7/90S"},
    {name = "RMF 90S + FAKTY", url = "http://31.192.216.7/90SF"},
    {name = "RMF 90S Dance", url = "http://195.150.20.7/90SDANCE"},
    {name = "RMF 90S Dance + FAKTY", url = "http://195.150.20.7/90SDANCEF"},
    {name = "RMF Alternatywa", url = "http://195.150.20.7/ALTERNATYWA"},
    {name = "RMF Alternatywa + FAKTY", url = "http://195.150.20.7/ALTERNATYWAF"},
    {name = "RMF Ballady", url = "http://195.150.20.7/NOSTALGIA"},
    {name = "RMF Ballady + FAKTY", url = "http://195.150.20.7/NOSTALGIAF"},
    {name = "RMF Beatlemania", url = "http://195.150.20.8/BEATLEMANIA"},
    {name = "RMF Beatlemania + FAKTY", url = "http://195.150.20.8/BEATLEMANIAF"},
    {name = "RMF Blues", url = "http://31.192.216.10/BLUES"},
    {name = "RMF Blues + FAKTY", url = "http://31.192.216.10/BLUESF"},
    {name = "RMF Bravo", url = "http://31.192.216.8/BRAVO"},
    {name = "RMF Bravo + FAKTY", url = "http://31.192.216.8/BRAVOF"},
    {name = "RMF Celtic", url = "http://31.192.216.7/CELTIC"},
    {name = "RMF Celtic + FAKTY", url = "http://31.192.216.7/CELTICF"},
    {name = "RMF Chillout", url = "http://31.192.216.8/CHILLOUT"},
    {name = "RMF Chillout + FAKTY", url = "http://31.192.216.8/CHILLOUTF"},
    {name = "RMF Chopin + FAKTY", url = "http://31.192.216.8/CHOPINF"},
    {name = "RMF Classic", url = "http://31.192.216.8/RMFCLASSIC48"},
    {name = "RMF Classic Rock", url = "https://rs201-krk.rmfstream.pl/rmf_classic_rock"},
    {name = "RMF Club", url = "http://31.192.216.7/CLUB"},
    {name = "RMF Club + FAKTY", url = "http://31.192.216.7/CLUBF"},
    {name = "RMF Cuba", url = "http://31.192.216.8/CUBA"},
    {name = "RMF Cuba + FAKTY", url = "http://31.192.216.8/CUBAF"},
    {name = "RMF Dance", url = "http://rmfstream1.interia.pl:8000/rmf_dance"},
    {name = "RMF Dance + FAKTY", url = "http://31.192.216.10/DANCEF"},
    {name = "RMF DANCE FAKTY", url = "http://195.150.20.7/rmf_dance_f"},
    {name = "RMF Depeche Mode", url = "http://31.192.216.7/DEPECHEMODE"},
    {name = "RMF Depeche Mode + FAKTY", url = "http://31.192.216.7/DEPECHEMODEF"},
    {name = "RMF Disco Polo", url = "http://www.rmfon.pl/n/discopolo.pls"},
    {name = "RMF Dla Dzieci", url = "http://195.150.20.8/BABY"},
    {name = "RMF Dla Dzieci + FAKTY", url = "http://195.150.20.8/BABYF"},
    {name = "RMF Fitness", url = "http://31.192.216.7/FITNESS"},
    {name = "RMF Fitness + FAKTY", url = "http://31.192.216.7/FITNESSF"},
    {name = "RMF FITNESS FAKTY", url = "http://195.150.20.7/rmf_fitness_f"},
    {name = "RMF FM", url = "http://195.150.20.9/RMFFM48"},
    {name = "RMF FM 128 Kbps", url = "https://rs101-krk.rmfstream.pl/rmf_fm"},
    {name = "RMF FM 48 Kbps", url = "https://rs101-krk.rmfstream.pl/RMFFM48"},
    {name = "Rmf Fm Polska", url = "https://rs101-krk-cyfronet.rmfstream.pl/RMFFM48"},
    {name = "RMF Francais", url = "http://195.150.20.7/FRANCAIS"},
    {name = "RMF Francais + FAKTY", url = "http://195.150.20.7/FRANCAISF"},
    {name = "RMF Funk", url = "https://rs101-krk-cyfronet.rmfstream.pl/rmf_funk"},
    {name = "RMF Game Music", url = "http://195.150.20.243:8000/rmf_gamemusic"},
    {name = "RMF Gold", url = "http://195.150.20.9/GOLD"},
    {name = "RMF Gold + FAKTY", url = "http://195.150.20.9/GOLDF"},
    {name = "RMF Grunge", url = "http://195.150.20.7/GRUNGE"},
    {name = "RMF Grunge + FAKTY", url = "http://195.150.20.7/GRUNGEF"},
    {name = "RMF Hip Hop", url = "http://195.150.20.8/HIPHOP"},
    {name = "RMF Hip Hop + FAKTY", url = "http://195.150.20.8/HIPHOPF"},
    {name = "RMF Hot New", url = "http://195.150.20.9/HOTNEW"},
    {name = "RMF Hot New + FAKTY", url = "http://195.150.20.9/HOTNEWF"},
    {name = "RMF Koledy", url = "http://31.192.216.7/KOLEDY"},
    {name = "RMF Koledy + FAKTY", url = "http://31.192.216.7/KOLEDYF"},
    {name = "RMF LADY PANK", url = "http://195.150.20.9/LADYPANK"},
    {name = "RMF LADY PANK + FAKTY", url = "http://195.150.20.9/LADYPANKF"},
    {name = "RMF Latino", url = "http://www.rmfon.pl/n/latino.pls"},
    {name = "RMF MAXX Hop Bęc", url = "http://195.150.20.244/rmf_hop_bec"},
    {name = "RMF MAXX Podlasie", url = "https://rs101-krk.rmfstream.pl/rmf_maxxx_lom"},
    {name = "RMF MAXX POZNAŃ", url = "https://rs103-krk-cyfronet.rmfstream.pl/MAXXXPOZ"},
    {name = "RMF MAXX ŚLĄSK", url = "https://rs202-krk-cyfronet.rmfstream.pl/MAXXXSLK?aw_0_req.gdpr=true&aw_0_req.userConsentV2=CPwKwZzPwKwZzFKACAPLDNCsAP_AAEPAAB5YJitX_H__bW9r8f7_aft0eY1P9_j77uQxBhfJk-4F3LvW-JwX52E5NF36tqoKmR4Eu3LBIUNlHNHUTVmwaokVryHsak2cpTNKJ6BEkHMRM2dYCF5rmxtjeQKY5_p_d3fx2D-t_dv839z3z81Xn3dZf--0-PCdU5-9Dfn9fRfb-9IP9_78v8v8_9_rk2_eT13_79_7_D9-f_87_WCYoBJhqXEAXYEDITaBhFCiBGFYQEUCgAAAEgaICAFwYFOiMAn1gMgBQigCOCAEMAKMiAQAAAQBIRABIEWCAACAQCAAEACAQCAAgYABQAWAgEAAIDoGKYUACgWECRAREKYEJUCQQEtlQglBdIaYQBVlgBQCI2CgARAACKwABAWLgGCJASoSCBLqDaAAAgAQCiVCsQSemgAUEjZagAAA.YAAAD4AAAAAA&aw_0_1st.playerid=RMF_Player_JS_P&aw_0_1st.rmf_disable_preroll=false"},
    {name = "RMF MAXX SUNRISE", url = "http://195.150.20.7/MAXXSUNF"},
    {name = "RMF Maxx Włocławek", url = "http://www.rmfon.pl/n/rmf_maxxx_wlc.pls"},
    {name = "RMF MAXXX 997 Pomorze", url = "https://rs202-krk-cyfronet.rmfstream.pl/rmf_maxxx?aw_0_1st.playerid=RMF_TuneIn&skey=1616600473"},
    {name = "RMF MAXXX Hop Bec", url = "http://31.192.216.10/HOPBEC"},
    {name = "RMF MAXXX Hop Bec + FAKTY", url = "http://31.192.216.10/HOPBECF"},
    {name = "RMF MAXXX KIELCE", url = "http://rs6-krk2.rmfstream.pl/rmf_maxxx_kie"},
    {name = "RMF MAXXX KRAKÓW", url = "https://rs102-krk.rmfstream.pl/MAXXXKRA"},
    {name = "RMF MAXXX KROSNO", url = "http://rs6-krk2.rmfstream.pl/rmf_maxxx_ksn"},
    {name = "RMF MAXXX Mazowsze", url = "http://www.rmfon.pl/n/rmf_maxxx_cie.pls"},
    {name = "RMF MAXXX Szczecin", url = "http://217.74.72.10/rmf_maxxx_szc"},
    {name = "RMF Michael Jackson", url = "http://195.150.20.9/MICHALEJACKSON"},
    {name = "RMF Michael Jackson + FAKTY", url = "http://195.150.20.9/MICHALEJACKSONF"},
    {name = "RMF Muzyka Klasyczna", url = "http://www.rmfon.pl/n/klasyczna.pls"},
    {name = "RMF Muzykafilmowa", url = "http://www.miastomuzyki.pl/n/rmffilmowa.pls"},
    {name = "RMF Najwieksze Polskie Przeboje", url = "http://www.rmfon.pl/n/npp.pls"},
    {name = "RMF Niezapomniane Melodie", url = "http://31.192.216.10/NIEZAPOMNIANEMELODIE"},
    {name = "RMF Niezapomniane Melodie + FAKTY", url = "http://31.192.216.10/NIEZAPOMNIANEMELODIEF"},
    {name = "RMF Party", url = "http://195.150.20.7/PARTY"},
    {name = "RMF Party + FAKTY", url = "http://195.150.20.7/PARTYF"},
    {name = "RMF PIOSENKA FILMOWA", url = "http://217.74.72.10/rmf_piosenka_filmowa"},
    {name = "RMF Piosenka Literacka", url = "http://31.192.216.7/PIOSENKALITERACKA"},
    {name = "RMF Piosenka Literacka + FAKTY", url = "http://31.192.216.7/PIOSENKALITERACKAF"},
    {name = "RMF Pobudka", url = "http://www.rmfon.pl/n/rmfpobudka.pls"},
    {name = "RMF Polska Prywatka", url = "http://www.rmfon.pl/n/polskaprywatka.pls"},
    {name = "RMF Polski Hip Hop", url = "http://217.74.72.10/rmf_trend_sounds"},
    {name = "RMF Polski Rock", url = "http://195.150.20.9/rmf_polski_rock"},
    {name = "RMF Polskie Przeboje", url = "http://195.150.20.8/PPRZEBOJE"},
    {name = "RMF Polskie Przeboje + FAKTY", url = "http://195.150.20.8/PPRZEBOJEF"},
    {name = "RMF PRL", url = "http://195.150.20.8/PRL"},
    {name = "RMF PRL + FAKTY", url = "http://195.150.20.8/PRLF"},
    {name = "RMF Przeboj Roku", url = "http://31.192.216.10/PRZEBOJROKU"},
    {name = "RMF Przeboj Roku + FAKTY", url = "http://31.192.216.10/PRZEBOJROKUF"},
    {name = "RMF Queen", url = "http://195.150.20.8/QUEEN"},
    {name = "RMF Queen + FAKTY", url = "http://195.150.20.8/QUEENF"},
    {name = "RMF Reggae", url = "http://195.150.20.7/REGGAE"},
    {name = "RMF Reggae + FAKTY", url = "http://195.150.20.7/REGGAEF"},
    {name = "RMF Relaks", url = "http://31.192.216.8/RELAKS"},
    {name = "RMF Relaks + FAKTY", url = "http://31.192.216.8/RELAKSF"},
    {name = "RMF Rock", url = "http://195.150.20.7/ROCK"},
    {name = "RMF Rock + FAKTY", url = "http://195.150.20.7/ROCKF"},
    {name = "RMF Rock Progresywny", url = "http://195.150.20.8/ROCKPROGRESYWNY"},
    {name = "RMF Rock Progresywny + FAKTY", url = "http://195.150.20.8/ROCKPROGRESYWNYF"},
    {name = "RMF Sloneczne Przeboje", url = "http://195.150.20.8/SPRZEBOJE"},
    {name = "RMF Sloneczne Przeboje + FAKTY", url = "http://195.150.20.8/SPRZEBOJEF"},
    {name = "RMF Smooth Jazz", url = "http://31.192.216.8/SJAZZ"},
    {name = "RMF Smooth Jazz + FAKTY", url = "http://31.192.216.8/SJAZZF"},
    {name = "RMF Styl", url = "http://31.192.216.7/STYL"},
    {name = "RMF Styl + FAKTY", url = "http://31.192.216.7/STYLF"},
    {name = "RMF Swieta", url = "http://195.150.20.7/SWIETA"},
    {name = "RMF Swieta + FAKTY", url = "http://195.150.20.7/SWIETAF"},
    {name = "RMF Szanty", url = "http://217.74.72.11/SZANTY"},
    {name = "RMF TOP 30 DANCE", url = "http://195.150.20.244/rmf_top_5_dance"},
    {name = "RMF TOP 30 PL", url = "http://195.150.20.244/rmf_top_5_pl"},
    {name = "RMF TOP 30 POP", url = "http://195.150.20.245/rmf_top_5_pop"},
    {name = "RMF TOP2", url = "https://rs103-krk.rmfstream.pl/TOP2"},
    {name = "RMF TOP3", url = "https://rs103-krk-cyfronet.rmfstream.pl/TOP3"},
    {name = "RMF TOP4", url = "https://rs102-krk-cyfronet.rmfstream.pl/rmf_top4"},
    {name = "RMF TOP5", url = "https://rs202-krk.rmfstream.pl/TOP5"},
    {name = "RMF Trend Sounds", url = "http://195.150.20.7/TRENDSOUNDS"},
    {name = "RMF Trend Sounds + FAKTY", url = "http://195.150.20.7/TRENDSOUNDSF"},
    {name = "RMF W Pracy", url = "http://31.192.216.10/WPRACY"},
    {name = "RMF W Pracy + FAKTY", url = "http://31.192.216.10/WPRACYF"},
    {name = "RMF24", url = "http://rmfstream1.interia.pl/rmf_24"},
    {name = "RMF3 Pop Rock", url = "http://195.150.20.8/RMF3"},
    {name = "Rmfa Classic", url = "http://195.150.20.242:8000/rmf_classic"},
    {name = "Rmfmaxx", url = "http://www.rmfon.pl/n/rmfmaxxx.pls"},
    {name = "RMI - Euro Disco", url = "https://cast1.torontocast.com:1335/stream"},
    {name = "RMI - Italo Disco Classic", url = "https://cast1.torontocast.com:1165/stream"},
    {name = "RMI - Italo Disco New Generation", url = "https://cast1.torontocast.com:1315/stream"},
    {name = "Rock Radio", url = "https://radiostream.pl/tuba8-1.mp3?cache=1650763965"},
    {name = "Rock Radio - Kraków", url = "http://radiostream.pl/tuba9000-1.mp3"},
    {name = "Rock Radio Klasyka Rocka", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_ROCK.mp3"},
    {name = "Rockradio", url = "https://pl-play.adtonos.com/rock-radio"},
    {name = "Rockserwisfm", url = "http://radio.rockserwis.fm/live"},
    {name = "Rockserwisfm ACC+", url = "http://radio.rockserwis.fm/live.aac"},
    {name = "Romantic Music", url = "http://s1.slotex.pl:7392/"},
    {name = "Rozgłośnia Błyskawica", url = "https://s1.slotex.pl/shoutcast/7266/stream"},
    {name = "Rp", url = "http://s1.radioparty.pl:8000/stream"},
    {name = "Sizeer", url = "https://rs103-krk-cyfronet.rmfstream.pl/sizeer_fm"},
    {name = "Śląskie Radio", url = "https://stream10.hosterion.pl:7032/;?v=63125/;type=mp3"},
    {name = "Slonskie Radio Hitmix", url = "http://s1.slotex.pl:7294/"},
    {name = "Smoothjazzcompl", url = "https://bcast.vigormultimedia.com:48888/sjcompl320mp3"},
    {name = "Soundfm", url = "http://s1.slotex.pl:7494/"},
    {name = "Stars TV", url = "http://85.14.116.58:8001/starstv.m3u"},
    {name = "Strefa FM", url = "http://play.strefa.fm:8000/strefa.mp3"},
    {name = "Studenckie Radio ZAK", url = "http://lodz.radio.pionier.net.pl:8000/radiozak.ogg"},
    {name = "Studio Kolobrzeg", url = "https://ssl-1.radiohost.pl:11578/stream?type=https&nocache=1700543980605"},
    {name = "Super FM", url = "http://stream.super.fm:8000/superfm.mp3"},
    {name = "Super FM 975", url = "https://stream.super.fm:8443/superfm.mp3?1697692156303"},
    {name = "Supernova", url = "https://ic1.smcdn.pl/1070-2.aac"},
    {name = "Supernova Gdańsk", url = "http://ic1.smcdn.pl/1170-1.mp3"},
    {name = "Supernova Jelenia Góra", url = "http://ic1.smcdn.pl/1480-1.mp3"},
    {name = "Supernova Kielce", url = "http://ic1.smcdn.pl/1050-1.mp3"},
    {name = "Supernova Party", url = "https://ic2.smcdn.pl/6160-1.mp3#Supernova_Party"},
    {name = "Supernova Rock", url = "https://waw.ic.smcdn.pl/6090-1.mp3"},
    {name = "Supernova Super 13", url = "https://ic2.smcdn.pl/6230-1.mp3#Supernova_Party"},
    {name = "Supernova Szczecin", url = "http://ic1.smcdn.pl/1260-1.mp3"},
    {name = "Supernova Wrocław", url = "http://ic1.smcdn.pl/1180-1.mp3"},
    {name = "Superorbita", url = "https://s1.slotex.pl/shoutcast/7086/stream"},
    {name = "Tobifm", url = "https://s1.slotex.pl/shoutcast/7822/stream"},
    {name = "TOK Muzyka", url = "http://stream10.radioagora.pl/ytBTynyvd3e.mp3"},
    {name = "TOK FM", url = "https://radiostream.pl/tuba10-1.mp3#TOK_FM"},
    {name = "TOK FM 48K", url = "https://stream.open.fm/200"},
    {name = "Tokfm", url = "http://stream10.radioagora.pl/tuba10-1.mp3.m3u"},
    {name = "Toksyna FM", url = "http://s01.toksyna.fm:8000/"},
    {name = "Toksyna FM Chillout More", url = "http://s01.toksyna.fm:8050/"},
    {name = "Toksyna FM DJ Channel", url = "http://s01.toksyna.fm:8040/"},
    {name = "Toksyna FM Elektronica", url = "http://s01.toksyna.fm:8010/"},
    {name = "Toksyna FM New Romantic", url = "http://s01.toksyna.fm:8020/"},
    {name = "Toksyna FM Psytrance", url = "http://www.toksyna.fm/psytrance.pls"},
    {name = "Top 20 Impreza - Open FM", url = "https://stream.open.fm/95"},
    {name = "Top Wszech Czasów - Polska - Open FM", url = "https://stream.open.fm/152"},
    {name = "Trap", url = "https://getradio.reconv.pl/openfm?s=trap-pl"},
    {name = "Trap Pl", url = "https://getradio.reconv.pl/openfm?s=trap"},
    {name = "Trendy Radio", url = "http://stream.trendyradio.pl:8000/h"},
    {name = "Trendy Radio Mobile", url = "https://stream.trendyradio.pl/m"},
    {name = "Trójka", url = "http://mp3.polskieradio.pl:8904/"},
    {name = "Trojka", url = "http://stream3.polskieradio.pl:8904/"},
    {name = "Twoja Polska Stacja", url = "https://twojapolskastacja.pl/sluchaj/tps_winamp.m3u"},
    {name = "Twoje Radio Szczecin", url = "http://51.77.59.65:8000/stream.ogg"},
    {name = "Tyflo Radio", url = "http://radio.tyflopodcast.net:8000/listen.pls"},
    {name = "U-RADIO TRANCE", url = "http://stream.zeno.fm/n8yr1d9g9whvv"},
    {name = "UJOT FM", url = "https://stream.ujot.fm/"},
    {name = "Ultra-Max", url = "https://ssl-1.radiohost.pl:9111/stream"},
    {name = "Vibefm", url = "https://ic2.smcdn.pl/6490-1.aac"},
    {name = "Vox Fm", url = "https://radio.stream.smcdn.pl/timeradio-p/3990-1.aac/playlist.m3u8"},
    {name = "VOX FM 128", url = "https://ic2.smcdn.pl/3990-1.mp3"},
    {name = "VOX FM 128Kbps", url = "https://pldm.one.pl/radio?url=https://www.eskago.pl/radio/vox-fm"},
    {name = "VOX FM BEST LISTA", url = "http://ic1.smcdn.pl/6100-1.mp3"},
    {name = "VOX FM DISCO 90", url = "http://ic1.smcdn.pl/6170-1.mp3"},
    {name = "VOX FM DISCO PARTY", url = "http://ic1.smcdn.pl/6180-1.mp3"},
    {name = "VOX FM HIT 22", url = "http://ic1.smcdn.pl/6020-1.mp3"},
    {name = "VOX POZNAŃ", url = "https://radio.stream.smcdn.pl/icradio-p/3140-1.aac/playlist.m3u8"},
    {name = "W Podróży", url = "https://stream.open.fm/381"},
    {name = "Wasze Radio FM", url = "https://sluchaj.link:5443/wasze"},
    {name = "Wieczor-Odkrywcow", url = "http://mp3.polskieradio.pl:8102/"},
    {name = "WP Radio", url = "https://stream.open.fm/367?type=.aac&user=800035396554&player_group=WWWf"},
    {name = "Zamek Nadaje", url = "http://uksoutha.streaming.broadcast.radio:15190/zameknadaje"},
    {name = "Zet 90S", url = "https://zt02.cdn.eurozet.pl/ZET090.mp3"},
    {name = "ZET DANCE", url = "http://pl01.cdn.eurozet.pl/ZETDAN.mp3"},
    {name = "ZET Impreza", url = "https://zt.cdn.eurozet.pl/ZETPAR.mp3"},
    {name = "ZET Latino", url = "https://ch.cdn.eurozet.pl/ZETLTN.mp3"},
    {name = "ZET Na Swieta", url = "https://zt.cdn.eurozet.pl/ZETSWI.mp3"},
    {name = "ZET Po Polsku", url = "https://zt.cdn.eurozet.pl/ZETPL1.mp3"},
    {name = "ZET Pop Rock", url = "https://zt.cdn.eurozet.pl/ZETPRK.mp3"},
    {name = "Zet Radio", url = "http://www.emsoft.ct8.pl/inne/zet.m3u"},
    {name = "ZET Same Hity", url = "https://zt.cdn.eurozet.pl/ZETHIT.mp3"},
    {name = "Zloteprzeboje", url = "https://radiostream.pl/tuba8904-1.mp3"},
    {name = "Złote Przeboje Poznań", url = "http://radiostream.pl/tuba8926-1.mp3"},
}

return stations
