local stations = {
    {name = "5Fm", url = "https://5fm.mk:8000/"},
    {name = "5FM Veles", url = "http://5fm.mk:8000/;"},
    {name = "=Keco=70S ROCK", url = "http://jfm1.hostingradio.ru:14536/rock70.mp3"},
    {name = "Antenna 5 Macedonia", url = "http://antenna5stream.neotel.mk:8000/live128"},
    {name = "Bum Kumanovo", url = "http://iandonov.radioca.st/;stream/1"},
    {name = "Jazz FM", url = "https://radio.jazzfm.mk/listen/jazzfm/live"},
    {name = "Just Music Radio", url = "https://radiostream.neotel.mk/justmusicradio"},
    {name = "Kanal 103", url = "http://radiostream.neotel.mk/kanal103"},
    {name = "Lider FM 107,4", url = "https://liderfm.ipradio.mk/"},
    {name = "Life Radio", url = "http://liferadio.ddns.net:8000/"},
    {name = "Life Radio 891 Macedonia", url = "http://liferadio.ddns.net:8000/;"},
    {name = "Radio 22", url = "https://radio.server14.kariha.net:8008/"},
    {name = "Radio Bravo 1", url = "http://80.77.157.10:8000/stream/2;live.mp3"},
    {name = "Radio Bravo Smooth Jazz Mix Radio", url = "http://server.webnetradio.net:5490/stream?"},
    {name = "Radio G - Gostivar", url = "https://live.mkdstream.com/listen/ragostivar/radiog"},
    {name = "Radio Maria Macedonia", url = "http://dreamsiteradiocp.com:8118/stream"},
    {name = "Radio Meff", url = "https://s32.myradiostream.com:16040/;?type=http&nocache=1688299470?0.591044522318551"},
    {name = "Radio Valandovo", url = "https://live.mkdstream.com/listen/valan/valand"},
    {name = "Radiobar", url = "https://visual.shoutca.st:8122/stream"},
    {name = "Sky Radio 1025 Skopje, Macedonia", url = "https://s1.skyradio.com.mk/;*.mp3"},
    {name = "Star Radio Ex-Yu Retro Skopje, Macedonia", url = "https://radiostar.pro/stream/exyuretro.php"},
    {name = "Star Radio Plus Skopje, Macedonia", url = "https://radiostar.pro/stream/starplus.php"},
    {name = "Star Radio Urban Folk Skopje, Macedonia", url = "https://radiostar.pro/stream/narodna.php"},
    {name = "Urban FM 908 Skopje", url = "https://securestreams4.autopo.st:1668/stream"},
}

return stations
