local stations = {
    {name = "Deep House Radio - Bucharest Romania", url = "http://live.dancemusic.ro:7000/listen.pls?sid=1"},
    {name = "Radio Romania Actualități", url = "http://89.238.227.6:8006/;"},
    {name = "Radio Zu", url = "http://zuicast.digitalag.ro:9420/zu"},
    {name = "Kiss Fm Ro", url = "https://www.kissfm.ro/listen.pls"},
    {name = "Magic FM", url = "http://live.magicfm.ro:9128/magicfm.aacp"},
    {name = "Play 90'S", url = "http://live.playradio.org:9090/90HD"},
    {name = "DIGI FM", url = "http://edge76.rdsnet.ro:84/digifm/digifm.mp3"},
    {name = "Pro FM", url = "http://edge126.rdsnet.ro:84/profm/profm.mp3"},
    {name = "Magic Party Mix", url = "https://live.magicfm.ro/magic.party.mix"},
    {name = "Dance FM 895 Bucharest", url = "http://edge126.rdsnet.ro:84/profm/dancefm.mp3"},
    {name = "Digi24Fm", url = "https://edge76.rcs-rds.ro/digifm/digi24fm.mp3"},
    {name = "Radio Cafe Romania", url = "http://live.radiocafe.ro:8048/live.aac"},
    {name = "Europafm", url = "http://astreaming.edi.ro:8000/EuropaFM_aac"},
    {name = "Gherla FM", url = "http://89.39.189.52:8000/;"},
    {name = "Radio Manele FM", url = "http://a.fmradiomanele.ro:8054/;"},
    {name = "Europa FM Romania", url = "https://astreaming.edi.ro:8443/EuropaFM_aac"},
    {name = "Radio România Cultural", url = "http://stream2.srr.ro:8012/"},
    {name = "Europa FM", url = "http://astreaming.europafm.ro:8000/europafm_aacp48k"},
    {name = "Virgin Radio Romania", url = "https://astreaming.edi.ro:8443/VirginRadio_aac"},
    {name = "Goldfm", url = "http://80.86.106.110:8002/"},
    {name = "Rockfm", url = "https://live.rockfm.ro/rockfm.aacp"},
    {name = "Radio Impuls Romania", url = "http://live2.radio-impuls.ro/"},
    {name = "Realitatea FM", url = "https://shout.realitatea.net:8001/rfmweb"},
    {name = "Radio 1 Manele", url = "http://radio1manele.no-ip.org:8000/;"},
    {name = "Rock FM Romania", url = "http://live.rockfm.ro:9128/rockfm.aacp"},
    {name = "Lautaru Populara", url = "http://live.radiolautaru.ro:9000/;stream.nsv"},
    {name = "DJ Radio Romania", url = "https://stream.djradio.ro/radio/8000/stream.mp3"},
    {name = "Atmospheric Dnb S0Urce", url = "https://brokenbeats.net/stream/aac"},
    {name = "Radio Tequila Dance Romania", url = "http://dance.radiotequila.ro:7000/;stream.nsv"},
    {name = "Eteatru", url = "http://stream2.srr.ro:8078/eteatru.mp3"},
    {name = "Național FM", url = "http://live2.nationalfm.ro:8001/;"},
    {name = "Kiss Fm", url = "https://live.kissfm.ro/kissfm.aacp"},
    {name = "Radio Reggaeton", url = "http://85.120.223.142:8888/stream?icy=https"},
    {name = "Prob Radio", url = "http://live.radioprob.ro:8888/stream"},
    {name = "RFI Romania", url = "http://asculta.rfi.ro:9128/live.aac"},
    {name = "Radio Trinitas", url = "http://81.196.25.70:8000/"},
    {name = "Radio România Muzical", url = "http://stream2.srr.ro:8022/"},
    {name = "Focus FM", url = "http://live.focusfm.ro:8000/focusfmhigh.ogg.m3u"},
    {name = "Chill FM Romania", url = "http://edge126.rdsnet.ro:84/profm/chillfm.mp3"},
    {name = "Radio Oldies Romania", url = "http://listen.radiooldies.ro:9200/;"},
    {name = "Mooz Dance TV - Sunet ONLINE By Romaniaradioro", url = "http://109.103.178.66:8018/listen.pls"},
    {name = "Radio Petrecăretzu", url = "http://live.radiopetrecaretzu.ro:8383/;"},
    {name = "Radio Romanian Manele", url = "https://asculta.radioromanian.net/8300/stream"},
    {name = "Play Radio 916", url = "http://live.playradio.org:9090/FMHD"},
    {name = "Romantic FM", url = "http://zuicast.digitalag.ro:9420/romanticfm"},
    {name = "Radio Romania International", url = "http://stream2.srr.ro:8052/;"},
    {name = "Radio MANELE", url = "https://play.wrhradios.com/8044/stream"},
    {name = "90S 3Nergy", url = "https://s11.ssl-stream.com/ssl/90s_energy?mp=/stream"},
    {name = "Antena Satelor", url = "http://89.238.227.6:8042/"},
    {name = "Radio Boom House Music", url = "https://stream.radioboom.ro/listen/boom_house_music/radio.mp3"},
    {name = "Radio Guerilla", url = "http://live.guerrillaradio.ro:8010/guerrilla.aac"},
    {name = "Radio Folclor", url = "https://ssl.omegahost.ro/8092/stream"},
    {name = "Radio Cartier Romania", url = "https://live.radiocartier.eu:8048/stream"},
    {name = "Doina", url = "http://89.43.138.116:8000/radiodoina.mp3"},
    {name = "Rock Fm Ballads", url = "https://live.rockfm.ro/ballads.rock"},
    {name = "Radio Transilvania - Cluj", url = "https://stream2.radiotransilvania.ro/Cluj"},
    {name = "Radio Bucuresti FM", url = "http://89.238.227.6:8032/;stream/1"},
    {name = "Radio Kids Romania", url = "https://asculta.radioromanian.net:10997/"},
    {name = "Extravaganza Radio", url = "https://s3.radio.co/s1492c0564/listen"},
    {name = "Radio Tequila Petrecere", url = "http://petrecere.radiotequila.ro:7000/;"},
    {name = "Radio Hit Fm Manele", url = "http://asculta.radiohitfm.net:8340/;"},
    {name = "Smart FM", url = "http://live.smartradio.ro:9128/live"},
    {name = "Eveniment FM Sibiu 1032", url = "https://live.gofm.ro:2000/stream/eveniment"},
    {name = "Play Radio Cafe", url = "http://live.playradio.org:9090/CafeHD"},
    {name = "Magic FM Romania", url = "https://live.magicfm.ro/magicfm.aacp"},
    {name = "Magic Sunset", url = "https://live.magicfm.ro/magic.lite"},
    {name = "Radio Etno Mania", url = "https://radio.sonicpanel.ro:9300/"},
    {name = "Radio Hot Style", url = "http://mp3.radiohot.ro:8000/stream"},
    {name = "Radio Timișoara 630 AM", url = "http://89.238.227.6:8352/"},
    {name = "One FM Dance", url = "https://live.onefm.ro/onefm.aacp"},
    {name = "Space Fm Dance", url = "https://spacefm.live/radio/8000/spacefm128"},
    {name = "Radio DEEA", url = "http://radiocdn.nxthost.com/radio-deea"},
    {name = "Dance FM", url = "https://edge126.rcs-rds.ro/profm/dancefm.mp3"},
    {name = "Alba24Ro", url = "http://movingrecords.radioca.st:8045/stream"},
    {name = "Radio Liberty Multiplayer Phonk Remix", url = "https://hs1.radiolibertymp.ro/listen/lmpphonk/stream.mp3"},
    {name = "Gospace", url = "https://live.gofm.ro:2000/stream/goSPACE/stream.mp3"},
    {name = "EBS | Electro", url = "https://azura.ebsmedia.ro/listen/electro/electro128.mp3"},
    {name = "Radio DA", url = "http://n01.radiojar.com/du8khw2d2wzuv"},
    {name = "FM Radio Manele", url = "http://a.fmradiomanele.ro:8054/stream"},
    {name = "Radio Vacanta", url = "http://89.238.227.6:8330/listen.pls"},
    {name = "MB Music Radio", url = "http://s33.myradiostream.com:16150/"},
    {name = "Radio Romantic", url = "http://stream.zeno.fm/72k4a597rs8uv"},
    {name = "Bucuresti FM", url = "https://stream4.srr.ro:8443/bucuresti-fm"},
    {name = "Radio Guerrilla", url = "https://live.guerrillaradio.ro:8443/guerrilla.aac"},
    {name = "Radio Dreams Dance Hits Adrenaline", url = "http://5.2.184.92:3390/radiodreams.g1.ro?icy=https"},
    {name = "Radio Armonia Romania", url = "http://audio.radioarmoniaro.bisericilive.com/mainradioarmoniaro.mp3.m3u"},
    {name = "RADIO MIRAJUL MUZICII", url = "http://live.radiomiraj.ro:9952/stream"},
    {name = "Radio România Iași", url = "http://89.238.227.6:8202/listen.pls"},
    {name = "Getarum Radio", url = "https://stream.clever-host.ro/8010/stream"},
    {name = "Radio România Cluj", url = "http://89.238.227.6:8384/"},
    {name = "Lounge Avenue", url = "https://arlandria.go.ro:7443/lounge"},
    {name = "Radio Timișoara", url = "http://89.238.227.6:8354/"},
    {name = "RADIO MANELE PETRECERE", url = "https://ssl.servereradio.ro/8123/stream"},
    {name = "ONEFM", url = "http://live.onefm.ro:9128/onefm.aacp"},
    {name = "Radio Deep", url = "http://live.radiodeep.ro:7500/;"},
    {name = "Radio ZEN", url = "https://streaming.shoutcast.com/radiozen"},
    {name = "OXO Radio", url = "https://s4.ssl-stream.com/listen/oxo_radio/radio.mp3"},
    {name = "EBS | Movie Soundtracks", url = "https://azura.ebsmedia.ro/listen/movies/movies128.mp3"},
    {name = "Play Urban", url = "http://live.playradio.org:9090/UrbanHD"},
    {name = "Radio Oltenia Craiova", url = "http://stream2.srr.ro:8370/listen.pls"},
    {name = "Capital FM - Manele", url = "http://manele.capitalfm.ro:8020/;"},
    {name = "Dark Edge Radio", url = "http://stream.darkedge.ro:8000/"},
    {name = "Radio Romania Constanta", url = "http://89.238.227.6:8332/listen.pls?sid=1"},
    {name = "Sweet FM Romania", url = "https://live.gofm.ro:2000/stream/SWEET/stream.mp3"},
    {name = "Radio Romania Muzical", url = "http://stream2.srr.ro:8020/listen.pls"},
    {name = "Radio Romanian Hip-Hop", url = "https://asculta.radioromanian.net/8400/stream"},
    {name = "Aripi Spre Cer Instrumental", url = "https://instrumental.aac.aripisprecer.ro/radio.mp3;"},
    {name = "CFM Radio", url = "http://stream2.radiocfm.ro:9090/CFM"},
    {name = "Radio Flo Manele", url = "https://live.radioflomanele.ro/8084/stream"},
    {name = "Radio Trinitas - Patriarhia Romana", url = "http://www.radiotrinitas.ro/radiotrinitas.pls"},
    {name = "Radio Folclor Buzau", url = "https://live.radiofolclorbuzaufm.ro:8910/stream"},
    {name = "Love Marilena Galați", url = "https://radio.sonicpanel.ro/8068/stream"},
    {name = "HIT FM Brasov", url = "https://s25.myradiostream.com/:16434/listen.mp3?nocache=1719549990"},
    {name = "Musicfm", url = "http://edge126.rdsnet.ro:84/profm/music-fm.mp3"},
    {name = "Radio Brașov", url = "https://live.radiobrasov.ro/stream.mp3?nocache=${Math.random()}"},
    {name = "Radio 7 Bucuresti Romania", url = "http://80.86.106.32:8000/radio7.mp3"},
    {name = "Magic Gold Hits", url = "https://live.magicfm.ro/magic.gold.hits"},
    {name = "Radio Energy Cugir", url = "https://sonicssl.namehost.ro/8790/stream/;"},
    {name = "Radio Mynele", url = "http://live.radiomynele.ro:8000/;"},
    {name = "247 FM Exotic", url = "http://exotic.radio247international.com:9810/;stream.mp3"},
    {name = "Radio Pro Manele", url = "http://radiopromanele.zapto.org:8000/stream"},
    {name = "Radio Gold FM", url = "http://80.86.106.110:8002/listen.pls"},
    {name = "Radio Romanian Dance", url = "https://asculta.radioromanian.net/8100/stream"},
    {name = "Radio Vacanța - Fresh", url = "https://stream4.srr.ro:8443/fresh_rv"},
    {name = "Radio Marketescu Reggaetrip-Hop", url = "https://s37.radiolize.com/radio/8100/radio.mp3"},
    {name = "Radio Arad", url = "http://85.120.220.205:8000/radio-arad.m3u"},
    {name = "România Oltenia-Craiova", url = "http://stream2.srr.ro:8370/;stream.mp3"},
    {name = "Radio Marketescu Minimal", url = "https://sonic2-rbx.cloud-center.ro:7022/stream"},
    {name = "TWIST -Radio Trap", url = "https://stream.zeno.fm/9dhe4r7upg8uv"},
    {name = "Kanal D2", url = "https://stream2.kanald.ro/iphone/knd-live.m3u8"},
    {name = "Nationa FM", url = "http://www.nationalfm.ro/assets/national-fm.pls"},
    {name = "Play Radio", url = "https://live.playradio.org:8443/90HD"},
    {name = "Radio Folclor Muntenia", url = "https://live.radiofolclormuntenia.ro:8008/stream"},
    {name = "Radio Vocea Evangheliei RVE Sibiu", url = "https://c13.radioboss.fm:18286/stream"},
    {name = "HIT FM Alba", url = "https://s3.myradiostream.com/4404/listen.mp3"},
    {name = "Radio Mioveni", url = "http://argesmioveninr1.radi0.im:8000/stream"},
    {name = "Radio Space 90", url = "http://ingame.go.ro:8003/stream"},
    {name = "Radio Goldies", url = "https://s10.streamingcloud.online/stream/13664"},
    {name = "Radio Taraf MANELE", url = "http://asculta.radiotaraf.ro:7100/;"},
    {name = "West City Radio", url = "http://live.westcityradio.ro:8000/mp3"},
    {name = "Radio Greenstone", url = "https://stream.clever-host.ro/8018/stream"},
    {name = "Itsy Bitsy", url = "http://live.itsybitsy.ro:8000/itsybitsy"},
    {name = "Rock Fm Blues", url = "https://live.rockfm.ro/blues"},
    {name = "Radio Voces Campi", url = "http://vocescampi.ro:8001/;"},
    {name = "Radio Romanian Popular", url = "https://asculta.radioromanian.net/8500/stream"},
    {name = "Free FM Rock București", url = "https://freefmrock.radioca.st/stream"},
    {name = "Radio Romanian Gold", url = "https://asculta.radioromanian.net/8900/stream"},
    {name = "Black Rhino Radio", url = "https://blackrhinoradio.out.airtime.pro/blackrhinoradio_a"},
    {name = "Plusz FM - Nagyvarad", url = "https://stream2.radiotransilvania.ro/Nagyvarad"},
    {name = "Radio Marketescu Houseminimal", url = "https://s31.radiolize.com/radio/8020/radio.mp3"},
    {name = "Roman FM", url = "https://live.romanfm.ro:8000/;rfm"},
    {name = "Radio Badita Popular", url = "http://89.39.189.29:8000/listen.pls"},
    {name = "EBS Radio", url = "https://azura.ebsmedia.ro/public/live/playlist.m3u"},
    {name = "BUG Mafia", url = "https://stream-153.zeno.fm/x3626gvvsf9uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4MzYyNmd2dnNmOXV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InRBU2NXVkZDUWZHTkpWLUgySjdxa3ciLCJpYXQiOjE3MTU4MjkwNDIsImV4cCI6MTcxNTgyOTEwMn0.FEyU-KKrVHVgpMYMNw3sAdunkbEeCRtxphRRFVPnPDw"},
    {name = "Frăsinești Radio", url = "https://stream.zeno.fm/mpmilx1n4yuuv"},
    {name = "Radio Tequila Manele Romania", url = "https://petrecere.radiotequila.ro/7000/stream"},
    {name = "Free FM Bucarest", url = "https://rocafmadrid.radioca.st/"},
    {name = "RADIO MARIA ROMANIA HUNG", url = "http://dreamsiteradiocp4.com:8026/stream"},
    {name = "Baraka Radio", url = "https://ice.streams.ovh:1165/stream"},
    {name = "Atlas 21", url = "https://radio.manelemania.ro/listen/atlas21/atl21"},
    {name = "Intens", url = "http://live.radiointens.ro:8070/stream"},
    {name = "Radio România Brașov", url = "http://stream2.srr.ro:8210/;"},
    {name = "Radio Filadelfia", url = "https://b1.radiofiladelfia.ro:8101/filadelfia_128.aac"},
    {name = "EBS | Romanian Gold", url = "https://azura.ebsmedia.ro/listen/romaniangold/romaniangold128.mp3"},
    {name = "Radio Camarad", url = "https://93.115.53.53/radio"},
    {name = "Kolozsvári Rádió", url = "http://89.238.227.6:8386/listen.pls"},
    {name = "Rock Fm Hard Rock", url = "https://live.rockfm.ro/hard.rock"},
    {name = "Radio Veselia Folclor", url = "http://asculta.radioveseliafolclor.com:8232/;"},
    {name = "Radio Killer Câmpia Turzii", url = "https://s12.myradiostream.com/17492/listen.mp3"},
    {name = "Valori Românești Radio", url = "https://securestreams6.autopo.st:2250/"},
    {name = "Radio Super Manele", url = "http://manele.capitalfm.ro:8020/listen.pls"},
    {name = "90S 3Nergyremix", url = "http://s11.ssl-stream.com:8084/live"},
    {name = "Favorit FM", url = "http://91.250.252.251:8001/;"},
    {name = "RADAIO ROMANCE21ROMANIA", url = "https://stream.rcast.net/200392"},
    {name = "Radio România Actualități", url = "https://stream4.srr.ro:8443/romania-actualitati"},
    {name = "Radio Crazy", url = "http://live.crazyradio.ro:8024/stream"},
    {name = "Radio Taraf", url = "https://ddos.radiotaraf.ro/7100/stream"},
    {name = "Radio Korrupt Nostalgic", url = "http://stream.zeno.fm/ow1xlcqo3aatv"},
    {name = "Radio Romanian Disco", url = "https://asculta.radioromanian.net/8700/stream"},
    {name = "Radio Dada", url = "https://live.laris.ro:8004/radiodada128.mp3"},
    {name = "Paprika Rádió", url = "http://stream1.paprikaradio.ro:8000/;stream"},
    {name = "City Fm 983", url = "https://mscp1.gazduireradio.ro:1270/stream"},
    {name = "Music FM Romania", url = "https://live.musicfm.ro:8000/"},
    {name = "Radio Constanta FM", url = "http://89.238.227.6:8332/;stream/1"},
    {name = "Mária Rádió Erdély", url = "http://stream.mariaradio.ro:8000/MRE.m3u"},
    {name = "Radio Cuibul Lupilor Albi", url = "https://stream.zeno.fm/7s5mmrtzmuhvv"},
    {name = "Deearadio", url = "http://live.radiodeea.ro:8090/listen.pls"},
    {name = "Europa FM-AAC", url = "http://astreaming.virginradio.ro:8000/EuropaFM_aac"},
    {name = "Bairam Radio", url = "https://45.140.140.212:8144/stream"},
    {name = "Radio Gosen", url = "http://ascultaradiogosen.no-ip.org:8125/listen.pls"},
    {name = "Radio Orion", url = "http://90.84.231.191:7000/live.mp3"},
    {name = "RADIO PRO PARTY", url = "http://asculta.proparty.net:8567/stream"},
    {name = "Radio Tanănana", url = "https://live.tananana.ro:8443/stream-48.aac"},
    {name = "Radio Best Musik", url = "https://live.radiobestmusik.ro:8010/;"},
    {name = "Blaj Radio", url = "https://ssl.asculta.live:8016/"},
    {name = "Super FM", url = "https://live.superfm.ro/stream.mp3"},
    {name = "Radio Turda", url = "https://live.aftech.ro/radio/8010/radio.mp3"},
    {name = "Blues Radio", url = "http://stream.zeno.fm/bpn1hy0h6ehvv.m3u"},
    {name = "Radio Manele Romania", url = "http://petrecere.fmradiomanele.ro:8123/;stream.nsv"},
    {name = "Gofresh", url = "https://live.gofm.ro:2000/stream/goFMFRESH/stream.mp3"},
    {name = "EBS | Blues", url = "https://azura.ebsmedia.ro/listen/blues/blues128.mp3"},
    {name = "We Radio", url = "http://93.115.175.106:8000/player"},
    {name = "Capital FM - Dance", url = "https://ssl.omegahost.ro:8020/stream"},
    {name = "Cool FM", url = "https://live.aftech.ro/radio/8060/radio.mp3"},
    {name = "Ambiento", url = "https://ambiento-adradio.radioca.st/128"},
    {name = "Radio Lipova", url = "https://securestreams5.autopo.st:1888/;listen.pls"},
    {name = "Radio Lăutaru", url = "http://live.radiolautaru.ro:9000/;"},
    {name = "Radio Trandafirul Rosu", url = "https://stream-148.zeno.fm/46mdd8ebdchvv?zs=3KOOJiuCTAuEqso88MJ74A"},
    {name = "Jurnal FM", url = "https://ssl.radios.show:7009/stream"},
    {name = "Muscel FM 941", url = "http://188.27.135.199:8000/muscelfm"},
    {name = "Cozy FM", url = "https://live.cozyfm.ro:8010/live"},
    {name = "Gocafe", url = "https://live.gofm.ro:2000/stream/goCAFE/stream.mp3"},
    {name = "Radio Someș", url = "https://evcast01.mediacp.eu/somes"},
    {name = "Doxologia", url = "https://doxologia.ro/radio/radio_doxologia.pls"},
    {name = "RADIO MARIA ROMANIA", url = "http://dreamsiteradiocp2.com:8002/stream"},
    {name = "UNTOLD RADIO", url = "https://live-untold.distinct.ro:8001/untold.ogg"},
    {name = "Ascultă-Radio Levi", url = "http://audio.radioleviro.bisericilive.com/radioleviro.mp3"},
    {name = "Radio Flacara Rusaliilor", url = "http://86.35.4.210:8000/;"},
    {name = "Funfm", url = "http://online.funfm.ro:8000/funfm.mp3"},
    {name = "Radio Doza Manele", url = "https://manele.radiodoza.eu:8100/listen.pls"},
    {name = "Radio Vocea Evangheliei Suceava - RVE", url = "http://s9.yesstreaming.net:7014/stream"},
    {name = "Moinesti FM", url = "https://listen.moinestifm.ro/radio.mp3"},
    {name = "Radio Antena Braşovului", url = "http://streaming.radiomures.ro:8302/listen.pls"},
    {name = "Radio Delta Romania", url = "https://sslstreaming.com/8014/stream"},
    {name = "Radio Terra", url = "https://stream.radio-terra.ro/terra.aac"},
    {name = "Chill FM", url = "https://edge126.rcs-rds.ro/profm/chillfm.mp3?1712405207687"},
    {name = "Bistrița FM 926", url = "https://audio-edge-cmc51.fra.h.radiomast.io/66f238bb-8b61-4196-a8c3-28aea07235e8"},
    {name = "EBS | Lounge", url = "https://azura.ebsmedia.ro/listen/lounge/lounge128.mp3"},
    {name = "Social FM 969", url = "https://noasrv.caster.fm:10085/listen"},
    {name = "Radio Click Romania", url = "http://live.radioclick.ro:8008/"},
    {name = "Radio Noise Hip-Hop", url = "https://radio.sonicpanel.ro:9110/stream"},
    {name = "Radio Alba24", url = "https://movingrecords.radioca.st/;"},
    {name = "Biblia Audio - Radio Calea Spre Cer", url = "https://panel.radiocaleasprecer.com/radio/8010/radio.mp3"},
    {name = "TRADIȚIONAL POPULAR - Radio Calea Spre Cer LIVE 247", url = "https://panel.radiocaleasprecer.com/radio/8020/radio.mp3"},
    {name = "Poetunes Radio", url = "https://sonic1-rbx.cloud-center.ro/8054/stream"},
    {name = "Radio Aquila", url = "https://s10.webradio-hosting.com/proxy/schrteam/stream"},
    {name = "Pink Radio", url = "http://pink.exyuserver.com/stream"},
    {name = "Radio 3Net", url = "http://media.3netmedia.ro:8000/Live128.m3u"},
    {name = "Rádió Gaga Háromszék", url = "https://a3.my-control-panel.com:6670/radio.mp3"},
    {name = "Playradio Urban", url = "https://live.playradio.org:8443/UrbanHD"},
    {name = "Radio Vacanța - Gold", url = "https://stream4.srr.ro:8443/gold_rv"},
    {name = "Radio Bucovina", url = "http://radiobucovina.ro/live.m3u"},
    {name = "Radio RFM", url = "https://shout.realitatea.net:8001/mixt"},
    {name = "Gojazz", url = "https://live.gofm.ro:2020/stream/goJAZZ"},
    {name = "Radio Biserica Romano Catolica Bacau", url = "http://46.4.14.12:8020/listen.pls"},
    {name = "Radio Banat FM", url = "http://live.radiobanatfm.com:8002/listen.pls"},
    {name = "Radio Arges", url = "http://89.39.189.53:8000/listen.pls"},
    {name = "Trinitas", url = "https://www.radiotrinitas.ro/radiotrinitas.pls"},
    {name = "Radio Resita", url = "http://89.238.227.6:8344/listen.pls"},
    {name = "Martathonita Radio", url = "https://radio.mountathos.info/live"},
    {name = "Radio Rahanopolis", url = "http://86.120.124.101:8000/128"},
    {name = "Dcnews", url = "https://live.radiodcnews.ro:8443/public-live-feed"},
    {name = "Vox FM - Székelykeresztúr", url = "http://stream.voxfm.ro:8000/listen.pls"},
    {name = "Radio Nebunya", url = "http://asculta.radionebunya.ro:7575/"},
    {name = "City Radio Romania", url = "http://live.city-radio.ro:8800/;"},
    {name = "Radio Dacia Energie", url = "https://streaming.napocalive.ro/radio-dacia01"},
    {name = "Bigfm Deva", url = "http://82.208.143.10:8000/;"},
    {name = "Radio Prahova", url = "https://streamx.rph.ro:8100/relay;"},
    {name = "Pluszfm", url = "http://stream2.radiotransilvania.ro:8000/Nagyvarad"},
    {name = "Radioromanian Colinde", url = "https://asculta.radioromanian.net/8600/stream"},
    {name = "Alt FM", url = "http://asculta.radiocnm.ro:8002/live"},
    {name = "Star Rádió", url = "http://live.starradio.ro:9000/;&type=mp3"},
    {name = "Alien Club Fantasy", url = "http://radio.club-fantasy-hub.ro:8000/;"},
    {name = "Enjoy Radio", url = "https://live.enjoyradio.ro/radio/8000/enjoylive.mp3"},
    {name = "Rádió Gaga Udvarhelyszék", url = "https://a3.my-control-panel.com:6680/radio.mp3?1709996423"},
    {name = "Radio Extrem Live", url = "https://www.radio-extrem.com/asculta"},
    {name = "Superfm Brasov 938 FM", url = "https://live.superfm.ro/stream.mp3?nocache=0.19023860954617056"},
    {name = "Dejavumusic", url = "https://stream.zeno.fm/mdupctf7zxhvv"},
    {name = "Sepsi Rádió", url = "https://stream.sepsiradio.ro:8001/SepsiRadio"},
    {name = "Radio Damici", url = "http://ssl.radios.show:8004/stream"},
    {name = "Radio Manelescu", url = "https://my3.radiolize.com:8000/radio.mp3"},
    {name = "Radio Oldies", url = "http://live.radiooldies.ro:9200/listen.pls"},
    {name = "Space FM", url = "http://stream.radioparadise.com/world-etc-192"},
    {name = "Radio Sky FM", url = "http://89.43.138.116:8000/radiosky.mp3"},
    {name = "Radio Antena Satelor", url = "http://89.238.227.6:8042/listen.pls"},
    {name = "Supravibe Radio", url = "https://supraviberadio-radiohosting.radioca.st/stream"},
    {name = "Marlene Radio", url = "https://live.gofm.ro:2000/stream/MARLENERADIO/stream.mp3"},
    {name = "EBS | Jazz", url = "https://azura.ebsmedia.ro/listen/jazz/jazz128.mp3"},
    {name = "Ercis FM", url = "https://ercislive.enkosoft.com/live"},
    {name = "Radio Bandit", url = "http://live.radiobandit.ro:8000/320.mp3"},
    {name = "Nicecreamfm - Blue", url = "https://play.nicecream.fm/radio/8020/blue.mp3"},
    {name = "Nicecreamfm - Red", url = "https://play.nicecream.fm/radio/8000/red.mp3"},
    {name = "Radio Noise Rock", url = "https://radio.sonicpanel.ro:9130/"},
    {name = "Radio Noise Hits", url = "https://radio.sonicpanel.ro:9140/"},
    {name = "Radio Noise Gold", url = "https://radio.sonicpanel.ro:9170/"},
    {name = "Radio Romance 21", url = "http://live.radioromance21.ro:9950/stream"},
    {name = "Radio Eco Natura", url = "https://n0a.radiojar.com/fp5c3fgbyzzuv"},
    {name = "Ascultă-Rve Oradea", url = "http://38.96.148.39:6700/stream"},
    {name = "Radio FX Net", url = "http://asculta.radiofxnet.ro:8458/;"},
    {name = "Radio Calea Spre Cer LIVE 247", url = "https://panel.radiocaleasprecer.com/radio/8000/radio.mp3"},
    {name = "Dance Effect Radio", url = "http://asculta.danceeffect.ro:3333/;"},
    {name = "Napoca FM", url = "https://streaming.napocalive.ro/napoca-fm"},
    {name = "Radio 80", url = "https://live.radio80.ro:8443/s80"},
    {name = "Radio HY Brăila", url = "https://asculta.ascultatare.ro:8034/;"},
    {name = "Galaxy Radio", url = "https://radio.tgx.rs:25374/stream.m3u"},
    {name = "Radiopitesteanuromania", url = "https://free.rcast.net/246157"},
    {name = "HIT FM", url = "http://s3.myradiostream.com:4404/;"},
    {name = "Radiopapuc", url = "https://stream.zeno.fm/phcn6lncrj4tv"},
    {name = "Erdély FM", url = "https://efm.radioca.st/stream"},
    {name = "Radio Romanian Rock", url = "https://asculta.radioromanian.net/8800/stream"},
    {name = "Radio România 3 Net", url = "http://media.3netmedia.ro:8000/Live128"},
    {name = "Gofm", url = "https://live.gofm.ro:2000/stream/goFMro"},
    {name = "Szépvíz FM", url = "http://szepvizfm.ro:8000/"},
    {name = "Gobeach", url = "https://live.gofm.ro:2000/stream/goBEACH/stream.mp3"},
    {name = "Radio Marketescu Drumbass", url = "https://s51.radiolize.com/radio/8100/radio.mp3"},
    {name = "Radio Nova22", url = "http://s2.myradiostream.com:4520/listen.m4a"},
    {name = "Radio Marketescu Raptrap", url = "https://s45.radiolize.com/radio/8060/radio.mp3"},
    {name = "Gorebel", url = "https://live.gofm.ro:2000/stream/goREBEL/stream.mp3"},
    {name = "Radio Intens", url = "https://www.radiointens.ro/128.pls"},
    {name = "Aripi Spre Cer Predici", url = "https://predici.aac.aripisprecer.ro/radio.mp3"},
    {name = "Aripi Spre Cer Worship", url = "https://worship.aac.aripisprecer.ro/radio.mp3;"},
    {name = "Gorock", url = "https://live.gofm.ro:2020/stream/goROCK"},
    {name = "Radio Claudia", url = "http://ssl.kenhost.ro:8091/listen.pls?sid=1"},
    {name = "Radio Boom Energy", url = "https://stream.radioboom.ro/listen/boom_energy/radio.mp3"},
    {name = "Traffic Radio", url = "https://live.gofm.ro:2000/stream/traficradio"},
    {name = "Orion FM 917", url = "https://sonic1-rbx.cloud-center.ro/8070/stream"},
    {name = "Rádió Koko", url = "https://radiokoko.ro/live"},
    {name = "Agnus Rádió", url = "http://radio2.tirek.hu:8000/agnusradio"},
    {name = "Smart Radio", url = "https://live.smartradio.ro:8443/live"},
    {name = "Ascultă-Radio Unison", url = "http://audio.radiounisonro.bisericilive.com:8080/radiounisonro.mp3"},
    {name = "TWIST -Radio Ușoară", url = "https://stream.zeno.fm/g7uert66bxhvv"},
    {name = "Replica Radio Rock", url = "https://securestreams.autopo.st:2496/"},
    {name = "Radio Popular Arhiva 1", url = "http://web.archive.org/web/20180110095018if_/http://mp3.radiopopular.ro:7777/;"},
    {name = "Electric Castle", url = "https://electriccastle.out.airtime.pro/electriccastle_a"},
    {name = "Radio Dacia Paradis", url = "https://streaming.napocalive.ro/radio-dacia02"},
    {name = "MDI Fm", url = "http://stream.mdifm.ro:8000/live"},
    {name = "Club Radio", url = "https://live.clubradio.ro/listen/clubradio/live"},
    {name = "Marosvásárhelyi Rádió", url = "http://streaming.radiomures.ro:8312/;stream.nsv&type=mp3"},
    {name = "Metronom FM", url = "http://86.123.134.70:8000/metronom"},
    {name = "Radio Blue Romania", url = "https://asculta.muzicaok.de:8002/stream"},
    {name = "Radio Tranquila Manele", url = "https://live.radiotranquila.net:8032/stream"},
    {name = "Rádió Gaga Csíkszék", url = "https://a3.my-control-panel.com:6700/radio.mp3"},
    {name = "Radio Romania Targu Mures", url = "http://streaming.radiomures.ro:8302/listen.pls;/stream"},
    {name = "Radio Boom", url = "https://stream.radioboom.ro:8000/boom256k"},
    {name = "Rádió Gaga Marosszék", url = "https://a3.my-control-panel.com:6660/radio.mp3?1709995925"},
    {name = "Radio Vacanța Nostalgia", url = "https://stream4.srr.ro:8443/nostalgia_rv"},
    {name = "Unirea Radio", url = "http://82.208.158.156:8000/"},
    {name = "Social FM", url = "http://noasrv.caster.fm:10085/listen.m3u"},
    {name = "Radio Noise Party", url = "https://partylive.radionoise.ro:9160/"},
    {name = "Super FM Brasov 938", url = "https://live.superfm.ro/stream.mp3?time=1697692801"},
    {name = "Radio Greu De Difuzat", url = "https://greudedifuzat.ro/stream/"},
    {name = "Medias Fm", url = "http://mediasfm.eushells.ro:8082/;stream.nsv"},
    {name = "EBS | Magyar Zene", url = "https://azura.ebsmedia.ro/listen/hungarian/hungarian128.mp3"},
    {name = "EBS | Fresco", url = "https://azura.ebsmedia.ro/listen/fresco/fresco128.mp3"},
    {name = "Radio Manele Premium", url = "http://88.198.70.25:8894/;"},
    {name = "Nicecreamfm - Green", url = "https://play.nicecream.fm/radio/8010/green.mp3"},
    {name = "Supersonic Radio", url = "https://s5.radio.co/s08e5c5875/listen"},
    {name = "Radio Party București", url = "http://asculta.radiopartybucuresti.ro:8050/;"},
    {name = "Radio Noise Retro", url = "https://radio.sonicpanel.ro:9120/"},
    {name = "Radio CEAW", url = "https://dl.dropboxusercontent.com/s/scu6zf89qc0wu11/RadioCEAW.mp3"},
    {name = "Radio Stres", url = "http://live.radiostres.com:8402/;"},
    {name = "Radio Tequila Manele", url = "http://live.radiotequila.ro:7000/;"},
    {name = "Radio VIP", url = "http://live1.radiovip.ro:8969/;"},
    {name = "Radio ROT Romania", url = "http://radiorot.ovh:8000/radio.mp3"},
    {name = "Dux Radio", url = "https://radio.duxradio.ro:8002/stream"},
    {name = "Golounge", url = "http://fr1.streamhosting.ch/lounge128.mp3"},
    {name = "Radio Elim Español", url = "http://91.213.11.102:8023/stream_high"},
    {name = "Radio HIT Iasi", url = "http://live02.radiohit.ro:8000/hit.mp3"},
    {name = "Aripi Spre Cer", url = "https://mobile.stream.aripisprecer.ro/radio.mp3"},
    {name = "Free FM Bucaresti", url = "https://rocafmadrid.radioca.st/stream"},
    {name = "Radio A-Tentat", url = "https://ssl.omegahost.ro/8066/stream"},
    {name = "Radio FIR", url = "https://sonic1-rbx.cloud-center.ro/8010/stream"},
    {name = "Rádió Gaga Gyergyószék", url = "https://a3.my-control-panel.com:6690/radio.mp3"},
    {name = "Radio KPTV", url = "https://nl1.streamingpulse.com/ssl/KPTV"},
    {name = "Plusz FM - Margitta", url = "https://stream2.radiotransilvania.ro/Margitta"},
    {name = "Play Radio Urban Romania", url = "http://www.romaniaradio.ro/pls/play-urban.pls"},
    {name = "Radio Romania Targu Mures AM", url = "http://streaming.radiomures.ro:8322/"},
    {name = "You FM Romania", url = "https://asculta.muzicaok.de:8034/listen.pls"},
    {name = "Aripi Spre Cer International", url = "https://international.aac.aripisprecer.ro/radio.mp3"},
    {name = "Aripi Spre Cer Special", url = "https://special.aac.aripisprecer.ro/radio.mp3;"},
    {name = "Radio Dobrogea", url = "http://stream.arhivaradiodobrogea.ro:7000/dobrogea"},
    {name = "Radio Medias", url = "http://mediasfm.eushells.ro:8082/listen.pls"},
    {name = "Radio Boom Gold", url = "https://stream.radioboom.ro/listen/boom_gold/radio.mp3"},
    {name = "Radio Boom Rock", url = "https://stream.radioboom.ro/listen/boom_rock/radio.mp3"},
    {name = "Spliff Radio", url = "https://play.spliff.ro/legacy"},
    {name = "Replica Radio", url = "https://securestreams.autopo.st:2490/"},
    {name = "Https:Livereintregirearo", url = "https://live.reintregirea.ro/"},
    {name = "Reintregirea", url = "https://reintregirea.ro/sites/default/files/tema/radio.pls"},
    {name = "Radio Noise", url = "http://live.radionoise.ro:9100/;"},
    {name = "Half Is Enough", url = "http://centauri.shoutca.st:8322/stream"},
    {name = "Radio România Târgu Mureș - Marosvásárhelyi Rádió Románia", url = "http://streaming.radiomures.ro:8312/listen.pls?sid=1"},
    {name = "Impact FM", url = "http://109.166.241.233:8500/"},
    {name = "Radio Unique", url = "http://listen.radiounique.ro:8106/live"},
    {name = "Radio Dacia Relax", url = "https://streaming.napocalive.ro/radio-dacia03"},
    {name = "Radio Dacia Calm", url = "https://streaming.napocalive.ro/radio-dacia04"},
    {name = "Radio Boom Vrancea", url = "http://89.38.8.133:8000/listen.pls"},
    {name = "Radio Liberty Slagare", url = "http://slagare.radioliberty.ro:1989/"},
    {name = "Radio T", url = "http://82.77.249.68:8000/"},
    {name = "Hangos Rádió", url = "https://stream.zeno.fm/mv62tmd8wp8uv.aac"},
    {name = "Radio Master One", url = "http://whsh4u-server.com:11060/autodj"},
    {name = "Gofmro", url = "http://live.gofm.ro:9128/"},
    {name = "Régió Rádió", url = "https://live.regioradio.info/listen/"},
    {name = "EBS | Music", url = "https://azura.ebsmedia.ro/listen/music/music128.mp3"},
    {name = "Fresh FM", url = "https://radio.onlinehost.ro/listen/freshfm/radio.mp3"},
    {name = "Super FM Prahova", url = "https://asculta.superfmradio.ro:9720/stream"},
    {name = "Radio 1 FM 1072", url = "https://stream.zeno.fm/ekrzffgjb4ktv"},
    {name = "Manastirea Putna", url = "https://www.ortodoxradio.ro:8000/stream48"},
    {name = "Radio Condor Bucharest", url = "http://www.radiocondor.ro:6303/"},
    {name = "Gherlafm", url = "http://89.39.189.52:8000/stream"},
    {name = "Radio Renașterea", url = "https://rlive.radiorenasterea.ro/;"},
    {name = "Radio Alpin", url = "http://live.radiodeejay.hr:7002/;"},
    {name = "Radio Vestea Buna", url = "http://c34.radioboss.fm:8175/autodj"},
    {name = "EBS | Nouvelle Vague", url = "https://azura.ebsmedia.ro/listen/nouvelle/nouvelle128.mp3"},
    {name = "EBS | Alternative", url = "https://azura.ebsmedia.ro/listen/alternative/alternative128.mp3"},
    {name = "Profi Rádió", url = "http://93.115.175.141:8000/stream"},
    {name = "One World Radio", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/OWR_INTERNATIONAL_ADP"},
    {name = "Radio Trib", url = "https://streams.radio.co/s78f983952/listen"},
    {name = "Radio Tequila Hip-Hop", url = "http://necenzurat.radiotequila.ro:7000/;"},
    {name = "Radio Tequila Oldies", url = "https://stream.zeno.fm/5a1utt11fkhvv"},
    {name = "Radio Test", url = "https://hs1.radiolibertymp.ro/listen/lmpchill/stream.mp3?refresh=1700228324588"},
    {name = "Radio Elim Plus", url = "http://91.213.11.102:8003/stream3"},
    {name = "Retró Rádió Csíkszereda", url = "http://online.radioretro.ro:8002/RetroRadio.mp3"},
    {name = "Aripi Spre Cer Popular", url = "https://popular.stream.aripisprecer.ro/radio.mp3"},
    {name = "Fain Simplu", url = "http://zuicast.digitalag.ro:9420/fainsisimplu"},
    {name = "Radio Top Suceava", url = "https://live.radiotop.ro/radio/8000/radio.mp3"},
    {name = "Radio Maria", url = "http://cloudrad.io/radiomariaromania/listen.pls"},
    {name = "Rocker Inside", url = "https://cast4.my-control-panel.com/proxy/fountai1/stream"},
    {name = "Radio Etno Vest Timisoara", url = "http://ssl.radios.show:8020/;"},
    {name = "Radio Iubire", url = "http://ssl.radios.show:8026/;"},
    {name = "RADIO MAGIA INIMII TALE", url = "https://radio.cloud23.eu/magiainimiitale"},
    {name = "Radio Marketescu Rockpop", url = "https://s37.radiolize.com/radio/8040/radio.mp3"},
    {name = "Radio Underland", url = "https://radio.underland.team/radio/8000/radio.mp3"},
    {name = "Radio Lumina 904", url = "http://live.radiolumina.ro/lumina_winamp-hi.m3u"},
    {name = "Radiogaga", url = "http://rc.radiogaga.ro:8000/live"},
    {name = "Radio Marketescu Travel", url = "https://s103.radiolize.com:8020/radio.mp3"},
    {name = "Radio Xtream", url = "https://ssl.radios.show:7008/;"},
    {name = "Radio DOR Romania", url = "https://live7digi.antenaplay.ro/radiodor/radiodor-48000.m3u8"},
    {name = "Next Radio", url = "https://stream.nextradio.live/listen/nextradio/NextHD"},
    {name = "Radio Impuls RO", url = "https://live.radio-impuls.ro/stream"},
    {name = "Radio Dacia Clasic", url = "https://streaming.napocalive.ro/radio-dacia05"},
    {name = "Radio Dacia Traditional", url = "https://streaming.napocalive.ro/radio-dacia06"},
    {name = "Rádio Koko", url = "https://az10.yesstreaming.net:8210/radiokoko"},
    {name = "Cross One Radio", url = "https://lb01.bpstream.com:8630/;"},
    {name = "Radio Doza Urban", url = "https://stream.zeno.fm/cezx5b1nw98uv.pls"},
    {name = "Radio Trinitas 885", url = "https://live.radiotrinitas.ro:8003/;stream.nsv"},
    {name = "Radio Renaaterea Cluj", url = "https://radiorenasterea.ro/live.pls"},
    {name = "EBS | Classical", url = "https://azura.ebsmedia.ro/listen/classical/classical128.mp3"},
    {name = "EBS | Xmas", url = "https://azura.ebsmedia.ro/listen/xmas/xmas128.mp3"},
    {name = "Radio Crasna", url = "http://ssl.omegahost.ro/8006/stream/"},
    {name = "Siculus Rádió", url = "http://46.214.17.202:8000/radioac3"},
    {name = "Radio Elim", url = "http://91.213.11.102:8000/stream_high"},
    {name = "Radio Elim Air", url = "http://91.213.11.102:8011/stream_high"},
    {name = "Radio Peniel", url = "https://stream.zeno.fm/a26ipyehngytv"},
    {name = "Nova 22", url = "https://s2.myradiostream.com/4520/listen.mp3"},
}

return stations
