local stations = {
    {name = "Bestfm", url = "https://stream3.bestfm.sk:8000/160.aac"},
    {name = "Europa 2", url = "https://stream.bauermedia.sk/europa2.mp3"},
    {name = "Fun Radio", url = "http://stream.funradio.sk:8000/fun128.mp3"},
    {name = "Fun Radio Chill", url = "https://stream.funradio.sk:8000/chill128.mp3"},
    {name = "Fun Radio CZ", url = "http://stream.funradio.sk:8000/cs128.mp3"},
    {name = "Fun Radio Dance", url = "http://stream.funradio.sk:8000/dance128.mp3"},
    {name = "FUN RÁDIO 80-90", url = "http://stream.funradio.sk:8000/80-90-128.mp3"},
    {name = "Funradio Live", url = "http://stream.funradio.sk:8000/funpgm256.mp3"},
    {name = "Funradio Live 256Kbps", url = "https://stream.funradio.sk:8000/funpgm256.mp3"},
    {name = "Funrádio Mileniálky", url = "http://stream.funradio.sk:8000/milenialky128.mp3"},
    {name = "Infovojna", url = "http://159.69.219.5:8010/aac"},
    {name = "METALSCENA Netradio", url = "https://listen.radioking.com/radio/263218/stream/308365"},
    {name = "Radio Dychovka", url = "https://epanel.mediacp.eu:7661/stream"},
    {name = "Radio Expres", url = "http://195.168.61.226:8000/96.mp3"},
    {name = "Radio Expres SK", url = "https://stream.expres.sk/128.mp3"},
    {name = "Radio Romper Čechoslovakia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SAM05AAC415.aac"},
    {name = "Radio Vega", url = "http://stream.sepia.sk:8000/vega128.mp3"},
    {name = "Radio Vega Slovakia", url = "https://stream.sepia.sk:8000/vega128.mp3"},
    {name = "Radio VIVA", url = "https://stream.sepia.sk/viva128.mp3"},
    {name = "Radio Viva Metropol", url = "http://stream.sepia.sk:8000/viva128.mp3"},
    {name = "Rádio Bestfm", url = "https://stream3.bestfm.sk:8000/128.mp3"},
    {name = "Rádio Jazz", url = "http://stream.sepia.sk:8000/jazz128.mp3"},
    {name = "Rádio KIKS", url = "https://online.radiokiks.sk:8000/kiks_hq.mp3"},
    {name = "Rádio KIKS - Big 90S", url = "https://online.radiokiks.sk:8000/kiks_big90s.mp3"},
    {name = "Rádio KIKS - Rock Music", url = "https://online.radiokiks.sk:8000/kiks_rock.mp3"},
    {name = "Rádio Maria Slovensko", url = "http://dreamsiteradiocp5.com:8012/streaming.mp3"},
    {name = "Rádio Melody", url = "https://stream.bauermedia.sk/melody-hi.mp3"},
    {name = "Rádio Muzika", url = "https://listen.radioking.com/radio/276343/stream/321988"},
    {name = "Rádio Paráda", url = "https://extra.mediacp.eu/stream/RadioParada,o.z."},
    {name = "Rádio ROCK", url = "https://stream.bauermedia.sk/rock-hi.mp3"},
    {name = "Rádio Rock SV", url = "https://s2.myradiostream.com/:4870/listen.mp3"},
    {name = "Rádio Sity", url = "https://radiosity.online:8000/aac"},
    {name = "Rádio Topoľčany", url = "http://80.242.44.249:8000/;"},
    {name = "Rádio Vlna", url = "http://stream.radiovlna.sk/vlna-hi.mp3"},
    {name = "Rádio Vlna CLASSIC ROCK", url = "http://stream.radiovlna.sk:8000/rock-hi.mp3"},
    {name = "Slobodný Vysielač", url = "http://159.69.219.5:8010/mp3"},
}

return stations
