local stations = {
    {name = "5FM", url = "http://25483.live.streamtheworld.com/5FMAAC.aac"},
    {name = "702 Johannesburg", url = "http://27943.live.streamtheworld.com:3690/FM702_SC"},
    {name = "702 Talk Radio Johannesburg", url = "https://23543.live.streamtheworld.com/FM702AAC.aac"},
    {name = "919", url = "https://edge.iono.fm/xice/112_medium.aac"},
    {name = "947", url = "http://25443.live.streamtheworld.com/FM947_SC"},
    {name = "African Praise Radio", url = "https://usa3.fastcast4u.com/proxy/africanpraiserad?mp=/1"},
    {name = "AGANANG FM", url = "https://streaming.fabrik.fm/aganangfm/echocast/audio/low/index.m3u8?session_id=1pbxzwxy1RWaVFv&device_id=Q7fauplH"},
    {name = "Al-Ansaar Radio", url = "https://al-ansaar.simplestreaming.co.za/radio/8000/radio.mp3"},
    {name = "Algoa FM", url = "http://edge.iono.fm/xice/54_high.mp3"},
    {name = "Amapiano FM", url = "https://stream-156.zeno.fm/xs6zeac1ts8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ4czZ6ZWFjMXRzOHV2IiwiaG9zdCI6InN0cmVhbS0xNTYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjdfNDFqbGs0U3NTLXZOY05PX0N0SnciLCJpYXQiOjE3MjQ3MDM2NzIsImV4cCI6MTcyNDcwMzczMn0.moB7DBKI6AcUi0ArYb3B54vOCOo6_0NzOze65nKeK1w"},
    {name = "Bloem Radio Digital", url = "https://9300.co.za/listen/bloem_radio_digital/radio.mp3"},
    {name = "Bok Radio", url = "https://bokradio.highquality.radiostream.co.za/"},
    {name = "Bokradio", url = "http://bokradio.highquality.radiostream.co.za/"},
    {name = "Bosveld Stereo", url = "http://capeant.antfarm.co.za:8000/Bosveld"},
    {name = "Box Afrofusion Amapiano", url = "https://boxradio-edge-00.streamafrica.net/amp"},
    {name = "Cape Talk", url = "http://27753.live.streamtheworld.com:3690/CAPE_TALK_SC"},
    {name = "Cape Town Classic", url = "https://edge.iono.fm/xhls/fmr_live_high.m3u8"},
    {name = "Capital Radio 604", url = "https://stream.galaxywebsolutions.com/proxy/capitalradio604?mp=%2Fstream"},
    {name = "Capricorn FM", url = "http://edge.iono.fm/xice/67_medium.aac"},
    {name = "Chai FM", url = "https://zas1.ndx.co.za:8008/stream?1702143258610"},
    {name = "Channel Islam International", url = "http://edge.iono.fm/xice/109_medium.aac"},
    {name = "Classic FM 1027", url = "http://edge.iono.fm/xice/49_medium.aac?p=embed"},
    {name = "Cliff Central", url = "https://edge.iono.fm/xice/cliffcentral_live_medium.aac"},
    {name = "East Coast Gold", url = "https://live.ecr.co.za/ecrgoldhigh.mp3"},
    {name = "East Coast Radio", url = "https://live.ecr.co.za/ecrhigh.mp3?aw_0_pinpoll=1,2,9&listenerid=94d1ac3bf877b65e4e17cd7e9bfec132&awparams=companionAds%3Atrue&aw_0_1st.ri=iono"},
    {name = "ECR - East Coast Radio -Kwazulu Natal", url = "https://live.ecr.co.za/ecrlow.aac"},
    {name = "Emzini Fm Radio", url = "http://stream-151.zeno.fm/2kbssevq5tjvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIya2Jzc2V2cTV0anZ2IiwiaG9zdCI6InN0cmVhbS0xNTEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjJWQkVyZEthUmJHN2dmZ3Rvd1FIMHciLCJpYXQiOjE3MjQ2ODcwOTYsImV4cCI6MTcyNDY4NzE1Nn0.yntd3ajW0MVlbXpXLMQVS8-nh_JPLeSbBn3RbssXNCE"},
    {name = "Emzini Fm Radio", url = "http://stream-151.zeno.fm/2kbssevq5tjvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIya2Jzc2V2cTV0anZ2IiwiaG9zdCI6InN0cmVhbS0xNTEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImQ2NHNWTHF1U29LeUtyRTNlOTBZbEEiLCJpYXQiOjE3MjQ2NzIxOTAsImV4cCI6MTcyNDY3MjI1MH0.sZxVBiPv-hwv0dU0m33H5zNJ_rqqv_tgyQp7Nw34yNA"},
    {name = "Express-Fm Digital", url = "http://198.7.59.28:34235/stream"},
    {name = "Faithofgodseedchurch", url = "http://faithofgodseedchurch.stream.laut.fm/faithofgodseedchurch?pl=pls&t302=2024-08-26_17-30-55&uuid=2bbcc95d-a2ca-40c5-8db9-53a99afe70c6"},
    {name = "Fine Music Radio", url = "http://edge.iono.fm/xhls/fmr_live_medium.m3u8"},
    {name = "Gaysa Radio", url = "https://zas1.ndx.co.za:8018/stream"},
    {name = "Groot FM", url = "https://cast3.my-control-panel.com/proxy/grootfm/stream?1682362396578"},
    {name = "Harties FM", url = "https://s5.radio.co/s68c6f4028/listen"},
    {name = "Heaven FM", url = "https://stream-176.zeno.fm/eequgfw72hhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJlZXF1Z2Z3NzJoaHZ2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InZaTHFSNE5XUVZTLS1Ub3ZkWFd5d3ciLCJpYXQiOjE3MjQ2NTQ3NDMsImV4cCI6MTcyNDY1NDgwM30.S9J9XzIyHvMDdVqS-awdx7kIbdU3Ev2zdg35QqEUDko"},
    {name = "Helderberg FM", url = "https://helderberg.highquality.radiostream.co.za/"},
    {name = "Hellenic Radio", url = "http://iceant.eclipse-streaming.co.za/Hellenic"},
    {name = "Ilizwi Fm", url = "https://sv2.famcast.co.za/proxy/ilizwi_fm/stream"},
    {name = "Impala Radio", url = "https://maggie.torontocast.com:8014/stream"},
    {name = "Izwi Lomzansi", url = "https://streaming.fabrik.fm/izwi/echocast/audio/index.m3u8"},
    {name = "Jacaranda", url = "https://live.jacarandafm.com/jacarandahigh.mp3"},
    {name = "Jacaranda FM", url = "https://live.jacarandafm.com/jacarandalow.aac"},
    {name = "Jacarandahigh", url = "https://live.jacarandafm.com/jacarandalow.aac"},
    {name = "Jakaranda FM", url = "https://live.jacarandafm.com/jacarandahigh.mp3"},
    {name = "JOY GOSPEL RADIO", url = "https://servidor17.brlogic.com:7012/live"},
    {name = "Joyful FM", url = "http://c15.radioboss.fm:8218/stream"},
    {name = "Jozi FM", url = "https://edge.iono.fm/xice/51_medium.aac"},
    {name = "Katlego Fm", url = "https://das-edge15-live365-dal02.cdnstream.com/a26642"},
    {name = "Katlego Fm", url = "https://das-edge15-live365-dal02.cdnstream.com/a26642"},
    {name = "Katlego Fm", url = "https://das-edge16-live365-dal02.cdnstream.com/a26642"},
    {name = "Kaya FM", url = "https://live-kaya.sharp-stream.com/kayalow.aac"},
    {name = "Kfm", url = "http://25583.live.streamtheworld.com/KFM_SC"},
    {name = "KM RADIO", url = "https://centova.hostingelectrica.net/proxy/kmradio?mp=/stream&1704296313782"},
    {name = "Kurara FM", url = "https://stream-173.zeno.fm/gvmschcf9yzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJndm1zY2hjZjl5enV2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjZaYS05WkRJUl9ha0hqd2JZdFROcXciLCJpYXQiOjE3MjQ2OTUwNTgsImV4cCI6MTcyNDY5NTExOH0.8F9SfrEKb8M2CVYOJoFMiCI--kbqbmCKgxqqqKGk0ww"},
    {name = "Lekker FM", url = "https://zas3.ndx.co.za:8002/stream"},
    {name = "Link FM EC", url = "https://de2.streamingpulse.com/ssl/LinkFM"},
    {name = "Lister FM", url = "http://www.adhocstreaming.co.za:8000/LuisterFM"},
    {name = "LM Radio", url = "https://streaming.fabrik.fm/lm-radio/echocast/audio/low/index.m3u8"},
    {name = "LM Radio South Africa", url = "http://cast.fabrik.fm:8008/"},
    {name = "Mabopane Rise Radio", url = "https://stream-151.zeno.fm/kyap8zs093yvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJreWFwOHpzMDkzeXZ2IiwiaG9zdCI6InN0cmVhbS0xNTEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjdqV1VsSWdEU0VPS19MOWJvOXFGZVEiLCJpYXQiOjE3MjQ2ODUxODEsImV4cCI6MTcyNDY4NTI0MX0.ar3_OLXNsO3CBjFybbTB7eL0RRoOr1S9sQENonlss3w"},
    {name = "Magic 828", url = "https://streaming.fabrik.fm/magic828/echocast/audio/low/index.m3u8"},
    {name = "MFM", url = "https://edge.iono.fm/xice/46_medium.aac"},
    {name = "NCDOH Radio The Healthy Sound From Northern Cape Department Of Health", url = "https://stream-154.zeno.fm/grjnbwcxbneuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJncmpuYndjeGJuZXV2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IllJcG9HNFJ2UXlHN3JGU0ZMdjBIVnciLCJpYXQiOjE3MjQ3MDAwNjUsImV4cCI6MTcyNDcwMDEyNX0.HqI05Z6AjAWM2Crni6pQBKItORjfA7VAVSYEEwCZmWI"},
    {name = "Orania Radio", url = "https://eclipse-radio2.eclipse-streaming.co.za/listen/radio_orania/radio.mp3"},
    {name = "Pep Feel Good Fm", url = "https://edge.iono.fm/xice/feelgood_live_high.aac"},
    {name = "Perron FM", url = "https://zas7.ndx.co.za:8044/stream?1694973588521"},
    {name = "Pitch Radio", url = "http://stream-172.zeno.fm/etw8vx9knm0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJldHc4dng5a25tMHV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkVwLVF1VU5pVDlxVFI3dXBKWnVpeVEiLCJpYXQiOjE3MjQ2OTg2NDYsImV4cCI6MTcyNDY5ODcwNn0.KWTdpLbY3FVYzob2_1uoOrpjBiX5s33PeVY2RtZbVwI"},
    {name = "Pretoria FM", url = "http://capeant.antfarm.co.za:8000/ptafm"},
    {name = "Radio 2000", url = "http://27743.live.streamtheworld.com/RADIO2000AAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=8310c16e-1928-4209-9339-97787465358b"},
    {name = "Radio 2000 SABC", url = "http://25483.live.streamtheworld.com/RADIO2000AAC.aac?dist=triton-widget&tdsdk=js-2.9&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=3e99e625-68d3-4273-8866-a73f7d8fe4d8"},
    {name = "Radio 786", url = "http://stream.krypton.co.za:8040/stream/"},
    {name = "Radio Free Tankwa", url = "http://26523.live.streamtheworld.com/SAM09AAC213_SC"},
    {name = "Radio Fynbos - Stilbaai", url = "https://stream-152.zeno.fm/w0cyqt4cyy8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ3MGN5cXQ0Y3l5OHV2IiwiaG9zdCI6InN0cmVhbS0xNTIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImhNbkY0T29nVE51b2NDS1BXVFZwWWciLCJpYXQiOjE3MjQ2Nzg1OTUsImV4cCI6MTcyNDY3ODY1NX0.2rfPJn-7OLPjAlYUqlzkN5GdeHTaZ86A3qjWHhAqT9w"},
    {name = "Radio Islam", url = "http://stream.radioislam.org.za:7542/radioislam.mp3"},
    {name = "Radio Islam International", url = "http://listen.radioislam.co.za:8080/radioislam.mp3"},
    {name = "RADIO NAMAKWALAND", url = "https://zas3.ndx.co.za:8034/stream"},
    {name = "Radio Orania", url = "https://saukradio.com/wp-content/uploads/2021/07/5-Julie-Orania.mp3"},
    {name = "Radio Pulpit", url = "https://edge.iono.fm/xice/189_medium.aac?ref=https%3A%2F%2Fwww.radiopulpit.co.za%2F&adToken="},
    {name = "Radio Veritas", url = "https://zas5.ndx.co.za:9618/stream?1722433923032"},
    {name = "Rainbow FM", url = "https://edge.iono.fm/xice/237_low.aac"},
    {name = "Redplay Radio", url = "http://stream-174.zeno.fm/a5r2rwnnffhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhNXIycndubmZmaHZ2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImNFajdIaGZ6UnhhWFZRTDBKQWhmbVEiLCJpYXQiOjE3MjQ2ODY2MjAsImV4cCI6MTcyNDY4NjY4MH0.JK05qzz7sMFUAHKTUhWvr-eq12oYFU9bQDQtxtpfyeM"},
    {name = "Replay Radio", url = "http://stream-174.zeno.fm/a5r2rwnnffhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhNXIycndubmZmaHZ2IiwiaG9zdCI6InN0cmVhbS0xNzQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjhGSlF3OTlDUllhdTltcVE5NWJHRGciLCJpYXQiOjE3MjQ2NzEzMzMsImV4cCI6MTcyNDY3MTM5M30.0G7WLPFGEpkIyA30H6gPJhQt4_SuRijrXqdYRzsbNVo"},
    {name = "RISE FM", url = "https://edge.iono.fm/xice/73_medium.aac?ref=https%3A%2F%2Frisefm.co.za%2F&adToken="},
    {name = "RSG", url = "http://25443.live.streamtheworld.com/RSGAAC.aac?dist=triton-widget&tdsdk=js-2.9&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=05b99128-657f-4c70-b58c-df652bf26291"},
    {name = "RSG SA", url = "http://25443.live.streamtheworld.com/RSGAAC.aac?dist=triton-widget&tdsdk=js-2.9&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=05b99128-657f-4c70-b58c-df652bf26291"},
    {name = "SAFFA Onair World Radio", url = "http://stream-153.zeno.fm/k8cqvwu2za0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJrOGNxdnd1MnphMHV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IklRbTZlUWFBUXBhLUtQQ1owWGZBVlEiLCJpYXQiOjE3MjQ2NjU0MDMsImV4cCI6MTcyNDY2NTQ2M30.O22idYr5Plgyd2AqC6bh0p_2iOzBkdGLywe3Zg9bUNk"},
    {name = "SAFM", url = "http://25433.live.streamtheworld.com/SAFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=8af09f6c-1528-4186-9e2b-4f0275cc87b9"},
    {name = "Salaam Media", url = "http://capeant.antfarm.co.za:1935/salaam/salaam.stream/chunklist_w1196116988.m3u8"},
    {name = "Salaammedia", url = "https://iceant.antfarm.co.za/Salaam"},
    {name = "SFM Streek Radio", url = "http://capeant.antfarm.co.za:8000/SFM"},
    {name = "Simply Making Success Radio", url = "https://stream-171.zeno.fm/ylvoyhv6tbntv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ5bHZveWh2NnRibnR2IiwiaG9zdCI6InN0cmVhbS0xNzEuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlJIQ3Y3SkFRVE42Q01BRGxfNkJfRVEiLCJpYXQiOjE3MjQ2Mzk3MTYsImV4cCI6MTcyNDYzOTc3Nn0.hwoRjAFhA1-jURzlXnM4H9IFBd7pu5evvX4WItVHhvU"},
    {name = "Sky Alpha HD", url = "https://sv2.famcast.co.za/proxy/skyalphahd?mp=/stream"},
    {name = "Starfm", url = "https://edge.iono.fm/xice/112_medium.aac"},
    {name = "Talk Radio 702", url = "https://27823.live.streamtheworld.com:443/FM702_192AAC.aac"},
    {name = "TAMBO FM", url = "https://listen.radioking.com/radio/326599/stream/374668?fbclid=IwAR3lWR7ZdVVmZBSBedW_Cv1xF_Q7KzGmUQ0stgVCc_A7kx8Cf3Ncek1ntxk"},
    {name = "Thobelafm", url = "https://22673.live.streamtheworld.com:443/THOBELAAAC.aac"},
    {name = "Trufm SABC", url = "http://25483.live.streamtheworld.com/TRUFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=ccfa99e2-501e-41aa-ba19-701128ad7a93"},
    {name = "Tuks FM", url = "http://edge.iono.fm/xice/tuksfm_live_medium.aac"},
    {name = "Tygerberg 104FM", url = "http://zas6.ndx.co.za:8007/"},
    {name = "Ubuntufm", url = "https://streaming.coollective.nl:8443/UbuntuFM"},
    {name = "Ubuntufm Africa", url = "https://streaming.coollective.nl:8443/UbuntuFMafrica"},
    {name = "Uniquefive HD Radio", url = "http://stream-153.zeno.fm/a4t818ymva0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhNHQ4MTh5bXZhMHV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InJ4aUtFWTdZVFdTdzVTbUdXZ2NZVVEiLCJpYXQiOjE3MjQ2Njg3NzYsImV4cCI6MTcyNDY2ODgzNn0.QUFW2KPaP4vHnds5mUMQ6I5hkTijeMJ0Xa5efQyth-k"},
    {name = "Viva Nation Radio", url = "https://servidor34-3.brlogic.com:7056/live?source=website"},
    {name = "YFM", url = "http://streaming.fabrik.fm/yfm/echocast/audio/index.m3u8"},
}

return stations
