local stations = {
    {name = "702 Johannesburg", url = "http://playerservices.streamtheworld.com/m3u/FM702.m3u"},
    {name = "919", url = "https://edge.iono.fm/xice/112_low.aac"},
    {name = "947", url = "http://playerservices.streamtheworld.com/m3u/FM947.m3u"},
    {name = "African Praise Radio", url = "https://fastcast4u.com/player/africanpraiserad/?pl=winamp&c=African%20Praise%20Radio"},
    {name = "Al-Ansaar Radio", url = "https://al-ansaar.simplestreaming.co.za/radio/8000/radio.mp3"},
    {name = "Algoa FM", url = "http://edge.iono.fm/xice/54_high.mp3"},
    {name = "Bosveld Stereo", url = "http://capeant.antfarm.co.za:8000/Bosveld"},
    {name = "Cape Talk", url = "http://playerservices.streamtheworld.com/m3u/CAPE_TALK.m3u"},
    {name = "Capricorn FM", url = "http://edge.iono.fm/xice/67_medium.aac"},
    {name = "CCFM 1075", url = "https://edge.iono.fm/xice/69_medium.aac"},
    {name = "Channel Islam International", url = "http://edge.iono.fm/xice/109_medium.aac"},
    {name = "Classic FM 1027", url = "http://edge.iono.fm/xice/49_medium.aac?p=embed"},
    {name = "Cliff Central", url = "https://edge.iono.fm/xice/cliffcentral_live_medium.aac"},
    {name = "East Coast Gold", url = "https://live.ecr.co.za/ecrgoldhigh.mp3"},
    {name = "Express-Fm Digital", url = "http://198.7.59.28:34235/stream"},
    {name = "Faithofgodseedchurch", url = "http://stream.laut.fm/faithofgodseedchurch.pls"},
    {name = "Harties FM", url = "https://s5.radio.co/s68c6f4028/listen"},
    {name = "Hellenic Radio", url = "http://iceant.eclipse-streaming.co.za/Hellenic"},
    {name = "Hot 1027 FM", url = "https://edge.iono.fm/xice/57_high.aac"},
    {name = "Hot 1027 FM Club", url = "https://edge.iono.fm/xice/306_high.aac"},
    {name = "HOT 919", url = "http://edge.iono.fm/xice/57_medium.mp3"},
    {name = "Jacaranda FM", url = "https://edge.iono.fm/xice/jacarandafm_live_medium.aac"},
    {name = "Jacarandahigh", url = "https://edge.iono.fm/xice/jacarandafm_live_high.aac"},
    {name = "JOY GOSPEL RADIO", url = "https://servidor17.brlogic.com:7012/live"},
    {name = "Joyful FM", url = "http://c15.radioboss.fm:8218/stream"},
    {name = "Jozi FM", url = "https://edge.iono.fm/xice/51_medium.aac"},
    {name = "Jozi FM Hifi Aac", url = "https://edge.iono.fm/xice/51_high.aac"},
    {name = "Katlego Fm", url = "https://streaming.live365.com/a26642"},
    {name = "MC 903 FM", url = "http://zas4.ndx.co.za:9066/stream"},
    {name = "Metro FM SA", url = "https://27993.live.streamtheworld.com/METROFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=496fec8c-5809-460a-beb7-3545115118ca"},
    {name = "MFM", url = "https://edge.iono.fm/xice/46_medium.aac"},
    {name = "Mix 938 FM", url = "https://edge.iono.fm/xice/113_medium.aac"},
    {name = "OFM 94 97 FM Bloemfontein", url = "http://edge.iono.fm/xice/ofm_live_medium.aac"},
    {name = "Orania Radio", url = "https://eclipse-radio2.eclipse-streaming.co.za/listen/radio_orania/radio.mp3"},
    {name = "Pep Feel Good Fm", url = "https://edge.iono.fm/xice/feelgood_live_high.aac"},
    {name = "Power 987", url = "https://edge.iono.fm/xice/65_medium.aac"},
    {name = "Pretoria FM", url = "http://capeant.antfarm.co.za:8000/ptafm"},
    {name = "PSH Radio", url = "https://radio2.whazup.mobi/listen/psh_radio/pshlive.aac?1725024971931"},
    {name = "Radio 2000", url = "http://27743.live.streamtheworld.com/RADIO2000AAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=8310c16e-1928-4209-9339-97787465358b"},
    {name = "Radio 2000 SABC", url = "http://25483.live.streamtheworld.com/RADIO2000AAC.aac?dist=triton-widget&tdsdk=js-2.9&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=3e99e625-68d3-4273-8866-a73f7d8fe4d8"},
    {name = "Radio 786", url = "http://stream.krypton.co.za:8040/stream/"},
    {name = "Radio Orania", url = "https://saukradio.com/wp-content/uploads/2021/07/5-Julie-Orania.mp3"},
    {name = "Radio Pulpit", url = "https://edge.iono.fm/xice/189_medium.aac?ref=https%3A%2F%2Fwww.radiopulpit.co.za%2F&adToken="},
    {name = "Rainbow FM", url = "https://edge.iono.fm/xice/237_low.aac"},
    {name = "RISE FM", url = "https://edge.iono.fm/xice/73_medium.aac?ref=https%3A%2F%2Frisefm.co.za%2F&adToken="},
    {name = "Salaammedia", url = "https://iceant.antfarm.co.za/Salaam"},
    {name = "SFM Streek Radio", url = "http://capeant.antfarm.co.za:8000/SFM"},
    {name = "Smile 904 FM", url = "https://edge.iono.fm/xice/212_medium.aac"},
    {name = "Starfm", url = "https://edge.iono.fm/xice/112_medium.aac"},
    {name = "TAMBO FM", url = "https://listen.radioking.com/radio/326599/stream/374668?fbclid=IwAR3lWR7ZdVVmZBSBedW_Cv1xF_Q7KzGmUQ0stgVCc_A7kx8Cf3Ncek1ntxk"},
    {name = "Thobelafm", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/THOBELAAAC.aac"},
    {name = "Trufm SABC", url = "http://25483.live.streamtheworld.com/TRUFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&burst-time=15&sbmid=ccfa99e2-501e-41aa-ba19-701128ad7a93"},
    {name = "Tuks FM", url = "http://edge.iono.fm/xice/tuksfm_live_medium.aac"},
    {name = "Tygerberg 104FM", url = "http://zas6.ndx.co.za:8007/"},
    {name = "Ukhozi FM SA", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/UKHOZIFMAAC_SC?dist=triton-widget&pname=tdwidgets"},
    {name = "Viva Nation Radio", url = "https://servidor34-3.brlogic.com:7056/live?source=website"},
}

return stations
