local stations = {
    {name = "Cope Directo 2", url = "https://flucast07-o-cloud.flumotion.com/cope/net2.mp3"},
    {name = "Cadena SER España", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3"},
    {name = "KISS FM", url = "https://adhandler.kissfmradio.cires21.com/get_link?url=https://bbkissfm.kissfmradio.cires21.com/bbkissfm.mp3"},
    {name = "Rock FM", url = "http://rockfm.cope.stream.flumotion.com/cope/rockfm-low.mp3.m3u"},
    {name = "RAC1", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RAC_1.mp3"},
    {name = "LOS 40 Principales España", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/Los40.mp3"},
    {name = "Café Del Mar", url = "https://streams.radio.co/se1a320b47/listen"},
    {name = "Ibiza Global Radio", url = "http://ibizaglobalradio.streaming-pro.com:8024/"},
    {name = "Cadena 100", url = "http://cadena100-streamers-mp3.flumotion.com/cope/cadena100.mp3"},
    {name = "Esradio", url = "http://livestreaming.esradio.fm/stream64.mp3"},
    {name = "RNE", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r1_main.m3u8?idasset=1712486"},
    {name = "ONDA CERO España", url = "https://atres-live.ondacero.es/live/ondacero/bitrate_1.m3u8"},
    {name = "1000 HITS 80S", url = "http://c2.auracast.net:8048/stream"},
    {name = "Radio Marca Madrid", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOMARCA_NACIONAL_SC"},
    {name = "Absolute Chillout", url = "http://edge4.peta.live365.net/b05055_128mp3"},
    {name = "RNE 5", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r5_madrid_main.m3u8?idasset=1712404"},
    {name = "LOS 40 Classic", url = "https://25633.live.streamtheworld.com/LOS40_CLASSIC.mp3"},
    {name = "Cadena Dial", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL.mp3"},
    {name = "Los 40 Urban", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_URBAN.mp3"},
    {name = "Costa Del Mar - Chillout AAC 96Kbps", url = "http://stream.cdm-chillout.com:8020/stream-AAC-Chill"},
    {name = "Chocolate FM", url = "http://streaming5.elitecomunicacion.es:8082/live.mp3"},
    {name = "RNE 3", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r3_main.m3u8?idasset=1712469"},
    {name = "80 EXITOS", url = "https://80sexitos.stream.laut.fm/80sexitos"},
    {name = "Los 40 Dance", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_DANCE_SC"},
    {name = "Cadena SER - Radio Valencia", url = "http://provisioning.streamtheworld.com/pls/SER_VALENCIA.pls"},
    {name = "Hit FM", url = "https://adhandler.kissfmradio.cires21.com/get_link?url=https://bbhitfm.kissfmradio.cires21.com/bbhitfm.mp3"},
    {name = "24H RTVE Televisión", url = "https://ztnr.rtve.es/ztnr/1694255.m3u8"},
    {name = "Electrodanceworld Radio", url = "http://stream.zeno.fm/s70bvdgqks8uv"},
    {name = "Catalunya Radio", url = "https://shoutcast.ccma.cat/ccma/catalunyaradioHD.mp3"},
    {name = "Loca FM Deep Techno", url = "http://s02.fjperezdj.com:8066/live"},
    {name = "Cafe Del Mar Channel 2", url = "https://s4.radio.co/seeae9c220/listen"},
    {name = "Rockfm 1017", url = "http://rockfm.cope.stream.flumotion.com/cope/rockfm.aac.m3u"},
    {name = "Ibiza Stardust Radio", url = "https://www.radioking.com/play/ibiza-stardust-radio-1"},
    {name = "Pure Ibiza Radio", url = "https://pureibizaradio.clubbingradios.com:9518/PureIbizaRadio"},
    {name = "Ibiza Live Radio", url = "https://streams.radio.co/sdc9cfaf77/listen"},
    {name = "Catalunya Informació Catinfo", url = "https://shoutcast.ccma.cat/ccma/catalunyainformacioHD.mp3"},
    {name = "Radio Libertad", url = "https://server9.emitironline.com:19482/stream?cb=1708722000350"},
    {name = "Chocolate FM HD", url = "http://streaming5.elitecomunicacion.es:8030/live.mp3"},
    {name = "Perfect Deep House", url = "https://stream.radiojar.com/asngk2sg798uv?1659885393"},
    {name = "Canal Sur Radio Andalucía", url = "https://cdnlive.codev8.net/rtvalive/smil:channel9.smil/chunklist_b250000.m3u8"},
    {name = "Radiolé", url = "https://provisioning.streamtheworld.com/pls/RADIOLEAAC.pls"},
    {name = "RADIO MARCA", url = "https://25633.live.streamtheworld.com/RADIOMARCA_NACIONAL.mp3"},
    {name = "Inselradio Mallorca", url = "http://addrad.io/445fxk9"},
    {name = "Maxima FM Madrid - FM 1043 - Madrid", url = "http://178.32.146.184:2088/stream/"},
    {name = "Loca FM Live", url = "http://s3.we4stream.com:8045/liv"},
    {name = "Flaix FM", url = "https://stream.flaixfm.cat/icecast"},
    {name = "RNE Clásica", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r2_main.m3u8?idasset=1712494"},
    {name = "RNE Radio 3", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r3_main.m3u8"},
    {name = "1000 80S Hits", url = "https://ais-sa9.cdnstream1.com/1898_128"},
    {name = "Esradioaac", url = "http://livestreaming9.esradio.fm/aaclive32"},
    {name = "Cienciaes", url = "http://ns331078.ip-176-31-120.eu:8000/mpd"},
    {name = "Onda Cero Noroeste", url = "http://stream.ondaceronoroeste.es:8000/stream"},
    {name = "Remember The Music FM 966", url = "https://eu1.lhdserver.es:9041/stream"},
    {name = "Cope Sevilla", url = "http://sevilla.copesedes.stream.flumotion.com/copesedes/sevilla.mp3.m3u"},
    {name = "Cafe Mambo Ibiza Radio", url = "http://streamer.radio.co/sd7b28e5f3/listen"},
    {name = "Ibiza Relax", url = "http://54.38.43.201:8036/stream-128kmp3-IbizaRelax"},
    {name = "Megastarfm", url = "http://megastar.cope.stream.flumotion.com/cope/megastar.mp3.m3u"},
    {name = "Radio Euskadi", url = "http://mp3-eitb.stream.flumotion.com/eitb/radioeuskadi.mp3"},
    {name = "Cadena SER Radio MADRID", url = "http://server7.20comunicacion.com:8040/"},
    {name = "Funky Corner Radio Spain", url = "https://ais-sa2.cdnstream1.com/2447_96.aac"},
    {name = "Canal Sur Flamenco Radio", url = "https://cdnlive.codev8.net/rtvalive/smil:channel7.smil/chunklist_b250000.m3u8"},
    {name = "INFORMA RADIO", url = "https://24x7.red:42045/informa"},
    {name = "Classic Old Time Radio", url = "http://stream.zeno.fm/b6v6nu8uhnruv"},
    {name = "RAC1 +1", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RAC_MES_1.mp3"},
    {name = "Loca Progressive House", url = "https://s02.fjperezdj.com:8056/live?listening-from-radio-garden=1647634146"},
    {name = "Radio Mi Amigo International", url = "https://procyon.shoutca.st:2199/tunein/rmai.pls"},
    {name = "El Toro TV", url = "https://edge-nodo-002.streaming.hitcloser.net/eltorotv-streaming-web/tracks-v1a1/mono.m3u8"},
    {name = "Ibiza 1", url = "https://stream.ibiza1.hits1radio.com/"},
    {name = "Cope Deportes", url = "https://net2-cope-rrcast.flumotion.com/cope/net2-low.mp3"},
    {name = "Radio Planeta Costa Del Sol", url = "https://radioplaneta.emitironline.com/radio"},
    {name = "Radio Nervión", url = "https://gruponervion.streaming-pro.com:6131/"},
    {name = "Radio España", url = "https://stream.zeno.fm/7ywx2u45vv8uv"},
    {name = "Costa Del Mar Smooth Jazz", url = "https://radio4.cdm-radio.com:18024/stream-mp3-Smooth"},
    {name = "Radio Nacional De España - Radio 5 Todo Noticias", url = "https://d131.rndfnk.com/star/crtve/rne5/main/mp3/128/stream.mp3?aggregator=tunein&cid=01GEP4MW5CAHPYP1EXHVKWFJ8W&sid=2OeE42hivuba6dTGvjnMGjKByQe&token=cdczXcnimVx4AY4iamqYbTMdu3cK7oBxmS2UQN9cWc0&tvf=pdPcDBxuVxdkMTMxLnJuZGZuay5jb20"},
    {name = "Cadena SER - Ràdio Barcelona", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_BARCELONA.mp3"},
    {name = "Ibiza Sonica", url = "https://ibizasonica.streaming-pro.com:8000/ibizasonica"},
    {name = "Loca FM Chillout", url = "http://s02.fjperezdj.com:8006/live"},
    {name = "LOCAFM REMEMBER", url = "http://s02.fjperezdj.com:8035/live"},
    {name = "Free FM Chill", url = "https://freefmchill.radioca.st/"},
    {name = "Euskadi Irratia", url = "http://mp3-eitb.stream.flumotion.com/eitb/euskadiirratia.mp3"},
    {name = "Loca FM Urban", url = "http://locafm02.we4stream.com:8015/live"},
    {name = "Punk", url = "https://punkirratia.net:8443/punk"},
    {name = "Cadena SER", url = "https://20073.live.streamtheworld.com/CADENASER_SC"},
    {name = "Esradio MP3 HQ", url = "https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-high.mp3"},
    {name = "RNE - R5 --> Madrid", url = "https://d121.rndfnk.com/star/crtve/rne5/mad/mp3/128/stream.mp3?cid=01GEP4QN2TSXQQDS2JQA783NYX&sid=2HgHkKUje0YQl468xMDmJHKhDmz&token=bRjUW1ZmpjTaF8EgRmo3u6OCUep9WTHKjib0rpzUUzw&tvf=FG8P7Wd9KBdkMTIxLnJuZGZuay5jb20"},
    {name = "RNE Radio Nacional De España", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r1_main.m3u8"},
    {name = "Hitz Latino FM", url = "http://stream.zeno.fm/aq899a53rs8uv"},
    {name = "Sleep Sea Radio", url = "https://live.radiospinner.com/sslp-96"},
    {name = "Catalunya Música Catmúsica", url = "https://shoutcast.ccma.cat/ccma/catalunyamusicaHD.mp3"},
    {name = "Spektra FM Valencia", url = "http://stm1.emiteonline.com:8008/spektrafm"},
    {name = "Multicanal Radio", url = "https://a2.asurahosting.com:8800/radio.mp3"},
    {name = "RADIO MARÍA ESPAÑA", url = "http://dreamsiteradiocp2.com:8006/stream"},
    {name = "Aragón Radio Zaragoza", url = "https://cartv.streaming.aranova.es/hls/live/aragonradio_aragonradio1.m3u8"},
    {name = "LOCA FM Techhouse", url = "http://s02.fjperezdj.com:8046/live"},
    {name = "Ovejas Negrax", url = "https://stream-035.zeno.fm/sd0wcp7ddd0uv"},
    {name = "Openlab Radio", url = "https://ice04.fluidstream.net/openlab.mp3"},
    {name = "Onda Wantuki", url = "https://stream.zeno.fm/5dfkzqm70s8uv"},
    {name = "Radio Marca Barcelona", url = "http://radioweb.radiomarcabarcelona.com:9000/stream.m3u"},
    {name = "Rne-Suspilne Ukraine", url = "https://rtvehlslivestream.akamaized.net/hls/live/2096140/rneoca/oca5/master.m3u8"},
    {name = "Catalunya Ràdio", url = "https://directes-radio-int.ccma.cat/live-content/catalunya-radio-hls/master.m3u8"},
    {name = "Vaughan", url = "http://vaughanradioweb.streaming-pro.com:8057/;streamdemo_mp3.nsv"},
    {name = "Cadena SER Radio Murcia", url = "http://playerservices.streamtheworld.com/m3u/SER_MURCIA.m3u"},
    {name = "Loca Ambient", url = "http://s02.fjperezdj.com:8036/live"},
    {name = "Esradio Asturias", url = "http://server9.emitironline.com:8822/radio"},
    {name = "SER+ CÁDIZ", url = "https://22673.live.streamtheworld.com/SER_MAS_CADIZ.mp3"},
    {name = "Canal FIESTA Radio Andalucia", url = "https://cdnlive.codev8.net/rtvalive/smil:channel5.smil/playlist.m3u8"},
    {name = "Cadena Cope - Más Madrid", url = "https://flucast08-h-cloud.flumotion.com/cope/net4.mp3"},
    {name = "Chocolate FM [Calidad Móvil-Low Bandwidth]", url = "http://streaming5.elitecomunicacion.es:8082/live32.aac"},
    {name = "Radio Nacional De España - Radio Clasica", url = "https://f141.rndfnk.com/star/crtve/rnerc/main/mp3/128/stream.mp3?cid=01GEM633TKTAHEB3GYTNAEZB90&sid=2OeEj3cbhDQiZQY1d3kTqQyea1Y&token=cHn_jT-26Z0rPqXMo0QMJUWS-2ZjHiwAiKVk3Y_JrX4&tvf=IU7TAmhuVxdmMTQxLnJuZGZuay5jb20"},
    {name = "RNE - R1 --> Madrid", url = "https://d121.rndfnk.com/star/crtve/rne1/mad/mp3/128/stream.mp3?cid=01GEM7S23A9B744SKFN04XA893&sid=2HgEg5aD71G8EuEf67MKTba5AnL&token=n_qXJorii6EVsZ_IP-RSzQP8sRamUc8gqb1nDnqiNT8&tvf=HHgasgd8KBdkMTIxLnJuZGZuay5jb20"},
    {name = "#1 Splash Spa", url = "https://ais-sa2.cdnstream1.com/2347_128.mp3"},
    {name = "Cope Madrid", url = "https://flucast02-h-cloud.flumotion.com/cope/madrid.mp3"},
    {name = "Radio Vallekas", url = "https://radio.radiobot.org/listen/rvk/rvk.mp3"},
    {name = "LOCA FM Techno", url = "http://s02.fjperezdj.com:8050/live"},
    {name = "RNE Radio 1 Galicia", url = "https://dispatcher.rndfnk.com/crtve/rne1/gal/mp3/high"},
    {name = "Onda Regional De Murcia", url = "https://crmlive.redctnet.es/liveedge/orm/orm/chunklist_w329392737.m3u8"},
    {name = "CUAC FM MP3", url = "https://streaming.cuacfm.org/cuacfm-128k.mp3"},
    {name = "Edenex", url = "https://cervera.eldialdigital.com:23121/stream"},
    {name = "Onda Cero Sevilla", url = "https://atres-live.ondacero.es/live/delegaciones/oc/sevilla/master.m3u8"},
    {name = "华夏之声China FM·西班牙马德里FM929", url = "https://radioserver12.profesionalhosting.com/proxy/pkg152387/stream"},
    {name = "1000 Oldies", url = "https://c3.auracast.net/radio/8010/;"},
    {name = "Radio Galega", url = "https://crtvg-radiogalega-hls.flumotion.cloud/playlist.m3u8"},
    {name = "Costa Del Mar", url = "http://sc-costadelmar.1.fm:10152/"},
    {name = "Onda Cero Malaga", url = "https://atres-live.ondacero.es/live/delegaciones/oc/malaga/master.m3u8"},
    {name = "Cadena SER Vitoria", url = "http://25603.live.streamtheworld.com/SER_VITORIA.mp3"},
    {name = "1000 HITS Classical", url = "https://ais-sa2.cdnstream1.com/2208_128.mp3"},
    {name = "#1 Splash Coffee", url = "https://ais-sa2.cdnstream1.com/2345_128.mp3"},
    {name = "1 Slow-Radio - Lautfm", url = "https://1slowradio.stream.laut.fm/1_slowradio"},
    {name = "Gladys Palmera Radio Online", url = "http://streamer.radio.co/sb28a7fb81/listen"},
    {name = "Esradio Principal", url = "https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-low.mp3"},
    {name = "Muybuena", url = "https://stream.mediasector.es/radio/8010/muybuena.mp3"},
    {name = "Cope Valencia", url = "https://wecast-b03-01.flumotion.com/copesedes/valencia.mp3"},
    {name = "Ibiza Sonica Club", url = "https://ibizasonica.streaming-pro.com:8011/sonicaclub"},
    {name = "Ondacero Granada", url = "https://atres-live.ondacero.es/live/delegaciones/oc/granada/bitrate_1.m3u8"},
    {name = "Cadena SER Sevilla", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_SEVILLA.mp3"},
    {name = "ABSOLUTE CHILLOUT España", url = "https://ais-edge89-dal02.cdnstream.com/b05055_128mp3"},
    {name = "House Radio Spain", url = "http://37.187.76.127:8010/houseradio"},
    {name = "Radio Sevillanas", url = "http://radio.wesped.com:8000/stream"},
    {name = "Radio Almaina", url = "http://s.streampunk.cc/almaina.ogg"},
    {name = "FORMULA 10 MUSICA", url = "https://formula10musica.stream.laut.fm/formula10musica"},
    {name = "C DIAL Baladas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL_03.mp3"},
    {name = "Cadena Ser +", url = "https://27953.live.streamtheworld.com/CADENASER_ALT1AAC.aac"},
    {name = "Cadena Ser Mallorca", url = "http://provisioning.streamtheworld.com/pls/SER_MALLORCA.pls"},
    {name = "Onda Vasca Gipuzkoa", url = "http://www.ondavasca.com:8000/gipuzkoa"},
    {name = "Radio Exterior De España", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_re_main.m3u8"},
    {name = "RNE Radio 5 Las Palmas", url = "https://d121.rndfnk.com/star/crtve/rne5/lpa/mp3/128/stream.mp3?cid=01GEP4X9Y3EYSQDV2G2MRTWGGZ&sid=2KXdzbu8f6MPAaCmdrAfA7scSHY&token=wiTLRflaxoLHseM8UraPggqszRT9NNr2mUoTnKi8TdU&tvf=6Up4UpPDOxdkMTIxLnJuZGZuay5jb20"},
    {name = "Europa FM España", url = "https://agregadores-atres-live.atresmedia.com/tunein/live/europafm/bitrate_1.m3u8"},
    {name = "Energía Flamenca", url = "https://axarquia.emisiononline.es/radio/8020/radio.mp3"},
    {name = "Ràdio Olot", url = "http://chrome.frilab.com:8000/radiolot"},
    {name = "LA JUNGLA RADIO", url = "https://streaming12.elitecomunicacion.es:8626/stream?type=.mp3"},
    {name = "Loca FM Industrial", url = "http://s02.fjperezdj.com:8076/live"},
    {name = "CADENA DIAL España", url = "https://cadena100-cope-rrcast.flumotion.com/cope/cadena100.mp3"},
    {name = "24 Horas", url = "https://rtvelivestream-clnx.rtve.es/rtvesec/24h/24h_main_360.m3u8"},
    {name = "Radio Maria Spain Espana", url = "http://dreamsiteradiocp.com:8060/;stream.mp3"},
    {name = "Blue Marlin Ibiza", url = "https://ibizasonica.streaming-pro.com:8001/bluemarlin"},
    {name = "LOVE RADIO - Loveradio", url = "https://loveradio.streamingmedia.it/espana"},
    {name = "Adagio Radio HD", url = "https://stream.tunerplay.com/radio/8010/adagioradioHD.mp3"},
    {name = "Digital Hits FM", url = "https://dhits.frilab.com:8443/dhits"},
    {name = "Radio Popular Herri Irratia - Bilbao", url = "http://79.137.33.224/radiopopular2"},
    {name = "+Buena FM", url = "https://sonic.mediatelekom.net/8156/stream"},
    {name = "77 RADIO LA PALMA FM 883 - 998", url = "https://radioserver11.profesionalhosting.com/proxy/suoqgqzc?mp=/stream"},
    {name = "NEGOCIOSCOM", url = "https://streaming013.gestec-video.com/hls/negociostv.m3u8"},
    {name = "Ibiza Global Classics", url = "https://control.streaming-pro.com:8000/ibizaglobalclassics.mp3"},
    {name = "Cadena Ser - Las Palmas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_LAS_PALMAS.mp3"},
    {name = "Los 40 Catalunya", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CAT_SC"},
    {name = "Radio Remember Last", url = "https://node-25.zeno.fm/5nvz43btqg8uv?rj-ttl=5&rj-tok=AAABd24dwXQAYQSRcz9whBAeXA"},
    {name = "La 1", url = "https://rtvelivestream.akamaized.net/rtvesec/la1/la1_main_360.m3u8"},
    {name = "Baby Radio España", url = "https://sd396babyradio1.dns-lcinternet.com/8002/stream"},
    {name = "Amor FM", url = "https://stream.zeno.fm/fqmu9c005hhvv"},
    {name = "Canal Fiesta Radio", url = "https://cdnlive.codev8.net/rtvalive/smil:channel4.smil/playlist.m3u8"},
    {name = "RNE - R5 --> Valencia", url = "https://f131.rndfnk.com/star/crtve/rne5/vlc/mp3/128/stream.mp3?cid=01GEP70HQKHM3WJB5GHG662KX3&sid=2HgIGK1NtDDUVhSnKN9RWpCUKWE&token=r4st34giurxRWd0CMkMBmwayGa2nB6j_aUgMn_xD7vs&tvf=RH0CSKN9KBdmMTMxLnJuZGZuay5jb20"},
    {name = "Bikini FM Marina Baja Benidorm", url = "https://stream.mediasector.es/radio/8030/bikinifm.mp3"},
    {name = "Radioblues Flac", url = "https://streams.radiomast.io/radioblues-flac"},
    {name = "Cadena100", url = "https://cadena100-cope.flumotion.com/playlist.m3u8"},
    {name = "Smooth Jazz Classics By Cloud Jazz", url = "https://stream-57.zeno.fm/w3phtkukfg8uv?zs=90IfdbcARnS99_b8RaX9sQ&acu-uid=736851429618&dyn-uid=&an-uid=0&mm-uid=a42b63d5-b9eb-4f00-9692-60c79195c3a4&triton-uid=cookie%3A7e5c2d9b-9c30-46f6-b8b4-0354fd4dd340&amb-uid=3916839388731891724"},
    {name = "Hitz 90S FM", url = "https://stream.zeno.fm/1q3dwmd6yf8uv"},
    {name = "Radio Vilasound Ibiza 927 FM", url = "https://s9.citrus3.com:8174/stream"},
    {name = "COPE Málaga", url = "http://net1.cope.stream.flumotion.com/cope/net1.mp3.m3u"},
    {name = "COPE + Sevilla", url = "http://wecast09-h-cloud.flumotion.com/copesedes/sevilla-mas.mp3"},
    {name = "RAC105", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/RAC105.mp3"},
    {name = "LOS40 Classic", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CLASSIC.mp3"},
    {name = "Cope Granada", url = "https://granada-copesedes-flucast.flumotion.com/copesedes/granada.mp3.m3u"},
    {name = "Kiss-Fm Madrid", url = "https://kissfm.kissfmradio.cires21.com/kissfm.mp3"},
    {name = "Otaku Musicradio", url = "http://kathy.torontocast.com:2880/listen.pls?sid=1"},
    {name = "Esradio Tenerife", url = "https://panel5.soydigital.fm/8024/live?1678446871465"},
    {name = "RADIO BOB", url = "https://streams.radiobob.de/bob-national/mp3-192/homepage?mode=preroll&aw_0_1st.skey=1671400102&cb=286873666&aw_0_1st.playerid=radiobob_web&aw_0_req.userConsentV2=CPkIkEAPkIkEAAFADBDECvCsAP_AAEPAAAYgI9td_H__bW9j-f5_aft0eY1P9_rz7uQzDhfNk-4F3L_W_LwX52E7NF36tq4KmR4ku1LBIQNlHMHUDUmwaokVryHsak2cpSNKJ7BEknMZOydYGF9Pmxtj-QKY5v5_d3bx2D-t_9v-39z338VXn3d53-_02PDdV599Dfn9fR_b89KP9958v4v8_____3_e__3_74I9gEmGrcQBdmWODNoGEUCIEYVhIRQKACCgGFogIAHBwU7KwCfWECABAKAIwIgQ4AowIBAAAJAEhEAEgRYIAAARAIAAQAIAEIAGBgEFgBYGAQAAgGgYohQACBIAZEBEUpgQFQJBAS2VCCUFUhphAFWWAFAIjYKABEEgIpAAEBYOAYIkBKxYIEmKN8gBGCFAKJUIAgaADAAEEexEAGAAII9ioAMAAQR7GQAYAAgj2AAA.YAAAAAAAAAAA&aw_0_1st.kuid=kppidff_PQ5ovBN7&aw_0_1st.ksg=%5B%22vz9c46692%22%5D&listenerid=c47683ff451bdf8ebe068dea8a897b50"},
    {name = "Ràdio Klara HQ", url = "https://www.radioklara.org/emision2.m3u"},
    {name = "Gaztea Irratia", url = "http://mp3-eitb.stream.flumotion.com/eitb/gaztea.mp3"},
    {name = "13 TV", url = "https://play.cdn.enetres.net/091DB7AFBD77442B9BA2F141DCC182F5021/021/playlist.m3u8"},
    {name = "Radioteletaxi", url = "http://radiott-web.streaming-pro.com:6103/radiott.mp3"},
    {name = "Hits 1 Ibiza", url = "https://player.ibiza.hits1radio.com/"},
    {name = "Ladiez", url = "https://panel5.soydigital.fm/8030/stream"},
    {name = "ROCK FM España", url = "http://rockfm.cope.stream.flumotion.com/cope/rockfm/playlist.m3u8"},
    {name = "Locafm Melodic Deep", url = "http://s02.fjperezdj.com:8056/live"},
    {name = "Misterio FM", url = "https://stream-38.zeno.fm/zr1ntv61fchvv?zs=B6YIARuRSaujjyuQoZxg0g"},
    {name = "#1 Splash 90S", url = "https://c4.auracast.net/radio/8050/radio.mp3"},
    {name = "#1 Splash 90S Dance", url = "https://c6.auracast.net/radio/8090/radio.mp3"},
    {name = "Radio Bluesflac", url = "https://audio-edge-jfbmv.sin.d.radiomast.io/radioblues-flac?t=nightvision%3Fs%3D88baf5be-4b2d-416a-afc6-b0d9be7c9f1e&cachebuster=5213503296919065"},
    {name = "#1 Splash Lounge", url = "https://ais-sa2.cdnstream1.com/2209_128.mp3"},
    {name = "Gladys Palmera Latin Fresh", url = "https://streamer.radio.co/s00c7ec6fa/listen"},
    {name = "IB3 Ràdio Mallorca", url = "https://icecast.ib3radio.com/ib3radio.mp3"},
    {name = "Marca Valladolid", url = "https://radiomarcavalladolid.streaming-pro.com:6106/radiomarca.mp3"},
    {name = "Ibiza Sonicalm", url = "https://ibizasonica.streaming-pro.com:8014/sonicalm"},
    {name = "Radio Bilbao SER", url = "https://25553.live.streamtheworld.com/SER_BILBAO.mp3"},
    {name = "Radio Moscatel 1071 FM Axarquía - España", url = "https://axarquia.emisiononline.es/radio/8040/radio.mp3"},
    {name = "Hola 957 FM 1 Costa Calma", url = "http://5.135.183.124:8207/stream"},
    {name = "Radio Oasis", url = "https://cervera.eldialdigital.com:21141/stream"},
    {name = "1000 Hits Spain", url = "https://c2.auracast.net:8022/;"},
    {name = "Exito Radio", url = "http://5.135.183.124:9252/stream"},
    {name = "Cope Carballiño", url = "http://radio.copecarballino.es:8000/directo.mp3"},
    {name = "Digital Hits", url = "http://digitalhits.frilab.com:8000/digitalhits"},
    {name = "Intimidad Relax", url = "https://eu1.lhdserver.es:9121/stream"},
    {name = "Qfm", url = "http://51.255.235.165:5092/;"},
    {name = "Swing Latinos FM", url = "https://eu1.lhdserver.es:9033/stream"},
    {name = "Cadena Cope - Más Valencia", url = "https://wecast12-h-cloud.flumotion.com/copesedes/valencia-mas.mp3"},
    {name = "Cadena 100 Barcelona", url = "https://cadena100bcn-cope.flumotion.com/playlist.m3u8"},
    {name = "La Mega Super Dance", url = "https://stream.mediasector.es:8020/lamega.mp3?icy=https"},
    {name = "COPE Albacete", url = "https://albacete-copesedes-flucast.flumotion.com/copesedes/albacete.mp3.m3u"},
    {name = "Top Radio Madrid - 972 FM - Multimedios Radio - Madrid, España", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/TOPRADIOAAC.aac"},
    {name = "Radio Andalucía Información", url = "https://cdnlive.codev8.net/rtvalive/smil:channel34.smil/chunklist_b250000.m3u8"},
    {name = "Radio Del Principáu D'Asturies [RPA]", url = "https://cdnlive.codev8.net/rtpalive/smil:radio.smil/chunklist_b1000000.m3u8"},
    {name = "Mallorca Sunshine Radio", url = "https://stream.inselradio.com/high.sunshine.mp3"},
    {name = "Talk Radio Europe", url = "http://s3.yesstreaming.net:7014/stream"},
    {name = "Retropop", url = "http://stream.zenolive.com/aqr9g5q5pvduv.m3u"},
    {name = "Esradio AAC HQ", url = "https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-high.aac"},
    {name = "Europa FM Guipuzcoa", url = "https://stream.zeno.fm/se76qau1hc9uv"},
    {name = "FUNKY TRACKS RADIO Barcelona", url = "http://streaming2.elitecomunicacion.es:8134/stream"},
    {name = "Onda 4 Ronda", url = "https://cervera.eldialdigital.com:23161/stream"},
    {name = "Beachgrooves Radio", url = "https://stream.beachgrooves.com:9000/stream"},
    {name = "Sputnik Radio", url = "http://sputnikradio.es:8009/live"},
    {name = "Cadena SER Radio San Sebastián", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_PONTEVEDRAAAC.aac"},
    {name = "Cadena Ser - Radio León", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_LEON.mp3"},
    {name = "RNE Radio 5 Asturias", url = "https://rtvehlslivestream.akamaized.net/hls/live/2097769/rne5/ast/master.m3u8"},
    {name = "Hits 1 Mallorca", url = "https://radio7.pro-fhi.net/radio/9006/hits1ibiza"},
    {name = "Cadena SER Almería 882 FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_ALMERIA.mp3"},
    {name = "LOCA FM House", url = "http://s02.fjperezdj.com:8026/live"},
    {name = "SER", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3"},
    {name = "SER Catalunya", url = "https://25553.live.streamtheworld.com/SER_CATAAC.aac"},
    {name = "Calimbre Radio", url = "https://control.streaming-pro.com:6048/stream"},
    {name = "Jazz Radio Spain", url = "https://stream.tunerplay.com/radio/8020/jazzradiospain.mp3"},
    {name = "Decada FM 1001", url = "http://streaming5.elitecomunicacion.es:8230/;"},
    {name = "RNE Andalucía", url = "https://f141.rndfnk.com/star/crtve/rne5/gra/mp3/128/stream.mp3?cid=01GEPXW032X3Y2SXM6M4X4F1X4&sid=2ar1MBXpFkcnL6WuaxAXO1hEITa&token=L_nTm1RjUems0IjZMMQ_ZzFu3XQ_1_faFzfSM3OR5t8&tvf=06JeYFmsqRdmMTQxLnJuZGZuay5jb20"},
    {name = "Radio90 FM Valencia", url = "https://stream.radio90.fm:2002/web"},
    {name = "Mediterrani FM Barcelona", url = "https://listen1.myradio24.com/37511"},
    {name = "Free FM 80S", url = "https://freefm80.radioca.st/"},
    {name = "TRECE", url = "https://live-edge-ams-1.cdn.enetres.net/091DB7AFBD77442B9BA2F141DCC182F5021/liveld/index.m3u8"},
    {name = "Jamm FM Radio Costa Del Sol", url = "http://stream.jammfmradio.com/proxy/stream256.php"},
    {name = "Ushuaia Radio English", url = "https://s4.radio.co/sc6f29e098/low"},
    {name = "Cadena SER Granada", url = "https://25603.live.streamtheworld.com/SER_ASO_GRANADAAAC.aac?csegid=10000&ppid=ZWNpZDE5ODkwNjYxMzI4OTgwNDk3MjY2NDgyNjE2NzA2MTIyMTcyMjM0dXN1bmlkMTk4OTA2NjEzMjg5ODA0OTcyNjY0ODI2MTY3MDYxMjIxNzIyMzQ%3D&gam-paln=AQzzBGQEPSQcV-sSaAqXINZhOHRQZj5mfm7ceb7mFWj8KBmaOvlU-zV7FQbiIyALuiknv7qGvICjn60mtxA3sZs96aXzaoGqzBkqV9WxqsT0y4ZsmWe4jbZR4ViTV0kquCkK9G5V73xMGn9pymm5WWsTFzD0lqZBayiPetnX6RpBri2T6KvMymt_l-XKdOM2dUcrAg-aAn0mYkXaJx7momqJXWRWj973AGeQBiJgCPScdXpz6rAE1rf4UioAbZ-6FbQXEi4Z2Mbz0XplNS2LNQt8Ux9XJwP5jG85FWd_6Wfo2tiV8SoJzWX9onB5ni-rmGFw-zjHXUyQ_3evrngMEMtg_gp6iD-YxnjfITBfCFgDA89jUZVpXHkcZJGRmnIycb3Lnc4aP7SpamBtztDMnJjnpN5rMbpGdnu4cvVV7eqe08qr02onJVxdzKQMW-PW9kU8Viti_4vbptipGGBIGFGdL4CPUqsTkgNsc4kX229UjrHcCLiXublokOJCs3SL8bqyu_lUbX-Fg_vfDsSJ0-tkuA8rPkNBHq1hUvVFGMb0F1ehxpbWe7jFdvjRFk8ds0GSJxExGjt8KcKp3NtiPQLhKEiiFictYvTy-bN5HN7pLvSfYNJQYW6wjcHBLbJ7gbTDiHcFwP1Mmmj2ZM0w8wxINNLT4FK8P1XRRFual6Lw-4ecEJBBeB2sk35SQ2yg0TpsCqllblg0P5c8tbln5oRCoP_k0wkS_r4v3mEt8Vfip5HAOOpR_rbGKAVmvps9cxCjviWqEI0E-5KMg7n5pC17EvKDLtsVsv2Ywynh0xvcpuBUBsLR6naqRH2ZgIxiUGH4As8TTSSpIqrVaCtmoaSuQ8a7NZr_a8C8Zyx7hkd0Mwd91KToatSKWiymXhzhFP6fzwBgwVKk-yX3ro3VW3QQ3K4QytQVu2-3ysKi8chRkXFlIKvUbrgtBvYMt94E2T-9oAOplbh-Bz_A9Z59ggpXkh5YfBlms85Jf6mkdkDkAlO8HMGEA-lOQF3Qqr0b4yGDZDWrQJgLQfZIIKmlTg..&gdpr=1&gdpr_consent=CP5WeUAP5WeUAAHABBENAlEsAP_gAAAAAAAAg1NX_H__bX9r8Xr36ft0eY1f99j77uQxBhfJk-4FzLvW_JwX32EzNA26tqYKmRIEu3ZBIQFlHJHUTVigaogVrzHsYkGchTNKJ6BkiFMRc2dYCF5vmYtj-QKY5_p_d3f52T-9_dv83dzzz81nv3f5f-e1cLCdQ58tDfv_bRKb-5IP9_78v4v09t_rk2_eTVn_tevr7B-uft-7_XV-9_ffeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAxKADAAEQaikAGAAIg1DoAMAARBqIQAYAAiDUEgAwABEGotABgACINQAAA.f_wAAAAAAAAA&dist=cadenaser-web-tod-permanente&tdsdk=js-2.9&swm=true&pname=TDSdk&pversion=2.9&banners=300x250&burst-time=15&sbmid=e1c41bef-e974-48de-d579-9cd876d4dff8"},
    {name = "Canarias Radio", url = "https://rtvc-radio.flumotion.com/rtvc-radio/radio1-high.mp3"},
    {name = "DMT-FM Psytrance - EU Server", url = "https://eu2-centova.serverse.com/proxy/ywycfrxn/stream"},
    {name = "Radio Europa", url = "https://server9.emitironline.com:19144/"},
    {name = "Radio 1 Hits 90S", url = "http://c4.auracast.net:8050/stream"},
    {name = "Madrid Fm", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "Radio 90 FM", url = "http://stream.radio90.fm:2000/stream"},
    {name = "La Fresca FM", url = "http://stream.produccionesdale.com:8899/moviles"},
    {name = "Aegean Lounge Radio", url = "http://ns352055.ip-91-121-78.eu:8469/;"},
    {name = "Naiz: Irratia", url = "https://zuzenean.naiz.eus/naiz_irratia.mp3"},
    {name = "Dabclassic", url = "https://studio.dabclassic.com/hls/dabclassic/live.m3u8"},
    {name = "Radio Topo", url = "https://radiobot.radioslibres.info/radio/8060/radio.mp3"},
    {name = "CUAC FM", url = "https://streaming.cuacfm.org/cuacfm.ogg"},
    {name = "Megastar FM", url = "https://megastar-cope-rrcast.flumotion.com/cope/megastar.mp3"},
    {name = "BN Mallorca", url = "http://91.121.156.27:8008/stream"},
    {name = "Gladys Palmera Coleccion", url = "http://streams.radio.co/s496c4d2e8/listen"},
    {name = "Move Ibiza Radio", url = "https://s5.myradiostream.com:42007/moveibiza"},
    {name = "Holiday Gym FM", url = "http://holidaygym.emitironline.com/"},
    {name = "Radio 90 FM Valencia", url = "http://stream.radio90.fm:2000/ios"},
    {name = "7TV CADIZ", url = "https://streaming004.gestec-video.com/hls/7TVCADIZ.m3u8"},
    {name = "Playfm", url = "http://radioplaneta.emitironline.com:8000/"},
    {name = "Ondamar80", url = "https://antares.dribbcast.com/proxy/ondamar80?mp=/live"},
    {name = "Dynamis Radio 875 FM Madrid", url = "https://control.streaming-pro.com:8014/stream"},
    {name = "Esradio Galicia", url = "https://libertaddigital-radio-live2.flumotion.com/libertaddigital/ld-live2-low.mp3"},
    {name = "LOCA FM Trance", url = "http://s02.fjperezdj.com:8055/live"},
    {name = "SER Gijón", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_GIJON.mp3"},
    {name = "Onda Cero Cádiz", url = "https://atres-live.ondacero.es/live/delegaciones/oc/cadiz/master.m3u8"},
    {name = "Onda Vasca", url = "http://www.ondavasca.com:8000/bizkaia"},
    {name = "SER Murcia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MURCIA"},
    {name = "Etzanda Irratia", url = "http://51.68.46.71:9000/eztanda.mp3"},
    {name = "Cadena Ser + Valencia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_VALENCIA.mp3"},
    {name = "Locafm 90'S", url = "https://s2.we4stream.com/listen/loca_90s_/live"},
    {name = "Scannerfm", url = "https://eu10.fastcast4u.com/scannerfm"},
    {name = "Dance Wave Retro", url = "https://retro.dancewave.online/retrodance.flac.ogg"},
    {name = "Cadena Cope - Más Castellon", url = "https://wecast15-h-cloud.flumotion.com/copesedes/castellon-mas.mp3"},
    {name = "Esradio Granada", url = "https://azura.abcorp.es/listen/esradio_granada/radio.mp3"},
    {name = "Radio Galega Música", url = "https://crtvg-radiogalega-musica-hls.flumotion.cloud/playlist.m3u8"},
    {name = "Cadena Ser Radio Galicia", url = "http://playerservices.streamtheworld.com/m3u/SER_GALICIA.m3u"},
    {name = "Radio Nature", url = "https://stream.zeno.fm/3ac97ysh6f0uv.aac"},
    {name = "Radio Linguas", url = "https://radiolinguas.eu:8001/radiolinguas"},
    {name = "Ahora Radio 886", url = "https://streaming.enacast.com:30293/ahoraradiogelvesHD.mp3"},
    {name = "Radio Círculo", url = "https://play.cdn.enetres.net/863690D2607511E098B669C2DFD72085028/02984/playlist.m3u8"},
    {name = "Radio Intercontinental - Madrid", url = "https://cast5.servcast.net/proxy/inter/stream"},
    {name = "Energía Vintage", url = "https://axarquia.emisiononline.es/radio/8000/radio.mp3"},
    {name = "Lola FM 80`S", url = "https://digitalcreative.es:9000/lolafm_80s"},
    {name = "Free FM Classical", url = "https://stream.zeno.fm/x5jlpogsaedvv"},
    {name = "Mad Radio Barcelona", url = "https://c2.radioboss.fm/stream/588"},
    {name = "EITB Euskal Kantak", url = "http://multimedia.eitb.eus/live-content/eitbeuskalkantak-hls/master.m3u8"},
    {name = "Esradio Sevilla", url = "https://libertaddigital-radio-live3.flumotion.com/libertaddigital/ld-live3-low.aac"},
    {name = "Onda Musical De Yecla", url = "https://stream.zeno.fm/89t31p4mdwzuv"},
    {name = "Ràdio Vilablareix", url = "https://enacast.com/radiovilablareix/streams/SD"},
    {name = "Cadena SER Palencia", url = "https://27823.live.streamtheworld.com/SER_PALENCIA.mp3"},
    {name = "Hits 1", url = "https://ecmanager3.pro-fhi.net:2680/stream"},
    {name = "JTM Radio Funky", url = "https://stream.zeno.fm/yteunchcxg0uv?aw_0_req_lsid=1699392045084_0.39890697330234526&acu-uid=849521821170&an-uid=0&mm-uid=f609654a-a7a1-4f00-9835-b8bab3e3e931&dot-uid=09c520050094789e6905bb3b&triton-uid=cookie%3A5299e43e-60ef-4843-9a9e-7d574eecce4a&amb-uid=2800325040644623638"},
    {name = "Radio Ateos De Barcelona", url = "https://servidor25.brlogic.com:7054/live"},
    {name = "Pepe Radio", url = "http://server10.emitironline.com:8032/"},
    {name = "RADIOLE España", url = "https://20043.live.streamtheworld.com/RADIOLE.mp3"},
    {name = "Costa Blanca FM", url = "https://costablancafm.stream:18106/"},
    {name = "Radio Betis", url = "https://wecast-b01-04.flumotion.com/betistv/radio1.mp3"},
    {name = "999 Plaza Radio Valencia", url = "https://stream1.solstreaming.com:8112/stream"},
    {name = "Dunas FM 944 Y 942", url = "https://sonic.mediatelekom.net/8424/stream/;"},
    {name = "DMT-FM - EU Server 320K", url = "https://dc1.serverse.com/proxy/ywycfrxn/live"},
    {name = "A Xente De Teo", url = "https://axentedeteo.ddns.net/radio/8000/radio.mp3"},
    {name = "Cadena SER Radio Menorca", url = "http://server10.emitironline.com:8040/"},
    {name = "FIESTA FM LEVANTE - ALICANTE 88,4 ELCHE 952", url = "http://cdn4.onstream.audio:9181/stream"},
    {name = "Fiesta FM 876", url = "https://radio.fiestamallorca.com/fiesta?1724972882139"},
    {name = "Esradio Madrid", url = "http://livestreaming3.esradio.fm/stream64.mp3"},
    {name = "Radio Esport Valencia", url = "https://streaming.radioesport914.com:58000/stream"},
    {name = "Radio Humor FM", url = "https://stream.radiohumorfm.com/stream"},
    {name = "Carrusel FM", url = "http://server6.20comunicacion.com:8921/;"},
    {name = "Blue Radio FM 902", url = "http://one.cloudstreaming.eu:9053/;"},
    {name = "Cadena SER Coruña", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_CORUNA.mp3"},
    {name = "Hit Radio", url = "http://stm1.emiteonline.com:8004/hitelgrado"},
    {name = "RNE Radio Nacional Almería", url = "https://dispatcher.rndfnk.com/crtve/rne1/alm/mp3/high"},
    {name = "Perfect Softrock", url = "http://www.surfmusic.de/m3u/perfect-softrock,21777.m3u"},
    {name = "Radio Planeta", url = "http://radioplaneta.emitironline.com/radio"},
    {name = "RNE Radio Clásica Almería", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r2_main.m3u8"},
    {name = "COPE Santander", url = "http://santander.copesedes.stream.flumotion.com/copesedes/santander.mp3.m3u"},
    {name = "Remember VIP Radio", url = "http://node-19.zeno.fm/471az1pu2nhvv?rj-ttl=5&aw_0_req_lsid=47ff91dffd57dbf75dd0fb53d70887a6&acu-uid=592123274268&bsw-uid=821f026b-0bba-437a-8608-4175e0f8681a&amb-uid=4433801850266558616&rj-tok=AAABgvsOIBIA01PqCt44uBvX-A&aw-uid=7d8ef8fede4e9d48810209d9211a4b12&dyn-uid=&dbm-uid=CAESEE2_JyH-nO_DIddQW1whFfI&mm-uid=ef936263-16b7-4900-8f84-e3367baa5653&triton-uid=cookie%3Ae618ff5c-77ba-49f3-ac6e-b9c6b093d00f&zs=l4i70_8iS4m6nNOBdKq6LA&an-uid=4758170041402249417"},
    {name = "Hispahits", url = "https://st4.laurban.eu:8443/hispahits"},
    {name = "Mariskal Rock", url = "https://media.profesionalhosting.com:8047/stream"},
    {name = "Radio Sant Boi", url = "https://streaming.enacast.com/radiosantboi128.mp3"},
    {name = "La Urban Radio", url = "https://st1.urbanrevolution.es:8443/zonaelectronica"},
    {name = "Radio Jabato", url = "http://giss.tv:8000/radiojabato.mp3"},
    {name = "SER - Radio Zaragoza", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ZARAGOZA.mp3"},
    {name = "Radio La Granja", url = "https://radiobot.radioslibres.info/listen/radio_la_granja/rlg.mp3"},
    {name = "Radio Todo Exitos", url = "http://cervera.eldialdigital.com:7999/autodj"},
    {name = "Cadena SER - Radio Zamora", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_ZAMORA.mp3"},
    {name = "Radio 5 RNE Córdoba", url = "https://f141.rndfnk.com/star/crtve/rne5/cor/aac/128/stream.aac?cid=01GEPXCEBXZ55V5Q46BA5MKGQJ&sid=2Ijj8gOaUIfAlXbKakMiT1ah6Uk&token=EltrTn6HzLi0eEmfDXHoz0vVYnz6083DqWp5D3DcZfo&tvf=hjpV5gOaLxdmMTQxLnJuZGZuay5jb20"},
    {name = "Cantabria FM 899", url = "http://stream.zeno.fm/jndgdm0esn9vv"},
    {name = "Hitz Funky Radio", url = "https://stream.zeno.fm/azgx0ktf4p8uv"},
    {name = "Chilli FM Costa Del Sol", url = "https://playoutonestreaming.com/proxy/chilli?mp=/mp3"},
    {name = "Onda Cero Barcelona", url = "https://atres-live.ondacero.es/live/delegaciones/oc/barcelona/bitrate_1.m3u8"},
    {name = "SER Asturias", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_ASTURIAS.mp3"},
    {name = "LOCA FM 80S", url = "http://s02.fjperezdj.com:8075/live"},
    {name = "Radio Radio Network", url = "http://radioradio.es:8000/listen.pls"},
    {name = "Cadena Ser Guadix", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_GUADIXAAC_SC"},
    {name = "Radio Carcoma", url = "https://live.radiocarcoma.com/main"},
    {name = "Holland FM Gran Canaria", url = "https://panel.amediastream.eu:8500/live#.mp3"},
    {name = "Cadena Ser + Bilbao", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_BILBAO.mp3"},
    {name = "Cadena Ser + Granada", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_MAS_GRANADA.mp3"},
    {name = "Mix Radio Gran Canaria", url = "https://mixfm.radionetz.de/mixfm.mp3"},
    {name = "Cadena Ser + Madrid", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_MADRID.mp3"},
    {name = "S+ Ibiza", url = "https://ice.studiopiu.net/studiopiuibiza.aac"},
    {name = "Cadena Ser + Alicante", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_ALICANTE.mp3"},
    {name = "Tenerife Sur Adeje", url = "https://streaming.enacast.com/radiosuradeje128.mp3"},
    {name = "Radio Atlantis Lanzarote", url = "https://atlantisfm.radionetz.de/atlantisfm.mp3"},
    {name = "La Mega Estación", url = "https://eu1.lhdserver.es:9049/stream?1630947253320"},
    {name = "La Nueva 879 FM 879 FM Madrid", url = "https://statics-v2.streema.com/static/audios/sample.ea78c3d52389.mp3"},
    {name = "Cadena SER - Radio Vigo", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_VIGO.mp3"},
    {name = "ENERGIA FM - CARAVACA DE LA CRUZ 900", url = "http://streaming5.elitecomunicacion.es:8128/caravaca?type=.mp3"},
    {name = "Escuela Abierta FM 1075", url = "http://streaming.elitecomunicacion.es:8042/;"},
    {name = "Eixample Barcelona Radio", url = "https://directe.eixamplebarcelonaradio.com:8443/radioOnline"},
    {name = "AFN 360 Rota", url = "http://playerservices.streamtheworld.com/m3u/AFNE_RTA.m3u"},
    {name = "Radio Barça", url = "https://open.http.mp.streamamg.com/p/3000707/sp/300070700/playManifest/entryId/0_dej0sx5j/format/applehttp/protocol/https/uiConfId/30024000/a.m3u8"},
    {name = "Radio Picariña", url = "https://xabarin.gal/videos/83165"},
    {name = "Hits 1 San Sebàstian", url = "https://player.hd.hits1radio.com/"},
    {name = "Litoral FM Online", url = "https://stream.mediasector.es/radio/8310/litoralfm.mp3"},
    {name = "Radio Vila-Real", url = "http://www.radiovila-real.es/player/?pl=vlc&c=Radio%20VIla-real%2092.2%20Fm"},
    {name = "Arraio Irratia", url = "http://irratia.arraio.eus:9001/irratia.ogg"},
    {name = "FIESTA El Vigia 1011 FM", url = "https://acp2.lorini.net:28058/stream"},
    {name = "Fiebre Latina Radio 966 FM", url = "https://eu1.lhdserver.es:9035/stream"},
    {name = "Agora Sol Radio", url = "https://cervera.eldialdigital.com:23141/stream"},
    {name = "90 FM 952", url = "http://185.23.192.118:8010/;"},
    {name = "Radio Líder", url = "http://server9.emitironline.com:8200/stream"},
    {name = "Cadena SER Extremadura", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_EXTREMADURAAAC.aac"},
    {name = "Playtrance Radio - Main Channel", url = "https://live-ff.playtrance.com/playtrance-main.mp3"},
    {name = "Only Romantic Radio", url = "https://stream.laut.fm/only-romantic-radio"},
    {name = "Onda Cero Cinca", url = "https://sonando-us.digitalproserver.com/litera.aac"},
    {name = "SER --> Henares20240109", url = "https://27743.live.streamtheworld.com/SER_HENARES.mp3?csegid=10000&ppid=ZWNpZDUzNzE0NzUzOTExMzgzMTkxNzIxNzU4NDUzNDY5NDM0Mjk5MTk1dXN1bmlkNTM3MTQ3NTM5MTEzODMxOTE3MjE3NTg0NTM0Njk0MzQyOTkxOTU%3D&gam-paln=AQzzBGQEtRmO1MeP4fDls1BY5T97Pc1eriGu9WoY-v2LQmGZVOkJYh4f9lm60n-TCRHd1vvhQ0Pk5E9BXaY0QDDRRsGxmLamtsxZ4L0CC2qZNGOVHh4CdzubJyLx8GY_2WBRDkAajKFHmtSeCoSj9UZP7WXyJ43IHeHfCWHU-uKqkiU9N77W6AIqczhcXr16zT9cNOXLL-d8gijX-Lk-_Bk3Lwd0cXnmUx3oGgIy9AlJXF8rcyD6Gh4I39MxTY0MLbRjwYHsbFNJN3a2pVCABzaTPmIRMQndsLpcpnFa080z_-mLSy5AtdrbG5YxSl6PB_4ilvFXx5r23Pa7XLZTOTcWxqSv2AxtsvcwIHG5CtIKR3TTi2EFdKS7k8rJFy-c4VM0LLZ9yBLwSVLqpGadJiIxHI5V8Ca9xRGkTJUWwkNpHM8cID7ZXSaoXYShnEqsHV2F5T9xLP9YIUeCzVf6gkhb4V348TJw_TRKokTWg1BtaS9pfo87L046xVJNfFRI6vm5rAQ0b5k9C3UUif4lsahzWWriA-YiZg3Wr1k0vaBFlpDFQCAbkI-KVpYs1SKtm2xOD175X1m2I5PixCY5WvKVmx1opJixZv44NudPKXETrCUksxiZRfMavs3AL5Ecj_m2EW6KFwXBcWjJrcBQUzt71QN_93vlnMTTgaH5y0IjDFfbVwtnECLHsUg4LKE_Vf5UC-fdq3x2L3G7uZgtG8LqXRVH7Rz2mj_loE-EhQeVuBVEkgsLXBEBQIAXolckHBabVOMzcketK0Rc3vMWe8hWLMfalFrXFRzrloshW5XF6Ipz26X1dWT4ik8KUYDLkKJcrkYVBAWS9vHD0cZ5iqzWi-hge45cpqtQIHYy06Or3YnJXh-BsqdsofQAVDu_ff9wdjF8YLED02wWlaQO6WZqMZWy4WSfeb3QnwToL6E3fIcKThilF3kp8S5Q8rpQNjxEXnV6tyA5tzGqfBByzM63Uo8s7OaFerVuQKjfvPxlVKm4ueRqi5wgauGu0lM6nqohH-As3dN7SO1pcIrKhX-kg9lJj5_VBgJX391TL6axaWbcjSUaOFl2xv3N6DuF0ANomhDKJfsAqqVXWx-i0PPO-k1593o78M-T1zbey9sPDCKQErasr1wxuDQuUFfxltEP0JK2zSJeGUwTqTuirbnqtYsonuam2SuBhGugWWvvSvbPGdeuXid5AHossfNikQWqTrDiwntNyZbruEYxC3hY8x5X3Rl9Cio-qO2K3TOpn2QqyzQBefWjgyDg-lMnl29ZI-jFPvnFEgdJRt2v9H1ibfL7Himg-sNoDMQhPSFG2mdackyn7-1WtbfQtHKVrVhWfD0IUJh5A243T9xmmBs_BJQ2MQBAjm4qJ-YbdFNKkUygzWTKt5PT-viFPg..&gdpr=1&gdpr_consent=CP4HX0AP4HX0AAHABBENAiEsAP_gAAAAAAAAg1NX_H__bX9r8Xr36ft0eY1f99j77uQxBhfJk-4FzLvW_JwX32EzNA26tqYKmRIEu3ZBIQFlHJHURVigaogVrzHsYkGchTNKJ6BkgFMRc2dYCF5vmYtj-QKY5_p_d3f52T-9_dv83dzzz81nv3f5f-clcLCdQ58tDfn_bRKb-5IO9_78v4v09t_rk2_eTVn_tevr7B-uft-7_XV-9_ffcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAxKADAAEQaikAGAAIg1DoAMAARBqIQAYAAiDUEgAwABEGotABgACINQAAA.f_wAAAAAAAAA&dist=cadenaser-web-tod-permanente&tdsdk=js-2.9&swm=false&pname=TDSdk&pversion=2.9&banners=none&burst-time=15&sbmid=dedeb80d-8058-4aee-bf46-f2d1a0b123d4"},
    {name = "Icat FM", url = "https://shoutcast.ccma.cat/ccma/icatHD.mp3"},
    {name = "PRA RADIO By Xopo", url = "http://154.58.11.34:8001/;?"},
    {name = "Onda Cero Gijón", url = "https://atres-live.ondacero.es/live/delegaciones/oc/gijon/bitrate_1.m3u8"},
    {name = "Formula 30", url = "http://stm1.emiteonline.com:8001/formula30"},
    {name = "Los 40 Sur", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_ASO_MORON.mp3"},
    {name = "Cope Barcelona", url = "https://wecast-b02-06.flumotion.com/copesedes/barcelona.mp3"},
    {name = "EITB Irratia", url = "http://mp3-eitb.stream.flumotion.com/eitb/eitbmusika.mp3"},
    {name = "Ràdio 90 320K", url = "https://giss.tv:666/r90.mp3"},
    {name = "Bilbo Hiria Irratia", url = "https://server8.emitironline.com:18392/stream"},
    {name = "Esencia FM", url = "https://stream.mediasector.es/radio/8040/esenciafm.mp3"},
    {name = "Canal Ebro Radio", url = "http://streaming.capsulaimposible.com:8000/stream/2/canalebro.mp3"},
    {name = "Rock FM Espana Hi-Res", url = "https://rockfm-cope.flumotion.com/chunks.m3u8"},
    {name = "Lounge Radio Ibiza", url = "https://stream.laut.fm/lounge-radio-ibiza"},
    {name = "LOCA FM DANCE", url = "http://s02.fjperezdj.com:8025/live"},
    {name = "Radio Marca Lanzarote", url = "https://5c0956165db0b.streamlock.net/radio/marca.stream_aac/playlist.m3u8"},
    {name = "Relax FM", url = "https://sg.centrocibernetico.com/relaxfm"},
    {name = "Contrabanda FM", url = "http://www.contrabanda.org:8000/contrabanda"},
    {name = "Onda Cero Pontevedra", url = "https://atres-live.ondacero.es/live/delegaciones/oc/pontevedra/master.m3u8"},
    {name = "Colsub-Lounge", url = "http://stream.exeamedia.com:5086/Colsub-lounge"},
    {name = "Artefm VIVATV", url = "http://stream1.gomezdearanda.com:8000/stream"},
    {name = "Candela Radio 914 FM", url = "https://radio.streamenginelogin.com:8002/stream"},
    {name = "Ibiza Organica", url = "https://playoutonestreaming.com/proxy/organica?mp=/stream"},
    {name = "Bohemia FM 931", url = "http://5.135.183.124:8042/stream"},
    {name = "La Urban TV", url = "https://urbanrevolution.es:8443/live/TV/playlist.m3u8"},
    {name = "Radio Filispim", url = "https://streaming.cuacfm.org/filispim.mp3"},
    {name = "Mi Amigo Radio, De Échte", url = "https://stan319bisbis.radioca.st/stream"},
    {name = "Hits1", url = "https://radio12.pro-fhi.net:19018/currentsong?sid=1&_=1713601834734"},
    {name = "Radiovoz Pontevedra", url = "http://live.radiovoz.es/mp3/stream_vigo.mp3"},
    {name = "Canal SUR Almería Radio", url = "https://cdnlive.codev8.net/rtvalive/smil:channel8.smil/playlist.m3u8"},
    {name = "Radiovoz Lugo", url = "http://live.radiovoz.es/mp3/stream_lugo.mp3"},
    {name = "Eco Leganes", url = "https://cervera.eldialdigital.com:25191/stream"},
    {name = "Ruben'S Mixes", url = "https://ia600202.us.archive.org/16/items/DeepFunkyHouse21014022014/DeepFunkyHouse21014022014_vbr.m3u"},
    {name = "Radio Verbum Dei", url = "https://s01.digitalserver.org/cp/links.php?p=8006&m=pls"},
    {name = "Cadena Azul Lorca 1078 FM", url = "https://stream.zeno.fm/sxma7nk6azzuv"},
    {name = "Radio Enlace", url = "https://cervera.eldialdigital.com:25121/stream"},
    {name = "AB95FM", url = "https://stream-157.zeno.fm/dwqgk9dxs98uv"},
    {name = "Imusica Rock", url = "https://stream.zeno.fm/4wu2dwa6krruv"},
    {name = "Perfect Italian Hits", url = "https://n02.radiojar.com/9fdycttep7uvv?1709395524=&rj-tok=AAABjf_zWwMApNXs9BnZjBKlwQ&rj-ttl=5"},
    {name = "SER - Radio Pamplona", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_PAMPLONA.mp3"},
    {name = "Radio Marca Tenerife", url = "https://cervera.eldialdigital.com:22131/stream"},
    {name = "La Cuarta FM", url = "http://radio.amgroupmkt.com:1050/stream"},
    {name = "MDT Radio", url = "http://streams1.mdtradio.com:8020/mdtweb"},
    {name = "Radio Oro Marbella", url = "http://185.23.192.118:8004/;stream.mp3"},
    {name = "Bayradio Spain", url = "https://securestreams2.autopo.st:1317/stream?1715088808599"},
    {name = "Ushuaia Radio 877 FM Madrid", url = "https://s4.radio.co/sc6f29e098/listen"},
    {name = "C DIAL Esencial", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL_01.mp3"},
    {name = "Radios Libres", url = "https://radiobot.radioslibres.info/listen/radio_cadenazo_libre/cadenazo.mp3"},
    {name = "Sonica Tribe", url = "https://ibizasonica.streaming-pro.com:8010/sonicatribe"},
    {name = "Cadena Ser + Las Palmas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_LAS_PALMAS.mp3"},
    {name = "Cadena Ser + Cadiz", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_CADIZ.mp3"},
    {name = "Disney Ice", url = "https://ar.radiodisney.com/"},
    {name = "Free FM", url = "https://rocafmadrid.radioca.st/"},
    {name = "Jazz Radio Bcn", url = "http://stream.zeno.fm/u40kkya8hg8uv"},
    {name = "COPE Gijón", url = "https://gijon-copesedes-stream.flumotion.com/copesedes/gijon.mp3.m3u"},
    {name = "Onda Latina", url = "https://cervera.eldialdigital.com:21131/stream"},
    {name = "Radio MARCA Asturias", url = "https://streaming.enacast.com/radiomarcaasturiasHD.mp3"},
    {name = "Cadena Ser + Santander", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_SANTANDER.mp3"},
    {name = "Play Trance Radio Main Channel High Quality", url = "https://streaming.playtrance.com/playtrance-main-high"},
    {name = "Play Trance Radio Uplifting Only Channel High Quality", url = "https://streaming.playtrance.com/playtrance-uplifting-high"},
    {name = "Makina Fm 1067", url = "https://stream-155.zeno.fm/roqewn7dp4gtv?zs=pHT3yBVRSCuhAS6RsOSNiQ"},
    {name = "Cadena Ser + Pontevedra", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_MAS_PONTEVEDRA.mp3"},
    {name = "Radio Nostalgia Spain", url = "http://streamingv2.shoutcast.com/nostalgiaspain"},
    {name = "Gente Radio", url = "https://pr1cen101.emisionlocal.com/proxy/genteradio?mp=/live"},
    {name = "Cristianos - Christen Auf Spanisch", url = "http://stream.laut.fm/cristianos.pls"},
    {name = "LA POPU RADIO", url = "https://ams1.acelerun.com:8010/radio.mp3"},
    {name = "Roquetas Fm Radio 965", url = "https://stream20.usastreams.com/8224/stream/;"},
    {name = "Costa FM", url = "https://grupocostafm.es/listen/costafm/1"},
    {name = "DISCO MUSIC RADIO", url = "https://discomusicradio.com:8100/;"},
    {name = "Adagioradio", url = "https://stream.tunerplay.com/radio/8010/adagioradio.mp3"},
    {name = "Radio Salut Catalunya", url = "https://51.38.57.199:9001/stream"},
    {name = "Cadena Cope - Más Pamplona", url = "https://wecast09-h-cloud.flumotion.com/copesedes/pamplona-mas.mp3"},
    {name = "Cadena Cope - Más Sevilla", url = "https://wecast-b03-04.flumotion.com/copesedes/sevilla-mas.mp3"},
    {name = "Radio Del Hogar De La Brisa", url = "http://stream.zeno.fm/4vwgvyq82k8uv"},
    {name = "Onda Regional Música", url = "https://crmlive.redctnet.es/liveedge/orm/ormmusical/chunklist_w835504041.m3u8"},
    {name = "Ona Cat Ràdio", url = "https://server8.emitironline.com:10824/"},
    {name = "Cadena Cope - Más Zaragoza", url = "https://wecast07-h-cloud.flumotion.com/copesedes/zaragoza-mas.mp3"},
    {name = "Flux Radio", url = "https://pr1cen101.emisionlocal.com/proxy/fluxradio?mp=/stream"},
    {name = "COPE Cartagena", url = "http://cartagena.copesedes.stream.flumotion.com/copesedes/cartagena.mp3.m3u"},
    {name = "RNE Murcia", url = "https://d121.rndfnk.com/star/crtve/rne1/mur/mp3/128/stream.mp3?cid=01GEP3ZKY6YSV20P6RMNTKNDD6&sid=2ar2W2AJRHCleglLtfnn6nLklsU&token=25qdZ9PRjFVlFZkLiFrLLCHGs5cDbRXkhlVCjXwNN8Q&tvf=kGi_U96sqRdkMTIxLnJuZGZuay5jb20"},
    {name = "El Salto Radio", url = "https://radio.radiobot.org/listen/salto/elsaltoradio.mp3"},
    {name = "Canal Sur Radio Granada", url = "https://cdnlive.codev8.net/rtvalive/smil:channel4.smil/chunklist_b250000.m3u8"},
    {name = "Spectrum FM Costa Almeria", url = "https://eu8.fastcast4u.com/proxy/almeria2?mp=/1"},
    {name = "Agro Radio 1030", url = "https://sonicpanel.streamsolutions.us/8038/stream"},
    {name = "Canal Sur Radio Música", url = "https://cdnlive.codev8.net/rtvalive/smil:channel10.smil/chunklist_b250000.m3u8"},
    {name = "24FM Axarquía 1039", url = "https://axarquia.emisiononline.es:8030/radio.mp3"},
    {name = "Es Mi Radio", url = "http://streaming.elitecomunicacion.es:8038/live"},
    {name = "Euskalerria Irratia", url = "http://server4.beatproducciones.com:8014/"},
    {name = "Águilas Radio FM 914", url = "http://streaming2.elitecomunicacion.es:8032/stream?type=.mp3"},
    {name = "Onda Sevilla Radio", url = "https://streaming2.elitecomunicacion.es:8630/stream?type=.mp3"},
    {name = "Doble V Radio 1079 FM", url = "https://stream.zeno.fm/x7wm4rrv5yzuv"},
    {name = "La Villa Fm", url = "https://sonic.mediatelekom.net:10907/stream"},
    {name = "Radio Carrizal", url = "http://streaming.enantena.com:8000/radiocarrizal128.mp3"},
    {name = "Aire Latino 885 FM", url = "https://server2.ejeserver.com:8810/stream"},
    {name = "999 Valencia Radio", url = "http://stream1.solstreaming.com:8010/stream"},
    {name = "Fiesta 891 FM", url = "https://acp2.lorini.net:36050/stream"},
    {name = "Onda 80 Radio Bellvitge", url = "https://antares.dribbcast.com/proxy/onda80/stream"},
    {name = "Radio Marca Cordoba", url = "http://str2.mediatelekom.net:9316/;#.mp3%22%20type=%22audio/mp3"},
    {name = "Lola FM Dance", url = "https://digitalcreative.es:9000/lolafm_dance"},
    {name = "Radio Santvi 1074FM", url = "https://dhits.frilab.com:8443/santvi"},
    {name = "Makina Fm", url = "https://stream-157.zeno.fm/roqewn7dp4gtv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJyb3Fld243ZHA0Z3R2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsImp0aSI6IkI0SXZuWFRBU21LVWRvWUZqSGstcUEiLCJpYXQiOjE3MTU0NzA1NzUsImV4cCI6MTcxNTQ3MDYzNX0.1HVDh84CZBnlRWWluiPLbGWAXEHbpedQw55Kv8AZZYg&zttl=5"},
    {name = "Ràdio Nova", url = "http://radio.08-produccions.cat:8000/rvilanova.mp3"},
    {name = "La Mega", url = "https://stream.emisorasmusicales.net/listen/la_mega/lamega.mp3"},
    {name = "9 Radio 977 Las Palmas - 936 Norte - 879 Sureste - 977 Sur", url = "https://app.sonicpanelradio.com/8072/stream"},
    {name = "Eñe Radio", url = "https://stream.zeno.fm/am74zvzksv8uv"},
    {name = "Ràdio Alfacs", url = "https://radioalfacs.com/emissioogg"},
    {name = "Radio Espacio", url = "https://eu1.lhdserver.es:8037/stream"},
    {name = "CADENA SER Aviles", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_AVILES.mp3"},
    {name = "Dos FM Radio 977 1010", url = "https://control.streaming-pro.com:8008/stream"},
    {name = "Calafell Ràdio", url = "http://streaming.enantena.com:8000/calafellradio128.mp3?_=1"},
    {name = "Remember Vip Techno", url = "https://stream-153.zeno.fm/xilwjn4t17qvv"},
    {name = "COPE Avilés", url = "https://wecast19-h-cloud.flumotion.com/copesedes/aviles.mp3"},
    {name = "Ecuatoriana FM 884", url = "http://radioserver9.profesionalhosting.com:55332/;stream"},
    {name = "ALDAIA RADIOS", url = "https://relay.stream.enacast-cloud.com:40223/aldaiaradioHD.mp3"},
    {name = "BENICARLO RADIO By Xopo", url = "https://streaming.enacast.com/radiobenicarlo128.mp3"},
    {name = "Radio Almenara 106,7", url = "https://cervera.eldialdigital.com:25211/stream"},
    {name = "Ràdio Tàrrega", url = "https://enacast.com/radiotarrega/streams/HD"},
    {name = "L'OM PICASSENT RADIO By Xopo", url = "http://radiolom.es:8800/;&type=mp3"},
    {name = "Musicbox", url = "http://stm1.emiteonline.com:8025/musicbox"},
    {name = "Free FM Sports", url = "https://stream.zeno.fm/31nnibfpnxktv"},
    {name = "Oro", url = "http://185.23.192.118:8002/;"},
    {name = "VEU D'ONDARA RADIO By Xopo", url = "https://relay.stream.enacast-cloud.com:40235/laveudondaraSD.mp3"},
    {name = "Canal 2000 La Solana", url = "http://canal2000.berkano-systems.net/streaming/streams/canal2000-720p.m3u8"},
    {name = "RIBA-ROJA RADIO By Xopo", url = "https://streaming.enacast.com/radioribarroja128.mp3"},
    {name = "Jazler FM", url = "http://solid48.streamupsolutions.com:8091/stream"},
    {name = "Radio Santoña", url = "http://radio.xn--santoa-0wa.es:10212/radio.mp3"},
    {name = "TURIA RADIO By Xopo", url = "http://streaming.enacast.com:8000/radioturiaHD.mp3"},
    {name = "Radio Unión Catalunya", url = "http://srv0435.lcinternet.com:9522/stream"},
    {name = "A Rádio POP", url = "https://pop.jmvstream.com/stream"},
    {name = "IBI RADIO By Xopo", url = "https://streaming.enacast.com/radioibiSD.mp3"},
    {name = "Revive FM", url = "https://radio.revivefm.es/stream"},
    {name = "Ràdio Vic", url = "http://streaming.enantena.com:8000/radiovic56.mp3"},
    {name = "The Club", url = "https://relay.stream.enacast-cloud.com:30256/radioclubmovilHD.mp3"},
    {name = "Ràdio 4 RNE", url = "https://rtvelivestream.akamaized.net/rtvesec/rne/rne_r4_main.m3u8?idasset=1712438"},
    {name = "Radiocable", url = "https://radio.radiobot.org/listen/radiocable/radio.mp3"},
    {name = "Rock FM Es", url = "https://rockfm-cope-rrcast.flumotion.com/cope/rockfm-low.mp3"},
    {name = "Radio Marca Donostia", url = "https://marca-sansebastian.streaming-pro.com:6101/live"},
    {name = "Felove Biblia En Español", url = "http://radio.produccionescasaverde.com:8696/autodj"},
    {name = "Ocionews Plus", url = "https://stream.zeno.fm/vgv984uznfhvv"},
    {name = "Radio Vilafant", url = "https://sonic.mediatelekom.net/9986/stream"},
    {name = "Radio Sefarad", url = "https://www2.radiosefarad.com/joomla/images/mp3/sefaradparaweb.mp3"},
    {name = "FM Bierzo", url = "https://streaming12.elitecomunicacion.es:8648/stream?type=.mp3"},
    {name = "Bside", url = "https://flow.emisiononline.es/radio/8010/bside.aac"},
    {name = "FUNKY TRACKS RADIO", url = "https://streaming2.elitecomunicacion.es:8134/stream"},
    {name = "Ruben Tortosa", url = "https://archive.org/download/DeepFunkyHouse21014022014/DeepFunkyHouse21014022014_vbr.m3u"},
    {name = "Radio Hostafrancs", url = "https://radiohostafrancs.cat/directe.mp3"},
    {name = "RADIO LUZ CLASSIC DALIAS", url = "https://broadcast.radioponiente.org:8034/;listen.pls"},
    {name = "Radio Almendralejo", url = "http://srv0510.lcinternet.com:8004/stream"},
    {name = "Aragon TV Internacional", url = "https://cartv.streaming.aranova.es/hls/live/aragontv_canal1.m3u8"},
    {name = "Java Radio", url = "http://stream.radio90.fm:2000/javadj"},
    {name = "RNE 1 - Zaragoza", url = "https://dispatcher.rndfnk.com/crtve/rne5/zgz/mp3/high?idasset=3894741"},
    {name = "RNE - Radio 5 Huesca", url = "https://dispatcher.rndfnk.com/crtve/rne5/ter/mp3/high?idasset=6116428"},
    {name = "Radio Estrada", url = "https://srv7031.dns-lcinternet.com/8028/stream"},
    {name = "MEGA STAR FM", url = "https://megastar-cope.flumotion.com/playlist.m3u8"},
    {name = "SER Lucena", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_ASO_LUCENAAAC.aac"},
    {name = "Onda Cero Madrid Norte", url = "https://cast.direcnode.com/proxy/ondacero/stream"},
    {name = "Radio Valga", url = "http://99.198.118.250:8028/;"},
    {name = "Armonía Duero 1077 FM", url = "http://s5.myradiostream.com:42840/listen.mp3"},
    {name = "Feel Good Radio Costa Del Sol", url = "https://caster05.streampakket.com/proxy/8321/stream"},
    {name = "Ràdio L'Om", url = "http://radiolom.es:8800/;stream.mp3"},
    {name = "FM MUSICAL", url = "https://stream.zenolive.com/mpgqwn4h0wzuv.aac"},
    {name = "Fresh Radio", url = "http://stream.zenolive.com/gzaf75yevceuv.m3u"},
    {name = "Nostalgia", url = "https://azura.abcorp.es/listen/nostalgia/live"},
    {name = "Canal Metropol 1026 FM", url = "https://radioserver11.profesionalhosting.com/proxy/pkg78607?mp=/stream"},
    {name = "Ràdio Gràica", url = "http://streaming.enantena.com:8000/radiograciaSD.mp3"},
    {name = "Das Inselradio Malorca", url = "https://addrad.io/445fxk9"},
    {name = "Onda Cero Ourense", url = "https://atres-live.ondacero.es/live/delegaciones/oc/ourense/master.m3u8"},
    {name = "Cadena Ser + Gandia", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_ASO_GANDIA.mp3"},
    {name = "Radio 5 RNE Almería", url = "https://dispatcher.rndfnk.com/crtve/rne5/alm/mp3/high"},
    {name = "Inolvidable FM", url = "https://uk1.streamingpulse.com/ssl/inolvidablefm"},
    {name = "Cadena Ser + Elche", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_ASO_ELCHE.mp3"},
    {name = "Cadena Ser + La Coruña", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/SER_MAS_ASO_CORUNA.mp3"},
    {name = "Onda Cero Santiago De Compostela", url = "https://atres-live.ondacero.es/live/delegaciones/oc/santiago/master.m3u8"},
    {name = "Giralda FM", url = "https://server1.radiocast.es/listen/radio_giralda/giraldaweb"},
    {name = "Ona Mediterrània", url = "https://enacast.com/onamediterrania/streams/HD"},
    {name = "Aragón Radio", url = "https://cartv.streaming.aranova.es/hls/live/aragonradio_huesca.m3u8"},
    {name = "Radio Despi", url = "https://streaming12.elitecomunicacion.es:8228/stream?type=.mp3"},
    {name = "Fresh Radio Spain", url = "https://freshrad.radioca.st/stream"},
    {name = "Passion Ibiza Radio", url = "https://www.radioking.com/play/passion-ibiza-radio1/485588"},
    {name = "La Movida Latina", url = "https://server2.ejeserver.com:8400/stream"},
    {name = "Europa FM Marina Alta", url = "https://stm2.emiteonline.com:9029/marinaefm"},
    {name = "Activa FM - Marina Alta Sur", url = "https://stream.mediasector.es/radio/8000/activafm-marina-alta-sur.mp3"},
    {name = "Irati Irratia", url = "http://188.93.73.7:8102/stream"},
    {name = "Radio Disco Melodia FM", url = "https://sonic.mediatelekom.net/8020/stream"},
    {name = "Kiss FM España", url = "https://live.kissfm.ro/kissfm.aacp"},
    {name = "Ràdio Sabadell", url = "http://online.radiosabadell.fm:8013/stream"},
    {name = "Diez TV", url = "https://streaming.cloud.innovasur.es/mmj/index.m3u8"},
    {name = "Radio Morata", url = "https://cervera.eldialdigital.com:25141/stream"},
    {name = "Radio Xata", url = "https://radio.radiobot.org/listen/xata/radio.mp3"},
    {name = "Radio Espiritrompa", url = "https://radiobot.radioslibres.info/listen/radio_espiritrompa/radio.mp3"},
    {name = "Cadena Digital 978 FM", url = "http://185.23.192.118:8006/;"},
    {name = "Trendy FM", url = "https://broadcast.radioponiente.org:8038/index"},
    {name = "Mozoilo Irratia", url = "https://radioserver11.profesionalhosting.com/proxy/alettwge?mp=/stream"},
    {name = "Fresh Energy", url = "https://freshenergy.radioca.st/stream"},
    {name = "Radio Allegria2", url = "http://stream.zeno.fm/9ewh90xz4rhvv"},
    {name = "Emoción Radio", url = "http://topradio.one:8057/autodj"},
    {name = "Radio Akyyes", url = "http://topradio.one:8018/autodj"},
    {name = "Radio El Palmar", url = "http://topradio.one:8027/autodj"},
    {name = "Radio Guadalix", url = "http://topradio.uno:8054/autodj"},
    {name = "Candil Radio", url = "https://candilradio.com/liveradio/candil/live.mp3"},
    {name = "Free FM Classics", url = "https://xxdelgado.radioca.st/"},
    {name = "Kaibo Radio", url = "https://ibizasonica.streaming-pro.com:8013/kaiboradio"},
    {name = "Classic Rock Granada", url = "https://streaming2.elitecomunicacion.es:8054/stream"},
}

return stations
