local stations = {
    {name = "1FM - Deep House Radio", url = "http://strm112.1.fm/deephouse_mobile_mp3"},
    {name = "Radio Swiss Jazz", url = "http://stream.srg-ssr.ch/m/rsj/mp3_128"},
    {name = "1FM - Chillout Lounge Radio", url = "http://strm112.1.fm/chilloutlounge_mobile_mp3"},
    {name = "Kontrafunk", url = "https://s5.radio.co/sca4082ebb/listen"},
    {name = "SRF 3", url = "http://stream.srg-ssr.ch/m/drs3/mp3_128"},
    {name = "1FM - Amsterdam Trance Radio", url = "http://strm112.1.fm/atr_mobile_mp3"},
    {name = "SRF 4 News", url = "http://stream.srg-ssr.ch/m/drs4news/mp3_128"},
    {name = "1FM - Classic Rock Replay Radio", url = "http://strm112.1.fm/crock_mobile_mp3"},
    {name = "1FM - Deep Techno Deep House", url = "http://strm112.1.fm/deeptech_mobile_mp3"},
    {name = "Radio Swiss Classic German", url = "http://stream.srg-ssr.ch/m/rsc_de/mp3_128"},
    {name = "1FM - Ambient Psychill", url = "http://strm112.1.fm/ambientpsy_mobile_mp3"},
    {name = "Kontrafunk AAC 64", url = "https://s5.radio.co/sca4082ebb/low"},
    {name = "1FM - Classic Country Radio", url = "http://strm112.1.fm/ccountry_mobile_mp3"},
    {name = "1FM - Blues Radio", url = "http://strm112.1.fm/blues_mobile_mp3"},
    {name = "Kontrafunk MP3 192", url = "https://stream.kontrafunk.radio/listen/kontrafunk/radio.mp3"},
    {name = "RTS La Première", url = "http://stream.srg-ssr.ch/m/la-1ere/mp3_128"},
    {name = "1FM - Bay Smooth Jazz Radio", url = "http://strm112.1.fm/smoothjazz_mobile_mp3"},
    {name = "RTS Couleur 3", url = "http://stream.srg-ssr.ch/m/couleur3/mp3_128"},
    {name = "1FM - Absolute Country Hits Radio", url = "http://strm112.1.fm/acountry_mobile_mp3"},
    {name = "UZICCH :: TECHNO - MINIMAL", url = "http://stream.uzic.ch:9010/"},
    {name = "Radio Swiss Pop", url = "http://stream.srg-ssr.ch/m/rsp/mp3_128"},
    {name = "Vintage Radio", url = "https://vintageradio.ice.infomaniak.ch/vintageradio-high.mp3"},
    {name = "Energy Zürich NRJ", url = "http://broadcast.infomaniak.ch/energyzuerich-high.mp3"},
    {name = "1FM - BOM Psytrance Radio", url = "http://strm112.1.fm/psytrance_mobile_mp3"},
    {name = "1FM - Otto'S Baroque Music Radio", url = "http://strm112.1.fm/baroque_mobile_mp3"},
    {name = "Couleur3", url = "http://stream.srg-ssr.ch/m/couleur3/aacp_96"},
    {name = "1FM - Absolute TOP 40 Radio", url = "http://strm112.1.fm/top40_mobile_mp3"},
    {name = "Radio SRF 4 News", url = "https://stream.srg-ssr.ch/m/drs4news/aacp_32"},
    {name = "Radio SRF 3", url = "https://stream.srg-ssr.ch/m/drs3/aacp_32"},
    {name = "1FM - Rock Classics Radio", url = "http://strm112.1.fm/rockclassics_mobile_mp3"},
    {name = "1Fm Otto'S Baroque Music", url = "http://strm112.1.fm/baroque_mobile_aac"},
    {name = "1FM - Alternative Rock X Hits Radio", url = "http://strm112.1.fm/x_mobile_mp3"},
    {name = "1FM - Love Classics Radio", url = "http://strm112.1.fm/loveclassics_mobile_mp3"},
    {name = "Swissgroove", url = "http://158.69.74.203/"},
    {name = "Electroradiofm", url = "http://n05.radiojar.com/fkyxx4q35k0uv"},
    {name = "1FM - Disco Ball 70'S-80'S Radio", url = "http://strm112.1.fm/disco_mobile_mp3"},
    {name = "1FM - High Voltage Radio", url = "http://strm112.1.fm/highvoltage_mobile_mp3"},
    {name = "Ambi Nature Radio", url = "https://nature-rex.radioca.st/stream"},
    {name = "1FM - Adore Jazz Radio", url = "http://strm112.1.fm/ajazz_mobile_mp3"},
    {name = "Radio SRF 1 Regionaljournal Ostschweiz", url = "http://stream.srg-ssr.ch/m/regi_ost/mp3_128"},
    {name = "1FM - Reggaetrade Radio", url = "http://strm112.1.fm/reggae_mobile_mp3"},
    {name = "1FM - Ibiza Chill Tropical", url = "http://strm112.1.fm/ibizachill_mobile_mp3?aw_0_req.gdpr=true"},
    {name = "SRF 2", url = "http://stream.srg-ssr.ch/drs2/mp3_128.m3u"},
    {name = "1FM - Absolute Pop Latino Radio", url = "http://strm112.1.fm/latino_mobile_mp3"},
    {name = "GDSFM", url = "http://gdsfm.out.airtime.pro:8000/gdsfm_a"},
    {name = "Radio SRF 1 Regionaljournal Zürich, Schaffhausen", url = "http://stream.srg-ssr.ch/m/regi_zh_sh/mp3_128"},
    {name = "1FM - America'S Best Ballads Radio", url = "http://strm112.1.fm/onelive_mobile_mp3"},
    {name = "1FM - Absolute Trance Euro Radio", url = "http://strm112.1.fm/trance_mobile_mp3"},
    {name = "SRF 1", url = "http://stream.srg-ssr.ch/m/drs1/mp3_128"},
    {name = "1FM - Absolute 70'S Pop Radio", url = "http://strm112.1.fm/70s_mobile_mp3"},
    {name = "Radio Vostok", url = "http://radiovostok.ice.infomaniak.ch/radiovostok.aac"},
    {name = "Ip Music 320", url = "http://live7.avf.ch:8000/ipmusic320"},
    {name = "1FM - Bossa Nova Hits", url = "http://strm112.1.fm/bossanova_mobile_mp3"},
    {name = "80S Forever - We Keep The 80S Alive", url = "https://premium.shoutcastsolutions.com/radio/8050/256.mp3"},
    {name = "Radio Swiss Classic", url = "http://stream.srg-ssr.ch/m/rsc_it/mp3_128"},
    {name = "Spoon Radio", url = "http://spoonradio.ice.infomaniak.ch/spoonradio-hd"},
    {name = "Radio SRF 1", url = "http://stream.srg-ssr.ch/drs1/aacp_32.m3u"},
    {name = "Lounge Radio", url = "http://de1.streamhosting.ch/"},
    {name = "Radio SRF 1 Zentralschweiz", url = "http://stream.srg-ssr.ch/m/regi_zentr/mp3_128"},
    {name = "A Fine Jazz Gumbo Radio", url = "https://streaming.smartradio.ch:9502/stream"},
    {name = "1FM - Dubstep Forward Radio", url = "http://strm112.1.fm/dubstep_mobile_mp3"},
    {name = "Energy Basel NRJ", url = "https://energybasel.ice.infomaniak.ch/energybasel-high.mp3"},
    {name = "1FM - Bombay Beats India Radio", url = "http://strm112.1.fm/bombaybeats_mobile_mp3"},
    {name = "Vibration Zen Relax", url = "http://vibration.stream2net.eu:8220/;stream/1"},
    {name = "1FM - Dance One Radio", url = "http://strm112.1.fm/dance_mobile_mp3"},
    {name = "1FM - Country One Radio", url = "http://strm112.1.fm/country_mobile_mp3"},
    {name = "1FM - Costa Del Mar", url = "http://strm112.1.fm/costadelmarchillout_mobile_mp3"},
    {name = "Traxx FM - Tech Minimal", url = "http://traxx020.ice.infomaniak.ch/traxx020-low.mp3"},
    {name = "Electro Radio", url = "https://www.electroradio.fm/stream.m3u"},
    {name = "1FM - Afterbeat Electronica Radio", url = "http://strm112.1.fm/electronica_mobile_mp3"},
    {name = "1FM - Funky Express Radio", url = "http://185.33.22.15:11121/"},
    {name = "1FM - Eternal Praise Worship Radio", url = "http://strm112.1.fm/praise_mobile_mp3"},
    {name = "GOAT Radio", url = "https://20min.dmd2streaming.com/20minuten_radio_64.aac"},
    {name = "Radio24", url = "https://stream.streambase.ch/radio24/mp3-192/direct/"},
    {name = "Virgin Radio Switzerland", url = "https://stream.streambase.ch/vrock/mp3-192/direct/"},
    {name = "RADIO FM1", url = "https://chmedia.streamabc.net/79-fm1-mp3-192-7523806?sABC=6499oos8%230%230016or1p1r381r4485n244q3016qs660%23qverpg&aw_0_1st.playerid=direct&amsparams=playerid:direct;skey:1687796728"},
    {name = "RSI Rete Tre", url = "http://stream.srg-ssr.ch/m/retetre/mp3_128"},
    {name = "RSI Rete Uno", url = "http://stream.srg-ssr.ch/reteuno/aacp_32.m3u"},
    {name = "Spoon Radio - Rock Ballads", url = "https://spoonradiorockballads.ice.infomaniak.ch/spoon-rockballads-hd.aac"},
    {name = "Radio Suisse Classique", url = "http://www.surfmusik.de/m3u/station/radio-suisse-classique,16403.m3u"},
    {name = "1FM - Otto'S Opera House Music Radio", url = "http://strm112.1.fm/opera_mobile_mp3"},
    {name = "1FM - Sax4Love", url = "http://strm112.1.fm/sax4ever_mobile_mp3"},
    {name = "1FM - Cafe Radio", url = "http://strm112.1.fm/caferadio_mobile_mp3"},
    {name = "Radio SRF 1 Zürich Schaffhausen", url = "http://stream.srg-ssr.ch/regi_zh_sh/aacp_32.m3u"},
    {name = "SRF Virus", url = "http://stream.srg-ssr.ch/drsvirus/mp3_128.m3u"},
    {name = "1FM - A List 80S", url = "http://strm112.1.fm/back280s_mobile_mp3"},
    {name = "1FM - Magic 80 Radio", url = "http://strm112.1.fm/magic80_mobile_mp3"},
    {name = "Radio SRF 4 News HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs4news_96.stream/chunklist_DVR.m3u8"},
    {name = "1FM - All Times Hits", url = "http://185.33.21.111/allmixedup_mobile_mp3"},
    {name = "FLASHBACK FM", url = "https://flashback.streambase.ch/001"},
    {name = "RADIO BERN1", url = "https://stream.streambase.ch/radiobern1/mp3-192/direct/"},
    {name = "Radio 32", url = "https://stream.streambase.ch/radio32/mp3-192/chmedia-today-web"},
    {name = "Planet Ambi HD", url = "http://philae.shoutca.st:9019/stream"},
    {name = "1FM - Absolute 90S Party Zone Radio", url = "http://strm112.1.fm/partyzone90s_mobile_mp3"},
    {name = "1Fm Top Rap", url = "https://strm112.1.fm/jamz_mobile_mp3?aw_0_req.gdpr=true&listenerid=bc625eb7aaf609dd3942dc610e46ed40&awparams=companionAds%3Atrue"},
    {name = "Radio Pilatus", url = "https://stream.streambase.ch/radiopilatus/mp3-192/chmedia/"},
    {name = "Energy Bern", url = "https://energybern.ice.infomaniak.ch/energybern-high.mp3"},
    {name = "Open Broadcast Radio", url = "http://stream.openbroadcast.ch/320.mp3"},
    {name = "Spoon Radio - Modern Rock", url = "https://spoonradiomodernrock.ice.infomaniak.ch/spoon-modernrock-hd.aac"},
    {name = "1FM - Movie Soundtrack", url = "http://strm112.1.fm/moviesoundtracks_mobile_mp3"},
    {name = "Radio1Ch", url = "https://stream.radio1.ch/128k"},
    {name = "Basspistol Radio", url = "https://radio.basspistol.com/radio.mp3"},
    {name = "1FM - Adult Urban Hits Choice Radio", url = "http://strm112.1.fm/oldschool_mobile_mp3"},
    {name = "SWISS GROOVE", url = "https://relay2.swissgroove.ch/;"},
    {name = "Radio Zürisee", url = "http://mp3.radio.ch/radiozuerisee128k"},
    {name = "Spoon Radio - Alternative Rock", url = "https://spoonradioalternativerock.ice.infomaniak.ch/spoon-alternativerock-hd.aac"},
    {name = "1FM Essential Classical", url = "http://strm112.1.fm/polskafm_mobile_mp3"},
    {name = "Pop | Radio Swiss", url = "https://stream.srg-ssr.ch/m/rsp/mp3_128"},
    {name = "1FM - Club 1 Radio", url = "http://strm112.1.fm/club_mobile_mp3"},
    {name = "Radio SRF 1 Bern Freibourg Wallis", url = "http://stream.srg-ssr.ch/regi_be_fr_vs/aacp_32.m3u"},
    {name = "RTS Option Musique", url = "http://stream.srg-ssr.ch/option-musique/mp3_128.m3u"},
    {name = "Radio X Basel MP3 Stream", url = "http://mp3.radiox.ch:8000/standard.mp3.m3u"},
    {name = "1FM - All Euro 80'S Radio", url = "http://strm112.1.fm/80s_90s_mobile_mp3"},
    {name = "1FM - Slow Jamz Radio", url = "http://strm112.1.fm/slowjamz_mobile_mp3"},
    {name = "1FM - Samba Hits Brazil Radio", url = "http://strm112.1.fm/samba_mobile_mp3"},
    {name = "RADIO ARGOVIA", url = "https://stream.streambase.ch/argovia/mp3-192/direct/"},
    {name = "Radio SRF 1 Regionaljournal Basel, Baselland", url = "http://stream.srg-ssr.ch/m/regi_bs_bl/mp3_128"},
    {name = "1FM - All Times Urban Gospel Radio", url = "http://strm112.1.fm/gospel_mobile_mp3"},
    {name = "Traxx FM - Deep", url = "http://traxx013.ice.infomaniak.ch/traxx013-low.mp3"},
    {name = "Radio SRF 1 Aargau Solothurn", url = "http://stream.srg-ssr.ch/regi_ag_so/aacp_32.m3u"},
    {name = "Truehouse Chill", url = "http://www.truehouse.net/chill.m3u"},
    {name = "SRF Musikwelle", url = "http://stream.srg-ssr.ch/drsmw/mp3_128.m3u"},
    {name = "Radio Melody", url = "https://chmedia.streamabc.net/79-rm-mp3-192-7754268?sABC=64726ssr%230%23565o8622n9638n515p1pqq82pnq6q099%23zlghare&aw_0_1st.playerid=mytuner&amsparams=playerid:mytuner;skey:1685221374"},
    {name = "Spoon Radio - Hard Rock", url = "https://spoonradiohardrock.ice.infomaniak.ch/spoon-hardrock-hd.aac"},
    {name = "My105 - Deep", url = "http://stream01.my105.ch/my105deep.mp3"},
    {name = "1FM - Kids FM Radio", url = "http://strm112.1.fm/kidsfm_mobile_mp3"},
    {name = "RSR La Premiere", url = "http://stream.srg-ssr.ch/la-1ere/aacp_32.m3u"},
    {name = "Radio Tell", url = "http://stream.radiotell.ch/radiotell.mp3"},
    {name = "Radio SRF 1 Regionaljournal Aargau, Solothurn", url = "http://stream.srg-ssr.ch/m/regi_ag_so/mp3_128"},
    {name = "Rundfunk FM", url = "http://rundfunk.ice.infomaniak.ch/rundfunk-192.mp3"},
    {name = "1FM Beloved Ballads", url = "https://strm112.1.fm/onelive_mobile_mp3?"},
    {name = "LFM", url = "http://lausannefm.ice.infomaniak.ch/lausannefm-high.mp3"},
    {name = "Traxx FM - Lounge", url = "http://traxx004.ice.infomaniak.ch/traxx004-low.mp3"},
    {name = "Spoon Radio - Classic Rock", url = "https://spoonradioclassicrock.ice.infomaniak.ch/spoon-classicrock-hd.aac"},
    {name = "Radio Freundesdienst Deutsch", url = "http://radiofd.ice.infomaniak.ch/radiofd.mp3"},
    {name = "Rouge Reggae", url = "http://rouge-reggae.ice.infomaniak.ch/rouge-reggae-128.mp3"},
    {name = "Radio Basilisk", url = "http://radiobasilisk-64.ice.infomaniak.ch/radiobasilisk-64-128-2.mp3"},
    {name = "SRF1 Radio", url = "http://stream.srg-ssr.ch/drs1/aacp_96.m3u"},
    {name = "1FM - Back To The 50'S 60'S Radio", url = "http://strm112.1.fm/60s_70s_mobile_mp3"},
    {name = "Radio Chablais", url = "http://radiochablais.ice.infomaniak.ch/radiochablais-high.mp3"},
    {name = "Sunshine Radio Switzerland", url = "https://stream.streambase.ch/rsunshine/mp3-192/chmedia-radio-web/1699795900047_8633080"},
    {name = "Radio SRF 1 Regionaljournal Graubünden", url = "http://stream.srg-ssr.ch/m/regi_gr/mp3_128"},
    {name = "Radio Svizzera Classica", url = "https://stream.srg-ssr.ch/rsc_it/aacp_96.m3u"},
    {name = "1Fm Otto'S Classical Music Httpmp3", url = "http://strm112.1.fm/classical_mobile_mp3"},
    {name = "Radio Melody Schweiz", url = "https://stream.streambase.ch/rm/mp3-192/mytuner/"},
    {name = "1Fm Otto'S Classical Music", url = "https://strm112.1.fm/classical_mobile_aac"},
    {name = "1FM - Destination: SPA Radio", url = "http://strm112.1.fm/spa_mobile_mp3"},
    {name = "Radio SRF 2 Kultur", url = "http://stream.srg-ssr.ch/drs2/aacp_32.m3u"},
    {name = "Radio Swiss Jazz HLS 96", url = "http://lsaplus.swisstxt.ch/audio/rsj_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Lora 975", url = "https://livestream.lora.ch/lora.mp3"},
    {name = "Traxx FM - Pop", url = "http://traxx009.ice.infomaniak.ch/traxx009-low.mp3"},
    {name = "Swiss Pop", url = "http://www.radioswisspop.ch/live/aacp.m3u"},
    {name = "Jazzology Radio", url = "https://c2.radioboss.fm:18094/stream"},
    {name = "Radio Top Ostschweiz", url = "https://radiotop.ice.infomaniak.ch/radiotop96.aac"},
    {name = "RSI Rete Due", url = "http://stream.srg-ssr.ch/m/retedue/mp3_128"},
    {name = "One FM 2000S", url = "https://webradio0009.ice.infomaniak.ch/webradio0009-128.mp3"},
    {name = "Radio 1", url = "http://stream.radio1.ch/128k.m3u"},
    {name = "1FM - Jamz Radio", url = "http://strm112.1.fm/jamz_mobile_mp3"},
    {name = "1FM - Italia On Air Radio", url = "http://strm112.1.fm/italiaonair_mobile_mp3"},
    {name = "Radio Top Two", url = "http://77.109.144.109:8000/twosrp128"},
    {name = "IP Music Slow 96 Kbps AAC", url = "http://live7.avf.ch:8000/ipmusicslowaacp96"},
    {name = "Rock The Blues", url = "http://stream.laut.fm/rock-the-blues"},
    {name = "Happy Radio", url = "https://uksoutha.streaming.broadcast.radio/stream/11340/gtradio?1672903939995"},
    {name = "Traxx FM - Ambient", url = "http://traxx011.ice.infomaniak.ch/traxx011-low.mp3"},
    {name = "Energy St Gallen NRJ", url = "https://energystgallen.ice.infomaniak.ch/energystgallen-high.mp3"},
    {name = "One Dance Ticino", url = "https://ice15.fluidstream.net/onedancech.aac"},
    {name = "My105 - Mashup", url = "http://stream01.my105.ch/my105mashup.mp3"},
    {name = "Country Radio Switzerland CRS", url = "http://stream.countryradio.ch/crs-128.mp3"},
    {name = "Energy Bern NRJ", url = "http://broadcast.infomaniak.ch/energybern-high.mp3"},
    {name = "Jazz | Radio Swiss", url = "https://stream.srg-ssr.ch/m/rsj/mp3_128"},
    {name = "Electrons Libres", url = "https://api.radioking.io/radio/427889/listen.m3u"},
    {name = "Radio SRF 1 Ostschweiz", url = "http://stream.srg-ssr.ch/regi_ost/aacp_32.m3u"},
    {name = "1FM - Gorilla FM Radio", url = "http://strm112.1.fm/gorillafm_mobile_mp3"},
    {name = "1FM - Radio Gaia", url = "http://strm112.1.fm/radiogaia_mobile_mp3"},
    {name = "Radio Sans Chaine", url = "http://radio-sans-chaine.ice.infomaniak.ch/radiosanschaine.aac"},
    {name = "Spoon Radio - Acoustic Rock", url = "https://spoonradioacousticrock.ice.infomaniak.ch/spoon-acousticrock-hd.aac"},
    {name = "Ta Radio", url = "https://stream.taradio.ch/dab"},
    {name = "Traxx FM - Golden Oldies", url = "http://traxx023.ice.infomaniak.ch/traxx023-1.mp3"},
    {name = "Al Quran Radio", url = "https://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABhdgGORQA-2acfyF3_4WY2g"},
    {name = "1FM - Sunshine", url = "https://strm112.1.fm/allmixedup_mobile_mp3?"},
    {name = "Radio Lac", url = "https://radiolac.ice.infomaniak.ch/radiolac-high.mp3"},
    {name = "Radio Gaba Switzerland", url = "http://radio-gaba.ddns.net:8000/play.ogg"},
    {name = "Barix Radio", url = "http://barix.streamguys.net/barix_hi.m3u"},
    {name = "Jazz Black Music", url = "http://jazzblackmusic.ice.infomaniak.ch/jazzblackmusic-high.aac"},
    {name = "Classic Rock", url = "https://chmedia.streamabc.net/79-classicrock-mp3-192-6577748?sABC=655o94o7%230%239906209q5qoq5po487r1668p80q43331%23qverp&aw_0_1st.playerid=direc&amsparams=playerid:direc;skey:1700500663"},
    {name = "My105 - DJ Mixes", url = "http://stream01.my105.ch/my105djnights.mp3"},
    {name = "ஊரி தமிழ் வானொலி URI TAMIL RADIO", url = "http://stream.zenolive.com/u8nt64f6sfeuv"},
    {name = "Radio SRF 1 Basel Baselland", url = "http://stream.srg-ssr.ch/m/regi_bs_bl/aacp_96"},
    {name = "Radio Swiss Classic French", url = "http://www.radioswissclassic.ch/fr/live/aacp32.m3u"},
    {name = "Rabe Radio Bern Switzerland", url = "http://stream.rabe.ch:8000/livestream/rabe-mid.mp3"},
    {name = "ABSOLUTE 90'S RADIO", url = "http://sc1.1.fm:8065/"},
    {name = "1FM - Exitos Del Ayer Radio", url = "http://strm112.1.fm/spanisholdies_mobile_mp3"},
    {name = "Canal3 Deutsch", url = "https://radio.upstream-cloud.ch/canal3allemand-192.aac"},
    {name = "Radio Gloria", url = "https://ch-be06-ice.dmd2streaming.com/radiogloria_lo"},
    {name = "Radio SRF Virus - Indie Rock", url = "http://streaming.swisstxt.ch/m/drsvirus/mp3_128"},
    {name = "Traxx FM - Jazz", url = "http://traxx014.ice.infomaniak.ch/traxx014-low.mp3"},
    {name = "Radio Eviva", url = "https://stream.streambase.ch/reviva/mp3-192/direct/"},
    {name = "Audioasyl", url = "http://stream.audioasyl.net:8000/audioasyl"},
    {name = "RTS Espace 2", url = "http://stream.srg-ssr.ch/espace-2/mp3_128.m3u"},
    {name = "New Clear Radio", url = "http://live.ncradio.fm/320"},
    {name = "Energy Luzern", url = "https://energyluzern.ice.infomaniak.ch/energyluzern-high.mp3"},
    {name = "My105 - Original", url = "http://stream01.my105.ch/my105original.mp3"},
    {name = "Classic | Radio Swiss", url = "https://stream.srg-ssr.ch/m/rsc_de/mp3_128"},
    {name = "Traxx FM - Cool Jam", url = "http://traxx005.ice.infomaniak.ch/traxx005-low.mp3"},
    {name = "Neo1", url = "https://neo1.ice.infomaniak.ch/neo1.mp3"},
    {name = "Radio Maxxima", url = "https://maxxima.mine.nu/maxxima.mp3"},
    {name = "1FM - Top Fiesta Radio", url = "http://strm112.1.fm/spanishparty_mobile_mp3"},
    {name = "RADIO MARIA SWITZERLAND", url = "http://dreamsiteradiocp2.com:8106/stream"},
    {name = "Radio SRF 3 HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs3_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Rocket", url = "https://i9.streams.ovh/sc/radioroc/stream"},
    {name = "Radio Swiss Pop HLS 96", url = "http://lsaplus.swisstxt.ch/audio/rsp_96.stream/chunklist_DVR.m3u8"},
    {name = "IP Music Slow", url = "http://live7.avf.ch:8000/ipmusicslow256"},
    {name = "My105 - Ritmo Latino", url = "http://stream01.my105.ch/my105ritmolatino.mp3"},
    {name = "1Fm Movie Soundtrack Hits", url = "https://strm112.1.fm/moviesoundtracks_mobile_mp3?"},
    {name = "Radio Central", url = "https://stream.streambase.ch/rcentral/mp3-192/chmedia-radio-web/1723615196409_33800762"},
    {name = "Vibración Latina", url = "http://vibration.stream2net.eu:8410/;stream/1"},
    {name = "Radio 3FACH", url = "http://stream01.3fach.ch:8001/live"},
    {name = "Radio Südostschweiz", url = "https://somedia-1.streaming.deliver.media/rso_mp3_128?suffix0=RSO"},
    {name = "Jazz Radio Lounge", url = "http://jazzlounge.ice.infomaniak.ch/jazzlounge-high.aac"},
    {name = "Radio Grischa", url = "https://somedia-1.streaming.deliver.media/radiogrischa_mp3_128?suffix0=RSO"},
    {name = "One FM New-Hits", url = "https://webradio0001.ice.infomaniak.ch/webradio0001-128.mp3"},
    {name = "Radio Morcote International", url = "http://streaming.radiomorcoteinternational.com:8000/;"},
    {name = "Rouge", url = "http://rougefm.ice.infomaniak.ch/rougefm-high.aac"},
    {name = "My105 - The Battle", url = "http://stream01.my105.ch/my105thebattle.mp3"},
    {name = "Gnu Radio - Metal FM", url = "https://fluxfm.streamabc.net/flx-metalfm-mp3-320-9154971?sABC=61s83r32%230%2389nqs1p1q8rrq2q126260sp7877or6oo%23fgernzf.syhksz.qr&amsparams=playerid:streams.fluxfm.de;skey:1643658802"},
    {name = "My105 - Dance", url = "http://stream01.my105.ch/my105dance.mp3"},
    {name = "RSR Couleur 3", url = "http://stream.srg-ssr.ch/couleur3/aacp_32.m3u"},
    {name = "Traxx FM - Rap", url = "http://traxx015.ice.infomaniak.ch/traxx015-low.mp3"},
    {name = "Traxx FM - House", url = "http://traxx002.ice.infomaniak.ch/traxx002-low.mp3"},
    {name = "Radio S", url = "https://stream.radio-s.ch/stream"},
    {name = "Musikwälle", url = "https://stream.srg-ssr.ch/drsmw/mp3_128.m3u"},
    {name = "IP Music", url = "http://live9.avf.ch:8000/ipmusicaacplus96"},
    {name = "Radio3I", url = "https://vstream-cdn.ch/hls/radio3i.m3u8"},
    {name = "Break Radio", url = "https://breakradio.ice.infomaniak.ch/breakradio-192.mp3"},
    {name = "True House Radio", url = "http://www.truehouse.net/house.m3u"},
    {name = "1FM - Circuit Pride Radio", url = "http://strm112.1.fm/circuitpride_mobile_mp3"},
    {name = "1FM - Total Hits En Español Radio", url = "http://strm112.1.fm/spanishtophits_mobile_mp3"},
    {name = "Radio R", url = "http://radior.ice.infomaniak.ch/radior-128.mp3"},
    {name = "Radio SRF 1 Regionaljournal Bern, Freiburg, Wallis", url = "http://stream.srg-ssr.ch/m/regi_be_fr_vs/mp3_128"},
    {name = "Radio SRF Musikwelle", url = "http://stream.srg-ssr.ch/m/drsmw/aacp_96"},
    {name = "1FM - MPB Hits Radio", url = "http://strm112.1.fm/mpb_mobile_mp3"},
    {name = "1FM - Sertaneja Hits Radio", url = "http://strm112.1.fm/sertanejo_mobile_mp3"},
    {name = "Radio 32 Goldies", url = "https://stream.streambase.ch/r32goldies/mp3-192/direct/"},
    {name = "Aebisland", url = "https://aebisland.ice.infomaniak.ch/aebisland-128.mp3"},
    {name = "Radio Argovia Classic Rock", url = "https://stream.streambase.ch/crock/mp3-192/radiobrowser/"},
    {name = "Radio SRF 2 Kultur HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs2_96.stream/chunklist_DVR.m3u8"},
    {name = "Loungemain Radio Jazz-Chill-Funk", url = "http://185.238.128.191:8002/live"},
    {name = "RADIO SWISS CLASSICA ITALIA", url = "https://stream.srg-ssr.ch/rsc_it/mp3_128.m3u"},
    {name = "URBN Radio", url = "https://dr2101.ice.infomaniak.ch/dr2103.mp3"},
    {name = "Radio Niesen", url = "https://login.streamplus.de/app.php/streamserver/public/31677.m3u"},
    {name = "Radiofr Freiburg", url = "http://radiofreiburg.ice.infomaniak.ch/radiofreiburg-high.mp3"},
    {name = "Christmas Radio", url = "http://xmasfm1.dmd2streaming.com/christmasradiofm-128.mp3"},
    {name = "Jukebox - Nonstop Music,Autodj", url = "https://kreuzbergswiss.sp.radio.fm/stream"},
    {name = "Radiofr Fribourg", url = "http://radiofribourg.ice.infomaniak.ch/radiofribourg-high.mp3"},
    {name = "Kanalk", url = "https://play.kanalk.ch/kanalk/mp3-192/"},
    {name = "Radio Zuerisee", url = "http://mp3.radio.ch/radiozuerisee256k"},
    {name = "Radio Fribourg", url = "https://radiofribourg.ice.infomaniak.ch/radiofribourg-high.mp3"},
    {name = "RSR Option Musique", url = "http://stream.srg-ssr.ch/option-musique/aacp_32.m3u"},
    {name = "ROCKSTATION", url = "https://radio2.stream24.net:8130/live.mp3"},
    {name = "SRF1 Regionaljournal Aargau Solothurn", url = "http://stream.srg-ssr.ch/regi_ag_so/aacp_96.m3u"},
    {name = "My105 - Charts", url = "http://stream01.my105.ch/my105charts.mp3"},
    {name = "Radio Rasa Schaffhausen", url = "https://radio.upstream-cloud.ch/radiorasa-128.mp3"},
    {name = "1014 YOUNG FM", url = "https://canli.arabeskinmerkezi.com/9180/stream"},
    {name = "Radio Swiss Classic DE HLS 96", url = "http://lsaplus.swisstxt.ch/audio/rsc_de_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Radius Ogg", url = "http://relay.radio.ethz.ch/sender.ogg.m3u"},
    {name = "My105 - All The Hits", url = "http://stream01.my105.ch/my105allthehits.mp3"},
    {name = "1Fm Back To The 50'S", url = "https://strm112.1.fm/60s_70s_mobile_mp3?"},
    {name = "Skuizz Hits 90S-00S", url = "https://traxx024.ice.infomaniak.ch/traxx024-1.mp3"},
    {name = "Traxx FM - Funk", url = "http://traxx016.ice.infomaniak.ch/traxx016-low.mp3"},
    {name = "World Radio Switzerland", url = "https://uksouth.streaming.broadcast.radio:10290/wrs"},
    {name = "Rouge FM Suisse", url = "http://rouge-suisse.ice.infomaniak.ch/rouge-suisse-128.mp3"},
    {name = "Vibration Vintage", url = "http://vibrationvintage-high.ice.infomaniak.ch/vibration-vintage.mp3"},
    {name = "Rouge FM Lounge", url = "http://rougefm.ice.infomaniak.ch/rougefm-high.mp3"},
    {name = "Radio SRF Virus", url = "http://stream.srg-ssr.ch/drsvirus/aacp_32.m3u"},
    {name = "Abc", url = "https://lounge-radio.com/aacplus.m3u"},
    {name = "Driftfm", url = "https://s4.radio.co/s5729f2e59/listen"},
    {name = "Radio Stadtfilter Winterthur", url = "http://stream.stadtfilter.net:8406/stadtfilter.mp3"},
    {name = "Global Sport - Suisse", url = "http://live9.avf.ch:8000/globalfm160"},
    {name = "Global Sport NFBJ", url = "http://live9.avf.ch:8000/globalfmdabne"},
    {name = "My105 - Chill", url = "http://stream01.my105.ch/my105chill.mp3"},
    {name = "Kanal Bethesda", url = "http://162.13.25.174/a2dd2q0kb"},
    {name = "My105 - Party", url = "http://stream01.my105.ch/my105party.mp3"},
    {name = "IP Music SLOW - Aacplus@96 Kbs", url = "https://live9.avf.ch/ipmusicslowaacp96"},
    {name = "Jazz Radio", url = "http://broadcast.infomaniak.ch/jazzlounge-high.mp3"},
    {name = "Powerup Radio", url = "http://stream.powerup.ch/powerupradio-192.mp3"},
    {name = "Glaubenskampf Bibel Radio", url = "https://streams.radio.co/s06c02a443/listen"},
    {name = "My105 - Rock", url = "http://stream01.my105.ch/my105rock.mp3"},
    {name = "NRJ Léman 103,6 FM", url = "http://cdn.nrjaudio.fm/audio1/ch/50001/mp3_128.mp3"},
    {name = "Pineapple Juice", url = "http://stream.laut.fm/pineapplejuice"},
    {name = "R102", url = "http://94.23.66.155:9334/listen.pls"},
    {name = "My105 - Fresh", url = "http://stream01.my105.ch/my105fresh.mp3"},
    {name = "IP Music Slow 128 Kbps AAC", url = "http://live7.avf.ch:8000/ipmusicslowaacp128"},
    {name = "DIKS ДИКС", url = "https://icecast.correctiv.net/sacharow"},
    {name = "Radioswiss", url = "http://stream.laut.fm/radioswiss"},
    {name = "WALTS WELT", url = "https://waltswelt.out.airtime.pro/waltswelt_a?_ga=2.33964516.474222732.1669644968-446937151.1669306237"},
    {name = "Arc Musique", url = "https://arcmusique.ice.infomaniak.ch/arcmusique-128.mp3"},
    {name = "Ktfm Geneva - THE BEST OF 70'S AND 80'S", url = "https://ktfm.ice.infomaniak.ch/ktfm-high.mp3"},
    {name = "GRRIF", url = "https://rjb.ice.infomaniak.ch/rjb-high.mp3"},
    {name = "Lounge-Radiocom", url = "https://fr1.streamhosting.ch/lounge128.mp3"},
    {name = "Kanal K", url = "https://play.kanalk.ch/kanalk/mp3-192/webstream"},
    {name = "Traxx FM - Rnb", url = "http://traxx007.ice.infomaniak.ch/traxx007-low.mp3"},
    {name = "One FM", url = "http://onefm.ice.infomaniak.ch/onefm-high.mp3"},
    {name = "1FM - Always-Christmas Radio", url = "http://strm112.1.fm/christmas_mobile_mp3"},
    {name = "Radio R Louange", url = "https://radiorlouange.ice.infomaniak.ch/radiorlouange-96.aac?ver=666978"},
    {name = "1FM - Samba Rock Radio", url = "http://strm112.1.fm/sambarock_mobile_mp3"},
    {name = "80Ies Dot Radio", url = "https://stream.radiojar.com/6cbvkaa1mrruv?1643199882"},
    {name = "Radio Onyx", url = "http://nr4.newradio.it:9432/listen.pls"},
    {name = "1FM - Acappella Radio", url = "http://strm112.1.fm/acpl_mobile_mp3"},
    {name = "Radio15Ch", url = "http://radio15.ice.infomaniak.ch/radio15-192kbps.mp3?fbclid=IwAR1RgI4qFLCInWkcBZBlod__-7UXEufqWJJl2BnOT1s_xnkTuUQg8BG4avc"},
    {name = "Radio Rotblau", url = "https://rotblaustream.ch:8443/live"},
    {name = "Radio Swiss Classic Italian", url = "http://www.radioswissclassic.ch/it/live/aacp32.m3u"},
    {name = "Radio Merak", url = "http://79.143.187.96:8092/"},
    {name = "Option Musique", url = "http://stream.srg-ssr.ch/m/option-musique/mp3_128"},
    {name = "Radio Freundesdienst Schweiz", url = "http://radiofdch.ice.infomaniak.ch/radiofdch.mp3"},
    {name = "Radio Summernight", url = "https://stream.laut.fm/radiosummernight"},
    {name = "Radio Neue Hoffnung", url = "https://stream.mnr.ch/rnh-mp3"},
    {name = "Vibration Poprock", url = "http://vibrationpoprock.ice.infomaniak.ch/vibrationpoprock-high.mp3"},
    {name = "Radio SRF 1 HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drs1_96.stream/chunklist_DVR.m3u8"},
    {name = "Radio Bollwerk", url = "https://radiobollwerk.out.airtime.pro/radiobollwerk_a"},
    {name = "Radio RTR", url = "https://stream.srg-ssr.ch/rr/aacp_96.m3u"},
    {name = "Radio Radius AAC", url = "http://relay.radio.ethz.ch/sender.aac.m3u"},
    {name = "My105 - Love", url = "http://stream01.my105.ch/my105love.mp3"},
    {name = "Radio Radius Mp3", url = "http://relay.radio.ethz.ch/sender.mp3.m3u"},
    {name = "Vertical Radio", url = "http://verticalradio.ice.infomaniak.ch/verticalradio-128.mp3"},
    {name = "Vibration 108", url = "http://vibration108-high.ice.infomaniak.ch/vibration108-high.mp3"},
    {name = "Vibration Soft Hits", url = "http://vibration.stream2net.eu:8350/;stream/1"},
    {name = "WRS Swiss Radio In English", url = "https://uksouth.streaming.broadcast.radio:10290/wrs?_=443217"},
    {name = "Vibration Gayradio", url = "http://vibration.stream2net.eu:8480/;stream/1"},
    {name = "Rouge FM Latino", url = "http://rouge-latino.ice.infomaniak.ch/rouge-latino-128.mp3"},
    {name = "Radio Ouistiti", url = "http://radioouistiti2.ice.infomaniak.ch/radioouistiti-high.mp3"},
    {name = "Radionet+", url = "http://radionetplus.ice.infomaniak.ch/radionetplus-high.mp3"},
    {name = "Toxicfm", url = "http://toxicfm.ice.infomaniak.ch/toxicfm-128"},
    {name = "Radio Rumantsch", url = "http://stream.srg-ssr.ch/m/rr/mp3_128"},
    {name = "Ahuga Lautfm", url = "http://stream.laut.fm/ahuga"},
    {name = "Radiopolis", url = "http://rs01.swissnwx.ch:20080/stream"},
    {name = "Global Sport - Genève", url = "http://live9.avf.ch:8000/globalfmdabge"},
    {name = "Global Sport - Vaud", url = "http://live9.avf.ch:8000/globalfmdabvd"},
    {name = "Radio Kaiseregg", url = "http://kaiseregg.ice.infomaniak.ch/stream128k.mp3"},
    {name = "Gorillafm", url = "https://strm112.1.fm/gorillafm_mobile_mp3"},
    {name = "RADIO ROTATION", url = "http://stream.laut.fm/radio-rotation"},
    {name = "My105 - Dreist", url = "http://stream01.my105.ch/my105dreist.mp3"},
    {name = "Radiosouvenircom", url = "http://www.radiosouvenir.com/radio.m3u"},
    {name = "Radio Barix AAC", url = "http://barix.streamguys.net/barix_aacp"},
    {name = "Rouge FM 90S", url = "http://rouge-90.ice.infomaniak.ch/rouge-90-128.mp3"},
    {name = "Burningstationcom", url = "https://server1.streamserver-unlimited.de:2199/tunein/iu245.pls"},
    {name = "My105 - Deluxe", url = "http://stream01.my105.ch/my105deluxe.mp3"},
    {name = "Telebielinguetv", url = "http://livevideo.infomaniak.com/streaming/livecast/telebielinguech/playlist.m3u8"},
    {name = "Dream Sequence", url = "https://www.radioking.com/play/dream-sequence/508976"},
    {name = "Soul Club Radio", url = "https://a1.asurahosting.com:8430/radio.mp3"},
    {name = "RTN", url = "https://rtn.ice.infomaniak.ch/rtn-high.mp3"},
    {name = "RFJ", url = "https://rfj.ice.infomaniak.ch/rfj-high.mp3"},
    {name = "Radio X Basel OGG Stream", url = "http://mp3.radiox.ch:8000/standard.ogg.m3u"},
    {name = "RSR Espace 2", url = "http://stream.srg-ssr.ch/espace-2/aacp_32.m3u"},
    {name = "Global FM", url = "http://globalfm.ice.infomaniak.ch/globalfm-high.mp3"},
    {name = "Radio Grenzenlos,Radio Grenzenlos [Test Spcast]", url = "http://stream.grenzenlos.ch/"},
    {name = "Framboase", url = "http://framboase.ice.infomaniak.ch/framboase-128.mp3"},
    {name = "Energy Blick Trendz", url = "http://energyzuerich.ice.infomaniak.ch/energyzuerich-high.mp3"},
    {name = "Global Sport SUISSE", url = "http://live7.avf.ch:8000/globalfm"},
    {name = "JAMES FM", url = "https://jamesfm.ice.infomaniak.ch/jamesfm.mp3"},
    {name = "Radio4Tng", url = "http://radio4tng.ice.infomaniak.ch/radio4tng-live-web.mp3"},
    {name = "M La Radio", url = "https://mlaradio.ice.infomaniak.ch/mlaradio.mp3"},
    {name = "Kiss Collector Radio", url = "https://dr2101.ice.infomaniak.ch/dr2101.mp3"},
    {name = "Rhône FM", url = "http://rhonefm.ice.infomaniak.ch/rhonefm-high.aac"},
    {name = "One FM 90S", url = "https://webradio0006.ice.infomaniak.ch/webradio0006-128.mp3"},
    {name = "Piratenradio", url = "http://piratenradioch.ice.infomaniak.ch/piratenradioch-128.mp3"},
    {name = "Radio Drachenblut", url = "http://radio-drachenblut.ch:8000/stream/3/"},
    {name = "Radio Stadtfilter DAB+", url = "https://www.digris.ch/stream/8a1a42f0-3f59-4113-b544-aad9275d34a7"},
    {name = "Open Broadcast", url = "https://www.digris.ch/stream/092210ed-4eb4-483b-814f-21df6ecb1352"},
    {name = "Traxx FM - Rock", url = "http://traxx019.ice.infomaniak.ch/traxx019-low.mp3"},
    {name = "Traxx FM - Soul", url = "http://traxx006.ice.infomaniak.ch/traxx006-low.mp3"},
    {name = "TVM 3 TV", url = "http://tvm3.vedge.infomaniak.com/livecast/tvm3/playlist.m3u8"},
    {name = "Gottes Radio", url = "http://stream.laut.fm/gottesradio.m3u"},
    {name = "Traxx FM - Classic", url = "http://traxx012.ice.infomaniak.ch/traxx012-low.mp3"},
    {name = "Traxx FM - France", url = "http://traxx025.ice.infomaniak.ch/traxx025-1.mp3"},
    {name = "Traxx FM - Italia", url = "http://traxx021.ice.infomaniak.ch/traxx021-1.mp3"},
    {name = "Traxx FM - Latino Pop", url = "http://traxx022.ice.infomaniak.ch/traxx022-1.mp3"},
    {name = "Radio SRF Musikwelle HLS 96", url = "http://lsaplus.swisstxt.ch/audio/drsmw_96.stream/chunklist_DVR.m3u8"},
    {name = "LUX RADIO", url = "https://fluxradio.ice.infomaniak.ch/fluxradio-32.aac"},
    {name = "Vibration Chanson Française", url = "http://vibration.stream2net.eu:8510/;stream/1"},
    {name = "Vibration FM", url = "http://vibration-aac.stream2net.eu:8040/listen.pls"},
    {name = "VOXINOX", url = "http://voxinox.ice.infomaniak.ch/voxinox-128"},
    {name = "Radio-Drachenblut", url = "https://radio-drachenblut.ch/stream.m3u"},
    {name = "Traxx FM - Deluxe", url = "http://traxx001.ice.infomaniak.ch/traxx001-low.mp3"},
    {name = "Rockstation'S Broadcast", url = "http://radio2.stream24.net:8130/live.mp3"},
    {name = "Radio Maria Schweiz", url = "http://streaming2.elitecomunicacion.es:9000/radiomaria_lo"},
    {name = "Radio Beo", url = "http://stream11.radiobeo.ch:8000/radiobeo.mp3"},
    {name = "TVM3TV", url = "http://livevideo.infomaniak.com/streaming/livecast/tvm3/playlist.m3u8"},
    {name = "Adonia-Kidsradio", url = "http://puma.streemlion.com:1930/stream"},
    {name = "My105 X-MAS", url = "https://stream01.my105.ch/my105xmas.mp3"},
    {name = "My105 X-MAS Radio AAC", url = "https://stream01.my105.ch/my105xmas-aac.mp3"},
    {name = "Radio Chablais - 100% Français", url = "http://stream.radiochablais.ch/chablais-100francais.mp3"},
    {name = "Radio Vihor", url = "https://r.name.ba:7500/"},
    {name = "Traxx FM - Latino", url = "http://traxx008.ice.infomaniak.ch/traxx008-low.mp3"},
    {name = "Radio Gugelhopf", url = "http://uk3.internet-radio.com:8113/stream"},
}

return stations
