local stations = {
<<<<<<< HEAD
    {name = "EXA FM: POP MUSIC In Spanish And English", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac"},
    {name = "907 FM KWMU-1", url = "https://kwmu1-ice.streamguys1.com/kwmu1.m3u"},
    {name = "Iheart Radio Café", url = "http://stream.revma.ihrhls.com/zc6951/hls.m3u8"},
    {name = "KHSU 905FM - California State Polytechnic University, Humboldt", url = "https://18743.live.streamtheworld.com/KHSUFM.mp3"},
    {name = "KTLR The Light", url = "http://stream.zeno.fm/gaaa0t09ewzuv"},
    {name = "TNT Radio Live", url = "https://streaming.tntradio.live/"},
    {name = "WBBM Newsradio 780 AM 1059 FM", url = "https://live.amperwave.net/direct/audacy-wbbmammp3-imc"},
    {name = "WVPE HD3 - Blues", url = "http://live.str3am.com:2240/live"},
    {name = "1 Oldies", url = "https://80sexitos.stream.laut.fm/80sexitos"},
    {name = "1Oldies", url = "https://stream.laut.fm/80sexitos"},
    {name = "80 HITS", url = "http://stream.laut.fm/80sexitos"},
    {name = "80Sradio", url = "https://samcloud.spacial.com/api/listen?sid=111415&_80s&live&mp3"},
    {name = "Funky Corner Radio USA", url = "https://ais-sa2.cdnstream1.com/2447_192.mp3"},
    {name = "Radio Energyusa", url = "https://gmusto.radioca.st/mp3"},
    {name = "Al Quran Radio", url = "https://n0a.radiojar.com/0tpy1h0kxtzuv?rj-ttl=5&rj-tok=AAABhdgGORQA-2acfyF3_4WY2g"},
    {name = "100 Hip Hop And RNB FM", url = "https://ice64.securenetsystems.net/LFTM"},
    {name = "977 80S", url = "http://playerservices.streamtheworld.com/pls/977_80.pls"},
    {name = "977 90S", url = "http://playerservices.streamtheworld.com/pls/977_90.pls"},
    {name = "977 Comedy", url = "http://playerservices.streamtheworld.com/pls/977_COMEDY.pls"},
    {name = "977 Country", url = "http://playerservices.streamtheworld.com/pls/977_COUNTRY.pls"},
    {name = "977 Hitz", url = "http://playerservices.streamtheworld.com/pls/977_HITS.pls"},
    {name = "977 Jamz", url = "http://playerservices.streamtheworld.com/pls/977_JAMZ.pls"},
    {name = "977 Oldies", url = "http://playerservices.streamtheworld.com/pls/977_OLDIES.pls"},
    {name = "977 Smooth Jazz", url = "http://playerservices.streamtheworld.com/pls/977_SMOOJAZZ.pls"},
    {name = "977 The Mix", url = "http://playerservices.streamtheworld.com/pls/977_MIX.pls"},
    {name = "The Mighty1290 GLI", url = "https://streaming.live365.com/a33394"},
    {name = "𝕎𝕏𝔻𝕁 𝔼𝕃 ℕ𝕌𝔼𝕍𝕆 ℤ𝕆𝕃 𝟙𝟘𝟞𝟟", url = "https://liveaudio.lamusica.com/MIA_WXDJ_icy"},
    {name = "#1 HITS 80S", url = "https://makri.cdnstream.com/1898_128"},
    {name = "011FM - Holiday Instrumental", url = "http://listen.011fm.com/stream33"},
    {name = "011FM - Smooth Jazz", url = "https://listen.011fm.com/stream23"},
    {name = "011FM - The Office Mix", url = "https://listen.011fm.com/stream01"},
    {name = "011FM - Todays Country", url = "http://listen.011fm.com/stream09"},
    {name = "1 Classic", url = "http://listen.radionomy.com/1classic"},
    {name = "1FM", url = "http://sc8.1.fm:7030/"},
    {name = "100 Chill Radio", url = "https://chill.100radios.net/"},
    {name = "100 Hitradio", url = "https://radio1.streamserver.link/radio/8010/100hit-aac"},
    {name = "100 XR", url = "https://xr.dockl.com/stream"},
    {name = "1001 Jack FM", url = "https://player.listenlive.co/68631/en"},
    {name = "1001 The Beat", url = "https://stream.revma.ihrhls.com/zc2069"},
    {name = "1001 WCLG", url = "http://live.amperwave.net/direct/bowers-wclgfmaac-imc1"},
    {name = "1003 Big", url = "https://stream.revma.ihrhls.com/zc2505/hls.m3u8?streamid=2505&zip=20779&at=0&birthYear=null&clientType=web&fb_broadcast=0&host=webapp.US&init_id=8169&modTime=1625981235400&pname=OrganicWeb&profileid=1563075259&territory=US&uid=e12ed9af-25e3-44c8-8473-18fe98723481&age=null&gender=null&aw_0_1st.playerid=iHeartRadioWebPlayer&aw_0_1st.skey=1625981235&terminalid=159&companionAds=true&playedFrom=6&us_privacy=1-N-&callLetters=WBIG-FM&devicename=web-desktop&stationid=2505&dist=iheart&aw_0_1st.ccaud="},
    {name = "1003 Jack FM", url = "https://live.amperwave.net/direct/audacy-kjkkfmaac-imc"},
    {name = "1003 KISS FM", url = "https://stream.revma.ihrhls.com/zc1629"},
    {name = "1003 The Beat", url = "https://stream.revma.ihrhls.com/zc1289/hls.m3u8"},
    {name = "1003 The Bus", url = "https://stream.revma.ihrhls.com/zc2744"},
    {name = "1003 The Edge", url = "https://ample.revma.ihrhls.com/zc89/11_1v7zzn0xnejsy02/playlist.m3u8?zip=&streamid=89&pname=live_profile&companionAds=false&dist=iheart&terminalId=159&deviceName=web-mobile&aw_0_1st.playerid=iHeartRadioWebPlayer&listenerId=&clientType=web&profileId=6952492483&aw_0_1st.skey=6952492483&host=webapp.US&playedFrom=157&stationid=89&territory=US"},
    {name = "1003 The Edge KDJE", url = "http://stream.revma.ihrhls.com/zc89"},
    {name = "1003 The Peak", url = "https://stream.revma.ihrhls.com/zc1389"},
    {name = "1003 The River - WQRV - Meridianvillehuntsville, AL", url = "https://stream.revma.ihrhls.com/zc21"},
    {name = "1003 WHEB", url = "https://stream.revma.ihrhls.com/zc1353"},
    {name = "1003 WKIT", url = "https://ice6.securenetsystems.net/WKIT"},
    {name = "1003 WNIC", url = "https://stream.revma.ihrhls.com/zc1153?streamid=1153"},
    {name = "1005 FM", url = "https://stream.revma.ihrhls.com/zc973"},
    {name = "1005 The Fox", url = "https://stream.revma.ihrhls.com/zc2938/hls.m3u8"},
    {name = "1007 KGBI", url = "https://nwmedia-kgbi.streamguys1.com/kgbi-mp3"},
    {name = "1007 KGMO THE Classic Rock Station", url = "https://ice.wbcengineering.com:8106/stream"},
    {name = "1007 KKRQ The Fox", url = "https://stream.revma.ihrhls.com/zc2812"},
    {name = "1007 Mix", url = "https://stream.revma.ihrhls.com/zc689/hls.m3u8"},
    {name = "1007 The Bay", url = "https://ais-sa1.streamon.fm/7225_48k.aac"},
    {name = "1007 WMMS", url = "https://stream.revma.ihrhls.com/zc1741"},
    {name = "1007 WZLX", url = "https://stream.revma.ihrhls.com/zc7730"},
    {name = "1009 FM The Hill", url = "https://audio-edge-qse4n.yyz.g.radiomast.io/e503838e-de07-476b-a4e3-6cf146915584"},
    {name = "1009 POWER", url = "https://stream.revma.ihrhls.com/zc6469"},
    {name = "1001 BEST COVERS", url = "https://stream.zeno.fm/quf5vwjtsdxtv"},
    {name = "1001 NATURE SOUNDS", url = "http://stream.zeno.fm/kju0gtjeei3uv"},
    {name = "100Hitz - 90'S Alternative", url = "http://pureplay.cdnstream1.com/6040_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1OTE4NiwiaXNzIjoidGlzcnYifQ.MLF0T_JezQR4rG8wAnSmznCEsw4KL1TECaKnS2rV2fw%22"},
    {name = "100Hitz - 90'S Hitz", url = "http://pureplay.cdnstream1.com/6056_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1ODgyMywiaXNzIjoidGlzcnYifQ.p0ux4zgs6Xj7dhIr3EqVlXAiEOTKtY7snGxgD55apOM"},
    {name = "100Hitz - 90S Alternative Hitz", url = "http://pureplay.cdnstream1.com/6040_64.aac/playlist.m3u8"},
    {name = "100Hitz - Alternative", url = "https://pureplay.cdnstream1.com/6034_128.mp3"},
    {name = "100Hitz - Alternative Hitz", url = "https://pureplay.cdnstream1.com/6034_64.aac/playlist.m3u8"},
    {name = "100Hitz - Hip Hop", url = "http://pureplay.cdnstream1.com/6042_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1NzMwMSwiaXNzIjoidGlzcnYifQ.304XDmX1AZJCylkYdV5G8PlaYlNeCUPPYQBcPiVox7I"},
    {name = "100Hitz - Indie", url = "http://206.217.213.236:8360/;stream"},
    {name = "100Hitz - Indie Rock", url = "http://pureplay.cdnstream1.com/6056_64.aac?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1ODAzMywiaXNzIjoidGlzcnYifQ.iRK4czQtolWgtNsj8Uy5lioP0EoZu1wCuvj2VwsCs3o"},
    {name = "100Hitz - Rock", url = "http://pureplay.cdnstream1.com/6036_64.aac?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1ODMwOSwiaXNzIjoidGlzcnYifQ.8uFrLWMHqAB47XrnGAR6efpR1sAYafRsPfFz-EXglmQ"},
    {name = "100Hitz - Top 40", url = "http://gr02.cdnstream.com:8300/;stream/1"},
    {name = "100Hitz - Urban Hitz", url = "http://pureplay.cdnstream1.com/6043_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1ODUzMywiaXNzIjoidGlzcnYifQ.uR3Z5-tMJDskTZ3Rp6u3qmXtCUgZM_7DP0ged5SwRvU"},
    {name = "100Hitz Hot Hitz", url = "http://pureplay.cdnstream1.com/6027_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1NjY1OSwiaXNzIjoidGlzcnYifQ.qFjTFowI3sAHS4IFwRsz-zxLYbgTlfZFse1AtCH642s"},
    {name = "100Hitz The Mix - 80S 90S Today'S Hits", url = "http://pureplay.cdnstream1.com/6038_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1Nzc4NCwiaXNzIjoidGlzcnYifQ.pcgS3hF5YBvvbD9rJO3OMBWPgEGE037nPVwPu4hamPY%22"},
    {name = "100Hitz Today'S New Country", url = "http://pureplay.cdnstream1.com/6030_128.mp3?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzk1NzY0NiwiaXNzIjoidGlzcnYifQ.egsO64un0_ERf_GWzA1GBpsRrgkssRZtYIxOkwbEMp8"},
    {name = "101 ESPN", url = "https://provisioning.streamtheworld.com/pls/WXOSFM.pls"},
    {name = "101 Smooth Jazz", url = "http://listen.radionomy.com/101smoothjazz.m3u"},
    {name = "101 SMOOTH JAZZ MELLOW MIX", url = "http://www.101smoothjazz.com/101-mellowmix.m3u"},
    {name = "101 SMOOTH JAZZ WEST", url = "http://www.101smoothjazz.com/101-smoothjazz.m3u"},
    {name = "101 The Fox", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KCFXFMAAC.aac"},
    {name = "1011 WNOE", url = "https://stream.revma.ihrhls.com/zc1045"},
    {name = "1013 KDWB", url = "https://ample.revma.ihrhls.com/zc1201/73_mjuuisvr6gbl02/playlist.m3u8"},
    {name = "1013 WKRD - Rockford'S Best Mix", url = "http://ice24.securenetsystems.net/WRKD"},
    {name = "1015 Bob Rocks", url = "https://ais-sa8.cdnstream1.com/3526_128.mp3"},
    {name = "1015 Hank FM", url = "https://ais-sa1.streamon.fm/7169_48k.aac"},
    {name = "1015 KGB", url = "https://stream.revma.ihrhls.com/zc237"},
    {name = "1015 KPLA", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KPLAFMAAC.aac"},
    {name = "1015 The River", url = "https://ample.revma.ihrhls.com/zc1853/19_1n3b2kyukilj602/playlist.m3u8?zip=&streamid=1853&pname=live_profile&companionAds=false&dist=iheart&terminalId=159&deviceName=web-mobile&aw_0_1st.playerid=iHeartRadioWebPlayer&listenerId=&clientType=web&profileId=6319548085&aw_0_1st.skey=6319548085&host=webapp.US&playedFrom=157&stationid=1853&territory=US"},
    {name = "1015 WIBA FM", url = "https://stream.revma.ihrhls.com/zc3466"},
    {name = "1015 WYNK", url = "https://stream.revma.ihrhls.com/zc1021"},
    {name = "1017 KSAM", url = "https://ice23.securenetsystems.net/KSAM"},
    {name = "1017 The Bull", url = "https://stream.revma.ihrhls.com/zc6586"},
    {name = "1019 KISS FM", url = "https://stream.revma.ihrhls.com/zc4864"},
    {name = "1019 The Bull", url = "https://live.amperwave.net/manifest/townsquare-katpfmaac-ibc3"},
    {name = "1019 The Horn Austin Sports Talk", url = "https://arn.leanstream.co/KTAEAM"},
    {name = "1019 The Rock", url = "https://live.amperwave.net/manifest/townsquare-wozifmaac-ibc3"},
    {name = "1019 The Twister", url = "https://stream.revma.ihrhls.com/zc1913"},
    {name = "1010 KSIR", url = "http://alpha.newerastreaming.com:8016/;"},
    {name = "1010 WINS 923 FM", url = "https://live.amperwave.net/direct/audacy-winsamaac-imc"},
    {name = "1010 XL", url = "https://ice23.securenetsystems.net/WJXL"},
    {name = "1011 The Beat", url = "https://stream.revma.ihrhls.com/zc2153"},
    {name = "102 Jams", url = "https://live.amperwave.net/manifest/audacy-krbqfmaac-hlsc.m3u8"},
    {name = "1021 The Fox", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WMXTFMAAC.aac"},
    {name = "1021 WDRM - Decaturhuntsville, AL", url = "https://stream.revma.ihrhls.com/zc13"},
    {name = "1023 Blake FM", url = "https://live.amperwave.net/manifest/townsquare-kwfsfmaac-ibc3"},
    {name = "1023 The Beat", url = "https://stream.revma.ihrhls.com/zc2169"},
    {name = "1023 The Rocket", url = "https://ice23.securenetsystems.net/WZDQ"},
    {name = "1025 Jack FM", url = "https://playerservices.streamtheworld.com/pls/KCMOH2.pls"},
    {name = "1025 KZOK", url = "https://stream.revma.ihrhls.com/zc7787"},
    {name = "1025 WFMF", url = "https://stream.revma.ihrhls.com/zc1005"},
    {name = "1027 Jack-Fm", url = "https://stream.revma.ihrhls.com/zc4330"},
    {name = "1027 KIIS FM", url = "https://stream.revma.ihrhls.com/zc185"},
    {name = "1027 KIIS FM Los Angeles", url = "http://stream.revma.ihrhls.com/zc185"},
    {name = "1027 KISS FM WEGR Memphis", url = "http://stream.revma.ihrhls.com/zc2133"},
    {name = "1027 WEBN", url = "https://stream.revma.ihrhls.com/zc1701"},
    {name = "1029 KBLX HD3: Praise Bay Area", url = "https://bonneville.cdnstream1.com/2775_48.aac?aw_0_1st.playerid=Tuner"},
    {name = "1029 NOW", url = "https://stream.revma.ihrhls.com/zc2237"},
    {name = "1029 The Lake", url = "https://stream.revma.ihrhls.com/zc1609"},
    {name = "1029 Wkik Country", url = "https://www.streamvortex.com:8444/s/11020"},
    {name = "103 JAMZ", url = "https://stream.revma.ihrhls.com/zc2453"},
    {name = "103 She", url = "http://sheradio1055.com/ListenLive.m3u"},
    {name = "1031 Jack FM", url = "https://ice24.securenetsystems.net/KDAA"},
    {name = "1031 KCDA", url = "https://stream.revma.ihrhls.com/zc2589"},
    {name = "1031 The Wave", url = "https://ais-sa3.cdnstream1.com/2284_96.aac"},
    {name = "1031 WZLO", url = "https://ice8.securenetsystems.net/WZLO"},
    {name = "1033 Asheville FM", url = "https://listen.ashevillefm.org/stream"},
    {name = "1033 Country", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WKDFFMAAC"},
    {name = "1033 Ed-Fm", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KDRFFMAAC.aac"},
    {name = "1033 Lite FM", url = "https://ice9.securenetsystems.net/KLGN"},
    {name = "1033 The Range", url = "https://nebcoradio.com:1010/KRAN"},
    {name = "1033 WZND FUZED RADIO", url = "https://26433.live.streamtheworld.com/WZNDFM.mp3"},
    {name = "1035 1029 The Vault", url = "https://ice66.securenetsystems.net/WJKI"},
    {name = "1035 KISS FM - WKSC-FM Chicago", url = "https://stream.revma.ihrhls.com/zc849"},
    {name = "1035 KISS FM WKSC Chicago", url = "http://stream.revma.ihrhls.com/zc849"},
    {name = "1035 The Arrow KRSP-FM", url = "https://bonneville.cdnstream1.com/2700_48.aac"},
    {name = "1035 The Game KGA", url = "https://ice6.securenetsystems.net/KGA"},
    {name = "1035 WEZL", url = "https://stream.revma.ihrhls.com/zc2061"},
    {name = "1035 WGRR", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WGRRFMAAC.aac"},
    {name = "1035 WRBO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WRBOFMAAC.aac"},
    {name = "1037 The Buzz", url = "https://signalmedia.streamguys1.com/signalmedia/kabz-aac"},
    {name = "1037 The Game", url = "https://ice6.securenetsystems.net/KLWB"},
    {name = "1037 The Oasis", url = "https://ice42.securenetsystems.net/KOAZAM?playSessionID=EE67F132-DB59-0E2B-D5F260EC5335C908"},
    {name = "1037 The Q - WQEN - Trussvillebirmingham, AL", url = "https://stream.revma.ihrhls.com/zc3093"},
    {name = "1037 WMGM", url = "https://us2.maindigitalstream.com/ssl/WMGM"},
    {name = "1039 The Bulldog", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WXKQFM.mp3?dist=onlineradiobox"},
    {name = "1039 WYAB", url = "http://www.wyab.com:81/stream"},
    {name = "1035 KTU The Beat Of New York", url = "http://ample.revma.ihrhls.com/zc1473"},
    {name = "1041 KRBE", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KRBEFMAAC.aac"},
    {name = "1041 The Edge", url = "https://stream.revma.ihrhls.com/zc1397"},
    {name = "1041 The Spot", url = "https://stream.revma.ihrhls.com/zc1041"},
    {name = "1043 Hallelujah FM", url = "https://stream.revma.ihrhls.com/zc4892"},
    {name = "1043 Hitfm", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XHTO_FMAAC.aac"},
    {name = "1045 Latino Hits", url = "https://stream.revma.ihrhls.com/zc4051"},
    {name = "1045 Radio Latina", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/XLTNFM_SC"},
    {name = "1045 WRVR Memphis", url = "https://live.amperwave.net/manifest/audacy-wrvrfmaac-hlsc.m3u8"},
    {name = "1047 KCLD", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KCLDAAC.aac"},
    {name = "1047 Mi Preferida", url = "https://ice7.securenetsystems.net/KNIV"},
    {name = "1047 WNOK", url = "https://stream.revma.ihrhls.com/zc2081"},
    {name = "1047 WTUE", url = "https://stream.revma.ihrhls.com/zc1785"},
    {name = "1049 Funasia", url = "https://funasia.streamguys1.com/live-1"},
    {name = "1049 Max Country", url = "https://ais-sa1.streamon.fm/7246_48k.aac"},
    {name = "1049 The Hawk", url = "https://ice7.securenetsystems.net/WLKZ"},
    {name = "1049 The River", url = "http://stream.riverradio.com:8000/wcvofm.mp3"},
    {name = "1049 The River AAC", url = "http://stream.riverradio.com:8000/wcvofm.aac"},
    {name = "1043 Myfm", url = "https://stream.revma.ihrhls.com/zc173"},
    {name = "1051 FM WKCE", url = "https://stream.radiojar.com/q04ksted22quv"},
    {name = "1051 KNCI", url = "https://bonneville.cdnstream1.com/2617_48.aac?aw_0_1st.playerid=Tuner"},
    {name = "1051 The Bounce", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WMGCFMAAC.aac"},
    {name = "1051 The River", url = "https://stream.revma.ihrhls.com/zc1249"},
    {name = "1053 KZNN", url = "https://ice5.securenetsystems.net/KZNNFM"},
    {name = "1053 The Beat", url = "https://stream.revma.ihrhls.com/zc3256"},
    {name = "1053 WDAS FM", url = "https://stream.revma.ihrhls.com/zc1993"},
    {name = "1055 The X Factor", url = "https://crystalout.surfernetwork.com:8001/KXFC-FM_MP3"},
    {name = "1055 Triple M", url = "http://live.amperwave.net/direct/audacy-wmmmfmaac-imc"},
    {name = "1055 Triple M Madison WMMM-FM", url = "https://live.amperwave.net/direct/audacy-wmmmfmaac-imc"},
    {name = "1057 The Brew", url = "https://stream.revma.ihrhls.com/zc2946"},
    {name = "1057 The HOG", url = "http://69.8.162.164:8000/hog.mp3"},
    {name = "1057 The X Rocks", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WIXOFMAAC.aac"},
    {name = "1057 WAPL", url = "https://woodward-radio.streamb.live/SB00020?args=web_01&starttime=1702969916"},
    {name = "1059 FM WMAL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WMALFMAAC.aac"},
    {name = "1059 The Brew", url = "https://stream.revma.ihrhls.com/zc3540"},
    {name = "1059 The X WXDX", url = "https://stream.revma.ihrhls.com/zc2033"},
    {name = "1050 AM KTBL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KTBLAMAAC.aac"},
    {name = "106 WCOD", url = "https://stream.revma.ihrhls.com/zc6756"},
    {name = "1061 KISS FM Seattle", url = "https://stream.revma.ihrhls.com/zc4257"},
    {name = "1061 KISS-FM KHKS", url = "https://stream.revma.ihrhls.com/zc2245"},
    {name = "1061 The Breeze", url = "https://stream.revma.ihrhls.com/zc2001"},
    {name = "1063 NBZ-FM", url = "https://playoutonestreaming.com/proxy/wnbz?mp=/stream&_=244532"},
    {name = "1063 NBZ-FM WNBZ Plattsburgh, NY", url = "https://playoutonestreaming.com/proxy/wnbz?mp=/stream"},
    {name = "1065 860 WNOV", url = "https://crystalout.surfernetwork.com:8001/WNOV-AM_MP3"},
    {name = "1065 The END", url = "https://stream.revma.ihrhls.com/zc1597"},
    {name = "1067 The Beat", url = "https://stream.revma.ihrhls.com/zc3632"},
    {name = "1067 The Bull", url = "https://stream.revma.ihrhls.com/zc7784"},
    {name = "1067 The Krewe", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KKNDFMAAC.aac"},
    {name = "1067 WLLZ", url = "https://stream.revma.ihrhls.com/zc1137"},
    {name = "1069 The Eagle", url = "https://ice9.securenetsystems.net/KEGK"},
    {name = "1069 The Light", url = "https://ais-sa8.cdnstream1.com/2815_96.aac?listenerId=esTrackblock0202518&aw_0_1st.playerid=esPlayer&aw_0_1st.skey=1700590934"},
    {name = "1069 The Q", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KVGQFMAAC.aac"},
    {name = "1069 The Ranch", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KRVFFMAAC.aac"},
    {name = "107 WANS", url = "http://hemnos.cdnstream.com/1442_128"},
    {name = "1071 A1A", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WAOAFMAAC.aac"},
    {name = "1071 FM WTDK", url = "http://stream.abacast.net/direct/wboc-wtdkfmaac-ibc2"},
    {name = "1071 The Peak NY", url = "http://ais-sa1.streamon.fm/7836_128k.aac"},
    {name = "1071 The X", url = "http://sc1.reignradio.net:9302/"},
    {name = "1073 Alternative - Cleveland, Ohio", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WNWVFMAAC_SC"},
    {name = "1073 The Outlaw", url = "https://provisioning.streamtheworld.com/pls/THE_OUTLAWAAC.pls"},
    {name = "1073 The Vibe", url = "https://playerservices.streamtheworld.com/pls/KMJKFM.pls"},
    {name = "1075 KISS FM", url = "https://stream.revma.ihrhls.com/zc2740"},
    {name = "1075 The Game", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WNKTFMAAC.aac"},
    {name = "1075 WGCI", url = "https://stream.revma.ihrhls.com/zc841"},
    {name = "1079 FM “The Bull”", url = "https://ais-sa1.streamon.fm/7283_48k.aac"},
    {name = "1079 KBPI", url = "https://stream.revma.ihrhls.com/zc373"},
    {name = "1079 The Fox", url = "https://ice3.securenetsystems.net/KPFX"},
    {name = "1079 The Mix", url = "https://stream.radio.co/s5c993fa61/listen"},
    {name = "1079 The Mix WNTR", url = "https://playerservices.streamtheworld.com/pls/WNTRFM.pls"},
    {name = "1070 WDIA", url = "https://stream.revma.ihrhls.com/zc2129"},
    {name = "1090 KJR", url = "https://stream.revma.ihrhls.com/zc7747"},
    {name = "10Dash20", url = "http://ice55.securenetsystems.net/DASH52"},
    {name = "1110 KFAB", url = "https://stream.revma.ihrhls.com/zc1325"},
    {name = "113FM - Awesome 80S", url = "http://listen.113.fm/awesome80s.m3u"},
    {name = "113FM - Indie Nation", url = "https://113fm-atunwadigital.streamguys1.com/1047"},
    {name = "113FM Big Kickin Country", url = "https://113fm-atunwadigital.streamguys1.com/1004"},
    {name = "113FM Elevator", url = "http://113fm-atunwadigital.streamguys1.com/1010"},
    {name = "113Fm Legends Of Country", url = "https://113fm-atunwadigital.streamguys1.com/1073?aw_0_1st.playerid=SGplayer&aw_0_1st.skey=1714719945670&awparams=playerid%3ASGplayer%3B"},
    {name = "1200 WOAI Talk Radio", url = "https://stream.revma.ihrhls.com/zc2361/hls.m3u8"},
    {name = "1250 WTMA", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WTMAAMAAC.aac"},
    {name = "1260 KYA Golden Gate Great Oldies", url = "https://pavo.prostreaming.net:2020/tunein/8038/stream/pls"},
    {name = "1310 KGLB", url = "https://ice5.securenetsystems.net/KGLB"},
    {name = "1330 1015 WHBL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WHBLAMAAC.aac"},
    {name = "1340 The Fan 3", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WIFNAM.mp3"},
    {name = "1340 The Game", url = "https://stream.revma.ihrhls.com/zc3066"},
    {name = "1370 KWRT", url = "https://ic1.sslstream.com/kwrt-am"},
    {name = "1380 KCIM", url = "https://ice5.securenetsystems.net/KCIM"},
    {name = "1390 WNIO", url = "https://stream.revma.ihrhls.com/zc2760"},
    {name = "1440 WNFL", url = "https://mwc.streamguys1.com/wnfl-aac"},
    {name = "1450 961 The Big X", url = "https://ice66.securenetsystems.net/WXVW"},
    {name = "1460 AM Deportes Vegas", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KENOAM.mp3"},
    {name = "1460 ESPN Deportes", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KENOAMAAC.aac"},
    {name = "1460 KXNO", url = "https://stream.revma.ihrhls.com/zc921"},
    {name = "1490 WMRN", url = "https://stream.revma.ihrhls.com/zc1829"},
    {name = "1560 The Franchise 2", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KEBCAMAAC.aac"},
    {name = "1580 Hiphop On Dash", url = "http://ice55.securenetsystems.net/DASH11"},
    {name = "1580 The Fanatic", url = "https://ice41.securenetsystems.net/KQFN"},
    {name = "1650 The Fan", url = "https://ice23.securenetsystems.net/KCNZ"},
    {name = "181 Fm The Beat", url = "http://www.181.fm/stream/pls/181-beat.pls"},
    {name = "181FM - 80'S Country", url = "http://listen.181fm.com/181-80scountry_128k.mp3"},
    {name = "181FM - 80'S Hairband", url = "http://www.181.fm/stream/pls/181-hairband.pls"},
    {name = "181FM - 90'S Alternative", url = "http://www.181.fm/stream/pls/181-90salt.pls"},
    {name = "181FM - 90'S Country", url = "http://www.181.fm/stream/pls/181-90scountry.pls"},
    {name = "181FM - 90'S Dance", url = "http://www.181.fm/stream/pls/181-90sdance.pls"},
    {name = "181FM - Acid Jazz", url = "http://www.181.fm/stream/pls/181-acidjazz.pls"},
    {name = "181FM - Awesome 80'S", url = "http://www.181.fm/stream/pls/181-awesome80s.pls"},
    {name = "181FM - Beatles", url = "http://www.181.fm/stream/pls/181-beatles.pls"},
    {name = "181FM - Bebop Jazz", url = "http://www.181.fm/stream/pls/181-bebop.pls"},
    {name = "181FM - Chilled Out", url = "http://www.181.fm/stream/pls/181-chilled.pls"},
    {name = "181FM - Chilled Out USA 128K Mp3", url = "http://listen.181fm.com/181-chilled_128k.mp3"},
    {name = "181FM - Chloe@181Fm", url = "http://www.181.fm/stream/pls/181-chloe.pls"},
    {name = "181FM - Christmas Blender", url = "http://www.181.fm/stream/pls/181-xblender.pls"},
    {name = "181FM - Christmas Classics", url = "http://www.181.fm/stream/pls/181-xtraditional.pls"},
    {name = "181FM - Christmas Fun", url = "http://www.181.fm/stream/pls/181-xfun.pls"},
    {name = "181FM - Christmas Gospel", url = "http://www.181.fm/stream/pls/181-xgospel.pls"},
    {name = "181FM - Christmas Highway", url = "http://www.181.fm/stream/pls/181-xhighway.pls"},
    {name = "181FM - Christmas Kids", url = "http://www.181.fm/stream/pls/181-xkids.pls"},
    {name = "181FM - Christmas Kountry", url = "http://www.181.fm/stream/pls/181-xkkountry.pls"},
    {name = "181FM - Christmas Mix", url = "http://www.181.fm/stream/pls/181-xmix.pls"},
    {name = "181FM - Christmas Oldies", url = "http://www.181.fm/stream/pls/181-xoldies.pls"},
    {name = "181FM - Christmas Power", url = "http://www.181.fm/stream/pls/181-xpower.pls"},
    {name = "181FM - Christmas RB", url = "http://www.181.fm/stream/pls/181-xtrue.pls"},
    {name = "181FM - Christmas Rock", url = "http://www.181.fm/stream/pls/181-xrock.pls"},
    {name = "181FM - Christmas Smooth Jazz", url = "http://www.181.fm/stream/pls/181-xsmooth.pls"},
    {name = "181FM - Christmas Soundtracks", url = "http://www.181.fm/stream/pls/181-xsoundtrax.pls"},
    {name = "181FM - Christmas Spirit", url = "http://www.181.fm/stream/pls/181-xspirit.pls"},
    {name = "181FM - Christmas Standards", url = "http://www.181.fm/stream/pls/181-xstandards.pls"},
    {name = "181FM - Christmas Swing", url = "http://www.181.fm/stream/pls/181-xswing.pls"},
    {name = "181FM - Classic Buzz Alt", url = "http://www.181.fm/stream/pls/181-classicbuzz.pls"},
    {name = "181FM - Classic Hits 181", url = "http://www.181.fm/stream/pls/181-greatoldies.pls"},
    {name = "181FM - Classical Guitar", url = "http://listen.livestreamingservice.com/181-classicalguitar_64k.aac"},
    {name = "181FM - Classical Jazz", url = "http://listen.181fm.com/181-classicaljazz_128k.mp3"},
    {name = "181FM - Classical Music", url = "http://www.181.fm/stream/pls/181-classical.pls"},
    {name = "181FM - Comedy Club", url = "http://www.181.fm/stream/pls/181-comedy.pls"},
    {name = "181FM - Energy 93 Euro EDM", url = "http://www.181.fm/stream/pls/181-energy93.pls"},
    {name = "181FM - Energy 98", url = "http://listen.181fm.com/181-energy98_128k.mp3"},
    {name = "181FM - Front Porch Bluegrass", url = "http://www.181.fm/stream/pls/181-frontporch.pls"},
    {name = "181FM - Fusion Jazz", url = "http://www.181.fm/stream/pls/181-fusionjazz.pls"},
    {name = "181FM - Good Time Oldies Radio", url = "http://listen.181fm.com/181-goodtime_128k.mp3"},
    {name = "181FM - Highway 181", url = "http://www.181.fm/stream/pls/181-highway.pls"},
    {name = "181FM - Jammin 181", url = "http://www.181.fm/stream/pls/181-jammin.pls"},
    {name = "181FM - Kickin' Country", url = "http://www.181.fm/stream/pls/181-kickincountry.pls"},
    {name = "181FM - Lite 80'S", url = "http://www.181.fm/stream/pls/181-lite80s.pls"},
    {name = "181FM - Lite 90'S", url = "http://www.181.fm/stream/pls/181-lite90s.pls"},
    {name = "181FM - Mellow Gold", url = "http://www.181.fm/stream/pls/181-mellow.pls"},
    {name = "181FM - Old School Hiphoprnb", url = "http://listen.181fm.com/181-oldschool_128k.mp3"},
    {name = "181FM - Party 181", url = "http://www.181.fm/stream/pls/181-party.pls"},
    {name = "181FM - Power 181 Top 40", url = "http://www.181.fm/stream/pls/181-power.pls"},
    {name = "181FM - Real Country", url = "http://www.181.fm/stream/pls/181-realcountry.pls"},
    {name = "181FM - Reggae Roots", url = "http://www.181.fm/stream/pls/181-reggae.pls"},
    {name = "181FM - Rock 181", url = "http://www.181.fm/stream/pls/181-rock.pls"},
    {name = "181FM - Rock 40 Rock Roll", url = "http://www.181.fm/stream/pls/181-rock40.pls"},
    {name = "181FM - Salsa", url = "http://www.181.fm/stream/pls/181-salsa.pls"},
    {name = "181FM - Smooth AC", url = "http://www.181.fm/stream/pls/181-smoothac.pls"},
    {name = "181FM - Soul", url = "http://www.181.fm/stream/pls/181-soul.pls"},
    {name = "181FM - Star 90'S", url = "http://www.181.fm/stream/pls/181-star90s.pls"},
    {name = "181FM - Super 70S", url = "http://www.181.fm/stream/pls/181-70s.pls"},
    {name = "181FM - Techno Club", url = "http://www.181.fm/stream/pls/181-technoclub.pls"},
    {name = "181FM - The Ball", url = "http://www.181.fm/stream/pls/181-ball.pls"},
    {name = "181FM - The Box Urban", url = "http://www.181.fm/stream/pls/181-thebox.pls"},
    {name = "181FM - The Breeze", url = "http://www.181.fm/stream/pls/181-breeze.pls"},
    {name = "181FM - The Buzz Alt Rock", url = "http://www.181.fm/stream/pls/181-buzz.pls"},
    {name = "181FM - The Eagle Classic", url = "http://www.181.fm/stream/pls/181-eagle.pls"},
    {name = "181FM - The Heart Love Songs", url = "http://www.181.fm/stream/pls/181-heart.pls"},
    {name = "181FM - The Mix", url = "http://www.181.fm/stream/pls/181-themix.pls"},
    {name = "181FM - The Office", url = "http://www.181.fm/stream/pls/181-office.pls"},
    {name = "181FM - The Point", url = "http://www.181.fm/stream/pls/181-thepoint.pls"},
    {name = "181FM - The Rock Hardrock", url = "http://www.181.fm/stream/pls/181-hardrock.pls"},
    {name = "181FM - The Vibe Of Vegas", url = "http://www.181.fm/stream/pls/181-vibe.pls"},
    {name = "181FM - Trance Jazz", url = "http://www.181.fm/stream/pls/181-trancejazz.pls"},
    {name = "181FM - True Blues", url = "http://www.181.fm/stream/pls/181-blues.pls"},
    {name = "181FM - True RB", url = "http://www.181.fm/stream/pls/181-rnb.pls"},
    {name = "181FM - UK Top 40", url = "http://www.181.fm/stream/pls/181-uktop40.pls"},
    {name = "181FM - Vocal Jazz", url = "http://www.181.fm/stream/pls/181-vocals.pls"},
    {name = "181FM 80S RB", url = "http://listen.livestreamingservice.com/181-80srnb_64k.aac"},
    {name = "181FM 90S Dance", url = "http://listen.livestreamingservice.com/181-90sdance_128k.mp3"},
    {name = "181FM 90S RB", url = "http://listen.livestreamingservice.com/181-90srnb_128k.mp3"},
    {name = "181FM Classical Music", url = "http://listen.livestreamingservice.com/181-classical_128k.mp3"},
    {name = "181Fm Good Time Oldies", url = "https://listen.181fm.com/181-goodtime_128k.mp3"},
    {name = "181FM Super 70'S", url = "http://listen.livestreamingservice.com/181-70s_128k.mp3"},
    {name = "181Fm The Beat", url = "http://listen.livestreamingservice.com/181-beat_64k.aac"},
    {name = "181Fm The Buzz", url = "http://listen.livestreamingservice.com/181-buzz_64k.aac"},
    {name = "181FM The Office", url = "http://listen.livestreamingservice.com/181-office_64k.aac"},
    {name = "181Fm UK Top 40", url = "http://listen.livestreamingservice.com/181-uktop40_64k.aac"},
    {name = "1980Sfm", url = "http://hi5.1980s.fm/;stream.mp3"},
    {name = "1AM Radio", url = "http://ice55.securenetsystems.net/DASH75"},
    {name = "1RADIOSPACE 247", url = "http://c22.radioboss.fm/playlist/118/1RADIO.SPACE.m3u"},
    {name = "2000 FM - Alternative Rock", url = "http://bigrradio.cdnstream1.com/5101_128"},
    {name = "2000 FM - Chillin", url = "http://bigrradio.cdnstream1.com/5102_128"},
    {name = "2000 FM - Country", url = "http://bigrradio.cdnstream1.com/5103_128"},
    {name = "2000 FM - Hard Rock", url = "http://bigrradio.cdnstream1.com/5104_128"},
    {name = "2000 FM - Rnb Hip-Hop", url = "http://bigrradio.cdnstream1.com/5105_128"},
    {name = "2000 FM - Top 40", url = "http://bigrradio.cdnstream1.com/5106_128"},
    {name = "2000'S Country Music Radio", url = "https://2.mystreaming.net/uber/cmr00scountry/icecast.audio"},
    {name = "202Fm 020 Alternative", url = "http://listen.livestreamingservice.com/181-buzz_128k.mp3"},
    {name = "202Fm 90'S Alternative", url = "http://listen.livestreamingservice.com:8052/"},
    {name = "22 West Radio", url = "https://16603.live.streamtheworld.com/22WESTRADIOONLINEAAC.aac"},
    {name = "24-7 The ‘80S", url = "http://antares.dribbcast.com:4424/stream"},
    {name = "247 - Dance", url = "https://ip39.ip-178-33-37.eu/radio/8010/radio.mp3"},
    {name = "247 Christmas Music Radio Station", url = "http://streaming.live365.com/a29903"},
    {name = "247 Christmas Music Radio Station MP3", url = "http://ais-edge101-live365-dal02.cdnstream.com/a29903"},
    {name = "247 Comedy", url = "https://stream.revma.ihrhls.com/zc4902"},
    {name = "247 Polka Heaven", url = "http://192.99.83.149:8046/stream/;"},
    {name = "247 Mixing", url = "https://listen.radioking.com/radio/558131/stream/617633"},
    {name = "2Unes Wave Jazz", url = "http://login.webinternetradio.com:1320/stream"},
    {name = "300 Live Niagara Radio", url = "https://streaming.live365.com/a60417"},
    {name = "305 MI RADIO", url = "https://cast3.my-control-panel.com/proxy/305miradio/stream"},
    {name = "365FM The Vibe", url = "https://cast1.asurahosting.com/proxy/lowell/stream"},
    {name = "3ABN Music Channel", url = "https://war.streamguys1.com:7185/MC01"},
    {name = "3ABN Music Channel Non SSL", url = "http://war.str3am.com:7180/MC01"},
    {name = "3ABN Radio", url = "http://war.str3am.com:7180/live"},
    {name = "3WZ", url = "https://ice9.securenetsystems.net/WZWW"},
    {name = "40 Dias Por La Vida", url = "https://play10.tikast.com:20043/;"},
    {name = "4680Q", url = "https://s7.voscast.com:10017/stream"},
    {name = "4U 70S Flower", url = "https://streamingp.shoutcast.com/4U-70s"},
    {name = "4U Classic Rock", url = "https://str4uice.streamakaci.com/4uclassicrock.mp3"},
    {name = "4U Motown", url = "https://str4uice.streamakaci.com/4umotown.mp3"},
    {name = "4U Rock Live", url = "https://str4uice.streamakaci.com/4urocklive.mp3"},
    {name = "540 WRGC The River", url = "https://ice24.securenetsystems.net/WRGC"},
    {name = "55KRC", url = "https://stream.revma.ihrhls.com/zc1709"},
    {name = "590 KQNT", url = "https://stream.revma.ihrhls.com/zc4952"},
    {name = "60'S On Dash", url = "http://ice55.securenetsystems.net/DASH34"},
    {name = "600 WREC", url = "https://stream.revma.ihrhls.com/zc2145"},
    {name = "60NORTHRADIO", url = "http://r5.zetcast.net/flac"},
    {name = "60Sradio Mrgfm", url = "http://listen.mrg.fm:8020/stream"},
    {name = "61 Blues", url = "https://hts06.kshost.com.br:10182/live"},
    {name = "620 WTMJ", url = "https://live.amperwave.net/manifest/goodkarma-wtmjamaac-ibc"},
    {name = "670 KBOI", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KBOIAMAAC.aac"},
    {name = "680 The Fan", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WCNNAMAAC.aac"},
    {name = "695Therockcom", url = "http://radio.695therock.com:8000/stream.mp3"},
    {name = "6Forty Radio", url = "http://radio.6forty.com:8000/6forty.m3u"},
    {name = "70'S Hits DJ Jan The Man", url = "https://quincy.torontocast.com:2500/stream"},
    {name = "70'S On Dash", url = "http://ice55.securenetsystems.net/DASH26"},
    {name = "700 ESPN KXLX", url = "https://13743.live.streamtheworld.com/KXLXAMAAC.aac"},
    {name = "70S 80S Disco Funk Modernsoul Boogie", url = "https://discofunk.streamingmedia.it/usa"},
    {name = "70S All Hits", url = "http://ec4.yesstreaming.net:2270/"},
    {name = "70Sradio Mrgfm", url = "http://listen.mrg.fm:8030/stream"},
    {name = "760 AM The Gospel", url = "https://crystalout.surfernetwork.com:8001/WENO-AM_MP3"},
    {name = "770 KKOB", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KKOBAMAAC.aac"},
    {name = "777 FM", url = "http://stream.laut.fm/777fm.pls"},
    {name = "790 AM - KCAM Glennallen Alaska", url = "https://streams.radiomast.io/kcam"},
    {name = "790 KRD", url = "https://stream.revma.ihrhls.com/zc4836"},
    {name = "80 Love Classical", url = "https://strm112.1.fm/loveclassics_mobile_mp3"},
    {name = "80S 90S Mix - Bestnet Radio", url = "https://bigrradio.cdnstream1.com/5143_128"},
    {name = "80S America", url = "http://wallyjradio.com:8000/80sAmerica?1670287224820"},
    {name = "80S Central", url = "https://streaming.live365.com/a97972"},
    {name = "80S Metal FM - Bestnetradio", url = "http://bigrradio-edge1.cdnstream.com/5146_128"},
    {name = "80S Radio", url = "http://stream.zeno.fm/h5skggtacm8uv"},
    {name = "80Sradio Mrgfm", url = "http://listen.mrg.fm:8080/stream"},
    {name = "830 WEEU", url = "https://ais-sa2.cdnstream1.com/2350_128.mp3"},
    {name = "850 WFTL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WFTLAMAAC.aac"},
    {name = "870 AM KRLA", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KRLAAM.mp3"},
    {name = "881 WRFL Radio Free Lexington", url = "https://wrfl.fm/stream"},
    {name = "883 The Wind", url = "https://rtn.cdnstream1.com/2571_96.aac"},
    {name = "883FM WXOU", url = "http://wxou.oakland.edu:8000/;"},
    {name = "883FM WXOU Radio", url = "http://wxou.oakland.edu:8000/listen.m3u"},
    {name = "885 Chuck FM", url = "https://ice23.securenetsystems.net/CHUCKFM"},
    {name = "885 KQED", url = "https://streams.kqed.org/kqedradio?onsite=true"},
    {name = "885 WJIE", url = "https://ice7.securenetsystems.net/WJIE"},
    {name = "885 WRAS FM GPB", url = "https://gpb.streamguys1.com/gpb-atlanta-aac-website"},
    {name = "887 The Bridge", url = "https://ice66.securenetsystems.net/WKNZ2"},
    {name = "887 The Cross", url = "https://playoutonestreaming.com/proxy/kbmq?mp=/stream"},
    {name = "887 WICR - The Diamond", url = "https://live.amperwave.net/direct/univofindy-wicrhd1mp3-ibc4"},
    {name = "889 The Bridge", url = "https://www.streamvortex.com:8444/s/11390"},
    {name = "891 KCLC", url = "https://ice6.securenetsystems.net/KCLC?playSessionID=127F250F-FF15-4515-9A6B79F140F56918"},
    {name = "891 Ken'S FM", url = "http://108.59.11.81:8315/;"},
    {name = "893 - WZRD “The Wizard” Freeform Radio", url = "https://wzrd.streamguys1.com/live"},
    {name = "893 KSBJ", url = "https://ksbj.streamguys1.com/national/ksbj.aac"},
    {name = "893 WRKF", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WRKFFM.mp3"},
    {name = "895 Fm KBACH", url = "http://stream.kbaq.org/kbaq_mp3_128"},
    {name = "895 WMFV News", url = "https://wmfe-iad.streamguys1.com/wmfv"},
    {name = "897 KSGN", url = "https://ksgn.com/assets/audio/stream/aac"},
    {name = "899 FM WDVX East TN", url = "https://wdvx.streamguys1.com/live"},
    {name = "899 KUNM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KUNMFM_128.mp3"},
    {name = "899 WBRO", url = "https://s5.radio.co/s43adc6d7e/listen"},
    {name = "899 WDAV", url = "https://wdav-ice.streamguys1.com/live-mp3"},
    {name = "901 KPFT", url = "https://streams.pacifica.org:9000/live_64"},
    {name = "901 WMBT The Wombat", url = "https://s2.stationplaylist.com:7142/listen.mp3"},
    {name = "905 The Edge", url = "http://kvhs.smrn.com:5561/live"},
    {name = "905 Wes", url = "https://ais-sa3.cdnstream1.com/2556_128.mp3"},
    {name = "905 WICN Public Radio - Jazz+ For New England", url = "https://wicn-ice.streamguys1.com/live-mp3"},
    {name = "905 WKHS", url = "https://ic1.sslstream.com/wkhs-fm"},
    {name = "907 K-LOVE", url = "https://emf-hls.streamguys1.com/k-love-live-aac-64k/playlist.m3u8"},
    {name = "907 The Lion", url = "http://stream.radiojar.com/k9uw1tyr7x8uv"},
    {name = "907 WMFE-FM", url = "http://wmfe.iad.streamguys1.com/wmfe"},
    {name = "909 The Light", url = "https://ic.liberty.edu:8443/WQLU"},
    {name = "90'S Country Music Radio", url = "https://2.mystreaming.net/uber/cmr90scountry/icecast.audio"},
    {name = "90'S On Dash", url = "http://ice55.securenetsystems.net/DASH1"},
    {name = "90'S, 2000'S And Today'S Hits FMM Radiocom", url = "https://media.fmmradio.com/listen/todays_hits/radio.mp3"},
    {name = "90S Country", url = "https://stream.revma.ihrhls.com/zc6870"},
    {name = "90Sradio Mrgfm", url = "http://listen.mrg.fm:8050/stream"},
    {name = "91,5 Jazz And More", url = "https://kunv.oit.unlv.edu/stream/1/"},
    {name = "911 The Avenue", url = "http://ice5.securenetsystems.net/WOVM"},
    {name = "915 FAMILY LIFE RADIO", url = "https://icecast.streammyflr.org/FLRstream"},
    {name = "915 WBEZ-FM", url = "https://stream.wbez.org/wbez64-web.aac"},
    {name = "917 Equip FM", url = "https://ice66.securenetsystems.net/EQUIPFM?playSessionID=44ED3B1E-A57C-3532-23802CC6B00D9CFD"},
    {name = "917 KXT", url = "https://kera.streamguys1.com/kxtlive128"},
    {name = "917 NGEN", url = "https://ksbj.streamguys1.com/national/ngen.aac"},
    {name = "917 The Curve", url = "https://jasperhi.radioca.st/;"},
    {name = "917 WSHS-FM", url = "http://wpr-ice.streamguys.net/wpr-ideas-40"},
    {name = "919 KASU", url = "https://kasu.streamguys1.com/live?uuid=j2cw92p6i"},
    {name = "919 KSOI FM Southern Iowa Community Radio", url = "https://ais-edge104-live365-dal02.cdnstream.com/a01407"},
    {name = "919 KUDR", url = "http://kdurradio.fortlewis.edu/stream"},
    {name = "919 Positive Life Radio KGTS", url = "https://ice10.securenetsystems.net/PLR"},
    {name = "910 ESPN Billings KBLG", url = "https://desertmountainbroadcasting.streamguys1.com/KBLG"},
    {name = "910Am Detroit'S News Talk Superstation", url = "https://clouditize.piksel.tech/hls/live/2043189/ClouditizeStream2/playlist.m3u8"},
    {name = "92 KQRS", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KQRSFMAAC.aac"},
    {name = "92 PRO-FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WPROFMAAC.aac"},
    {name = "921 Hank FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KTFWFMAAC.aac"},
    {name = "921 The Beat", url = "https://stream.revma.ihrhls.com/zc2449"},
    {name = "921 The Ticket", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KQSMFMAAC.aac"},
    {name = "921 WSQV", url = "https://ice41.securenetsystems.net/WSQV"},
    {name = "923 NASH", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KRSTFMAAC.aac"},
    {name = "923 WCOL", url = "https://stream.revma.ihrhls.com/zc1757"},
    {name = "923 WXRK Charlottesville, VA", url = "https://ice64.securenetsystems.net/WXRK"},
    {name = "925 And 933 The Bull", url = "https://stream.revma.ihrhls.com/zc6168"},
    {name = "925 KJJY", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KJJYFMAAC.aac"},
    {name = "925 The Breeze", url = "https://stream.revma.ihrhls.com/zc4366"},
    {name = "925 The Fox", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WOFXFMAAC.aac"},
    {name = "925 The River", url = "https://nebcoradio.com:8443/WXRV"},
    {name = "927 WOBM", url = "https://live.amperwave.net/manifest/townsquare-wobmfmaac-ibc3"},
    {name = "929 KAT-FM Dubuque", url = "https://us9.maindigitalstream.com/ssl/katf"},
    {name = "929 KUZU", url = "http://138.197.2.189:8000/kuzu.mp3"},
    {name = "929 Peak FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KKPKFMAAC.aac"},
    {name = "929 Shooter FM", url = "https://ais-sa1.streamon.fm/7052_32k.aac"},
    {name = "929 The Bull", url = "https://live.amperwave.net/manifest/townsquare-kdblfmaac-ibc3"},
    {name = "929 The Grand", url = "https://24443.live.streamtheworld.com/CHTGFMAAC.aac?pname=StandardPlayerV4&pversion=4.19.2-042&dist=triton-web&tdsdk=js-2.9&swm=false&banners=300x250%2C728x90&burst-time=15&sbmid=ccb83d50-ac55-4f97-989e-6c170802ff9b"},
    {name = "929 TOM-FM", url = "https://ample.revma.ihrhls.com/zc469/7_l0p93yeajqk102/playlist.m3u8"},
    {name = "92Q Nashville", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WQQKFMAAC.aac"},
    {name = "92ZEW", url = "https://centova.rockhost.com/proxy/dotcompl?mp=/92zew"},
    {name = "931 AMOR Bachata Y Más", url = "https://liveaudio.lamusica.com/NY_WPAT_icy"},
    {name = "931 Jack FM", url = "https://ic1.sslstream.com/kwrt-fm"},
    {name = "931 KFBK 1530AM", url = "https://ample.revma.ihrhls.com/zc217/16_elstp0q9whne02/playlist.m3u8"},
    {name = "931 The Fan", url = "https://crystalout.surfernetwork.com:8001/WWSR-FM_MP3"},
    {name = "931 The Mountain", url = "https://stream.revma.ihrhls.com/zc1337"},
    {name = "931 WPOC", url = "https://stream.revma.ihrhls.com/zc1073"},
    {name = "933 FLZ", url = "http://stream.revma.ihrhls.com/zc681"},
    {name = "933 FM WXRH", url = "http://69.8.162.164:8000/hd3.mp3"},
    {name = "933 Jake FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KJKEFMAAC.aac"},
    {name = "933 La Raza Solo Idólos Con Música De Calidad", url = "https://liveaudio.lamusica.com/SF_KRZZ_icy"},
    {name = "933 The Beat", url = "https://stream.revma.ihrhls.com/zc517"},
    {name = "933 The Bus", url = "https://stream.revma.ihrhls.com/zc1761"},
    {name = "933 The Drive", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WPBGFM.mp3"},
    {name = "933 THE Q", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KOBQFMAAC.aac"},
    {name = "933 WBZD Classic Hits", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WBZDFMAAC.aac"},
    {name = "933 WTPT The Planet Rocks", url = "https://live.amperwave.net/manifest/audacy-wtptfmaac-hlsc.m3u8?source=aud-webplayer"},
    {name = "935 Chet FM", url = "https://ice23.securenetsystems.net/KDJF"},
    {name = "935 MAX - WMXQ - Maximum Classic Rock", url = "http://ice24.securenetsystems.net/WMXQ"},
    {name = "935 The Mix", url = "https://ice7.securenetsystems.net/THEMIX"},
    {name = "935 The Pirate", url = "http://sc2.spacialnet.com:33358/listen.pls"},
    {name = "935 WMWV", url = "https://crystalout.surfernetwork.com:8001/WMWV_MP3"},
    {name = "937 El Patron", url = "https://stream.revma.ihrhls.com/zc53"},
    {name = "937 El Patron Pura Música Perróna", url = "https://stream.revma.ihrhls.com/zc53/hls.m3u8"},
    {name = "937 Familia FM Seattle", url = "https://cast10.plugstreaming.com:2000/sslstream/famseattle"},
    {name = "937 Nash Icon", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WJBCFMAAC.aac"},
    {name = "937 The Ticket", url = "https://ice8.securenetsystems.net/KNTK"},
    {name = "939 KPDQ", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KPDQFMAAC.aac"},
    {name = "939 KSOU", url = "https://ice24.securenetsystems.net/KSOU"},
    {name = "939 Lite FM", url = "https://stream.revma.ihrhls.com/zc853"},
    {name = "930 AM WKY ESPN Deportes", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WKYAMAAC.aac"},
    {name = "930 KOGA", url = "https://stream.revma.ihrhls.com/zc1317/hls.m3u8?streamid=1317"},
    {name = "93X", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KXXRFMAAC.aac"},
    {name = "94 Rock", url = "https://stream.revma.ihrhls.com/zc1405"},
    {name = "941 ROCK", url = "https://stream.revma.ihrhls.com/zc1405/hls.m3u8"},
    {name = "941 The Bear KJRB", url = "https://ice6.securenetsystems.net/KJRB"},
    {name = "941 The Beat", url = "https://stream.revma.ihrhls.com/zc805"},
    {name = "941 The Brand", url = "https://ais-sa1.streamon.fm/7244_48k.aac"},
    {name = "941 The VIBE", url = "http://69.8.162.164:8000/vibe.aac"},
    {name = "941 ZBQ - WZBQ - Carrolltontuscaloosa, AL", url = "https://stream.revma.ihrhls.com/zc3077"},
    {name = "943 FM The Talker", url = "http://ice6.securenetsystems.net/WTRW?&playSessionID=D0AB2839-9D72-BA7B-94094742B6E"},
    {name = "943 Nash Icon", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KAMOFMAAC.aac"},
    {name = "943 The Buck", url = "http://13.bteradio.com:9090/THEBUCK"},
    {name = "945 ESPN FM Milwaukee", url = "https://live.amperwave.net/manifest/goodkarma-wktifmaac-ibc2"},
    {name = "945 KSMB", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KSMBFMAAC.aac"},
    {name = "945 Mix FM", url = "http://www.ophanim.net:8970/live"},
    {name = "945 Roxy", url = "https://live.amperwave.net/manifest/olympiabroadcasters-krxyfmaac-ibc2"},
    {name = "947 Alternative Anchorage", url = "https://ice10.securenetsystems.net/KZND"},
    {name = "947 KUMU", url = "https://pacificmedia.cdnstream1.com/2783_64.aac"},
    {name = "947 KUMU 128Kbps", url = "https://pacificmedia.cdnstream1.com/2783_128.mp3"},
    {name = "947 The Block", url = "https://live.amperwave.net/direct/audacy-wxbkfmaac-imc"},
    {name = "947 The Brew", url = "https://stream.revma.ihrhls.com/zc1901"},
    {name = "949 FM Duluth-Superior 95 KQDS", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KQDSFMAAC_SC"},
    {name = "949 FM WKHI", url = "https://ice66.securenetsystems.net/WKHI"},
    {name = "949 HOM - The Best Mix Of The '80S, '90'S Today WHOM-FM", url = "https://live.amperwave.net/manifest/townsquare-whomfmaac-hlsc3.m3u8"},
    {name = "949 KCMO", url = "https://provisioning.streamtheworld.com/pls/KCMOFMAAC.pls"},
    {name = "949 News Now", url = "https://crystalout.surfernetwork.com:8001/WJJF-FM_MP3"},
    {name = "949 The Palm And 1230 AM", url = "https://live.amperwave.net/playlist/alphacorporate-warqhd4aac-ibc4.pls"},
    {name = "949 The Surf", url = "https://ice24.securenetsystems.net/WVCO?playSessionID=1E009D1C-91CC-364D-ED1C527217927522"},
    {name = "949 WOLX Madison", url = "https://prod-54-164-138-156.amperwave.net/audacy-wolxfmaac-hlsc.m3u8"},
    {name = "94HJY", url = "https://stream.revma.ihrhls.com/zc2049"},
    {name = "95 KGGO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KGGOFMAAC.aac"},
    {name = "95 KQDS", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KQDSFMAAC.aac"},
    {name = "95 The Met", url = "https://ice66.securenetsystems.net/WMTT"},
    {name = "951 HOT OLDSCHOOL", url = "https://stream.revma.ihrhls.com/zc1393"},
    {name = "951 Stevefm", url = "https://ice23.securenetsystems.net/WUEZ"},
    {name = "951 The Fox", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WXFXFMAAC.aac"},
    {name = "951 ZZO", url = "https://stream.revma.ihrhls.com/zc1977"},
    {name = "955 GLO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WGLOFMAAC.aac"},
    {name = "955 Hallelujah FM", url = "https://stream.revma.ihrhls.com/zc1253"},
    {name = "955 Nash Icon", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WWSMFMAAC"},
    {name = "955 The Bull", url = "https://stream.revma.ihrhls.com/zc1345"},
    {name = "955 WSB", url = "https://cmg.streamguys1.com/atl750/atl750-sgplayer-aac"},
    {name = "957 BIG FM", url = "https://stream.revma.ihrhls.com/zc2689"},
    {name = "957 Hallelujah FM", url = "https://stream.revma.ihrhls.com/zc2137"},
    {name = "957 QMF", url = "https://stream.revma.ihrhls.com/zc3383"},
    {name = "957 That Station", url = "https://ais-sa8.cdnstream1.com/2749_64.aac"},
    {name = "957 The Jet", url = "https://stream.revma.ihrhls.com/zc2569"},
    {name = "957 The Party", url = "https://stream.revma.ihrhls.com/zc2795/hls.m3u8"},
    {name = "957 The Ride Charlotte'S Only Independent Radio Station", url = "https://ice8.securenetsystems.net/WXRC"},
    {name = "959 FM AM 610 The Sports Animal", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KNMLAMAAC.aac"},
    {name = "959 KISS FM", url = "https://woodward-radio.streamb.live/SB00132?args=web_01&starttime=1702970697"},
    {name = "959 The Rat", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WRATFMAAC.aac"},
    {name = "96-1 SRS", url = "https://stream.revma.ihrhls.com/zc1109"},
    {name = "96-7 KCAL Rocks", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KCALFMAAC.aac"},
    {name = "961 KISS FM", url = "https://stream.revma.ihrhls.com/zc1333"},
    {name = "961 KXY", url = "https://stream.revma.ihrhls.com/zc1917"},
    {name = "961 NOW", url = "https://stream.revma.ihrhls.com/zc2357"},
    {name = "961 The River", url = "https://stream.revma.ihrhls.com/zc1001"},
    {name = "961 WEJZ", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WEJZFMAAC.aac"},
    {name = "963 KHEY Country", url = "https://stream.revma.ihrhls.com/zc3192"},
    {name = "963 WDVD", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WDVDFMAAC.aac"},
    {name = "965 JACK-FM", url = "https://stream.revma.ihrhls.com/zc7788"},
    {name = "965 KSOM", url = "http://hestia.cdnstream.com/1528_128"},
    {name = "967 KISS FM", url = "https://stream.revma.ihrhls.com/zc2173"},
    {name = "967 KISS FM KHFI Austin", url = "http://stream.revma.ihrhls.com/zc1173"},
    {name = "967 Steve FM", url = "https://stream.revma.ihrhls.com/zc2077"},
    {name = "969 BOB FM", url = "https://ais-sa1.streamon.fm/7215_48k.aac"},
    {name = "969 Hits FM", url = "https://ice9.securenetsystems.net/KLTAHD2"},
    {name = "969 The Eagle KKGL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KKGLFMAAC.aac"},
    {name = "969 The Game", url = "https://stream.revma.ihrhls.com/zc601/hls.m3u8"},
    {name = "969 The Kat", url = "https://stream.revma.ihrhls.com/zc1605"},
    {name = "960 The Ref", url = "https://cmg.streamguys1.com/ath960/ath960-sgplayer-aac"},
    {name = "96X - Memphis", url = "https://ais-sa3.cdnstream1.com/2599_128.aac"},
    {name = "971 The Edge", url = "https://a7.asurahosting.com:6680/radio.mp3"},
    {name = "971 The Fan WBNS FM", url = "https://oom-radiohio.streamguys1.com/cols/wbnsfm.mp3"},
    {name = "973 The Game", url = "https://stream.revma.ihrhls.com/zc2685"},
    {name = "973 The Rock", url = "https://us9.maindigitalstream.com/ssl/kgrr"},
    {name = "973 WZBG", url = "https://ice6.securenetsystems.net/WZBG"},
    {name = "973FM Oasisradio", url = "https://stream1.305stream.com/proxy/client911?mp=/stream"},
    {name = "975 FM The Ride", url = "http://ice8.securenetsystems.net/WXRC"},
    {name = "975 KJMO", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KJMOFMAAC.aac"},
    {name = "975 WAMZ", url = "https://stream.revma.ihrhls.com/zc977"},
    {name = "975 WCOS", url = "https://stream.revma.ihrhls.com/zc2073"},
    {name = "975 WOKQ", url = "https://live.amperwave.net/manifest/townsquare-wokqfmaac-ibc3"},
    {name = "975 WONE Akron'S Home Of Rock Roll", url = "http://playerservices.streamtheworld.com/pls/WONEFMAAC.pls"},
    {name = "977 ESPN The Zone", url = "https://ic2.sslstream.com/wzzn-fm?rnd=7398"},
    {name = "977 The Bay", url = "https://www.streamvortex.com:8444/s/11030"},
    {name = "977 The Zone", url = "https://ic2.sslstream.com/wzzn-fm"},
    {name = "979 1073 The Bull", url = "https://ice8.securenetsystems.net/WDAQHD3"},
    {name = "979 WJLB", url = "https://stream.revma.ihrhls.com/zc1141"},
    {name = "979 WNCI", url = "http://stream.revma.ihrhls.com/zc1753"},
    {name = "979X WBSX-FM", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/WBSXFM.mp3"},
    {name = "970 KVWM", url = "https://ice41.securenetsystems.net/KVWM"},
    {name = "97X", url = "https://streaming.live365.com/a10801"},
    {name = "98 Rock", url = "http://provisioning.streamtheworld.com/pls/WIYYFMAAC.pls"},
    {name = "98 TXT - WTXT - Fayettetuscaloosa, AL", url = "https://stream.revma.ihrhls.com/zc3073"},
    {name = "981 KBEAR", url = "http://desertmountainbroadcasting.streamguys1.com/KYYA"},
    {name = "981 KKFM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KKFMFMAAC.aac"},
    {name = "981 KVET", url = "https://stream.revma.ihrhls.com/zc2185"},
    {name = "981 The Bull", url = "https://stream.revma.ihrhls.com/zc1381"},
    {name = "981 The Max", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WXMXFMAAC.aac"},
    {name = "981 WTSN", url = "https://ice64.securenetsystems.net/WTSN"},
    {name = "983 Nash Icon", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WMIMFMAAC.aac"},
    {name = "983 The Vibe", url = "http://provisioning.streamtheworld.com/pls/KWQWFMAAC.pls"},
    {name = "985 El Patron", url = "https://stream.revma.ihrhls.com/zc6969/hls.m3u8"},
    {name = "985 Kfox San Jose, California", url = "https://bonneville.cdnstream1.com/2620_48.aac?aw_0_1st.playerid=Tuner"},
    {name = "985 KTIS", url = "https://nwmedia-ktisfm.streamguys1.com/ktis-fm"},
    {name = "985 The Cat", url = "https://stream.revma.ihrhls.com/zc5128"},
    {name = "985 WOMG", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WOMGFMAAC.aac"},
    {name = "985 WYLD", url = "https://stream.revma.ihrhls.com/zc1053"},
    {name = "987 Arizona Sports KMVP", url = "https://bonneville.cdnstream1.com/2699_48.aac"},
    {name = "987 KMGO", url = "http://us1.streamingpulse.com:8080/stream"},
    {name = "987 KRQU Vintage Vinyl", url = "http://nebcoradio.com:1010/KRQU"},
    {name = "987 The Shark", url = "http://playerservices.streamtheworld.com/api/livestream-redirect/WPBBFMAACHI.aac"},
    {name = "987 WNLC", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WNLCFMAAC.aac"},
    {name = "987FM WVMO, The Voice Of Monona", url = "https://22073.live.streamtheworld.com/WVMOFMAAC.aac"},
    {name = "989 KISS-FM", url = "https://stream.revma.ihrhls.com/zc3387"},
    {name = "989 KKZX", url = "https://stream.revma.ihrhls.com/zc2581"},
    {name = "989 Magic FM", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KKMGFMAAC.aac"},
    {name = "989 The Bridge", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WKIMFMAAC.aac"},
    {name = "98Q", url = "https://ice10.securenetsystems.net/WDAQ?playSessionID=1E3A6CE8-A288-0AEF-C4547809DB73F8CE"},
    {name = "991 Joy FM", url = "https://gateway.cdnstream1.com/2808_96.aac"},
    {name = "991 KBUU", url = "http://s7.viastreaming.net:9140/;"},
    {name = "991 The Beat Of Eugene", url = "https://us9.maindigitalstream.com/ssl/KODZ"},
    {name = "991 The BULL", url = "https://ice10.securenetsystems.net/KBBLFM?playSessionID=EFCF6901-8455-4C50-A9A9EB4A300374D0"},
    {name = "991 The Ranch", url = "https://ice9.securenetsystems.net/KWSV"},
    {name = "991FM Downtown Radio", url = "https://securestreams6.autopo.st:2110/stream.mp3"},
    {name = "993 The Peach", url = "https://ice7.securenetsystems.net/KPCH"},
    {name = "993 The Vine", url = "https://ice10.securenetsystems.net/KVYN"},
    {name = "993 WCON My Country", url = "http://ice10.securenetsystems.net/WCON"},
    {name = "995 MAGIC", url = "http://provisioning.streamtheworld.com/pls/KMGAFM.pls"},
    {name = "995 The River", url = "https://stream.revma.ihrhls.com/zc1433"},
    {name = "995 The Word", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/KGUFMAAC.aac"},
    {name = "995 WCRB - Bach Channel", url = "http://wgbh.streamguys.com/Bach-8108"},
    {name = "995 WZPL", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WZPLFMAAC.aac"},
    {name = "997 1450 WHTC", url = "http://provisioning.streamtheworld.com/pls/WHTCAM.pls"},
    {name = "997 Hank FM", url = "https://ice8.securenetsystems.net/KNAH"},
    {name = "997 NOW KMVQ-FM", url = "https://bonneville.cdnstream1.com/2622_48.aac"},
    {name = "997 The Fox", url = "https://stream.revma.ihrhls.com/zc1613"},
    {name = "997 The Fox - Charlotte'S Classic Rock WRFX", url = "http://stream.revma.ihrhls.com/zc1613/hls.m3u8"},
    {name = "999 Gator Country", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WGNEAAC.aac"},
    {name = "999 KGOR", url = "https://stream.revma.ihrhls.com/zc3344"},
    {name = "999 KISW - The Rock Of Seattle", url = "http://stream.abacast.net/direct/audacy-kiswfmaac-imc"},
    {name = "999 The Beat", url = "https://ice42.securenetsystems.net/KMGG"},
    {name = "999 The Hawk", url = "https://playerservices.streamtheworld.com/api/livestream-redirect/WODEFM_SC"},
    {name = "A Classical California Christmas", url = "https://25043.live.streamtheworld.com/CC2_S01AAC_96.aac?tdsdk=js-2.9&swm=false&pname=TDSdk&pversion=2.9&banners=none&burst-time=15&sbmid=8c8f8b67-33f1-43a1-d0cc-5b0b4e502a30"},
    {name = "A Strangely Isolated Place 9128", url = "https://streams.radio.co/s0aa1e6f4a/listen"},
    {name = "A Tribal Smile", url = "https://impoid.radioca.st/;"},
    {name = "AA Dance", url = "http://62.210.204.2:8000/stream/7/?icy=https"},
    {name = "Am Ambient", url = "http://radio.stereoscenic.com/ama-h"},
    {name = "Amambient", url = "https://radio.stereoscenic.com/ama-s"},
    {name = "Aardvark Blues FM", url = "https://ais-sa5.cdnstream1.com/b77280_128mp3"},
    {name = "ABC 11", url = "https://content.uplynk.com/channel/ext/f05837c508c44712aa7129d531f7dbe6/wtvd_24x7_news.m3u8"},
    {name = "ABC News Live", url = "https://content.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be.m3u8"},
    {name = "ABC News Radio", url = "https://abcnews-streams.akamaized.net/hls/live/2024904/radiolive/master-96000.m3u8"},
    {name = "ABC Radio National NT HLS", url = "https://mediaserviceslive.akamaized.net/hls/live/2038332/rnnt/index.m3u8"},
    {name = "Abiding Radio Bluegrass Hymns", url = "http://streams.abidingradio.org:7840/1"},
    {name = "Abiding Radio Instrumental Hymns", url = "https://www.abidingradio.org/radio/instrumental"},
    {name = "Abiding Radio Kids' Songs And Bible Stories", url = "http://streams.abidingradio.org:7810/1"},
    {name = "Abiding Radio Sacred Hymns", url = "http://streams.abidingradio.org:7820/1"},
    {name = "Abiding Radio Seasonal", url = "http://streams.abidingradio.org:7830/1"},
=======
    {name = "919 KUDR", url = "http://kdurradio.fortlewis.edu/stream"},
    {name = "3ABN Music Channel Non SSL", url = "http://war.str3am.com:7180/MC01"},
    {name = "22 West Radio", url = "https://16603.live.streamtheworld.com/22WESTRADIOONLINEAAC.aac"},
    {name = "899 WDAV", url = "https://wdav-ice.streamguys1.com/live-mp3"},
>>>>>>> 7d1f32cebb0f314e8136a3afc632dac88694d724
}

return stations
