local stations = {
    {name = "Ucm-The Beat", url = "http://198.245.60.88:8232/stream"},
    {name = "KBOO 907 Portland, OR", url = "http://live.kboo.fm:8000/high.m3u"},
    {name = "Bible Radio Network - English Channel", url = "https://shout2.brnstream.com/proxy/brnradio1?mp=/stream"},
    {name = "DCLM Online Radio - English", url = "https://airtime.dclm.org/radio/8000/live"},
    {name = "The Big 80S Station", url = "http://158.69.114.190:8065/;"},
    {name = "WFUV 24-7 Music New York, NY", url = "http://wfuv-music.streamguys.org/music-hi"},
    {name = "Folk Alley Fresh Cuts", url = "https://freshgrass.streamguys1.com/freshcuts-128mp3"},
    {name = "Radio Nightingale Volksmusik", url = "http://streams.radioriel.org:8060/stream"},
    {name = "Planet Hiphop Mrgfm", url = "http://listen.mrg.fm:8100/stream"},
    {name = "The Ultimate Art Bell", url = "http://stream.willstare.com:8450/"},
    {name = "Rez 91", url = "http://192.99.14.49:9009/stream?1691594087197"},
    {name = "Radio Dismuke", url = "http://74.208.71.58:8078/"},
    {name = "Boss Radio 66", url = "https://rfcm.streamguys1.com/bossradio66-mp3"},
    {name = "CRN 7", url = "http://64.78.234.173:8302/;"},
    {name = "World Fusion Radio Revolution", url = "http://51.255.235.165:5366/stream"},
    {name = "Ziradio", url = "http://andromeda.shoutca.st:8023/;"},
    {name = "KNCE 935 True Taos Radio", url = "https://shoutcast.brownrice.com:8002/stream"},
    {name = "Mytime Movie Network", url = "https://appletree-mytime-samsungbrazil.amagi.tv/playlist.m3u8"},
    {name = "KBKY Radio Alfa Y Omega", url = "http://s6.myradiostream.com/6114/listen.mp3"},
    {name = "American Voice Radio Network AVRN 1", url = "http://ca9.rcast.net:8040/stream"},
    {name = "KPBS", url = "https://kpbs.streamguys1.com/kpbs-mp3"},
    {name = "KSRQ Pioneer 901 Northland Community Technical College - Thief River Falls, MN", url = "http://134.29.211.155:8002/;.mp3"},
    {name = "Angels Radio AM830", url = "http://klaa.streamguys1.com/live-aac"},
    {name = "No Agenda Stream", url = "http://listen.noagendastream.com/noagenda"},
    {name = "WXRV 925 The River Andover, MA", url = "http://72.13.83.130:8010/;.mp3"},
    {name = "PAMA ONE Radio", url = "http://c5.radioboss.fm:8271/live"},
    {name = "KSCB Radio News", url = "https://1.ice1.sslstream.com/kscb_am.aac"},
    {name = "WUNH 913 University Of New Hampshire - Durham, NH", url = "http://s9.viastreaming.net:9000/;.mp3"},
    {name = "KHCB Chinese Radio華人之聲", url = "https://khcb.streamguys1.com/chinese-128k-mp3"},
    {name = "Not Gamingfm", url = "http://67.212.165.106:8191/listen.pls"},
    {name = "Fade To Black With Jimmy Church", url = "http://tc1.bahamatel.net:8268/"},
    {name = "Superq104", url = "http://176.31.118.39:3676/;"},
    {name = "SPRLIVEFM", url = "https://us1.streamingpulse.com/ssl/sprlivefm#.mp3"},
    {name = "KBRD", url = "http://205.134.192.90:680/"},
    {name = "LA Talk Radio", url = "https://securestreams2.autopo.st:1185/;stream/1"},
    {name = "WBOR 911 FM", url = "https://listen.wbor.org/"},
    {name = "Save Souls Today", url = "http://we.savesouls.today:8088/stream"},
}

return stations
