local stations = {
    {name = "Вести ФМ Vesti FM", url = "http://icecast.vgtrk.cdnvideo.ru/vestifm_mp3_192kbps"},
    {name = "Europa Plus", url = "http://ep256.hostingradio.ru:8052/europaplus256.mp3"},
    {name = "Ретро FM", url = "http://retroserver.streamr.ru:8043/retro256.mp3"},
    {name = "РАДИО ВАНЯ", url = "https://icecast-radiovanya.cdnvideo.ru/radiovanya"},
    {name = "Соловьёв LIVE", url = "https://solovievfm.hostingradio.ru/solovievfm128.aacp"},
    {name = "Радио «Комсомольская Правда» | КП Россия", url = "http://kpradio.hostingradio.ru:8000/russia.radiokp128.mp3"},
    {name = "Маруся FM", url = "http://radio-holding.ru:9000/marusya_aac_64"},
    {name = "ROCK FM", url = "http://nashe1.hostingradio.ru/rock-128.mp3"},
    {name = "DFM RUSSIAN DANCE", url = "https://dfm-dfmrusdance.hostingradio.ru/dfmrusdance96.aacp?0.9987259013359274"},
    {name = "Дискотека СССР", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/144?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjUuMTguMjQ4Ljk4IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6ODIuMCkgR2Vja29cLzIwMTAwMTAxIEZpcmVmb3hcLzgyLjAiLCJ1aWRfY2hhbm5lbCI6IjE0NCIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MDU5NjQ1MTZ9.Ln1wEJ8cHHzK_Ea6Zr8J8acdny0R9ShZ_KUKVf6TmQA"},
    {name = "Авторадио - FM 903 - Москва", url = "http://ic4.101.ru:8000/v3_1"},
    {name = "Дорожное Радио Dorognoe Radio", url = "http://dorognoe.hostingradio.ru:8000/dorognoe"},
    {name = "Шансон Радио", url = "http://chanson.hostingradio.ru:8041/chanson128.mp3"},
    {name = "Спутник", url = "https://icecast-rian.cdnvideo.ru/voicerus"},
    {name = "Радио Маяк Radio Mayak", url = "http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_192kbps"},
    {name = "DFM Дискач 90-Х", url = "https://dfm-disc90.hostingradio.ru/disc9096.aacp"},
    {name = "Радио Патриот", url = "http://radio.mixto.ru:8001/patriot"},
    {name = "Комсомольская Правда", url = "https://kpradio.hostingradio.ru:8000/64"},
    {name = "Вести FM", url = "http://icecast.vgtrk.cdnvideo.ru/vestifm"},
    {name = "Эхо Online", url = "https://noasrv.caster.fm:10034/stream"},
    {name = "Comedy Radio New Link", url = "http://ic6.101.ru:8000/stream/air/aac/64/202"},
    {name = "Дорожное Радио", url = "http://dorognoe.hostingradio.ru:8000/radio"},
    {name = "Радио Книга", url = "http://bookradio.hostingradio.ru:8069/fm"},
    {name = "Радио Русские Песни", url = "http://listen.rusongs.ru/ru-mp3-128"},
    {name = "Наше Радио", url = "http://nashe.streamr.ru/nashe-128.mp3"},
    {name = "Радио 7 На Семи Холмах", url = "http://radio7server.streamr.ru:8040/radio7256.mp3"},
    {name = "Звезда", url = "https://icecast-zvezda.mediacdn.ru/radio/zvezda/zvezda_128"},
    {name = "ДИСКОТЕКА 90-Х", url = "https://radiorecord.hostingradio.ru/sd9096.aacp?0968d4a7"},
    {name = "РАДИО ДЛЯ ВЗРОСЛЫХ", url = "http://listen6.myradio24.com:9000/alex542888"},
    {name = "Radio Record - Russian Mix", url = "https://radiorecord.hostingradio.ru/rus96.aacp"},
    {name = "Радио Дача", url = "http://listen13.vdfm.ru:8000/dacha"},
    {name = "Соловьёв FM", url = "https://solovievfm.hostingradio.ru/solovievfm32.aacp"},
    {name = "Спокойное Радио", url = "https://listen1.myradio24.com/6262"},
    {name = "Mixadance FM", url = "https://stream.mixadance.fm/mixadance"},
    {name = "101Ru - Deep House", url = "https://pub0202.101.ru:8000/stream/trust/mp3/128/173"},
    {name = "РЕТРО ХИТ - RETRO HIT", url = "http://retro.volna.top/Retro"},
    {name = "Русский Рок - Russian Rock", url = "http://rock.volna.top/RusRock"},
    {name = "Шансон Без Цензуры", url = "http://chanson.hostingradio.ru:8041/chanson-uncensored256.mp3"},
    {name = "Комерсант Kommersant FM 936 Moscow", url = "http://kommersant77.hostingradio.ru:8016/kommersant64.mp3"},
    {name = "Русское Радио", url = "https://rusradio.hostingradio.ru/rusradio96.aacp"},
    {name = "Бизнес FM", url = "https://bfm.hostingradio.ru:9075/fm"},
    {name = "101,Ru Russian Dance", url = "https://pub0302.101.ru:8443/stream/trust/mp3/128/17?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjQ5LjM3LjE1MS42IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6ODguMCkgR2Vja29cLzIwMTAwMTAxIEZpcmVmb3hcLzg4LjAiLCJ1aWRfY2hhbm5lbCI6IjE3IiwidHlwZV9jaGFubmVsIjoiY2hhbm5lbCIsImV4cCI6MTYxODUwMTYyM30.vsWQ1s12RL1P3yuD4Eb6E2Og6YaLbXceO-cfhhhwl5s"},
    {name = "Radio Record - Russian Gold", url = "https://radiorecord.hostingradio.ru/russiangold96.aacp"},
    {name = "Ретро FM 70E", url = "http://retro70.hostingradio.ru:8025/retro70-128.mp3"},
    {name = "Европа Плюс", url = "http://ep128server.streamr.ru:8030/ep128"},
    {name = "Говорит Москва", url = "http://media.govoritmoskva.ru:8880/ru64.mp3"},
    {name = "Юмор FM", url = "http://pub0101.101.ru:8000/stream/air/aac/64/102"},
    {name = "Discovertranceradio MP3 HQ Stereo 192Kbits", url = "http://www.discovertrance.com/DiscoverTrance-high.m3u"},
    {name = "101Ru Italo Disco", url = "http://pub0202.101.ru:8000/stream/pro/aac/64/161"},
    {name = "Instrumental Jazz", url = "https://jfm1.hostingradio.ru:14536/ijstream.mp3"},
    {name = "Известия ТВ Звук", url = "https://hls-igi.cdnvideo.ru/igi/radio1/tracks-a1/mono.m3u8"},
    {name = "Радио России Radio Russia", url = "http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_128kbps"},
    {name = "Radio Monte Carlo 1059 FM", url = "https://icecast227.ptspb.ru:8443/monte"},
    {name = "Модель Для Сборки", url = "http://mds-station.com:8000/mds"},
    {name = "Радио Книга Вслух", url = "https://radio-soyuz.ru:1045/stream"},
    {name = "Советская Эстрада", url = "https://evcast.mediacp.eu:2075/stream"},
    {name = "Radio Ultra", url = "http://nashe1.hostingradio.ru/ultra-192.mp3"},
    {name = "Luxury Lounge - Late Night, Deep Sleep Meditation", url = "http://188.40.109.122:8000/ices3"},
    {name = "Sputnik Europe", url = "https://nfw.ria.ru/flv/audio.aspx?ID=75651129&type=mp3"},
    {name = "Анекдот Фм", url = "http://ic6.101.ru:8000/stream/trust/mp3/128/20"},
    {name = "Радио Шансон - Radio Shanson", url = "http://chanson.hostingradio.ru:8041/chanson256.mp3"},
    {name = "Ностальгия - Дорожное Радио", url = "http://stream1.hostingradio.ru:8010/19_mp3_128"},
    {name = "Cassiopeia Station Наука", url = "https://stream.cassiopeia-station.ru:1095/stream"},
    {name = "Best Deep FM", url = "https://myradio24.org/5129_320.m3u"},
    {name = "Радио Ностальжи Россия", url = "http://listen7.myradio24.com:9000/alexx333.m3u"},
    {name = "Вести FM AAC", url = "https://icecast-vgtrk.cdnvideo.ru/vestifm_aac_32kbps"},
    {name = "Nashe Radio", url = "http://nashe1.hostingradio.ru/nashe-128.mp3"},
    {name = "ХИТ FM", url = "https://hitfm.hostingradio.ru/hitfm128.mp3?48c22b78"},
    {name = "Ретро FM 90E", url = "http://retro90.hostingradio.ru:8025/retro90-128.mp3"},
    {name = "101Ru - Drum Bass", url = "https://pub0302.101.ru:8000/stream/pro/aac/64/6?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjIxMi41MS4xNDIuMTY2IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IFVidW50dTsgTGludXggeDg2XzY0OyBydjo4OC4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvODguMCIsInVpZF9jaGFubmVsIjoiNiIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MTU0NjYxNDh9.ReVmj9UP8k1j83oPOXewKDc37Me9RpR3wA3nm5bMWmE"},
    {name = "Настоящее Время", url = "http://rfe-ingest.akamaized.net/hls/live/2033043/tvmc05/playlist_0240.m3u8"},
    {name = "Радио Шоколад", url = "https://choco.hostingradio.ru:10010/fm"},
    {name = "DFM", url = "https://dfm.hostingradio.ru/dfm96.aacp?0.28225617725168517"},
    {name = "Радио Рекорд Russian Mix", url = "http://radiorecord.hostingradio.ru/rus96.aacp"},
    {name = "Серебряный Дождь", url = "http://213.59.4.27:8000/silver128.mp3"},
    {name = "Radio Fantastika", url = "http://fantasyradioru.no-ip.biz:8002/live"},
    {name = "Радио Маяк", url = "https://icecast-vgtrk.cdnvideo.ru/mayakfm"},
    {name = "Ретро ФМ", url = "http://retroserver.streamr.ru:8043/retro128"},
    {name = "Deep One", url = "https://stream.deep1.ru/deep1mp3"},
    {name = "Enigmatic 3 - Magnetic Chillout", url = "http://radio.enigmatic.su:8050/radio"},
    {name = "Старое Радио - Old Radio", url = "http://195.91.237.50:8000/ices128"},
    {name = "Питер FM - Санкт-Петербург 1009 Мгц", url = "http://icecast-piterfm.cdnvideo.ru/piterfm"},
    {name = "Antidot", url = "https://135.125.205.200:8443/main"},
    {name = "101Ru Techno", url = "https://pub0302.101.ru:8000/stream/trust/mp3/128/18"},
    {name = "MAXIMUM", url = "https://maximum.hostingradio.ru/maximum96.aacp"},
    {name = "Новое Радио 911 Спб", url = "http://emgspb.hostingradio.ru/novoespb128.mp3"},
    {name = "Enigmatic Station 1", url = "http://listen2.myradio24.com:9000/8226"},
    {name = "Радио Рекорд Супердискотека 90-Х", url = "http://radiorecord.hostingradio.ru/sd9096.aacp"},
    {name = "101Ru СССР 50-70", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/47"},
    {name = "Пионер FM Russian Wave", url = "https://ppr90.status-media.ru/ru-wave.mp3"},
    {name = "101Ru Trance", url = "http://pub0101.101.ru:8000/stream/trust/mp3/128/19?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ijc5LjI1My4xMy43MSIsInVzZXJhZ2VudCI6Ik1vemlsbGFcLzUuMCAoWDExOyBMaW51eCB4ODZfNjQ7IHJ2Ojk0LjApIEdlY2tvXC8yMDEwMDEwMSBGaXJlZm94XC85NC4wIiwidWlkX2NoYW5uZWwiOiIxOSIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MzY4ODYwMzJ9.0vfq2B5eNRtuEwE42pHUS9Sf_GosTmrQs0aHcPvbFj8"},
    {name = "Modern Talking", url = "http://stream.dar.fm/119941"},
    {name = "Радио Романтика", url = "https://pub0202.101.ru:8443/stream/air/aac/64/101"},
    {name = "DFM - Vocal Trance", url = "https://dfm-trance.hostingradio.ru/trance96.aacp"},
    {name = "Маруся ФМ", url = "https://listen.vdfm.ru:8000/marusya"},
    {name = "Радио Maximum", url = "https://maximum.hostingradio.ru/maximum128.mp3"},
    {name = "Радио Монте Карло", url = "https://montecarlo.hostingradio.ru/montecarlo128.mp3"},
    {name = "Discoteca 80", url = "https://pub0302.101.ru:8443/stream/pro/aac/64/1?"},
    {name = "Anima Amoris - Goa Psy Trance", url = "http://amoris.sknt.ru/goa.mp3"},
    {name = "Radio Caprice - Goa Trance", url = "http://79.120.39.202:9105/"},
    {name = "Радио Родных Дорог", url = "http://stream1.radiord.ru:8000/live96.aac"},
    {name = "Коммерсантъ FM 936", url = "https://kommersant77.hostingradio.ru:8085/kommersant128.mp3"},
    {name = "Радио Юность", url = "http://icecast-vgtrk.cdnvideo.ru/unost_mp3_192kbps"},
    {name = "Remix FM", url = "http://air4.amgradio.ru/RemixFM"},
    {name = "Made In Russia Dance Radio", url = "https://listen7.myradio24.com/9083"},
    {name = "Коммерсант", url = "http://kommersant77.hostingradio.ru:8016/kommersant128.mp3"},
    {name = "Relax FM Nature", url = "https://pub0101.101.ru/stream/trust/mp3/128/263"},
    {name = "DFM - Insomnia", url = "https://dfm-insomnia.hostingradio.ru/insomnia96.aacp"},
    {name = "Ретро FM — Вечеринка", url = "https://hls-01-retro-vecherinka.emgsound.ru/20/playlist.m3u8"},
    {name = "Spacesynthru", url = "http://listen2.myradio24.com:9000/1987"},
    {name = "Радио Сахаров", url = "https://icecast.correctiv.net/sacharow"},
    {name = "Высоцкий", url = "https://rr-vysockij.hostingradio.ru/vysockij96.aacp"},
    {name = "Radio Record Megamix", url = "https://radiorecord.hostingradio.ru/mix96.aacp"},
    {name = "Radio Record - Main Channel", url = "https://radiorecord.hostingradio.ru/rr_main96.aacp"},
    {name = "Radio Caprice - Jazz Fusion", url = "http://79.111.119.111:9009/;"},
    {name = "Пи FM", url = "http://cdn.pifm.ru/mp3"},
    {name = "Пионер", url = "https://ppr.status-media.ru/ppr128.mp3"},
    {name = "Радио Атмосфера", url = "http://185.64.76.49:8000/128.m3u"},
    {name = "Радио МИР", url = "https://icecast-mirtv.cdnvideo.ru/radio_mir_256"},
    {name = "Radio Chocolate", url = "http://choco.hostingradio.ru:10010/fm"},
    {name = "101Ru - Relax FM", url = "https://ic4.101.ru:8000/stream/air/aac/64/200"},
    {name = "Дядя Ваня На Даче 18+", url = "https://ic1.radiosignal.one/vanya-mp3"},
    {name = "ABBA Radio", url = "https://pub0102.101.ru:8443/stream/personal/aacp/64/1785788"},
    {name = "Enigma", url = "http://stream.dar.fm/125334"},
    {name = "Радио Рекорд Russian Hits", url = "http://radiorecord.hostingradio.ru/russianhits96.aacp"},
    {name = "8Bitfm", url = "http://8bit.fm:8000/live"},
    {name = "DONAT FM - Шансон", url = "http://c6.radioboss.fm:8096/stream"},
    {name = "СВОЕFM | DEEP RADIO", url = "http://relay4.radiotoolkit.com/svoefm"},
    {name = "Голос Свободной России", url = "http://freerutube.info:8000/live"},
    {name = "Radio Caprice - Classical Baroque", url = "http://79.111.14.76:8002/baroque"},
    {name = "Радио Ретроклуб", url = "http://retroclub.hostingradio.ru/retroclub128.aacp"},
    {name = "Radio Caprice - Cyberpunk", url = "http://79.120.12.130:8004/cyberpunk"},
    {name = "Radio Caprice - Chicago Blues", url = "http://79.111.14.76:8000/chicagoblues"},
    {name = "РАДИО ENERGY - Москва 1042 FM", url = "http://pub0302.101.ru:8000/stream/air/aac/64/99"},
    {name = "Советская Классика", url = "https://rr-sovclass.hostingradio.ru/sovclass96.aacp"},
    {name = "101Ru: Виктор Цой И Группа «КИНО»", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/103?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ijc4LjEwMi4yMzEuMTYiLCJ1c2VyYWdlbnQiOiJNb3ppbGxhXC81LjAgKFdpbmRvd3MgTlQgNi4zOyBXaW42NDsgeDY0OyBydjo5NS4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvOTUuMCIsInVpZF9jaGFubmVsIjoiMTAzIiwidHlwZV9jaGFubmVsIjoiY2hhbm5lbCIsImV4cCI6MTY0MDY4NTcwNH0.lnoDlTGctdMYI221sL4xM2B60tGLcLY5nYiv8bu1vNs"},
    {name = "Радио Для Двоих", url = "https://icecast-radiofortwo.cdnvideo.ru/radiofortwo"},
    {name = "Радиола", url = "http://online1.gkvr.ru:8000/radiola_eka_128.mp3"},
    {name = "Милицейская Волна НН", url = "https://radiomv.hostingradio.ru:80/radiomv128.mp3"},
    {name = "Mixcult", url = "http://radio.mixcult.net:8000/MixCult_256kbps"},
    {name = "Дискач 90S Мегахит ДНР", url = "http://stream.laut.fm/radio90s"},
    {name = "Союз ФМ", url = "http://soyuzfm.su:8100//soyuzfm-320.mp3?1702169748633"},
    {name = "Умное Радио", url = "http://umnoe.amgradio.ru/Umnoe"},
    {name = "Красное Радио", url = "https://myradio24.org/zuek1917"},
    {name = "Radio Caprice - Eurodance", url = "http://79.120.39.202:9003/"},
    {name = "Noise FM - It'S Your Lifestyle", url = "http://play.sas-media.ru/play_256"},
    {name = "L-Radio", url = "https://air.unmixed.ru/lradio256"},
    {name = "Гусьолдскул", url = "https://stream.radiogoose.ru:8010/play"},
    {name = "Radio Record Chill-Out", url = "https://radiorecord.hostingradio.ru/chil32.aacp"},
    {name = "DONAT FM - Русская Поп-Музыка", url = "http://c6.radioboss.fm:8099/stream"},
    {name = "Super-Radio Remix", url = "https://listen2.myradio24.com/serz"},
    {name = "Сказка FM", url = "https://skazka.amgradio.ru/Skazka"},
    {name = "Искатель", url = "http://iskatel.hostingradio.ru:8015/iskatel-128.mp3"},
    {name = "Русское Радио: Русский Рок", url = "https://rr-russkijrok.hostingradio.ru/russkijrok96.aacp.m3u"},
    {name = "Radio Record Trancehouse", url = "https://radiorecord.hostingradio.ru/trancehouse96.aacp"},
    {name = "Пионер ФМ Кассета", url = "https://ppr90.status-media.ru/kasseta.mp3"},
    {name = "Калина Красная", url = "http://icecast-studio21.cdnvideo.ru/KalynaK_1a"},
    {name = "HIP HOP RADIO", url = "https://tntradio.hostingradio.ru:8027/hhr128.mp3"},
    {name = "Radio Caprice - Progressive House", url = "http://79.111.119.111:9021/"},
    {name = "Relax FM 90,8 Moscow", url = "http://pub0302.101.ru:8000/stream/trust/mp3/128/264"},
    {name = "DONAT FM - Музыка СССР", url = "http://c6.radioboss.fm:8098/stream"},
    {name = "Женский Stand Up", url = "https://pub0102.101.ru:8443/stream/pro/aac/64/448"},
    {name = "Radio Caprice - Minimal Tech House [2]", url = "http://79.111.119.111:8000/mintechhouse"},
    {name = "Радио ЗВЕЗДА - Центральная Россия", url = "https://zvezda-radio128.mediacdn.ru/radio/zvezda/zvezda_128"},
    {name = "Спутник 912 Fm", url = "https://stream03.pcradio.ru/sputnik_ria_ru-med"},
    {name = "Record Minimal", url = "https://radiorecord.hostingradio.ru/mini96.aacp"},
    {name = "URALSOUND FM | DEEP HOUSE", url = "https://5.restream.one/1392_1"},
    {name = "Радио Культура Radio Kultura", url = "http://icecast.vgtrk.cdnvideo.ru/kulturafm_mp3_192kbps"},
    {name = "Романтический Шансон", url = "http://chanson.hostingradio.ru:8041/chanson-romantic256.mp3"},
    {name = "Радио Душевные Песни", url = "http://1dp.5cdn.ru:8000/dushevniepesni?time=1682183806914"},
    {name = "Радио Сектор Sector Progressive Flac", url = "http://89.223.45.5:8000/progressive-flac"},
    {name = "DNB FM", url = "https://air.dnbfm.ru/listen/player/qplay"},
    {name = "Radio Record Ambient", url = "http://radiorecord.hostingradio.ru/ambient96.aacp"},
    {name = "Radio Caprice - Dub Techno [2]", url = "http://79.120.39.202:8000/dubtechno"},
    {name = "Sovietwave", url = "http://station.waveradio.org/soviet.mp3"},
    {name = "Echo ЭХО Online", url = "https://i1.echofm.online:8443/stream"},
    {name = "Radio Caprice - Minimal Tech House [3]", url = "http://79.111.119.111:8004/mintechhouse"},
    {name = "Luxury Lounge - Chillwave Retrowave", url = "http://188.40.109.122:8000/ices2"},
    {name = "101Ru Любэ", url = "https://pub0302.101.ru:8000/stream/pro/aac/64/158?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ij"},
    {name = "Радиостация Маяк Москва 128Kbs", url = "http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_128kbps"},
    {name = "Radio Caprice - Dark Psytrance", url = "http://79.111.119.111:9057/;"},
    {name = "Radio Caprice - Atmosphericambient Black Metal", url = "http://79.120.39.202:9093/"},
    {name = "РАДИО КАФЕ - Radio CAFE", url = "http://cafe.volna.top/Cafe"},
    {name = "Radio Caprice LIQUID FUNK INTELLIGENT ATMOSPHERIC Drum'N'Bass", url = "http://79.111.119.111:8000/liquidfunk"},
    {name = "ШАНСОН БЕЗ ЦЕНЗУРЫ [CHANSONUNCENSORED]", url = "http://chanson.hostingradio.ru:8041/chanson-uncensored128.mp3"},
    {name = "Radio Record Deep", url = "http://radiorecord.hostingradio.ru/deep96.aacp"},
    {name = "Жара FM", url = "https://live1.zharafm.ru/internet"},
    {name = "Radio Caprice - Minimal Techno [2]", url = "http://79.120.39.202:8000/mintechno"},
    {name = "STUDIO 21", url = "http://icecast-studio21.cdnvideo.ru/S21cl_1r"},
    {name = "Radio Caprice - Erotic", url = "http://79.120.39.202:8000/erotic"},
    {name = "Радио Эрмитаж", url = "http://hermitage.hostingradio.ru/hermitage128.mp3"},
    {name = "Радонеж", url = "http://icecast.radonezh.cdnvideo.ru:8000/rad"},
    {name = "Радио Рекорд Remix", url = "http://radiorecord.hostingradio.ru/rmx96.aacp"},
    {name = "Garage FM Online", url = "http://music.garagefm.ru:8005/Garagefm128"},
    {name = "Radio Caprice - Symponic Metal", url = "http://79.120.77.11:8004/symphometal"},
    {name = "Radio Caprice - Heavy Metal", url = "http://79.111.14.76:8000/heavymetal.m3u"},
    {name = "Anima Amoris Dub Techno Mix", url = "http://amoris.sknt.ru/dubtechnomix.mp3"},
    {name = "Invoice Радио", url = "https://listen.myrh.ru/id079040"},
    {name = "MOTORADIO", url = "http://stream.motoradio.online:8000/high-aac"},
    {name = "Radio Record Liquid Funk", url = "https://radiorecord.hostingradio.ru/liquidfunk96.aacp"},
    {name = "Радиоканал Мелодия", url = "http://stream128.melodiafm.spb.ru:8000/melodia128"},
    {name = "Musical Decadence Radio", url = "https://stream.musicaldecadence.ru/live"},
    {name = "Atmosfera 128", url = "http://185.64.76.49:8000/128"},
    {name = "Like FM Moscow, Russia", url = "http://pub0302.101.ru:8000/stream/air/aac/64/219"},
    {name = "Соль Fm Соликамск", url = "https://www.liveradio.es/http://solfm.ru:8000/online128"},
    {name = "Радио Орфей 992 FM", url = "http://orfeyfm.hostingradio.ru:8034/orfeyfm192.mp3"},
    {name = "Азбука Молитвы", url = "https://radio.azbyka.ru/azbyka-molitvy"},
    {name = "Вести ФМ", url = "https://icecast-vgtrk.cdnvideo.ru/vestifm_mp3_64kbps"},
    {name = "Радио Джаз 89,1FM", url = "http://jazz.streamr.ru/jazz-128.mp3"},
    {name = "Радио Рекорд Основной Канал", url = "http://radiorecord.hostingradio.ru/rr_main96.aacp"},
    {name = "Sputnik Europe High", url = "https://nfw.ria.ru/flv/audio.aspx?ID=36292119&type=mp3"},
    {name = "Italo Disco - Caprice Radio", url = "http://79.111.119.111:8000/italodisco"},
    {name = "Ясен Бит 18+", url = "https://5.restream.one/1198_1"},
    {name = "RCM DEEP", url = "https://relay.radiotoolkit.com/rcmdeep"},
    {name = "Эльдорадио Eldo Radio 1014 St Petersburg", url = "http://emgspb.hostingradio.ru/eldoradio128.mp3"},
    {name = "Радио Классик Classic Gold", url = "http://jfm1.hostingradio.ru:14536/gcstream.mp3"},
    {name = "Radio Jazz 891 - Classic JAZZ", url = "http://jfm1.hostingradio.ru:14536/ijstream.mp3"},
    {name = "101Ru Россия Топ 50", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/34?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjczLjEzMC4zNy43OSIsInVzZXJhZ2VudCI6InB5dGhvbi1yZXF1ZXN0c1wvMi4yNS4xIiwidWlkX2NoYW5uZWwiOiIzNCIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MTY0MzcyNDh9.LRVefwOLisK0VGs3qvDvuYZ31k4mW7VJFd4mbWQQlD8.aac"},
    {name = "Radio Caprice - Relaxation Music", url = "http://79.120.39.202:9109/"},
    {name = "Вера", url = "http://77.39.8.49:8000/vera_air_96"},
    {name = "Гопфм", url = "https://radiorecord.hostingradio.ru/gop96.aacp"},
    {name = "Детское Радио", url = "http://ic7.101.ru:8000/v14_1"},
    {name = "THT Music Radio", url = "http://tntradio.hostingradio.ru:8027/tntradio128.mp3"},
    {name = "Радио Рекорд Нафталин FM", url = "http://radiorecord.hostingradio.ru/naft96.aacp"},
    {name = "Record Trancemission", url = "https://radiorecord.hostingradio.ru/tm96.aacp"},
    {name = "Radio Caprice - Symphonic Power Metal", url = "http://213.141.131.10:8000/symphopower.m3u"},
    {name = "Radio Caprice - Black Metal", url = "http://79.120.77.11:9003/"},
    {name = "Ретро Хит", url = "http://air.volna.top/Retro"},
    {name = "Z-FM Фронтовое", url = "https://zfm.hostingradio.ru/zfm128.mp3"},
    {name = "Старый Портфель", url = "https://lk.castnow.ru:8100/oldbrief-320.mp3"},
    {name = "CRN - Hardcore Raphorrorcore", url = "http://79.120.39.202:8000/hardcorerap"},
    {name = "Классика Жанра", url = "https://s.fmplay.ru/e9d523c7"},
    {name = "РАДИО РЕКОРД 256K", url = "http://radiorecord.hostingradio.ru/rr_spb"},
    {name = "РЕТРО FM 320K", url = "http://emgregion.hostingradio.ru:8064/moscow.retrofm.mp3"},
    {name = "Radio Caprice - Acoustic Guitar", url = "http://79.120.39.202:8000/acousticguitar.m3u"},
    {name = "Рок АРСЕНАЛ - Rock Arsenal", url = "http://online.rockarsenal.ru:8000/rockarsenal"},
    {name = "Radio Caprice - Old School Hip-Hop Rap", url = "http://213.141.131.10:8002/oldschoolhiphop"},
    {name = "Radio Gameplay", url = "https://c22.radioboss.fm:8144/GamePlay"},
    {name = "Radio Caprice - Neo-Progressive Rock", url = "http://79.111.119.111:9095/;stream/1"},
    {name = "Вечная Молодость", url = "http://misato.ru-hoster.com:8037/stream"},
    {name = "Radio Caprice - Thrash Metal", url = "http://79.120.77.11:9101/"},
    {name = "Anisonfm", url = "http://anison.fm/anison.m3u"},
    {name = "Relax FM Latino", url = "https://pub0302.101.ru:8443/stream/trust/mp3/128/265"},
    {name = "Radio Caprice - Dark Jazz", url = "http://79.120.39.202:9137/"},
    {name = "Радио Сектор Sector SPACE Flac", url = "http://89.223.45.5:8000/space-flac"},
    {name = "Radio Caprice - Future Garage Chillstep Deep Post Dubstep", url = "http://79.120.39.202:8002/futuregarage"},
    {name = "Литературное Радио", url = "http://79.137.234.183:8000/;stream.mp3"},
    {name = "Град Петров", url = "http://stream.grad-petrov.ru:8093/aac"},
    {name = "Radio Caprice - Retrowave", url = "http://79.120.39.202:9125/"},
    {name = "JAZZ MANOUCHE GYPSY JAZZ GYPSY SWING - Radio Caprice", url = "http://79.120.77.11:8004/manouche"},
    {name = "Radio Источник", url = "http://s0.radioheart.ru:8000/VM73179"},
    {name = "-=- Relax-Fm -=-", url = "http://ic4.101.ru:8000/stream/air/aac/64/200"},
    {name = "Radio Caprice - Drum 'N' Bass [2]", url = "http://79.111.14.76:8000/drumbass"},
    {name = "Russian Radio Golden Gramophone", url = "http://rr-zolotoigrammofon.hostingradio.ru/zolotoigrammofon96.aacp"},
    {name = "Старое Радио - Музыка", url = "http://www.staroeradio.ru/music128.m3u"},
    {name = "Radio Caprice Romantic Music Collection", url = "http://79.120.39.202:8002/romantic"},
    {name = "Radio Record 00'S", url = "https://radiorecord.hostingradio.ru/200096.aacp"},
    {name = "Radio Caprice - Rock Ballads", url = "http://79.120.77.11:9059/;stream.aac"},
    {name = "Russian Punk Rock", url = "http://79.120.77.11:8000/punkru"},
    {name = "Радио «Luxury Lounge»", url = "http://188.40.109.122:8000/ices1"},
    {name = "Anima Amoris Minimal Deep Techno", url = "https://amoris.sknt.ru/minimal.mp3"},
    {name = "Radio Caprice - Gothic Black Metal", url = "http://79.120.39.202:8000/gothblackmet"},
    {name = "Наше Радио Панки-Хой", url = "http://nashe1.hostingradio.ru/nashepunks.mp3"},
    {name = "Бизнес ФМ Санкт-Петербург 1074 FM", url = "http://bfmreg.hostingradio.ru/spb.bfm128.mp3"},
    {name = "Royal Radio 968FM", url = "https://c22.radioboss.fm/stream/186"},
    {name = "Радио 107", url = "http://62.183.34.109:8000/radio107_256.mp3"},
    {name = "Радио Монте-Карло", url = "https://mc-mcgold.hostingradio.ru/mcgold96.aacp"},
    {name = "DONAT FM - Русский Рок", url = "http://c6.radioboss.fm:8097/stream"},
    {name = "Radio Caprice Dark Techno HQ", url = "http://79.111.14.76:8000/darktechno"},
    {name = "Russkoe Radio", url = "http://rusradio.hostingradio.ru/rusradio96.aacp"},
    {name = "Promodj Top100", url = "http://radio.promodj.com/top100-192"},
    {name = "Radio Caprice-Gregorian Chant", url = "http://213.141.131.10:8002/chants"},
    {name = "Radio Sefon", url = "http://193.42.108.9:8010/stream"},
    {name = "Радио Забытая Кассета", url = "https://casseta-disco.ru:6275/stream?x=1711899723831"},
    {name = "Radio Caprice - Stoner Metal", url = "http://79.120.77.11:9089/"},
    {name = "101Ru - Boney M", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/114"},
    {name = "101Ru СССР 30-50", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/46"},
    {name = "Radio Caprice - Progressive Rock", url = "http://79.111.119.111:9121/"},
    {name = "Радио Монте Карло - Covers", url = "https://mc-covers.hostingradio.ru/mccovers96.aacp"},
    {name = "Monte Carlo", url = "https://montecarlo.hostingradio.ru/montecarlo96.aacp"},
    {name = "Казак FM", url = "https://radio.mediacdn.ru/kazak_fm.mp3"},
    {name = "DFM Trap", url = "https://dfm-dfmtrap.hostingradio.ru/dfmtrap96.aacp"},
    {name = "Радио СССР", url = "https://myradio24.org/ussr"},
    {name = "Radio Caprice - Vocal Trance", url = "http://79.120.39.202:9031/;"},
    {name = "Radio Caprice - Melodic Death Metal", url = "http://79.120.77.11:8000/melodicdeath.m3u"},
    {name = "DFM DISCO", url = "https://dfm-disco.hostingradio.ru/disco96.aacp"},
    {name = "Русская Волна", url = "https://ru2.volna.top/RuWave48"},
    {name = "Звезда ТВ🌟ТВЧ📺", url = "https://tvchannelstream1.tvzvezda.ru/cdn/tvzvezda/playlist.m3u8"},
    {name = "Radio Record Organic", url = "http://radiorecord.hostingradio.ru/organic96.aacp"},
    {name = "Radio Caprice - Piano", url = "http://79.120.77.11:8002/piano"},
    {name = "Радио Монте Карло - Wonderful Blues", url = "https://mc-blues.hostingradio.ru/blues96.aacp"},
    {name = "Radio Caprice - Baroque", url = "http://79.111.14.76:8000/baroque"},
    {name = "101Ru Bard Songs - Авторская Песня", url = "https://ic6.101.ru:8000/stream/pro/aac/64/35"},
    {name = "Радио Рекорд Медляк FM", url = "http://radiorecord.hostingradio.ru/mdl96.aacp"},
    {name = "Всемирная Радиосеть World Radio Network – Russia", url = "http://streaming.edmradio.online:8025/WRN-R"},
    {name = "Record Chill House", url = "https://radiorecord.hostingradio.ru/chillhouse96.aacp"},
    {name = "Comedy Radio", url = "http://pub0302.101.ru:8000/stream/reg/mp3/128/region_comedy_31"},
    {name = "Radio Record Chill House", url = "https://radiorecord.hostingradio.ru/organic96.aacp"},
    {name = "SECTOR Jazz", url = "http://89.223.45.5:8000/jazz-flac"},
    {name = "Monte Carlo Gold Collection", url = "https://montecarlo.hostingradio.ru/mcgold96.aacp"},
    {name = "Читаем Евангелие", url = "https://radio.azbyka.ru/evangelie"},
    {name = "Radio Jazz 891 - JAZZ Vocals", url = "http://jfm1.hostingradio.ru:14536/jvstream.mp3"},
    {name = "Radio Caprice - Dark Techno", url = "http://79.111.14.76:9139/"},
    {name = "Родные Нулевые - Русское Радио", url = "https://rr-00.hostingradio.ru/rr0096.aacp"},
    {name = "Детский Канал - Русское Радио", url = "https://rr-detskijkanal.hostingradio.ru/detskijkanal96.aacp"},
    {name = "WRN Rus", url = "http://shoutcast.wrn.org:8025/WRN-R"},
    {name = "Caprice Radio - Dark Psy", url = "http://79.111.119.111:8000/darkpsytrance"},
    {name = "DFM - Breakbeat", url = "https://dfm-breakbeat.hostingradio.ru/breakbeat96.aacp"},
    {name = "Radio Caprice - Minimal Tech House [1]", url = "http://79.111.119.111:8002/mintechhouse"},
    {name = "Радио Сектор Sector Geny Flac", url = "http://89.223.45.5:8000/geny-flac"},
    {name = "Radio Monte Carlo Golf Club", url = "http://montecarlo.hostingradio.ru/golfcup96.aacp"},
    {name = "Record Trance Classics", url = "https://radiorecord.hostingradio.ru/trancehits96.aacp"},
    {name = "Radio Caprice - Power Metal", url = "http://79.120.77.11:9099/"},
    {name = "HIT FM", url = "https://hitfm.hostingradio.ru/hitfm96.aacp"},
    {name = "Radio Record Breaks", url = "https://radiorecord.hostingradio.ru/brks96.aacp"},
    {name = "Radio Record Phonk", url = "http://radiorecord.hostingradio.ru/phonk96.aacp"},
    {name = "Sw-Radio Russisch", url = "http://www.segenswelle.de:8000/russisch"},
    {name = "Чипльдук", url = "http://radio.4duk.ru/4duk128.mp3"},
    {name = "Radio Caprice - Eurobeathi-Nrg", url = "http://79.120.39.202:9159/listen.pls"},
    {name = "Radio Caprice - Dark Electro Aggrotech", url = "http://79.120.39.202:8002/darkelectro"},
    {name = "Радио Ваня - Не Лихие 90-Е", url = "https://stream.pcradio.ru/vanya_90-med"},
    {name = "Легенда", url = "https://radiolegenda.ru:8001/64.aac"},
    {name = "Radio Record - Russian Hits", url = "https://radiorecord.hostingradio.ru/russianhits96.aacp"},
    {name = "Kamchatka Live Chillout", url = "https://radio.kamchatkalive.ru:8103/chillout"},
    {name = "Radio Caprice - African Folk Ethnic Music 320K", url = "http://79.120.39.202:8004/africanfolk"},
    {name = "BAG", url = "http://radio-holding.ru:9000/rfm_aac_64"},
    {name = "Орфей", url = "https://orfeyfm.hostingradio.ru:8034/orfeyfm96.aacp"},
    {name = "Radio Caprice - Symphonic Gothic Metal", url = "http://213.141.131.10:8002/symphogoth"},
    {name = "Radio Caprice - Hip-Hop", url = "http://79.120.77.11:9067/;stream/1"},
    {name = "Stand Up", url = "https://pub0102.101.ru:8443/stream/pro/aac/64/447"},
    {name = "Radio Caprice - Death Metal", url = "http://79.120.77.11:9083/"},
    {name = "Radio Caprice - Russian Rock", url = "http://79.120.77.11:9029/listen.pls"},
    {name = "Папино Радио", url = "http://a1.radioheart.ru:8001/RH58197"},
    {name = "Радио Победа", url = "https://radio.gtrklnr.ru:8443/victori.fm"},
    {name = "Dancehall Raggamuffin - Caprice Radio", url = "http://79.111.14.76:8000/dancehall"},
    {name = "Moskva FM", url = "http://icecast.vgtrk.cdnvideo.ru/moscowfm128?v=1550419566950"},
    {name = "Radio Caprice - PSYCHOBILLY", url = "http://79.111.119.111:8002/psychobilly"},
    {name = "Promodj Too Nu", url = "http://radio.promodj.com/toonu-192"},
    {name = "Radio Caprice - Depressive Black Metal", url = "http://79.111.119.111:9011/;"},
    {name = "Радио Гордость", url = "https://rgordost.hostingradio.ru/rgordost64.aacp"},
    {name = "Radio Caprice - Neurofunk", url = "http://79.111.119.111:8004/neurofunk"},
    {name = "Радио Орфей - Популярная Классика 256Kbps", url = "https://channels.fonotron.ru:8000/Chan_72_256.mp3"},
    {name = "Radio Caprice - Instrumental Music", url = "http://79.120.77.11:8000/instrumental"},
    {name = "Radio Caprice - Easy Listening", url = "http://79.111.14.76:8002/easylistening"},
    {name = "Russian Rap Hip Hop - Caprice Radio", url = "http://79.120.77.11:8000/rapru"},
    {name = "Record Hard Bass", url = "https://radiorecord.hostingradio.ru/hbass96.aacp"},
    {name = "Radio Caprice - Female Vocal In Metal Music", url = "http://79.111.14.76:8000/femalemetal?type=.mp3"},
    {name = "Space Rock - Radio Caprice Acc48", url = "http://79.111.119.111:8002/spacerock"},
    {name = "Radio Caprice - Brutal Death Metal", url = "http://79.111.119.111:8000/brutaldeathmetal.m3u"},
    {name = "Радио Sputnik Россия 256 Кбитс", url = "https://icecast-rian.cdnvideo.ru/voicerushi"},
    {name = "Radio Caprice - Roots Reggae", url = "http://79.111.119.111:9047/"},
    {name = "Radio Caprice - Melodic Power Metal", url = "http://79.111.119.111:8000/melodicpower.m3u"},
    {name = "101Ru - House", url = "https://pub0202.101.ru:8000/stream/trust/mp3/128/10"},
    {name = "Наше Радио Классик Рок", url = "http://nashe1.hostingradio.ru/nasheclassic.mp3"},
    {name = "Metaradio", url = "https://s2.metaradio.ru/mradio.aacp"},
    {name = "Radio Caprice - АВТОРСКАЯ БАРДОВСКАЯ ПЕСНЯ", url = "http://79.120.39.202:9021/"},
    {name = "Радио Бесконечность", url = "https://misato.ru-hoster.com:8067/stream"},
    {name = "Countryfolk Blues - Radio Caprice", url = "http://79.120.77.11:8004/countryblues"},
    {name = "Biker FM", url = "https://listen4.myradio24.com/69846"},
    {name = "RADCAP: ATMOSPHERIC AMBIENT BLACK METAL", url = "http://79.120.39.202:8000/aabmds"},
    {name = "Radio Caprice - Computer Video Game Music Ost Score Soundrack", url = "http://79.120.39.202:9139/"},
    {name = "Радио Орфей - Классика Без Границ 192Kbps", url = "https://orfeyfm.hostingradio.ru:8034/orpheuscwb192.mp3"},
    {name = "Радио СПУТНИК Radio Sputnik", url = "http://online.sputnikfm.ru:8000/sputnik_mp3"},
    {name = "Radio Caprice - Deep Chill House [2]", url = "http://79.120.39.202:8000/deephouse"},
    {name = "Record Neurofunk", url = "https://radiorecord.hostingradio.ru/neurofunk96.aacp"},
    {name = "Radio Kamchatka LIVE Chillout", url = "http://radio.kamchatkalive.ru:8103/chillout"},
    {name = "Авторская Песня101", url = "https://pub0101.101.ru:8000/stream/pro/aac/64/35"},
    {name = "Europapplus Top 40", url = "http://eptop128.streamr.ru/"},
    {name = "Silver Rain", url = "http://silverrain.hostingradio.ru/silver128.mp3"},
    {name = "Хорошее Радио", url = "https://hr.amgradio.ru/Horoshee"},
    {name = "Radio Caprice - Progressive Metal", url = "http://79.120.77.11:8000/progmetal"},
    {name = "DFM - Organic House", url = "https://dfm-organichouse.hostingradio.ru/organichouse96.aacp"},
    {name = "Donat FM - Russian Rock", url = "http://c6.radioboss.fm:8097/autodj"},
    {name = "Radio 7 Moscow", url = "https://emgregion.hostingradio.ru:8064/moscow.radio7.mp3"},
    {name = "Yoga Radio", url = "http://play.yogaradio.fm:8000/YOGAr256.m3u"},
    {name = "Radio Caprice - Folk Black Metal", url = "http://79.120.12.130:8002/folkblackmet"},
    {name = "Радио Рекорд Jungle", url = "http://radiorecord.hostingradio.ru/jungle96.aacp"},
    {name = "Best FM", url = "http://nashe.streamr.ru/best-128.mp3"},
    {name = "Clavecincembaloharpsichord - Radio Caprice", url = "http://213.141.131.10:8004/clavecin"},
    {name = "Авторадио Дискотека 90 Х", url = "https://pub0202.101.ru:8443/stream/pro/aac/64/74"},
    {name = "Радио Сектор Sector NEXT Flac", url = "http://89.223.45.5:8000/next-flac"},
    {name = "Radio Caprice - Breakbeat", url = "https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://79.120.39.202:9051/listen.pls&t=.pls"},
    {name = "Радио ТВ Твоя Волна", url = "https://icecast-tvoyavolna.cdnvideo.ru/tvoyavolna"},
    {name = "Радио Восток России", url = "http://138.201.190.251:8000/;stream.nsv"},
    {name = "Soundpark Deep", url = "https://relay1.radiotoolkit.com/spdeep"},
    {name = "Радио Культура", url = "http://icecast.vgtrk.cdnvideo.ru/kulturafm"},
    {name = "Radio Caprice - Free Jazz", url = "http://79.111.14.76:8002/freejazz"},
    {name = "МУЗКОМ", url = "https://geshou.s02.radio-tochka.com:5005/stream"},
    {name = "Радио Турист", url = "https://listen7.myradio24.com/turist"},
    {name = "Sputnik News Belarussian", url = "https://nfw.ria.ru/flv/audio.aspx?ID=68862011&amp;type=mp3"},
    {name = "Радио НОД", url = "https://s05.volnorez.com/live-app/855343"},
    {name = "Радио Республика ФМ 1048 FM", url = "http://193.228.161.99:8080/republic.fm"},
    {name = "Radio Caprice Math Rock", url = "http://79.120.39.202:8000/mathrock"},
    {name = "Europapplus Party", url = "http://epdop.hostingradio.ru:8033//epparty128.mp3"},
    {name = "Radio Caprice - Psychedelic Rock", url = "http://79.111.119.111:9027/listen.pls"},
    {name = "Радио Радонеж Москва 7292 УКВ", url = "http://icecast.radonezh.cdnvideo.ru:8000/rad128"},
    {name = "Радио Рекорд - Dream Dance", url = "https://hls-01-radiorecord.hostingradio.ru/record-dream/playlist.m3u8"},
    {name = "Radio Caprice - Instrumental Rock", url = "http://79.120.39.202:8002/instrumentalrock"},
    {name = "Radio Record - Reggae", url = "http://radiorecord.hostingradio.ru/reggae96.aacp"},
    {name = "Radio Record - Disco Funk", url = "https://radiorecord.hostingradio.ru/discofunk96.aacp"},
    {name = "Heavy Music Atmospheric Radio", url = "http://stream.heavy-music.net:8176/stream"},
    {name = "Золотой Граммофон", url = "https://rr-zolotoigrammofon.hostingradio.ru/zolotoigrammofon96.aacp"},
    {name = "Радио МЕТРО 102,4", url = "http://stream.radiometro.ru:8230/"},
    {name = "DFM - Dancehall", url = "https://dfm-dancehall.hostingradio.ru/dancehall96.aacp"},
    {name = "DFM - Tech House", url = "https://dfm-techhouse.hostingradio.ru/techhouse96.aacp"},
    {name = "Radio Caprice - Minimal Techno [1]", url = "http://79.120.39.202:8002/mintechno"},
    {name = "Radio Caprice - Instrumental Metal", url = "http://79.111.119.111:8004/instrumentalmetal"},
    {name = "Radiogora - Electro", url = "http://listen.radiogora.ru:8000/electro128"},
    {name = "Звезда 956 FM", url = "https://radio.mediacdn.ru/radio/zvezda/zvezda_96"},
    {name = "Radio Record Hardstyle", url = "https://radiorecord.hostingradio.ru/teo96.aacp"},
    {name = "Радио А", url = "https://stream05.pcradio.ru/rad_rdbryanck-med"},
    {name = "Радио Родные Песни", url = "https://rodpesni.amgradio.ru/rp"},
    {name = "Радио Лихие Девяностые", url = "https://rr-90.hostingradio.ru/rr9096.aacp"},
    {name = "Волшебный Шансон", url = "https://chanson.hostingradio.ru:8041/chanson128.mp3"},
    {name = "Omsk FM", url = "http://www.omskfm.ru:8000/881-128.mp3"},
    {name = "Radio Caprice - Medieval Folk", url = "http://213.141.131.10:8004/medievalfolk"},
    {name = "CRN - Hip-Hop", url = "http://79.120.77.11:8000/hiphop"},
    {name = "Radio Caprice - Rock Metal Ballads", url = "http://79.120.77.11:8002/rockballads"},
    {name = "Россия 90-Х", url = "https://pub0202.101.ru:8443/stream/pro/aac/64/33"},
    {name = "Старое Радио Детское - Old Radio Detskoe 64", url = "http://195.91.237.50:8000/detskoe64"},
    {name = "RADCAP: PROGRESSIVE BLACK POST-BLACK BLACKGAZE", url = "http://79.111.14.76:8000/postblack"},
    {name = "Chill Russia", url = "https://chillrussia.ru/chillradio"},
    {name = "Kinozaltv", url = "https://listen4.myradio24.com/kinozaltv"},
    {name = "Radio Caprice - Gabber Early Mainstream Hardcore", url = "http://213.141.131.10:8002/gabber"},
    {name = "Donat FM - European Hits", url = "http://c6.radioboss.fm:8089/autodj"},
    {name = "Пилигрим", url = "http://radiopiligrim.ru:8000/live"},
    {name = "Кекс FM", url = "https://dorognoe.hostingradio.ru/keksfm64.aac"},
    {name = "Мухомор", url = "https://listen7.myradio24.com/muhomor"},
    {name = "Radio Caprice ACID CLUB GROOVE JAZZ", url = "http://79.111.14.76:8000/acidjazz"},
    {name = "Radio Record Synthwave", url = "http://radiorecord.hostingradio.ru/synth96.aacp"},
    {name = "Radiorecordru Techno", url = "https://radiorecord.hostingradio.ru/techno96.aacp"},
    {name = "Радио Сектор Sector SPACE", url = "http://89.223.45.5:8000/space-160"},
    {name = "Random Chiptune Radio", url = "http://79.120.11.40:8000/chiptune.ogg"},
    {name = "Читаем Добротолюбие", url = "https://radio.azbyka.ru/dobrotolubie"},
    {name = "Radio Anonymous", url = "http://anon.fm:8000/radio.m3u"},
    {name = "Anima Amoris Deep Tech House", url = "https://amoris.sknt.ru/deeptech.mp3"},
    {name = "Radio Caprice - Metalcore", url = "http://79.120.39.202:8000/metalcore.m3u"},
    {name = "Royal Trip Hop", url = "https://royalradio.space/TH"},
    {name = "Anima Amoris [Trance]", url = "http://anima.sknt.ru/trance.mp3"},
    {name = "DFM - Gangsta Deep", url = "https://dfm-gangstadeep.hostingradio.ru/gangstadeep96.aacp"},
    {name = "Badbeatradio", url = "http://misato.ru-hoster.com:8061/badbeatradio"},
    {name = "Диполь", url = "https://icecast-sibinformburo.cdnvideo.ru/dipolfm"},
    {name = "Capital FM Moscow", url = "http://icecast.vgtrk.cdnvideo.ru/capitalfmmp3"},
    {name = "Monsters Of Rock USSR", url = "https://stream-51.zeno.fm/6nbz7p2w908uv"},
    {name = "Гусьдипхаус", url = "https://stream.radiogoose.ru:8120/play"},
    {name = "RADCAP: TRIP-HOP", url = "http://79.111.14.76:8000/triphop"},
    {name = "Afrobeat Afrobeats - Radio Caprice", url = "http://79.120.39.202:8000/afrobeat"},
    {name = "Radio Caprice - Folk Death Metal", url = "http://79.120.12.130:8000/folkdeathmet"},
    {name = "Thrash Heavy Metal - Caprice Radio", url = "http://213.141.131.10:8000/thrashheavy"},
    {name = "Милицейская Волна", url = "https://radiomv.hostingradio.ru:80/radiomv256.mp3"},
    {name = "Radio Caprice - Space Music", url = "http://79.111.119.111:8000/spacemusic"},
    {name = "Radio Caprice Minimalism", url = "http://213.141.131.10:8000/minimalism"},
    {name = "Blues - Caprice Radio", url = "http://79.120.77.11:8000/blues"},
    {name = "Radio Caprice - Deathcore", url = "http://79.111.14.76:8000/deathcore"},
    {name = "СПРАВЕДЛИВАЯ РОССИЯ", url = "https://spravedlivo.hostingradio.ru:8022/spravedlivo128.mp3"},
    {name = "Radio Caprice - Guitar Jazz", url = "http://79.120.77.11:8002/guitarjazz"},
    {name = "Радио Орфей - Классика Эстрады", url = "https://channels.fonotron.ru:8000/Chan_7_192.mp3"},
    {name = "Promodj - Too Deep", url = "http://radio.promodj.com:8000/toodeep-192"},
    {name = "Xddance", url = "http://94.241.171.205:8000/stream"},
    {name = "Пилигрим Библия", url = "http://radiopiligrim.ru:8000/bible"},
    {name = "Radio 2000X", url = "http://air.radio2000x.com:8000/stream"},
    {name = "Radio Record Lo-Fi", url = "https://radiorecord.hostingradio.ru/lofi96.aacp"},
    {name = "Enigmatic Immersion", url = "http://radio.enigmatic.su:8040/radio"},
    {name = "Verdure Station", url = "http://air.verdure.net:8881/stream"},
    {name = "Nebula", url = "https://cast4.my-control-panel.com/proxy/nebulara/stream"},
    {name = "Radio Caprice - Lo-Fi", url = "http://79.111.14.76:8000/lo-fi"},
    {name = "Radio Caprice - Nu Metal 128", url = "http://79.111.14.76:8000/numetal"},
    {name = "Record Radio 70'S", url = "https://radiorecord.hostingradio.ru/197096.aacp"},
    {name = "Удалое Радио", url = "http://l29.no-ip.org:8002/listen.pls"},
    {name = "Radio Caprice - Crust Punk", url = "http://79.120.39.202:9123/"},
    {name = "Радио России AAC", url = "http://icecast.vgtrk.cdnvideo.ru/rrzonam_aac_64kbps"},
    {name = "Radio Caprice - Electro House", url = "http://79.111.14.76:9075/"},
    {name = "Радио 54", url = "http://91.202.68.50:8000/;stream.mp3"},
    {name = "Radio Monte Carlo - Bossa Nova", url = "https://mc-mcbossa.hostingradio.ru/mcbossa96.aacp?listening-from-radio-garden=1645969315"},
    {name = "Beta Anonfm", url = "https://radio.anonymous.delivery/music.mp3"},
    {name = "Radio Caprice - Psychedelic Folk", url = "http://213.141.131.10:8000/psychfolk.m3u"},
    {name = "Radio Caprice - Stoner Rock", url = "http://79.111.119.111:9025/"},
    {name = "Radio Caprice - Indian Folk", url = "http://79.111.14.76:8000/indianfolk"},
    {name = "Жития Святых", url = "https://radio.azbyka.ru/lives"},
    {name = "Radio Caprice - Contemporary Jazz", url = "http://79.111.119.111:8002/contemporaryjazz"},
    {name = "Radio Caprice - Viking Metal", url = "http://79.111.14.76:8000/vikingmetal.m3u"},
    {name = "Radio Caprice - Psybient", url = "http://79.111.14.76:9023/;"},
    {name = "Воскресение", url = "http://217.24.181.164:8000/stream.ogg"},
    {name = "Radio Caprice - Classical Piano", url = "http://79.120.39.202:9069/;"},
    {name = "DFM POP GOLD 2000S", url = "https://dfm-popgold00.hostingradio.ru/popgold0096.aacp"},
    {name = "[Rocktime-Radio]", url = "http://a9.radioheart.ru:8049/rocktime"},
    {name = "1023 FM Хомякс Луганск", url = "https://radio.play-fm.ru:8001/homyak"},
    {name = "101Ru - Electronic", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/132"},
    {name = "Приморская Волна 900 FM", url = "http://inhold.org:8000/primvolna-ussuriysk"},
    {name = "Radio Caprice - Russian Folk", url = "http://79.120.77.11:9057/;"},
    {name = "C-Pop Chinese Popular Music", url = "http://213.141.131.10:8000/cpop"},
    {name = "Promodj - Yoo", url = "http://radio.promodj.com:8000/yo-192"},
    {name = "Радио STORY FM", url = "https://storyfm.hostingradio.ru:8031/storyfm128.mp3?1701610665147"},
    {name = "Radio Caprice Indie Electronic", url = "http://79.111.119.111:8002/indieelectronic"},
    {name = "Seva Ru", url = "https://seva.ru/radio/stream"},
    {name = "CRN - Rap", url = "http://79.120.77.11:8000/rap"},
    {name = "101Ru ABBA", url = "http://pub0101.101.ru:8000/stream/pro/aac/64/104?"},
    {name = "Ралио Релакс Москва 90,8 FM", url = "http://pub0302.101.ru:8000/stream/air/aac/64/200"},
    {name = "Techno Trance Techtrance", url = "http://213.141.131.10:8000/techtrance.m3u"},
    {name = "Радио Орфей - Русская Классика 256Kbps", url = "https://channels.fonotron.ru:8000/Chan_73_256.mp3"},
    {name = "Radio Caprice Triphop", url = "https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://79.111.14.76:9013/listen.pls&t=.pls"},
    {name = "Радио Рекорд Black Rap", url = "http://radiorecord.hostingradio.ru/yo96.aacp"},
    {name = "Радио Гусь", url = "https://stream.radiogoose.ru:8000/play"},
    {name = "161 FM", url = "http://stream.161.fm:8000/256"},
    {name = "Автодор", url = "https://avtodor-tr.hostingradio.ru/avtodortr128.mp3"},
    {name = "Радио Курс", url = "https://radio.dcatk.pro/radio.mp3"},
    {name = "XXL FM", url = "http://91.211.246.42:8000/XXL-FM"},
    {name = "CORE Radio", url = "http://194.58.97.117:8000/coreradio"},
    {name = "Radio Caprice - Cool Jazz", url = "http://79.120.39.202:9085/;"},
    {name = "Radio Fish", url = "https://listen1.myradio24.com/8317"},
    {name = "Comfort FM", url = "https://listen7.myradio24.com/118966"},
    {name = "Radio Caprice - Folk Metal", url = "http://79.120.39.202:8000/folkmetal.m3u"},
    {name = "Radio Radiola", url = "http://online.gkvr.ru/radiola_eka_128.mp3"},
    {name = "Ultrafan", url = "http://radioultrafan.ru:8000/192"},
    {name = "Radio Caprice - Progressive Trance", url = "http://79.120.39.202:9025/;"},
    {name = "Радио МЕГАПОЛИС", url = "http://online.radio-megapolis.ru:8000/megapolis"},
    {name = "Радио Мир Барнаул", url = "https://icecast-mirtv.cdnvideo.ru/radio_mir4_256"},
    {name = "920 Москва FM", url = "http://icecast.vgtrk.cdnvideo.ru:8000/moscowfm128"},
    {name = "DFM DANCE GOLD 2000S", url = "https://dfm-dancegold00.hostingradio.ru/dancegold0096.aacp"},
    {name = "Street Beat FM", url = "https://glassroomrec.s02.radio-tochka.com:5015/stream"},
    {name = "Dance 90", url = "https://ppr90.status-media.ru/ppr_90.mp3"},
    {name = "Radiomv Russian", url = "https://ice.radiomv.co:8440/russian.mp3"},
    {name = "Релиз", url = "https://listen.myrh.ru/radioreliz"},
    {name = "Радио 7 На Семи Холмах - Настроение Счастья", url = "https://radio7.hostingradio.ru:8040/radio7_happiness64.aacp"},
    {name = "Radio Caprice - Forest Psytrance", url = "http://213.141.131.10:8004/forestpsytrance"},
    {name = "Веда Радио", url = "http://listen.vedaradio.fm:8000/veryhigh.m3u"},
    {name = "Радио Пассаж", url = "http://listen.radiopassazh.ru/aac-48"},
    {name = "Радио Рекорд Neurofunk", url = "http://radiorecord.hostingradio.ru/neurofunk96.aacp"},
    {name = "ДЕТСКОЕ РАДИО [DETSKOE RADIO BABY FM", url = "http://a5.radioheart.ru:8012/nonstop"},
    {name = "RT Español", url = "https://rt-esp.rttv.com/dvr/rtesp/playlist_64Kb.m3u8"},
    {name = "Кальян Рэп DFM", url = "https://dfm-kalianrap.hostingradio.ru/kalianrap96.aacp"},
    {name = "Radio DFM Ufa 915 FM", url = "http://92.50.177.134:8000/dfm_ufa"},
    {name = "Radio Caprice Jazz Modern Creative", url = "http://79.120.77.11:8000/mcreative"},
    {name = "Радио Рекорд Dubstep", url = "http://radiorecord.hostingradio.ru/dub96.aacp"},
    {name = "Макс FM", url = "https://maksfm.hostingradio.ru/maksfm320.mp3"},
    {name = "Radio Maximum - Rammstein", url = "https://maximum-rammstein.hostingradio.ru/rammstein96.aacp"},
    {name = "Радио Рекорд Dream Dance", url = "http://radiorecord.hostingradio.ru/dream96.aacp"},
    {name = "Promodj - Dubstep", url = "http://radio.promodj.com/dubstep-192"},
    {name = "Https:Streamstudio21Rustudio2196Aacp", url = "https://stream.studio21.ru/studio2196.aacp"},
    {name = "101Ru ДДТ", url = "http://pub0302.101.ru:8000/stream/pro/aac/64/112?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6Ijg4LjIyMy42OC44NCIsInVzZXJhZ2VudCI6Ik1vemlsbGFcLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0OyBydjo5MS4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvOTEuMCBXYXRlcmZveFwvOTEuNC4yIiwidWlkX2NoYW5uZWwiOiIxMTIiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwiZXhwIjoxNjQxNjcxOTg3fQ.k_WsYHWH-yoxEogmsvirk_IcKDdHKpTLDj5rCoF0B2E"},
    {name = "Radio Caprice - Russian Pop Music", url = "http://79.120.77.11:8000/popru"},
    {name = "Весёлый Dance - Радио Ваня", url = "https://stream.pcradio.ru/vanya_fundance-med"},
    {name = "CRN - Old School Hip-Hoprap", url = "http://213.141.131.10:8000/oldschoolhiphop"},
    {name = "Старое Радио - Old Radio 32", url = "http://195.91.237.50:8000/ices32"},
    {name = "CRN - Abstractexperimental Raphip-Hop", url = "http://79.111.14.76:8000/abstracthiphop"},
    {name = "Europa Plus Acoustic", url = "http://epdop.hostingradio.ru:8033/acoustic128.mp3"},
    {name = "Radio 42 FM — Радио «Воруй-Убивай»", url = "http://listen.42fm.ru:8000/stealkill-8.0.ogg"},
    {name = "Радио Орфей - Классика Киномузыки", url = "https://channels.fonotron.ru:8000/Chan_9_192.mp3"},
    {name = "Radio Caprice - Suomisaundi Freeform Psytrance Spugedelic Trance [2]", url = "http://79.120.77.11:8000/suomisaundi"},
    {name = "Radio Sibir", url = "https://stream.radiosibir.ru:8093/om2"},
    {name = "ХАЙП FM", url = "https://hfm.amgradio.ru/HypeFM"},
    {name = "Radio Caprice - Soul Jazz", url = "http://79.111.14.76:8002/souljazz"},
    {name = "Coffee FM", url = "https://stream.pcradio.ru/Vintazh_kafe-med"},
    {name = "Культура AAC+", url = "https://icecast-vgtrk.cdnvideo.ru/kulturafm_aac_64kbps"},
    {name = "Пилот FM - Dance", url = "https://online.pilotfm.ru/pilot_dance"},
    {name = "Rockabilly - Caprice Radio", url = "http://79.111.14.76:8000/rockabilly"},
    {name = "Детский Хит - Kids Hit", url = "http://deti.volna.top/Deti"},
    {name = "Комсомольская Правда Воронеж 977 FM", url = "http://kpradio.hostingradio.ru:8000/voroneg.radiokp128.mp3"},
    {name = "Радио Монте Карло - Chill Lounge", url = "https://mc-chilllonge.hostingradio.ru/chilllonge96.aacp"},
    {name = "Радио России Калуга", url = "http://radio.gtrk-kaluga.ru/russiafm_kaluga"},
    {name = "Радио Монте Карло - Meditation", url = "https://mc-meditation.hostingradio.ru/meditation96.aacp"},
    {name = "На Шашлыки - Радио Рекорд", url = "https://hls-01-radiorecord.hostingradio.ru/record-nashashlyki/playlist.m3u8"},
    {name = "Anima Amoris Dub Techno", url = "https://amoris.sknt.ru/dubtechno"},
    {name = "Күңел Радиосы", url = "http://live.kunelradio.ru:8000/128.mp3"},
    {name = "German Deutsche Hip-Hop Rap - Caprice Radio", url = "http://213.141.131.10:8000/germanrap"},
    {name = "Ночной Звонок", url = "https://listen7.myradio24.com/74828"},
    {name = "Радио Рекорд - Нафталин FM", url = "https://hls-01-radiorecord.hostingradio.ru/record-naft/playlist.m3u8"},
    {name = "Radio Caprice - Experimental Techno [2]", url = "http://213.141.131.10:8000/experimentaltechno"},
    {name = "Планета ФМ", url = "https://radio-24.ru/audio2.php?url=http://fm.media56.ru:8000/Planeta"},
    {name = "Radio Caprice - Blues Rock", url = "http://79.120.39.202:8002/bluesrock"},
    {name = "Посад", url = "https://a1.radioheart.ru:9001/RH4122"},
    {name = "1970'S Music Collection", url = "http://213.141.131.10:8004/70collection"},
    {name = "Первое Железнодорожное Радио", url = "https://www.liveradio.es/http://1zd.su:8050/radio"},
    {name = "Роксана Радиосы", url = "https://listen1.myradio24.com/2761"},
    {name = "ЭХО Лосей", url = "https://icecast-radioosc.cdnvideo.ru/radioosc64"},
    {name = "Radio Fantastiki", url = "http://fantasyradioru.no-ip.biz:8016/"},
    {name = "Радио Новая Жизнь", url = "https://nlradio.stream/hifi"},
    {name = "Radio Caprice - Bossa Nova", url = "http://79.111.14.76:8002/bossanova"},
    {name = "Radio Caprice - Post-Rock", url = "http://79.111.14.76:8004/postrock"},
    {name = "Z FM Фронтовое Радио, Луганск", url = "http://zfm.hostingradio.ru/zfm128.mp3"},
    {name = "Fresh FM", url = "https://a2.radioheart.ru:8007/live"},
    {name = "Лидер", url = "https://stream.volnorez.com/live-app/900927"},
    {name = "ASMR", url = "https://live.lofiradio.ru/asmr_mp3_320"},
    {name = "Движуха", url = "https://myradio24.org/78805"},
    {name = "Radiomv Russian Music", url = "https://ice.radiomv.co:8440/russian_music.mp3"},
    {name = "Шансон Плюс", url = "http://radio.radioshansonplus.com:8000/radio"},
    {name = "Радио 40", url = "http://195.112.119.187:8000/Radio40"},
    {name = "Radio Caprice - Piano Jazz Stride Ragtime", url = "http://79.111.119.111:8002/pianojazz"},
    {name = "101Ru - French Chanson", url = "http://ic6.101.ru:8000/stream/pro/aac/64/146"},
    {name = "Radio Caprice - Harmonica Blues", url = "http://79.120.39.202:9081/"},
    {name = "Radio Caprice - Death Doom Metal", url = "http://79.120.39.202:9007/"},
    {name = "Spinner - Saxophone Jazz", url = "https://live.radiospinner.com/saxophone-jazz-64"},
    {name = "DFM - Chill", url = "https://dfm-dfmchill.hostingradio.ru/dfmchill96.aacp"},
    {name = "Прибой", url = "http://77.232.167.247:1007/admin"},
    {name = "Relax Instrumental", url = "https://pub0101.101.ru/stream/pro/aac/64/28"},
    {name = "101Ruchannel119-Laskoviymay", url = "http://pub0202.101.ru:8000/stream/pro/aac/64/119"},
    {name = "16Bitfm Cafe", url = "http://16bitfm.com:8000/cafe_mp3_128"},
    {name = "Radio 2X2", url = "http://95.104.192.220:8001/radio2x2.ogg"},
    {name = "ULTRA", url = "http://nashe1.hostingradio.ru/ultra-256"},
    {name = "Радио Рекорд Rap Hits", url = "http://radiorecord.hostingradio.ru/rap96.aacp"},
    {name = "Бард-Радио", url = "https://listen.myrh.ru/Bard-Radio"},
    {name = "Relax FM", url = "https://pub0302.101.ru:8443/stream/air/aac/64/200"},
    {name = "Radio Caprice - New Age", url = "http://79.120.77.11:8002/newage"},
    {name = "Радио Рекорд Eurodance", url = "http://radiorecord.hostingradio.ru/eurodance96.aacp"},
    {name = "Radio Maximum - Nirvana", url = "https://maximum-nirvana.hostingradio.ru/nirvana96.aacp"},
    {name = "Всесоюзное Радио", url = "https://stream.cassiopeia-station.ru:1045/stream"},
    {name = "Radio Maximum - Russian Music", url = "https://maximum-russian.hostingradio.ru/maxrussian96.aacp"},
    {name = "Твой День", url = "http://a7.radioheart.ru:8035/RH8851"},
    {name = "Radio Caprice Organ Classic", url = "http://79.120.77.11:9051/"},
    {name = "Radio Caprice - Grunge", url = "http://79.120.39.202:8000/grunge"},
    {name = "Радио Монте Карло - Bossa Nova", url = "https://mc-mcbossa.hostingradio.ru/mcbossa96.aacp"},
    {name = "Megapolisnight", url = "https://a4.radioheart.ru:9042/MegaNightRadio"},
    {name = "Komsomolskaya Pravda", url = "http://kraskp.ru:8000/mskregion"},
    {name = "Радио России Приморье", url = "http://mp3.vestiprim.ru:8000/Radio128"},
    {name = "RADCAP: INDUSTRIAL DARK RITUAL AMBIENT", url = "http://79.120.39.202:8000/darkambient"},
    {name = "Звезда ТВ🌟ТСЧ", url = "https://tvchannelstream1.tvzvezda.ru/cdn/tvzvezda/playlist_sdhigh.m3u8"},
    {name = "Старое Радио - Old Radio 64", url = "http://195.91.237.50:8000/ices64"},
    {name = "Radio Record HQ", url = "https://air.unmixed.ru/record320"},
    {name = "Ретро FM Санкт-Петербург 128 Kbps, Mp3", url = "http://emgspb.hostingradio.ru/retrofmspb128.mp3"},
    {name = "ЯНФМ Диско 90Х РФ", url = "https://stream.laut.fm/radio90s"},
    {name = "Liquid Dnb Station", url = "http://95.47.244.172:8000/live"},
    {name = "Радио Рекорд Breaks", url = "http://radiorecord.hostingradio.ru/brks96.aacp"},
    {name = "VIVA-RUSSIA", url = "https://livestreamc.prdv3.dlivecdn.com/viva-russia/1711834373/360p/live.m3u8"},
    {name = "Первое Сетевой", url = "http://streamer.radiovseti.ru:8000/128"},
    {name = "Radio Caprice - Latin Afro-Cuban Jazz", url = "http://79.111.119.111:8002/latinjazz"},
    {name = "Bleeplove Chiptune Radio", url = "https://stream-152.zeno.fm/gyazcly9dfotv?zs=4n2MPkZJRImNtNA8HGWuFw"},
    {name = "Радио Гамаюн", url = "https://gamaun.online:8025/radio"},
    {name = "Радио Классик Essential Classic", url = "http://jfm1.hostingradio.ru:14536/ecstream.mp3"},
    {name = "Radio Vanya", url = "http://icecast-radiovanya.cdnvideo.ru/radiovanya"},
    {name = "Радио АЛЬФА", url = "https://online.alfafm.ru/alfa_mp3"},
    {name = "Radio Caprice - Dub", url = "http://79.111.14.76:9029/"},
    {name = "Голос Бирмы", url = "https://listen4.myradio24.com/39982"},
    {name = "Межзвёздное Радио", url = "https://myradio24.org/97557"},
    {name = "Магадан ФМ", url = "https://myradio24.org/magadanfm"},
    {name = "Premium", url = "https://listen2.rpfm.ru/premium128"},
    {name = "Radio Caprice Industrialdarkritual Ambient", url = "http://79.120.39.202:8002/darkambient"},
    {name = "Radio 107 Moscow", url = "http://62.183.34.109:8000/radio107.mp3"},
    {name = "Radio Caprice - West Coast Hip-Hop, Gangsta Rap, G-Funk 320K", url = "http://79.120.39.202:8004/gangstarap"},
    {name = "161Fm", url = "http://stream.161.fm:8000/128"},
    {name = "Radio Caprice - Funky House [3]", url = "http://213.141.131.10:8004/funkyhouse"},
    {name = "Камеди Радио Екатеринбург", url = "https://pub0202.101.ru:8443/stream/reg/mp3/128/region_comedy_9"},
    {name = "Рояль", url = "https://c22.radioboss.fm:18186/stream"},
    {name = "Радио Рекорд - Russian Gold", url = "https://hls-01-radiorecord.hostingradio.ru/record-russiangold/playlist.m3u8"},
    {name = "Радио Сектор Sector Nota Flac", url = "http://89.223.45.5:8000/nota-flac"},
    {name = "Своё Радио", url = "http://svoeradiofm.hostingradio.ru:8032/svoe-320.mp3"},
    {name = "Свободное Радио", url = "http://nradio.net/freemp3"},
    {name = "Radio Caprice - Melodic Heavy Metal", url = "http://79.111.119.111:8000/melodicheavy.m3u"},
    {name = "Комбат ФМ Военное Радио, Луганск", url = "http://193.228.161.95:10000/live-mp3"},
    {name = "Radio Caprice - Neue Deutsche Härte", url = "http://213.141.131.10:8000/ndh.m3u"},
    {name = "East Of Russia Восток России", url = "http://109.70.24.182:8000/stream/1/"},
    {name = "Relax Smooth Jazz", url = "https://pub0202.101.ru:8443/stream/trust/mp3/128/31"},
}

return stations
