local stations = {
    {name = "Sport FM 946", url = "http://netradio.live24.gr/sportfm7712"},
    {name = "Blues Radio", url = "http://cast3.radiohost.ovh:8352/"},
    {name = "Rythmos 949", url = "http://stream.radiojar.com/aw1w2xfx1vduv"},
    {name = "Skai 1003", url = "http://netradio.live24.gr/skai1003"},
    {name = "Psyndora Chillout", url = "http://cast.magicstreams.gr:9125/stream"},
    {name = "Real FM 978", url = "http://netradio.live24.gr/realfm"},
    {name = "Ellinikos 932", url = "http://netradio.live24.gr/orange9320"},
    {name = "Psyndora Psytrance", url = "http://cast.magicstreams.gr:9111/stream"},
    {name = "Trance Athena", url = "https://cast.streams.ovh:2199/tunein/tranceathena.pls"},
    {name = "Vanilla Radio Deep Flavors [HD 320]", url = "https://stream.vanillaradio.com:8090/live"},
    {name = "Off Radio - Athens", url = "https://s3.yesstreaming.net:2199/tunein/offradio.pls"},
    {name = "Zeppelin 1067", url = "https://radiostreaming.ert.gr/ert-zeppelin"},
    {name = "Galaxy 92 FM", url = "http://galaxy.live24.gr/galaxy9292"},
    {name = "Ερασπορ", url = "https://radiostreaming.ert.gr/ert-erasport"},
    {name = "ΕΡΤ Δεύτερο Λαϊκά", url = "http://radiostreaming.ert.gr/ert-talaika"},
    {name = "Love Radio 975", url = "http://netradio.live24.gr/loveradio-1000"},
    {name = "Mad Radio 1062", url = "http://mediaserver.mad.tv/stream"},
    {name = "Sfera 1022", url = "https://sfera.live24.gr/sfera4132"},
    {name = "Kiss 929", url = "http://netradio.live24.gr/kissfmathens"},
    {name = "Stokokkino", url = "http://stream.radiojar.com/kokkino-ath.mp3"},
    {name = "Ρυθμός 892", url = "http://s4.onweb.gr:8892/stream?type=http&nocache=136101"},
    {name = "Σκύλος 90", url = "http://n01.radiojar.com/819r8wupdrruv?rj-ttl=5&rj-tok=AAABePEMVGgAGH9g3lsAx7imBA"},
    {name = "Γλέντι 1011", url = "http://onairmediagroup.live24.gr/glenti1011xanthi"},
    {name = "Menta Fm 88", url = "https://stream.radiojar.com/menta"},
    {name = "Παραπολιτικά FM 901", url = "http://netradio.live24.gr/athinaradio"},
    {name = "Derti 986", url = "http://derti.live24.gr/derty1000"},
    {name = "Laikos FM", url = "http://netradio.live24.gr/laikos876"},
    {name = "Δημοτική Ανθολογία", url = "http://shoutcast.24radio.gr:8070/;"},
    {name = "Rainbow 89", url = "http://n0e.radiojar.com/083wqknmsuhvv?rj-ttl=5&rj-tok=AAABhHgFMdoAMjpYSw5BtqF9Zg"},
    {name = "Metropolis 955", url = "http://metropolis.live24.gr/metropolis955thess"},
    {name = "ERA Deftero Programma", url = "http://radiostreaming.ert.gr/ert-deftero"},
    {name = "Radio Art - Chillout", url = "http://air.radioart.com/fChillout.mp3"},
    {name = "KISS FM 1006", url = "http://live.radiokiss.gr/kissfm1006hq.mp3"},
    {name = "Ελληνικός 1072", url = "http://everest.streams.ovh:2390/;"},
    {name = "Disco Net", url = "https://stream1.468.gr/8004/stream"},
    {name = "Radio Art - Yoga", url = "http://air-tunein.radioart.com/fYoga.mp3"},
    {name = "Sfera 966", url = "http://n01.radiojar.com/mg2vq26eewzuv?rj-ttl=5&rj-tok=AAABePDKYnkA9kVa1QYWTKFxIQ"},
    {name = "VELVET 968", url = "http://s10.voscast.com:9942/;"},
    {name = "Radio Art - Gregorian Chants", url = "http://air.radioart.com/fGregorian_chants.mp3"},
    {name = "Dalkas 882", url = "https://stream.radiojar.com/pr9r38w802hvv"},
    {name = "Arion Laikos", url = "http://ice.onestreaming.com/arionlaikos"},
    {name = "Cosmoradio 95,1", url = "http://eco.onestreaming.com:8689/"},
    {name = "Athens Rock 969", url = "https://az10.yesstreaming.net/radio/8060/radio.mp3"},
    {name = "Club FM GR", url = "https://stream-32.zeno.fm/z8cp1nqwhnruv?zs=sUtan8GnTDGarEqChfudfg&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "ΕΡΤ Δεύτερο Πρόγραμμα", url = "https://radiostreaming.ert.gr/ert-deftero"},
    {name = "Vanilla Radio Deep Flawors", url = "https://stream.vanillaradio.com:8012/live"},
    {name = "ΕΡΤ Kosmos Jazz", url = "https://radiostreaming.ert.gr/ert-webjazz"},
    {name = "ERA Kosmos", url = "http://radiostreaming.ert.gr/ert-kosmos"},
    {name = "Galaxy 92", url = "http://netradio.live24.gr/galaxy9292"},
    {name = "Δρομοσ 89,8 | Dromos 89,8", url = "http://netradio.live24.gr/dromos2"},
    {name = "Imagine 897 Thessaloniki,Gr", url = "https://www.imagine897.gr/webplayer/?pl=winamp&c=IMAGINE897"},
    {name = "ERA Trito Programma", url = "http://radiostreaming.ert.gr/ert-trito"},
    {name = "Λάμψη", url = "https://i6.streams.ovh/sc/radiolampsi/stream"},
    {name = "Rock Hard Greece", url = "https://noc.ezhellas.com:44450/live"},
    {name = "ΕΡΤ Πρώτο Πρόγραμμα", url = "https://radiostreaming.ert.gr/ert-proto"},
    {name = "Πειραϊκή Εκκλησία", url = "https://impradio.bytemasters.gr/8002/stream"},
    {name = "Best 926", url = "http://best.live24.gr/best1222"},
    {name = "REBEL 1052", url = "http://netradio.live24.gr/rebel1052"},
    {name = "Zografou", url = "http://i3.streams.ovh:12162/live"},
    {name = "Radio Art - Meditation", url = "http://air-tunein.radioart.com/fMeditation.mp3"},
    {name = "Ζημιά 939", url = "http://www.gointernet.gr:8012/;listen.pls"},
    {name = "Radio Art - Love Smooth Jazz", url = "https://live.radioart.com/fLove_smooth_jazz.mp3"},
    {name = "Merakia", url = "https://stream-57.zeno.fm/r4k1wdsshkhvv?zs=1oZXErYwSLei_qvBzZxyag&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Focus Fm 1036 Gr", url = "https://ice.greekstream.net/focusfm"},
    {name = "Θάλασσα Και Παράδοση", url = "http://i.streams.ovh:9391/stream"},
    {name = "Easy FM 972", url = "https://stream.radiojar.com/cthtwxk5yvduv.mp3"},
    {name = "Libero FM 1074", url = "https://radio.libero.fm:10750/live?1697856170939"},
    {name = "Vanilla Radio Smooth Flavors", url = "https://smooth.vanillaradio.com:8032/live.m3u"},
    {name = "Bar Legend Radio", url = "https://solid24.streamupsolutions.com/proxy/nilxzqeg?mp=/stream"},
    {name = "Sokfm 1048", url = "https://stream.radiojar.com/zeqcyyvu48hvv"},
    {name = "Fly 104", url = "https://imagine2.radioca.st/;stream.nsv"},
    {name = "Radioactive", url = "https://streamyourdream.org:8050/radioactive"},
    {name = "Parapolitika 901", url = "https://netradio.live24.gr/athinaradio"},
    {name = "Radio Art - Solo Harp", url = "http://air-tunein.radioart.com/fSolo_harp.mp3"},
    {name = "Music 892", url = "https://netradio.live24.gr/music892"},
    {name = "Ήπειρος 945", url = "https://rdst.win:59450/stream"},
    {name = "Radio Art - Sleep", url = "http://air-tunein.radioart.com/fSleep.mp3"},
    {name = "ΕΡΤ Τρίτο Πρόγραμμα", url = "https://radiostreaming.ert.gr/ert-trito"},
    {name = "Love Trap", url = "http://n0a.radiojar.com/tkeve70hqd0uv?rj-ttl=5&rj-tok=AAABeL0yWmwArvLu3hf9O3iTGQ"},
    {name = "Psyland", url = "https://sp.streams.ovh/8020/stream"},
    {name = "City Of Primo 1061", url = "http://radio.lancom.gr:8014/stream6"},
    {name = "876 Studio 1", url = "http://s3.onweb.gr:8872/;"},
    {name = "Pepper 966", url = "https://stream.radiojar.com/pepper"},
    {name = "Athens Party", url = "http://ice.onestreaming.com/athensparty"},
    {name = "Derti 1077", url = "http://i5.streams.ovh:14008/stream?type=http&nocache=100540"},
    {name = "Radio Art - Ambient Piano", url = "http://air.radioart.com/fAmbient_piano.mp3"},
    {name = "Energy 883", url = "http://s1.onweb.gr:8412/stream"},
    {name = "ERA Proto Programma", url = "http://radiostreaming.ert.gr/ert-proto"},
    {name = "Easy 972", url = "http://stream.radiojar.com/cthtwxk5yvduv"},
    {name = "Zoo 908", url = "https://netradio.live24.gr/zoo908thess"},
    {name = "Η Φωνή Της Ελλάδας", url = "https://radiostreaming.ert.gr/ert-voiceofgreece"},
    {name = "Νησιώτικα 247", url = "https://n0f.radiojar.com/f4uubny2uexb?1709758100=&rj-tok=AAABjhWQEEQAcVrb65vN3wqd0A&rj-ttl=5"},
    {name = "Radio Art - Relaxing Violin, Piano Cello", url = "http://air.radioart.com/fRelaxing.mp3"},
    {name = "Λαϊκή Κιβωτός", url = "http://everest.streams.ovh:1310/stream"},
    {name = "Alexandroupolis Dee Jay 948", url = "https://stream.myip.gr/proxy/deejay?mp=/stream"},
    {name = "Radio Art - Bach", url = "http://air.radioart.com/fBach.mp3"},
    {name = "NITRO", url = "http://stream.zeno.fm/t272zvxu4yzuv"},
    {name = "The Greek Radio", url = "https://stream-44.zeno.fm/qq2btg0vp68uv?zs=04c42hA2SRyAHj7VojzerQ&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Omega Radio Greek Music", url = "https://rdst.win:59962/stream"},
    {name = "Echoesgr Netradio - Thessaloniki", url = "http://85.17.75.146/echoes"},
    {name = "Πανόραμα 984", url = "http://netradio.live24.gr/panorama984"},
    {name = "Sohos 887", url = "https://eu7.fastcast4u.com/proxy/sohosfm?mp=/1"},
    {name = "929 KISS", url = "https://kissfm.live24.gr/kissfmathens"},
    {name = "Άνεμος 92", url = "http://s4.onweb.gr:8842/;"},
    {name = "Radio Art - Violin", url = "http://air.radioart.com/fViolin_works.mp3"},
    {name = "Λάμψη 1057", url = "http://stream2.proradio.gr:8004/lampsi"},
    {name = "Radio Art - Flamenco", url = "http://air.radioart.com/fFlamenco.mp3"},
    {name = "Ξενύχτης", url = "https://sp3.streams.ovh/8018/stream"},
    {name = "2O ΠΑΡΑΔΟΣΙΑΚΑ", url = "https://radiostreaming.ert.gr/ert-defteroparadosiaka"},
    {name = "Athens Deejay 952", url = "http://netradio.live24.gr/athensdeejay"},
    {name = "Λαϊκός 1006", url = "http://sp2.streams.ovh:8100/stream?type=http&nocache=185"},
    {name = "Blueswave Radio", url = "https://blueswave.radio:8100/hifiblues"},
    {name = "Travellers Web Radio", url = "https://stream-42.zeno.fm/n4yfk24tm2zuv?zs=2h2zfJYNTW2XWW7r8ZkYqQ&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Radio Art - Classical For Sleep", url = "http://live.radioart.com/fClassical_for_sleep.mp3"},
    {name = "Griechenland - Akroama", url = "http://live.e-streaming.eu:8100/"},
    {name = "Στο Κόκκινο ΘΕΣΣΑΛΟΝΙΚΗ 91,4 FM", url = "http://n09.radiojar.com/275p8ssmb?rj-ttl=5&rj-tok=AAABe5KoPq0A-SETCU2cfsnBjA"},
    {name = "MUSIC FACTORY RADIO", url = "http://radio.musicfactory.gr:9000/"},
    {name = "Vasilis Cfu Psy Trance", url = "https://stream-40.zeno.fm/c2t7d9p6mf9uv?zs=_D-E0xBPQcGB_V9n7LLuqA"},
    {name = "Fancy Trance", url = "https://stream-33.zeno.fm/ygh3m8m7n48uv?zs=9zm4lJvjTjiN-Ws_yi1L5g&acu-uid=727435602967&triton-uid=cookie%253A83ca5b14-582e-4c12-a5ab-255cdb39e"},
    {name = "Radio Art - Organ", url = "http://air.radioart.com/fOrgan.mp3"},
    {name = "My Radio 1046", url = "http://streaming.myradio1046.fm/myradio1046"},
    {name = "1055 Rock", url = "http://radio.1055rock.gr:30000/1055"},
    {name = "Radio Art - Classical Relaxation", url = "http://air.radioart.com/fClassical_relaxation.mp3"},
    {name = "Metro Radio", url = "https://stream.crete.ovh:8443/metro"},
    {name = "Republic Radio", url = "http://netradio.live24.gr/republicthess"},
    {name = "Athina 984", url = "http://athina984.live24.gr/athina984"},
    {name = "Radio Art - Harpsichord", url = "http://air.radioart.com/fHarpsichord.mp3"},
    {name = "Λαϊκός 1057", url = "http://sp2.streams.ovh:8106/stream?type=http&nocache=540"},
    {name = "Alpha 989", url = "http://stream.radiojar.com/xcdg6yggzfeuv"},
    {name = "Athens 1065 FM", url = "http://89.163.217.252:9400/;"},
    {name = "Happy 104", url = "http://ath10400fm-radioplayer.live24.gr/ath10400fm"},
    {name = "Starradio", url = "http://hermes.gretor.net:8000/"},
    {name = "Hot FM 1046 Greece", url = "https://hotfm.live24.gr/hotfm"},
    {name = "Plus Radio", url = "http://eco.onestreaming.com:8039/"},
    {name = "Houseradio", url = "https://i9.streams.ovh/sc/contactradio/stream"},
    {name = "Ertopen Web Radio", url = "http://radio.ertopen.com/erasport"},
    {name = "Hit Radio Greece", url = "https://solid2.streamupsolutions.com:2199/tunein/lposuiem.pls"},
    {name = "Vasilis Cfu Heavy Metal Rock", url = "https://stream-42.zeno.fm/rfwpuu6pzd0uv?zs=xy5-Y-DqTY--2M2vdi_P3Q"},
    {name = "Offradio 320", url = "https://s7.yesstreaming.net/stream/8000"},
    {name = "Velvet Ballads", url = "http://173.249.6.18:9684/;"},
    {name = "1Ο Ερασιτεχνικό Πρόγραμμα Γαργαλιάνων 888", url = "https://i2.streams.ovh:2200/ssl/trelostwnfm?mp=/stream&1671747517218"},
    {name = "ΕΡΤ Kosmos", url = "https://radiostreaming.ert.gr/ert-kosmos"},
    {name = "Radio Art - Baroque", url = "http://air.radioart.com/fBaroque.mp3"},
    {name = "Radio Oi", url = "http://eu4.fastcast4u.com/proxy/nikoud00?mp=/1"},
    {name = "Zucca", url = "http://stream.zuccaradio.com/stream?"},
    {name = "Ερωτικός 948", url = "http://eu1.fastcast4u.com:21624/stream"},
    {name = "2O Laika", url = "https://radiostreaming.ert.gr/ert-talaika"},
    {name = "Μοναχική Διακονία 875", url = "http://eco.onestreaming.com:8019/;stream.mp3"},
    {name = "Sfera 944", url = "http://netradio.live24.gr/sfera941nauplio"},
    {name = "Karamela 924", url = "https://netradio.live24.gr/924fm-thess"},
    {name = "Galaxy FM 920", url = "https://galaxy.live24.gr/galaxy9292"},
    {name = "Dj Power Music", url = "https://c2.radioboss.fm:8796/DjPowerMusicTheBest"},
    {name = "Deejay Radio 975 Fm Corfu Greece", url = "http://s4.onweb.gr:8470/"},
    {name = "Kalamaria FM 1017 - Thessaloniki - Greece", url = "https://ice.greekstream.net/focusfm_128"},
    {name = "Streamee Lounge Chillout", url = "https://politismedia-sec3.live24.gr/pm-remos"},
    {name = "Streamee Metal", url = "https://politismedia-sec.live24.gr/streameemetal"},
    {name = "Sampotaz", url = "https://eu10.fastcast4u.com/sampotaz"},
    {name = "1055 Rock Thessaloniki", url = "http://radio.1055rock.gr:30000/1055?ver=334672"},
    {name = "Citizen", url = "https://sp3.streams.ovh/8082/;"},
    {name = "Play 915", url = "http://s6.onweb.gr:8058/stream"},
    {name = "Radio Art - Bossa Nova", url = "http://air-tunein.radioart.com/fBosa_nova.mp3"},
    {name = "Rock Melodic Radio", url = "http://live.rockmelodic-radio.com:8124/listen.pls"},
    {name = "Vanilla Radio Deep Flavors", url = "https://stream.vanillaradio.com:8003/live.m3u"},
    {name = "Downtuned", url = "https://free.rcast.net/62232"},
    {name = "7000FM", url = "https://stream.7000fm.gr/radio/8000/radio.mp3"},
    {name = "Monkey Bros", url = "http://n01.radiojar.com/5tyqrwpgpfeuv?rj-ttl=5&rj-tok=AAABeL13ku4Ae8jgeSRH6aWTyA"},
    {name = "Apps 966", url = "https://stream.myip.gr/proxy/app966?mp=/stream"},
    {name = "Strouga", url = "https://neos.win:48350/stream"},
    {name = "Imagine Radio 897 Thessaloniki Greece", url = "https://imagine897.radioca.st/stream"},
    {name = "Aegean Lounge Radio", url = "http://radio2.citrus3.com:2199/tunein/geertvernelen.pls"},
    {name = "Radio Drama 991", url = "http://pstnet6.shoutcastnet.com:60160/stream"},
    {name = "Deejay 975 Greece Corfu", url = "https://sh.onweb.gr:7083/stream"},
    {name = "2000 FM 998", url = "https://i8.streams.ovh/ic/2000fm/stream"},
    {name = "RSO 917 Thessaloniki", url = "http://tachyon.shoutca.st:8594/stream"},
    {name = "Easy 932", url = "https://solid48.streamupsolutions.com/proxy/lhlamody?mp=/stream"},
    {name = "Radio Lehovo", url = "http://s4.onweb.gr:8468/"},
    {name = "1O Ερασιτεχνικό Πρόγραμμα Γαργαλιάνων", url = "http://i2.streams.ovh:7109/stream?type=http&nocache=11373"},
    {name = "Radiokyklos - Greek Hiphop", url = "https://azuracast.streams.ovh/listen/radiokyklos/radio.mp3"},
    {name = "Μελωδία Θεσσαλονίκης 98", url = "https://netradio.live24.gr/north98thess"},
    {name = "Minore 96,1", url = "https://eu3.fastcast4u.com/proxy/nmarog00?mp=/1"},
    {name = "Jazz Cafe", url = "https://stream-59.zeno.fm/hx6t4t15e8zuv?zs=NBUVDmgqQSWS38xPcU2OmA&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Athens Up Radio", url = "http://n05.radiojar.com/9ndpdg3c0s8uv"},
    {name = "Στο Κόκκινο 1055", url = "http://n06.radiojar.com/kokkino-ath.mp3?rj-ttl=5&rj-tok=AAABe5JM3SoATYdU3sO03CR5Pw"},
    {name = "ERT3 102 FM", url = "http://radiostreaming.ert.gr/ert-102fm"},
    {name = "Status Web Radio", url = "https://cast5.magicstreams.gr/sc/statuswe/stream"},
    {name = "Panikos", url = "http://toradio.cc:8010/stream"},
    {name = "Κρητόραμα 979", url = "http://sc2.streamwithq.com:8052/stream?type=http&nocache=556"},
    {name = "Radio Art - Guitar Jazz", url = "https://live.radioart.com/fGuitar_jazz.mp3"},
    {name = "Streamee Old School Hip Hop 18+", url = "https://politismedia-sec3.live24.gr/pm-thuglife"},
    {name = "Πειρατικός FM 995", url = "https://shoutcast.k-planet.eu/9800/stream"},
    {name = "Radio Art - Vocal Jazz", url = "https://live.radioart.com/fVocal_jazz.mp3"},
    {name = "My Way Radio", url = "https://cast.iplayradio.net/listen/mywayradio/stream"},
    {name = "Cityvibes", url = "http://everest.streams.ovh:1350/stream"},
    {name = "696Radio", url = "https://ample.radiojar.com/696radio.mp3"},
    {name = "Classic Radio Greece", url = "http://streaming.radionomy.com/JamendoLounge"},
    {name = "Blues Radio Alternative", url = "https://i4.streams.ovh/sc/bluesrad/stream"},
    {name = "Radio Art - Solo Piano", url = "http://live.radioart.com/fSolo_piano.mp3"},
    {name = "ERT Trito Maestro", url = "https://radiostreaming.ert.gr/ert-trito-maestro"},
    {name = "Madness 95", url = "http://s7.onweb.gr:8044/stream?type=http&nocache=40904"},
    {name = "Memories Radio", url = "https://stream1.468.gr/8108/stream"},
    {name = "Radio Gold @Net", url = "http://radiogold.live24.gr/radiogold"},
    {name = "Radio Art - Folk And Soft Rock2", url = "http://air.radioart.com/fFolk_and_soft_rock.mp3"},
    {name = "4U 931", url = "http://netradio.live24.gr/4uradio931"},
    {name = "Palmos 1027", url = "http://s6.onweb.gr:8010/stream?type=http&nocache=55918"},
    {name = "Sohos FM 887", url = "http://sohosfm.gr/Radio/Live.m3u"},
    {name = "1035 Studio 3", url = "https://sh.onweb.gr/8408/;"},
    {name = "Corfu Dee Jay 975", url = "https://sh.onweb.gr:7083/stream?type=http&nocache=35812"},
    {name = "Venus Mykonos", url = "https://politismedia-sec.live24.gr/streameemykonos"},
    {name = "Radio Art - Greek Art Mood Up", url = "http://air.radioart.com/fGreek_art_contemporary.mp3"},
    {name = "A 100", url = "http://bestgreek.info:8104/live?type=http&nocache=110731"},
    {name = "Radioart: Broadway", url = "https://live.radioart.com/fBroadway.mp3"},
    {name = "Ellada 943", url = "https://stream.ellada943.gr:10198/radio.mp3"},
    {name = "Point Radio", url = "http://radio.streamings.gr:8029/stream"},
    {name = "METAL ZONE", url = "https://neos.win:48282/stream"},
    {name = "Metal City Radio", url = "http://i6.streams.ovh:16036/stream"},
    {name = "Cavo Paradiso", url = "http://s5.onweb.gr:8488/"},
    {name = "Vanilla Radiocom - Fresh Flavours Stream", url = "https://fresh.vanillaradio.com:8028/live"},
    {name = "Ράδιο Θεσσαλονίκη 945 FM", url = "https://eu7.fastcast4u.com/proxy/nmarog02?mp=/1"},
    {name = "Radio Art - Smooth Bossa Nova", url = "https://live.radioart.com/fSmooth_bossa_nova.mp3"},
    {name = "Berock Radio", url = "http://solid55.streamupsolutions.com:30013/stream"},
    {name = "Viva 883", url = "http://s3.onweb.gr:8030/stream?type=http&nocache=114707"},
    {name = "1 News", url = "https://cast2.radiohost.ovh/onenewsradio?mp=/stream"},
    {name = "Rocket Greek Rock", url = "https://politismedia-sec.live24.gr/streameerocket"},
    {name = "Zooradio 908", url = "http://s10.voscast.com:9940/"},
    {name = "Ακούστε Το Χριστιανισμό 104,3 FM", url = "https://eu1.fastcast4u.com/proxy/afreeapo?mp=/1"},
    {name = "Forever 963", url = "https://lofos.win:59630/stream"},
    {name = "Radio Art - Solo Instruments", url = "http://air.radioart.com/fSolo_instruments.mp3"},
    {name = "Rempetissa", url = "https://webinternetradios.eu:59339/"},
    {name = "Music Star GR", url = "https://azura.streams.ovh/radio/8130/radio.mp3"},
    {name = "Super FM 101 Thessaloniki", url = "http://ice.greekstream.net/superfm"},
    {name = "90S Heaven", url = "https://sp3.streams.ovh/8070/stream"},
    {name = "Ekrixi Fm 998 Mhz - Greece Thessaloniki", url = "https://ice.greekstream.net/ekrixifm.m3u"},
    {name = "Yellow Radio 1017 - Thessaloniki - Greece", url = "https://ice.greekstream.net/yellow.m3u"},
    {name = "Studio12-22", url = "https://cast6.asurahosting.com/proxy/radiosky/stream"},
    {name = "Best Radio 926", url = "http://netradio.live24.gr/best1222"},
    {name = "Mykonos Live Radio", url = "https://solid55.streamupsolutions.com/proxy/lsdmuqhb?mp=/stream"},
    {name = "Hit Ellinikos", url = "https://solid9.streamupsolutions.com/proxy/zvbgdllc?mp=/stream"},
    {name = "Πάτρα 1065", url = "http://live.cast-control.eu:9102/;"},
    {name = "Galaxy Music The Deep House", url = "https://stream-51.zeno.fm/sgehc2mzwd0uv?zs=DutBe-m5Sz6waLQy8l8ejg"},
    {name = "Focus FM", url = "http://ice.greekstream.net/focusfm"},
    {name = "100 FM Radio 1", url = "http://s3.onweb.gr:8814/;"},
    {name = "Καλόκαρδος 1015", url = "http://i3.streams.ovh:12095/stream"},
    {name = "Radio Gold 2", url = "http://radiogold.live24.gr/radiogoldies"},
    {name = "80Smania GR", url = "https://solid9.streamupsolutions.com/proxy/glzzkced/streamor"},
    {name = "Classic Love 975", url = "https://n06.radiojar.com/gt0xy4z88f0uv?rj-ttl=5&rj-tok=AAABjTchKEYALPbenkCDtQIleQ"},
    {name = "Πήλιο 934", url = "http://s3.myradiostream.com:4060/;"},
    {name = "Rock FM 969", url = "https://az10.yesstreaming.net:8060/radio.mp3"},
    {name = "Play Radio", url = "http://eco.onestreaming.com:8222/"},
    {name = "Radio Art - Ancient Solfeggio Frequencies", url = "http://air.radioart.com/fAncient_solfeggio_frequencies.mp3"},
    {name = "Marios Blackman", url = "https://cloud.123hosting.gr:2200/radio/black9326?mp=/stream"},
    {name = "80Smania", url = "http://158.69.114.190:8024/stream"},
    {name = "Halkidiki 988", url = "https://ice.greekstream.net/988"},
    {name = "Radio Art - George Handel", url = "http://air.radioart.com/fGeorge_handel.mp3"},
    {name = "PRAKTORIO FM", url = "http://s3.onweb.gr:8436/;"},
    {name = "Athens Jazz", url = "http://music.wixstatic.com/mp3/6aa018_e43fa27d27c7437fb9306ff8dbb193c9.mp3"},
    {name = "Radio Art - Pyotr Tchaikovsky", url = "http://air.radioart.com/fPyotr_tchaikovsky.mp3"},
    {name = "JAZZ TUNE RADIO", url = "http://c30.radioboss.fm/playlist/119/stream.m3u"},
    {name = "Radio Art - Ancient", url = "http://air.radioart.com/fAncient.mp3"},
    {name = "Streamee Afro House", url = "https://politismedia-sec3.live24.gr/pm-afrohouse"},
    {name = "Streamee Soul", url = "https://politismedia-sec3.live24.gr/pm-soul"},
    {name = "Streamee Reggae", url = "https://politismedia-sec3-push.live24.gr/pm-reggae"},
    {name = "Orthodoxia Kai Paradosi", url = "http://radio.lts-group.eu:52390/ANS"},
    {name = "ΕΝΑ 905", url = "https://rdst.win:48000/stream?type=.mp3"},
    {name = "Πειρατικός", url = "http://89.163.217.252:9800/;"},
    {name = "Fun Radio 1043 Greece", url = "https://solid9.streamupsolutions.com/proxy/wpgqrttp/stream"},
    {name = "Κρητικόραμα 938", url = "http://prech.kritikorama.eu:9382/prech"},
    {name = "Alepou Radio", url = "https://stream.radiojar.com/h693vkmhe5uvv"},
    {name = "Electricity Web", url = "https://i9.streams.ovh/sc/electri1/stream"},
    {name = "Mikis Radio", url = "http://radio.hostchefs.net:8046/stream?1520818130148"},
    {name = "Radio Art - Mellow Piano Jazz", url = "https://live.radioart.com/fMellow_piano_jazz.mp3"},
    {name = "Kalloni 875", url = "https://solid55.streamupsolutions.com/proxy/pelsssbw?mp=/;type=mp3"},
    {name = "1055 ROCK - THESSALONIKI - RADIO2", url = "http://radio.1055rock.gr:30000/1055?ver=324406"},
    {name = "Olympos 1015", url = "https://streamer.stordia.net/listen/olympos/radio.mp3"},
    {name = "To Pikap", url = "http://comet.shoutca.st:8430/live?1513679743968"},
    {name = "Central 1033", url = "https://i6.streams.ovh/sc/central/stream"},
    {name = "1St Greek New Age Radio", url = "https://stream-156.zeno.fm/9yu82xwmdc9uv?zs=kfRTbEsBT1S-LI24kc6lVg"},
    {name = "Radio Art-Overtures", url = "http://air.radioart.com/fOvertures.mp3"},
    {name = "Rock Club Classic Rock", url = "https://stream-11.zeno.fm/uft90xvk4nhvv?zs=6xh3vbJ3QreawrPvhuYBpw&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Fly FM", url = "http://eco.onestreaming.com:8602/;"},
    {name = "Chroma 1058 - Thessaloniki", url = "https://hroma1058thess.live24.gr/hroma1058thess"},
    {name = "Aqua", url = "https://s2.e-resellers.gr:18888/stream"},
    {name = "Bottle O' Groove", url = "http://n06.radiojar.com/n8buhxbsk9duv?rj-ttl=5&rj-tok=AAABeD060SkAnhYCEHekyrYV6g"},
    {name = "Radio Art - Cello Works", url = "http://air.radioart.com/fCello_works.mp3"},
    {name = "Radio Art - Folk And Soft Rock", url = "http://air-tunein.radioart.com/fFolk_and_soft_rock.mp3"},
    {name = "Ikaria", url = "http://stream.radio-ikaria.gr:8000/;?type=http&nocache=4008"},
    {name = "902Gr", url = "https://icecast.902.gr:8001/904"},
    {name = "Chill FM GR", url = "https://stream-61.zeno.fm/p2rk6a1pfg0uv?zs=vzCFMjdPQzq1cC0zehM5Aw&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Must-X GR", url = "https://stream.radiomustathens.com/must-x?app=true&refer="},
    {name = "Radio Art - Nature", url = "http://air.radioart.com/fNature.mp3"},
    {name = "Radio Art - Smooth Jazz", url = "https://live.radioart.com/fSmooth_jazz.mp3"},
    {name = "Radio Art - Film Scores", url = "http://air.radioart.com/fFilm_scores.mp3"},
    {name = "Ερωτικός FM 948", url = "https://eu1.fastcast4u.com/proxy/nmarog01"},
    {name = "Athens Voice 1025", url = "http://netradio.live24.gr/nitro4555"},
    {name = "Atlantis Radio", url = "https://radio.streamings.gr/proxy/atlantisfm?mp=/stream"},
    {name = "Scanner 1022", url = "http://s1.onweb.gr:8074/stream?type=http&nocache=61679"},
    {name = "Radio Art - Vocal New Age", url = "http://air.radioart.com/fVocal_new_age.mp3"},
    {name = "To Steki Tou Erwta", url = "https://i2.streams.ovh/sc/tostekit/stream"},
    {name = "Radio Art - Zen", url = "http://air.radioart.com/fZen.mp3"},
    {name = "FRGFREE Radio Greece", url = "https://stream-154.zeno.fm/r8blmeuo8beuv?zs=ibMilpR0RhqTxgaMDZiPNw"},
    {name = "Paranoise", url = "https://paranoisewebcast.radioca.st/stream"},
    {name = "Chillout Treepines", url = "https://n07.radiojar.com/n4dzb3znn3quv.mp3?rj-ttl=5&rj-tok=AAABhNTTrbwAVrK_m_qtIxI5pQ"},
    {name = "Wave 974", url = "https://mediacp.32bit.gr:8018/stream"},
    {name = "All Star Disco Radio", url = "https://cast.iplayradio.net/radio/8027/stream"},
    {name = "99 Ράδιο 1", url = "http://n13.radiojar.com/t0x7dyqmsuhvv?rj-ttl=5&rj-tok=AAABhH0rD-QAgA2xJnC5B93PWQ"},
    {name = "Easy 1053", url = "http://s4.onweb.gr:8076/stream?type=http&nocache=104869"},
    {name = "Derti 107,7 Heraklion Crete", url = "https://i5.streams.ovh:2200/sc/web101/stream"},
    {name = "Κρητικός 887", url = "http://dione.shoutca.st:8443/;"},
    {name = "Christianity", url = "http://eu1.fastcast4u.com:9326/stream"},
    {name = "Galaxy Music The Rock Metal Ballads", url = "https://stream-52.zeno.fm/fe300c1tpuhvv?zs=ecFJNTpkQXKgNdGJebEOUQ"},
    {name = "Musicartclub", url = "https://eu9.fastcast4u.com/proxy/musicart?mp=/1"},
    {name = "Thessradio", url = "https://noc.ezhellas.com:30580/live"},
    {name = "Preveza Dee Jay 934", url = "http://i3.streams.ovh:12218/stream?type=http&nocache=328"},
    {name = "Kriti FM 875", url = "http://s3.onweb.gr:8878/listen.pls"},
    {name = "Music Corner", url = "https://stream1.468.gr/8010/stream"},
    {name = "Athens Dee Jay 952", url = "https://netradio.live24.gr/athensdeejay"},
    {name = "Αίολος 928", url = "http://eco.onestreaming.com:8552/;"},
    {name = "Opa", url = "https://eu3.fastcast4u.com/proxy/opar?mp=/1"},
    {name = "Movementradio 1", url = "https://movementathens.out.airtime.pro/movementathens_a"},
    {name = "Liquid Fm", url = "https://netradio.live24.gr/freeradio-1000"},
    {name = "Ράδιο Eurovision", url = "https://radiostreaming.ert.gr/ert-eurovision"},
    {name = "Nostos 1006", url = "https://neos.win:37878/stream?type=.mp3?ver=325606"},
    {name = "X Radio 913", url = "https://live.sugarweb.gr/913.aac"},
    {name = "Pathos Radio", url = "http://dione.shoutca.st:8628/stream/;"},
    {name = "Γαλαξίας 911", url = "http://shoutcast.24radio.gr:8018/;"},
    {name = "Paidaki 975", url = "https://paidaki975.radioca.st/;"},
    {name = "Legend 1016", url = "http://onairmediagroup.live24.gr/legend1016xanthi"},
    {name = "Samano Radio", url = "https://streams.radio.co/s8a6d959b1/listen"},
    {name = "Radio Art - Mozart", url = "http://air.radioart.com/fMozart.mp3"},
    {name = "Metropolis", url = "https://metromedia.live24.gr/metropolis955thess"},
    {name = "Essential Mix", url = "https://greeksonic.alphaserver.gr/8004/stream"},
    {name = "Strummer Radio", url = "http://n02.radiojar.com/fg3tm92rxeruv?rj-ttl=5&rj-tok=AAABgyLgWysAEp7R4lXf-DlT1g"},
    {name = "Radio Art - Shamanic", url = "http://air.radioart.com/fShamanic.mp3"},
    {name = "Radio Art - For Study2", url = "http://air.radioart.com/fFor_study.mp3"},
    {name = "Radio Patra 106,5", url = "https://player.magicstreams.gr/radio/iframe/playlist.php?stream=https://live.cast-control.eu:2000/stream/radiopatra&title=RADIO%20PATRA&name=Listen.pls"},
    {name = "Radio Art - Workout Rock Indie", url = "http://air.radioart.com/fRock_and_indie.mp3"},
    {name = "Velvet FM", url = "https://ice.onestreaming.com/velvetfm"},
    {name = "We Radio 894", url = "https://centova.gr-net.gr/proxy/we894/stream"},
    {name = "Red 963", url = "https://netradio.live24.gr/red9630"},
    {name = "Radio Apollon", url = "https://webinternetradio.eu:47026/"},
    {name = "Αρχάγγελος 941", url = "http://eco.onestreaming.com:8536/;"},
    {name = "SEDUCTION DANCE TUNES RADIO", url = "https://24streams.gr/8057/stream"},
    {name = "Jazz Breeze", url = "https://n03.radiojar.com/8tqwqkrhk48uv?rj-ttl=5&rj-tok=AAABhWUzD2oAZxpriF75OruLjw"},
    {name = "Miniwatt 1125", url = "http://solid1.streamupsolutions.com:11003/live"},
    {name = "Radio Art - Swing", url = "http://air.radioart.com/fSwing.mp3"},
    {name = "Rock 1047", url = "https://s9.yesstreaming.net:2199/proxy/anyhowmo/stream"},
    {name = "Radio Art - Salsa", url = "http://air.radioart.com/fSalsa.mp3"},
    {name = "Lemon Web Radio", url = "https://s2.e-resellers.gr/proxy/radio888/stream"},
    {name = "Radio Art - Athenian Early", url = "http://air.radioart.com/fAthenian_early.mp3"},
    {name = "Volos Dee Jay 1045", url = "http://cast3.radiohost.ovh:8008/stream"},
    {name = "NRG 1015", url = "http://n04.radiojar.com/apb4wybq36duv.mp3?rj-ttl=5&rj-tok=AAABhIJxLQwAy78cDpx6RkU5Cg"},
    {name = "Streamee Bar Music", url = "https://politismedia-sec3.live24.gr/pm-techno"},
    {name = "Epiloges Κιλκίς", url = "http://ice.streamcloud.mediacdn.com/epiloges1028"},
    {name = "Camara", url = "https://n06.radiojar.com/252ry9dgytzuv?rj-ttl=5&rj-tok=AAABeKi3emcATmr2vFF6A41gwQ"},
    {name = "Mykonos 981", url = "http://radio.streamings.gr:8007/stream"},
    {name = "Εκκλησία Της Ελλάδας 895", url = "https://loki.mental-media.gr:8038/index.html"},
    {name = "Capital 1048", url = "https://rdst.win:59354/stream"},
    {name = "Arion Stigmes", url = "https://live.arionradio.com/arionstigmes"},
    {name = "Rythmos FMGR", url = "https://n01.radiojar.com/g4tyehk5yvduv.mp3"},
    {name = "Μουσικός Επισκέπτης Γαλατσίου", url = "https://sslstreaming.com:7019/;?1604171746021"},
    {name = "ERT Tripoli", url = "https://radiostreaming.ert.gr/ert-tripoli"},
    {name = "Musica Radio", url = "http://n11.radiojar.com/w6c6bssk95vtv?rj-ttl=5&rj-tok=AAABeL2tvXsA_W4ZZxft3G5omQ"},
    {name = "Alpha 989 Athens", url = "https://n0e.radiojar.com/xcdg6yggzfeuv?rj-ttl=5&rj-tok=AAABeGu7-YMAAjbbx7O97iNbyw"},
    {name = "Gavdos 888", url = "https://sc2.streamwithq.com:2000/stream/GavdosFm"},
    {name = "Rockha Radio", url = "https://radio.rockharadio.com/listen/rockharadio/radio.mp3"},
    {name = "Radio Art - Piano Guitar", url = "http://air-tunein.radioart.com/fPiano_and_guitar.mp3"},
    {name = "Velvet Ballads 968 FM", url = "https://metromedia.live24.gr/velvet968thess"},
    {name = "Radio Art - Guitar", url = "http://air-tunein.radioart.com/fGuitar.mp3"},
    {name = "Disco Cafe", url = "https://azuracast.streams.ovh:8260/radio.mp3"},
    {name = "Fresh 105", url = "https://webradio.neatv.gr:8443/stream?1637751294799"},
    {name = "Radio Art - Roots Reggae", url = "https://live.radioart.com/fRoots_reggae.mp3"},
    {name = "Pirate Radio GR", url = "https://live.piratefm.net/top"},
    {name = "Radio Art - Indie", url = "https://live.radioart.com/fIndie.mp3"},
    {name = "Entropia", url = "https://radio.hostchefs.net/proxy/entropiaradio?mp=/stream"},
    {name = "Radio Art - Oldies", url = "https://live.radioart.com/fOldies.mp3"},
    {name = "Γνήσιος", url = "https://streamyourdream.org:8138/stream"},
    {name = "Kardia", url = "https://stream.crete.ovh:8443/kardia"},
    {name = "Mondo Bongo Radio", url = "http://eu1.reliastream.com:2199/tunein/mondobon.pls"},
    {name = "Greca 994", url = "https://cast2.radiohost.ovh/grecafm?mp=/stream"},
    {name = "One Radio Athens", url = "https://securestreams4.autopo.st:1599/LIVE?type=http&nocache=29"},
    {name = "101 FM1", url = "https://neos.win:59261/stream"},
    {name = "Amore 875", url = "http://s4.onweb.gr:8442/;"},
    {name = "12 Gods Cafe", url = "https://s4.myradiostream.com/:14374/;?type=http&nocache=1695638039?0.8040765476688225"},
    {name = "Rockarolla Radio", url = "https://solid2.streamupsolutions.com/proxy/msoepowo?mp=/stream"},
    {name = "Disco 1011", url = "https://stream-152.zeno.fm/8uhaz4x25bhvv?zs=96P8STqCRQKyBa82jb6QKQ"},
    {name = "Derti", url = "https://derti.live24.gr/derty1000"},
    {name = "Venus", url = "http://s3.onweb.gr:8808/"},
    {name = "MENTA 88", url = "https://netradio.live24.gr/menta88ath?1699021717"},
    {name = "KIIS Extra 922", url = "https://streams.enjoyfm.gr:48502/kiis.mp3"},
    {name = "Gtcrete", url = "https://sp2.streams.ovh/gtcrete/stream"},
    {name = "NRG 91", url = "https://sh.onweb.gr/9100/stream/;"},
    {name = "Blue Space 107,2 FM Athens", url = "https://sp1.19cloudsnetwork.gr/8008/stream?1701442520261"},
    {name = "Cosmos 1038", url = "http://n02.radiojar.com/duh3nm1v6hhvv?rj-ttl=5&rj-tok=AAABhLYSsOIAhf23KEeztv2SJw"},
    {name = "Μυτιλήνη 90", url = "http://cast5.magicstreams.gr:8041/stream?"},
    {name = "Thrakifm 998", url = "http://eco.onestreaming.com:8010/"},
    {name = "Angel 1028", url = "http://s5.onweb.gr:8502/stream?type=http&nocache=77822"},
    {name = "Live 896", url = "http://netradio.live24.gr/livefm896"},
    {name = "Radio Art - New Age", url = "http://air.radioart.com/fNew_age.mp3"},
    {name = "Box Radio 1049", url = "https://feelgood.radioca.st/stream"},
    {name = "Rtpress GR", url = "https://stream.rtpress.gr:8000/live"},
    {name = "Aria 1074", url = "https://cast4.magicstreams.gr/sc/oisvampg/stream"},
    {name = "Acropol 1242", url = "https://webinternetradio.eu:59373/"},
    {name = "My 80S GR", url = "http://cast2.radiohost.ovh:9051/;listen.pls"},
    {name = "Ellinadiko FM", url = "http://ellinadikofm.gr:8020/stream"},
    {name = "Paranomos", url = "https://stream-57.zeno.fm/ycvstp7s8hhvv?zs=V7Hd7pSnRDOrBfONi7Zoyw"},
    {name = "Radio Art - Jazz Ballads", url = "https://live.radioart.com/fJazz_ballads.mp3"},
    {name = "Smooth Radio Thessaloniki", url = "https://solid9.streamupsolutions.com/proxy/lrazisyb?mp=/live"},
    {name = "Συκολόγος", url = "https://sc2.streamwithq.com:2000/stream/sykologos/stream"},
    {name = "Σφαίρα Θεσσαλίας 907", url = "http://cast3.radiohost.ovh:8243/stream"},
    {name = "Jockey", url = "https://ec4.yesstreaming.net:2135/stream"},
    {name = "Radio Art - Spa", url = "http://air-tunein.radioart.com/fSpa.mp3"},
    {name = "Radio Art - Ambient", url = "http://air.radioart.com/fAmbient.mp3"},
    {name = "Blue Radio", url = "http://sip.blueradio.gr:8033/stream?type=http&nocache=308275"},
    {name = "Astra 992", url = "http://i6.streams.ovh:16134/stream?"},
    {name = "HROMA - VOLOS 882", url = "https://metrovolos882.live24.gr/metrovolos882"},
    {name = "Alpha FM", url = "http://stream.myip.gr:9219/stream"},
    {name = "Groove Radio", url = "https://cast.magicstreams.gr/ic/grooveradio/stream"},
    {name = "Radio Art - Didgeridoo", url = "http://air.radioart.com/fDidgeridoo.mp3"},
    {name = "Radio Art - Vocal Chillout", url = "http://air.radioart.com/fVocal_chillout.mp3"},
    {name = "Άγιος Σπυρίδων 911", url = "http://s3.onweb.gr:8462/"},
    {name = "Wild Radio", url = "http://sip.wildradio.gr:8037/stream?type=http&nocache=48915"},
    {name = "Streamee Entexno", url = "https://politismedia-sec3.live24.gr/pm-entexno"},
    {name = "Radio Art - Piano For Sleep", url = "http://air.radioart.com/fPiano_for_sleep.mp3"},
    {name = "Pemptousia FM", url = "http://stream.radiojar.com/48cz219puzzuv"},
    {name = "Aktina", url = "http://live.e-streaming.eu:8110/stream?type=http&nocache=1394"},
    {name = "Radio Melody Oldies", url = "https://i9.streams.ovh/sc/radiome2/stream"},
    {name = "SKGLOBENET | MIXED EMOTIONS", url = "https://smartstream.link/mixedemotions"},
    {name = "Galaxy Music The Love Songs", url = "https://stream-40.zeno.fm/718bfqy5muhvv?zs=CeIL1d5-Q9y1zBcvtH9iQw"},
    {name = "Rebetiko Sealabs", url = "https://rebetiko.sealabs.net/radio"},
    {name = "West", url = "http://hubble.shoutca.st:8167/stream"},
    {name = "Realfm978", url = "https://realfm.live24.gr/realfm"},
    {name = "Στο Κόκκινο Πάτρα 1077", url = "http://n05.radiojar.com/s5sa2z0mtceuv?rj-ttl=5&rj-tok=AAABhFP9IxQA9W5H323mo22S9Q"},
    {name = "MUSIC CLUB 1058", url = "https://antares.dribbcast.com/proxy/music1058?mp=/stream"},
    {name = "Rythmos FM", url = "http://ample.radiojar.com/aw1w2xfx1vduv.mp3"},
    {name = "Studio 2΄31", url = "https://webinternetradios.eu:59231/"},
    {name = "Μελωδία Ρόδου 1037", url = "http://live3.istoikona.com:8183/stream?type=http&nocache=25"},
    {name = "Radio Anemos", url = "http://168.119.74.185:9008/stream"},
    {name = "Palmos Radio", url = "http://live.onweb.gr:8010/;"},
    {name = "Mousiko Kanali 1051", url = "https://stream1.mousikokanali.gr/mc"},
    {name = "Galaxy Music Chillout Lounge", url = "https://stream-50.zeno.fm/kn8byvtb6uhvv?zs=VA1nby_MTFC8RxrEYdOJaw"},
    {name = "Alpha News 1062", url = "https://antares.dribbcast.com/proxy/alpha1062?mp=/stream"},
    {name = "Dance Wave", url = "https://dancewave.online/dance.mp3"},
    {name = "Radio Samos", url = "http://everest.streams.ovh:1850/stream"},
    {name = "Ράδιο Αναμνήσεις", url = "https://i8.streams.ovh/sc/radioanamnhseis/stream"},
    {name = "Radio Art - 21St Century", url = "http://air.radioart.com/f21st_Century.mp3"},
    {name = "Kifissia", url = "http://cast.streams.ovh:12097/;"},
    {name = "Flocafe London", url = "http://radio.anim8.gr:1290/stream"},
    {name = "ZOO New Hits", url = "https://metromedia.live24.gr/zoohitsthess"},
    {name = "Ρούμελη News 98", url = "https://live.webhosting4u.gr/radioroumelinews"},
    {name = "Πένα 1031", url = "https://tls-chrome.live24.gr/831?http://stream.sy3dud.com:8000/stream/2/"},
    {name = "Radio Art - For Study", url = "http://air-tunein.radioart.com/fFor_study.mp3"},
    {name = "Antennes Καστοριά", url = "http://cast.streams.ovh:9177/live?1494329758071"},
    {name = "Radio Art - Wind", url = "http://air.radioart.com/fWind_works.mp3"},
    {name = "Metal Lab", url = "https://stream-42.zeno.fm/x7e4uu23dm8uv?zs=p2fXqIYZTZyw7qnWV8s4uQ&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Xanthi Dee Jay 946", url = "http://onairmediagroup.live24.gr/radiodeejay946xanthi"},
    {name = "Rock Radio Station RRS", url = "https://i8.streams.ovh/sc/rockrad1/stream"},
    {name = "Φλόγα Ορθόδοξο Ραδιόφωνο", url = "https://stream-44.zeno.fm/s59eutgtf48uv?zs=BtI9INb_R0CICEqvBTbuHw&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Magic FM Agrinio", url = "https://www.magicfmagrinio.net/playerlinks/playlist.m3u"},
    {name = "Εν Πλώ Ηγουμενίτσα", url = "http://51.38.125.141:1070/enplofm?1538473095852"},
    {name = "Free Radio", url = "https://n09.radiojar.com/e206r95qsp8uv?rj-ttl=5&rj-tok=AAABjTeegtEAWNPK06lYDhypDQ"},
    {name = "Energy Radio Greece", url = "https://azuracast.streams.ovh/listen/energy/radio.mp3"},
    {name = "Ράδιο Καψούρα Πτολεμαΐδα", url = "https://sp2.streams.ovh/8044/stream"},
    {name = "Hit 935", url = "http://s3.onweb.gr:8006/;"},
    {name = "Fly Σπάρτη", url = "http://eco.onestreaming.com:8272/;"},
    {name = "962 FM1", url = "http://sc2.streamwithq.com:8092/;listen.pls"},
    {name = "Radio Art - Lullaby", url = "http://air.radioart.com/fLullaby.mp3"},
    {name = "269 FM", url = "https://neos.win:48006/lstream"},
    {name = "Radio Art - Inspiration", url = "http://air.radioart.com/fFor_inspiration.mp3"},
    {name = "Radio Art - Tantra", url = "http://air.radioart.com/fTantra.mp3"},
    {name = "Lyra 914", url = "https://i4.streams.ovh/ic/lyrafm/stream"},
    {name = "Streamee Salt", url = "https://politismedia-sec.live24.gr/streameesalt"},
    {name = "Streamee VFM", url = "https://politismedia-sec.live24.gr/streameevfm"},
    {name = "886 Kanali 20", url = "https://server.el1.info:37086/stream"},
    {name = "Radio Art - Joyful Classical", url = "http://air.radioart.com/fJoyful_classical.mp3"},
    {name = "Radio Art - Peaceful Classical", url = "http://air.radioart.com/fPeaceful_classical.mp3"},
    {name = "OFFRADIO", url = "http://s3.yesstreaming.net:7062/stream"},
    {name = "Streamee Chilly", url = "https://politismedia-sec.live24.gr/streameechilly"},
    {name = "Kiss 98", url = "https://s6.onweb.gr:7029/stream.mp3"},
    {name = "Streamee Greek Hits", url = "https://politismedia-sec3.live24.gr/pm-greekhits"},
    {name = "Radio In", url = "http://www.radioin.link:8383/stream"},
    {name = "Streamee Hot Hits", url = "https://politismedia-sec3.live24.gr/pm-hothits"},
    {name = "Radio Art - Chopin", url = "http://air.radioart.com/fChopin.mp3"},
    {name = "Streamee Rock’N’Roll", url = "https://politismedia-sec3.live24.gr/pm-rocknroll"},
    {name = "Ράδιο Λευκίμμη 1055", url = "https://i3.streams.ovh/ic/radiolefkimmi/stream"},
    {name = "Radio Art - Antonio Vivaldi", url = "http://air.radioart.com/fVivaldi.mp3"},
    {name = "Life FM 88 Kalamata", url = "https://streams.enjoyfm.gr:48502/life.mp3"},
    {name = "Reboot Radio", url = "http://88.198.8.51:8471/stream"},
    {name = "Family 895", url = "http://193.227.111.111:8002/;"},
    {name = "Metalourgio", url = "http://cast.metalourgio.com:9043/stream.pls/"},
    {name = "Radio Art - Reflexology", url = "http://air.radioart.com/fReflexology.mp3"},
    {name = "Streamee Cofee Music", url = "https://politismedia-sec3.live24.gr/pm-halloween"},
    {name = "Ξυλαγανή 1045", url = "http://solid2.streamupsolutions.com:24950/stream"},
    {name = "Weloveradio GR", url = "https://solid67.streamupsolutions.com/proxy/xgrdbxsg?mp=/live_live"},
    {name = "Meli 1066", url = "https://i3.streams.ovh:12064/live"},
    {name = "Radio Art - Latin Jazz", url = "http://air.radioart.com/fLatin_jazz.mp3"},
    {name = "Free Central Greece", url = "http://sh.onweb.gr:8634/stream?type=http&nocache=45"},
    {name = "Εν Τεχνο", url = "https://en-texno.com:8085/stream128_autodj"},
    {name = "Radio Art - Mantras", url = "http://air.radioart.com/fMantras.mp3"},
    {name = "Radio Art - Gypsy Jazz", url = "http://air.radioart.com/fGypsy_jazz.mp3"},
    {name = "KIIS 958", url = "http://streams.enjoyfm.gr:48500/kiis958.mp3"},
    {name = "XFM GR", url = "https://solid1.streamupsolutions.com/proxy/zizthduh?mp=/=stream"},
    {name = "Vivagr 1028", url = "https://solid9.streamupsolutions.com/proxy/ehrehten?mp=/;type=mp3?ver=983003"},
    {name = "Xryses Notes", url = "https://cast.radiohost.ovh:9031/live"},
    {name = "Streamee Greek Rap 18+", url = "https://politismedia-sec3.live24.gr/pm-hiphop"},
    {name = "AFN 360 Souda Bay", url = "http://playerservices.streamtheworld.com/m3u/AFNE_SDB.m3u"},
    {name = "Μύθος", url = "http://s2.free-shoutcast.com:18560/stream/;.mp3"},
    {name = "Zarpa Χανιά", url = "http://s3.onweb.gr:8454/stream?type=http&nocache=21370"},
    {name = "Athens Noise Rocks", url = "https://radio.athensnoise.rocks/listen/athensnoise.rocks/radio.mp3"},
    {name = "Αυθεντικό GR", url = "https://solid33.streamupsolutions.com/proxy/xbygwcwv/stream"},
    {name = "Κρήτη 1003", url = "https://i9.streams.ovh:2200/sc/kritifm1003/stream"},
    {name = "Filadelfeia GR", url = "https://s2.e-resellers.gr:19000/live"},
    {name = "Παύλειος Λόγος - ΙMΒΝΚ 902", url = "http://eco.onestreaming.com:8548/"},
    {name = "Star Λαμία", url = "http://eco.onestreaming.com:8434/stream?type=http&nocache=107"},
    {name = "Ak Radio", url = "http://sc2.streamwithq.com:8048/"},
    {name = "Fresh Athens Radio", url = "https://stream-57.zeno.fm/4k0w7ye23k8uv?zs=0xJ4ehZhQG2OsTOAeoGOyg"},
    {name = "Radio Megalonisos", url = "http://s3.onweb.gr:8540/"},
    {name = "Streamee Kids’ Party", url = "https://politismedia-sec3.live24.gr/pm-kidsparty"},
    {name = "Sin", url = "https://solid67.streamupsolutions.com/proxy/lqomhdjk?mp=//stream"},
    {name = "Palmos 1032", url = "https://netradio.live24.gr/palmos1032"},
    {name = "Joy", url = "http://n0c.radiojar.com/2nwynzgmb.mp3?rj-ttl=5&rj-tok=AAABeLhLVlcA21aDOVvm7eqVCQ"},
    {name = "La Famiglia", url = "https://cast.magicstreams.gr:9010/stream?type=http&nocache=1/;"},
    {name = "Λέχοβο 971", url = "http://s4.onweb.gr:8468/stream?type=http&nocache=62788"},
    {name = "The Pressproject", url = "http://ample-11.radiojar.com/qgra821mrtwtv?rj-ttl=5&rj-token=AAABaTjQgJCWOqfpbPGt1vFvtByvc0IHsQffGMFUDEfQLg0qLSoSRg"},
    {name = "Shook", url = "http://s1.onweb.gr:8812/;"},
    {name = "Velvet 984", url = "http://onairmediagroup.live24.gr/velvet984xanthi"},
    {name = "Radio Art - Latin", url = "http://air.radioart.com/fLatin.mp3"},
    {name = "Radio Art - Aura2", url = "http://air.radioart.com/fAura.mp3"},
    {name = "Tppradio Thepressproject", url = "http://stream.radiojar.com/qgra821mrtwtv.mp3"},
    {name = "Ρυθμός 106", url = "http://onairmediagroup.live24.gr/rythmos106xanthi"},
    {name = "Soul Radio GR", url = "https://cast4.magicstreams.gr:10053/stream"},
    {name = "Studio Delta GR", url = "https://i2.streams.ovh/ic/studiode/stream"},
    {name = "Radio Art - Smooth Up Tempo", url = "http://air.radioart.com/fSmooth_up_tempo.mp3"},
    {name = "Love Classic", url = "http://n0f.radiojar.com/gt0xy4z88f0uv?rj-ttl=5&rj-tok=AAABeL0p0LoA-5x-FfgVSPOA6w"},
    {name = "Radio Art - Saxophone Jazz", url = "http://air.radioart.com/fSaxophone_jazz.mp3"},
    {name = "Radio Art - Jsbach", url = "http://live.radioart.com/fBach.mp3"},
    {name = "Olympos 1002", url = "http://eco.onestreaming.com:8146/;"},
    {name = "Kiss 1004", url = "http://sp2.streams.ovh:8096/stream?type=http&nocache=99"},
    {name = "Πάρος 985", url = "http://s1.onweb.gr:8098/;"},
    {name = "Radio Art - Greek Art For Kids", url = "http://air.radioart.com/fGreek_art_for_kids.mp3"},
    {name = "Radio Art - Music For Kids", url = "http://air.radioart.com/fMusic_for_kids.mp3"},
    {name = "Radio Art - Eric Satie", url = "http://air.radioart.com/fEric_satie.mp3"},
    {name = "Radio Art - Inspire", url = "http://air.radioart.com/fDisney.mp3"},
    {name = "Blu Lounge Radio", url = "https://streamyourdream.org:8100/stream"},
    {name = "Χρώμα 919", url = "http://netradio.live24.gr/hroma918"},
    {name = "Brake Κόρινθος", url = "http://proradio.gr:8004/brake"},
    {name = "Roxx Radio", url = "http://n08.radiojar.com/aay95tkmb?1676622496=&rj-tok=AAABhl6Gxj0AhPNmYI0wOR0gkA&rj-ttl=5"},
    {name = "Studio 54 Volos", url = "https://cast.magicstreams.gr:9017/stream"},
    {name = "Streamee Beach Bar", url = "https://politismedia-sec3.live24.gr/pm-vertis"},
    {name = "Streamee Hotels Luxury Bars", url = "https://politismedia-sec3.live24.gr/pm-gaming"},
    {name = "Παραδοσιακός 1066", url = "http://sp2.streams.ovh:8104/stream?type=http&nocache=763"},
    {name = "Streamee Fine Dining", url = "https://politismedia-sec3.live24.gr/pm-dining"},
    {name = "Real Classic GR", url = "https://netradio.live24.gr/realclassic"},
    {name = "Streamee New Rock", url = "https://politismedia-sec3.live24.gr/pm-newrock"},
    {name = "Superhitradio", url = "https://s10.streamingcloud.online/stream/13578/Superhitradio"},
    {name = "BARS RADIO", url = "http://88.99.171.20:8020/stream"},
    {name = "Rainbow 89 Christmas", url = "http://stream.radiojar.com/4nwwcyesv8hvv"},
    {name = "Σταγών Καλαμπάκα", url = "http://s1.onweb.gr:8830/stream?type=http&nocache=19162"},
    {name = "Mousikos 986", url = "http://netradio.live24.gr/mousikos986"},
    {name = "Νεάπολις 908", url = "https://radio.divographics.com:8030/radio.mp3"},
    {name = "Φάρος 104", url = "http://s41.myradiostream.com:28554/;?type=http&nocache=73527"},
    {name = "AEL 1048", url = "https://mediacp.32bit.gr:2000/stream/ael-sh"},
    {name = "To Pikap Radio", url = "https://radiopikap.radioca.st/stream"},
    {name = "Μελωδία 1068", url = "http://eu5.fastcast4u.com:5020/stream"},
    {name = "Nitro Radio", url = "https://politisradios.live24.gr/streameenitro"},
    {name = "Ραδιοενέργεια", url = "http://s1.onweb.gr:8828/;"},
    {name = "ΔΙΑΥΛΟΣ FM 992", url = "https://server.el1.info:37060/stream"},
    {name = "Proto Κως", url = "http://server.insms.gr:45114/;stream.mp3"},
    {name = "DRS 953", url = "http://drs953.live24.gr/drs953"},
    {name = "Santorini Jazz Radio", url = "https://stream.santorinijazzradio.com/a2vmt89kd5uvv"},
    {name = "Κόσμος 938", url = "https://netradio.live24.gr/kosmos938rodos"},
    {name = "Aposperitis 945", url = "http://eco.onestreaming.com:8600/;"},
    {name = "Ραδιοφωνία Κυκλαδων 1013", url = "http://ice.streamcloud.mediacdn.com/rkykladwn"},
    {name = "Rock And Blues Athens", url = "https://tls-chrome.live24.gr/3253?http://78.129.132.7:35663/"},
    {name = "Rock Velvet Radio", url = "https://free.rcast.net/62225"},
    {name = "Mancode", url = "http://comet.shoutca.st:8366/;"},
    {name = "Μαρτυρία 955", url = "https://sc2.streamwithq.com:2000/stream/martiria"},
    {name = "Λυδία FM 942", url = "http://eu1.radiolydia.com:1086/;"},
    {name = "D-Code 962", url = "https://s15.myradiostream.com/:13980/listen.mp3"},
    {name = "Αντέννα Δυτικής Κρήτης 971", url = "http://sc2.streamwithq.com:8008/;stream.mp3"},
    {name = "Radio Art - Big Bands", url = "http://air-tunein.radioart.com/fBig_bands.mp3"},
    {name = "Star 977", url = "https://solid55.streamupsolutions.com/proxy/vkpzhens?mp=/stream"},
    {name = "Radio Art - A Cappella", url = "https://live.radioart.com/fA_Cappella.mp3"},
    {name = "Magic 982", url = "https://netradio.live24.gr/magic982"},
    {name = "Antenna Νότιας Ελλάδας 972", url = "http://eco.onestreaming.com:8510/;"},
    {name = "Δρόμος 1054", url = "https://sc2.streamwithq.com:8124/stream?type=http&nocache=239"},
    {name = "Radio 984", url = "https://cast4.my-control-panel.com/proxy/anastas2/stream"},
    {name = "Jadore", url = "https://i6.streams.ovh:2200/ssl/jadore?mp=/stream"},
    {name = "Adelin 1073", url = "http://cast.magicstreams.gr:8050/stream?type=http&nocache=368"},
    {name = "Laiko 107", url = "https://stream-19.zeno.fm/58uqx820dnzuv?zs=OPfJ6wakTOq-2IVqejRhMg"},
    {name = "Melody 888", url = "http://stream.melody888.gr:48500/melody.mp3"},
    {name = "Mple 99 Fm", url = "https://n10.radiojar.com/f4pqr7wu48hvv?rand=604321&rj-tok=AAABhwia68IAEMa7tAHWaQFpDg&rj-ttl=5"},
    {name = "Λυχνάρι 914", url = "http://eco.onestreaming.com:8037/;"},
    {name = "Ρυθμός 945", url = "https://netradio.live24.gr/rythmos945rodos"},
    {name = "Alpha 886", url = "http://proradio.gr:8004/alpharadio"},
    {name = "Radio Art - Mellow Smooth Jazz", url = "https://live.radioart.com/fMellow_smooth_jazz.mp3"},
    {name = "Ραδιοφράγματα", url = "http://185.86.150.52:8000/live"},
    {name = "Me 884", url = "https://eco.onestreaming.com/proxy/radiome/stream"},
    {name = "Coffee Web Radio", url = "https://solid9.streamupsolutions.com/proxy/teqgebwz/stream"},
    {name = "Tiger Radio Greece", url = "http://sirius.shoutca.st:8198/stream.mp3?1561554299276"},
    {name = "Radio Art - Stress Relief", url = "http://air-tunein.radioart.com/fStress_relief.mp3"},
    {name = "Kiss 89", url = "https://kiss-89-kalamata.live24.gr/kiss89kalamata"},
    {name = "Στόχος 99", url = "http://s3.onweb.gr:8016/stream?type=http&nocache=906097"},
    {name = "Techno Base 1031", url = "https://stream-10.zeno.fm/izyb6gtfozpuv?zs=hRR4wSYGTi2FdjV89bXz5g&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Focus 888", url = "http://s3.onweb.gr:8014/stream?type=http&nocache=120452"},
    {name = "KIIS Extra 938", url = "http://stream.kiisextra.gr:48500/kiis.mp3"},
    {name = "ΕΑΠ Study Relax", url = "http://n10.radiojar.com/u2a94hrbay8uv?rj-ttl=5&rj-tok=AAABhSHvuxgAfKxDjBnr3Q1v5A"},
    {name = "Rock Lab Ballads", url = "https://stream.zeno.fm/xqyzz6vzmg8uv?acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Beteranos", url = "http://s33.myradiostream.com:6482/;?1633097841057"},
    {name = "Luciano Pavarotti", url = "http://air.radioart.com/fLuciano_pavarotti.mp3"},
    {name = "Radio Art-Opera", url = "http://air.radioart.com/fOpera.mp3"},
    {name = "Παμβώτις 1057", url = "http://iphone.live24.gr/pamvotis1057ioannina"},
    {name = "Sky Ρόδος", url = "http://s6.myradiostream.com:45076/;listen.mp3;audio.mp3?hash=1528711740048"},
    {name = "DJ 105", url = "https://stream-59.zeno.fm/jifm5pk5vzxvv?zs=dK5Kx1B3RXOqYT2fGxyUtw&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Hot Lips", url = "http://netradio.live24.gr/radiohotlips"},
    {name = "Studio Arxontissa", url = "https://stream-51.zeno.fm/fkxvbxbz6bhvv?zs=BlIWuazNQaSpewuv6SyeJQ&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Action", url = "http://stream-31.zeno.fm/7p30ef2u2a0uv?zs=Ogf1XqXHSOKHr1BKxHIAFw"},
    {name = "Hit Eclectic", url = "http://netradio.live24.gr/bootleg"},
    {name = "Figaro Disco", url = "https://stream-54.zeno.fm/u9b7ayh6na0uv?zs=4AtzkttTQW-_6v5G19WIEQ&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Καντίνι Web Radio", url = "https://fra-pioneer08.dedicateware.com/kantiniradio"},
    {name = "Star Channel GR", url = "https://24streams.gr/9999/stream"},
    {name = "Best 947", url = "http://bestradio.net:9470/stream?type=http&nocache=166"},
    {name = "Power 932", url = "http://mediacp.32bit.gr:8002/stream"},
    {name = "Sevi", url = "http://cast.streams.ovh:9035/live"},
    {name = "Ράδιο Ειρήνη", url = "https://i3.streams.ovh/sc/demo/stream"},
    {name = "Athens Metro Mall", url = "http://mmr.yourstreaming.gr:9300/;"},
    {name = "Blublu Radio", url = "http://go.radioin.audio:8488/;"},
    {name = "Μελωδία Πάτρας 1004", url = "http://i.streams.ovh:9523/stream?type=http&nocache=373"},
    {name = "Symi Radio", url = "https://stream-47.zeno.fm/2me3a1e6ag0uv?zs=3WKmTDgjSoW6sclZWjyckg"},
    {name = "City 1038", url = "https://server.el1.info:37027/stream"},
    {name = "City 93", url = "http://radio.city93.gr:9996/stream?type=http&nocache=89"},
    {name = "Must", url = "http://176.58.122.60:8000/stream"},
    {name = "88Miso", url = "https://solid33.streamupsolutions.com/proxy/sxxaojkx?mp=/stream"},
    {name = "Top 93", url = "https://netradio.live24.gr/topfm93patra"},
    {name = "Movementradio 2", url = "https://movementathens2.out.airtime.pro/movementathens2_a"},
    {name = "Mikis Radio Folk", url = "http://radio.hostchefs.eu:8065/stream"},
    {name = "Makedonia 1386", url = "https://webinternetradio.eu:48238/"},
    {name = "Ρυθμός 988", url = "https://mediacp.32bit.gr:2000/stream/rythmos988"},
    {name = "Ρυθμός 974", url = "http://sc2.streamwithq.com:8034/;stream.mp3"},
    {name = "ΕΡΤ Open 1067", url = "https://netradio.live24.gr/erasport"},
    {name = "Radio Art - Aura", url = "http://air-tunein.radioart.com/fAura.mp3"},
    {name = "Σφαίρα Θεσσαλίας 1016", url = "http://cast3.radiohost.ovh:8280/stream"},
    {name = "Star 888", url = "http://onairmediagroup.live24.gr/star888xanthi"},
    {name = "Μεσσατίδα 98", url = "https://cast4.magicstreams.gr:2200/ssl/rnamozwi?mp=/stream&1668884587044"},
    {name = "Greek Otaku Radio", url = "http://usa2.fastcast4u.com:3684/;"},
    {name = "Ρυθμός 916", url = "http://cast5.magicstreams.gr:8028/stream?"},
    {name = "Minore 968", url = "https://i4.streams.ovh:2200/ssl/minore?mp=/stream"},
    {name = "Σκάι Αιγαίου 998", url = "http://live.isol.biz:8500/;stream.nsv"},
    {name = "Metro 903", url = "http://netradio.live24.gr/agia"},
    {name = "Rare Radio", url = "http://bestgreek.info:8104/"},
    {name = "Μεγαλόνησος 898", url = "http://s3.onweb.gr:8540/stream"},
    {name = "ΙΜ Σπάρτης 888", url = "http://s4.onweb.gr:8862/"},
    {name = "Disco500", url = "http://stream.zeno.fm/aqe61pyu4yzuv"},
    {name = "Fraoulitsa", url = "https://webinternetradio.eu:59402/"},
    {name = "Nova 921", url = "https://sh.onweb.gr:7125/;stream.mp3"},
    {name = "Must Cafe GR", url = "https://stream.radiomustathens.com/must-cafe?app=true&refer="},
    {name = "Μελωδικός 1057", url = "http://eco.onestreaming.com:8054/;"},
    {name = "Must Hero GR", url = "https://stream.radiomustathens.com/must-hero?app=true&refer="},
    {name = "Sok GR", url = "https://24streams.gr/8071/stream"},
    {name = "Radio Art - Vocal Lounge", url = "http://air.radioart.com/fVocal_lounge.mp3"},
    {name = "Speak Radio GR", url = "https://i4.streams.ovh/sc/speakradio/stream"},
    {name = "Super FM Thessaloniki", url = "https://ice.greekstream.net/superfm"},
    {name = "Flash 994", url = "https://webradio.northbridge.gr/proxy/flash994/source"},
    {name = "Chillout Tree Pines", url = "http://n0f.radiojar.com/n4dzb3znn3quv.mp3?rj-ttl=5&rj-tok=AAABeKi_TokAUTY4EzBEHHiJzQ"},
    {name = "City 1061", url = "https://ice.greekstream.net/city1061.m3u"},
    {name = "Radio Play 915 Fm Stereo Gr Xanthi", url = "http://s6.onweb.gr:8058/"},
    {name = "Palmos 983", url = "http://ice.streamcloud.mediacdn.com/palmos983"},
    {name = "Χρυσές Νότες", url = "http://cast.radiohost.ovh:9031/live"},
    {name = "Avanti 1076", url = "http://avantifm.live24.gr/avantifm"},
    {name = "Radio Art - Piano", url = "http://air.radioart.com/fPiano.mp3"},
    {name = "Focus FM 1036", url = "https://ice.greekstream.net/focusfm.m3u"},
    {name = "Streamee Smooth Jazz", url = "https://politismedia-sec.live24.gr/streameepanama"},
    {name = "Streamee Classic Jazz", url = "https://politismedia-sec3.live24.gr/pm-sfakianakis"},
    {name = "Radio Art - Positivity", url = "http://air.radioart.com/fPositivity.mp3"},
    {name = "Streamee Classical", url = "https://politismedia-sec.live24.gr/streameesymphony"},
    {name = "Fidelio Erotica", url = "https://stream-59.zeno.fm/98g6y8a8m5zuv?zs=umdG3XPaRUm8qVwFMWMM3Q&acu-uid=727435602967&triton-uid=cookie%3A83ca5b14-582e-4c12-a5ab-255cdb39e2cb"},
    {name = "Praktoreio 1049 FM", url = "https://ice.greekstream.net/praktoreio.m3u"},
    {name = "Vasilis Cfu Oldies 80S 90S", url = "https://stream-40.zeno.fm/ycn3vfnpzd0uv?zs=0k3c5mUNRAOq6rzcVkolfg"},
    {name = "Streamee 90S Clubbing", url = "https://politismedia-sec3.live24.gr/pm-90"},
    {name = "Ιερά Μητρόπολις Άρτης 1066", url = "http://i.streams.ovh:9566/live"},
    {name = "Scorpios Athens Radio", url = "https://cast.streams.ovh:2200/ssl/scorpio1?mp=/stream"},
    {name = "Mousiko Kanali", url = "http://stream1.mousikokanali.gr:8100/mc?.mp3"},
    {name = "Στουρναραίικα 925", url = "https://i8.streams.ovh/sc/radiostournareika/stream"},
    {name = "Rock` N Other", url = "https://solid41.streamupsolutions.com/proxy/yzltwqtc?mp=/stream"},
    {name = "Radio Art - Tango", url = "http://air.radioart.com/fTango.mp3"},
    {name = "Mousikos 98,6", url = "https://netradio.live24.gr/mousikos986"},
    {name = "Ζημιά 945", url = "https://www.gointernet.gr:9034/live?1677414458691"},
    {name = "A Patras 944", url = "https://netradio.live24.gr/alpha944patra"},
    {name = "Ελληνικό Παραδοσιακό Ραδιόφωνο", url = "http://i2.streams.ovh:7058/stream1"},
    {name = "Master", url = "https://stream1.468.gr/9902/stream"},
    {name = "Retro 937", url = "https://sp.streams.ovh/8056/stream"},
    {name = "Radio Art - Smooth Lounge", url = "http://air.radioart.com/fSmooth_lounge.mp3"},
    {name = "Τεριρέμ", url = "https://c34.radioboss.fm:18213/stream"},
    {name = "Beton7 Art Radio", url = "https://uk1.streamingpulse.com/ssl/b7artradio"},
    {name = "Real FM", url = "https://realfm2.live24.gr/realfm"},
    {name = "1022 Αλιβέρι 1", url = "http://88.99.239.52:9300/;"},
    {name = "Radio Art - Chillout Tropical", url = "http://air.radioart.com/fChillout_and_tropical.mp3"},
    {name = "Radio Art - Ludovico Einaudi", url = "https://live.radioart.com/fLudovico_einaudi.mp3"},
    {name = "Radio Art - Dreamscapes", url = "http://air.radioart.com/fDreamscapes.mp3"},
    {name = "88 FM Radio 1", url = "http://www.111.gr:8000/stream?type=http&nocache=181015"},
    {name = "Radio Art - Reiki", url = "http://air.radioart.com/fReiki.mp3"},
    {name = "RED 80'S", url = "https://n13a-eu.rcs.revma.com/40uryq80ubuvv?rj-ttl=5&rj-tok=AAABkbSeZioAdeT-a0mzJYc8Fg"},
    {name = "Lemon 888", url = "https://cast.streams.ovh/sc/radio888/stream/"},
    {name = "RED METAL", url = "https://n43a-eu.rcs.revma.com/pt14gt80ubuvv?rj-ttl=5&rj-tok=AAABkbShL7oAdA1dRWi_lkF2LQ"},
    {name = "Xilia Diamantia", url = "https://i8.streams.ovh/ic/xiliadiamantia/stream"},
    {name = "Dream Ηράκλειο", url = "https://neos.win:48420/stream"},
    {name = "RED 90'S", url = "https://n22a-eu.rcs.revma.com/vwqwss80ubuvv?rj-ttl=5&rj-tok=AAABkbSjjC0A3V6E1GQeHmzlGA"},
    {name = "Prime 1003", url = "http://s20.myradiostream.com:6738/;listen.pls"},
}

return stations
