#!/usr/bin/env python3
"""Generate deterministic Lua locale artifacts from canonical locale JSON."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from pathlib import Path

from generated_payloads import (
    CLIENT_SENT_LZMA_TARGET,
    LOCALE_CHUNK_MAX_JSON_BYTES,
    PayloadFile,
    render_payload_return_file,
    validate_client_sent_file,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "data" / "locales"
OUTPUT_DIR = REPO_ROOT / "lua" / "rradio" / "client" / "lang"

GENERATED_HEADER = "-- Generated by scripts/build_locale_artifacts.py; do not edit by hand."
LANG_RE = re.compile(r"^[a-z][a-z0-9_]*$")
SECTIONS = ("ui", "themes", "countries")


@dataclass(frozen=True)
class LocaleFragment:
    lang: str
    fragment_index: int
    global_index: int
    data: dict[str, dict[str, str]]
    single_file_sent_size: int


@dataclass
class LocaleChunkBin:
    fragments: list[LocaleFragment]


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def load_locales(source_dir: Path = SOURCE_DIR) -> dict[str, dict[str, dict[str, str]]]:
    if not source_dir.exists():
        raise ValueError(f"missing locale source directory: {display_path(source_dir)}")

    locales: dict[str, dict[str, dict[str, str]]] = {}
    for path in sorted(source_dir.glob("*.json")):
        lang = path.stem
        if not LANG_RE.match(lang):
            raise ValueError(f"{display_path(path)} has invalid language id: {lang!r}")
        if lang in locales:
            raise ValueError(f"duplicate locale language: {lang!r}")

        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{display_path(path)} must contain a JSON object")
        unknown_sections = sorted(set(data) - set(SECTIONS))
        if unknown_sections:
            raise ValueError(
                f"{display_path(path)} has unknown section(s): {', '.join(unknown_sections)}"
            )

        locale: dict[str, dict[str, str]] = {}
        for section in SECTIONS:
            rows = data.get(section, {})
            if rows is None:
                rows = {}
            if not isinstance(rows, dict):
                raise ValueError(f"{display_path(path)} section {section!r} must be an object")

            normalized_rows: dict[str, str] = {}
            for key in sorted(rows):
                value = rows[key]
                if not isinstance(key, str) or not isinstance(value, str):
                    raise ValueError(
                        f"{display_path(path)} section {section!r} must map strings to strings"
                    )
                normalized_rows[key] = value
            if normalized_rows:
                locale[section] = normalized_rows

        locales[lang] = locale

    if not locales:
        raise ValueError(f"no locale JSON files found in {display_path(source_dir)}")
    if "en" not in locales:
        raise ValueError("missing required English locale: data/locales/en.json")

    return locales


def locale_chunk_payload(items: list[tuple[str, dict[str, dict[str, str]]]]) -> dict[str, object]:
    locales: dict[str, dict[str, dict[str, str]]] = {}

    for lang, data in items:
        locale = locales.setdefault(lang, {})
        for section in SECTIONS:
            rows = data.get(section, {})
            if not rows:
                continue
            target = locale.setdefault(section, {})
            for key, value in rows.items():
                if key in target and target[key] != value:
                    raise ValueError(f"locale {lang!r} has conflicting {section}.{key} values")
                target[key] = value

    return {
        "version": 1,
        "locales": locales,
    }


def render_locale_chunk(items: list[tuple[str, dict[str, dict[str, str]]]]) -> PayloadFile:
    return render_payload_return_file(
        header=GENERATED_HEADER,
        kind="locale_chunk",
        payload=locale_chunk_payload(items),
    )


def _locale_chunk_fits(rendered: PayloadFile) -> bool:
    return (
        rendered.lua_sent_lzma_size <= CLIENT_SENT_LZMA_TARGET
        and rendered.json_size <= LOCALE_CHUNK_MAX_JSON_BYTES
    )


def _validate_locale_chunk(label: str, rendered: PayloadFile) -> None:
    validate_client_sent_file(label, rendered)
    if rendered.json_size > LOCALE_CHUNK_MAX_JSON_BYTES:
        raise ValueError(
            f"{label} JSON payload is {rendered.json_size} bytes, exceeding "
            f"{LOCALE_CHUNK_MAX_JSON_BYTES} byte runtime decode limit"
        )


def _single_locale_fragment_size(lang: str, data: dict[str, dict[str, str]]) -> PayloadFile:
    return render_locale_chunk([(lang, data)])


def split_locale_to_fragments(
    lang: str,
    data: dict[str, dict[str, str]],
    global_index_start: int,
) -> list[LocaleFragment]:
    rendered = _single_locale_fragment_size(lang, data)
    if _locale_chunk_fits(rendered):
        return [
            LocaleFragment(
                lang=lang,
                fragment_index=0,
                global_index=global_index_start,
                data=data,
                single_file_sent_size=rendered.lua_sent_lzma_size,
            )
        ]

    fragments: list[LocaleFragment] = []
    fragment_index = 0
    global_index = global_index_start

    for section in SECTIONS:
        rows = data.get(section, {})
        if not rows:
            continue

        section_data = {section: rows}
        section_rendered = _single_locale_fragment_size(lang, section_data)
        if _locale_chunk_fits(section_rendered):
            fragments.append(
                LocaleFragment(
                    lang=lang,
                    fragment_index=fragment_index,
                    global_index=global_index,
                    data=section_data,
                    single_file_sent_size=section_rendered.lua_sent_lzma_size,
                )
            )
            fragment_index += 1
            global_index += 1
            continue

        entries = list(rows.items())
        offset = 0
        while offset < len(entries):
            lo = 1
            hi = len(entries) - offset
            best = 0
            best_size = 0

            while lo <= hi:
                mid = (lo + hi) // 2
                subset = dict(entries[offset : offset + mid])
                candidate_data = {section: subset}
                candidate = _single_locale_fragment_size(lang, candidate_data)

                if _locale_chunk_fits(candidate):
                    best = mid
                    best_size = candidate.lua_sent_lzma_size
                    lo = mid + 1
                else:
                    hi = mid - 1

            if best <= 0:
                key, value = entries[offset]
                candidate = _single_locale_fragment_size(lang, {section: {key: value}})
                raise ValueError(
                    f"single locale row {lang}.{section}.{key} is "
                    f"{candidate.lua_sent_lzma_size} compressed bytes and "
                    f"{candidate.json_size} JSON bytes"
                )

            fragments.append(
                LocaleFragment(
                    lang=lang,
                    fragment_index=fragment_index,
                    global_index=global_index,
                    data={section: dict(entries[offset : offset + best])},
                    single_file_sent_size=best_size,
                )
            )
            offset += best
            fragment_index += 1
            global_index += 1

    return fragments


def build_locale_fragments(
    locales: dict[str, dict[str, dict[str, str]]],
) -> list[LocaleFragment]:
    fragments: list[LocaleFragment] = []
    global_index = 0

    for lang, data in sorted(locales.items()):
        lang_fragments = split_locale_to_fragments(lang, data, global_index)
        fragments.extend(lang_fragments)
        global_index += len(lang_fragments)

    return fragments


def render_locale_bin(bin_: LocaleChunkBin) -> PayloadFile:
    ordered = sorted(bin_.fragments, key=lambda fragment: fragment.global_index)
    return render_locale_chunk([(fragment.lang, fragment.data) for fragment in ordered])


def pack_locale_fragments(fragments: list[LocaleFragment]) -> list[LocaleChunkBin]:
    bins: list[LocaleChunkBin] = []
    ordered_fragments = sorted(
        fragments,
        key=lambda fragment: (
            -fragment.single_file_sent_size,
            fragment.lang,
            fragment.fragment_index,
        ),
    )

    for fragment in ordered_fragments:
        best_index: int | None = None
        best_size: int | None = None

        for index, bin_ in enumerate(bins):
            candidate = LocaleChunkBin(fragments=[*bin_.fragments, fragment])
            rendered = render_locale_bin(candidate)
            size = rendered.lua_sent_lzma_size

            if _locale_chunk_fits(rendered) and (
                best_size is None or size > best_size
            ):
                best_index = index
                best_size = size

        if best_index is None:
            singleton = LocaleChunkBin(fragments=[fragment])
            rendered = render_locale_bin(singleton)
            if not _locale_chunk_fits(rendered):
                raise ValueError(
                    f"locale fragment {fragment.lang}#{fragment.fragment_index} "
                    f"is {rendered.lua_sent_lzma_size} compressed bytes and "
                    f"{rendered.json_size} JSON bytes"
                )
            bins.append(singleton)
        else:
            bins[best_index].fragments.append(fragment)

    return bins


def build_chunks(
    locales: dict[str, dict[str, dict[str, str]]],
) -> list[tuple[str, str]]:
    fragments = build_locale_fragments(locales)
    bins = pack_locale_fragments(fragments)

    chunks: list[tuple[str, str]] = []
    for index, bin_ in enumerate(bins, 1):
        chunk_name = f"data_{index:03d}.lua"
        rendered = render_locale_bin(bin_)
        _validate_locale_chunk(chunk_name, rendered)
        chunks.append((chunk_name, rendered.text))

    return chunks


def render_artifacts(locales: dict[str, dict[str, dict[str, str]]]) -> dict[str, str]:
    return dict(build_chunks(locales))


def write_artifacts(output_dir: Path = OUTPUT_DIR, source_dir: Path = SOURCE_DIR) -> None:
    locales = load_locales(source_dir)
    artifacts = render_artifacts(locales)

    output_dir.mkdir(parents=True, exist_ok=True)
    for old_file in output_dir.glob("*.lua"):
        old_file.unlink()

    for filename, text in artifacts.items():
        (output_dir / filename).write_text(text, encoding="utf-8")

    print(f"Generated {len(locales)} locale artifacts in {len(artifacts)} chunks")


def main() -> int:
    write_artifacts()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
