#!/usr/bin/env python3
"""Generate deterministic Lua station artifacts from canonical station JSON."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from pathlib import Path
from typing import Iterator

from generated_payloads import (
    CLIENT_SENT_LZMA_TARGET,
    CLIENT_STATION_CHUNK_MAX_JSON_BYTES,
    SERVER_REGISTRY_MAX_JSON_BYTES,
    PayloadFile,
    render_payload_return_file,
    render_server_registry_file,
    validate_client_sent_file,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "data" / "stations.json"
SERVER_PATH = REPO_ROOT / "lua" / "rradio" / "server" / "stations" / "builtin_registry.lua"
SERVER_GENERATED_DIR = REPO_ROOT / "lua" / "rradio" / "server" / "stations" / "generated"
CLIENT_PATH = REPO_ROOT / "lua" / "rradio" / "client" / "stations" / "builtin_catalog.lua"
CLIENT_GENERATED_DIR = REPO_ROOT / "lua" / "rradio" / "client" / "stations" / "generated"

ID_RE = re.compile(r"^[A-Za-z0-9_\-:.]+$")
URL_RE = re.compile(r"^(https?|mms)://", re.IGNORECASE)
SERVER_STATIONS_PER_FUNCTION = 30_000
STATION_ID_LIMIT = 128
GENERATED_HEADER = "-- Generated by scripts/build_station_artifacts.py; do not edit by hand."


@dataclass(frozen=True)
class ClientCountryFragment:
    country_key: str
    country_name: str
    fragment_index: int
    global_index: int
    rows: tuple[tuple[str, str], ...]
    single_file_sent_size: int


@dataclass
class ClientChunkBin:
    fragments: list[ClientCountryFragment]
    sent_size: int = 0
    json_size: int = 0

    @property
    def country_keys(self) -> set[str]:
        return {fragment.country_key for fragment in self.fragments}


@dataclass(frozen=True)
class ClientChunk:
    name: str
    text: str
    bin: ClientChunkBin

    @property
    def country_fragments(self) -> tuple[tuple[str, int], ...]:
        return tuple(
            (fragment.country_key, fragment.fragment_index)
            for fragment in self.bin.fragments
        )

    def __iter__(self) -> Iterator[str]:
        yield self.name
        yield self.text


def builtin_id_prefix(country_key: str) -> str:
    return f"builtin:{country_key}:"


def station_id_suffix(station_id: str, country_key: str) -> str:
    prefix = builtin_id_prefix(country_key)
    if not station_id.startswith(prefix):
        raise ValueError(
            f"station id {station_id!r} does not start with expected prefix {prefix!r}"
        )

    return station_id[len(prefix) :]


def lua_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def format_country_key(country_key: str) -> str:
    value = country_key.replace("_", " ")
    return re.sub(
        r"([a-zA-Z])([a-zA-Z']*)",
        lambda m: m.group(1).upper() + m.group(2).lower(),
        value,
    )


def validate(stations: list[dict[str, str]]) -> None:
    seen: set[str] = set()
    for index, station in enumerate(stations):
        prefix = f"station[{index}]"
        station_id = station.get("id", "")
        if not ID_RE.match(station_id):
            raise ValueError(f"{prefix} has invalid id: {station_id!r}")
        if len(station_id.encode("utf-8")) > STATION_ID_LIMIT:
            raise ValueError(
                f"{prefix} id exceeds protocol limit of {STATION_ID_LIMIT} bytes: {station_id!r}"
            )
        if station_id in seen:
            raise ValueError(f"{prefix} duplicates id: {station_id!r}")
        seen.add(station_id)

        for field in ("name", "url", "countryKey", "source"):
            if not isinstance(station.get(field), str) or not station[field]:
                raise ValueError(f"{prefix} missing non-empty {field}")

        if not URL_RE.match(station["url"]):
            raise ValueError(f"{prefix} has invalid url: {station['url']!r}")
        if station["source"] != "builtin":
            raise ValueError(f"{prefix} source must be builtin")


def build_server_registry_payload(stations: list[dict[str, str]]) -> dict[str, object]:
    countries: dict[str, dict[str, list[str]]] = {}

    for station in stations:
        country_key = station["countryKey"]
        station_suffix = station_id_suffix(station["id"], country_key)
        countries.setdefault(country_key, {})[station_suffix] = [
            station["name"],
            station["url"],
        ]

    return {
        "version": 1,
        "countries": countries,
    }


def build_client_country_index(stations: list[dict[str, str]]) -> list[dict[str, object]]:
    countries: list[dict[str, object]] = []
    by_country: dict[str, dict[str, object]] = {}

    for station in stations:
        country_key = station["countryKey"]
        country = by_country.get(country_key)
        if country is None:
            country = {
                "key": country_key,
                "name": format_country_key(country_key),
                "stations": [],
                "chunks": [],
            }
            by_country[country_key] = country
            countries.append(country)

        country["stations"].append(station)

    return countries


def build_client_country_rows(stations: list[dict[str, str]]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []

    for country in build_client_country_index(stations):
        country_key = str(country["key"])
        country_name = str(country["name"])
        station_rows: list[list[str]] = []

        for station in country["stations"]:
            station_rows.append([
                station_id_suffix(station["id"], country_key),
                station["name"],
            ])

        rows.append(
            {
                "country_key": country_key,
                "country_name": country_name,
                "stations": station_rows,
            }
        )

    return rows


def client_chunk_payload(country_blocks: list[list[object]]) -> dict[str, object]:
    return {
        "version": 1,
        "countries": country_blocks,
    }


def render_client_chunk_file(country_blocks: list[list[object]]) -> PayloadFile:
    return render_payload_return_file(
        header=GENERATED_HEADER,
        kind="client_station_catalog_chunk",
        payload=client_chunk_payload(country_blocks),
    )


def _client_chunk_fits(rendered: PayloadFile) -> bool:
    return (
        rendered.lua_sent_lzma_size <= CLIENT_SENT_LZMA_TARGET
        and rendered.json_size <= CLIENT_STATION_CHUNK_MAX_JSON_BYTES
    )


def _validate_client_chunk_file(label: str, rendered: PayloadFile) -> None:
    validate_client_sent_file(label, rendered)
    if rendered.json_size > CLIENT_STATION_CHUNK_MAX_JSON_BYTES:
        raise ValueError(
            f"{label} JSON payload is {rendered.json_size} bytes, exceeding "
            f"{CLIENT_STATION_CHUNK_MAX_JSON_BYTES} byte runtime decode limit"
        )


def fragment_to_country_block(fragment: ClientCountryFragment) -> list[object]:
    return [
        fragment.country_key,
        fragment.country_name,
        [list(row) for row in fragment.rows],
    ]


def split_country_to_fragments(
    country: dict[str, object],
    global_index_start: int,
) -> list[ClientCountryFragment]:
    country_key = str(country["country_key"])
    country_name = str(country["country_name"])
    rows = list(country["stations"])
    fragments: list[ClientCountryFragment] = []
    offset = 0
    fragment_index = 0
    global_index = global_index_start

    while offset < len(rows):
        lo = 1
        hi = len(rows) - offset
        best = 0
        best_size = 0

        while lo <= hi:
            mid = (lo + hi) // 2
            block = [
                country_key,
                country_name,
                rows[offset : offset + mid],
            ]
            rendered = render_client_chunk_file([block])

            if _client_chunk_fits(rendered):
                best = mid
                best_size = rendered.lua_sent_lzma_size
                lo = mid + 1
            else:
                hi = mid - 1

        if best <= 0:
            row = rows[offset]
            rendered = render_client_chunk_file([[country_key, country_name, [row]]])
            raise ValueError(
                f"single station row for {country_key!r} ({row[0]!r}, {row[1]!r}) "
                f"is {rendered.lua_sent_lzma_size} compressed bytes and "
                f"{rendered.json_size} JSON bytes"
            )

        fragments.append(
            ClientCountryFragment(
                country_key=country_key,
                country_name=country_name,
                fragment_index=fragment_index,
                global_index=global_index,
                rows=tuple(tuple(row) for row in rows[offset : offset + best]),
                single_file_sent_size=best_size,
            )
        )

        offset += best
        fragment_index += 1
        global_index += 1

    return fragments


def build_client_fragments(country_rows: list[dict[str, object]]) -> list[ClientCountryFragment]:
    fragments: list[ClientCountryFragment] = []
    global_index = 0

    for country in country_rows:
        country_fragments = split_country_to_fragments(country, global_index)
        fragments.extend(country_fragments)
        global_index += len(country_fragments)

    return fragments


def render_bin(bin_: ClientChunkBin) -> PayloadFile:
    ordered = sorted(bin_.fragments, key=lambda fragment: fragment.global_index)
    blocks = [fragment_to_country_block(fragment) for fragment in ordered]
    return render_client_chunk_file(blocks)


def pack_client_fragments(fragments: list[ClientCountryFragment]) -> list[ClientChunkBin]:
    bins: list[ClientChunkBin] = []

    ordered_fragments = sorted(
        fragments,
        key=lambda fragment: (
            -fragment.single_file_sent_size,
            fragment.country_key,
            fragment.fragment_index,
        ),
    )

    for fragment in ordered_fragments:
        best_index: int | None = None
        best_size: int | None = None
        best_rendered: PayloadFile | None = None

        for index, bin_ in enumerate(bins):
            if fragment.country_key in bin_.country_keys:
                continue

            candidate = ClientChunkBin(fragments=[*bin_.fragments, fragment])
            rendered = render_bin(candidate)
            size = rendered.lua_sent_lzma_size

            if _client_chunk_fits(rendered) and (
                best_size is None or size > best_size
            ):
                best_index = index
                best_size = size
                best_rendered = rendered

        if best_index is None:
            singleton = ClientChunkBin(fragments=[fragment])
            rendered = render_bin(singleton)
            if not _client_chunk_fits(rendered):
                raise ValueError(
                    f"client fragment {fragment.country_key}#{fragment.fragment_index} "
                    f"is {rendered.lua_sent_lzma_size} compressed bytes and "
                    f"{rendered.json_size} JSON bytes"
                )
            singleton.sent_size = rendered.lua_sent_lzma_size
            singleton.json_size = rendered.json_size
            bins.append(singleton)
        else:
            bins[best_index].fragments.append(fragment)
            if best_rendered is None:
                best_rendered = render_bin(bins[best_index])
            bins[best_index].sent_size = best_rendered.lua_sent_lzma_size
            bins[best_index].json_size = best_rendered.json_size

    return bins


def build_client_chunks(stations: list[dict[str, str]]) -> list[ClientChunk]:
    country_rows = build_client_country_rows(stations)
    fragments = build_client_fragments(country_rows)
    bins = pack_client_fragments(fragments)

    chunks: list[ClientChunk] = []
    for index, bin_ in enumerate(bins, 1):
        chunk_name = f"catalog_{index:03d}.lua"
        rendered = render_bin(bin_)
        _validate_client_chunk_file(chunk_name, rendered)
        chunks.append(ClientChunk(name=chunk_name, text=rendered.text, bin=bin_))

    return chunks


def build_client_chunk_index(
    stations: list[dict[str, str]],
    chunks: list[ClientChunk],
) -> list[dict[str, object]]:
    countries = build_client_country_index(stations)
    by_country = {str(country["key"]): country for country in countries}
    refs: dict[str, list[tuple[int, str]]] = {
        str(country["key"]): [] for country in countries
    }

    for chunk in chunks:
        seen_in_chunk: set[str] = set()

        for fragment in chunk.bin.fragments:
            if fragment.country_key in seen_in_chunk:
                raise ValueError(
                    f"{chunk.name} contains country {fragment.country_key!r} more than once"
                )
            seen_in_chunk.add(fragment.country_key)
            refs[fragment.country_key].append((fragment.fragment_index, chunk.name))

    for country_key, country_refs in refs.items():
        chunk_names: list[str] = []
        seen_names: set[str] = set()

        for _fragment_index, chunk_name in sorted(country_refs):
            if chunk_name in seen_names:
                raise ValueError(
                    f"{country_key!r} has duplicate chunk reference {chunk_name}"
                )
            seen_names.add(chunk_name)
            chunk_names.append(chunk_name)

        by_country[country_key]["chunks"] = chunk_names

    return countries


def render_client_index(stations: list[dict[str, str]], chunks: list[ClientChunk]) -> str:
    countries = build_client_chunk_index(stations, chunks)
    country_entries: list[str] = []
    for country in countries:
        chunk_list = ",".join(f'"{chunk}"' for chunk in country["chunks"])
        country_entries.append(
            f'{{"{lua_string(str(country["key"]))}",'
            f'"{lua_string(str(country["name"]))}",'
            f"{len(country['stations'])},"
            f"{{{chunk_list}}}}}"
        )

    lines = [
        GENERATED_HEADER,
        "rRadio = rRadio or {}",
        "rRadio.generated = rRadio.generated or {}",
        (
            "rRadio.generated.clientCatalog="
            f"{{stationCount={len(stations)},countries={{{','.join(country_entries)}}}}}"
        ),
        "return rRadio.generated.clientCatalog",
        "",
    ]
    text = "\n".join(lines)
    validate_client_sent_file(str(CLIENT_PATH.relative_to(REPO_ROOT)), text)
    return text


def render_server(stations: list[dict[str, str]]) -> str:
    payload = build_server_registry_payload(stations)
    rendered = render_server_registry_file(header=GENERATED_HEADER, payload=payload)
    if rendered.json_size > SERVER_REGISTRY_MAX_JSON_BYTES:
        raise ValueError(
            f"server station registry JSON payload is {rendered.json_size} bytes, "
            f"exceeding {SERVER_REGISTRY_MAX_JSON_BYTES} byte runtime decode limit"
        )
    return rendered.text


def write_server(stations: list[dict[str, str]]) -> int:
    if SERVER_GENERATED_DIR.exists():
        for old_chunk in SERVER_GENERATED_DIR.glob("stations_*.lua"):
            old_chunk.unlink()
        for old_chunk in SERVER_GENERATED_DIR.glob("builtin_*.lua"):
            old_chunk.unlink()

    SERVER_PATH.write_text(render_server(stations), encoding="utf-8")
    return 1


def write_client(stations: list[dict[str, str]]) -> int:
    CLIENT_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for old_chunk in CLIENT_GENERATED_DIR.glob("catalog_*.lua"):
        old_chunk.unlink()

    chunks = build_client_chunks(stations)
    for chunk in chunks:
        (CLIENT_GENERATED_DIR / chunk.name).write_text(chunk.text, encoding="utf-8")

    CLIENT_PATH.write_text(render_client_index(stations, chunks), encoding="utf-8")
    return len(chunks)


def main() -> int:
    stations = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    stations.sort(key=lambda station: (station["countryKey"], station["name"], station["id"]))
    validate(stations)
    write_server(stations)
    client_chunk_count = write_client(stations)
    print(
        f"Generated {len(stations)} station artifacts in "
        f"1 compressed server registry and {client_chunk_count} client chunks"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
