#!/usr/bin/env python3
"""Verify rRadio clean-rebuild runtime contract constraints."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from generated_payloads import (
    CLIENT_SENT_LZMA_HARD_LIMIT,
    CLIENT_SENT_LZMA_TARGET,
    lua_sent_lzma_size,
    parse_payload_lua_wrapper,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
LUA_ROOT = REPO_ROOT / "lua"
STATION_SOURCE = REPO_ROOT / "data" / "stations.json"
SERVER_ARTIFACT = LUA_ROOT / "rradio" / "server" / "stations" / "builtin_registry.lua"
CLIENT_CATALOG_INDEX = LUA_ROOT / "rradio" / "client" / "stations" / "builtin_catalog.lua"
CLIENT_CHUNKS = LUA_ROOT / "rradio" / "client" / "stations" / "generated"
CLIENT_LOCALES = LUA_ROOT / "rradio" / "client" / "lang"
LOCALE_SOURCE = REPO_ROOT / "data" / "locales"
STATION_ID_RE = re.compile(r"^[A-Za-z0-9_\-:.]+$")
STATION_GENERATED_HEADER = "-- Generated by scripts/build_station_artifacts.py; do not edit by hand."
LOCALE_GENERATED_HEADER = "-- Generated by scripts/build_locale_artifacts.py; do not edit by hand."
LOCALE_SECTIONS = {"ui", "themes", "countries"}

FORBIDDEN_PATTERNS = {
    "rRadio.v2 namespace": re.compile(r"\brRadio\.v2\b"),
    "v2 runtime path": re.compile(r"rradio/v2|rradio\\v2"),
    "StationURL networked var": re.compile(r"\bStationURL\b"),
    "misspelled VehicleClassOverides": re.compile(r"\bVehicleClassOverides\b"),
    "legacy play net string": re.compile(r'"rRadio\.PlayStation"'),
    "legacy stop net string": re.compile(r'"rRadio\.StopStation"'),
    "legacy volume net string": re.compile(r'"rRadio\.SetRadioVolume"'),
    "legacy status net string": re.compile(r'"rRadio\.UpdateRadioStatus"'),
    "legacy open menu net string": re.compile(r'"rRadio\.OpenMenu"'),
    "legacy vehicle animation net string": re.compile(r'"rRadio\.PlayVehicleAnimation"'),
    "legacy custom stations net string": re.compile(r'"rRadio\.CustomStationsUpdate"'),
    "legacy list custom stations net string": re.compile(r'"rRadio\.ListCustomStations"'),
    "legacy add custom station net string": re.compile(r'"rRadio\.AddCustomStation"'),
    "legacy remove custom station net string": re.compile(r'"rRadio\.RemoveCustomStation"'),
    "legacy persistence net string": re.compile(
        r'"rRadio\.(SetPersistent|RemovePersistent|SendPersistentConfirmation)"'
    ),
    "legacy language hook": re.compile(r'"LanguageUpdated"'),
    "legacy theme hook": re.compile(r'"ThemeChanged"'),
    "legacy rRadio.sv namespace": re.compile(r"\brRadio\.sv\b"),
    "legacy rRadio.cl namespace": re.compile(r"\brRadio\.cl\b"),
    "legacy rRadio.interface namespace": re.compile(r"\brRadio\.interface\b"),
    "legacy rRadio.utils namespace": re.compile(r"\brRadio\.utils\b"),
    "legacy rRadio.status runtime enum": re.compile(r"\brRadio\.status\b"),
    "legacy constants.Status runtime enum": re.compile(r"\bconstants\.Status\b"),
    "legacy Status NW field": re.compile(r"\bNW\.Status\b"),
    "legacy IsPlaying NW field": re.compile(r"\bIsPlaying\b"),
    "server-side fake playing timer": re.compile(r"rRadio\.SetPlaying_"),
    "reference runtime include": re.compile(r"references/v1|references\\v1"),
}

ALLOWED_DIRECT_NET_STRING_FILES = {
    LUA_ROOT / "rradio" / "shared" / "net" / "protocol.lua",
}

ALLOWED_CLIENT_PLAYURL_FILES = {
    LUA_ROOT / "rradio" / "client" / "audio" / "manager.lua",
}

REQUIRED_FILES = [
    LUA_ROOT / "autorun" / "sh_rradio_init.lua",
    LUA_ROOT / "rradio" / "shared" / "core" / "settings_catalog.lua",
    LUA_ROOT / "rradio" / "shared" / "net" / "protocol.lua",
    LUA_ROOT / "rradio" / "shared" / "stations" / "schema.lua",
    LUA_ROOT / "rradio" / "shared" / "core" / "generated_payload.lua",
    LUA_ROOT / "rradio" / "server" / "radio" / "service.lua",
    LUA_ROOT / "rradio" / "server" / "stations" / "registry.lua",
    LUA_ROOT / "rradio" / "client" / "net" / "handlers.lua",
    LUA_ROOT / "rradio" / "client" / "audio" / "manager.lua",
    LUA_ROOT / "entities" / "rammel_boombox" / "shared.lua",
    LUA_ROOT / "entities" / "rammel_boombox_gold" / "shared.lua",
]

CONFIG_DEFAULTS = LUA_ROOT / "rradio" / "shared" / "core" / "config.lua"
CONFIG_SCHEMA = LUA_ROOT / "rradio" / "shared" / "core" / "config_schema.lua"
SETTINGS_CATALOG = LUA_ROOT / "rradio" / "shared" / "core" / "settings_catalog.lua"
CONFIG_SCHEMA_EXCLUDED_TOP_LEVEL = {
    "AnimationDefaultOn",
    "ClientConVars",
    "FrameSize",
    "MenuScale",
    "UI",
    "VehicleHint",
}
CONFIG_SCHEMA_NESTED_TABLES = {
    "Boombox",
    "Crossfade",
    "GoldenBoombox",
    "Occlusion",
    "Sounds",
    "VehicleRadio",
}
CONFIG_SCHEMA_MANAGED_TOP_LEVEL_TABLES: set[str] = set()
CONFIG_SCHEMA_EXCLUDED_IDS = {
    "Boombox.SourceOffset",
    "GoldenBoombox.SourceOffset",
}
RADIO_CONFIG_FIELDS = {
    "Volume",
    "FullVolumeDistance",
    "MaxHearingDistance",
    "DistanceFalloffExponent",
    "RetryAttempts",
    "RetryDelay",
}


def iter_runtime_files() -> list[Path]:
    paths: list[Path] = []
    for root in (LUA_ROOT, REPO_ROOT / "scripts", REPO_ROOT / "data"):
        if root.exists():
            paths.extend(path for path in root.rglob("*") if path.is_file())
    return sorted(paths)


def should_scan_for_forbidden_patterns(path: Path) -> bool:
    if path.suffix not in {".lua", ".py", ".json"}:
        return False
    if path == STATION_SOURCE or LOCALE_SOURCE in path.parents:
        return False
    if CLIENT_CHUNKS in path.parents or CLIENT_LOCALES in path.parents:
        return False
    return True


def check_client_sent_size(path: Path) -> list[str]:
    if not path.exists():
        return [f"missing client-sent generated file: {path.relative_to(REPO_ROOT)}"]

    sent_size = lua_sent_lzma_size(path.read_text(encoding="utf-8"))
    errors: list[str] = []
    if sent_size > CLIENT_SENT_LZMA_HARD_LIMIT:
        errors.append(
            f"{path.relative_to(REPO_ROOT)} exceeds AddCSLuaFile hard limit: {sent_size}"
        )
    if sent_size > CLIENT_SENT_LZMA_TARGET:
        errors.append(
            f"{path.relative_to(REPO_ROOT)} exceeds compressed target: {sent_size}"
        )

    return errors


def count_server_stations() -> tuple[int, list[str]]:
    errors: list[str] = []
    if not SERVER_ARTIFACT.exists():
        return 0, ["missing server station artifact"]

    try:
        wrapper = parse_payload_lua_wrapper(SERVER_ARTIFACT)
    except ValueError as exc:
        return 0, [f"server station artifact decode failed: {exc}"]

    if wrapper.kind != "server_station_registry":
        errors.append("server station artifact has invalid payload kind")

    payload = wrapper.payload
    if payload.get("version") != 1:
        errors.append("server station artifact has invalid payload version")

    countries = payload.get("countries")
    if not isinstance(countries, dict):
        return 0, [*errors, "server station artifact missing countries object"]

    count = 0
    for country_key, stations in countries.items():
        if not isinstance(stations, dict):
            errors.append(f"server country {country_key!r} is not an object")
            continue
        count += len(stations)

    return count, errors


def count_client_stations() -> tuple[int, list[str]]:
    errors: list[str] = []
    count = 0
    if not CLIENT_CHUNKS.exists():
        return 0, ["missing client generated station chunk directory"]

    for chunk in sorted(CLIENT_CHUNKS.glob("catalog_*.lua")):
        errors.extend(check_client_sent_size(chunk))

        try:
            wrapper = parse_payload_lua_wrapper(chunk)
        except ValueError as exc:
            errors.append(f"{chunk.relative_to(REPO_ROOT)} decode failed: {exc}")
            continue

        if wrapper.kind != "client_station_catalog_chunk":
            errors.append(f"{chunk.relative_to(REPO_ROOT)} has invalid payload kind")

        payload = wrapper.payload
        if payload.get("version") != 1:
            errors.append(f"{chunk.relative_to(REPO_ROOT)} has invalid payload version")

        countries = payload.get("countries")
        if not isinstance(countries, list):
            errors.append(f"{chunk.relative_to(REPO_ROOT)} missing countries list")
            continue

        seen_countries: set[str] = set()
        for country_block in countries:
            if not isinstance(country_block, list) or len(country_block) < 3:
                errors.append(f"{chunk.relative_to(REPO_ROOT)} has invalid country block")
                continue

            country_key = country_block[0]
            if isinstance(country_key, str):
                if country_key in seen_countries:
                    errors.append(
                        f"{chunk.relative_to(REPO_ROOT)} contains country {country_key!r} more than once"
                    )
                seen_countries.add(country_key)

            stations = country_block[2]
            if isinstance(stations, list):
                count += len(stations)
            else:
                errors.append(f"{chunk.relative_to(REPO_ROOT)} has invalid station rows")

    return count, errors


def validate_locale_payloads() -> tuple[set[str], list[str]]:
    errors: list[str] = []
    languages: set[str] = set()

    if not CLIENT_LOCALES.exists():
        return languages, ["missing client generated locale directory"]

    for locale in sorted(CLIENT_LOCALES.glob("data_*.lua")):
        errors.extend(check_client_sent_size(locale))

        try:
            wrapper = parse_payload_lua_wrapper(locale)
        except ValueError as exc:
            errors.append(f"{locale.relative_to(REPO_ROOT)} decode failed: {exc}")
            continue

        if wrapper.kind != "locale_chunk":
            errors.append(f"{locale.relative_to(REPO_ROOT)} has invalid payload kind")

        payload = wrapper.payload
        if payload.get("version") != 1:
            errors.append(f"{locale.relative_to(REPO_ROOT)} has invalid payload version")

        locales = payload.get("locales")
        if not isinstance(locales, dict):
            errors.append(f"{locale.relative_to(REPO_ROOT)} missing locales object")
            continue

        for language_key, language_data in locales.items():
            if not isinstance(language_key, str):
                errors.append(f"{locale.relative_to(REPO_ROOT)} has non-string language key")
                continue
            if not isinstance(language_data, dict):
                errors.append(
                    f"{locale.relative_to(REPO_ROOT)} language {language_key!r} is not an object"
                )
                continue

            languages.add(language_key)
            unknown_sections = sorted(set(language_data) - LOCALE_SECTIONS)
            if unknown_sections:
                errors.append(
                    f"{locale.relative_to(REPO_ROOT)} language {language_key!r} has "
                    f"unknown sections: {', '.join(unknown_sections)}"
                )

            for section, rows in language_data.items():
                if section not in LOCALE_SECTIONS:
                    continue
                if not isinstance(rows, dict):
                    errors.append(
                        f"{locale.relative_to(REPO_ROOT)} language {language_key!r} "
                        f"section {section!r} is not an object"
                    )
                    continue
                for key, value in rows.items():
                    if not isinstance(key, str) or not isinstance(value, str):
                        errors.append(
                            f"{locale.relative_to(REPO_ROOT)} language {language_key!r} "
                            f"section {section!r} must map strings to strings"
                        )
                        break

    return languages, errors


def has_generated_header(path: Path, header: str) -> bool:
    if not path.exists():
        return False

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    if not lines:
        return False

    first_line = lines[0]
    return first_line == header


def find_lua_table_block(text: str, table_name: str) -> str | None:
    match = re.search(
        rf"config\.{re.escape(table_name)}\s*=\s*config\.{re.escape(table_name)}\s+or\s+\{{",
        text,
    )
    if not match:
        return None

    start = match.end()
    depth = 1
    index = start
    while index < len(text):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start:index]

        index += 1

    return None


def find_local_lua_table_block(text: str, table_name: str) -> str | None:
    match = re.search(rf"local\s+{re.escape(table_name)}\s*=\s*\{{", text)
    if not match:
        return None

    start = match.end()
    depth = 1
    index = start
    while index < len(text):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start:index]

        index += 1

    return None


def settings_catalog_server_ids() -> set[str]:
    text = SETTINGS_CATALOG.read_text(encoding="utf-8")
    block = find_local_lua_table_block(text, "SERVER_SETTINGS")
    ids: set[str] = set()

    if block:
        ids.update(re.findall(r"\bid\s*=\s*\"([^\"]+)\"", block))

    for match in re.finditer(r"appendRadioConfig\(\s*\"([^\"]+)\"", text):
        prefix = match.group(1)
        ids.update(f"{prefix}.{field}" for field in RADIO_CONFIG_FIELDS)

    sound_block = find_local_lua_table_block(text, "SOUND_SETTINGS")
    if sound_block:
        ids.update(re.findall(r"\bid\s*=\s*\"([^\"]+)\"", sound_block))

    return ids


def config_default_ids() -> set[str]:
    if SETTINGS_CATALOG.exists():
        return settings_catalog_server_ids()

    text = CONFIG_DEFAULTS.read_text(encoding="utf-8")
    ids: set[str] = set()

    for match in re.finditer(r"^config\.([A-Za-z_][A-Za-z0-9_]*)\s*=", text, re.MULTILINE):
        name = match.group(1)
        if name in CONFIG_SCHEMA_EXCLUDED_TOP_LEVEL or name in CONFIG_SCHEMA_NESTED_TABLES:
            continue
        if name in CONFIG_SCHEMA_MANAGED_TOP_LEVEL_TABLES or not find_lua_table_block(text, name):
            ids.add(name)

    for table_name in CONFIG_SCHEMA_NESTED_TABLES:
        block = find_lua_table_block(text, table_name)
        if not block:
            continue

        for key_match in re.finditer(r"^\s+([A-Za-z_][A-Za-z0-9_]*)\s*=", block, re.MULTILINE):
            ids.add(f"{table_name}.{key_match.group(1)}")

    for match in re.finditer(
        r"^config\.([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)\s*=",
        text,
        re.MULTILINE,
    ):
        table_name = match.group(1)
        if table_name not in CONFIG_SCHEMA_NESTED_TABLES:
            continue

        ids.add(f"{table_name}.{match.group(2)}")

    return ids - CONFIG_SCHEMA_EXCLUDED_IDS


def config_schema_ids() -> set[str]:
    text = CONFIG_SCHEMA.read_text(encoding="utf-8")
    if "GetServerSettings" in text and "settingsCatalog" in text:
        return settings_catalog_server_ids()

    ids = set(re.findall(r"add\(\s*[\r\n]+\s+\"([^\"]+)\"", text))

    for match in re.finditer(r"addRadioConfig\(\s*\"([^\"]+)\"", text):
        prefix = match.group(1)
        ids.update(f"{prefix}.{field}" for field in RADIO_CONFIG_FIELDS)

    return ids


def check_config_schema_coverage() -> list[str]:
    errors: list[str] = []
    if not SETTINGS_CATALOG.exists():
        errors.append("missing settings catalog")

    expected = config_default_ids()
    actual = config_schema_ids()
    missing = sorted(expected - actual)
    extra = sorted(actual - expected)

    if missing:
        errors.append("config schema missing managed defaults: " + ", ".join(missing))
    if extra:
        errors.append("config schema has entries without managed defaults: " + ", ".join(extra))

    if SETTINGS_CATALOG.exists():
        config_text = CONFIG_DEFAULTS.read_text(encoding="utf-8")
        schema_text = CONFIG_SCHEMA.read_text(encoding="utf-8")
        if "GetConfigSettings" not in config_text or "settingsCatalog" not in config_text:
            errors.append("config defaults are not derived from settings catalog")
        if "GetClientConVarDefinitions" not in config_text or "settingsCatalog" not in config_text:
            errors.append("client convars are not derived from settings catalog")
        if "GetServerSettings" not in schema_text or "settingsCatalog" not in schema_text:
            errors.append("config schema is not derived from settings catalog")

    return errors


def main() -> int:
    errors: list[str] = []

    for path in REQUIRED_FILES:
        if not path.exists():
            errors.append(f"missing required file: {path.relative_to(REPO_ROOT)}")

    errors.extend(check_config_schema_coverage())

    if (LUA_ROOT / "rradio" / "v2").exists():
        errors.append("forbidden runtime folder exists: lua/rradio/v2")

    for path in iter_runtime_files():
        if path == Path(__file__).resolve():
            continue

        if not should_scan_for_forbidden_patterns(path):
            continue

        text = path.read_text(encoding="utf-8", errors="replace")
        for label, pattern in FORBIDDEN_PATTERNS.items():
            if pattern.search(text):
                errors.append(f"{path.relative_to(REPO_ROOT)} contains {label}")

        if LUA_ROOT / "rradio" / "client" in path.parents and re.search(
            r":SetNW(?:Bool|Entity|Float|Int|String)?\s*\(",
            text,
        ):
            errors.append(f"{path.relative_to(REPO_ROOT)} mutates networked vars from a client module")

        direct_net_string = re.search(r"net\.(?:Start|Receive)\s*\(\s*\"rRadio\.", text)
        if direct_net_string and path not in ALLOWED_DIRECT_NET_STRING_FILES:
            errors.append(f"{path.relative_to(REPO_ROOT)} uses a direct rRadio net string literal")

        client_play_url = re.search(r"sound\.PlayURL\s*\(", text)
        if client_play_url and path not in ALLOWED_CLIENT_PLAYURL_FILES:
            errors.append(f"{path.relative_to(REPO_ROOT)} starts arbitrary client URL playback")

        if LUA_ROOT / "rradio" / "client" / "ui" in path.parents:
            if path.name != "actions.lua" and "rRadio.client.net.handlers" in text:
                errors.append(f"{path.relative_to(REPO_ROOT)} bypasses the UI action facade")
            if re.search(r"net\.(?:Start|Receive)\s*\(", text):
                errors.append(f"{path.relative_to(REPO_ROOT)} writes net messages directly from UI")

        for hook_match in re.finditer(r"hook\.(?:Run|Call)\s*\(\s*\"([^\"]+)\"", text):
            hook_name = hook_match.group(1)
            if not hook_name.startswith("rRadio_"):
                errors.append(f"{path.relative_to(REPO_ROOT)} emits unprefixed hook {hook_name!r}")

    if not STATION_SOURCE.exists():
        errors.append("missing canonical station JSON")
    else:
        stations = json.loads(STATION_SOURCE.read_text(encoding="utf-8"))
        station_ids = [station.get("id") for station in stations]
        if len(station_ids) != len(set(station_ids)):
            errors.append("canonical station JSON contains duplicate IDs")

        for station_id in station_ids:
            if not isinstance(station_id, str) or not STATION_ID_RE.match(station_id):
                errors.append(f"canonical station JSON contains invalid station ID: {station_id!r}")
                break

        source_count = len(stations)
        server_count, server_errors = count_server_stations()
        client_count, chunk_errors = count_client_stations()
        errors.extend(server_errors)
        errors.extend(chunk_errors)

        if source_count != server_count:
            errors.append(f"server station artifact has {server_count} stations, expected {source_count}")
        if source_count != client_count:
            errors.append(f"client station chunks have {client_count} stations, expected {source_count}")

    if LOCALE_SOURCE.exists():
        source_locale_count = len(list(LOCALE_SOURCE.glob("*.json")))
        locale_languages, locale_errors = validate_locale_payloads()
        errors.extend(locale_errors)
        if len(locale_languages) != source_locale_count:
            errors.append(
                f"generated locale chunks have {len(locale_languages)} languages, "
                f"expected {source_locale_count}"
            )
    else:
        errors.append("missing canonical locale JSON directory")

    for generated_file in [SERVER_ARTIFACT, CLIENT_CATALOG_INDEX]:
        if generated_file.exists() and not has_generated_header(generated_file, STATION_GENERATED_HEADER):
            errors.append(f"{generated_file.relative_to(REPO_ROOT)} is missing generated-file header")

    if CLIENT_CATALOG_INDEX.exists():
        errors.extend(check_client_sent_size(CLIENT_CATALOG_INDEX))

    if CLIENT_CHUNKS.exists():
        for chunk in sorted(CLIENT_CHUNKS.glob("catalog_*.lua")):
            if not has_generated_header(chunk, STATION_GENERATED_HEADER):
                errors.append(f"{chunk.relative_to(REPO_ROOT)} is missing generated-file header")

    if CLIENT_LOCALES.exists():
        for locale in sorted(CLIENT_LOCALES.glob("data_*.lua")):
            if not has_generated_header(locale, LOCALE_GENERATED_HEADER):
                errors.append(f"{locale.relative_to(REPO_ROOT)} is missing generated-file header")

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        print(f"FAILED: {len(errors)} runtime contract error(s)")
        return 1

    print("PASSED: runtime contract checks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
